### ISSUE TITLE
[CRITICAL] Noneunhashable type: 'list' - Error when having a percent sign '%' in the configuration in a list

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1021]
In GitLab by @abaer-kit on Apr 24, 2023, 18:04

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v4.0.76 (local installation)

### Which task has issues? Where is the log

`autosubmit create`

### Summary

For a project, in which the configuration contains a list and in this list one item contains a percent sign '%' (see MWE below), the configuration will fail with the following error:
```
[ERROR] Trace: unhashable type: 'list'
Traceback (most recent call last):
  File "/home/andreas/.local/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 644, in parse_args
    Autosubmit._init_logs(args, args.logconsole, args.logfile, expid)
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 787, in _init_logs
    as_conf.reload(force_load=True)
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 1337, in reload
    starter_conf = self.unify_conf(starter_conf, self.load_config_file(starter_conf, Path(filename)))
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 574, in load_config_file
    return self.unify_conf(current_folder_data,self.deep_normalize(new_file.data))
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 642, in unify_conf
    self.dynamic_variables = list(set(self.dynamic_variables))
TypeError: unhashable type: 'list'
 [CRITICAL] Noneunhashable type: 'list'
Unhandled error: If you see this message, please report it in Autosubmit's GitLab project
```

### Steps to reproduce

1. Create a new expid (`autosubmit expid -local -dm -d "Test for a bug with % in configuration files."`)
2. Add some entries to the configuration files (e.g. in `expdef_<expid>.yml`):
```
CUSTOM:
  - 'a'
  - 'b'
  - 'c%d'
```
3. Run `autosubmit create <expid>`

### What is the current bug behavior?

See summary above. Furthermore, this bug prevents the use of autosubmit variable substitution in such entries.

### What is the expected correct behavior?

Either this should not raise any problem, or a proper error should be raised, if percent signs are not allowed in this case.

### Relevant logs and/or screenshots

In this case, autosubmit does not produce a log file, only the output on the console (see summary).

### Any further information

This error seems to be independent of the level of nesting of sections in the config file.

If I can provide any further input, please let me know.

Best,
Andreas

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 25, 2023, 08:54

Hello @abaer-kit , 

I think we never had any % sign inside the templates(aside of the placeholders). I'll look at it

**Comment by kinow** [comment]
In GitLab by @abaer-kit on Apr 25, 2023, 09:08

Hello @dbeltrankyl ,

my aim was actually to use a placeholder, but this also does not work in the list. Looking for the cause of the problem, I realized that it seems to be the % sign.
