### ISSUE TITLE
CHECK = False not working

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#103]
In GitLab by @dmanubens on Apr 14, 2016, 13:30

cb5b8dc02110a3e69998824daa1e49c6f944b86b

is wrong: omit CHECK is not working.

see: http://stackoverflow.com/questions/21732123/convert-true-false-value-read-from-file-to-boolean
bool('True') and bool('False') always return True because strings 'True' and 'False' are not empty.

The error in Autosubmit 3.2 is as follows:

```
[CRITICAL] Unhandled exception on Autosubmit: [Errno 2] No such file or directory: '/home/Earth/dmanuben/debug/autosubmit/a007/proj/project/created.sh'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.2.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.2.0-py2.7.egg/autosubmit/autosubmit.py", line 286, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.2.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.2.0-py2.7.egg/autosubmit/autosubmit.py", line 575, in run_experiment
    joblist.check_scripts(as_conf)
  File "/shared/earth/software/autosubmit/3.2.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.2.0-py2.7.egg/autosubmit/job/job_list.py", line 560, in check_scripts
    if not job.check_script(as_conf, self.parameters):
  File "/shared/earth/software/autosubmit/3.2.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.2.0-py2.7.egg/autosubmit/job/job.py", line 658, in check_script
    template_content = self.update_content(as_conf.get_project_dir())
  File "/shared/earth/software/autosubmit/3.2.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.2.0-py2.7.egg/autosubmit/job/job.py", line 611, in update_content
    template_file = open(os.path.join(project_dir, self.file), 'r')
IOError: [Errno 2] No such file or directory: '/home/Earth/dmanuben/debug/autosubmit/a007/proj/project/created.sh'
```

**Comment by kinow** [comment]
In GitLab by @dmanubens on Apr 25, 2016, 17:37

Status changed to closed by commit ba517e3ef1634684c9bcaa340e9056db6800226b
