### ISSUE TITLE
[enhancement] autosubmit delete shouldn't print a traceback when experiment does not exist

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1046]
At the moment, running `autosubmit delete whatsmyname` will result in the following:

```bash
(autosubmit4) kinow@ranma:~/Development/python/workspace/autosubmit4-config-parser$ autosubmit delete whatsmyname
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 648, in parse_args
    Autosubmit._init_logs(args, args.logconsole, args.logfile, expid)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 870, in _init_logs
    raise AutosubmitCritical("Experiment does not exist", 7012)
log.log.AutosubmitCritical:  
 [CRITICAL] Experiment does not exist [eCode=7012]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

The traceback, the troubleshooting URL, the error code, the CRITICAL message, are all irrelevant to the user calling that. I believe the only important piece of information here is “Experiment does not exist”. It would be simpler to just return an exit code `1` and display that message.

Compare with other workflow manager tools:

1. Cylc

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/6057cd81d91f97a44417a988c34ba22e/image.png)

2. Nextflow

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/d5c6c0c5aff9eec7fa96b46324446079/image.png)

3. Autosubmit

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/c47c1c815826eed0d6ce506210bb26de/image.png)

**Comment by dbeltrankyl** [comment]
Simple issue, but one must be careful with the autosubmit delete fyi @VindeeR , @isimo00

**Comment by dbeltrankyl** [comment]
Recently, we agreed to show the full traceback in general ( cc: @kinow ) because people are not using `autosubmit -LC "debug"`, which requires the AS support person to go to the experiment and see the full log.

 This is only shown once, so there is no harm. I'm not sure if it is worth doing something there, and would rather do other issues

**Comment by dbeltrankyl** [comment]
Maybe you implement the issue about showing the full traceback always instead? Not sure if we created one.. as the discussion was through slack

**Comment by dbeltrankyl** [comment]
ah yes, this one: https://github.com/BSC-ES/autosubmit/issues/2342

**Comment by kinow** [comment]
From today's meeting: the solution for this issue is to stop logging errors when the deletion of experiment worked. But for #2342 we want to actually print the traceback when any error happens 👍

**Comment by kinow** [comment]
Done in #3171
