### ISSUE TITLE
pkl corrupted

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#105]
In GitLab by @fmassonn on Apr 25, 2016, 18:36

If you get the following error message:

[CRITICAL] Unhandled exception on Autosubmit: 
Traceback (most recent call last):
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 258, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 547, in run_experiment
    joblist = pickle.load(open(filename, 'rw'))
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError

your pickle file may be corrupted. You may want to re-create the experiment, recover it, and launch it again.

**Comment by kinow** [comment]
In GitLab by @fmassonn on Apr 27, 2016, 13:58

After discussion with @dmanubens it looks like a possible cause for this problem is the following.

When reading from/writing to the pkl file, you have to make sure that new information is not added meanwhile. One way to avoid this is to set the time between two updates of autosubmit with the HPC *larger*:

SAFETYSLEEPTIME = 120

(in autosubmit_${your_exp}.conf)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 12:09

closed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 12:09

related to #91
