### ISSUE TITLE
Missing details and malformed databases

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1054]
In GitLab by @mcastril on Jun 8, 2023, 19:28

( This is a template for bug reports. Please fill in the relevant information and delete the rest. )

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v3.14.0 and v3.15.0b

### Expid affected(If applicable)

a632, a64f, a64g, a64i...

### Summary

There's a possible issue with the DDBB population of some new experiments.

`as_metadata.db` might be broken

### Steps to reproduce

Create an experiment, copy of `a632`

### What is the current bug behavior?

I wanted to do an animation of a workflow running with the GUI. I saw my experiment was never seen as `ACTIVE`. Then I also saw some information is missing in the experiment details in the GUI:

![Screenshot_from_2023-06-08_19-16-10](https://earth.bsc.es/gitlab/es/autosubmit/uploads/ea125d328ff649ba062e914fd9d1553a/Screenshot_from_2023-06-08_19-16-10.png)

![Screenshot_from_2023-06-08_19-16-24](https://earth.bsc.es/gitlab/es/autosubmit/uploads/c424dc3bca7f0e98dbe371a3ef5f6f0a/Screenshot_from_2023-06-08_19-16-24.png)

As you can see, there's no user and HPC in the first case and no HPC in the second case. Although you can see both fields when entering the experiment view.

This could be more of a problem on the GUI side, what do you think @ jberlin ?

```
10629|rgaratac|2023-06-08 12:42:29.524016|https://earth.bsc.es/gitlab/es/auto-caliope.git|CMAQv5.4|marenostrum4
10631|yruprich|2023-06-08 15:03:44.132765|https://earth.bsc.es/gitlab/es/auto-ecearth3.git|auto-nemo|marenostrum4
10632|mcastril|2023-06-08 18:38:46.185593|||
10633|mcastril|2023-06-08 18:42:47.303258|||
10634|mcastril|2023-06-08 18:56:00.976642|||
10635|mcastril|2023-06-08 19:11:52.709248|||
```

There are no data in the `details` table in `ecearth.db`. So maybe the information in the experiments view is taken from another place, like the distributed database.

I ran the worker `populate_details.py` in case of issues, but I saw no change after running it. 

Concerning the experiment never becoming `active`, I saw that, actually, my experiment is not listed as running in `as_metadata.db -> experiment_status`.

```
883|a517|RUNNING|0|2023-01-03-15:15:02
9474|a5fy|RUNNING|0|2023-01-24-12:40:05
9867|a5l8|RUNNING|0|2023-02-06-19:40:07
10020|a5o9|RUNNING|0|2023-02-15-14:05:02
10073|a5pm|RUNNING|0|2023-02-27-15:40:04
10081|a5pt|RUNNING|0|2023-02-27-18:35:02
10098|a5q9|RUNNING|0|2023-03-02-14:40:02
10306|a5vp|RUNNING|0|2023-04-05-14:45:03
10475|a607|RUNNING|0|2023-05-10-11:05:03
10002|a5nr|RUNNING|0|2023-06-02-00:55:02
10035|a5ok|RUNNING|0|2023-06-02-00:00:06
9034|a550|RUNNING|0|2023-06-02-00:55:03
9675|a5k2|RUNNING|0|2023-06-02-17:40:05
10480|a60c|RUNNING|0|2023-06-02-17:40:04
10331|a5we|RUNNING|0|2023-06-04-21:55:02
7180|a3w5|RUNNING|0|2023-06-02-00:00:09
10029|a5oe|RUNNING|0|2023-06-02-00:00:05
10217|a5tf|RUNNING|0|2023-06-01-22:15:03
10057|a5p6|RUNNING|0|2023-06-01-22:40:05
9654|a5jk|RUNNING|0|2023-06-08-18:00:23
10299|a5vi|RUNNING|0|2023-06-02-17:40:02
9209|a59j|RUNNING|0|2023-06-08-18:30:30
9206|a59g|RUNNING|0|2023-06-07-23:46:00
9255|t0a8|RUNNING|0|2023-06-01-19:45:03
9265|t0al|RUNNING|0|2023-06-01-20:25:02
10533|a61q|RUNNING|0|2023-06-01-21:20:03
4710|a2in|RUNNING|0|2023-06-07-19:30:33
7785|a4a4|RUNNING|0|2023-06-07-19:45:17
8942|a52i|RUNNING|0|2023-06-08-03:30:24
10361|a5x8|RUNNING|0|2023-06-02-00:00:06
9929|a5ms|RUNNING|0|2023-06-03-03:00:47
6874|a3pd|RUNNING|0|2023-06-08-09:00:21
6673|a3lx|RUNNING|0|2023-06-02-16:10:06
10591|a63b|RUNNING|0|2023-06-06-11:35:02
10592|a63c|RUNNING|0|2023-06-02-10:00:03
10518|a61b|RUNNING|0|2023-06-07-14:20:02
10311|a5vu|RUNNING|0|2023-06-02-11:00:06
9479|a5g3|RUNNING|0|2023-06-08-10:30:37
10593|a63d|RUNNING|0|2023-06-02-11:00:03
8996|a53y|RUNNING|0|2023-06-02-11:00:08
```

Some experiments have been updated quite lately (18:00), though.

I tried running the `populate_running_experiments.py` worker, but there's an issue:

```
Traceback (most recent call last):
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/workers/populate_running_experiments.py", line 13, in <module>
    main()
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/workers/populate_running_experiments.py", line 9, in main
    ExperimentStatusManager().update_running_experiments()
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/history/experiment_status_manager.py", line 73, in update_running_experiments
    self._experiments_updated.add(ExperimentStatus(expid).set_as_running().exp_id)              
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/history/experiment_status.py", line 60, in set_as_running
    self.manager.create_experiment_status_as_running(exp_row)
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/history/database_managers/experiment_status_db_manager.py", line 85, in create_experiment_status_as_running
    self.create_exp_status(experiment.id, experiment.name, Models.RunningStatus.RUNNING)
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/history/database_managers/experiment_status_db_manager.py", line 135, in create_exp_status
    return self.insert_statement_with_arguments(self._as_times_file_path, statement, arguments)
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/history/database_managers/database_manager.py", line 138, in insert_statement_with_arguments
    cursor.execute(statement, arguments) 
sqlite3.DatabaseError: database disk image is malformed
```

I cannot create a dump to restore the DDBB because it belongs to `eadmin`:

```
-rw-r--r-- 1 eadmin Earth 569251477 Sep 13  2022 as_times.db.dump
-rwxrwxrwx 1 eadmin Earth 522308608 Sep 13  2022 as_times.db~
-rwxrwxrwx 1 eadmin Earth 630990848 Jun  8 19:24 as_times.db
```

The database continues to be updated by other processes, as you can see. 

There's no active experiment in the GUI starting by a64* so probably only experiments up to a certain id are updated.

CC @kinow

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 9, 2023, 18:00

`cat as_times.db.dump | sqlite3 as_times.new.db`

results in:

`-rw-r--r--  1 mcastril Earth 591M jun  9 17:58 as_times.new.db`

This is bigger, but clearly there's missing information in the dump

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 9, 2023, 18:04

Trying a new dump...

`sqlite3 as_times.db .dump > as_times.miguel.db.dum`

No errors...

The dump is taking 648M, same as yours... This is strange

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 9, 2023, 18:06

Again, same size as with `as_times.new.db` in https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1054#note_218560

```
-rw-r--r--  1 mcastril Earth 648M jun  9 18:02 as_times.miguel.db.dump
-rw-r--r--  1 mcastril Earth 591M jun  9 18:05 as_times.miguel.db
```

I am losing 11M and there's no error

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 9, 2023, 18:07

In my case, what gave the error was the creation step

> cat as_times.db.dump | sqlite3 as_times.db

Perhaps it was a filesystem error?

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 9, 2023, 18:07

Probably... because the `details` does not exist error didn't have much sense. I am performing a diff between the original and my new db

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 9, 2023, 19:08

I printed the output of a `SELECT *` in every table in different files, for `as_times.db` and `as_times.miguel.db`. The result is identical, as it should be as we did a dump...

I tend to think that the 11MB difference is due to corruption...

I copied the DDBBs locally and used an updated `sqlite3` client to run `.recover`.

`as_times.miguel.db.recover` cannot be opened after (the process is probably interrupted, but no errors are shown).

We'd probably need more sophisticated tools to know the exact problem with the DDBB

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 13, 2023, 10:58

@dbeltrankyl @kinow @ jberlin 

I am concerned about this issue because it's affecting the production GUI (some experiments cannot be seen as active).

Oddly, some new experiments are updated as active.

If we cannot do a complete check, I would dump the database and replace it to check if the worker can complete its job.

```
(base) webadmin@ bscesweb04:~> /srv/www/htdocs/AutosubmitAPI/venv27/bin/python -W ignore /srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/workers/populate_running_experiments.py
Traceback (most recent call last):
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/workers/populate_running_experiments.py", line 13, in <module>
    main()
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/workers/populate_running_experiments.py", line 9, in main
    ExperimentStatusManager().update_running_experiments()
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/history/experiment_status_manager.py", line 73, in update_running_experiments
    self._experiments_updated.add(ExperimentStatus(expid).set_as_running().exp_id)              
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/history/experiment_status.py", line 60, in set_as_running
    self.manager.create_experiment_status_as_running(exp_row)
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/history/database_managers/experiment_status_db_manager.py", line 85, in create_experiment_status_as_running
    self.create_exp_status(experiment.id, experiment.name, Models.RunningStatus.RUNNING)
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/history/database_managers/experiment_status_db_manager.py", line 135, in create_exp_status
    return self.insert_statement_with_arguments(self._as_times_file_path, statement, arguments)
  File "/srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/history/database_managers/database_manager.py", line 138, in insert_statement_with_arguments
    cursor.execute(statement, arguments) 
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 13, 2023, 13:06

So, then the action would be to try again `> cat as_times.db.dump | sqlite3 as_times.db` ?

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 13, 2023, 14:26

@dbeltrankyl I already did this step: https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1054#note_218565

The problem is that the resulting DDBB has 11MB less size than the current, corrupted one.

This could result from corruption, but can we be sure that we are not losing any data? 

What I could do is to compare the tables (with SELECT * from) in both tables (production and newly generated) and they match

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 13, 2023, 15:42

If we have no alternative to check it, could you generate a new DDBB and do the replacement Dani?

I would like to check the worker before I leave today.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 13, 2023, 16:26

I generated the db with my user , it currently has 592mb which is 10M less

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 13, 2023, 16:27

Same as mine. Can you backup the production one and do the swap?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 13, 2023, 16:28

Already did. The backup is called as_times.db_backup_13_jun

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 13, 2023, 16:31

Also, the missing MB could be due to empty pages that don't contain any info

see https://dba.stackexchange.com/questions/106132/why-does-an-sqlite3-dump-and-restore-result-in-a-smaller-database-file-size

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 13, 2023, 17:33

Thank you Dani, I run the worker and no error there! I gonna do one test.

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 13, 2023, 17:36

I started an experiment (that previously was not seen as active) and now it's seen as active.

@f-macchia

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 24, 2023, 13:33

mentioned in issue autosubmit_api#34
