### ISSUE TITLE
`autosubmit clean --project $expid` broken due to can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1075]
Hello @dbeltrankyl,

### Autosubmit Version

latest

### Expid affected(If applicable)
NA

### Which task has issues? Where is the log(If applicable)
NA

### Summary

Running `autosubmit clean --project $expid` on a Git project results in the error

```bash
(autosubmit4) bdepaula@ bsces107921:~/Development/python/workspace/autosubmit$ autosubmit clean --project a00m
Autosubmit is running with 4.0.0b

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Registering commit SHA...
Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 2681, in clean
    autosubmit_config.set_git_project_commit(autosubmit_config)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 1740, in set_git_project_commit
    Log.debug("Project branch is: " + project_branch)
TypeError: can only concatenate str (not "bytes") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 653, in parse_args
    return Autosubmit.clean(args.expid, args.project, args.plot, args.stats)
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 2697, in clean
    raise AutosubmitCritical("Couldn't clean this experiment, check if you have the correct permissions", 7012,
log.log.AutosubmitCritical:  
[ERROR] Trace: can only concatenate str (not "bytes") to str
 [CRITICAL] Couldn't clean this experiment, check if you have the correct permissions [eCode=7012]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

### Steps to reproduce

```bash
$ autosubmit expid \
    --HPC "local" \
    --description "Autosubmit mHM test domains" \
    --minimal_configuration \
    --git_as_conf conf/bootstrap \
    --git_repo https://github.com/kinow/auto-mhm-test-domains.git \
    --git_branch master
$ autosubmit create a00m
$ autosubmit clean --project a00m
```

### What is the current bug behavior?

```bash
(autosubmit4) bdepaula@ bsces107921:~/Development/python/workspace/autosubmit$ autosubmit clean --project a00m
Autosubmit is running with 4.0.0b

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Registering commit SHA...
Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 2681, in clean
    autosubmit_config.set_git_project_commit(autosubmit_config)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 1740, in set_git_project_commit
    Log.debug("Project branch is: " + project_branch)
TypeError: can only concatenate str (not "bytes") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 653, in parse_args
    return Autosubmit.clean(args.expid, args.project, args.plot, args.stats)
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 2697, in clean
    raise AutosubmitCritical("Couldn't clean this experiment, check if you have the correct permissions", 7012,
log.log.AutosubmitCritical:  
[ERROR] Trace: can only concatenate str (not "bytes") to str
 [CRITICAL] Couldn't clean this experiment, check if you have the correct permissions [eCode=7012]

```

### What is the expected correct behavior?

(What you should see instead)

### Relevant logs and/or screenshots(if applicable)

(Paste any relevant logs - use code blocks (```) to format console output, logs, and code, as
it's very hard to read otherwise.)

### Any other relevant information(if applicable)

()

**Comment by kinow** [comment]
This is blocking #929 as it's not possible to retrieve the git commit to include in the workflow metadata (at least not without running `git` command again to retrieve the commit.)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 6, 2023, 14:30

marked this issue as related to #929

**Comment by kinow** [comment]
WIP fix: https://earth.bsc.es/gitlab/ces/autosubmit4-config-parser/-/merge_requests/2

**Comment by kinow** [comment]
@edgano assigning this one for you, as you are working on the AS config parser issue. I think once that's fixed and merged there, and we have a new release, you can just update the config-parser version in Autosubmit, and then try the command above (which you can actually try now/before working, to confirm we still have the issue...).

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 5, 2024, 12:33

https://github.com/BSC-ES/autosubmit-config-parser/pull/33 updating ref link

**Comment by isimo00** [comment]
Hi @kinow, need help with this?

**Comment by kinow** [comment]
If you'd like to take over this one, no objections from me! (I'm half-way through the review of the mail notification :slightly_smiling_face: ). Thanks Irene!!!

**Comment by isimo00** [comment]
Unable to reproduce issue... Going through the related issues to investigate.

```
autosubmit clean --project a006
Yaml file /home/isimomun/.config/autosubmit/platforms.yml not found
Autosubmit admin user: eadmin is not set
Autosubmit is running with 4.1.12

Checking configuration files...
Yaml file /home/isimomun/.config/autosubmit/platforms.yml not found
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Registering commit SHA...
 [CRITICAL] Couldn't clean this experiment, check if you have the correct permissions [eCode=7012]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

**Comment by kinow** [comment]
@isimo00 did you use a Git project in your experiment? The last time I tried, I was able to reproduce it. If you confirm you used a Git project, then I will check the code to see if ti was solved (the linked PR had a partial fix, so the code changed would be around that area): https://github.com/BSC-ES/autosubmit-config-parser/pull/33#issuecomment-2428615902

Thanks!

**Comment by isimo00** [comment]
@kinow I did, I executed the commands you indicated in the issue to reproduce the issue:

> ```
> $ autosubmit expid \
>     --HPC "local" \
>     --description "Autosubmit mHM test domains" \
>     --minimal_configuration \
>     --git_as_conf conf/bootstrap \
>     --git_repo https://github.com/kinow/auto-mhm-test-domains.git \
>     --git_branch master
> $ autosubmit create a00m
> $ autosubmit clean --project a00m
> ```

**Comment by kinow** [comment]
@isimo00 

>Unable to reproduce issue... Going through the related issues to investigate.

Sorry, I was too hasty in replying before. Did you test with `master` branch? I checked `master`, `pip install -e .`, then:

```bash
(autosubmit4) kinow@ranma:~/Development/python/workspace/autosubmit$ autosubmit expid \
    --HPC "local" \
    --description "Autosubmit mHM test domains" \
    --minimal_configuration \
    --git_as_conf conf/bootstrap \
    --git_repo https://github.com/kinow/auto-mhm-test-domains.git \
    --git_branch master
/home/kinow/Development/python/micromamba/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: 
...
Experiment a033 created
(autosubmit4) kinow@ranma:~/Development/python/workspace/autosubmit$ autosubmit -lc DEBUG clean --project a033
/home/kinow/Development/python/micromamba/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.1.12')
Yaml file /home/kinow/.config/autosubmit/platforms.yml not found
Autosubmit admin user: eadmin is not set
Autosubmit is running with 4.1.12

Checking configuration files...
Yaml file /home/kinow/.config/autosubmit/platforms.yml not found
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Registering commit SHA...
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 2876, in clean
    autosubmit_config.set_git_project_commit(autosubmit_config)
  File "/home/kinow/Development/python/workspace/autosubmit-config-parser/autosubmitconfigparser/config/configcommon.py", line 2131, in set_git_project_commit
    Log.debug("Project branch is: " + project_branch)
TypeError: can only concatenate str (not "bytes") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/bin/autosubmit", line 36, in main
    return_value = Autosubmit.parse_args()
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 725, in parse_args
    return Autosubmit.clean(args.expid, args.project, args.plot, args.stats)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 2892, in clean
    raise AutosubmitCritical("Couldn't clean this experiment, check if you have the correct permissions", 7012,
log.log.AutosubmitCritical:  

Trace: can only concatenate str (not "bytes") to str
 [CRITICAL] Couldn't clean this experiment, check if you have the correct permissions [eCode=7012]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

**Comment by isimo00** [comment]
@kinow I was on the master branch and I did reinstall before trying to reproduce it. Just in case, I repeated it again and I still don't get the error.

```console
(test_as) isimomun@bsces110916:~/repos/autosubmit$ git branch
  3.15.0-branch
  iss1435
  iss1442
* master
(test_as) isimomun@bsces110916:~/repos/autosubmit$ pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/isimomun/repos/autosubmit
  Preparing metadata (setup.py) ... done
Requirement already satisfied: autosubmitconfigparser==1.0.76 in /home/isimomun/.local/lib/python3.10/site-packages (from autosubmit==4.1.12) (1.0.76)
...
Requirement already satisfied: multidict<7.0,>=4.5 in /home/isimomun/.local/lib/python3.10/site-packages (from aiohttp>=3.6.2->tuspy->bioblend->gxformat2>=0.11.0->galaxy2cwl->rocrate==0.*->autosubmit==4.1.12) (6.1.0)
Installing collected packages: autosubmit
  Attempting uninstall: autosubmit
    Found existing installation: autosubmit 4.1.12
    Uninstalling autosubmit-4.1.12:
      Successfully uninstalled autosubmit-4.1.12
  Running setup.py develop for autosubmit
Successfully installed autosubmit
(test_as) isimomun@bsces110916:~/repos/autosubmit$  autosubmit expid \
    --HPC "local" \
    --description "Autosubmit mHM test domains" \
    --minimal_configuration \
    --git_as_conf conf/bootstrap \
    --git_repo https://github.com/kinow/auto-mhm-test-domains.git \
    --git_branch master
Autosubmit is running with 4.1.12
The new experiment "a008" has been registered.
Generating folder structure...
Experiment folder: /home/isimomun/autosubmit/a008
Generating config files...
Experiment a008 created
(test_as) isimomun@bsces110916:~/repos/autosubmit$ autosubmit create a008
Yaml file /home/isimomun/autosubmit/a008/proj/git_project/conf/bootstrap not found
Autosubmit admin user: eadmin is not set
Autosubmit is running with 4.1.12
Autosubmit admin user: eadmin is not set
Preparing .lock file to avoid multiple instances with same expid.
Cloning master https://github.com/kinow/auto-mhm-test-domains.git into /home/isimomun/autosubmit/a008/proj
Cloning into 'git_project'...
remote: Enumerating objects: 495, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 495 (delta 64), reused 55 (delta 48), pack-reused 404 (from 1)
Receiving objects: 100% (495/495), 37.13 MiB | 13.75 MiB/s, done.
Resolving deltas: 100% (279/279), done.

Checking configuration files...
Yaml file /home/isimomun/.config/autosubmit/platforms.yml not found
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Loading parameters...

Creating the jobs list...
Loading JobList
[WARNING] File /home/isimomun/autosubmit/a008/pkl/job_list_a008.pkl does not exist. 
[WARNING] File /home/isimomun/autosubmit/a008/pkl/job_list_a008_backup.pkl does not exist. 
[WARNING] Joblist will be created from scratch due: [Errno 2] No such file or directory: '/home/isimomun/autosubmit/a008/pkl/job_list_a008_backup.pkl'
Creating jobs...
Adding dependencies to the graph..
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...

Saving the jobs list...

Plotting the jobs list...
Plotting...
Plot created at /home/isimomun/autosubmit/a008/plot/a008_20250115_1010.pdf
Writing status txt...
Status txt created at <_io.TextIOWrapper name='/home/isimomun/autosubmit/a008/status/a008_20250115_1010.txt' mode='w+' encoding='UTF-8'>

Job list created successfully
[WARNING] Remember to MODIFY the MODEL config files!
(test_as) isimomun@bsces110916:~/repos/autosubmit$ autosubmit clean --project a008
Yaml file /home/isimomun/.config/autosubmit/platforms.yml not found
Autosubmit admin user: eadmin is not set
Autosubmit is running with 4.1.12

Checking configuration files...
Yaml file /home/isimomun/.config/autosubmit/platforms.yml not found
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Registering commit SHA...
 [CRITICAL] Couldn't clean this experiment, check if you have the correct permissions [eCode=7012]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

**Comment by kinow** [comment]
HI @isimo00 ! So, I think you got the error, but you cannot **see** the error :laughing: 

If our verbosity was similar to other workflow managers (cylc, ecflow, nextflow, and cwltool, for instance) where an error is clearly displayed to the user in the logs, and/or a good error message, then you'd have seen the error before - https://github.com/BSC-ES/autosubmit/issues/1428

> ```
>  [CRITICAL] Couldn't clean this experiment, check if you have the correct permissions [eCode=7012]
> ```

As is, Autosubmit logs to the console (what you see when you run a subcommand like `create` or `clean`) in `INFO` IIRC, and in `DEBUG` in your log files.

Check your `~/autosubmit/a008/tmp/ASLOGS`, and in your most recent run out/err logs (last files in `ls -lart`) you should be able to see the error.

Otherwise, you can do what I did above, and run `autosubmit -lc DEBUG $subcomand $args`. The `lc` stands for log-console (or level-console?), and that way you should see that you are in fact reproducing the error… it's just AS is not displaying that to the user.

Let me know if that works!

p.s. the main reason why I prefer to be clear to users about what went wrong, is that it's common even for AS experienced users to forget about the different log levels, so users would get frustrated, maybe create unnecessary issues for us, etc., etc., whereas showing the error by default would be a lot simpler/faster -- IMHO

**Comment by isimo00** [comment]
@kinow You are right, found the error in the logs. Thanks!

**Comment by isimo00** [comment]
Issue comes from the config parser. It has been fixed, but the `autosubmit clean` command still fails due to other legacy mismanagements in the config parser script. Working on that!

**Comment by kinow** [comment]
Thanks Irene! Very likely this code was broken for a while but was just never used and tested 😅 Let's fix this and add some test to prevent this from happening again. Thanks!! 🙇

**Comment by dbeltrankyl** [comment]
Hello! 

I'm revising all the issues and assigning new milestones because it has been a while since the last time.

I'll set this to v4.1.13
