### ISSUE TITLE
`autosubmit clean --project $expid` broken due to can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1075]
Hello @dbeltrankyl,

### Autosubmit Version

latest

### Expid affected(If applicable)
NA

### Which task has issues? Where is the log(If applicable)
NA

### Summary

Running `autosubmit clean --project $expid` on a Git project results in the error

```bash
(autosubmit4) bdepaula@ bsces107921:~/Development/python/workspace/autosubmit$ autosubmit clean --project a00m
Autosubmit is running with 4.0.0b

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Registering commit SHA...
Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 2681, in clean
    autosubmit_config.set_git_project_commit(autosubmit_config)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 1740, in set_git_project_commit
    Log.debug("Project branch is: " + project_branch)
TypeError: can only concatenate str (not "bytes") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 653, in parse_args
    return Autosubmit.clean(args.expid, args.project, args.plot, args.stats)
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 2697, in clean
    raise AutosubmitCritical("Couldn't clean this experiment, check if you have the correct permissions", 7012,
log.log.AutosubmitCritical:  
[ERROR] Trace: can only concatenate str (not "bytes") to str
 [CRITICAL] Couldn't clean this experiment, check if you have the correct permissions [eCode=7012]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

### Steps to reproduce

```bash
$ autosubmit expid \
    --HPC "local" \
    --description "Autosubmit mHM test domains" \
    --minimal_configuration \
    --git_as_conf conf/bootstrap \
    --git_repo https://github.com/kinow/auto-mhm-test-domains.git \
    --git_branch master
$ autosubmit create a00m
$ autosubmit clean --project a00m
```

### What is the current bug behavior?

```bash
(autosubmit4) bdepaula@ bsces107921:~/Development/python/workspace/autosubmit$ autosubmit clean --project a00m
Autosubmit is running with 4.0.0b

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Registering commit SHA...
Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 2681, in clean
    autosubmit_config.set_git_project_commit(autosubmit_config)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 1740, in set_git_project_commit
    Log.debug("Project branch is: " + project_branch)
TypeError: can only concatenate str (not "bytes") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 653, in parse_args
    return Autosubmit.clean(args.expid, args.project, args.plot, args.stats)
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 2697, in clean
    raise AutosubmitCritical("Couldn't clean this experiment, check if you have the correct permissions", 7012,
log.log.AutosubmitCritical:  
[ERROR] Trace: can only concatenate str (not "bytes") to str
 [CRITICAL] Couldn't clean this experiment, check if you have the correct permissions [eCode=7012]

```

### What is the expected correct behavior?

(What you should see instead)

### Relevant logs and/or screenshots(if applicable)

(Paste any relevant logs - use code blocks (```) to format console output, logs, and code, as
it's very hard to read otherwise.)

### Any other relevant information(if applicable)

()

**Comment by kinow** [comment]
This is blocking #929 as it's not possible to retrieve the git commit to include in the workflow metadata (at least not without running `git` command again to retrieve the commit.)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 6, 2023, 14:30

marked this issue as related to #929

**Comment by kinow** [comment]
WIP fix: https://earth.bsc.es/gitlab/ces/autosubmit4-config-parser/-/merge_requests/2

**Comment by kinow** [comment]
@edgano assigning this one for you, as you are working on the AS config parser issue. I think once that's fixed and merged there, and we have a new release, you can just update the config-parser version in Autosubmit, and then try the command above (which you can actually try now/before working, to confirm we still have the issue...).

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 5, 2024, 12:33

https://github.com/BSC-ES/autosubmit-config-parser/pull/33 updating ref link
