### ISSUE TITLE
Using autosubmit with a remote git repo

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1086]
In GitLab by @hrosegalb on Jul 12, 2023, 15:12

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v.4.0.79

### Summary

I'm experimenting with using autosubmit with a gitlab repo, rather than local files. I've tried to model what I'm doing off of the autosubmit docs here: https://autosubmit.readthedocs.io/en/master/userguide/set_and_share_the_configuration/index.html#advanced-configuration-full-dummy-example-reproducible

I have created a remote repo that contains two subfolders: `as_conf/` (where the autosubmit configs are) and `shell_scripts/` (which contain the bash scripts that I want autosubmit to run on the cluster). Ideally, what I would like to do is give autosubmit the repo and have it overwrite its default config files with the configs in the repo and then run the shell scripts on the CTE-AMD cluster. Repo can be found here: https://gitlab.bsc.es/lang-tech-unit/autosubmit-template

I tried to create a new expid using the following command:

```
$ autosubmit expid -H AMD -repo https://gitlab.bsc.es/lang-tech-unit/autosubmit-template -b main -conf as_conf -d "Testing creating an experiment with git remote repo"

Autosubmit is running with 4.0.79
The new experiment "a00m" has been registered.
Generating folder structure...
Experiment folder: /home/hgalbrai/autosubmit/a00m
Generating config files...
Experiment a00m created
```

This created a new experiment id but didn't populate expdef.yml with any of the information given in the command. I then manually entered the following information into `expdef_a00m.yml`:

```
DEFAULT:
  EXPID: "a00m"
  HPCARCH: "AMD"
  CUSTOM_CONFIG: "%PROJDIR%/as_conf"
EXPERIMENT:
  DATELIST: "20000101"
  MEMBERS: "fc0"
  CHUNKSIZEUNIT: month
  CHUNKSIZE: "4"
  NUMCHUNKS: "2"
  CHUNKINI: ''
  CALENDAR: standard
PROJECT:
  PROJECT_TYPE: "git"
  PROJECT_DESTINATION: 'git_project'
GIT:
  PROJECT_ORIGIN: 'https://gitlab.bsc.es/lang-tech-unit/autosubmit-template'
  PROJECT_BRANCH: 'main'
  PROJECT_COMMIT: ''
  PROJECT_SUBMODULES: ''
  FETCH_SINGLE_BRANCH: True
SVN:
  PROJECT_URL: ''
  PROJECT_REVISION: ''
LOCAL:
  PROJECT_PATH: ''
PROJECT_FILES:
  FILE_PROJECT_CONF: ''
  FILE_JOBS_CONF: ''
  JOB_SCRIPTS_TYPE: ''
RERUN:
  RERUN: FALSE
  RERUN_JOBLIST: ''
```

I then ran `$ autosubmit refresh a00m` and got the following error:

```
Autosubmit is running with 4.0.79

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Traceback (most recent call last):
  File "/home/hgalbrai/.pyenv/versions/autosubmit_env/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 701, in parse_args
    return Autosubmit.refresh(args.expid, args.model_conf, args.jobs_conf)
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 3862, in refresh
    as_conf.show_messages()
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 457, in show_messages
    raise AutosubmitCritical(message, 7014)
log.log.AutosubmitCritical:  
 [CRITICAL] On Configuration files:
Critical Issues on [Expdef] config file:
[Default] Main platform is not defined! check if [HPCARCH = AMD] has any typo
 [eCode=7014]
```

It's giving an error because the AMD architecture isn't defined, but it would be defined if autosubmit would download the config files from the remote repo.

I guess my questions are:
1. How are you supposed to connect a git repo to autosubmit?
2. Is it absolutely necessary to clone the repo locally? If so, then what is the point of having the option of using a git repo in autosubmit?

**Comment by kinow** [comment]
Hi @hrosegalb !

I will start answering the questions here little by little :thumbsup: 

>I tried to create a new expid using the following command:

Thanks a lot for the detailed report. I ran the same commands, and got the same result as you did. Took me some minutes to realize what was going on. I noticed the issue after seeing this in your `PROJECT` settings.

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/292a28b3c524a4fc0e2ff08d8d4409a9/image.png)

This project type set to none means that you have a dummy project. This is due to an known bug in the current version of Autosubmit, with a fix to be released soon, sorry: https://earth.bsc.es/gitlab/es/autosubmit/-/merge_requests/347

To fix that part manually you have to set this in your `$expid/conf/expdef_$expid.yml` file, replacing the existing keys:

```yaml
PROJECT:
  # Type of the project.
  PROJECT_TYPE: git
  # Folder to hold the project sources.
  PROJECT_DESTINATION: ''
GIT:
  PROJECT_ORIGIN: 'https://gitlab.bsc.es/lang-tech-unit/autosubmit-template.git'
  PROJECT_BRANCH: 'main'
  PROJECT_COMMIT: ''
  PROJECT_SUBMODULES: ''
  FETCH_SINGLE_BRANCH: true
```

After that `autosubmit create $expid` or `autosubmit refresh $expid` should clone your project, and fail with a message like

```bash
(autosubmit4) bdepaula@ bsces107921:~$ autosubmit create a000
/home/bdepaula/mambaforge/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.0.0b0')
Autosubmit is running with 4.0.0b
Preparing .lock file to avoid multiple instances with same expid.
Cloning main https://gitlab.bsc.es/lang-tech-unit/autosubmit-template.git into /home/bdepaula/autosubmit/a000/proj
Cloning into 'autosubmit-template'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 19 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (19/19), 6.53 KiB | 3.27 MiB/s, done.

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Loading parameters...

Creating the jobs list...
Creating jobs...
Loading JobList
Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4528, in create
    prev_job_list = Autosubmit.load_job_list(
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 5785, in load_job_list
    job_list.generate(date_list, as_conf.get_member_list(), as_conf.get_num_chunks(), as_conf.get_chunk_ini(),
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 228, in generate
    self._create_jobs(dic_jobs, priority,default_job_type, jobs_data)
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 891, in _create_jobs
    dic_jobs.read_section(section, priority, default_job_type, jobs_data)
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/job/job_dict.py", line 75, in read_section
    self._create_jobs_once(section, priority, default_job_type, jobs_data,splits)
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/job/job_dict.py", line 162, in _create_jobs_once
    job = self.build_job(section, priority, None, None, None, default_job_type, jobs_data, -1)
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/job/job_dict.py", line 386, in build_job
    raise AutosubmitCritical("Platform does not exists, check the value of %JOBS.{0}.PLATFORM% = {1} parameter".format(job.section,job.platform_name),7000,"List of platforms: {0} ".format(self.experiment_data["PLATFORMS"].keys()) )
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 671, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4678, in create
    raise AutosubmitCritical(e.message, e.code, e.trace)
log.log.AutosubmitCritical:  
[ERROR] Trace: List of platforms: dict_keys(['MARENOSTRUM4', 'MARENOSTRUM_ARCHIVE', 'TRANSFER_NODE', 'TRANSFER_NODE_BSCEARTH000', 'BSCEARTH000', 'NORD3', 'ECMWF-XC40']) 
 [CRITICAL] Platform does not exists, check the value of %JOBS.REMOTE_SETUP.PLATFORM% = AMD parameter [eCode=7000]
```

That still fails, but confirms that the project type and Git details are being used correctly. (next comment coming with the next item)

**Comment by kinow** [comment]
Hi @hrosegalb 

>I then ran `$ autosubmit refresh a00m` and got the following error:
>It's giving an error because the AMD architecture isn't defined, but it would be defined if autosubmit would download the config files from the remote repo.
>
>I guess my questions are:
>
>1. How are you supposed to connect a git repo to autosubmit?

I believe you are using the correct approach to connect a git repo to autosubmit. I would blame it on our docs that need to be improved to give better guidance to newcomers :slight_smile: 

>Is it absolutely necessary to clone the repo locally? If so, then what is the point of having the option of using a git repo in autosubmit?

Not manually, running `git` commands. You should be able to use `autosubmit create` the first time, and then `autosubmit refresh` as commits are pushed to the git repo/branch.

I tried a few things, and I think I got a configuration that should match what you expected, more or less? Here's the MR: https://gitlab.bsc.es/lang-tech-unit/autosubmit-template/-/merge_requests/1

Let us know if that works.

Have a good weekend! :wave: 

Bruno

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 11, 2024, 11:08

Was this solved? @kinow

**Comment by kinow** [comment]
Yes, I think this was solved a long time ago, although not sure if there was other communication over email or Slack or in person. Closing this, thanks Dani!
