### ISSUE TITLE
KeyError on Slurm Header Template

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1088]
In GitLab by @manuel-g-castro on Jul 13, 2023, 11:14

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v3.15.0b(-foss-2015a-Python-2.7.9)

### Expid affected(If applicable)

a667

### Summary

Upon inspecting the experiment a667 (which is a copy of @eferre1's a3pg) with the below wrapper settings I get a `KeyError`. I also changed the number of chunks from 25 to 50 (upon request of @mcastril). 

```
[wrapper]
TYPE = multi
WRAPPER_LIST = SIM_WRAPPER,CMOR_WRAPPER

[...]

[CMOR_WRAPPER]
TYPE = horizontal
JOBS_IN_WRAPPER = CMORATM&CMOROCE&CMORTM5&CMORLPJG&SAVEIC&POST
MIN_WRAPPED = 4
MAX_WRAPPED = 6
POLICY = mixed #default is flexible. Values: flexible,strict,mixed
```

### Steps to reproduce

copy a667 and inspect it.

### Relevant logs and/or screenshots(if applicable)

```
Exception in thread data_processing:
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job_packages.py", line 125, in _create_scripts_threaded
    self._job_scripts[jobs[i].name] = jobs[i].create_script(configuration)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1337, in create_script
    template_content = self.update_content(as_conf)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1272, in update_content
    as_conf, snippet, template)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1287, in _get_template_content
    return self._get_paramiko_template(snippet, template)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1296, in _get_paramiko_template
    current_platform.get_header(self), self.executable),
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 1121, in get_header
    '%QUEUE_DIRECTIVE%', self.header.get_queue_directive(job))
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/platforms/headers/slurm_header.py", line 37, in get_queue_directive
    if job.parameters['CURRENT_QUEUE'] == '':
KeyError: 'CURRENT_QUEUE'
Exception in thread data_processing:
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job_packages.py", line 125, in _create_scripts_threaded
    self._job_scripts[jobs[i].name] = jobs[i].create_script(configuration)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1337, in create_script
    template_content = self.update_content(as_conf)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1272, in update_content
    as_conf, snippet, template)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1287, in _get_template_content
    return self._get_paramiko_template(snippet, template)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1296, in _get_paramiko_template
    current_platform.get_header(self), self.executable),
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 1121, in get_header
    '%QUEUE_DIRECTIVE%', self.header.get_queue_directive(job))
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/platforms/headers/slurm_header.py", line 37, in get_queue_directive
    if job.parameters['CURRENT_QUEUE'] == '':
KeyError: 'CURRENT_QUEUE'

Exception in thread data_processing:
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job_packages.py", line 125, in _create_scripts_threaded
    self._job_scripts[jobs[i].name] = jobs[i].create_script(configuration)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1337, in create_script
    template_content = self.update_content(as_conf)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1272, in update_content
    as_conf, snippet, template)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1287, in _get_template_content
    return self._get_paramiko_template(snippet, template)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1296, in _get_paramiko_template
    current_platform.get_header(self), self.executable),
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 1121, in get_header
    '%QUEUE_DIRECTIVE%', self.header.get_queue_directive(job))
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/platforms/headers/slurm_header.py", line 37, in get_queue_directive
    if job.parameters['CURRENT_QUEUE'] == '':
KeyError: 'CURRENT_QUEUE'


Exception in thread data_processing:
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job_packages.py", line 125, in _create_scripts_threaded
    self._job_scripts[jobs[i].name] = jobs[i].create_script(configuration)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1337, in create_script
    template_content = self.update_content(as_conf)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1272, in update_content
    as_conf, snippet, template)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1287, in _get_template_content
    return self._get_paramiko_template(snippet, template)
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/job/job.py", line 1296, in _get_paramiko_template
    current_platform.get_header(self), self.executable),
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 1121, in get_header
    '%QUEUE_DIRECTIVE%', self.header.get_queue_directive(job))
  File "/shared/earth/software/autosubmit/3.15.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.0b0-py2.7.egg/autosubmit/platforms/headers/slurm_header.py", line 37, in get_queue_directive
    if job.parameters['CURRENT_QUEUE'] == '':
KeyError: 'CURRENT_QUEUE'
```

**Comment by kinow** [comment]
In GitLab by @manuel-g-castro on Jul 13, 2023, 11:14

@eferre1 have you ever seen this error? I searched in the repo but couldn't find anything alike.

**Comment by kinow** [comment]
In GitLab by @eferre1 on Jul 13, 2023, 11:29

No, I haven't seen it, but I think that this might be related to #1062.

I don't know if @dbeltrankyl already did some work on that issue, but I had that conflict between the configuration on the `platforms.conf` and the `jobs.conf`, which seeing here the `CURRENT_QUEUE` complain makes me think that it is in fact related and that this error is caused by some modification made for that other issue.

**Comment by kinow** [comment]
In GitLab by @mcastril on Jul 13, 2023, 18:33

Do you have a queue defined for the platform and for the tasks that later are included in the wrapper?

**Comment by kinow** [comment]
In GitLab by @manuel-g-castro on Jul 14, 2023, 09:12

Every platform and all but the SIM jobs have a queue defined. But these SIM jobs shouldn't affect now, since they are not generated during the execution of the `inspect` command.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 26, 2023, 10:12

Hello @manuel-g-castro , 

Which command did you use to get these errors? I can't reproduce it, I've checked your logs, but it doesn't seem registered there. ( `cat * | grep "KeyError" -i` ) I may think it is not registered because the log is not set up inside that thread

**Comment by kinow** [comment]
>Fixing it

Was it fixed, @dbeltrankyl ? (Was searching for another wrapper issue and found this one)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 23, 2023, 09:12

I think so

**Comment by kinow** [comment]
Thanks, will close and we can re-open it later if needed.
