### ISSUE TITLE
Error in both autosubmit 3.2 and 3.3

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#109]
In GitLab by @vsicardi on Apr 27, 2016, 10:45

Hi,
since yesterday I am not able to launch any experiment with autosubmit 3.2. I have the error I copy at the bottom.
The same error happens with autosubmit 3.3.

Please, help me with this. I am stacked and I really need to make some tests.

Thank you in advance for your help

@dmanubens @jvegreg @ jlope2 

Checking configuration files...
autosubmit_a05s.conf OK
platforms_a05s.conf OK
jobs_a05s.conf OK
expdef_a05s.conf  OK
Configuration files OK

2016-04-26 14:53:09,182: radical.saga.cpi    : MainProcess                     : MainThread     : ERROR   : Could not detect shell prompt (timeout) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 288, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
[CRITICAL] Unhandled exception on Autosubmit: Could not detect shell prompt (timeout) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.2.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.2.0-py2.7.egg/autosubmit/autosubmit.py", line 286, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.2.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.2.0-py2.7.egg/autosubmit/autosubmit.py", line 541, in run_experiment
    submitter.load_platforms(as_conf)
  File "/shared/earth/software/autosubmit/3.2.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.2.0-py2.7.egg/autosubmit/platforms/submitter.py", line 68, in load_platforms
    local_platform.service = saga.job.Service("fork://localhost")
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/job/service.py", line 115, in __init__
    url, session, ttype=_ttype)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_job.py", line 504, in init_instance
    self._logger, opts=self.opts)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell.py", line 243, in __init__
    posix=self.posix)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 196, in initialize
    self._initialize_pty (info['pty'], info)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 411, in _initialize_pty
    raise ptye.translate_exception (e)
NoSuccess: Could not detect shell prompt (timeout) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))

**Comment by kinow** [comment]
In GitLab by @dmanubens on Apr 27, 2016, 10:58

hello @vsicardi 
This happened sometimes to me when my workstation was overloaded or very busy.
Could you try to login to `bscesautosubmit01` and run the experiment there?
regards

**Comment by kinow** [comment]
In GitLab by @vsicardi on Apr 27, 2016, 12:16

Thank you for the reply @dmanubens. Even on the machine bscesautosubmit01 I have the same error. My WS is very slow today, in general. Is this, maybe, the problem?
regards

**Comment by kinow** [comment]
In GitLab by @dmanubens on Apr 27, 2016, 14:58

Could you try in other workstations around ?

**Comment by kinow** [comment]
In GitLab by @fmassonn on Apr 27, 2016, 16:02

Hey, I have the same!

2016-04-27 16:01:04,738: radical.saga.cpi    : MainProcess                     : MainThread     : ERROR   : Could not detect shell prompt (timeout) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 288, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
[CRITICAL] Unhandled exception on Autosubmit: Could not detect shell prompt (timeout) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/autosubmit.py", line 283, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/autosubmit.py", line 537, in run_experiment
    submitter.load_platforms(as_conf)
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/platforms/submitter.py", line 70, in load_platforms
    local_platform.service = saga.job.Service("fork://localhost", session=session)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/job/service.py", line 115, in __init__
    url, session, ttype=_ttype)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_job.py", line 504, in init_instance
    self._logger, opts=self.opts)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell.py", line 243, in __init__
    posix=self.posix)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 196, in initialize
    self._initialize_pty (info['pty'], info)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 411, in _initialize_pty
    raise ptye.translate_exception (e)
NoSuccess: Could not detect shell prompt (timeout) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))

**Comment by kinow** [comment]
In GitLab by @fmassonn on Apr 27, 2016, 16:20

I'd like to add that the error seems to have a random component. Now my job went through:

119 of 127 jobs remaining (16:18)

Jobs ready for marenostrum3: 1
Jobs to submit: 1
2016-04-27 16:19:05,090: radical.saga.cpi    : MainProcess                     : MainThread     : ERROR   : Could not detect shell prompt (timeout) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 288, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
2016-04-27 16:19:16,388: radical.saga.cpi    : MainProcess                     : MainThread     : ERROR   : Could not detect shell prompt (timeout) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 288, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
a05v_19790101_fc01_1_CLEAN submitted

**Comment by kinow** [comment]
In GitLab by @dmanubens on Apr 27, 2016, 18:05

hi @fmassonn I think this random behaviour is somehow related to #89 .
We'll have a look, by now I have discovered that it is happening when running various experiments at the same time.
We need to further investigate it. A temporary solution would be to run each experiment in a different machine.

**Comment by kinow** [comment]
In GitLab by @dmanubens on Apr 28, 2016, 13:32

Hey if you have further timeout problems could you try doing this before autosubmit run ? `export SAGA_PTY_SSH_TIMEOUT=60`

**Comment by kinow** [comment]
In GitLab by @vsicardi on Apr 28, 2016, 14:19

Thank you @dmanubens! doing this it works for me.

**Comment by kinow** [comment]
In GitLab by @fmassonn on Apr 28, 2016, 14:58

Hey, yes, that seems to work too for me. Is that something we should add to our bashrc?

**Comment by kinow** [comment]
In GitLab by @fmassonn on Apr 28, 2016, 15:05

Now I have another error:

[CRITICAL] Unhandled exception on Autosubmit: make_dir (a05w) failed: mkdir: cannot create directory `a05w': File exists
 (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_file.py +767 (make_dir)  :  raise saga.NoSuccess ("make_dir (%s) failed: %s" % (tgt_in, out)))
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/autosubmit.py", line 283, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/autosubmit.py", line 607, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, joblist, platforms_to_test):
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/autosubmit.py", line 659, in submit_ready_jobs
    platform.send_file(scriptname)
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/platforms/platform.py", line 140, in send_file
    workdir = self.get_workdir(self.get_files_path())
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/platforms/platform.py", line 169, in get_workdir
    parent = self.get_workdir(os.path.dirname(path))
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/platforms/platform.py", line 170, in get_workdir
    parent.make_dir(new_directory)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/namespace/directory.py", line 197, in make_dir
    return self._adaptor.make_dir (surl.Url (tgt), flags, ttype=ttype)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_file.py", line 767, in make_dir
    raise saga.NoSuccess ("make_dir (%s) failed: %s" % (tgt_in, out))
NoSuccess: make_dir (a05w) failed: mkdir: cannot create directory `a05w': File exists
 (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_file.py +767 (make_dir)  :  raise saga.NoSuccess ("make_dir (%s) failed: %s" % (tgt_in, out)))

**Comment by kinow** [comment]
In GitLab by @dmanubens on Apr 28, 2016, 15:13

Hello @fmassonn I think it is a problem in the localsetup template... The issue and the solution is documented here: es/auto-ecearth3#38

**Comment by kinow** [comment]
In GitLab by @fmassonn on Apr 28, 2016, 15:28

Hey @dmanubens 
I'm troubled: As suggested by the post #38 I added a "/" 

   tar -cvf ../conf/$PROJDEST.tar $PROJDEST/

instead of 

   tar -cvf ../conf/$PROJDEST.tar $PROJDEST

in common.localsetup. But still get the same error (after recreating the experiment):

[CRITICAL] Unhandled exception on Autosubmit: make_dir (a05w) failed: mkdir: cannot create directory `a05w': File exists


François

**Comment by kinow** [comment]
In GitLab by @dmanubens on Apr 28, 2016, 15:31

@fmassonn may be the first attempt created a corrupted a05w folder on your scratch dir at mn (it looks like a file instead of a folder). Could you remove it and retry ?

**Comment by kinow** [comment]
In GitLab by @fmassonn on Apr 28, 2016, 15:33

Hey, @dmanubens , no there is nothing on the HPC yet.

**Comment by kinow** [comment]
In GitLab by @dmanubens on Apr 28, 2016, 15:35

sure ?
`++ rsync -acrv ../conf/model.tar mn-cns96:/gpfs/scratch/cns96/cns96177/a05w`

**Comment by kinow** [comment]
In GitLab by @fmassonn on Apr 28, 2016, 15:36

Sorry man, I was wrongly looking for a folder. I'm trying again.

**Comment by kinow** [comment]
In GitLab by @fmassonn on Apr 28, 2016, 15:43

I have the same result after deleting a05w first. A new a05w (not a folder) was created on HPC.

**Comment by kinow** [comment]
In GitLab by @fmassonn on Apr 28, 2016, 16:03

Yep, I get the same error despite having changed the localsetup.sh

**Comment by kinow** [comment]
In GitLab by @fmassonn on Apr 28, 2016, 17:39

Issue was: there are inconsistencies in the new auto-nemo: some plugins are not loaded in the templates while they should (in particular, in the template common/common.localsetup)

For now, a simple fix is to add "/" after the following line in common.localsetup:

DEST=$SCRATCH_DIR/$HPCPROJ/$HPCUSER/$EXPID/

**Comment by kinow** [comment]
In GitLab by @fmassonn on May 5, 2016, 12:33

I also tried 120 but that made an error that happened even before the error I get with 60. I'm not sure what this export SAGA... means!
François

**Comment by kinow** [comment]
In GitLab by @ macosta on May 5, 2016, 15:53

[TimeOutAutosubmit.txt](https://earth.bsc.es/gitlab/es/autosubmit/uploads/3b64f60a35cf821571a5dbe898299ac7/TimeOutAutosubmit.txt)

a05y: Autosubmit output for a failed example using TIMEOUT=10 and verbose.

**Comment by kinow** [comment]
In GitLab by @ macosta on May 6, 2016, 09:14

Using SAGA_PTY_SSH_TIMEOUT=120 and the experiment has been running fine since yesterday @ cprodhomme @fmassonn @ macosta @obellprat @vsicardi @dmanubens

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jul 8, 2016, 17:16

Milestone removed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 10:52

[Related To saga] I will close this issue due autosubmit  not supporting saga anymore.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 10:52

closed
