### ISSUE TITLE
Autosubmit minimal is not sufficient to `autosubmit create` a project (needs EXPERIMENT)

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1091]
Hello @dbeltrankyl and @mcastril,

### Autosubmit Version

Latest code from Git, 979ec7508e85f142c4eab33846793c5c8e1ee113

### Expid affected(If applicable)

NA

### Which task has issues? Where is the log(If applicable)

NA

### Summary

With the latest code on my local laptop:

```bash
$ autosubmit expid -H local -d test -min -local
```

Then, if I run `autosubmit report $expid` (, then I get the following error:

```bash
Autosubmit is running with 4.0.0b
Autosubmit couldn't retrieve performance metrics.
Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 3368, in report
    job_list = Autosubmit.load_job_list(
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 5808, in load_job_list
    job_list.generate(date_list, as_conf.get_member_list(), as_conf.get_num_chunks(), as_conf.get_chunk_ini(),
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/site-packages/autosubmitconfigparser/config/configcommon.py", line 1829, in get_num_chunks
    return int(self.get_section(['EXPERIMENT', 'NUMCHUNKS']))
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 675, in parse_args
    return Autosubmit.report(args.expid, args.template, args.show_all_parameters, args.folder_path,
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 3452, in report
    raise AutosubmitCritical("Unknown error while reporting the parameters list, likely it is due IO issues",
log.log.AutosubmitCritical:  
[ERROR] Trace: invalid literal for int() with base 10: ''
 [CRITICAL] Unknown error while reporting the parameters list, likely it is due IO issues [eCode=7040]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

### Steps to reproduce

```bash
$ autosubmit expid -H local -d test -min -local
$ autosubmit create a001
$ autosubmit report a001
```

### What is the current bug behavior?

```bash
$ autosubmit create a001
/home/bdepaula/mambaforge/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.0.0b0')
Autosubmit is running with 4.0.0b
Preparing .lock file to avoid multiple instances with same expid.
Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4496, in create
    if not Autosubmit._copy_code(as_conf, expid, as_conf.experiment_data.get("PROJECT",{}).get("PROJECT_TYPE","none"), False):
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4769, in _copy_code
    raise AutosubmitCritical("Empty project path! please change this parameter to a valid one.", 7014)
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 682, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4692, in create
    raise AutosubmitCritical(e.message, e.code, e.trace)
log.log.AutosubmitCritical:  
 [CRITICAL] Empty project path! please change this parameter to a valid one. [eCode=7014]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

### What is the expected correct behavior?

A minimal configuration to be used by a workflow.

### Relevant logs and/or screenshots(if applicable)

(Paste any relevant logs - use code blocks (```) to format console output, logs, and code, as
it's very hard to read otherwise.)

### Any other relevant information(if applicable)

()

**Comment by kinow** [comment]
Note too that even if you add the `EXPERIMENT`, and you have a local experiment (e.g. one that launches docker containers) you still must add a `PLATFORM: anything`. I saw Stella doing it in an experiment, and I had to do the same for an experiment of @edgano. Quite annoying to have to add the climate variables for non-climate experiments, and the random platforms even if not used...

**Comment by kinow** [comment]
mentioned in merge request egarriga/as_rnsseq!1

**Comment by dbeltrankyl** [comment]
This was fixed, I believe. Closing the issue
