### ISSUE TITLE
Nosetests fails in Python 3.10

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1093]
In GitLab by @pablogoitia on Jul 24, 2023, 13:15

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

Autosubmit v4.0.0b

### Summary

The tests execution with the `nosetests` command fails in Python v3.10 due to a lib incompatibility, but not in Python v3.9.

#### Reproduce the working case
`mamba create -n autosubmit4_p3-9 python=3.9`

`mamba activate autosubmit4_p3-9`

`mkdir autosubmit_p3-9`

`cd autosubmit_p3-9/`

`git clone https://earth.bsc.es/gitlab/es/autosubmit.git`

`pip install nose`

`python3 -m 'nose' --exclude=regression  --verbosity=3 test/unit --with-coverage --cover-package=autosubmit --cover-inclusive --cover-xml --cover-xml-file=test/coverage.xml`

```
(autosubmit4) pgoitia@ bsces107928:~/Workspace/autosubmit$ python3 -m 'nose' --exclude=regression  --verbosity=3 test/unit --with-coverage --cover-package=autosubmit --cover-inclusive --cover-xml --cover-xml-file=test/coverage.xml

[MUCH MORE STUFF I'VE DELETED]

Name                                                                    Stmts   Miss  Cover
-------------------------------------------------------------------------------------------
autosubmit/__init__.py                                                      0      0   100%
autosubmit/autosubmit.py                                                 3700   3144    15%
autosubmit/database/__init__.py                                             0      0   100%
autosubmit/database/db_common.py                                          254    223    12%
autosubmit/database/db_manager.py                                         113     34    70%
autosubmit/database/db_structure.py                                        85     72    15%
autosubmit/experiment/__init__.py                                           0      0   100%
autosubmit/experiment/experiment_common.py                                 61     32    48%
[MUCH MORE STUFF I'VE DELETED]
-------------------------------------------------------------------------------------------
TOTAL                                                                   14999  10205    32%

[MUCH MORE STUFF I'VE DELETED]
```

#### Reproduce the NON working case
`mamba create -n autosubmit4_p3-10 python=3.10`

`mamba activate autosubmit4_p3-10`

`pip install nose`

`cd autosubmit_p3-9/`

`git clone https://earth.bsc.es/gitlab/es/autosubmit.git`

`pip install nose`

`python3 -m 'nose' --exclude=regression  --verbosity=3 test/unit --with-coverage --cover-package=autosubmit --cover-inclusive --cover-xml --cover-xml-file=test/coverage.xml`

```
(autosubmit4_p3-10) pgoitia@ bsces107928:~/Workspace/autosubmit_p3-9/autosubmit$ python3 -m 'nose' --exclude=regression  --verbosity=3 test/unit --with-coverage --cover-package=autosubmit --cover-inclusive --cover-xml --cover-xml-file=test/coverage.xml
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
nose.config: INFO: Excluding tests matching ['regression']
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
Traceback (most recent call last):
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pgoitia/Workspace/autosubmit_p3-9/autosubmit/test/unit/test_basic_config.py", line 4, in <module>
    from mock import Mock
ModuleNotFoundError: No module named 'mock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/__main__.py", line 8, in <module>
    run_exit()
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/loader.py", line 354, in loadTestsFromModule
    tests.extend(self.loadTestsFromDir(module_path))
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/loader.py", line 183, in loadTestsFromDir
    yield self.loadTestsFromName(
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/loader.py", line 426, in loadTestsFromName
    return suite([Failure(exc[0], exc[1], exc[2],
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/suite.py", line 423, in __call__
    tests = self.wrapTests(tests)
  File "/home/pgoitia/mambaforge/envs/autosubmit4_p3-10/lib/python3.10/site-packages/nose/suite.py", line 541, in wrapTests
    if isinstance(tests, collections.Callable) or isinstance(tests, unittest.TestSuite):
AttributeError: module 'collections' has no attribute 'Callable'
```

### What is the current bug behavior?

It seems that `collections` lib is not used on Python v3.10 anymore, and must be replaced by `collections.abc`. The nosetests source code still contains the references to the `collections` lib. This does not happens in Python v3.9, as you can see above.

I have solved it temporally, just by changing those references, so I can keep working, but it could be a problem in the future if the collections lib maintainers don't solve this incompatibility issue (I think, maybe I am wrong with all this conclusions).

### What is the expected correct behavior?

To print the testing report.

()

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 24, 2023, 13:17

Hello @pablogoitia ,

Currently, we only ensure support for 3.7 and 3.9. 3.10+ is not tested, at least by me. ( well and 2.7 for AS 3.X)

The reason is that these are the python versions that we're using for our current BSC projects.

**Comment by kinow** [comment]
In GitLab by @pablogoitia on Jul 25, 2023, 14:51

Thanks for the clarification @dbeltrankyl

**Comment by kinow** [comment]
We don't have nosetests anymore :) closing.
