### ISSUE TITLE
Issues with autosubmit stats

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1098]
In GitLab by @mcastril on Jul 27, 2023, 18:37

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

autosubmit/4.0.0b22

### Expid affected(If applicable)

Many

### Summary

I'll summarize different issues found when running autosubmit stats

**Issue 1: IndexError: list index out of range**

It happens in many experiments. The `pdf` is created and apparently everything is alright, but we don't know if we are missing data.

```
[mcastril@climatedt-wf AUTOSUBMIT_DATA]$ autosubmit stats a06x
```

```
id: ‘eadmin’: no such user
list index out of range
Traceback (most recent call last):
  File "/appl/AS/4.0.0b22/lib/python3.9/site-packages/autosubmit-4.0.0b0-py3.9.egg/autosubmit/monitor/diagram.py", line 175, in create_bar_diagram
    create_csv_stats(exp_stats, jobs_list, output_file)
  File "/appl/AS/4.0.0b22/lib/python3.9/site-packages/autosubmit-4.0.0b0-py3.9.egg/autosubmit/monitor/diagram.py", line 194, in create_csv_stats
    job_names[i], start_times[i], end_times[i], queuing_times[i], running_times[i]))
IndexError: list index out of range
```

**Issue 2: CSV and PDF not copied into ./stats directory**

```
[mcastril@climatedt-wf AUTOSUBMIT_DATA]$ autosubmit stats a06x
```

```
Stats created at /appl/AS/AUTOSUBMIT_DATA/a06x/tmp/a06x_statistics_20230727_1930.pdf
```

**Issue 3: CSV and PDF not copied into ./stats directory**

Too many results were asked. Autosubmit prints a message, but also an exception is thrown:

```
The results are too large to be shown, try narrowing your query. 
 Use a filter like -ft where you supply a list of job types, e.g. INI, SIM;         or -fp where you supply an integer that represents the number of hours into the past that should be queried:         suppose it is noon, if you supply -fp 5 the query will consider changes starting from 7:00 am. If you really wish to query the whole experiment, refer to Autosubmit GUI.
Traceback (most recent call last):
  File "/appl/AS/4.0.0b22/lib/python3.9/site-packages/autosubmit-4.0.0b0-py3.9.egg/autosubmit/autosubmit.py", line 2656, in statistics
    monitor_exp.generate_output_stats(expid, jobs, file_format, period_ini, period_fi, not hide,
  File "/appl/AS/4.0.0b22/lib/python3.9/site-packages/autosubmit-4.0.0b0-py3.9.egg/autosubmit/monitor/monitor.py", line 484, in generate_output_stats
    create_bar_diagram(expid, joblist, self.get_general_stats(expid), output_complete_path, period_ini, period_fi, queue_time_fixes)
  File "/appl/AS/4.0.0b22/lib/python3.9/site-packages/autosubmit-4.0.0b0-py3.9.egg/autosubmit/monitor/diagram.py", line 94, in create_bar_diagram
    raise AutosubmitCritical("Stats query out of bounds", 7061, message)
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/AS/4.0.0b22/lib/python3.9/site-packages/autosubmit-4.0.0b0-py3.9.egg/autosubmit/autosubmit.py", line 2660, in statistics
    raise AutosubmitCritical(
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/AS/4.0.0b22/lib/python3.9/site-packages/autosubmit-4.0.0b0-py3.9.egg/EGG-INFO/scripts/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/appl/AS/4.0.0b22/lib/python3.9/site-packages/autosubmit-4.0.0b0-py3.9.egg/autosubmit/autosubmit.py", line 661, in parse_args
    return Autosubmit.statistics(args.expid, args.filter_type, args.filter_period, args.output, args.hide,
  File "/appl/AS/4.0.0b22/lib/python3.9/site-packages/autosubmit-4.0.0b0-py3.9.egg/autosubmit/autosubmit.py", line 2666, in statistics
    raise AutosubmitCritical("Stats couldn't be generated. Check trace for more details", 7061, str(e))
log.log.AutosubmitCritical:  
[ERROR] Trace:  
 [CRITICAL] Stats couldn't be generated. Check trace for more details [eCode=7061]
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 31, 2023, 09:59

Working on this now

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 31, 2023, 14:04

> **Issue 1: IndexError: list index out of range**

This is because there are some calculations only for jobs that have completed_retrials.. but then the list is iterated with the whole job_list, I think there may be misplaced values in the visualization. 

There are other similar errors when not all jobs have run at least one time, which could give errors when a new job is added.

I think these issues are now fixed in the STAT_FIX branch 

 
> **Issue 2: CSV and PDF not copied into ./stats directory**

This seems intended as long as the command is prompted by a user that is not the owner of the experiment and the stats folders don't exist and it doesn't have group permissions.


```python

        if is_owner or is_eadmin:
            HUtils.create_path_if_not_exists_group_permission(os.path.join(BasicConfig.LOCAL_ROOT_DIR, expid, "stats"))
            output_complete_path = os.path.join(BasicConfig.LOCAL_ROOT_DIR, expid, "stats", output_filename)
            is_default_path = False
        else:
            if os.path.exists(os.path.join(BasicConfig.LOCAL_ROOT_DIR, expid, "stats")) and os.access(os.path.join(BasicConfig.LOCAL_ROOT_DIR, expid, "stats"), os.W_OK):
                output_complete_path = os.path.join(BasicConfig.LOCAL_ROOT_DIR, expid, "stats", output_filename)
                is_default_path = False
            elif os.path.exists(os.path.join(BasicConfig.LOCAL_ROOT_DIR, expid, BasicConfig.LOCAL_TMP_DIR)) and os.access(os.path.join(BasicConfig.LOCAL_ROOT_DIR, expid, BasicConfig.LOCAL_TMP_DIR), os.W_OK):
                    output_complete_path = os.path.join(BasicConfig.LOCAL_ROOT_DIR, expid, BasicConfig.LOCAL_TMP_DIR, output_filename)
                    is_default_path = False
        if is_default_path:
            Log.info("You don't have enough permissions to the experiment's ({}) folder. The output file will be created in the default location: {}".format(expid, BasicConfig.DEFAULT_OUTPUT_DIR))
            HUtils.create_path_if_not_exists_group_permission(BasicConfig.DEFAULT_OUTPUT_DIR)                

```

> **Issue 3: Too many results were asked. Autosubmit prints a message, but also an exception is thrown:**

Not sure about the original intended behavior, 

```python
        Log.info(message)
        raise AutosubmitCritical("Stats query out of bounds", 7061, message)
```

It has both options at once, 

@mcastril  should I raise the exception or put a default -fp X value? In the case of putting a default value, I'm not entirely sure how to do it. 

I mean, at the start of the command looks for -ft or -fp filters, then it does all the stuff except prompting and the plot. So putting a default value would be equivalent to doing all the stuff twice, one without filters and the other with the default. Also, I'm not sure which value should have this default

It seems that the MAX_NUM_PLOT is hardcoded to 40. Not sure about the reason

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 31, 2023, 14:20

Also these files had a different indent than the rest of the code, not sure why it worked fine

**Comment by kinow** [comment]
In GitLab by @mcastril on Jul 31, 2023, 14:57

> This seems intended as long as the command is prompted by a user that is not the owner of the experiment and the stats folders don't exist and it doesn't have group permissions.

It makes sense Dani. I think I remember we were going to use /tmp for that?

I think all the tests that I did last week were on experiments which I didn't own, and I think I had the files in `stats/` in one of the cases, but I cannot guarantee that right now.

> @mcastril should I raise the exception or put a default -fp X value? In the case of putting a default value, I'm not entirely sure how to do it.

I wouldn't put a default.

The problem here was the exception. If there are too many tasks and the issue is in the plot, then Autosubmit should output the message and don't try to make a plot. Besides, the exception message makes the indication to use a filter difficult to see.

**Comment by kinow** [comment]
In GitLab by @mcastril on Jul 31, 2023, 14:58

I confirm it was not me who prompted the creation of /stats:

```
drwxrwxr--. 2 agayayav autosubmit_users   88 Apr 21 17:14 stats
drwxrwxr--. 2 dbeltran autosubmit_users    6 Apr 27 16:48 stats
drwxrwxr--. 2 agayayav autosubmit_users   88 Jun  1 15:41 stats
drwxrwxr--. 2 froura autosubmit_users    88 Jul 31 13:10 stats
drwxrwxr--. 2 sughosh autosubmit_users     88 Jul 27 16:19 stats
drwxrwxr--. 2 iwagner autosubmit_users   4096 Jul 28 13:23 stats
drwxrwxr--. 2 agayayav autosubmit_users  170 Jul 27 19:34 stats
```

So probably was Aina running stats on her own experiment.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 19, 2024, 09:15

mentioned in issue autosubmit-gui#115
