### ISSUE TITLE
Repeating autosubmit create results in error with conf/metadata/experiment_data.yml file

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1101]
In GitLab by @abaer-kit on Aug 4, 2023, 15:53

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v4.0.84

### Which task has issues? Where is the log(If applicable)

autosubmit create

### Summary

`autosubmit create` writes the full configuration into the file `<expid>/conf/metadata/experiment_data.yml` (a great feature!). Running `autosubmit create` again, e.g. after updating the configuration results in an error (full error logs, see below). After deleting the named file, `autosubmit create` runs again normally.

### Steps to reproduce
With the mini-project below run the following commands:
1. `autosubmit expid -min -conf "include.yml" -d "AS error report exp." -local`
1. In `conf/minimal.yml` set `local: PROJECT_PATH:` to the directory of the configuration files (see below).
2. `autosubmit create <expid>`
3. Change in `%PROJDIR%/include.yml` the included file from `conf-a.yml` to `conf-b.yml`.
4. `autosubmit create <expid>` -> error
5. Remove `<expid>/conf/metadata/experiment_data.yml`
4. `autosubmit create <expid>` -> works

### What is the current bug behavior?

`autosubmit create` returns
```
[ERROR] Trace: 'str' object has no attribute 'items'
 [CRITICAL] Unknown issue while checking the configuration files (check_conf_files) [eCode=7040]
```
After deleting `experiment_data.yml`, it creates the project normally.

### What is the expected correct behavior?

It should just create the experiment as before with the slightly updated configuration, regardless of the `experiment_data.yml` file.

### Relevant logs and/or screenshots(if applicable)
Full output of the erroneous create command:
```
Autosubmit is running with 4.0.84
Preparing .lock file to avoid multiple instances with same expid.
Using project folder: /home/andreas/research/experiments/a018/proj

Checking configuration files...
Traceback (most recent call last):
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 930, in check_conf_files
    self.reload(force_load)
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 1375, in reload
    self.load_last_run() # from unified conf if any.
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 1429, in load_last_run
    self.data_changed = self.quick_deep_diff(self.experiment_data, self.last_experiment_data)
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 1487, in quick_deep_diff
    changed = self.quick_deep_diff(last_run_data[key], val, changed)
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 1487, in quick_deep_diff
    changed = self.quick_deep_diff(last_run_data[key], val, changed)
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 1481, in quick_deep_diff
    for key, val in current_data.items():
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 4503, in create
    as_conf.check_conf_files(running_time=False,force_load=True, no_log=False)
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 937, in check_conf_files
    raise AutosubmitCritical("Unknown issue while checking the configuration files (check_conf_files)",7040,str(e))
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andreas/.local/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 682, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 4692, in create
    raise AutosubmitCritical(e.message, e.code, e.trace)
log.log.AutosubmitCritical:  
[ERROR] Trace: 'str' object has no attribute 'items'
 [CRITICAL] Unknown issue while checking the configuration files (check_conf_files) [eCode=7040]
```
Erroneous log files:  
**20230804_155156_create.log**
```
2023-08-04 15:51:57,613 Autosubmit is running with 4.0.84
2023-08-04 15:51:57,615 Preparing .lock file to avoid multiple instances with same expid.
2023-08-04 15:51:57,620 Using project folder: /home/andreas/research/experiments/a018/proj
2023-08-04 15:51:57,620 
Checking configuration files...
[ERROR] 2023-08-04 15:51:57,626 Trace: 'str' object has no attribute 'items'
[CRITICAL] 2023-08-04 15:51:57,626 Unknown issue while checking the configuration files (check_conf_files) [eCode=7040]
2023-08-04 15:51:57,626 More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```
**20230804_155156_create_err.log**
```
[ERROR] 2023-08-04 15:51:57,626 Trace: 'str' object has no attribute 'items'
[CRITICAL] 2023-08-04 15:51:57,626 Unknown issue while checking the configuration files (check_conf_files) [eCode=7040]
```

Configuration in the mini-project:  
**include.yml**
```
DEFAULT:
  CUSTOM_CONFIG:
    PRE:
      - "%PROJDIR%/conf-a.yml"
```
**conf-a.yml**
```
TEST-A: "value a"
#
JOBS:
  WAIT:
    FILE: wait-long.sh
#
experiment:
  DATELIST: 20201001
  MEMBERS: "fc0"
  CHUNKSIZEUNIT: hour
  CHUNKSIZE: 1
  NUMCHUNKS: 2
  CHUNKINI: 0
  CALENDAR: standard
#
PLATFORMS:
  DUMMY:
    TYPE: ps
    HOST: 'dummy.host'
    USER: 'dummy'
    SCRATCH_DIR: "/home"
```
**conf-b.yml**: same as conf-a.yml except for the first line:
```
TEST-B: "value b"
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 7, 2023, 10:58

Hello @abaer-kit , 

I can't reproduce the issue. Could you perform:

`pip freeze | grep autosubmitconfigparser`

To know which configparser version is being used? I'm using the 1.0.43 without issues

**Comment by kinow** [comment]
In GitLab by @abaer-kit on Aug 7, 2023, 12:19

For me the issue also arises both when changing the `include.yml` file directly in the experiment directory and when updating the underlying project and running `autosubmit refresh`.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 7, 2023, 15:24

Hello @abaer-kit ,

Could you use the autosubmitconfigparser 1.0.44?

I could not reproduce the issue, but the code should fix your problem. It will just recreate the experiment_data.yml Again in case some unexpected is raised. 

This file is not being used in any published version only for user visualization, and with this, I'll have time to look at it 
 in the future when it is necessary ( AS v4.1.X )
