### ISSUE TITLE
Error with leap years in Autosubmit 3.3.0

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#111]
In GitLab by @fmassonn on May 2, 2016, 08:25

Hi @dmanubens and @jvegreg,

I have had this error that seems related to the use of leap years in Autosubmit. I did not have this error with earlier versions. My experiment ID is a05y.

[CRITICAL] Unhandled exception on Autosubmit: day is out of range for month
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/autosubmit.py", line 283, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/autosubmit.py", line 607, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, joblist, platforms_to_test):
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/autosubmit.py", line 657, in submit_ready_jobs
    job.update_parameters(as_conf, joblist.parameters)
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/job/job.py", line 495, in update_parameters
    chunk_end_1 = previous_day(chunk_end, cal)
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/date/chunk_date_lib.py", line 277, in previous_day
    return sub_days(date, 1, cal)
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/date/chunk_date_lib.py", line 152, in sub_days
    result = leap_handle_backward_28th(result)
  File "/shared/earth/software/autosubmit/3.3.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.0-py2.7.egg/autosubmit/date/chunk_date_lib.py", line 146, in leap_handle_backward_28th
    if start_date > datetime.datetime(end_date.year, 2, 29) >= end_date:
ValueError: day is out of range for month

Can you help?
François

**Comment by kinow** [comment]
In GitLab by @ jlope2 on May 3, 2016, 11:37

Status changed to closed by commit dc57d626255e1b46a6da14e18234ef24fdf01d9e

**Comment by kinow** [comment]
In GitLab by @ jlope2 on May 3, 2016, 15:08

@fmassonn we've just released a new version where this issue should be resolved.

If there's any other problem, please, open another issue please.

Thanks!
