### ISSUE TITLE
Autosubmit describe in BSC ES VM 1 resulting in None'getpwuid(): uid not found: 1740'

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1112]
Hello @dbeltrankyl 

### Autosubmit Version

autosubmit/4.0.0b22-foss-2015a-Python-3.7.3 on our BSC ES VM

### Expid affected(If applicable)

NA

### Which task has issues? Where is the log(If applicable)

NA

### Summary

Just tried loading the module and running `autosubmit describe` on our VM. That resulted in the following traceback.

```bash
$ autosubmit describe
Autosubmit is running with 4.0.0b0
[ERROR] Trace: 'getpwuid(): uid not found: 1740'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/4.0.0b22-foss-2015a-Python-3.7.3/lib/python3.7/site-packages/autosubmit-4.0.0b0-py3.7.egg/EGG-INFO/scripts/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/shared/earth/software/autosubmit/4.0.0b22-foss-2015a-Python-3.7.3/lib/python3.7/site-packages/autosubmit-4.0.0b0-py3.7.egg/autosubmit/autosubmit.py", line 678, in parse_args
    return Autosubmit.describe(args.expid,args.user)
  File "/shared/earth/software/autosubmit/4.0.0b22-foss-2015a-Python-3.7.3/lib/python3.7/site-packages/autosubmit-4.0.0b0-py3.7.egg/autosubmit/autosubmit.py", line 3481, in describe
    if f.is_dir() and f.owner() == get_from_user:
  File "/shared/earth/software/Python/3.7.3-foss-2015a/lib/python3.7/pathlib.py", line 1168, in owner
    return pwd.getpwuid(self.stat().st_uid).pw_name
KeyError: 'getpwuid(): uid not found: 1740'
 [CRITICAL] None'getpwuid(): uid not found: 1740'
Unhandled error: If you see this message, please report it in Autosubmit's GitLab project

```

### Steps to reproduce

Above.

### What is the current bug behavior?

Traceback, no describe output.

### What is the expected correct behavior?

List of workflows, maybe warnings/errors if `-lc DEBUG`

### Relevant logs and/or screenshots(if applicable)

Above
### Any other relevant information(if applicable)

()

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 18, 2024, 12:22

Ah, I didn't know we had an issue for this

@Lerriola is facing the same error, I think it is necessary for the testing suite...

For me, it is working in 4.1.5 but not in 4.1.8; strangely, for @Lerriola , it is never working.

I'm revising the module and doing manual tests.

The same happens for autosubmit -v

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 18, 2024, 12:24

This is on the hubs*

**Comment by kinow** [comment]
In GitLab by @ainagaya on Jun 18, 2024, 12:56

Same here, using `4.1.8` in `bsceshub02`!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 18, 2024, 13:15

Actually, it is not related to the Version bug. Though it was the same issue but not, I'll open a new issue for that. 

The autosubmit describe bug happens when `ANY` user doesn't exist anymore. The getuser() function would return something in the lines like "1440," and the Path().owner() would crash, complaining that the user doesn't exist. 

This was only happening with `autosubmit describe $user, describe * or describe`, because what Autosubmit does in there is to check all the experiments that your user owns

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 18, 2024, 13:15

!449 related
