### ISSUE TITLE
Autosubmit should give more hints about errors in the input provided to setstatus and more meaninful errors

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1113]
In GitLab by @mcastril on Aug 11, 2023, 14:08

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v4.0.87

### Expid affected(If applicable)

a097 (Climate DT)

### Summary

I am trying to change the status of an experiment, but the errors I am seeing are not very helpful

### What is the current bug behavior?

`autosubmit setstatus a097 -ftc "[ 19500101 [ fc0 [1-124] ] ], SIM" -t COMPLETED `

```
[ERROR] Trace:   
 [CRITICAL] Error in the supplied input for -ftc. [eCode=7011]
```

`autosubmit setstatus a097 -fc "[ 19500101 [ fc0 [1-124] ] ]" -t COMPLETED`

```
Traceback (most recent call last):
  File "/appl/AS/4.0.87/lib/python3.9/site-packages/autosubmit-4.0.87-py3.9.egg/EGG-INFO/scripts/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/appl/AS/4.0.87/lib/python3.9/site-packages/autosubmit-4.0.87-py3.9.egg/autosubmit/autosubmit.py", line 697, in parse_args
    return Autosubmit.set_status(args.expid, args.noplot, args.save, args.status_final, args.list,
  File "/appl/AS/4.0.87/lib/python3.9/site-packages/autosubmit-4.0.87-py3.9.egg/autosubmit/autosubmit.py", line 5471, in set_status
    raise AutosubmitCritical(
log.log.AutosubmitCritical:  
[ERROR] Trace: 'int' object has no attribute 'split'
 [CRITICAL] An Error has occurred while setting some of the workflow jobs, no changes were made [eCode=7040]
```

I was checking the examples in the documentation, and it's strange that it seems that the `ftc` examples seem to miss the closing brackets:

```
autosubmit setstatus cxxx -ftc "[ 19601101 [ fc1 [1] ], SIM" -t SUSPENDED -s
autosubmit setstatus cxxx -ftc "[ 1960(1101-1201) [ fc1 [1] ], SIM" -t SUSPENDED -s
```

https://autosubmit.readthedocs.io/en/v3.14.0/usage/workflow_recovery/setstatus.html
https://autosubmit.readthedocs.io/en/master/userguide/manage/index.html#how-to-change-the-job-status-without-stopping-autosubmit

Trying to put 2 or 3 closing brackets does not solve the problem anyway

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 11, 2023, 14:15

@dbeltrankyl checked the config and told me that the `DATELIST` is declared as an `int`

@ainagaya this is my copy from @kellekai experiment (a06x)

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 11, 2023, 14:16

Now, the error is different:

`autosubmit setstatus a097 -fc "[ 19500101 [ fc0 [1-124] ]" -t COMPLETED`

`autosubmit setstatus a097 -fc "[ 19500101 [ fc0 [1] ]" -t COMPLETED`


```
Traceback (most recent call last):
  File "/appl/AS/4.0.87/lib/python3.9/site-packages/autosubmit-4.0.87-py3.9.egg/EGG-INFO/scripts/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/appl/AS/4.0.87/lib/python3.9/site-packages/autosubmit-4.0.87-py3.9.egg/autosubmit/autosubmit.py", line 697, in parse_args
    return Autosubmit.set_status(args.expid, args.noplot, args.save, args.status_final, args.list,
  File "/appl/AS/4.0.87/lib/python3.9/site-packages/autosubmit-4.0.87-py3.9.egg/autosubmit/autosubmit.py", line 5083, in set_status
    raise AutosubmitCritical(
log.log.AutosubmitCritical:  
[ERROR] Trace: ## -fc Validation Message ##
	Provided chunk formula does not have the right format. Were you trying to use another option? 
 [CRITICAL] Error in the supplied input for -fc. [eCode=7011]
```

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 11, 2023, 14:18

It works after adding all the closing brackets:

`autosubmit setstatus a097 -fc "[ 19500101 [ fc0 [1-124] ] ]" -t COMPLETED`

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 11, 2023, 14:20

However, there's also something strange with the output:

```
CHANGED: job: a097_19500101_fc0_1_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_1_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_2_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_2_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_3_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_3_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_4_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_4_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_5_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_5_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_6_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_6_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_7_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_7_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_8_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_8_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_9_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_9_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_10_SIM status to: COMPLETED
CHANGED: job: a097_19500101_fc0_10_SIM status to: COMPLETED
```

Every task appears twice

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 11, 2023, 14:33

mentioned in commit 03556cb8313e2c78bddac9f75b99a1e77b63782f

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 11, 2023, 15:09

mentioned in commit 611a04cf0c92086ee1af2401597d414fa19ef031
