### ISSUE TITLE
Profiler fails to stop and causes critical error

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1123]
In GitLab by @manuel-g-castro on Aug 25, 2023, 17:14

Hello @dbeltrankyl and @kinow, I am forwarding an issue that @pablogoitia noticed as he was travelling back to Cantabria.

MERGE REQUEST: !466 

### Autosubmit Version

4.0.87

### Summary

I had a flashback and realized that a last minute change I made this week produces an error when you run the "monitor" function with the profiler enabled.

The error occurs because the ``stop()`` function throws an exception when the user tries to call ``stop()`` twice. This is due to a ``_finished`` flag that I introduced in this merge request: !372

This was not happening before approving this MR, but I consider that the flag is still needed, so I propose the solution in MR !466 

### Steps to reproduce

Just run a `monitor` command for any experiment.

### What is the current bug behavior?

It critically fails.

### What is the expected correct behavior?

It should provide the profiler output and create the plot.

### Relevant logs and/or screenshots

```
 [CRITICAL] Cannot stop the profiler because was not running. [eCode=7074]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
Traceback (most recent call last):
  File "/home/mgimenez/Documents/local/dev/autosubmit/bin/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/home/mgimenez/Documents/local/dev/autosubmit/autosubmit/autosubmit.py", line 664, in parse_args
    return Autosubmit.monitor(args.expid, args.output, args.list, args.filter_chunks, args.filter_status,
  File "/home/mgimenez/Documents/local/dev/autosubmit/autosubmit/autosubmit.py", line 2528, in monitor
    profiler.stop()
  File "/home/mgimenez/Documents/local/dev/autosubmit/autosubmit/profiler/profiler.py", line 63, in stop
    raise AutosubmitCritical('Cannot stop the profiler because was not running.', 7074)
log.log.AutosubmitCritical: 
```

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 25, 2023, 18:03

Hi @manuel-g-castro and @pablogoitia 

Thanks for the report and for providing a solution already. I think it's not urgent as this is a corner case, but for sure it must be solved before the profiler gets used extensively.

@dbeltrankyl is back on Monday and he can evaluate which solution is better, but I think the 1) and 2) are good ones.

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 31, 2023, 10:27

I think that we should also Log and return when the profiler is not started yet, and don't trow an exception.

**Comment by kinow** [comment]
In GitLab by @pablogoitia on Jul 8, 2024, 15:25

Hi, @kinow. I'm working on this issue, and I don't know which of the 3 solutions above to implement. I think that the most viable is the third one. Why? Because it does not change the natural behaviour of the profiler, and it requires fewer changes to the `monitor()` function inside autosubmit.py.

The other ones would require a small change in `profiler.stop()`, but more complex ones in `monitor()` (some logic to avoid executing `profiler.stop()` if `monitor()` hasn't failed) that would make the code less maintainable, as programmers would know about it before applying any change into the function.

There is another option: if nobody used the profiler on the `monitor()` function, it can be removed.

Wdyt? :thinking:

**Comment by kinow** [comment]
In GitLab by @pablogoitia on Jul 8, 2024, 15:29

Why do I said that it is necessary to insert some logic into the `monitor()` function?

Because given the current structure, the profiler would stop reporting just after finishing the first try/except clause.

**Comment by kinow** [comment]
I think this option is the best one, just telling users about it (log in either info or warning).

**Comment by kinow** [comment]
@pablogoitia I think we do not need to remove that option (the plan is to have that in nearly all commands if possible, in the future).

What about the second option? Of just logging the warn/info to the user, and doing nothing else. Wouldn't that work with monitor too?

**Comment by kinow** [comment]
Maybe we could use just two states, STARTED and STOPPED, and use an Enum for that?

Something like,


```diff
diff --git a/autosubmit/profiler/profiler.py b/autosubmit/profiler/profiler.py
index b73ccea0..34d61ffa 100644
--- a/autosubmit/profiler/profiler.py
+++ b/autosubmit/profiler/profiler.py
@@ -21,6 +21,7 @@ import cProfile
 import io
 import os
 import pstats
+from enum import Enum
 from datetime import datetime
 from pathlib import Path
 from pstats import SortKey
@@ -33,6 +34,13 @@ from log.log import Log, AutosubmitCritical
 
 _UNITS = ["B", "KiB", "MiB", "GiB", "TiB", "PiB"]
 
+
+class ProfilerState(Enum):
+    """Enumeration of profiler states"""
+    STOPPED = "stopped"
+    STARTED = "started"
+
+
 class Profiler:
     """Class to profile the execution of experiments."""
 
@@ -45,27 +53,34 @@ class Profiler:
         self._mem_final = 0
 
         # Error handling flags
-        self._started = False
-        self._finished = False
+        self._state = ProfilerState.STOPPED
+
+    @property
+    def started(self):
+        return self._state == ProfilerState.STARTED
+
+    @property
+    def stopped(self):
+        return self._state == ProfilerState.STOPPED
 
     def start(self) -> None:
         """Function to start the profiling process."""
-        if self._started:
+        if self.started:
             raise AutosubmitCritical('The profiling process was already started.', 7074)
 
-        self._started = True
+        self.state = ProfilerState.STARTED
         self._profiler.enable()
         self._mem_init += _get_current_memory()
 
     def stop(self) -> None:
         """Function to finish the profiling process."""
-        if not self._started or self._finished:
-            raise AutosubmitCritical('Cannot stop the profiler because was not running.', 7074)
+        if not self.started:
+            Log.info("Cannot stop the profiler because was not started.")
+            return
 
         self._profiler.disable()
         self._mem_final += _get_current_memory()
         self._report()
-        self._finished = True
+        self.state = ProfilerState.STOPPED
 
     def _report(self) -> None:
         """Function to print the final report into the stdout, log and filesystem."""
```

**Comment by kinow** [comment]
In GitLab by @pablogoitia on Jul 10, 2024, 11:07

I like the idea of changing the flags to the Enum :eyes: It is easier to understand. I think I will include it in the next merge request.

Regarding the 2nd alternative, if I implement it we would still have the same problem: the profiler would stop on the first `finally` clause, which would require a rework on the `monitor()` function just for the profiler to work :grimacing:

I haven't considered this fact when opening the issue, but when reviewing the code: Currently, the `monitor()` function consists of multiple _try/except_ clauses, and I think that having the `profiler.stop()` call on each _finally_ block is no longer an option since it doesn't work as it should.

So, after this brief review, I've been thinking about... Do we really need the profiler output if something goes wrong with the function? If not, it would simplify the solution. Why? because it would be enough to put one single `profiler.stop()` at the end of the function, instead of on each _try/except_. If we aren't sure, I can ask it in the AS meeting tomorrow and see what people think

**Comment by kinow** [comment]
In GitLab by @pablogoitia on Jul 10, 2024, 11:22

I don't know if putting the `profiler.stop()` on the except clause instead of finally would be a good practice, but if it is, is definitely the best solution right now if we want to keep the profiler output after failures. @kinow

**Comment by kinow** [comment]
In GitLab by @pablogoitia on Jul 10, 2024, 12:44

Hi @kinow . I opened a MR with a proposal that combines both your state management with the second alternative plus a change in the monitor function, in order to move the `profiler.stop()` call from the finally block to the except, before raising the exception.

**Comment by kinow** [comment]
mentioned in commit b5c173099262e670ebd8ed593e5ff5efc7d28c06
