### ISSUE TITLE
When Platform is in main, Queue type not specified on platform LUMI Error

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1129]
In GitLab by @ainagaya on Sep 13, 2023, 11:36

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

Autosubmit is running with 4.0.89

### Expid affected(If applicable)

I recycled **a06l** to show you the issue.

### Which task has issues? Where is the log(If applicable)

The issue appears in the autosubmit create.

### Summary

We have a `platforms.yml` with:

```
Platforms:
  lumi:
    TYPE: slurm
    HOST: lumi-cluster
```
And then some users want to customize things in `main.yml`:

```
PLATFORMS:
   LUMI:
      NODES: 112
      TASKS: 16
      THREADS: 8
      PROCESSORS: 1792
      PARTITION: "standard"
      MAX_WALLCLOCK: "02:00"
```

When they to this, they get:

```
[ERROR] Trace: Queue type not specified on platform LUMI
 [CRITICAL] Error obtaining the project data, check the parameters related to PROJECT and GIT/SVN or LOCAL sections [eCode=7014]
```

This is solved when adding the type of platform in the `main.yml`. But it is a little bit confusing. I was just thinking that maybe is because of the lowercase-uppercase mismatch (but it shouldn't, right?). 

### Steps to reproduce

We are using --minimal, and a bootstrap with this `include.yml`:
```
DEFAULT:
  CUSTOM_CONFIG:
    PRE:
      - "%PROJDIR%/conf"
      - "%PROJDIR%/conf/simulation/%RUN.SIMULATION%.yml"
      - "%PROJDIR%/conf/parameter/%RUN.PARAMETER%.yml"
      - "%PROJDIR%/conf/model/%RUN.MODEL%/%RUN.MODEL%.yml"
      - "%PROJDIR%/conf/model/%RUN.MODEL%/%RUN.GRID_ATM%.yml"
      - "%PROJDIR%/conf/application/%RUN.APPLICATION%.yml"
    POST:
      - "~/platforms.yml"
~                          
```

The platforms.yml file is loaded in the first bullet point (`- "%PROJDIR%/conf"`). And then in the main.yml (that is in the middle of pre and post) it is overwritten. So to reproduce the error you should have a platform in pre, and try to override some values in another file that comes after it.  

### Relevant logs and/or screenshots(if applicable)

```
The a06l experiment 4.0.0b0 version is being updated to 4.0.89 for match autosubmit version
Autosubmit is running with 4.0.89
Preparing .lock file to avoid multiple instances with same expid.
Traceback (most recent call last):
  File "/appl/AS/4.0.89/lib/python3.9/site-packages/autosubmit-4.0.89-py3.9.egg/autosubmit/autosubmit.py", line 4539, in create
    if not Autosubmit._copy_code(as_conf, expid, as_conf.experiment_data.get("PROJECT",{}).get("PROJECT_TYPE","none"), False):
  File "/appl/AS/4.0.89/lib/python3.9/site-packages/autosubmit-4.0.89-py3.9.egg/autosubmit/autosubmit.py", line 4765, in _copy_code
    submitter.load_platforms(as_conf)
  File "/appl/AS/4.0.89/lib/python3.9/site-packages/autosubmit-4.0.89-py3.9.egg/autosubmit/platforms/paramiko_submitter.py", line 156, in load_platforms
    raise Exception(
Exception: Queue type not specified on platform LUMI

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/AS/4.0.89/lib/python3.9/site-packages/autosubmit-4.0.89-py3.9.egg/autosubmit/autosubmit.py", line 4544, in create
    raise AutosubmitCritical("Error obtaining the project data, check the parameters related to PROJECT and GIT/SVN or LOCAL sections", code=7014,trace=str(e))
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/AS/4.0.89/lib/python3.9/site-packages/autosubmit-4.0.89-py3.9.egg/EGG-INFO/scripts/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/appl/AS/4.0.89/lib/python3.9/site-packages/autosubmit-4.0.89-py3.9.egg/autosubmit/autosubmit.py", line 690, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/appl/AS/4.0.89/lib/python3.9/site-packages/autosubmit-4.0.89-py3.9.egg/autosubmit/autosubmit.py", line 4735, in create
    raise AutosubmitCritical(e.message, e.code, e.trace)
log.log.AutosubmitCritical:  
[ERROR] Trace: Queue type not specified on platform LUMI
 [CRITICAL] Error obtaining the project data, check the parameters related to PROJECT and GIT/SVN or LOCAL sections [eCode=7014]
```

### Any other relevant information(if applicable)

It is sorted out when adding `TYPE: slurm` under the platform in main, but is a little misleading for the users.
Thanks!!!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 13, 2023, 12:14

Thanks for reporting this, 

I think what might have happened during the create is that 

* minimal + main is loaded
* downloads the data.. but copy_code uses the hpcarch platform if defined and in this step is still incomplete
* loads all configuration including remote configuration
* finish create

So the 3) step is not reached, but an autosubmit run will work. 

I'll revise that function so this doesn't happen

**Comment by kinow** [comment]
In GitLab by @rohanali1798 on Nov 28, 2023, 12:42

Hi!

I also faced the same issue. Just reporting from my side.
Thanks!

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 21, 2024, 17:48

@dbeltrankyl we were doubting if the issue is fixed. I don't see any commit linked but it seems it's not happening in dev5

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 21, 2024, 18:07

If fixed it is a side effect of the changes

**Comment by kinow** [comment]
In GitLab by @ainagaya on Feb 28, 2024, 15:12

Just to clarify, we saw the other day that it was not fixed!

**Comment by kinow** [comment]
In GitLab by @ainagaya on May 16, 2024, 09:50

mentioned in issue digital-twins/de_340-2/workflow#374

**Comment by kinow** [comment]
In GitLab by @tkiszler on Nov 6, 2024, 09:31

Hello, I have had the same problem repeatedly. To switch to the operational Climate DT project I made changes in the main.yml setting
```
 PLATFORMS:
  LUMI:
    USER: robot-account
    PROJECT: project_462000560
    HPCARCH_short: lumi-operational
```
Then I get the error: 
```
Traceback (most recent call last):
  File "/appl/AS/4.1.10/lib/python3.9/site-packages/autosubmit-4.1.10-py3.9.egg/EGG-INFO/scripts/autosubmit", line 59, in main
    return_value = Autosubmit.parse_args()
  File "/appl/AS/4.1.10/lib64/python3.9/site-packages/autosubmit-4.1.10-py3.9.egg/autosubmit/autosubmit.py", line 739, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/appl/AS/4.1.10/lib64/python3.9/site-packages/autosubmit-4.1.10-py3.9.egg/autosubmit/autosubmit.py", line 4476, in create
    raise AutosubmitCritical("Error obtaining the project data, check the parameters related to PROJECT and GIT/SVN or LOCAL sections", code=7014,trace=str(e))
log.log.AutosubmitCritical:  

 [CRITICAL] Error obtaining the project data, check the parameters related to PROJECT and GIT/SVN or LOCAL sections [eCode=7014]
```
So I tried around and used `PLATFORM` instead of `PLATFORMS`and then I can run `autosubmit create` without error. But in that case none of these changes take any affect.

**Comment by kinow** [comment]
In GitLab by @ainagaya on Nov 6, 2024, 09:35

Hi @tkiszler , can you try 

```
 PLATFORMS:
  LUMI:
    TYPE: slurm
    USER: robot-account
    PROJECT: project_462000560
    HPCARCH_short: lumi-operational
```

And tell us if you have the same error? 

It's not a perfect solution but for the time being it might help.

**Comment by kinow** [comment]
In GitLab by @tkiszler on Nov 6, 2024, 09:40

Yes, this helped!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 6, 2024, 09:50

thanks @ainagaya 

This issue was lost as it was not assigned to a milestone, I'll revise if an automatic solution is possible from AS

**Comment by kinow** [comment]
In GitLab by @ainagaya on Nov 6, 2024, 09:51

Thanks @dbeltrankyl !!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 7, 2024, 08:49

mentioned in commit 705ee652f650848890e461aca85fa82e4db852ad

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 12, 2024, 12:57

mentioned in commit d6a2d51e3d80ed73be5012ae131ecb0dba2a5ed7

**Comment by kinow** [comment]
In GitLab by @ainagaya on Dec 3, 2024, 14:47

Hi @dbeltrankyl , this was fixed and is working smoothly, the only problem is that some users are now getting this warning

```
[WARNING] PLATFORMS.MARENOSTRUM5.TYPE: <not defined> for MARENOSTRUM5 is not supported
Remote git cloning is disabled
```

And I believe that it comes from this issue, since we can now use `PLATFORMS` in main without complains, but this warning is a bit confusing.

Thanks!!

cc @ragurida :smile:
