### ISSUE TITLE
[internal bsc] Issues in bsceshub

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1139]
In GitLab by @dbeltrankyl on Oct 3, 2023, 11:10

Hello @albertvilabsc , @eferre1 

We are having an issue with Autosubmit not being able to read /esarchive (I believe ) properly in the HUBS.

First, we thought about portalocker issues, I forced an older version of it and it still doesn't work in a brand-new autosubmit installation.

Then @eferre1  mentioned that the issue could be in the hubs, and it seems that it is the case because we are able to run the same command in the bscearth machines ( I was trying the commands on the bscautosubmit01 and he was in bschubs) 

Autosubmit is giving random issues about databases and also portalocker when it is ran under the hubs. 

Bschubs: 

```
[dbeltran@ bsceshub02 dbeltran]$ module load autosubmit/4.0.96-foss-2021b-Python-3.9.6
[dbeltran@ bsceshub02 dbeltran]$ autosubmit testcase -H HPC2020 -y t0d7 -d "auto-ECE4 initial developments testcase 2"
Autosubmit is running with 4.0.96
Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.96-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.96-py3.9.egg/autosubmit/database/db_common.py", line 176, in check_experiment_exists
    result = queue.get(True, TIMEOUT)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/multiprocessing/queues.py", line 114, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.96-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.96-py3.9.egg/autosubmit/autosubmit.py", line 1242, in expid
    exp_id = copy_experiment(copy_id, description, Autosubmit.autosubmit_version, testcase, operational)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.96-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.96-py3.9.egg/autosubmit/experiment/experiment_common.py", line 91, in copy_experiment
    if not db_common.check_experiment_exists(experiment_id):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.96-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.96-py3.9.egg/autosubmit/database/db_common.py", line 178, in check_experiment_exists
    raise AutosubmitCritical(
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.96-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.96-py3.9.egg/EGG-INFO/scripts/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.96-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.96-py3.9.egg/autosubmit/autosubmit.py", line 708, in parse_args
    return Autosubmit.testcase(args.description, args.chunks, args.member, args.stardate, args.HPC, args.copy,args.minimal_configuration,args.git_repo,args.git_branch,args.git_as_conf,args.use_local_minimal)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.96-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.96-py3.9.egg/autosubmit/autosubmit.py", line 5732, in testcase
    testcaseid = Autosubmit.expid(description, hpc, copy_id, False, minimal_configuration, git_repo, git_branch, git_as_conf, use_local_minimal=use_local_minimal, testcase=True)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.96-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.96-py3.9.egg/autosubmit/autosubmit.py", line 1250, in expid
    raise AutosubmitCritical("Error while generating a new experiment in the db: {0}".format(str(e)), 7011)
log.log.AutosubmitCritical:  
 [CRITICAL] Error while generating a new experiment in the db:   [eCode=7011]
```

autosubmit01:

```
module load autosubmit/4.0.96-foss-2015a-Python-3.7.3

dbeltran@ bscesautosubmit01:~> autosubmit testcase -H HPC2020 -y t0d7 -d "auto-ECE4 initial developments testcase 2"
Autosubmit is running with 4.0.96
The new experiment "t0do" has been registered.
Generating folder structure...
Experiment folder: /esarchive/autosubmit/t0do
Generating config files...
Experiment t0do created
```

We also tried other commands like run, monitor, and inspect. None of them are working on the hubs. 

Do you know what is the issue?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 3, 2023, 11:13

Not sure if Albert is available I'm fyi @fbeninca also

**Comment by kinow** [comment]
In GitLab by @fbeninca on Oct 3, 2023, 11:16

thanks @dbeltrankyl I'll take in charge this

**Comment by kinow** [comment]
In GitLab by @eferre1 on Oct 3, 2023, 11:19

Adding @ gbonet that it is also having the same issue in the hub, but he is using the 3.15 version, so we can confirm that it is not an issue of the AS version.

**Comment by kinow** [comment]
In GitLab by @fbeninca on Oct 3, 2023, 11:21

it seems something related to writing in the DB, where AS stores its databases?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 3, 2023, 11:23

Under /esarchive/autosubmit, the database is the same both in hubs and bscearth/autosumbit machines.

**Comment by kinow** [comment]
In GitLab by @fbeninca on Oct 3, 2023, 11:27

yes, in which folder exactly? I'm checking `/esarchive/autosubmit/t0d7/` Maybe is something related to permissions.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 3, 2023, 11:29

For the `autosubmit testcase` it uses:

`-rwxrwxrwx.    1 emoreno  Earth 1.2M Oct  3 11:27 /esarchive/autosubmit/ecearth.db`

inspect/monitor/run it also uses 

`-rw-r--r--. 1 eferre1 Earth 16384 Sep 14 08:47 /esarchive/autosubmit/t0d7/pkl/job_packages_t0d7.db`

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 3, 2023, 11:32

The GUI,api and  `autosubmit run/create` uses also, the ones under 

`/esarchive/autosubmit/as_metadata` ```(data/job_data_$expid.db) (structures/structure_$expid.db)```

(GUI,API) also uses `/esarchive/autosubmit/as_metadata/graph`

**Comment by kinow** [comment]
In GitLab by @fbeninca on Oct 3, 2023, 11:32

ok thanks! I'll check and let you know ASAP

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 3, 2023, 11:33

thanks!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 3, 2023, 11:45

FYI @ spalomas

**Comment by kinow** [comment]
In GitLab by @eferre1 on Oct 3, 2023, 14:52

tagging also @amozaffari so he can follow the issue

**Comment by kinow** [comment]
In GitLab by @albertvilabsc on Oct 4, 2023, 09:25

@fbeninca, I can take a look with Felipe if the /etc/fstab is the same as the workstations.

Maybe the problem is this...

Albert

FYI @stamenminkov

**Comment by kinow** [comment]
In GitLab by @eferre1 on Oct 4, 2023, 09:44

tagging @etiennesky since he is also using the hub to run on hpc2020

**Comment by kinow** [comment]
In GitLab by @fbeninca on Oct 4, 2023, 09:46

Hello,
right now we have several issues with the hub, so we asked Operations to reboot the machine, once it's done we can start working again on the issue.

**Comment by kinow** [comment]
In GitLab by @albertvilabsc on Oct 4, 2023, 11:03

Hello,

The access issue on the hub has been solved!

Anything, please, let us know.

Thanks,

Albert

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 4, 2023, 14:56

thanks, things are better, but I am still having one issue connecting to the bscearth000 machine, with autosubmit/3.15.1b-foss-2021b-Python-2.7.18 and expid a6ia

```
[ERROR] Trace:
[transfer_node_bscearth000] has configuration issues.
 Check that the connection is passwd-less.(ssh etourign@ bscearth000)
 Check the parameters that build the root_path are correct:{scratch_dir/project/user} = {/esarchive/scratch/Earth/etourign}
```

or if I use a SCRATCH not in esarchive I get

```
[ERROR] Trace:
[transfer_node_bscearth000] has configuration issues.
 Check that the connection is passwd-less.(ssh etourign@ bscearth000)
 Check the parameters that build the root_path are correct:{scratch_dir/project/user} = {/scratch/Earth/etourign}
[CRITICAL] Issues while checking the connectivity of platforms. [eCode=7010]
More info at https://autosubmit.readthedocs.io/en/v3.15.0/faq.html
```
as you can see, I can ssh into the bscearth000 machine and the folder /scratch/Earth/etourign exists

```
[etourign@ bsceshub02 etourign]$ ssh etourign@ bscearth000
Last login: Wed Oct 4 14:17:43 2023 from bsceshub02.bsc.es
Have a lot of fun...
ls /scratch/Earth/etourign
etourign@ bscearth000 : ~ > ls /scratch/Earth/etourign
a4kh a4ki a4kw a6ia tmp
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2023, 15:20

Hello @etiennesky ,

I'm not sure what the issue is. I did a copy of your experiment, and it works for me. 

```
[nord3v2] Correct user privileges for host nord4.bsc.es
[nord3v2] Connection successful to host nord4.bsc.es
[local] Correct user privileges for host localhost
[local] Connection successful to host localhost
[transfer_node_bscearth000] Correct user privileges for host bscearth000
[transfer_node_bscearth000] Connection successful to host bscearth000
```
In your case, it seems that the connection is established, but it can't create the tmp folder that tests that you have the right permissions in the /scratch/Earth/etourign folder

**Comment by kinow** [comment]
In GitLab by @fbeninca on Oct 4, 2023, 15:24

Hello @dbeltrankyl and all,
now after the reboot it seems to work fine:

```
[fbeninca@ bsceshub02 fbeninca]$ module load autosubmit/4.0.96-foss-2021b-Python-3.9.6
[fbeninca@ bsceshub02 fbeninca]$ autosubmit testcase -H HPC2020 -y t0d7 -d "auto-ECE4 initial developments testcase 2"
Autosubmit is running with 4.0.96
The new experiment "t0ds" has been registered.
Generating folder structure...
Experiment folder: /esarchive/autosubmit/t0ds
Generating config files...
Experiment t0ds created
```

can you test it please?

F.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2023, 15:28

Just in case, maybe check your ecmwf-hpc2020 certificate and settings. Maybe the message complains about a different platform? It is the only one I did not test

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2023, 15:28

Hello @fbeninca ,

For my side, All that was not working before seems to work now, thanks!

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 4, 2023, 16:03

I commented out the hpc2020 platform, and still have issues with the bscearth000 one...

It seems like it works fine with autosubmit/3.14.0-foss-2021b-Python-2.7.18

```
Autosubmit is running with v3.14.0
Checking the connection to all platforms in use
[marenostrum4] Correct user privileges for host mn1.bsc.es
[marenostrum4] Connection successful to host mn1.bsc.es
[transfer_node_bscearth000] Correct user privileges for host bscearth000
[transfer_node_bscearth000] Connection successful to host bscearth000
[nord3v2] Correct user privileges for host nord4.bsc.es
[nord3v2] Connection successful to host nord4.bsc.es

```

 but not with autosubmit/3.15.1b-foss-2021b-Python-2.7.18 , which is the version required to run on the hpc2020 platform. I also tried with autosubmit/3.15.0b-foss-2021b-Python-2.7.18 and get the same error:

```
Autosubmit is running with v3.15.0
Checking the connection to all platforms in use
[nord3v2] Correct user privileges for host nord4.bsc.es
[nord3v2] Connection successful to host nord4.bsc.es
[marenostrum4] Correct user privileges for host mn1.bsc.es
[marenostrum4] Connection successful to host mn1.bsc.es
[ERROR] Trace: 
[transfer_node_bscearth000] has configuration issues.
 Check that the connection is passwd-less.(ssh etourign@ bscearth000)
 Check the parameters that build the root_path are correct:{scratch_dir/project/user} = {/scratch/Earth/etourign}

 [CRITICAL] Issues while checking the connectivity of platforms. [eCode=7010]
```

@dbeltrankyl can you please check  ?

Also,  can you confirm which AS version I need to run with hpc2020 ?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2023, 16:25

> Also, can you confirm which AS version I need to run with hpc2020 ?

the 3.15.0b one has the latest changes so that one should work. I'll change the terminology in the next release to match the same versioning that 4.0.XX. 

> but not with autosubmit/3.15.1b-foss-2021b-Python-2.7.18 , the version required to run on the hpc2020 platform. I also tried with autosubmit/3.15.0b-foss-2021b-Python-2.7.18 and get the same error:

I tried with 3.15.1b and 3.15.0b, and the check part is working for me.. also there shouldn't be any difference at all between 3.14 and 3.15 regarding that section, so I'm not sure what the issue is or how to reproduce it since my copy worked


```bash
Starting job submission...
Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Using existing valid structure.
Checking scripts...
4 of 18 checked
Template SIM will be checked in running time
Template SIM will be checked in running time
8 of 18 checked
12 of 18 checked
16 of 18 checked
18 of 18 checked
Autosubmit is running with v3.15.0b0
Checking the connection to all platforms in use
[local] Correct user privileges for host localhost
[local] Connection successful to host localhost
[nord3v2] Correct user privileges for host nord4.bsc.es
[nord3v2] Connection successful to host nord4.bsc.es
[transfer_node_bscearth000] Correct user privileges for host bscearth000
[transfer_node_bscearth000] Connection successful to host bscearth000


18 of 18 jobs remaining (16:31)
a6ii_LOCAL_SETUP submitted
Call from a6ii_LOCAL_SETUP with status SUBMITTED


18 of 18 jobs remaining (16:31)
Job a6ii_LOCAL_SETUP is COMPLETED
a6ii_SYNCHRONIZE submitted
Call from a6ii_SYNCHRONIZE with status SUBMITTED


```

Edit: Maybe you can try naming the transfer_node_bscearth000 to transfernodebscearth000 just to check if it is a regex issue ( but I doubt )

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2023, 16:34

Does it work for you @eferre1?

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 4, 2023, 16:51

It seems @ gbonet is not having the same problem I have, with AS 3.15

here is what happens when I run with `autosubmit -lc DEBUG run a6ia`

```
Autosubmit is running with v3.15.0b0
Running job data structure
Backing up jobs_data...
Jobs_data database backup completed.
Checking the connection to all platforms in use
[marenostrum4] Correct user privileges for host mn1.bsc.es
[marenostrum4] Connection successful to host mn1.bsc.es
[WARNING] [transfer_node_bscearth000] Connection sucessful to host bscearth000, however there are issues with %HPCROOT%[eCode=3000]
[nord3v2] Correct user privileges for host nord4.bsc.es
[nord3v2] Connection successful to host nord4.bsc.es
[ERROR] Trace: 
[transfer_node_bscearth000] has configuration issues.
 Check that the connection is passwd-less.(ssh etourign@ bscearth000)
 Check the parameters that build the root_path are correct:{scratch_dir/project/user} = {/scratch/Earth/etourign}

 [CRITICAL] Issues while checking the connectivity of platforms. [eCode=7010]
More info at https://autosubmit.readthedocs.io/en/v3.15.0/faq.html
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2023, 16:59

I've compared branches, 

The only difference is that in 3.15, we also check the remote_log_dir.. 

```python
    def check_remote_permissions(self):
        try:
            path = os.path.join(self.scratch, self.project, self.user, "permission_checker_azxbyc")
            try:
                self._ftpChannel.rmdir(path)
            except:
                pass
            self._ftpChannel.mkdir(path)
            self._ftpChannel.rmdir(path)
            self.check_remote_log_dir()
            return True
        except:
            return False
```

Since it is an empty experiment, could you delete the folder `/scratch/Earth/etourign/a6ia`

and try again?

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 4, 2023, 17:01

I tried again, and it seems that AS re-created the folder, but still gives the same error...

EDIT - I deleted the folder before running AS as you instructed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2023, 17:01

Also, I see that the hour of bscearth000 seems ahead of the current time, which is strange, could it mess with the checkers? 

edit: done at 17:01
```
dbeltran@ bscearth000:/scratch/Earth/etourign> date
Wed Oct  4 17:10:15 CEST 2023
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2023, 17:05

Not sure what else we can try..

Maybe try a copy + create + run of that experiment and check that LOG_$EXPID is indeed in all `/$scratch/$project/$user/$expid `of all the remote platforms? ( Because you ran this one with 3.14 )

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2023, 17:09

If that doesn't work, I would look at ~/.bashrc of the bscearth000 and hubs, see if you have something set there and disable it for test

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 4, 2023, 17:47

thank you @dbeltrankyl in the end it was this single line in my .bashrc on the workstations

`export PS1="\[$(ppwd)\]\u@\h : \w > "`

I put it inside this if test and now it works

```
if [ -t 1 ] ;
then

export PS1="\[$(ppwd)\]\u@\h : \w > "

#[...]

fi
```

Should we add some documentation in AS docs that users should NOT do anything with PS1 which might cause interferences?

**Comment by kinow** [comment]
In GitLab by @ spalomas on Oct 4, 2023, 18:13

Hi, I don't have problems with the connection anymore but it seems that AS (3.15.0b0) does not submit the jobs on `hpc2020`, even though they are set to QUEUED and the .cmd file is copied to the remote platform.

The EXPID is `a6af`

A couple of notes: I could run the two first jobs manually (ssh + sbatch). I did not try this before the issues with bsceshub, so it may have nothing to do with it (srry).

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 5, 2023, 08:16

Hello @ spalomas ,

Did you verify the status on the remote with a squeue?

**Comment by kinow** [comment]
In GitLab by @eferre1 on Oct 5, 2023, 08:18

Hi @ spalomas, I think you have a misconfiguration in the `jobs.conf`, at least for the SYNC job:

```
EC_QUEUE = nf
#EC_QUEUE = ecs
```

The EC_QUEUE parameter accepts the values `ecs` or `hpc`, since this parameter regulates to which complex will the job be submitted through ecaccess.

The QUEUE parameter is the same as usual, regulating which queue will be used, which differ between the comlexes, being `nf, np, ni` available for the `HPC` complex, and `ef, ei, el, et`the ones for the `ECS` one. (Coming from their [documentation](https://confluence.ecmwf.int/display/UDOC/HPC2020%3A+Batch+system))

PS: Also, each of both options (ECS, HPC), has four complexes (`aa, ab, ac, ad`) where the jobs can be submitted, and the default `ssh` one might not be the same as the default ecacces submission one (they change the defaults depending on needs and/or machine maintentance, load, etc), which might make you to not see your job with an `squeue` if you are not in the same complex.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 5, 2023, 08:19

We made some changes in 3.15 to mitigate the impact of the bashrc stuff but seems that it was not enough https://earth.bsc.es/gitlab/es/autosubmit/-/issues/817#note_207933. We can continue there

**Comment by kinow** [comment]
In GitLab by @eferre1 on Oct 5, 2023, 09:30

Hi @fbeninca and @albertvilabsc, yesterday it was working for me too, but today we are having issues with the `ecaccess` module, that is not responding. I'm not sure if it is fully related to this issue, so we can move it to a new one if you see that it is another thing.

I'm having issues with `ecaccess` commands, any of them gets frozen and doesn't do anything. I was trying the `ecaccess-certificate` ones, to create it or to see it, but I have to abort it with `ctrl+C` after some minutes frozen. @dbeltrankyl confirmed that he is having the same issue and that `ecaccess` is working from his laptop, so we can discard an issue with the ECMWF part of the command. Autosubmit works fine unless (which is how I found the issue) it is an hpc2020 experiment that uses `ecaccess`, then it gets frozen and doesn't run. The log was like this:

```
Starting job submission...
Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Using existing valid structure.
Checking scripts...
5 of 20 checked
Template SIM will be checked in running time
Template SIM will be checked in running time
10 of 20 checked
15 of 20 checked
20 of 20 checked
Autosubmit is running with v3.15.0b0
Checking the connection to all platforms in use

(here it was frozen not doing anything until ctrl+C)
^CAutosubmit will interrupt at the next safe occasion

[nord3v2] Correct user privileges for host nord1.bsc.es
[nord3v2] Connection successful to host nord1.bsc.es
[local] Correct user privileges for host localhost
[local] Connection successful to host localhost
[transfer_node_bscearth000] Correct user privileges for host bscearth000
[transfer_node_bscearth000] Connection successful to host bscearth000
[ERROR] Trace: 
[ecmwf-hpc2020] Connection Unsuccessful to host hpc-login 

 [CRITICAL] Issues while checking the connectivity of platforms. [eCode=7010]
```

As you can see, it was frozen, and then, after aborting it finished printing the last message about the connection failing for hpc2020 (which has to be done through `ecaccess` and hence the failure).

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 5, 2023, 09:33

What I've tried is to: 

Laptop:

```bash
(base) dbeltran@ bsces107894:~$ ecaccess-certificate-create 
Please enter your user-id: xxx
Your passcode: 
(base) dbeltran@ bsces107894:~$ ecaccess-queue-list 
ecs             Slurm           submission on ecs (INIT=1400,WAIT=54,EXEC=115,DONE=8774,STOP=90)
hpc             Slurm           submission on hpc (INIT=195,WAIT=7,EXEC=5,DONE=921,STOP=98)
```

hub:

```bash
[dbeltran@ bsceshub02 dbeltran]$ module load ecaccess-webtoolkit
ecaccess-webtoolkit        ecaccess-webtoolkit/6.3.1         
[dbeltran@ bsceshub02 dbeltran]$ ecaccess-queue-list
# block forever
```

**Comment by kinow** [comment]
In GitLab by @ spalomas on Oct 5, 2023, 10:14

Hi @dbeltrankyl. Yes, no job is submitted on the remote platform (squeue).

@eferre1 I made this change just to check if the error persisted when using any other queue. Originally I used `ecs`.
I'll try again and validate if I'm in the same complex before using squeue.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 5, 2023, 10:19

I had a similar problem last night in the hub. I had to rename the certificate file in my $HOME, after that I was able to create a new one and it works fine.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 5, 2023, 10:27

now it seems like the hub is having issues, it cannot connect to any platform?

```
autosubmit -lc DEBUG run a6ij
[...]
Autosubmit is running with v3.15.0b0
Running job data structure
Backing up jobs_data...
Jobs_data database backup completed.
Checking the connection to all platforms in use
[nothing happens]
```

**Comment by kinow** [comment]
In GitLab by @fbeninca on Oct 5, 2023, 10:28

Hi @dbeltrankyl

can you try with what @etiennesky says and let me know.

In any case, we have an hardware issue with the whole archive, so if it
is related to access to files in esarchive, probably this is the reason.
Operations contacted IBM to fix the problem ASAP, but until this is not
done, we will experience instabilities (with all BSC infrastructure
mounting esarchive, so workstations, virtual machines, websites, etc ...).

If we can isolate the origin of the problem and we can be sure that is
not related to storage, but to connection or whatever, then we can check it.

Thanks,

F.

<details><summary>...</summary>

On 10/05/2023 10:19 AM, Etienne Tourigny (@etiennesky) wrote:
> GitLab
>
> Etienne Tourigny <https://earth.bsc.es/gitlab/etourign> commented on a
> discussion
> <https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1139#note_235093>:
>
> I had a similar problem last night in the hub. I had to rename the
> certificate file in my $HOME, after that I was able to create a new
> one and it works fine.
>
> —
> Reply to this email directly or view it on GitLab
> <https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1139#note_235093>.
> You're receiving this email because of your account on earth.bsc.es
> <https://earth.bsc.es/gitlab>. Unsubscribe
> <https://earth.bsc.es/gitlab/-/sent_notifications/REDACTED/unsubscribe>
> from this thread · Manage all notifications
> <https://earth.bsc.es/gitlab/-/profile/notifications> · Help
> <https://earth.bsc.es/gitlab/help>
>

-- 
----------------------------------------------------------------------
Francesco Benincasa
Senior Research Engineer - Earth Sciences Department
Barcelona Supercomputing Center - Centro Nacional de Supercomputación
Plaça Eusebi Güell 1-3, 08034 Barcelona, Spain
mailto: francesco.benincasa@ bsc.es
BSC Earth Sciences DDT: ............ https://tinyurl.com/bsc-ddt
Barcelona Dust Regional Center: .... http://dust.aemet.es/
----------------------------------------------------------------------

</details>

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 5, 2023, 10:31

Thanks @fbeninca 

Note, I just had the issue again, I could not get anything from ecaccess-certificate-list. So I renamed the certificate (again) and generated a new one, it works for now...

**Comment by kinow** [comment]
In GitLab by @fbeninca on Oct 5, 2023, 10:41

And have you used this from other machines?

Thanks,
F.

<details><summary>...</summary>

On 10/05/2023 10:31 AM, Etienne Tourigny (@etiennesky) wrote:
> GitLab
>
> Etienne Tourigny <https://earth.bsc.es/gitlab/etourign> commented on a
> discussion
> <https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1139#note_235098>:
>
> Thanks @fbeninca <https://earth.bsc.es/gitlab/fbeninca>
>
> Note, I just had the issue again, I could not get anything from
> ecaccess-certificate-list. So I renamed the certificate (again) and
> generated a new one, it works for now...
>
> —
> Reply to this email directly or view it on GitLab
> <https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1139#note_235098>.
> You're receiving this email because you have been mentioned on
> earth.bsc.es <https://earth.bsc.es/gitlab>. Unsubscribe
> <https://earth.bsc.es/gitlab/-/sent_notifications/REDACTED/unsubscribe>
> from this thread · Manage all notifications
> <https://earth.bsc.es/gitlab/-/profile/notifications> · Help
> <https://earth.bsc.es/gitlab/help>
>

-- 
----------------------------------------------------------------------
Francesco Benincasa
Senior Research Engineer - Earth Sciences Department
Barcelona Supercomputing Center - Centro Nacional de Supercomputación
Plaça Eusebi Güell 1-3, 08034 Barcelona, Spain
mailto: francesco.benincasa@ bsc.es
BSC Earth Sciences DDT: ............ https://tinyurl.com/bsc-ddt
Barcelona Dust Regional Center: .... http://dust.aemet.es/
----------------------------------------------------------------------

</details>

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 5, 2023, 10:47

no, I don't use ecaccess from any other machine, I connect via teleport and ssh only

**Comment by kinow** [comment]
In GitLab by @eferre1 on Oct 5, 2023, 10:58

The problem is that ecaccess only works from the hub due to the version, the one available in any other machine is deprecated and it cannot be updated (I don't recall exactly where we discussed this, I'm looking for it).

PS: there are mentions to the ecaccess version change in https://earth.bsc.es/gitlab/es/autosubmit/-/issues/917#note_193645

**Comment by kinow** [comment]
In GitLab by @fbeninca on Oct 5, 2023, 11:01

Thanks,

and how we can verify if is a problem related to storage or other
reason? @dbeltrankyl you are able to launch it from your laptop, isn't it?
If you try several times, does it give you any error related to the
certificate?

I'm not able to reproduce it, so I will need that people using ecaccess
help me.

Cheers,

F.

<details><summary>...</summary>

On 10/05/2023 10:58 AM, Eric Ferrer (@eferre1) wrote:
> GitLab
>
> Eric Ferrer <https://earth.bsc.es/gitlab/eferre1> commented on a
> discussion
> <https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1139#note_235107>:
>
> The problem is that ecaccess only works from the hub due to the
> version, the one available in any other machine is deprecated and it
> cannot be updated (I don't recall exactly where we discussed this, I'm
> looking for it).
>
> —
> Reply to this email directly or view it on GitLab
> <https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1139#note_235107>.
> You're receiving this email because of your account on earth.bsc.es
> <https://earth.bsc.es/gitlab>. Unsubscribe
> <https://earth.bsc.es/gitlab/-/sent_notifications/REDACTED/unsubscribe>
> from this thread · Manage all notifications
> <https://earth.bsc.es/gitlab/-/profile/notifications> · Help
> <https://earth.bsc.es/gitlab/help>
>

-- 
----------------------------------------------------------------------
Francesco Benincasa
Senior Research Engineer - Earth Sciences Department
Barcelona Supercomputing Center - Centro Nacional de Supercomputación
Plaça Eusebi Güell 1-3, 08034 Barcelona, Spain
mailto: francesco.benincasa@ bsc.es
BSC Earth Sciences DDT: ............ https://tinyurl.com/bsc-ddt
Barcelona Dust Regional Center: .... http://dust.aemet.es/
----------------------------------------------------------------------

</details>

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 5, 2023, 11:16

Hello @fbeninca 

> Note, I just had the issue again, I could not get anything from ecaccess-certificate-list. So I renamed the certificate (again) and generated a new one, it works for now...

This doesn't work for me, 

```bash
mv .eccert.crt .eccert2.crt
[dbeltran@ bsceshub02 dbeltran]$ ecaccess-certificate-create 
#block forever
```
I also tried to reuse the one generated in my laptop which I'm sure that works 100%...

```bash
scp .eccert.crt dbeltran@hub:~
ssh dbeltran@hub
[dbeltran@ bsceshub02 dbeltran]$ module load ecaccess-webtoolkit       
[dbeltran@ bsceshub02 dbeltran]$ ecaccess-queue-list 
#block forever
```

> @dbeltrankyl you are able to launch it from your laptop, isn't it? If you try several times, does it give you any error related to the certificate?

It always works from the laptop

**Comment by kinow** [comment]
In GitLab by @eferre1 on Oct 5, 2023, 14:15

Hi @fbeninca, I tried removing the `.eccert.crt` and it worked, but only on the terminal session were I removed it and regenerated the certificate. Opening a new terminal, where I loaded the `ecaccess` module (and another autosubmit version, since I have 2 different experiments running with AS-3.15 and AS-4.0.96 versions), and on this second one it didn't work.

**Comment by kinow** [comment]
In GitLab by @eferre1 on Oct 10, 2023, 09:45

Hi @fbeninca, I'm not sure if it was due to the maintenance or whatnot, but at least for now, it is working fine for me, creating the certificate in one terminal, and then opening a new one where I ran the `list` command it worked and didn't froze.

**Comment by kinow** [comment]
In GitLab by @fbeninca on Oct 10, 2023, 10:14

Great,

thanks for reporting, please can the others (Dani, Etienne) try on their
side and check if it works or not?

Cheers,

F.

<details><summary>...</summary>

On 10/10/2023 09:45 AM, Eric Ferrer (@eferre1) wrote:
> GitLab
>
> Eric Ferrer <https://earth.bsc.es/gitlab/eferre1> commented on a
> discussion
> <https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1139#note_235781>:
>
> Hi @fbeninca <https://earth.bsc.es/gitlab/fbeninca>, I'm not sure if
> it was due to the maintenance or whatnot, but at least for now, it is
> working fine for me, creating the certificate in one terminal, and
> then opening a new one where I ran the |list| command it worked and
> didn't froze.
>
> —
> Reply to this email directly or view it on GitLab
> <https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1139#note_235781>.
> You're receiving this email because you have been mentioned on
> earth.bsc.es <https://earth.bsc.es/gitlab>. Unsubscribe
> <https://earth.bsc.es/gitlab/-/sent_notifications/REDACTED/unsubscribe>
> from this thread · Manage all notifications
> <https://earth.bsc.es/gitlab/-/profile/notifications> · Help
> <https://earth.bsc.es/gitlab/help>
>

-- 
----------------------------------------------------------------------
Francesco Benincasa
Senior Research Engineer - Earth Sciences Department
Barcelona Supercomputing Center - Centro Nacional de Supercomputación
Plaça Eusebi Güell 1-3, 08034 Barcelona, Spain
mailto: francesco.benincasa@ bsc.es
BSC Earth Sciences DDT: ............ https://tinyurl.com/bsc-ddt
Barcelona Dust Regional Center: .... http://dust.aemet.es/
----------------------------------------------------------------------

</details>

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 10, 2023, 10:25

Hello, 

It also works for me, 

thanks

**Comment by kinow** [comment]
In GitLab by @fbeninca on Oct 11, 2023, 12:03

OK I close this for now, please feel free to reopen it.
