### ISSUE TITLE
autosubmit create gives [CRITICAL] invalid literal for int() with base 10: '' [eCode=7070]

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1141]
In GitLab by @chhaine on Oct 4, 2023, 15:24

( This is a template for bug reports. Please fill in the relevant information and delete the rest. )

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v4.0.92

### Expid affected(If applicable)

a0c6 (lumi_vm_lumi)

### Which task has issues? Where is the log(If applicable)

`$ autosubmit create a0c6` fails

### Summary

Experiment is a copy of a056:
- tried to change conf files `$ vim /appl/AS/AUTOSUBMIT_DATA/a0c6/conf/` to fetch a different branch of the workflow. 
- did `$ autosubmit refresh a0c6` successfully
- `$ autosubmit create a0c6` fails on the following:
```
$ autosubmit create a0c6
Autosubmit is running with 4.0.92
Preparing .lock file to avoid multiple instances with same expid.
Using project folder: /appl/AS/AUTOSUBMIT_DATA/a0c6/proj

Checking configuration files...
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Loading parameters...
Traceback (most recent call last):
  File "/appl/AS/4.0.92/lib/python3.9/site-packages/autosubmit-4.0.92-py3.9.egg/autosubmit/autosubmit.py", line 4572, in create
    num_chunks = as_conf.get_num_chunks()
  File "/appl/AS/4.0.92/lib/python3.9/site-packages/autosubmitconfigparser-1.0.48-py3.9.egg/autosubmitconfigparser/config/configcommon.py", line 1876, in get_num_chunks
    return int(self.get_section(['EXPERIMENT', 'NUMCHUNKS']))
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/AS/4.0.92/lib/python3.9/site-packages/autosubmit-4.0.92-py3.9.egg/EGG-INFO/scripts/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/appl/AS/4.0.92/lib/python3.9/site-packages/autosubmit-4.0.92-py3.9.egg/autosubmit/autosubmit.py", line 690, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/appl/AS/4.0.92/lib/python3.9/site-packages/autosubmit-4.0.92-py3.9.egg/autosubmit/autosubmit.py", line 4737, in create
    raise AutosubmitCritical(str(e), 7070)
log.log.AutosubmitCritical:  
 [CRITICAL] invalid literal for int() with base 10: '' [eCode=7070]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```
Doc says to report such errors.

### Steps to reproduce

1- log onto Lumi VM.
2- `autosubmit create a0c6`

### What is the current bug behavior?

See above.

### What is the expected correct behavior?

Successful completion of the `autosubmit create` command.

### Relevant logs and/or screenshots(if applicable)

(Paste any relevant logs - use code blocks (```) to format console output, logs, and code, as
it's very hard to read otherwise.)

### Any other relevant information(if applicable)

()

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2023, 16:04

Hello @chhaine ,

That happens when your current experiment configuration doesn't have set some of the following parameters:

```yaml
EXPERIMENT:
  CALENDAR: standard
  CHUNKSIZE: 1
  CHUNKSIZEUNIT: day
  DATELIST: 20200201
  MEMBERS: fc0
  NUMCHUNKS: 3
```

**Comment by kinow** [comment]
In GitLab by @chhaine on Oct 4, 2023, 16:10

`/appl/AS/AUTOSUBMIT_DATA/a0c6/conf/metadata/experiment_data.yml` reads
```
EXPERIMENT:
  CALENDAR: standard
  CHUNKSIZE: 1
  CHUNKSIZEUNIT: day
  DATELIST: 20200201
  MEMBERS: fc0
  NUMCHUNKS: 3
```

**Comment by kinow** [comment]
In GitLab by @chhaine on Oct 4, 2023, 16:15

All editing I did was changing one line 
```
#  PROJECT_BRANCH: "app-v0.1.7"
  PROJECT_BRANCH: "dev-model-app"
```
On an experiment that worked fine.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2023, 16:20

Hello, 

That `/appl/AS/AUTOSUBMIT_DATA/a0c6/conf/metadata/experiment_data.yml` is generated on a successful create, likely when the PROJECT_BRANCH was pointing to "app-v0.1.7" 


https://earth.bsc.es/gitlab/digital-twins/de_340/workflow/-/blob/app-v0.1.7/conf/applications/urban/request.yml has these lines. 

But the current request.yml that you're loading doesn't

https://earth.bsc.es/gitlab/digital-twins/de_340/workflow/-/blob/dev-model-app/conf/applications/urban/request.yml?ref_type=heads

FYI @ainagaya , @franra9

**Comment by kinow** [comment]
In GitLab by @chhaine on Oct 4, 2023, 16:25

Thank you, now it makes more sense to me.

**Comment by kinow** [comment]
In GitLab by @franra9 on Oct 4, 2023, 16:38

Hi, this is usually an issue with some wrongly placed parameter. Please revise your namelists. Make sure that you are pointing to the right application in "conf/main.yml" and that the data request (proj/proj/workflow/conf/applications/YOURAPP/request.yml) has all fields correctly

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2023, 16:40

Hello @franra9 ,

I've fyi you because the same file in different branches have a different structure, not sure if it is intended

**Comment by kinow** [comment]
In GitLab by @franra9 on Oct 4, 2023, 17:03

Hi @dbeltrankyl  @chhaine 

I discourage the use of `app-model-app` branch as as Dani says (thanks dani for pointing out), the configuration files are much different, as they serve different purposes (development vs app-users). Please stick to the "official" releases, that is `app-v0.1.7`. If the error persists, update this issue or contact myself via mattermost.

Thanks

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 5, 2023, 08:21

I'll close the issue as this has been solved, feel free of reopen it if it is not the case
