### ISSUE TITLE
Lost shell connection

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#115]
In GitLab by @obellprat on May 6, 2016, 10:53

2016-05-05 20:59:25,091: radical.saga.cpi    : MainProcess                     : MainThread     : ERROR   : IncorrectState: Lost shell connection to mn-pr1eaq00
2016-05-05 20:59:25,091: radical.utils       : MainProcess                     : MainThread     : ERROR   : Could not create lease object
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/radical.utils-0.40-py2.7.egg/radical/utils/lease_manager.py", line 175, in _create_object
    obj = _LeaseObject (self, self._log, creator, args)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/radical.utils-0.40-py2.7.egg/radical/utils/lease_manager.py", line 33, in __init__
    self.obj        = creator (*args)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_file.py", line 274, in _shell_creator
    return sups.PTYShell (url, self.get_session(), self._logger)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell.py", line 243, in __init__
    posix=self.posix)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 209, in initialize
    "Lost shell connection to %s" % info['host_str'])
IncorrectState: Lost shell connection to mn-pr1eaq00 (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +209 (initialize)  :  "Lost shell connection to %s" % info['host_str']))
^[[31m[CRITICAL] Unhandled exception on Autosubmit: Lost shell connection to mn-pr1eaq00 (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +209 (initialize)  :  "Lost shell connection to %s" % info['host_str']))
Traceback (most recent call last):

**Comment by kinow** [comment]
In GitLab by @obellprat on May 6, 2016, 10:54

The log can be found here ~obellpra/a05l_out.log (too large for attachment, 72MB!)

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 10, 2016, 18:24

@obellprat @fmassonn @ cprodhomme @ macosta Could you try setting the `export SAGA_PTY_SSH_TIMEOUT=60` or `export SAGA_PTY_SSH_TIMEOUT=90` rather than `120` to see if it is due to that ? Thanks and sorry for the inconvenience

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 13, 2016, 16:22

fixed in 57c509cc061530a4bfd59d689fbdcfdc95af75f9
