### ISSUE TITLE
Job tagged FAILED while it is completed on the remote

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#116]
In GitLab by @fmassonn on May 10, 2016, 09:57

Hey,

I'm using autosubmit 3.3.1. and running my autosubmit command on bscesautosubmit01 as:

expid=a065; export SAGA_PTY_SSH_TIMEOUT=120; nohup autosubmit run ${expid} >& ~/logs/autosubmit/log_${expid} &

 It happens regularly that one of my jobs finishes successfully on the HPC but is marked as failed by autosubmit, which causes everything to stop.

Example:
Experiment a064: the job a065_19930101_2_ENKF finished successfully (file /gpfs/scratch/cns96/cns96177/a064/LOG_a064/a064_19930101_2_ENKF_COMPLETED is well created) but autosubmit stopped (see autosubmit log file: /home/Earth/fmassonn/logs/autosubmit/log_a064).

It looks like this is related to SSH connection issues: the end of the log file:

 File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_file.py", line 274, in _shell_creator
    return sups.PTYShell (url, self.get_session(), self._logger)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell.py", line 243, in __init__
    posix=self.posix)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 209, in initialize
    "Lost shell connection to %s" % info['host_str'])
IncorrectState: Lost shell connection to mn-cns96 (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +209 (initialize)  :  "Lost shell connection to %s" % info['host_str']))
No more jobs to run.
Some jobs have failed and reached maximun retrials

I have to fix this manually each time, so I would appreciate any help.
François

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 10, 2016, 12:46

Hi @fmassonn ,
This is somehow related to #109 . The SSH connection suddenly got lost. Autosubmit captured a messsage from MareNostrum "Lost shell connection" and understood that the status was FAILED. We will implement a security check and retry mechanism here in case of a connectivity issue. However the real workaround is to fix the issue in the SAGA library which is loosing connections. It is being investigated here: https://github.com/radical-cybertools/saga-python/issues/527 and here: https://github.com/radical-cybertools/saga-python/issues/533
Meanwhile I would suggest to run just one experiment in the same machine. You could use others workstations.

 @obellprat @ cprodhomme @ macosta @ jlope2

**Comment by kinow** [comment]
In GitLab by @fmassonn on May 10, 2016, 12:49

Hi Mingu @dmanubens 
Thanks for detailing this issue. I'll use other workstations. Isn't that a problem if I'm running on another workstation if the person owning the workstation is him/herself running an autosubmit instance?
François

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 10, 2016, 13:09

Good point. So far we haven't been able to reproduce the problem using 2 user ID from the same workstation. The problem is just running under the same user ID and same workstation more than 1 Autosubmit instance.

**Comment by kinow** [comment]
In GitLab by @fmassonn on May 10, 2016, 13:10

OK, I'll try that and let you know if I've the same problem. But this actually should work since many of use already run on the same machine (bscesautosubmit01)

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 13, 2016, 16:22

fixed in 57c509cc061530a4bfd59d689fbdcfdc95af75f9

**Comment by kinow** [comment]
In GitLab by @fmassonn on May 23, 2016, 09:27

Hi,
I still get the same problem (/home/Earth/fmassonn/logs/autosubmit/log_a06m_20160522182829)

I was running this experiment exclusively on my machine (i.e. no other autosubmit job) and I'm using the latest version of autosubmit (3.4.1).

François

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 23, 2016, 14:22

Hi we have detected another point in the Autosubmit code where it could be failing. 
https://earth.bsc.es/gitlab/es/autosubmit/blob/e62b1e604e88d71b53eefe9daa3f7666ba808dbf/autosubmit/platforms/platform.py#L441
We will implement a similar fix as in 57c509cc

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 24, 2016, 11:43

Same problem reproduced:
```
NoSuccess: read from process failed '[Errno 5] Input/output error' : (*OTE_SETUP May 23 17:53
PROMPT-0->1843611 bsc3206 RUN   sequential login1      s01         *OTE_SETUP May 23 17:53
PROMPT-0->1843611 bsc3206 RUN   sequential login1      s01         *OTE_SETUP May 23 17:53
PROMPT-0->Shared connection to mn1.bsc.es closed.
) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
[CRITICAL] Unhandled exception on Autosubmit: read from process failed '[Errno 5] Input/output error' : (*OTE_SETUP May 23 17:53
PROMPT-0->1843611 bsc3206 RUN   sequential login1      s01         *OTE_SETUP May 23 17:53
PROMPT-0->1843611 bsc3206 RUN   sequential login1      s01         *OTE_SETUP May 23 17:53
PROMPT-0->Shared connection to mn1.bsc.es closed.
) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.4.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.4.1-py2.7.egg/autosubmit/autosubmit.py", line 285, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.4.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.4.1-py2.7.egg/autosubmit/autosubmit.py", line 608, in run_experiment
    if prev_status != job.update_status(platform.check_job(job.id)):
  File "/shared/earth/software/autosubmit/3.4.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.4.1-py2.7.egg/autosubmit/platforms/platform.py", line 442, in check_job
    if jobid not in self.service.jobs:
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/job/service.py", line 378, in list
    return self._adaptor.list (ttype=ttype)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/shared/earth/software/autosubmit/3.4.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.4.1-py2.7.egg/autosubmit/platforms/mn_adaptor.py", line 865, in list
    ret, out, _ = self.shell.run_sync("%s -a -noheader" % 'bjobs')
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell.py", line 648, in run_sync
    self.pty_shell.flush ()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (*OTE_SETUP May 23 17:53
PROMPT-0->1843611 bsc3206 RUN   sequential login1      s01         *OTE_SETUP May 23 17:53
PROMPT-0->1843611 bsc3206 RUN   sequential login1      s01         *OTE_SETUP May 23 17:53
PROMPT-0->Shared connection to mn1.bsc.es closed.
) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
```

**Comment by kinow** [comment]
In GitLab by @fmassonn on Jun 9, 2016, 12:52

Hi,

This problem happened again with Autosubmit 3.6

Experiment a077
log: `/home/Earth/fmassonn/logs/autosubmit/log_a077_20160606201431_bscesautosubmit01`

`^[[33m[WARNING] Job a077_19580101_fc00_22_SIM seemed to be completed but there is no COMPLETED file^[[0m^[[39m
^[[33mJob a077_19580101_fc00_22_SIM is FAILED^[[0m^[[39m
2016-06-09 02:07:31,020: radical.saga.pty    : MainProcess                     : Thread-2       : ERROR   : flushing failed
Traceback (most recent call last):`

but the job successfully finished:

`bsc32526@login1:/gpfs/scratch/bsc32/bsc32526> ls /gpfs/scratch/bsc32/bsc32526/a077/LOG_a077/a077_19580101_fc00_22_SIM_COMPLETED
/gpfs/scratch/bsc32/bsc32526/a077/LOG_a077/a077_19580101_fc00_22_SIM_COMPLETED
`

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jun 9, 2016, 13:10

hi @fmassonn you are looking a log file created the 06/06 (still Autosubmit 3.5) while the last log I see is created 09/06 `tmp/20160609_125554_run.log `.
Could be that this job was launched with Autosubmit 3.5 and again with Autosubmit 3.6 by mistake ?

**Comment by kinow** [comment]
In GitLab by @fmassonn on Jun 9, 2016, 13:20

Hello,
I think you are right, thanks for pointing this out! I thought all my experiments were running with 3.6 but this one was not, obviously. 
Sorry for the inconvenience,
François
