### ISSUE TITLE
unknown locale: UTF-8: Autosubmit problem related to Python library?

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#117]
In GitLab by @obellprat on May 10, 2016, 12:11

Hi,

I can't use autosubmit anymore, I get a similar error as the one related to the Python library but this time module unload Python won't help.

If I type:

module purge

module load autosubmit

autosubmit -v

Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/bin/autosubmit", line 4, in <module>
    __import__('pkg_resources').run_script('autosubmit==3.3.1', 'autosubmit')
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/EGG-INFO/scripts/autosubmit", line 29, in <module>
    from autosubmit.autosubmit import Autosubmit
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/autosubmit.py", line 69, in <module>
    from monitor.monitor import Monitor
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/monitor/monitor.py", line 35, in <module>
    import matplotlib.pyplot as plt
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

@dmanubens and @fbeninca could you have a look? @fmassonn @ cprodhomme @Eleftheriaexarchou @vsicardi  do you have the same problem?

Best from Prague,
Omar

**Comment by kinow** [comment]
In GitLab by @fmassonn on May 10, 2016, 12:14

Hey,

I can't reproduce your error @obellprat 

> fmassonn@ bscearth321: ~ >> module purge ; module load autosubmit ; autosubmit -v

> 3.3.1

**Comment by kinow** [comment]
In GitLab by @ jlope2 on May 10, 2016, 12:26

Can you check if you have the LANG env variable defined?

What do you get if you run the next command on the terminal/konsole?

> echo $LANG

**Comment by kinow** [comment]
In GitLab by @obellprat on May 10, 2016, 12:36

Hi,

the variable LANG seems not defined, echo $LANG returns a blank entry.

**Comment by kinow** [comment]
In GitLab by @ jlope2 on May 10, 2016, 12:56

Try to set a value to this env variable, for example with:

> export LANG=en_GB.UTF-8

Then check if now your LANG env variable has a value:

> echo $LANG

Finally try to rerun the autosubmit and see what happens (if the error persists)

Thanks!

**Comment by kinow** [comment]
In GitLab by @obellprat on May 10, 2016, 13:24

I tried this, but the error still persists, although 

obellpra@ bscearth315:~$ echo $LANG

en_GB.UTF-8

**Comment by kinow** [comment]
In GitLab by @ jlope2 on May 10, 2016, 14:48

The given error is the same than previously?

**Comment by kinow** [comment]
In GitLab by @obellprat on May 10, 2016, 14:50

Yes, its the same: 

obellpra@ bscearth315:~/Dropbox$ echo $LANG

en_GB.UTF-8

obellpra@ bscearth315:~/Dropbox$ autosubmit -v 

Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/bin/autosubmit", line 4, in <module>
    __import__('pkg_resources').run_script('autosubmit==3.3.1', 'autosubmit')
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/EGG-INFO/scripts/autosubmit", line 29, in <module>
    from autosubmit.autosubmit import Autosubmit
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/autosubmit.py", line 69, in <module>
    from monitor.monitor import Monitor
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/monitor/monitor.py", line 35, in <module>
    import matplotlib.pyplot as plt
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 10, 2016, 15:01

could you type `locale` in the terminal and give us the output?

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 10, 2016, 15:06

it should be:
```
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

https://blog.remibergsma.com/2012/07/10/setting-locales-correctly-on-mac-osx-terminal-application/

**Comment by kinow** [comment]
In GitLab by @obellprat on May 10, 2016, 15:21

Hi,

the variable LC_CTYPE was blank as well. 

export LC_CTYPE=en_GB.UTF-8

has fixed the problem, I don't understand what this means though. I'll let you know if it occurs again.

Thanks!
Omar

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 10, 2016, 16:16

Title changed from **Autosubmit problem related to Python library?** to **unknown locale: UTF-8: Autosubmit problem related to Python library?**

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 10, 2016, 16:19

@omula @kserradell I think those variables shoudln't be unset after `module purge` ? could you double check ?

**Comment by kinow** [comment]
In GitLab by @obellprat on May 16, 2016, 10:50

Hi,
the problem repeated itself, please let me know what I should do that it doesn't repeat.

@omula @kserradell

**Comment by kinow** [comment]
In GitLab by @ jlope2 on May 17, 2016, 07:17

Hi @obellprat, a possible workaround could be writing the environment variable export command on one of these files: .bashrc, .bash_profile or .profile.

However, it will be better that @kserradell or @omula reviews your situation, perhaps you have something wrong-defined.

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Mar 29, 2017, 11:25

I proceed to close this issue.

If you need more information you can open a new issue in the new ticketing repository.

Thanks!
