### ISSUE TITLE
[documentation] At least one of our wrapper examples fail to be reproduced

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1173]
Found while testing the !387 for @dbeltrankyl .

This example: https://autosubmit.readthedocs.io/en/master/userguide/wrappers/index.html#advanced-example-set-up-an-crossdate-wrapper

It provides `EXPERIMENT`, `JOBS`, and `WRAPPERS` configuration keys. Using those values, then `autosubmit refresh`, `autosubmit create -cw` results in the following:

```bash
(autosubmit4) kinow@ranma:~/Development/python/workspace/autosubmit$ autosubmit create -cw a003
/home/kinow/mambaforge/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.1.0')
Autosubmit is running with 4.1.0
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
Platforms sections: OK
Jobs sections OK
wrappers OK
Autosubmit general sections OK
Loading parameters...

Creating the jobs list...
Loading JobList
[ERROR] Autosubmit will use a backup for recover the job_list[eCode=6010]
Loading backup JobList
Loading JobList
[ERROR] Autosubmit will use a backup for recover the job_list[eCode=6010]
Loading backup JobList
Creating jobs...
Adding dependencies to the graph..
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4681, in create
    job_list.generate(as_conf,date_list, member_list, num_chunks, chunk_ini, parameters, date_format,
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 256, in generate
    self._add_dependencies(date_list, member_list, chunk_list, self._dic_jobs)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 319, in _add_dependencies
    self._manage_job_dependencies(dic_jobs, job, date_list, member_list, chunk_list, dependencies_keys,
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 1001, in _manage_job_dependencies
    filters_to_apply = self._filter_current_job(job, copy.deepcopy(dependency.relationships))
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 844, in _filter_current_job
    filters_to_apply = self._check_dates(relationships, current_job)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 653, in _check_dates
    filters_to_apply_c = self._check_chunks({"CHUNKS_FROM": (filter.pop("CHUNKS_FROM"))}, current_job)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 695, in _check_chunks
    filters_to_apply = self._check_relationship(relationships, "CHUNKS_FROM", current_job.chunk)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 613, in _check_relationship
    status = relationship.pop("STATUS", relationships.get("STATUS", None))
AttributeError: 'NoneType' object has no attribute 'pop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/bin/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 701, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4787, in create
    raise AutosubmitCritical(str(e), 7070)
log.log.AutosubmitCritical:  
 [CRITICAL] 'NoneType' object has no attribute 'pop' [eCode=7070]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

The example above is from the Destine-1025 branch, but I get a similar output for `master` (minus the errors about using the backup to recover).

**Comment by kinow** [comment]
Thanks @dbeltrankyl 

I get this on your branch for the workflow above:

![image](https://my-gitlab-bucket.s3.amazonaws.com/902354155/b9ad1dfebef2858a85bc9bbfb245e39bba6597e120513df78cca0ec48964fde9/image.png)

While on master:

```
Adding dependencies...
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4694, in create
    prev_job_list = Autosubmit.load_job_list(
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 5959, in load_job_list
    job_list.generate(date_list, as_conf.get_member_list(), as_conf.get_num_chunks(), as_conf.get_chunk_ini(),
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 243, in generate
    self._add_dependencies(date_list, member_list, chunk_list, dic_jobs, self.graph)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 320, in _add_dependencies
    self._manage_job_dependencies(dic_jobs, _job, date_list, member_list, chunk_list, dependencies_keys,
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 985, in _manage_job_dependencies
    filters_to_apply = self._filter_current_job(job, copy.deepcopy(dependency.relationships))
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 858, in _filter_current_job
    filters_to_apply = self._check_dates(relationships, current_job)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 669, in _check_dates
    if len(filters_to_apply_c) > 0 and len(filters_to_apply_c[0]) > 0:
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/bin/autosubmit", line 37, in main
    return_value = Autosubmit.parse_args()
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 694, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4837, in create
    raise AutosubmitCritical(str(e), 7070)
log.log.AutosubmitCritical:  
 [CRITICAL] 0 [eCode=7070]
```

So this example only works after the workflow optimizations branch is merged, correct?
