### ISSUE TITLE
[documentation] At least one of our wrapper examples fail to be reproduced

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1173]
Found while testing the !387 for @dbeltrankyl .

This example: https://autosubmit.readthedocs.io/en/master/userguide/wrappers/index.html#advanced-example-set-up-an-crossdate-wrapper

It provides `EXPERIMENT`, `JOBS`, and `WRAPPERS` configuration keys. Using those values, then `autosubmit refresh`, `autosubmit create -cw` results in the following:

```bash
(autosubmit4) kinow@ranma:~/Development/python/workspace/autosubmit$ autosubmit create -cw a003
/home/kinow/mambaforge/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.1.0')
Autosubmit is running with 4.1.0
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
Platforms sections: OK
Jobs sections OK
wrappers OK
Autosubmit general sections OK
Loading parameters...

Creating the jobs list...
Loading JobList
[ERROR] Autosubmit will use a backup for recover the job_list[eCode=6010]
Loading backup JobList
Loading JobList
[ERROR] Autosubmit will use a backup for recover the job_list[eCode=6010]
Loading backup JobList
Creating jobs...
Adding dependencies to the graph..
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4681, in create
    job_list.generate(as_conf,date_list, member_list, num_chunks, chunk_ini, parameters, date_format,
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 256, in generate
    self._add_dependencies(date_list, member_list, chunk_list, self._dic_jobs)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 319, in _add_dependencies
    self._manage_job_dependencies(dic_jobs, job, date_list, member_list, chunk_list, dependencies_keys,
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 1001, in _manage_job_dependencies
    filters_to_apply = self._filter_current_job(job, copy.deepcopy(dependency.relationships))
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 844, in _filter_current_job
    filters_to_apply = self._check_dates(relationships, current_job)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 653, in _check_dates
    filters_to_apply_c = self._check_chunks({"CHUNKS_FROM": (filter.pop("CHUNKS_FROM"))}, current_job)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 695, in _check_chunks
    filters_to_apply = self._check_relationship(relationships, "CHUNKS_FROM", current_job.chunk)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 613, in _check_relationship
    status = relationship.pop("STATUS", relationships.get("STATUS", None))
AttributeError: 'NoneType' object has no attribute 'pop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/bin/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 701, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4787, in create
    raise AutosubmitCritical(str(e), 7070)
log.log.AutosubmitCritical:  
 [CRITICAL] 'NoneType' object has no attribute 'pop' [eCode=7070]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

The example above is from the Destine-1025 branch, but I get a similar output for `master` (minus the errors about using the backup to recover).

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2023, 12:21

ah @kinow ,

I updated this section in that merge.. but it was duplicated in changelog.rst and was updated there.

The jobs configuration should be


```yaml
JOBS:
  LOCAL_SETUP:
    FILE: templates/local_setup.sh
    PLATFORM: marenostrum_archive
    RUNNING: once
    NOTIFY_ON: COMPLETED
  LOCAL_SEND_SOURCE:
    FILE: templates/01_local_send_source.sh
    PLATFORM: marenostrum_archive
    DEPENDENCIES: LOCAL_SETUP
    RUNNING: once
    NOTIFY_ON: FAILED
  LOCAL_SEND_STATIC:
    FILE: templates/01b_local_send_static.sh
    PLATFORM: marenostrum_archive
    DEPENDENCIES: LOCAL_SETUP
    RUNNING: once
    NOTIFY_ON: FAILED
  REMOTE_COMPILE:
    FILE: templates/02_compile.sh
    DEPENDENCIES: LOCAL_SEND_SOURCE
    RUNNING: once
    PROCESSORS: '4'
    WALLCLOCK: 00:50
    NOTIFY_ON: COMPLETED
  SIM:
    FILE: templates/05b_sim.sh
    DEPENDENCIES:
      LOCAL_SEND_STATIC:
      REMOTE_COMPILE:
      SIM-1:
      DA-1:
    RUNNING: chunk
    PROCESSORS: '68'
    WALLCLOCK: 00:12
    NOTIFY_ON: FAILED
  LOCAL_SEND_INITIAL_DA:
    FILE: templates/00b_local_send_initial_DA.sh
    PLATFORM: marenostrum_archive
    DEPENDENCIES: LOCAL_SETUP LOCAL_SEND_INITIAL_DA-1
    RUNNING: chunk
    SYNCHRONIZE: member
    DELAY: '0'
  COMPILE_DA:
    FILE: templates/02b_compile_da.sh
    DEPENDENCIES: LOCAL_SEND_SOURCE
    RUNNING: once
    WALLCLOCK: 00:20
    NOTIFY_ON: FAILED
  DA:
    FILE: templates/05c_da.sh
    DEPENDENCIES:
      SIM:
      LOCAL_SEND_INITIAL_DA:
        CHUNKS_TO: "all"
        DATES_TO: "all"
        MEMBERS_TO: "all"
      COMPILE_DA:
      DA:
        DATES_FROM:
          "20120201":
            CHUNKS_FROM:
              1:
                DATES_TO: "20120101"
                CHUNKS_TO: "1"
    RUNNING: chunk
    SYNCHRONIZE: member
    DELAY: '0'
    WALLCLOCK: 00:12
    PROCESSORS: '256'
    NOTIFY_ON: FAILED
```

**Comment by kinow** [comment]
Thanks @dbeltrankyl 

I get this on your branch for the workflow above:

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/ebf9016aea943704868b89684f898150/image.png)

While on master:

```
Adding dependencies...
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4694, in create
    prev_job_list = Autosubmit.load_job_list(
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 5959, in load_job_list
    job_list.generate(date_list, as_conf.get_member_list(), as_conf.get_num_chunks(), as_conf.get_chunk_ini(),
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 243, in generate
    self._add_dependencies(date_list, member_list, chunk_list, dic_jobs, self.graph)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 320, in _add_dependencies
    self._manage_job_dependencies(dic_jobs, _job, date_list, member_list, chunk_list, dependencies_keys,
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 985, in _manage_job_dependencies
    filters_to_apply = self._filter_current_job(job, copy.deepcopy(dependency.relationships))
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 858, in _filter_current_job
    filters_to_apply = self._check_dates(relationships, current_job)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 669, in _check_dates
    if len(filters_to_apply_c) > 0 and len(filters_to_apply_c[0]) > 0:
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/bin/autosubmit", line 37, in main
    return_value = Autosubmit.parse_args()
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 694, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4837, in create
    raise AutosubmitCritical(str(e), 7070)
log.log.AutosubmitCritical:  
 [CRITICAL] 0 [eCode=7070]
```

So this example only works after the workflow optimizations branch is merged, correct?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2023, 12:29

In master, it won't work until it is merged

But in v4.0.XXX-branch yes, that should be the 4.0 stuff.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2023, 12:29

It was fixed there when I encountered the issue with select chunk

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2023, 12:29

( Remember that for checking the wrappers you have to add -cw)

**Comment by dbeltrankyl** [comment]
We now have a regression test #2253. This one should be already there as I added all the documentation ones that I had in my laptop
