### ISSUE TITLE
SAGA issues

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#118]
In GitLab by @fmassonn on May 10, 2016, 12:45

Hi,

I'm now having this problem which seems related to the SAGA:

Experiment is a05z, log file is /home/Earth/fmassonn/logs/autosubmit/log_a05z_20160510115609

[CRITICAL] Unhandled exception on Autosubmit: Failed to run Job (['tail: cannot open \xe2\x80\x98/home/Earth/fmassonn/.saga/adaptors/shell_job///state\xe2\x80\x99 for reading: No such file or directory', 'UNKNOWN', 'OK']) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_job.py +712 (_job_run)  :  raise saga.NoSuccess ("Failed to run Job (%s)" % lines))
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/autosubmit.py", line 283, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/autosubmit.py", line 607, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, joblist, platforms_to_test):
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/autosubmit.py", line 663, in submit_ready_jobs
    saga_job.run()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/job/job.py", line 462, in run
    return self._adaptor.run (ttype=ttype)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_job.py", line 1605, in run
    self._id = self.js._job_run (self.jd)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_job.py", line 712, in _job_run
    raise saga.NoSuccess ("Failed to run Job (%s)" % lines)
NoSuccess: Failed to run Job (['tail: cannot open \xe2\x80\x98/home/Earth/fmassonn/.saga/adaptors/shell_job///state\xe2\x80\x99 for reading: No such file or directory', 'UNKNOWN', 'OK']) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_job.py +712 (_job_run)  :  raise saga.NoSuccess ("Failed to run Job (%s)" % lines))

Thanks

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 10, 2016, 12:53

This seems to be a MareNostrum3 problem. At that our some users have been affected and some jobs have failed.

**Comment by kinow** [comment]
In GitLab by @fmassonn on May 10, 2016, 12:59

Should that be reported to Support?

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 10, 2016, 13:04

Yes please.

In this case Autosubmit is not capturing the exception and overall experiment fails. We'll implement a similar security mechanism as in #116

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 13, 2016, 16:21

fixed in 57c509cc061530a4bfd59d689fbdcfdc95af75f9
