### ISSUE TITLE
Legacy jobs from previous runs not affected in new autosubmit create

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1185]
In GitLab by @franra9 on Dec 19, 2023, 10:58

( This is a template for bug reports. Please fill in the relevant information and delete the rest. )

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v4.1.0-beta
### Expid affected(If applicable)

a0g7

### Which task has issues? Where is the log(If applicable)

-

### Summary

Hi I have detected that in the new version, if there is a run that is stopped, if I create the experiment again and run it, the (some) jobs that were not run in the prevoius autosubmit run are submitted again, without respecting the workflow structure of the experiment. 

### Steps to reproduce

Autosubmit run a0g7 -v

cancel run after some time (ctrl + c)

Autosubmit create a0g7 -v

Autosubmit run a0g7 -v

### What is the current bug behavior?

jobs from old run still appear

### What is the expected correct behavior?

Run a clean experiment again

### Relevant logs and/or screenshots(if applicable)

![Screenshot_from_2023-12-19_10-51-03](https://earth.bsc.es/gitlab/es/autosubmit/uploads/c49dd48d05e312f7884834c2500a0677/Screenshot_from_2023-12-19_10-51-03.png)

### Any other relevant information(if applicable)

If i look at the graph (after create or by doing AS monitor before running), all jobs are in waiting status:
![Screenshot_from_2023-12-19_10-45-07](https://earth.bsc.es/gitlab/es/autosubmit/uploads/f36de803ce400c471ed4eb604d9cb229/Screenshot_from_2023-12-19_10-45-07.png)

and I dont have any job running in any queue when doing AS run nor AS create. (`squeue --me` is empty)
()

cc @Lerriola also noticed this behaviour

**Comment by kinow** [comment]
Thank you for reporting and including the details to reproduce it, @franra9 . It does sound like a possible issue caused by the changes in the workflow optimization branch (from which the release you are using was created).

I will try to reproduce it there, and confirm that it doesn't happen on master, and then update this issue (either today or tomorrow).

Did you try with `autosubmit create -f` too?

**Comment by kinow** [comment]
In GitLab by @franra9 on Dec 19, 2023, 12:17

Thanks @kinow I will try with the `-f `flag and report back

**Comment by kinow** [comment]
In GitLab by @franra9 on Dec 19, 2023, 12:30

Hi @kinow 

after create -f I get the jobs that had `non completed` error i the previous run:

 `[ERROR] Job a0g7_19900101_fc0_1_2_OPA_10U_RAW_DAILY_NOON completion check failed. There is no COMPLETED file[eCode=6009]` 

I have them as "prepared" now

![Screenshot_from_2023-12-19_12-25-29](https://earth.bsc.es/gitlab/es/autosubmit/uploads/18cf26456440d58ed87eaed817e21a51/Screenshot_from_2023-12-19_12-25-29.png)

If I try to change their status to "waiting" I get the following error:
```
[froura@climatedt-wf conf]$ autosubmit setstatus a0g7 -fs PREPARED -t WAITING -s
Autosubmit is running with 4.1.0
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Loading JobList
Creating jobs...
Load finished
Adding dependencies to the graph..
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...
Traceback (most recent call last):
  File "/appl/AS/4.1.0-beta/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/EGG-INFO/scripts/autosubmit", line 37, in main
    return_value = Autosubmit.parse_args()
  File "/appl/AS/4.1.0-beta/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 713, in parse_args
    return Autosubmit.set_status(args.expid, args.noplot, args.save, args.status_final, args.list,
  File "/appl/AS/4.1.0-beta/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 5379, in set_status
    Autosubmit._validate_set_status_filters(as_conf,job_list,filter_list,filter_chunks,filter_status,filter_section,filter_type_chunk, filter_type_chunk_split)
  File "/appl/AS/4.1.0-beta/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 5170, in _validate_set_status_filters
    Autosubmit._validate_status(job_list,filter_status)
  File "/appl/AS/4.1.0-beta/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 5117, in _validate_status
    raise AutosubmitCritical("Error in the supplied input for -fs.", 7011, status_validation_message)
log.log.AutosubmitCritical:  
[ERROR] Trace: 
## Status Validation Message ##
	 There are no jobs with status PREPARED in this experiment.
 [CRITICAL] Error in the supplied input for -fs. [eCode=7011]

```

**Comment by kinow** [comment]
I tried to reproduce it today.

First I started the experiment I had been using to test the workflow optimizations. It created and then started running the experiment. Until I hit CTRL+C to stop it after the first tasks completed.

![Screenshot_from_2023-12-21_13-32-13](https://earth.bsc.es/gitlab/es/autosubmit/uploads/40ddc8d844e10e8fa69eca79c8a4eb09/Screenshot_from_2023-12-21_13-32-13.png)

Doing a create (without -f) reset the workflow correctly.

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/0312b1fb65f97939f3efd9cb3e5336ed/image.png)

Then I did the same thing again, stopping (CTRL+C) the experiment after the first tasks succeeded. And tried the `setstatus` as @franra9 did above.

```bash
$ autosubmit setstatus a000 -fs SUBMITTED -t WAITING -s
/home/bdepaula/mambaforge/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.1.0')
Autosubmit is running with 4.1.0
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Loading JobList
Creating jobs...
Load finished
Adding dependencies to the graph..
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...
Checking the connection to all platforms in use
[local] Correct user privileges for host localhost
[local] Connection successful to host localhost

Plotting joblist...
Plotting...
Plot created at /home/bdepaula/autosubmit/a000/plot/a000_20231221_1338.pdf
Writing status txt...
Status txt created at <_io.TextIOWrapper name='/home/bdepaula/autosubmit/a000/status/a000_20231221_1338.txt' mode='w+' encoding='UTF-8'>
```

The command succeeds, and there is no error complaining about not finding jobs with the SUBMITTED status (as in the case of @franra9). But curiously, the plot shows the SUBMITTED tasks still as SUBMITTED :thinking: 

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/39ae428d94e71c89553c30d1eb716f22/image.png)

But... it works if I set the `COMPLETED` back to `WAITING`.

```bash
$ autosubmit setstatus a000 -fs COMPLETED -t WAITING -s
/home/bdepaula/mambaforge/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.1.0')
Autosubmit is running with 4.1.0
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Loading JobList
Creating jobs...
Load finished
Adding dependencies to the graph..
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...
Checking the connection to all platforms in use
[local] Correct user privileges for host localhost
[local] Connection successful to host localhost
CHANGED: job: a000_19900101_Member1_INI status to: WAITING
CHANGED: job: a000_19900101_Member2_INI status to: WAITING

Plotting joblist...
Plotting...
Plot created at /home/bdepaula/autosubmit/a000/plot/a000_20231221_1338.pdf
Writing status txt...
Status txt created at <_io.TextIOWrapper name='/home/bdepaula/autosubmit/a000/status/a000_20231221_1338.txt' mode='w+' encoding='UTF-8'>
```

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/5229ee6a9f604a17647e42f9278f9396/image.png)

Doing an `autosubmit create a000` resets the workflow tasks correctly.

What's weird is that I also cannot `setstatus` of the SUBMITTED with `master`. It seems that this is a separate issue, as in Autosubmit code there is a part that converts String to Classes, and it ignores other states of Autosubmit.

That means that for Autosubmit my `SUBMITTED` in this `setstatus` command was the same as `UNKNOWN`, which caused the command to not set any status (as unknown is ignored).

I guess @franra9's issue might be related to the Slurm platform, or to the PREPARED state. Will try to test with a remote platform, or force my local one to take a bit longer on the prepared...

**Comment by kinow** [comment]
Ah, I think that might actually be the reason for the bug: https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1188

The following statuses are not being handled in a part of the code (but looks like it has always been like that). The command should quietly ignore the following statuses: SUBMITTED, PREPARED, SKIPPED, DELAYED.

The fix is easy, but I am not sure what are the consequences of enabling that. I couldn't find docs or tests to explain that behavior, so waiting for @dbeltrankyl to return to confirm if that was intentional, or if we can simply update the function to handle these missing states.

**Comment by kinow** [comment]
@franra9 I believe the issue with `setstatus` is really not related to @dbeltrankyl 's work on workflow optimization (which is good!). The bug was replicated here: https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1188

And I confirmed that changing the code or using `fl` works: `autosubmit setstatus a000 -fl a000_19900101_Member2_INI -t WAITING -s -v`.

So if you try to `setstate` for a job in SUBMITTED, PREPARED, SKIPPED, DELAYED, AS may silently ignore those jobs.

I still need to replicate the other part of your issue, about the previous runs not affected in autosubmit create.

**Comment by kinow** [comment]
To clarify on this image, @franra9:

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/3e0f73199596ae5053ac90fce41afb03/image.png)

So you did an `autosubmit create` and this was the result image? With some tasks in READY?

Thanks

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 12, 2024, 09:33

When setting from any of these statuses back to waiting, there should be no issues. For the prepare  and queuing status, we should cancel the job in the remote ( and queuing that I think it already does) 

However, changing any status to prepared submitted, queuing, or running should not be doable as these jobs wouldn't have an id or do anything.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 12, 2024, 09:33

Maybe from queuing to running it could make sense, but autosubmit is able to acknowledge it automatically so there is no need

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 12, 2024, 09:35

@franra9 , @kinow, 

Was this fixed or there are still issues? If there are still issues, @franra9  the configuration of the expid a0g7 is still the same?

**Comment by kinow** [comment]
In GitLab by @franra9 on Jan 12, 2024, 11:26

hi @dbeltrankyl ,

As I was busy with the deliverable and this issue didn't imply any crash in the experiment execution, I didn't come to this again. When I have a moment I'll try to replicate the error again. 

Sorry for the delay

**Comment by kinow** [comment]
In GitLab by @franra9 on Jan 18, 2024, 17:23

Hi @dbeltrankyl @kinow ,

I think this issue is related with SIM not having a dependency assigned (see detail:)
![Screenshot_from_2024-01-18_17-20-20](https://earth.bsc.es/gitlab/es/autosubmit/uploads/01066e4d2011f06d6c56baffa3b46782/Screenshot_from_2024-01-18_17-20-20.png)

For that I think it had this strange behaviour. I think that we can just close the issue, as it does not involve any crash and I can work properly.

You are the autosubmit developers :) , I leave you the choice of closing the issue if you find it appropiate.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 18, 2024, 08:35

This was related to a dev version. Now that function is more mature and shouldn't have this type of failures 

In !409 I did another fix to the create, this issue fixes the following procedure:

* autosubmit expid

```yaml
JOBS:
 SIM:
   FILE: test.sh
   DEPENDENCIES: SIM-1
```
* autosubmit create -> Correct workflow



* autosubmit expid
```yaml
JOBS:
 SIM:
   FILE: test.h
   #DEPENDENCIES: SIM-1
```
* autosubmit create -> blank workflow


I'll close this issue as it may be confusing as many issues were fixed on a hot-fix basis due to the special condition we had at that moment. 

@franra9 If you find more create issues please open a new issue

**Comment by kinow** [comment]
In GitLab by @franra9 on Apr 24, 2024, 16:46

Thanks for the support @dbeltrankyl !
