### ISSUE TITLE
Improve how we log errors

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1199]
Last one for today from !395.

I noticed it some months ago, but only now I had some time to carefully look at the code. I think it might be due to our custom `Log` class, or some other thing, but our exception stack traces are not showing everything. See this error for example.

```bash
Configuration files OK

Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 2814, in recovery
    raise AutosubmitCritical(
log.log.AutosubmitCritical:  

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/bin/autosubmit", line 37, in main
    return_value = Autosubmit.parse_args()
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 685, in parse_args
    return Autosubmit.recovery(args.expid, args.noplot, args.save, args.all, args.hide, args.group_by,
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 2819, in recovery
    raise AutosubmitCritical(
log.log.AutosubmitCritical:  
[ERROR] Trace:  
 [CRITICAL] Couldn't restore the job_list or packages, check if the filesystem is having issues [eCode=7040]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

The user sees the last message, "Couldn't restore the job_list or packages, check if the filesystem is having issues [eCode=7040]". The traceback is, however, hiding a more useful message, created where the initial exception is raised.

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/ad598209270bfd9af0b1050b1439bfd0/image.png)

In the image above, you should be able to see the original error: "Experiment can't be recovered due being 1 active jobs in your experiment, If you want to recover the experiment, please use the flag -f and all active jobs will be cancelled".

But that error message is never displayed to the user.

This means users will open an issue in Autosubmit, a developer will open the code, see that message when following the traceback back to where it originated, and then tell the user something that could have been printed.

This is not very efficient (for both users and devs), and I think we can do better at printing the complete traceback for our users, empowering them and allowing them to troubleshoot issues much faster (i.e. a better user experience for Autosubmit users).

**Comment by kinow** [comment]
mentioned in issue digital-twins/de_340/project_management#632

**Comment by kinow** [comment]
From the `autosubmit monitor` code:

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/be22c2cc1f67e47e09c20f12a888799d/image.png)

~Here if `AutosubmitError` included information from other exceptions (complete trace), these are discarded and we raise a new `AutosubmitCritical` with the attributes of the `AutosubmitError` and ignore the rest.~

~This means if there was a `ValueError`, some IO error raising `Error`, etc., that all is ignored and never logged, which makes troubleshooting Autosubmit commands a lot harder.~

**Comment by kinow** [comment]
This is wrong :point_up: 

@dbeltrankyl was correct pointing in the meeting yesterday that the `traceback.print_exc` function we are using will print everything raised in context :thumbsup: 

The `from e` means the exceptions are chained (i.e. it shows that exception `AutosubmitError` happened because of a `ValueError`, and not that `ValueError` happened during the execution.

But by calling the `traceback` function everything is logged.

I think part of my confusion came from the fact I wasn't aware the `-lc` had a different log level than `-lf` in our commands (@dbeltrankyl told me that in another issue some days ago).

There are, however, still many cases where we are swallowing exceptions and discarding the exceptions (with `pass`, or not raising them, but instead raising others starting a new context).

**Comment by kinow** [comment]
mentioned in issue digital-twins/de_340-2/workflow#422

**Comment by kinow** [comment]
Today I spent some time troubleshooting o02q with @youcheng-csc 's help. It's a bit hard, as I get error codes like 6015, but they don't immediately mean anything. Reading the docs for the error code, sometimes they give a clue about what's wrong. IMHO, a good error message, and complete traceback when there are serious errors, would help a lot more.

In Cheng's experiment all that I have is this:

```bash
[eCode=6013]
[ERROR] 2026-07-17 16:44:20,014 Trace: list index out of range
[ERROR] 2026-07-17 16:44:20,014 LUMI submission failed [eCode=6015]
[ERROR] 2026-07-17 16:44:36,616 In Configuration files:
```

There are two error codes nearby. The real problem is the "list index out of range". But what list? In which part of the code? There are tons of lists. We know more or less that it's related to the `squeue`, as we had a few different experiments facing this same problem.

But it's still time consuming and frustrating to users & AS devs. IMHO this should be top priority for a future release. Not only this case of o02q issue, but to make sure every error include detailed and useful information about what went wrong.

Most of the errors with platforms just say to check connectivity, while in reality internally AS knows if it failed authenticating to SSH, or trying to create a directory under a certain path. There's no reason to hide that information from the user IMO.
