### ISSUE TITLE
Wrappers with job name 'PREPARE_MEMBER' fail with eCode=7014

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1206]
In GitLab by @abaer-kit on Jan 10, 2024, 17:48

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v4.0.101 (local installation)

### Which task has issues? Where is the log(If applicable)

autosubmit create <expid> -cw

### Summary

Creating the workflow with this wrapper
```
WRAPPERS:
  WRAPPER_H2:
    TYPE: "horizontal"
    JOBS_IN_WRAPPER: "PREPARE_MEMBER"
```
fails with
```
[ERROR] Trace: invalid literal for int() with base 10: 'PREPARE'
 [CRITICAL] Some section jobs of the wrapper:WRAPPER_H2 are not in the current job_list defined in jobs.conf [eCode=7014]
```
If the job is named differently (e.g. `PREPARE-MEMBER`, `PREPAREMEMBER`, `PREPARE-NAMELIST`) it works as expected.

### Steps to reproduce

```bash
autosubmit expid -dm -d "Dummy for wrapper issue report." -H MARENOSTRUM4
```
- Add user name and `MAX_PROCESSORS` to MARENOSTRUM4 platform.
- Add second member to experiment.
- Add this joblist: [jobs_a01g.yml](https://earth.bsc.es/gitlab/es/autosubmit/uploads/fb5e43493f5bc76d45eaeebefacb5529/jobs_a01g.yml)
- Add the following wrappers to autosubmit_<expid>.yml:
```yaml
WRAPPERS:
  WRAPPER_H1:
    TYPE: "horizontal"
    JOBS_IN_WRAPPER: "PREPARE_NAMELIST"
  WRAPPER_H2:
    TYPE: "horizontal"
    JOBS_IN_WRAPPER: "PREPARE_MEMBER"
```
Commenting wrapper H2 works fine, but with wrapper H2 it does not.

### What is the current bug behavior?

No wrapper is created instead an error occurs.

### What is the expected correct behavior?

Another wrapper as for the PREPARE_NAMELIST job.

### Relevant logs and/or screenshots(if applicable)

The error message and trace is:
```
Traceback (most recent call last):
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmit/job/job_list.py", line 284, in generate
    self._ordered_jobs_by_date_member[wrapper_section] = self._create_sorted_dict_jobs(
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmit/job/job_list.py", line 1220, in _create_sorted_dict_jobs
    jobs_to_sort = sorted(jobs_to_sort, key=lambda k: (k.name.split('_')[1], (k.name.split('_')[2]),
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmit/job/job_list.py", line 1221, in <lambda>
    (int(k.name.split('_')[3])
ValueError: invalid literal for int() with base 10: 'PREPARE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 4686, in create
    prev_job_list = Autosubmit.load_job_list(
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 5951, in load_job_list
    job_list.generate(date_list, as_conf.get_member_list(), as_conf.get_num_chunks(), as_conf.get_chunk_ini(),
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmit/job/job_list.py", line 289, in generate
    raise AutosubmitCritical(
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andreas/.local/bin/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 694, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/home/andreas/.local/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 4827, in create
    raise AutosubmitCritical(e.message, e.code, e.trace)
log.log.AutosubmitCritical:  
[ERROR] Trace: invalid literal for int() with base 10: 'PREPARE'
 [CRITICAL] Some section jobs of the wrapper:WRAPPER_H2 are not in the current job_list defined in jobs.conf [eCode=7014]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

Cheers,
Andreas

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 12, 2024, 12:19

Hello @abaer-kit ,

It seems to be a regex issue, with the "_" as jobnames. For now, I would change the jobnames (if possible). 

Please tell me if it is blocking for you, and I will give it more priority. I just returned from holidays, and I have many issues to look at.

**Comment by kinow** [comment]
In GitLab by @abaer-kit on Jan 12, 2024, 16:30

Hello @dbeltrankyl,

at the moment, this issue if of minor importance for me. The mentioned job is actually at a point in the workflow, where the benefit of placing it in a wrapper is very low (if any), thus just not including it in a wrapper is the way to go.

I just stumbled over the bug by testing which wrappers could potentially be applied to the workflow.

Side note: afaik there is currently no way to mark an issue with a custom priority. Maybe this could be interesting (and if it is another line in the templates).
