### ISSUE TITLE
Autosubmit vesion 3.1.9 has issue with modules

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#121]
In GitLab by @Eleftheriaexarchou on May 12, 2016, 18:03

 Autosubmit vesion 3.1.9 has issue with modules when trying to do autosubmit run a00p:      
```  
[CRITICAL] 2016-05-12 17:02:41,330 Unhandled exception on Autosubmit: No module named parser_factory     
Traceback (most recent call last):    
  File "/shared/earth/software/autosubmit/3.2.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.2.0-   py2.7.egg/autosubmit/autosubmit.py", line 286, in parse_args            
```      
on the file      
/esnas/autosubmit/a00p/tmp/20160512_170227_run.log    
how do I solve this?            
@dmanubens @ macosta  @ cp

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on May 12, 2016, 18:04

@ jlope2  ?

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 12, 2016, 18:04

@omula ?

**Comment by kinow** [comment]
In GitLab by @ jlope2 on May 13, 2016, 11:17

Sorry for the inconvenience @Eleftheriaexarchou.

@omula has checked some things with the 'module load', could you try it now, please?

Thanks!

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on May 13, 2016, 11:31

Hi,    

It does not seem to work:   
       
module unload  autosubmit/3.1.9-foss-2015a-Python-2.7.9          
module load  autosubmit/3.1.9-foss-2015a-Python-2.7.9            
nohup autosubmit run a00p  &                
       
and the error is     
2016-05-13 11:30:37,930 /esnas/autosubmit/a00p/pkl/job_list_a00p.pkl     
[CRITICAL] 2016-05-13 11:30:38,051 Unhandled exception on    Autosubmit: No module named parser_factory    
Traceback (most recent call last):    
  File "/shared/earth/software/autosubmit/3.1.9-foss-2015a-Python-    2.7.9/lib/python2.7/site-packages/autosubmit-3.1.9-     py2.7.egg/autosubmit/autosubmit.py", line 258, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.1.9-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.1.9-py2.7.egg/autosubmit/autosubmit.py", line 547, in run_experiment
    joblist = pickle.load(open(filename, 'rw'))
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 1069, in load_inst
    klass = self.find_class(module, name)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named parser_factory

**Comment by kinow** [comment]
In GitLab by @ jlope2 on May 13, 2016, 11:43

Try to do:

> module purge

and then:

> module load autosubmit/3.1.9-foss-2015a-Python-2.7.9

Thanks!

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on May 13, 2016, 12:01

Nope, same error:     
2016-05-13 12:01:57,210 /esnas/autosubmit/a00p/pkl/job_list_a00p.pkl    
[CRITICAL] 2016-05-13 12:01:57,222 Unhandled exception on Autosubmit: No module named parser_factory
Traceback (most recent call last):    
  File "/shared/earth/software/autosubmit/3.1.9-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on May 13, 2016, 12:22

Hi @ jlope2 , @omula created this file  /esnas/scratch/auto_error_a00p.log so you could have a look, thanks    
Eleftheria

**Comment by kinow** [comment]
In GitLab by @ jlope2 on May 17, 2016, 13:01

We've detected a backwards partial incompatibility.

The problems origin was that the experiment was being run with different Autosubmit versions at the same time.

Finally the solution was run the create command:

> autosubmit create expid

Each time the version is changed.

Thanks!
