### ISSUE TITLE
AS 3.3.1 issue  "make_dir (a06d) failed: mkdir: cannot create directory"

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#122]
In GitLab by @Eleftheriaexarchou on May 13, 2016, 12:07

Hi,    

I have another issue with another experiment a06d, which I am trying to run with AS 3.3.1:    
    
    

 Jobs ready for marenostrum3: 1
2016-05-13 12:06:19,204 Jobs to submit: 1
[CRITICAL] 2016-05-13 12:06:27,637 Unhandled exception on Autosubmit: make_dir (a06d) failed: mkdir: cannot create directory `a06d': File exists
 (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_file.py +767 (make_dir)  :  raise saga.NoSuccess ("make_dir (%s) failed: %s" % (tgt_in, out)))
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/autosubmit.py", line 283, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/autosubmit.py", line 607, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, joblist, platforms_to_test):
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/autosubmit.py", line 659, in submit_ready_jobs
    platform.send_file(scriptname)
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/platforms/platform.py", line 140, in send_file
    workdir = self.get_workdir(self.get_files_path())
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/platforms/platform.py", line 169, in get_workdir
    parent = self.get_workdir(os.path.dirname(path))
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/platforms/platform.py", line 170, in get_workdir
    parent.make_dir(new_directory)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/namespace/directory.py", line 197, in make_dir
    return self._adaptor.make_dir (surl.Url (tgt), flags, ttype=ttype)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_file.py", line 767, in make_dir
    raise saga.NoSuccess ("make_dir (%s) failed: %s" % (tgt_in, out))
NoSuccess: make_dir (a06d) failed: mkdir: cannot create directory `a06d': File exists
 (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_file.py +767 (make_dir)  :  raise saga.NoSuccess ("make_dir (%s) failed: %s" % (tgt_in, out)))
     
        
      
the log file is    
/esnas/autosubmit/a06d/tmp/20160513_120553_run.log       

Thanks   
Eleftheria 

@ jlope2  @dmanubens

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on May 13, 2016, 12:13

I tried to run the same experiment with AS 3.1.9, just in case it works, but it fails because of the problem reported in #121

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 13, 2016, 12:15

This was an error in the localsetup template that older versions of Autosubmit wrongly skipped. Please correct it following instructions in es/auto-ecearth3#38

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on May 13, 2016, 12:57

I did this change and    
autosubmit create a06d    
and now the localsetup fails due to      
```   
++ rsync -acrv ../conf/model.tar mn-bsc32:/gpfs/scratch/bsc32/bsc32525/a06d/    
rsync: ERROR: cannot stat destination "/gpfs/scratch/bsc32/bsc32525/a06d/": Not a directory (20)     
rsync error: errors selecting input/output files, dirs (code 3) at main.c(554) [receiver=3.0.4]     
rsync: connection unexpectedly closed (201 bytes received so far) [sender]    
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.1]      
```     

even if /gpfs/scratch/bsc32/bsc32525   exists, but AS does not create a directory a06d ... Am I doing something wrong here?

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 13, 2016, 15:48

Hi @Eleftheriaexarchou you are right, indeed I forgot to mention that previous executed locasetup has probably created wrongly `/gpfs/scratch/bsc32/bsc32525/a06d` as a file.
Then obviously this new try fails because it exists. You must delete it and run again. I will update accordingly the es/auto-ecearth3#38 issue.

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Oct 13, 2016, 23:23

I think this issue was due to an old and known issue related with auto-ecearth3.

Nothing else to do.
