### ISSUE TITLE
totaljobs value interacts with horizontal wrapper in a wrong way

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1224]
In GitLab by @dbeltrankyl on Feb 5, 2024, 16:14

Hello @franra9 , @kinow 

There is a bug with TOTALJOBS and the horizontal wrapper in which it took the max value of total jobs to know the max amount of jobs inside a wrapper, ignoring the MAX_WRAPPED value. 

Right now, what it does is to take the MAX_WRAPPED value only if it's number is lower than the TOTALJOBS,

The ideal behavior is to take the MAX_WRAPPED value, and if it is not set take the TOTALJOBS.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 5, 2024, 16:21

mentioned in issue digital-twins/de_340/workflow#186

**Comment by kinow** [comment]
In GitLab by @franra9 on Feb 5, 2024, 16:34

Hi @dbeltrankyl thanks for the support.

I got some extra finding: it takes the minimum(TOTALJOBS, MAXWAITINGJOBS) and it wrapps accordingly

e.g.: ![Screenshot_from_2024-02-05_16-30-55](https://earth.bsc.es/gitlab/es/autosubmit/uploads/93a9a39712b9bc1fd34cd4b43b3c556a/Screenshot_from_2024-02-05_16-30-55.png)

It is wrapping 2 + 1 .

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2024, 16:00

Hello @franra9 ,

There is a merge request !400 that fixes this issue, once it is merge this will be fixed

**Comment by kinow** [comment]
In GitLab by @franra9 on Feb 7, 2024, 16:11

That's great!

Can I know which module will I need to use a version with these fixes? `v4.1.0-beta-dev3`?

Nice merge request number btw (400 ;) )

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2024, 16:18

I will merge it with the 4.1 last code once Bruno reviews it 

The changes will be cherry-picked into 4.0 as well there are users who are having issues with the value of the total job sometimes ( as seen in Mattermost) 

The 4.1 code, has been reviewed by Bruno ( not sure if all changes ), but I have to address some feedback provided. 

So, to not be a blocker for you, once it is reviewed, I'll add a v4.1.0-beta-dev4 version from !400 branch, which contains the code of dev3 and dev2 tags).

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 9, 2024, 10:26

Hello @franra9 ,

This is avaliable in v4.1.0-beta-dev4

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 9, 2024, 10:31

Note: You could find an infinite loop using -cw or running with wrappers. It is known (see #1226).

This can happen, for example, if you put min_wrapped 7 and you can only wrap 6 of them at any time, and the jobs wrapped are splits, and the wrapper type is horizontal or 2-d. 

Once the wrappers are well-balanced, this infinite loop won't happen. So, I recommend testing them with the -cw flag before running the workflow. 

I'll apply a fix to apply the same behavior as non-splitted job ( raise an AutosubmitCritical)

**Comment by kinow** [comment]
In GitLab by @franra9 on Feb 13, 2024, 12:19

Thanks @dbeltrankyl I'll try when I have a moment!

**Comment by kinow** [comment]
In GitLab by @franra9 on Feb 13, 2024, 13:02

Hi @dbeltrankyl ,

I tried 

`autosubmit create a0g7 -f -cw` unsuccessfully, with MAXJOBS=10 and MIN and MAX_WRAPPED = 7

```
[froura@climatedt-wf a0g7]$ autosubmit create a0g7 -f -cw
[ERROR] Trace: 'int' object has no attribute 'get'
```

It seems it does not detect the %RUN.OPA_NAMES%

```
WRAPPERS:
  MAX_WRAPPED: 7
  MIN_WRAPPED: 7
  POLICY: mixed
  wrapper:
    JOBS_IN_WRAPPER: "%RUN.OPA_NAMES%"

```
<details><summary>here the full log</summary>

```
[froura@climatedt-wf conf]$ autosubmit create a0g7 -f -cw
[ERROR] Trace: 'int' object has no attribute 'get'
Traceback (most recent call last):
  File "/appl/AS/4.1.0-beta-dev4/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/EGG-INFO/scripts/autosubmit", line 37, in main
    return_value = Autosubmit.parse_args()
  File "/appl/AS/4.1.0-beta-dev4/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 666, in parse_args
    Autosubmit._init_logs(args, args.logconsole, args.logfile, expid)
  File "/appl/AS/4.1.0-beta-dev4/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 808, in _init_logs
    as_conf.reload(force_load=True)
  File "/appl/AS/4.1.0-beta-dev4/lib/python3.9/site-packages/autosubmitconfigparser-1.0.54-py3.9.egg/autosubmitconfigparser/config/configcommon.py", line 1437, in reload
    self.experiment_data = self.normalize_variables(self.experiment_data)
  File "/appl/AS/4.1.0-beta-dev4/lib/python3.9/site-packages/autosubmitconfigparser-1.0.54-py3.9.egg/autosubmitconfigparser/config/configcommon.py", line 513, in normalize_variables
    jobs_in_wrapper = wrappers[wrapper].get("JOBS_IN_WRAPPER", "")
AttributeError: 'int' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/AS/4.1.0-beta-dev4/bin/autosubmit", line 4, in <module>
    __import__('pkg_resources').run_script('autosubmit==4.1.0', 'autosubmit')
  File "/appl/AS/4.1.0-beta-dev4/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/appl/AS/4.1.0-beta-dev4/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/appl/AS/4.1.0-beta-dev4/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/EGG-INFO/scripts/autosubmit", line 77, in <module>
    main()
  File "/appl/AS/4.1.0-beta-dev4/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/EGG-INFO/scripts/autosubmit", line 72, in main
    raise AutosubmitCritical("Unhandled error: If you see this message, please report it in Autosubmit's GitLab project", 7000, str(e))
log.log.AutosubmitCritical:  
[froura@climatedt-wf conf]$ 
```
</details>

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 13, 2024, 13:08

But, you're using 2024-02-13 13:49:57,988 Autosubmit is running with 4.0.104 , no?

**Comment by kinow** [comment]
In GitLab by @franra9 on Feb 14, 2024, 13:21

I tried again making sure I was using `4.1.0-beta-dev4`, with the same error. We noticed in the slack chat also that `"%RUN.OPA_NAMES%"` would not work straight as there has to be the `OPA_`prefix int he job name. 

This is the WRAPPER configuration that is failing:
```
RUN:
  APP_NAMES:
  - MHM
  - WILDFIRES_FWI
  - URBAN
  - AQUA
  OPA_NAMES:
  - mhm_1
  - mhm_2
  - wildfires_fwi_1
  - wildfires_fwi_2
  - wildfires_fwi_3
  - wildfires_fwi_4
  - wildfires_fwi_5
  - urban_1
  - aqua_1
WRAPPERS:
  POLICY: "mixed"
  MIN_WRAPPED: 7
  MAX_WRAPPED: 7
  wrapper:
      TYPE: "horizontal"
      JOBS_IN_WRAPPER: OPA_WILDFIRES_FWI_1 OPA_WILDFIRES_1 OPA_WILDFIRES_1 OPA_WILDFIRES_1 OPA_WILDFIRES_1 OPA_MHM_1 OPA_MHM_2 OPA_AQUA_1 
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 14, 2024, 13:42

Not sure what the issue is, it is working for me

Could you test with 4.1.0-beta-dev5? 

If it doesn't work, what could you attach here  the jobs.ymls?

**Comment by kinow** [comment]
In GitLab by @franra9 on Feb 14, 2024, 15:11

I loaded the `beta-dev5` version and did `autosubmit create -f -cw ` but I had a different error.

```
[froura@climatedt-wf conf]$ autosubmit create a0g7 -f -cw
Traceback (most recent call last):
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmitconfigparser-1.0.55-py3.9.egg/autosubmitconfigparser/config/basicconfig.py", line 21, in <module>
    from configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/configparser-6.0.0-py3.9.egg/configparser/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/AS/4.1.0-beta-dev5/bin/autosubmit", line 4, in <module>
    __import__('pkg_resources').run_script('autosubmit==4.1.0', 'autosubmit')
  File "/appl/AS/4.1.0-beta-dev5/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/appl/AS/4.1.0-beta-dev5/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/EGG-INFO/scripts/autosubmit", line 31, in <module>
    from autosubmit.autosubmit import Autosubmit
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 32, in <module>
    from autosubmit.database.db_common import update_experiment_descrip_version
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/database/db_common.py", line 29, in <module>
    from autosubmitconfigparser.config.basicconfig import BasicConfig
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmitconfigparser-1.0.55-py3.9.egg/autosubmitconfigparser/config/basicconfig.py", line 24, in <module>
    from configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/configparser-6.0.0-py3.9.egg/configparser/__init__.py)

```

The jobs file is this one:

<details><summary>jobs</summary>

```
JOBS:
  APP:
    DEPENDENCIES: OPA
    FILE: templates/application.sh,templates/only_lra.yaml
    FOR:
      DEPENDENCIES:
      - APP_MHM:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
        OPA_MHM_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_MHM_2:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      - APP_WILDFIRES_FWI:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
        OPA_WILDFIRES_FWI_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_WILDFIRES_FWI_2:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_WILDFIRES_FWI_3:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_WILDFIRES_FWI_4:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_WILDFIRES_FWI_5:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      - APP_URBAN:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
        OPA_URBAN_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      - APP_AQUA:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
        OPA_AQUA_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      NAME: '%RUN.APP_NAMES%'
      SPLITS: '[31, 31, 31, 31]'
    NODES: 1
    PARTITION: '%CURRENT_APP_PARTITION%'
    PLATFORM: '%DEFAULT.HPCARCH%'
    PROCESSORS: 1
    RUNNING: chunk
    WALLCLOCK: 00:05
  DN:
    DEPENDENCIES:
      DN:
        SPLITS_FROM:
          all:
            SPLITS_TO: previous
      REMOTE_SETUP:
        STATUS: COMPLETED
    FILE: templates/dn.sh,conf/mother_request.yml
    PLATFORM: '%DEFAULT.HPCARCH%-login'
    RUNNING: chunk
    SPLITS: 31
    WALLCLOCK: 00:15
  LOCAL_SETUP:
    FILE: templates/local_setup.sh
    PLATFORM: LOCAL
    RUNNING: once
  OPA:
    DEPENDENCIES: null
    FILE: templates/opa.sh
    FOR:
      DEPENDENCIES:
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_MHM_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_MHM_2:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_WILDFIRES_FWI_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_WILDFIRES_FWI_2:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_WILDFIRES_FWI_3:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_WILDFIRES_FWI_4:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_WILDFIRES_FWI_5:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_URBAN_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_AQUA_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      NAME: '%RUN.OPA_NAMES%'
      SPLITS: '[31, 31, 31, 31, 31, 31, 31, 31, 31]'
    NODES: 1
    PARTITION: '%CURRENT_APP_PARTITION%'
    PLATFORM: '%DEFAULT.HPCARCH%'
    PROCESSORS: 1
    RUNNING: chunk
  REMOTE_SETUP:
    DEPENDENCIES: SYNCHRONIZE
    FILE: templates/remote_setup.sh,templates/fdb/confignative.yaml,templates/fdb/configregularll.yaml,templates/fdb/confighealpix.yaml
    PLATFORM: '%DEFAULT.HPCARCH%-login'
    RUNNING: once
    WALLCLOCK: 02:00
  SYNCHRONIZE:
    DEPENDENCIES: LOCAL_SETUP
    FILE: templates/synchronize.sh
    PLATFORM: LOCAL
    RUNNING: once
RUN:
  APP_NAMES:
  - MHM
  - WILDFIRES_FWI
  - URBAN
  - AQUA
  OPA_NAMES:
  - mhm_1
  - mhm_2
  - wildfires_fwi_1
  - wildfires_fwi_2
  - wildfires_fwi_3
  - wildfires_fwi_4
  - wildfires_fwi_5
  - urban_1
  - aqua_1
WRAPPERS:
  POLICY: "mixed"
  MIN_WRAPPED: 7
  MAX_WRAPPED: 7
  wrapper:
      TYPE: "horizontal"
      JOBS_IN_WRAPPER: OPA_WILDFIRES_FWI_1 OPA_WILDFIRES_FWI_2 OPA_WILDFIRES_FWI_3 OPA_WILDFIRES_FWI_4 OPA_WILDFIRES_FWI_5 OPA_MHM_1 OPA_MHM_2 OPA_AQUA_1 
      #"%RUN.OPA_NAMES%"

```
</details>

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 14, 2024, 15:28

Strange, I don't know why it complains in SafeConfigParser only in the lumi vm, I've updated the configparser to load configparser instead of SafeConfigparser ( as it is deprecated but the alias is currently in the library code so I don't know )

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 14, 2024, 15:30

@franra9 , 

I tested with a copy, and complains about ` [CRITICAL] Some section jobs of the wrapper:WRAPPER are not in the current job_list defined in jobs.conf [eCode=7014]
 `  KeyError: 'OPA_WILDFIRES_2'

**Comment by kinow** [comment]
In GitLab by @franra9 on Feb 14, 2024, 17:12

Hi @dbeltrankyl ,

I forgot to add the FWI to the names. I updated the jobs.yml:

`OPA_WILDFIRES_2` --> `OPA_WILDFIRES_FWI_2`

**Comment by kinow** [comment]
In GitLab by @manuel-g-castro on Feb 15, 2024, 10:31

Please @franra9 can you test is the fix is working?

**Comment by kinow** [comment]
In GitLab by @franra9 on Feb 15, 2024, 17:23

After cancelling the job by ctrl+c I get this other message:

<details><summary>error message</summary>
```
^CTraceback (most recent call last):
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 2380, in submit_ready_jobs
    save_1, failed_packages, error_message, valid_packages_to_submit = platform.submit_ready_jobs(as_conf,
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/platforms/platform.py", line 251, in submit_ready_jobs
    ready_jobs = job_list.get_ready(self, hold=hold)
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/job/job_list.py", line 2008, in get_ready
    ready = [job for job in self._job_list if
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/job/job_list.py", line 2009, in <listcomp>
    (platform is None or platform == "" or job.platform.name == platform.name) and
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/job/job.py", line 659, in platform
    if self.is_serial and self._platform:
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/job/job.py", line 649, in is_serial
    return str(self.processors) == '1' or str(self.processors) == ''
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/helpers/parameters.py", line 93, in wrapper
    @functools.wraps(wrapped_func)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 4754, in create
    Autosubmit.generate_scripts_andor_wrappers(
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 1603, in generate_scripts_andor_wrappers
    Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence, True,
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 2420, in submit_ready_jobs
    raise AutosubmitCritical("This seems like a bug in the code, please contact AS developers", 7070, str(e))
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/EGG-INFO/scripts/autosubmit", line 37, in main
    return_value = Autosubmit.parse_args()
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 701, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 4800, in create
    raise AutosubmitCritical(e.message, e.code, e.trace)
log.log.AutosubmitCritical:  
[ERROR] Trace: Traceback (most recent call last):
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 2380, in submit_ready_jobs
    save_1, failed_packages, error_message, valid_packages_to_submit = platform.submit_ready_jobs(as_conf,
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/platforms/platform.py", line 251, in submit_ready_jobs
    ready_jobs = job_list.get_ready(self, hold=hold)
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/job/job_list.py", line 2008, in get_ready
    ready = [job for job in self._job_list if
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/job/job_list.py", line 2009, in <listcomp>
    (platform is None or platform == "" or job.platform.name == platform.name) and
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/job/job.py", line 659, in platform
    if self.is_serial and self._platform:
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/job/job.py", line 649, in is_serial
    return str(self.processors) == '1' or str(self.processors) == ''
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/helpers/parameters.py", line 93, in wrapper
    @functools.wraps(wrapped_func)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 4754, in create
    Autosubmit.generate_scripts_andor_wrappers(
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 1603, in generate_scripts_andor_wrappers
    Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence, True,
  File "/appl/AS/4.1.0-beta-dev5/lib/python3.9/site-packages/autosubmit-4.1.0-py3.9.egg/autosubmit/autosubmit.py", line 2420, in submit_ready_jobs
    raise AutosubmitCritical("This seems like a bug in the code, please contact AS developers", 7070, str(e))
log.log.AutosubmitCritical:  

 [CRITICAL] This seems like a bug in the code, please contact AS developers [eCode=7070]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html

```
</details>

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 16, 2024, 11:24

The control+c stuff is normal as autosubmit is doing stuff

> Hi @manuel-g-castro I created again with `autosubmit create -f -cw` AS version -dev5 but now it gets frozen in this message:

This is due #1226, this only happens when the wrapper configuration is wrongly balanced ( you can never reach the MIN_WRAPPED at some point) I'm working on a fix, but if you encounter this bug, you need to change the min_wrapped and try again. Once the value is correct, Autosubmit will be able to show you the wrapper.
