### ISSUE TITLE
Error when running 'autosubmit create'

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1234]
In GitLab by @hrosegalb on Feb 22, 2024, 11:07

Hello @dbeltrankyl and @kinow,

### Autosubmit Version
4.0.101

### Summary
I am testing autosubmit locally with a `hello_world` script. When I tried to run `autosubmit create <expid>` to create the experiment, I get the following error:

```
 [CRITICAL] Traceback (most recent call last):
  File "/home/hgalbrai/.pyenv/versions/autosubmit_env/bin/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 659, in parse_args
    Autosubmit._init_logs(args, args.logconsole, args.logfile, expid)
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 801, in _init_logs
    as_conf.reload(force_load=True)
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 1394, in reload
    self.experiment_data = self.normalize_variables(self.experiment_data)
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 508, in normalize_variables
    dependencies = job_data.get("DEPENDENCIES",7000)
AttributeError: 'NoneType' object has no attribute 'get'
'NoneType' object has no attribute 'get'
Unhandled error: If you see this message, please report it in Autosubmit's GitLab project
```

### Steps to reproduce

1. Create a new `expid` using the `Autosubmit-Template` repo. 

```
$ autosubmit expid -H "local" -d "Test in local"
```

2. Update the `expdef_a012.yml` file:

```
DEFAULT:
  # Job experiment ID.
  EXPID: "a012"
  # Default HPC platform name.
  HPCARCH: "local"
EXPERIMENT:
  # List of start dates
  DATELIST: '20000101'
  # List of members.
  MEMBERS: fc0
  # Unit of the chunk size. Can be hour, day, month, or year.
  CHUNKSIZEUNIT: month
  # Size of each chunk.
  CHUNKSIZE: '4'
  # Number of chunks of the experiment.
  NUMCHUNKS: '2'
  CHUNKINI: ''
  # Calendar used for the experiment. Can be standard or noleap.
  CALENDAR: standard
PROJECT:
  # Type of the project.
  PROJECT_TYPE: 'local'
  # Folder to hold the project sources.
  PROJECT_DESTINATION: 'local'
GIT:
  PROJECT_ORIGIN: ''
  PROJECT_BRANCH: ''
  PROJECT_COMMIT: ''
  PROJECT_SUBMODULES: ''
  FETCH_SINGLE_BRANCH: true
SVN:
  PROJECT_URL: ''
  PROJECT_REVISION: ''
LOCAL:
  PROJECT_PATH: '/home/hgalbrai/Projects/autosubmit'
PROJECT_FILES:
  FILE_PROJECT_CONF: ''
  FILE_JOBS_CONF: ''
  JOB_SCRIPTS_TYPE: ''
RERUN:
  RERUN: false
  RERUN_JOBLIST: ''
```

3. Update the `jobs_a012.yml` file:

```
JOBS:
    HELLO_WORLD:
    FILE: "hello_world.sh"
    PLATFORM: local
    RUNNING: once
```

4. Run `autosubmit create a012`

### What is the current bug behavior?

I get the following error message:

```
[ERROR] Trace: 'NoneType' object has no attribute 'get'
 [CRITICAL] Traceback (most recent call last):
  File "/home/hgalbrai/.pyenv/versions/autosubmit_env/bin/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 659, in parse_args
    Autosubmit._init_logs(args, args.logconsole, args.logfile, expid)
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 801, in _init_logs
    as_conf.reload(force_load=True)
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 1394, in reload
    self.experiment_data = self.normalize_variables(self.experiment_data)
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmitconfigparser/config/configcommon.py", line 508, in normalize_variables
    dependencies = job_data.get("DEPENDENCIES",7000)
AttributeError: 'NoneType' object has no attribute 'get'
'NoneType' object has no attribute 'get'
Unhandled error: If you see this message, please report it in Autosubmit's GitLab project
```

### What is the expected correct behavior?

The experiment should be updated with everything needed to run the `hello_world.sh` script and I should not get an error message.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 22, 2024, 11:19

Hello @hrosegalb , 

I think that the issue is with 

```yaml
JOBS:
    HELLO_WORLD:
    FILE: "hello_world.sh"
    PLATFORM: local
    RUNNING: once
```

You're missing an indent

```yaml
JOBS:
    HELLO_WORLD:
      FILE: "hello_world.sh"
      PLATFORM: local
      RUNNING: once
```

If it doesn't work, Did you install it with pip? Could you try the 4.0.105? 



I've just uploaded the missing versions to pip

**Comment by kinow** [comment]
In GitLab by @hrosegalb on Feb 22, 2024, 12:02

Hi @dbeltrankyl,

Thank you for pointing out my error with formatting the jobs yaml. I indented the fields and then updated to autosubmit version to 4.0.105. Because I had created the experiment with version 4.0.101, I received an error message telling me to update the version of the experiment. I ran the following commands:

```
$ autosubmit updateversion a012
Autosubmit is running with 4.0.105
Expdef config file is correct
Changing a012 experiment version from 4.0.101 to  4.0.105

$ autosubmit create a012
Traceback (most recent call last):
  File "/home/hgalbrai/.pyenv/versions/autosubmit_env/bin/autosubmit", line 37, in main
    return_value = Autosubmit.parse_args()
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 659, in parse_args
    Autosubmit._init_logs(args, args.logconsole, args.logfile, expid)
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 865, in _init_logs
    raise AutosubmitCritical(
log.log.AutosubmitCritical:  
 [CRITICAL] Current experiment uses (4.0.101) which is not the running Autosubmit version  
Please, update the experiment version if you wish to continue using AutoSubmit 4.0.105
You can achieve this using the command autosubmit updateversion a012 
Or with the -v parameter: autosubmit create a012 -v  [eCode=7014]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

I then tried running `autosubmit create` with the `-v` flag:
```
$ autosubmit create a012 -v
The a012 experiment 4.0.101 version is being updated to 4.0.105 for match autosubmit version
Autosubmit is running with 4.0.105
Preparing .lock file to avoid multiple instances with same expid.
Copying /home/hgalbrai/Projects/autosubmit into /home/hgalbrai/autosubmit/a012/proj

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Loading parameters...

Creating the jobs list...
Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Updating structure persistence...
Looking for edgeless jobs...
Creating jobs...
Adding dependencies...
Removing redundant dependencies...
Updating structure persistence...
Looking for edgeless jobs...

Saving the jobs list...

Saving unified data..
Traceback (most recent call last):
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 4792, in create
    as_conf.save()
AttributeError: 'AutosubmitConfig' object has no attribute 'save'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hgalbrai/.pyenv/versions/autosubmit_env/bin/autosubmit", line 37, in main
    return_value = Autosubmit.parse_args()
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 694, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/home/hgalbrai/.pyenv/versions/3.10.12/envs/autosubmit_env/lib/python3.10/site-packages/autosubmit/autosubmit.py", line 4837, in create
    raise AutosubmitCritical(str(e), 7070)
log.log.AutosubmitCritical:  
 [CRITICAL] 'AutosubmitConfig' object has no attribute 'save' [eCode=7070]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

**Comment by kinow** [comment]
In GitLab by @hrosegalb on Feb 22, 2024, 12:31

Hi @dbeltrankyl,

Thank you, I updated to `autosubmitconfigparser==1.0.56` and then was able to create the experiment. I had been using v.1.0.29 before, so that was probably the issue.
