### ISSUE TITLE
[enhancement] Check that the AS project path is a directory, not a file

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1254]
I was testing a workflow today for Oriol, and accidentally pasted the location of a file. `autosubmit create` fails with:

```bash
(autosubmit4) bdepaula@ bsces107921:~/Development/python/workspace/autosubmit$ autosubmit create a004
/home/bdepaula/mambaforge/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.1.2')
Autosubmit is running with 4.1.2
Preparing .lock file to avoid multiple instances with same expid.
Copying /home/bdepaula/autosubmit/project/test.sh into /home/bdepaula/autosubmit/a004/proj
cp: cannot stat '/home/bdepaula/autosubmit/project/test.sh/*': Not a directory
Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4925, in _copy_code
    output = subprocess.check_output(
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cp -R /home/bdepaula/autosubmit/project/test.sh/* /home/bdepaula/autosubmit/a004/proj/local_project' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4627, in create
    if not Autosubmit._copy_code(as_conf, expid, as_conf.experiment_data.get("PROJECT",{}).get("PROJECT_TYPE","none"), False):
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4932, in _copy_code
    raise AutosubmitCritical(
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/bin/autosubmit", line 57, in main
    return_value = Autosubmit.parse_args()
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 703, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4798, in create
    raise AutosubmitCritical(e.message, e.code, e.trace)
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/bin/autosubmit", line 37, in exit_from_error
    Log.debug(traceback.format_exc())
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/site-packages/log/log.py", line 295, in debug
    Log.log.log(Log.DEBUG, msg.format(*args))
IndexError: Replacement index 0 out of range for positional args tuple

 [CRITICAL] Can not copy /home/bdepaula/autosubmit/project/test.sh into /home/bdepaula/autosubmit/a004/proj. Exiting... [eCode=7063]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.htm
```

We can improve it by simply checking if the `Path` object exists and is a directory, and failing with a nicer message to the user.

**Comment by kinow** [comment]
In GitLab by @edgano on Jul 4, 2024, 15:24

hey @kinow 
happy to put my feet here. I will need a bit of help on how to reproduce it... 
What I did:
```
egarriga@ bsces109872:~$ autosubmit expid -dm -H "local" -d "Tutorial"
Autosubmit is running with 4.1.8
The new experiment "a006" has been registered.
Generating folder structure...
Experiment folder: /home/egarriga/experiments/a006
Generating config files...
Experiment a006 created
```
Then I modified the `a006/conf/expdef_a006.yml`
```
...
LOCAL:
  PROJECT_PATH: '/home/egarriga/experiments/a006/proj/*.sh'
PROJECT_FILES:
  FILE_PROJECT_CONF: ''
  FILE_JOBS_CONF: ''
  JOB_SCRIPTS_TYPE: ''
```
and running `autosubmit -lc DEBUG create a006`
```
Autosubmit is running with 4.1.8
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Loading parameters...

Creating the jobs list...
Loading JobList
Loading JobList
Load finished
Creating jobs...
Creating LOCAL_SETUP jobs
Creating REMOTE_SETUP jobs
Creating INI jobs
Creating SIM jobs
Creating POST jobs
Creating CLEAN jobs
Creating TRANSFER jobs
Adding dependencies to the graph..
Looking if there are changes in the workflow
No changes detected, keeping edges
Adding dependencies for LOCAL_SETUP jobs
Adding dependencies for REMOTE_SETUP jobs
Adding dependencies for INI jobs
Adding dependencies for SIM jobs
Adding dependencies for POST jobs
Adding dependencies for CLEAN jobs
Adding dependencies for TRANSFER jobs
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...

Saving the jobs list...
Saving JobList: /home/egarriga/experiments/a006/pkl/job_list_a006.pkl.tmp
JobList saved in /home/egarriga/experiments/a006/pkl/job_list_a006.pkl
Backing up jobs_data...
Jobs_data database backup completed.

Plotting the jobs list...
Plotting...
Creating workflow graph...
Creating legend...
Creating job graph...
Graph definition finalized
Saving workflow plot at '/home/egarriga/experiments/a006/plot/a006_20240704_1522.pdf'
Plot created at /home/egarriga/experiments/a006/plot/a006_20240704_1522.pdf
Writing status txt...
Status txt created at <_io.TextIOWrapper name='/home/egarriga/experiments/a006/status/a006_20240704_1522.txt' mode='w+' encoding='UTF-8'>

Job list created successfully
[WARNING] Remember to MODIFY the MODEL config files!
```

**Comment by kinow** [comment]
Hi @edgano ! 

Thanks for offering to help here!!!

>and running `autosubmit -lc DEBUG create a006`

Ah, I know what you missed, but this might be either because a) our docs are lacking/not showing early enough, or b) our command-line output does not include enough information.

You created a dummy project, with `-dm`. This means that your generated configuration files must have `PROJECT.PROJECT_TYPE: none`.

So when you modified the `LOCAL` key, it had no effect. Not intuitive, and I think we could improve this somehow (another issue).

Just set `PROJECT_TYPE` to `'local'`, and then the `autosubmit create` that you used should raise that error :thumbsup: 

Cheers

p.s.: I should have provided a better example to reproduce the bug, sorry :bow:

**Comment by kinow** [comment]
In GitLab by @edgano on Jul 17, 2024, 10:57

here i am again.
A part of detecting if the path is valid or not. I have a question:

https://earth.bsc.es/gitlab/es/autosubmit/-/blob/master/autosubmit/autosubmit.py#L4757-4772

Why do the log.info and the ASCritical trigger the message about 'local_project_path' & 'project_path' but the copy process is called with 'local_project_path' & 'local_destination' ??

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 17, 2024, 11:49

Hello, no reason. Maybe it was changed at some point and was not reflected in the log. 

You can change the message to whatever you feel that is more informative

**Comment by kinow** [comment]
In GitLab by @edgano on Jul 17, 2024, 14:44

The strategy I propose is:
- check if `local_project_path` is a valid path using `Path(local_project_path).is_dir()` in one side.
- and other issue I found is the error when using `os.mkdir` when the path to build has multiple levels. the solution proposed is to build the parent dir too. (and moving to pathlib) `Path(xxx).mkdir(parents=True)`

I will prepare the test and do the MR.

If someone has any concerns feel free to open discussion here :smile:

**Comment by kinow** [comment]
In GitLab by @edgano on Aug 1, 2024, 16:21

I don't know if this behavior is expected:

Then if `project.project_destination` doesn't exist it triggers the error 

`[CRITICAL] Error obtaining the project data, check the parameters related to PROJECT and GIT/SVN or LOCAL sections [eCode=7014]`

And/but it created the folder

**Comment by kinow** [comment]
Will come back at this one later, just quickly read your comment but that part gave me chuckle. It's a critical error, but it still creates the folder. Unless that critical error is about something else, we will have to adjust the error message (or avoid creating the folder), I think.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 5, 2024, 12:35

Started but not finished https://earth.bsc.es/gitlab/es/autosubmit/-/merge_requests/484

**Comment by dbeltrankyl** [comment]
Related to #1972 ( this is the issue, while the related is also an issue but actually is a merge request)

**Comment by dbeltrankyl** [comment]
Moved to 4.1.15, just because the PR associated was set  to 4.1.15

**Comment by kinow** [comment]
Reproduced with `master` b34076442a02546b90b5c53361c7bdb792e3c22f. Still happening.
