### ISSUE TITLE
[bug,legacy feature] FILE_JOBS_CONF doesn't warn about invalid files, and tries to copy valid files to a relative directory to PWD

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1269]
( This is a template for bug reports. Please fill in the relevant information and delete the rest. )

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

`master` branch, and probably latest released PyPI version, 4.0.105.

### Summary

Stella has a testing workflow that she created for EDITO using `FILE_JOBS_CONF`, following our documentation https://autosubmit.readthedocs.io/en/latest/userguide/configure/develop_a_project.html#expdef-configuration.

I followed the same steps and reproduced the errors she had:

1. If you use something like `autosubmit/jobs.conf`, Autosubmit won't complain about a non-YAML file used
2. If you use a non-existent file, Autosubmit doesn't log any warnings. The code checks if the file exists, if not... it simply continues the configuration loading/command execution.

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/6a0429f9e379ba00072dc8b4df776015/image.png)

3. If you use a valid file, it still fails when `shutil.copyfile` is called

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/3489f0a75f3ab491339469588ee3688d/image.png)

```
(autosubmit4) kinow@ranma:/tmp$ autosubmit -lc DEBUG create a004 -np
/home/kinow/micromamba/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.1.4')
Autosubmit is running with 4.1.4
Preparing .lock file to avoid multiple instances with same expid.
Using project folder: /home/kinow/autosubmit/a004/proj

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/bin/autosubmit", line 57, in main
    return_value = Autosubmit.parse_args()
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 710, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4678, in create
    Autosubmit._create_project_associated_conf(
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4604, in _create_project_associated_conf
    shutil.copyfile(os.path.join(as_conf.get_project_dir(), as_conf.get_file_jobs_conf()),
  File "/home/kinow/micromamba/envs/autosubmit4/lib/python3.9/shutil.py", line 266, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'autosubmit/jobs.yml'

 [CRITICAL] An Unknown error occurred: [Errno 2] No such file or directory: 'autosubmit/jobs.yml'.
 Please report it to Autosubmit Developers through Git
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

### Steps to reproduce

Create a project with `autosubmit/jobs.yml`, with valid jobs.

Create a workflow and use a local project with

```yaml
PROJECT:
  PROJECT_DESTINATION: local_project
  PROJECT_TYPE: local
PROJECT_FILES:
  FILE_JOBS_CONF: autosubmit/jobs.yml
  FILE_PROJECT_CONF: ''
  JOB_SCRIPTS_TYPE: ''
RERUN:
  RERUN: false
  RERUN_JOBLIST: ''
ROOTDIR: /home/kinow/autosubmit/a004
```

Go to a directory like `/tmp`, then run `autosubmit -lc DEBUG create -np $expid`

### What is the current bug behavior?

It locates the `jobs.yml` and tries to copy into `$PWD/autosubmit/jobs.yml` (odd).

### What is the expected correct behavior?

Not sure. It seems to be like this is legacy from AS3 and probably should be removed? I suggested Stella to use `minimal` + the CUSTOM CONFIG setting we use in DestinE.

### Relevant logs and/or screenshots(if applicable)

Above.

### Any other relevant information(if applicable)

()

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 5, 2024, 14:50

Hello @kinow ,

> Not sure. It seems to be like this is legacy from AS3 and probably should be removed? I suggested Stella to use `minimal` + the CUSTOM CONFIG setting we use in DestinE.

Yes, it is legacy as you said.

**Comment by kinow** [comment]
And thanks for confirming it's legacy!

**Comment by kinow** [comment]
In GitLab by @sparonuz on Apr 5, 2024, 15:25

@orioltinto @omichel FYI: we were using this parameter for the POWN workflow. It should be replaced by using the CUSTOM_CONFIG setting of AS4, as @kinow explained to me.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 5, 2024, 15:40

> I think it won't be a problem if we remove this, as I think it's not working too? I can send a quick MR next week and we can confirm with Francesca/others on Thursday, WDYT?

I think that @charlio86 used this parameter in one of the earlier versions of AS4 in auto-Hermes ( if I recall correctly), but everybody should move to the custom_config as it does similar stuff but more powerful

**Comment by kinow** [comment]
In GitLab by @mcastril on Apr 5, 2024, 16:26

In which versions was FILE_JOBS_CONF being used?

**Comment by kinow** [comment]
In GitLab by @charlio86 on Apr 9, 2024, 15:24

I guess that it is used in auto-SNES, but we have plans to update it to the newest version:

https://earth.bsc.es/gitlab/es/auto-SNES/-/issues/10

auto-HERMES uses AS3.
