### ISSUE TITLE
Autosubmit 3.3 and above: HPCARCH=LOCAL in expdef.conf does not work

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#127]
In GitLab by @dmanubens on May 19, 2016, 16:00

```
dmanuben@ bscearth309:/esnas/autosubmit/a06h> autosubmit check a06h

Checking configuration files...
autosubmit_a06h.conf OK
platforms_a06h.conf OK
jobs_a06h.conf OK
expdef_a06h.conf  OK
Configuration files OK

[CRITICAL] Unhandled exception on Autosubmit: 'LOCAL'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.4.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.4.1-py2.7.egg/autosubmit/autosubmit.py", line 300, in parse_args
    return Autosubmit.check(args.expid)
  File "/shared/earth/software/autosubmit/3.4.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.4.1-py2.7.egg/autosubmit/autosubmit.py", line 1015, in check
    job.set_platform(submitter.platforms[job.platform_name])
KeyError: 'LOCAL'

```
@ mguevara

**Comment by kinow** [comment]
In GitLab by @ jlope2 on May 20, 2016, 12:28

There was an error since the version 3.2.0 which makes check functionality does not work.

Also there was a backwards incompatibility with the versions lower than 3.2.0.

Both will be solved in the next release.
