### ISSUE TITLE
Error when creating an experiment with -v from v.4.0.104 to v.4.1.4

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1280]
In GitLab by @ainagaya on Apr 25, 2024, 11:18

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

 v.4.1.4

### Expid affected(If applicable)

a192

### Which task has issues? Where is the log(If applicable)

autosubmit create

### Summary

I had an experiment I wanted to "re-use". It was running with v.4.0.104 but i needed 4.1.* so I loaded the lastest I found (4.1.4). I ran autosubmit create a192 and got this:

```
[agayayav@climatedt-wf conf]$ asc a192 -v
Traceback (most recent call last):
  File "/appl/AS/4.1.4/bin/autosubmit", line 4, in <module>
    __import__('pkg_resources').run_script('autosubmit==4.1.4', 'autosubmit')
  File "/appl/AS/4.1.4/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/appl/AS/4.1.4/lib64/python3.9/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/appl/AS/4.1.4/lib/python3.9/site-packages/autosubmit-4.1.4-py3.9.egg/EGG-INFO/scripts/autosubmit", line 31, in <module>
    from autosubmit.autosubmit import Autosubmit
  File "/appl/AS/4.1.4/lib/python3.9/site-packages/autosubmit-4.1.4-py3.9.egg/autosubmit/autosubmit.py", line 54, in <module>
    from .monitor.monitor import Monitor
  File "/appl/AS/4.1.4/lib/python3.9/site-packages/autosubmit-4.1.4-py3.9.egg/autosubmit/monitor/monitor.py", line 43, in <module>
    from .diagram import create_bar_diagram
  File "/appl/AS/4.1.4/lib/python3.9/site-packages/autosubmit-4.1.4-py3.9.egg/autosubmit/monitor/diagram.py", line 24, in <module>
    import matplotlib as mtp
  File "/appl/AS/4.1.4/lib/python3.9/site-packages/matplotlib-3.5.3-py3.9-linux-x86_64.egg/matplotlib/__init__.py", line 878, in <module>
    rcParamsDefault = _rc_params_in_file(
  File "/appl/AS/4.1.4/lib/python3.9/site-packages/matplotlib-3.5.3-py3.9-linux-x86_64.egg/matplotlib/__init__.py", line 780, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/appl/AS/4.1.4/lib/python3.9/site-packages/matplotlib-3.5.3-py3.9-linux-x86_64.egg/matplotlib/__init__.py", line 753, in _open_file_or_url
    fname = os.path.expanduser(fname)
  File "/usr/lib64/python3.9/posixpath.py", line 231, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not PosixPath
```

I don't really need the .4 so I moved to v.4.1.3, did the create, and seems to be working fine.

Any ideas?

Thx!

()

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 25, 2024, 13:13

Hello @ainagaya , 

thanks for the report

The issue is with the matplotlib, I downgraded it to a previous version and now is working
