### ISSUE TITLE
Failed to retrieve log makes an experiment not submitting jobs?

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1315]
In GitLab by @ainagaya on May 31, 2024, 15:50

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.1.3-dev 

### Expid affected(If applicable)

a1bx

### Which task has issues? Where is the log(If applicable)

-

### Summary

So I'm suffering quite a lot with a1bx. Its the same experiment that had the historical database problem, and that is killed almost every day, I think that because memory issues in the VM, but I didn't fins a way to confirm this. 

I was trying to restart it now, and I get output like:

```
Job a1bx_20200120_fc0_3243_TRANSFER is COMPLETED
Job a1bx_20200120_fc0_3244_TRANSFER is COMPLETED
Job a1bx_20200120_fc0_3245_TRANSFER is COMPLETED
Job a1bx_20200120_fc0_3246_TRANSFER is COMPLETED
Job a1bx_20200120_fc0_3247_TRANSFER is COMPLETED
Failed to retrieve log files a1bx_20200120_fc0_3265_TRANSFER.cmd.out.1 and a1bx_20200120_fc0_3265_TRANSFER.cmd.err.1 e=6001
Job a1bx_20200120_fc0_3248_TRANSFER is COMPLETED
Job a1bx_20200120_fc0_3249_TRANSFER is COMPLETED
Job a1bx_20200120_fc0_3251_TRANSFER is COMPLETED
Job a1bx_20200120_fc0_3252_TRANSFER is COMPLETED
Job a1bx_20200120_fc0_3254_TRANSFER is COMPLETED
Job a1bx_20200120_fc0_3255_TRANSFER is COMPLETED
Failed to retrieve log files a1bx_20200120_fc0_3259_TRANSFER.cmd.out.1 and a1bx_20200120_fc0_3259_TRANSFER.cmd.err.1 e=6001
Job a1bx_20200120_fc0_3256_TRANSFER is COMPLETED
Job a1bx_20200120_fc0_3257_TRANSFER is COMPLETED
Job a1bx_20200120_fc0_3258_TRANSFER is COMPLETED
[ERROR] Trace: Unknown failure while saving the job_list
[ERROR] unsupported format string passed to NoneType.__format__ [eCode=6040]
```

And then continues, does the same, eventually does:

```
ERROR:paramiko.transport:Exception (client): Error reading SSH protocol banner

Checking configuration files...
Failed to retrieve log files a1bx_20200120_fc0_3251_TRANSFER.cmd.out.4 and a1bx_20200120_fc0_3251_TRANSFER.cmd.err.4 e=6001
Failed to retrieve log files a1bx_20200120_fc0_3249_TRANSFER.cmd.out.4 and a1bx_20200120_fc0_3249_TRANSFER.cmd.err.4 e=6001
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/appl/AS/4.1.3/lib/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/transport.py", line 2327, in _check_banner
ERROR:paramiko.transport:    buf = self.packetizer.readline(timeout)
ERROR:paramiko.transport:  File "/appl/AS/4.1.3/lib/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/packet.py", line 381, in readline
ERROR:paramiko.transport:    buf += self._read_timeout(timeout)
ERROR:paramiko.transport:  File "/appl/AS/4.1.3/lib/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/packet.py", line 618, in _read_timeout
ERROR:paramiko.transport:    raise EOFError()
ERROR:paramiko.transport:EOFError
```

While writing this I had the "too many open files" problem. 

```
[Errno 24] Too many open files: '/appl/AS/AUTOSUBMIT_DATA/metadata/logs/a1bx_log.txt'
Logging failed. Please report it to the developers.
 [CRITICAL] There is a bug in the code, please contact via Gitlab [eCode=7070]
```

In general I would appreciate a lot that one of you takes a look and sees if there is something wrong with that experiment, the data base, or whatever, I can also change the version if you think it will improve the situation.

What I will do now is to run create + recovery and cross fingers.

Thanks a lot,

### Steps to reproduce

(How one can reproduce the issue - this is very important)

### What is the current bug behavior?

(What actually happens)

### What is the expected correct behavior?

(What you should see instead)

### Relevant logs and/or screenshots(if applicable)

(Paste any relevant logs - use code blocks (```) to format console output, logs, and code, as
it's very hard to read otherwise.)

### Any other relevant information(if applicable)

()

**Comment by kinow** [comment]
In GitLab by @ainagaya on May 31, 2024, 16:17

Create and recovery worked :thumbsup_tone2:

**Comment by kinow** [comment]
In GitLab by @ainagaya on Jun 3, 2024, 17:44

Same experiment, not sure if related, got:

```
[ERROR] 2024-06-03 15:22:50,683 Job a1bx_20200120_fc0_3548_TRANSFER completion check failed. There is no COMPLETED file[eCode=6009]
[ERROR] 2024-06-03 15:47:53,253 Trace: Failure while saving the job_list
[ERROR] 2024-06-03 15:47:53,254 cannot pickle '_thread.lock' object [eCode=6040]
[ERROR] 2024-06-03 15:54:40,895 check_job() The job id (None) is not an integer neither a string.
[ERROR] 2024-06-03 15:58:16,591 Job a1bx_20200120_fc0_3525_TRANSFER completion check failed. There is no COMPLETED file[eCode=6009]
[ERROR] 2024-06-03 15:58:46,928 Job a1bx_20200120_fc0_3552_TRANSFER completion check failed. There is no COMPLETED file[eCode=6009]
[ERROR] 2024-06-03 16:18:07,494 Trace: Failure while saving the job_list
[ERROR] 2024-06-03 16:18:07,495 cannot pickle '_thread.lock' object [eCode=6040]
[ERROR] 2024-06-03 16:18:49,855 check_job() The job id (None) is not an integer neither a string.
[ERROR] 2024-06-03 16:28:16,802 check_job() The job id (None) is not an integer neither a string.
```

Is there any way to fix this? This is in the _err.log but I think that what made the experiment crash is 


```
2024-06-03 16:32:25,853 Historical Database error: 'NoneType' object has no attribute 'energy' Traceback (most recent call last):
  File "/appl/AS/4.1.3/lib/python3.9/site-packages/autosubmit-4.1.3-py3.9.egg/autosubmit/history/experiment_history.py", line 198, in _verify_slurm_monitor
    if not slurm_monitor.steps_plus_extern_approximate_header_energy():
  File "/appl/AS/4.1.3/lib/python3.9/site-packages/autosubmit-4.1.3-py3.9.egg/autosubmit/history/platform_monitor/slurm_monitor.py", line 76, in steps_plus_extern_approximate_header_energy
    return abs(self.steps_energy + self.extern.energy - self.header.energy) <= 0.01*self.header.energy
AttributeError: 'NoneType' object has no attribute 'energy'
```

(I'm now restarting the experiment with create+recovery)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 4, 2024, 10:17

Hello @ainagaya ,

I don't think that the issue was that 

```
2024-06-03 16:32:25,853 Historical Database error: 'NoneType' object has no attribute 'energy' Traceback (most recent call last):
  File "/appl/AS/4.1.3/lib/python3.9/site-packages/autosubmit-4.1.3-py3.9.egg/autosubmit/history/experiment_history.py", line 198, in _verify_slurm_monitor
    if not slurm_monitor.steps_plus_extern_approximate_header_energy():
  File "/appl/AS/4.1.3/lib/python3.9/site-packages/autosubmit-4.1.3-py3.9.egg/autosubmit/history/platform_monitor/slurm_monitor.py", line 76, in steps_plus_extern_approximate_header_energy
    return abs(self.steps_energy + self.extern.energy - self.header.energy) <= 0.01*self.header.energy
AttributeError: 'NoneType' object has no attribute 'energy'
```

This comes from the Historical database code, which is not a critical error; autosubmit will continue. Although I don't know why this is showing

```
> [ERROR] 2024-06-04 10:40:21,545 cannot pickle '_thread.lock' object [eCode=6040]
[ERROR] 2024-06-04 11:02:55,644 cannot pickle '_thread.lock' object [eCode=6040]
```

It is my first time seeing this. The only stuff that AS pickles is the PKL, but it seems to work? weird

I think that in the first crash AS was OoS killed ( memory ),

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 4, 2024, 10:21

On a side note, 

There are some historical database errors in this experiment; I think that they should be fixed in 4.1.4, according to the changelog. (the experiment is using 4.1.3 ). 

So I expect them to be fixed on 4.1.7 once released

**Comment by kinow** [comment]
In GitLab by @ainagaya on Jun 4, 2024, 11:24

> I think that in the first crash AS was OoS killed ( memory ),

Could perfectly be. How did you check it? :eyes:

**Comment by kinow** [comment]
In GitLab by @ainagaya on Jun 4, 2024, 11:24

Perfect! Thanks Dani.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 4, 2024, 11:31

In the logs, I see that autosubmit was suddenly stopped without showing an AutosubmitCritical error or the "unknown error". I don't have access to the OS logs on the Lumi vm but I'm my experience, when something similar happened in the autosubmit machine it was always the Oom error

**Comment by kinow** [comment]
I think `dmesg` shows the oom killed processes.

BSC VM:

```bash
bdepaula@ bscesautosubmit01:~> dmesg | grep Killed
[84799.267276] Killed process 9783 (python) total-vm:4332344kB, anon-rss:3040736kB, file-rss:796kB
[84799.385851] Killed process 12360 (python) total-vm:4332344kB, anon-rss:3041028kB, file-rss:1604kB
```

ClimateDT VM:

```bash
[brunokino@climatedt-wf log]$ dmesg | grep Killed
```

No messages for oom-killer in the ClimateDT VM, but could be because the logs rotated...

Otherwise, the only way to look at `messages` I think would be asking Henrik/others to look at the logs.

**Comment by kinow** [comment]
In GitLab by @pabretonniere on Jun 5, 2024, 17:00

Hi @dbeltrankyl 


I might have a similar issue:

experiment a18b on Lumi. 

```
ERROR] Trace: Failure while saving the job_list
[ERROR] cannot pickle '_thread.lock' object [eCode=6040]
Storing failed job count...
Storing failed job count...done
Waiting 15 seconds before continue

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
wrappers OK
Autosubmit general sections OK
Configuration files OK

Recovering job_list
Loading JobList
Load finished
Creating jobs...
Adding dependencies to the graph..
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...
Recovering parameters info
Checking scripts...
914 of 3655 checked
1828 of 3655 checked
2742 of 3655 checked
3655 of 3655 checked
Recovering wrappers... Done
Restoring the connection to all experiment platforms
Recovering the remote platform connection
Waiting 15 seconds before continue
Checking the connection to all platforms in use
[LUMI] Correct user privileges for host lumi-cluster
[LUMI] Connection successful to host lumi-cluster


3553 of 3655 jobs remaining (17:40)
7 jobs has been  failed (17:40)
[ERROR] check_job() The job id (None) is not an integer neither a string.
Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Failed to retrieve log files a18b_20200120_fc0_140_TRANSFER.cmd.out.2 and a18b_20200120_fc0_140_TRANSFER.cmd.err.2 e=6001
Failed to retrieve log files a18b_20200120_fc0_136_TRANSFER.cmd.out.2 and a18b_20200120_fc0_136_TRANSFER.cmd.err.2 e=6001
Failed to retrieve log files a18b_20200120_fc0_137_TRANSFER.cmd.out.2 and a18b_20200120_fc0_137_TRANSFER.cmd.err.2 e=6001
No jobs to check for platform LUMI
Failed to retrieve log files a18b_20200120_fc0_135_TRANSFER.cmd.out.2 and a18b_20200120_fc0_135_TRANSFER.cmd.err.2 e=6001
Failed to retrieve log files a18b_20200120_fc0_138_TRANSFER.cmd.out.2 and a18b_20200120_fc0_138_TRANSFER.cmd.err.2 e=6001
Failed to retrieve log files a18b_20200120_fc0_133_TRANSFER.cmd.out.2 and a18b_20200120_fc0_133_TRANSFER.cmd.err.2 e=6001
Failed to retrieve log files a18b_20200120_fc0_139_TRANSFER.cmd.out.2 and a18b_20200120_fc0_139_TRANSFER.cmd.err.2 e=6001


3553 of 3655 jobs remaining (17:44)
7 jobs has been  failed (17:44)
[ERROR] check_job() The job id (None) is not an integer neither a string.
Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None


Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None



Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Failed to retrieve log files a18b_20200120_fc0_136_TRANSFER.cmd.out.3 and a18b_20200120_fc0_136_TRANSFER.cmd.err.3 e=6001
Failed to retrieve log files a18b_20200120_fc0_140_TRANSFER.cmd.out.3 and a18b_20200120_fc0_140_TRANSFER.cmd.err.3 e=6001
Failed to retrieve log files a18b_20200120_fc0_137_TRANSFER.cmd.out.3 and a18b_20200120_fc0_137_TRANSFER.cmd.err.3 e=6001
No jobs to check for platform LUMI
Failed to retrieve log files a18b_20200120_fc0_135_TRANSFER.cmd.out.3 and a18b_20200120_fc0_135_TRANSFER.cmd.err.3 e=6001
Failed to retrieve log files a18b_20200120_fc0_138_TRANSFER.cmd.out.3 and a18b_20200120_fc0_138_TRANSFER.cmd.err.3 e=6001
Failed to retrieve log files a18b_20200120_fc0_133_TRANSFER.cmd.out.3 and a18b_20200120_fc0_133_TRANSFER.cmd.err.3 e=6001
```
Don't spend too much time on this, I stopped, relaunched and it seems it worked but I wanted to report it just in case.

Thanks

**Comment by kinow** [comment]
In GitLab by @pabretonniere on Jun 5, 2024, 17:53

Actually the error seems to persist:

```
Waiting 15 seconds before continue
Checking the connection to all platforms in use
[LUMI] Correct user privileges for host lumi-cluster
[LUMI] Connection successful to host lumi-cluster


3553 of 3655 jobs remaining (18:48)
Wrapper job a18b_ASThread_17176000047018_4_4 changed from SUBMITTED to status COMPLETED
[ERROR] check_job() The job id (None) is not an integer neither a string.
Failed to retrieve log files a18b_20200120_fc0_7_TRANSFER.cmd.out.0 and a18b_20200120_fc0_7_TRANSFER.cmd.err.0 e=6001
Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Failed to retrieve log files a18b_20200120_fc0_8_TRANSFER.cmd.out.0 and a18b_20200120_fc0_8_TRANSFER.cmd.err.0 e=6001
Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Failed to retrieve log files a18b_20200120_fc0_11_TRANSFER.cmd.out.0 and a18b_20200120_fc0_11_TRANSFER.cmd.err.0 e=6001
Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Failed to retrieve log files a18b_20200120_fc0_4_TRANSFER.cmd.out.0 and a18b_20200120_fc0_4_TRANSFER.cmd.err.0 e=6001
Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

Command sacct -n -X --jobs None -o "State" in lumi-cluster warning: sacct: fatal: Bad job/step specified: None

ERROR:paramiko.transport:Exception (client): Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/appl/AS/4.1.3-dev-test/lib/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/transport.py", line 2327, in _check_banner
ERROR:paramiko.transport:    buf = self.packetizer.readline(timeout)
ERROR:paramiko.transport:  File "/appl/AS/4.1.3-dev-test/lib/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/packet.py", line 381, in readline
ERROR:paramiko.transport:    buf += self._read_timeout(timeout)
ERROR:paramiko.transport:  File "/appl/AS/4.1.3-dev-test/lib/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/packet.py", line 618, in _read_timeout
ERROR:paramiko.transport:    raise EOFError()
ERROR:paramiko.transport:EOFError
ERROR:paramiko.transport:
ERROR:paramiko.transport:During handling of the above exception, another exception occurred:
ERROR:paramiko.transport:
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/appl/AS/4.1.3-dev-test/lib/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/transport.py", line 2143, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/appl/AS/4.1.3-dev-test/lib/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/transport.py", line 2331, in _check_banner
ERROR:paramiko.transport:    raise SSHException(
ERROR:paramiko.transport:paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
ERROR:paramiko.transport:Exception (client): Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/appl/AS/4.1.3-dev-test/lib/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/transport.py", line 2327, in _check_banner
ERROR:paramiko.transport:    buf = self.packetizer.readline(timeout)
ERROR:paramiko.transport:  File "/appl/AS/4.1.3-dev-test/lib/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/packet.py", line 381, in readline
ERROR:paramiko.transport:    buf += self._read_timeout(timeout)
ERROR:paramiko.transport:  File "/appl/AS/4.1.3-dev-test/lib/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/packet.py", line 618, in _read_timeout
ERROR:paramiko.transport:    raise EOFError()
ERROR:paramiko.transport:EOFError
ERROR:paramiko.transport:
ERROR:paramiko.transport:During handling of the abo
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 6, 2024, 08:18

Hello @pabretonniere , 

Could you do an autosubmit create + autosubmit recovery and see if it works? Soon, I'll release 4.1.7, which will have some wrapper fixes; although I did not encounter this one, it may be more reliable.

**Comment by kinow** [comment]
In GitLab by @pabretonniere on Jun 6, 2024, 15:43

Thanks! I did the create + recovery and it temporally solved the issue, it ran a few chunks and failed again.

If you think and confirm this is "only" a wrapper issue, I'll deactivate them.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 13, 2024, 15:01

I've upload autosubmit 4.1.8, tell me if it happens on that version
