### ISSUE TITLE
Running autosubmit upgrade from the hub returns an error

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1330]
In GitLab by @ainagaya on Jun 18, 2024, 14:46

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

I tried:
- autosubmit/4.1.8-foss-2021b-Python-3.9.6
- autosubmit/4.1.5-foss-2021b-Python-3.9.6

### Expid affected(If applicable)

a78l

### Which task has issues? Where is the log(If applicable)

`/esarchive/autosubmit/a78l/tmp/ASLOGS/20240618_143215_refresh.log` & `20240618_143215_refresh_err.log`

### Summary

I was trying to run `autosubmit upgrade a78l` from the hubs, , but I'm getting 

```
TypeError: expected str, bytes or os.PathLike object, not PosixPath
```

Its this same error: https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1280

### Steps to reproduce

I think that copying the experiment and running autosubmit upgrade should give you the same error.

### What is the current bug behavior?

(What actually happens)

### What is the expected correct behavior?

(What you should see instead)

### Relevant logs and/or screenshots(if applicable)

```
[agayayav@ bsceshub02 a78l]$ ml autosubmit/4.1.6-hotfix-foss-2021b-Python-3.9.6

The following have been reloaded with a version change:
  1) autosubmit/4.1.8-foss-2021b-Python-3.9.6 => autosubmit/4.1.6-hotfix-foss-2021b-Python-3.9.6

[agayayav@ bsceshub02 a78l]$ autosubmit upgrade a78l
Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.6-hotfix-foss-2021b-Python-3.9.6/bin/autosubmit", line 4, in <module>
    __import__('pkg_resources').run_script('autosubmit==4.1.6', 'autosubmit')
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.6-hotfix-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.6-py3.9.egg/EGG-INFO/scripts/autosubmit", line 31, in <module>
    from autosubmit.autosubmit import Autosubmit
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.6-hotfix-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.6-py3.9.egg/autosubmit/autosubmit.py", line 54, in <module>
    from .monitor.monitor import Monitor
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.6-hotfix-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.6-py3.9.egg/autosubmit/monitor/monitor.py", line 43, in <module>
    from .diagram import create_bar_diagram
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.6-hotfix-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.6-py3.9.egg/autosubmit/monitor/diagram.py", line 24, in <module>
    import matplotlib as mtp
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.6-hotfix-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/matplotlib-3.8.3-py3.9-linux-x86_64.egg/matplotlib/__init__.py", line 963, in <module>
    rcParamsDefault = _rc_params_in_file(
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.6-hotfix-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/matplotlib-3.8.3-py3.9-linux-x86_64.egg/matplotlib/__init__.py", line 866, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.6-hotfix-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/matplotlib-3.8.3-py3.9-linux-x86_64.egg/matplotlib/__init__.py", line 842, in _open_file_or_url
    fname = os.path.expanduser(fname)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/posixpath.py", line 231, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not PosixPath

```

### Any other relevant information(if applicable)

()

**Comment by kinow** [comment]
In GitLab by @ainagaya on Jun 18, 2024, 14:49

In the bscesautosubmit01 machine with 4.0.98 I think that it worked

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 18, 2024, 14:56

Hello @ainagaya , 

Thanks, Aina. I'll check it.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 18, 2024, 15:04

@ainagaya, which was the original experiment? to make a copy since yours is already upgraded I think

I tried with one of mine, and it worked

`Changing t0lk experiment version from 3.13.0 to 4.1.8`

**Comment by kinow** [comment]
In GitLab by @ainagaya on Jun 19, 2024, 10:16

Hi @dbeltrankyl , I just did it again a bit more cleanly and it worked, I was "recycling" an old experiment before. Closing this, I'll reopen it if I find the same again. Thanks :)
