### ISSUE TITLE
transfer1 connectivity not working ( working, update docs with the solution)

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1335]
In GitLab by @IsidreMas on Jul 1, 2024, 15:22

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v4.1.8

### Expid affected(If applicable)

a7ft

### Which task has issues? Where is the log(If applicable)

* **Full_name**:20240701_151029_run

* **Log_Path:** /esarchive/autosubmit/a7ft/tmp/ASLOGS/20240701_151029_run.log

### Summary

I'm trying to run the experiment but some errors appear while checking the connectivity to transfer1.bsc.es. The ssh connection is working passwordless. This are the relevant outputs from running the experiment:

```
Autosubmit is running with v4.1.8
Checking the connection to all platforms in use
ERROR:paramiko.transport:Unknown exception: q must be exactly 160, 224, or 256 bits long
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/paramiko/transport.py", line 2109, in run
ERROR:paramiko.transport:    handler(self.auth_handler, m)
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
ERROR:paramiko.transport:    sig = self.private_key.sign_ssh_data(blob)
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/paramiko/dsskey.py", line 108, in sign_ssh_data
ERROR:paramiko.transport:    key = dsa.DSAPrivateNumbers(
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 244, in private_key
ERROR:paramiko.transport:    return backend.load_dsa_private_numbers(self)
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 826, in load_dsa_private_numbers
ERROR:paramiko.transport:    dsa._check_dsa_private_numbers(numbers)
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 282, in _check_dsa_private_numbers
ERROR:paramiko.transport:    _check_dsa_parameters(parameters)
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 274, in _check_dsa_parameters
ERROR:paramiko.transport:    raise ValueError("q must be exactly 160, 224, or 256 bits long")
ERROR:paramiko.transport:ValueError: q must be exactly 160, 224, or 256 bits long
ERROR:paramiko.transport:
ERROR:paramiko.transport:Unknown exception: q must be exactly 160, 224, or 256 bits long
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/paramiko/transport.py", line 2109, in run
ERROR:paramiko.transport:    handler(self.auth_handler, m)
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
ERROR:paramiko.transport:    sig = self.private_key.sign_ssh_data(blob)
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/paramiko/dsskey.py", line 108, in sign_ssh_data
ERROR:paramiko.transport:    key = dsa.DSAPrivateNumbers(
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 244, in private_key
ERROR:paramiko.transport:    return backend.load_dsa_private_numbers(self)
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 826, in load_dsa_private_numbers
ERROR:paramiko.transport:    dsa._check_dsa_private_numbers(numbers)
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 282, in _check_dsa_private_numbers
ERROR:paramiko.transport:    _check_dsa_parameters(parameters)
ERROR:paramiko.transport:  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 274, in _check_dsa_parameters
ERROR:paramiko.transport:    raise ValueError("q must be exactly 160, 224, or 256 bits long")
ERROR:paramiko.transport:ValueError: q must be exactly 160, 224, or 256 bits long
ERROR:paramiko.transport:
[local] Correct user privileges for host localhost
[local] Connection successful to host localhost
 [CRITICAL] Issues while checking the connectivity of platforms. [eCode=7014]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

Any help will be appreaciated,

Thanks

**Comment by kinow** [comment]
In GitLab by @IsidreMas on Jul 1, 2024, 16:30

Thank you Bruno,

generating a new ed25519 key and updating .ssh/config worked

Maybe its also worth to mention I didn't have this issue in AS v3

**Comment by kinow** [comment]
Thank you for confirming that worked, Isidre. I will leave this issue open until we have updated the documentation :thumbsup:

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 2, 2024, 08:24

@IsidreMas ,

> Maybe its also worth to mention I didn't have this issue in AS v3

We're using an external library that is called Paramiko, 

Autosubmit 4 uses v3.4, while Autosubmit 3 uses v2.X. ( This is mainly due python 2 vs python 3 , also other stuff like 2fa and ssh-agent works better in v3.4)

They probably made that change to strengthen the connection's security ( can't confirm 100% ). Anyway is not in our hands

Thanks for the report and thanks @kinow for the help
