### ISSUE TITLE
Joblist empty error message refinement

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1362]
In GitLab by @franra9 on Jul 10, 2024, 15:28

Hello @dbeltrankyl and @kinow (should we add @edgano in the template? ;) ), beloved autosubmit team all:

### Autosubmit Version

4.1.8

### Expid affected(If applicable)

- Create step
- 
### Which task has issues? Where is the log(If applicable)

* **Full_name**: -

* **Log_Path:** ASLOGS in create step.

### Summary

Error message could be more specific / accurate for easy debugging.

### Steps to reproduce

copy a1bh and create after deleting the file `jobs_apps.yml` under `conf/`

### What is the current bug behavior?

I think* it complains if some of the files in the include.yml file does not exist, sending a not much accurate error message. 

### What is the expected correct behavior?

If some of the files listed inside include.yml do not exist, the error message should say that, instead of "Check if there are YML files in /appl/AS/AUTOSUBMIT_DATA/a1et/proj/git_project/conf/bootstrap/ [eCode=7015]".

### Relevant logs and/or screenshots(if applicable)

```
Traceback (most recent call last):
  File "/appl/AS/4.1.8/lib/python3.9/site-packages/autosubmit-4.1.8-py3.9.egg/EGG-INFO/scripts/autosubmit", line 59, in main
    return_value = Autosubmit.parse_args()
  File "/appl/AS/4.1.8/lib64/python3.9/site-packages/autosubmit-4.1.8-py3.9.egg/autosubmit/autosubmit.py", line 739, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/appl/AS/4.1.8/lib64/python3.9/site-packages/autosubmit-4.1.8-py3.9.egg/autosubmit/autosubmit.py", line 4475, in create
    raise AutosubmitCritical(f'Job list is empty\nCheck if there are YML files in {as_conf.experiment_data.get("DEFAULT","").get("CUSTOM_CONFIG","")}', code=7015)
log.log.AutosubmitCritical:  

 [CRITICAL] Job list is empty
Check if there are YML files in /appl/AS/AUTOSUBMIT_DATA/a1et/proj/git_project/conf/bootstrap/ [eCode=7015]

```

### Any other relevant information(if applicable)

The issue comes from https://earth.bsc.es/gitlab/digital-twins/de_340-2/workflow/-/issues/474

()

**Comment by kinow** [comment]
@franra9 

> Hello @dbeltrankyl and @kinow (should we add @edgano in the template? ;) ), beloved autosubmit team all:

Ha! Faster than you! From yesterday :laughing:  https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1356
