### ISSUE TITLE
Still "Lost shell connection" issues with Autosubmit 3.5.0

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#137]
In GitLab by @fmassonn on May 30, 2016, 08:42

Hi,

I'm running a06q (log: /home/Earth/fmassonn/logs/autosubmit/log_a06q_20160529175545) but I am still experiencing trouble with SSH connection.

I understood from the meeting last week that Autosubmit 3.5.0 would resolve this, so I'm wondering if that's not a problem that I have to solve with Support?

François

    "Lost shell connection to %s" % info['host_str'])
IncorrectState: Lost shell connection to cns96177@mn-cns96 (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +209 (initialize)  :  "Lost shell connection to %s" % info['host_str']))
2016-05-30 00:39:56,202: radical.saga.cpi    : MainProcess                     : MainThread     : ERROR   : IncorrectState: Lost shell connection to cns96177@mn-cns96
2016-05-30 00:39:56,204: radical.utils       : MainProcess                     : MainThread     : ERROR   : Could not create lease object
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/radical.utils-0.40-py2.7.egg/radical/utils/lease_manager.py", line 175, in _create_object
    obj = _LeaseObject (self, self._log, creator, args)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/radical.utils-0.40-py2.7.egg/radical/utils/lease_manager.py", line 33, in __init__
    self.obj        = creator (*args)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_file.py", line 274, in _shell_creator
    return sups.PTYShell (url, self.get_session(), self._logger)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell.py", line 243, in __init__
    posix=self.posix)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 209, in initialize
    "Lost shell connection to %s" % info['host_str'])
IncorrectState: Lost shell connection to cns96177@mn-cns96 (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +209 (initialize)  :  "Lost shell connection to %s" % info['host_str']))

**Comment by kinow** [comment]
In GitLab by @fmassonn on May 30, 2016, 08:52

Edit: I still launch the experiments with 
"export SAGA_PTY_SSH_TIMEOUT=120"
and all my experiments run on bscesautosubmit01

**Comment by kinow** [comment]
In GitLab by @mmenegoz on May 30, 2016, 11:22

Hi, I have the same type of issue when trying to run the forecast a06n on marenostrum. autosubmit failed with the message that you will find below. Similarly, I cannot run any recovery for my experiments. What can we do?
Cheers
Martin

[CRITICAL] 2016-05-29 14:50:56,415 Unhandled exception on Autosubmit: read from process failed '[Errno 5] Input/output error' : (868012> is not found
PROMPT-0->Job <1868012> is not found
PROMPT-0->Job <1868012> is not found
PROMPT-0->Job <1868012> is not found
PROMPT-0->Job <1868012> is not found
PROMPT-0->Job <1868012> is not found
PROMPT-0->Shared connection to mn1.bsc.es closed.
) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.4.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.4.1-py2.7.egg/autosubmit/autosubmit.py", line 285, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.4.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.4.1-py2.7.egg/autosubmit/autosubmit.py", line 608, in run_experiment
    if prev_status != job.update_status(platform.check_job(job.id)):
  File "/shared/earth/software/autosubmit/3.4.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.4.1-py2.7.egg/autosubmit/platforms/platform.py", line 442, in check_job
    if jobid not in self.service.jobs:
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/job/service.py", line 378, in list
    return self._adaptor.list (ttype=ttype)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/shared/earth/software/autosubmit/3.4.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.4.1-py2.7.egg/autosubmit/platforms/mn_adaptor.py", line 865, in list
    ret, out, _ = self.shell.run_sync("%s -a -noheader" % 'bjobs')
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell.py", line 648, in run_sync
    self.pty_shell.flush ()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))

**Comment by kinow** [comment]
In GitLab by @mmenegoz on May 30, 2016, 12:06

Chloe just indicated me the option on the bashrc that I had to indicate in my .bashrc "export SAGA_PTY_SSH_TIMEOUT=90" . Including this modification in my .bashrc, I can run the recovery. Then ,I relaunched the experiment, and it seems to works now. So it was probably not an issue similar to those that François met.

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 30, 2016, 13:15

ok @mmenegoz thanks. 
@fmassonn we are investigating it. So far we detected two problems:
1. 
```
2016-05-29 23:54:05 Job a06q_19740101_fc13_23_SIM seemed to be completed but there is no COMPLETED file
2016-05-30 00:38:34 Job a06q_19740101_fc14_23_SIM seemed to be completed but there is no COMPLETED file
2016-05-30 00:39:05 Job a06q_19740101_fc15_23_SIM seemed to be completed but there is no COMPLETED file
```
These jobs completed fine and Autosubmit got the right status from Mn3. Then it failed to retreive the completed file most probably due to connectivity problems during that window timeframe. I am checking it with support. 
However, apparently in this situation Autosubmit only retries twice. We'll need to review the get_completed files function and increase these retries number.
2. 
```
2016-05-29 23:39:37 [ERROR] a06q_19740101_fc12_23_POST submission failed
2016-05-30 00:16:48 [ERROR] a06q_19740101_fc16_23_SIM submission failed
2016-05-30 00:39:56 [ERROR] a06q_19740101_fc17_23_SIM submission failed
```
During more or less the same timeframe of the above problem, the submission of three different jobs failed. By contrast in this case submit_ready_jobs function implements many retrials. This is why in your log you see that it went into a loop until 2016-05-30 08:44:00. The expected behaviour is that SAGA should interpret the delayed retry as a new connection request, and should start from scratch. This is working fine in the check_job function. However that's not the case in submit_jobs. We are trying to reproduce the problem. We'll keep you informed.

In the mean time I would suggest you to relaunch again the experiment and see if it reproduces.

Thanks for your patience.

@ jlope2 @ cprodhomme @Eleftheriaexarchou @obellprat @ macosta

**Comment by kinow** [comment]
In GitLab by @fmassonn on May 30, 2016, 13:47

At the same time I have another type of error:

Experiment a071
Log: /home/Earth/fmassonn/logs/autosubmit/log_a071_20160530095947

    "Lost shell connection to %s" % info['host_str'])
IncorrectState: Lost shell connection to cns96177@mn-cns96 (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +209 (initialize)  :  "Lost shell connection to %s" % info['host_str']))
2016-05-30 11:43:25,956: radical.saga.cpi    : MainProcess                     : MainThread     : ERROR   : IncorrectState: Lost shell connection to cns96177@mn-cns96
2016-05-30 11:43:25,961: radical.utils       : MainProcess                     : MainThread     : ERROR   : Could not create lease object
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/radical.utils-0.40-py2.7.egg/radical/utils/lease_manager.py", line 175, in _create_object
    obj = _LeaseObject (self, self._log, creator, args)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/radical.utils-0.40-py2.7.egg/radical/utils/lease_manager.py", line 33, in __init__
    self.obj        = creator (*args)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_file.py", line 274, in _shell_creator
    return sups.PTYShell (url, self.get_session(), self._logger)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell.py", line 243, in __init__
    posix=self.posix)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 209, in initialize
    "Lost shell connection to %s" % info['host_str'])
IncorrectState: Lost shell connection to cns96177@mn-cns96 (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +209 (initialize)  :  "Lost shell connection to %s" % info['host_str']))


Thanks


François

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 30, 2016, 15:48

Hi @fmassonn 
at `bscesautosubmit01` you have several large experiments of 25 * 120 jobs experiments. One of them is taking almost 100% cpu.
I wonder if you could reduce the number of chunks when running several exp. at the same time. Or alternatively change the `TOTAL_JOBS` to the default value, combined with an increase of `SAFETYSLEEPTIME`:
```
# Default maximum number of jobs to be running at the same time at any platform
# Default = 6
TOTALJOBS = 25
# Time (seconds) between connections to the HPC queue scheduler to poll already submitted jobs status
# Default = 10
SAFETYSLEEPTIME = 10
```

**Comment by kinow** [comment]
In GitLab by @fmassonn on Jun 2, 2016, 12:32

Hi, 

You mentioned during a discussion earlier this week that Paramiko will be enabled in the next autosubmit version, in order to not use SAGA. Do you know approximately when?

Cheers,

François

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jun 2, 2016, 12:44

We are working hard on it. If everything goes smoothly tomorrow we'll do testing. Count on it for the beginning of next week.
