### ISSUE TITLE
ED25519 ssh key aren't working

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1374]
In GitLab by @slim0 on Jul 25, 2024, 14:14

Hi,

Just to let you know that I tried to run an experimen using our autosubmit image (the one based on autosubmit docker img autosubmit/autosubmit:4.1.7) with my own LUMI ED25519 ssh key and discover that it does not work (but it works if I'm connecting with an ssh command, without autosubmit).
Some days ago, @sparonuz did the same using it's RSA key pair and it worked.

After creating an experiment, I tried to run it and it gave me the following result:
```shell
Loading JobList
Load finished
Creating jobs...
Adding dependencies to the graph..
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...
Autosubmit is running with v4.1.7
Checking the connection to all platforms in use
[local] Correct user privileges for host localhost
[local] Connection successful to host localhost
 [CRITICAL] Issues while checking the connectivity of platforms. [eCode=7014]
```
And the log file located in `/app/autosubmit/experiments/a000/tmp/ASLOGS`:

```shell
2024-07-25 11:57:54,581 Checking the connection to all platforms in use
2024-07-25 11:57:54,896 Failed to authenticate with ssh-agent due to unpack requires a buffer of 4 bytes
2024-07-25 11:57:54,896 Trying to authenticate with other methods
[WARNING] 2024-07-25 11:57:55,448 [LUMI] Connection failed to host lumi.csc.fi[eCode=3000]
2024-07-25 11:57:55,450 [local] Correct user privileges for host localhost
2024-07-25 11:57:55,451 [local] Connection successful to host localhost
2024-07-25 11:57:55,779 Failed to authenticate with ssh-agent due to unpack requires a buffer of 4 bytes
2024-07-25 11:57:55,779 Trying to authenticate with other methods
[WARNING] 2024-07-25 11:57:56,268 [LUMI_LOGIN] Connection failed to host lumi.csc.fi[eCode=3000]
2024-07-25 11:57:56,282 Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/autosubmit/autosubmit.py", line 2154, in run_experiment
    job_list, submitter , exp_history, host , as_conf, platforms_to_test, packages_persistence, _ = Autosubmit.prepare_run(expid, notransitive, start_time, start_after, run_only_members)
  File "/opt/conda/lib/python3.9/site-packages/autosubmit/autosubmit.py", line 2095, in prepare_run
    Autosubmit.restore_platforms(platforms_to_test,as_conf=as_conf)
  File "/opt/conda/lib/python3.9/site-packages/autosubmit/autosubmit.py", line 2475, in restore_platforms
    raise AutosubmitCritical("Issues while checking the connectivity of platforms.", 7010, issues + "\n" + ssh_config_issues)
log.log.AutosubmitCritical:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/autosubmit", line 59, in main
    return_value = Autosubmit.parse_args()
  File "/opt/conda/lib/python3.9/site-packages/autosubmit/autosubmit.py", line 707, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive,args.start_time,args.start_after, args.run_only_members, args.profile)
  File "/opt/conda/lib/python3.9/site-packages/autosubmit/autosubmit.py", line 2157, in run_experiment
    raise AutosubmitCritical(e.message, 7014, e.trace)
log.log.AutosubmitCritical:

2024-07-25 11:57:56,283 Trace:
[LUMI] has configuration issues.
 Check that the connection is passwd-less.(ssh lyobards@lumi.csc.fi)
 Check the parameters that build the root_path are correct:{scratch_dir/project/user} = {/scratch/project_465001161/lyobards}
[LUMI_LOGIN] has configuration issues.
 Check that the connection is passwd-less.(ssh lyobards@lumi.csc.fi)
 Check the parameters that build the root_path are correct:{scratch_dir/project/user} = {/scratch/project_465001161/lyobards}
  this is an PARAMIKO SSHEXCEPTION: indicates that there is something incompatible in the ssh_config for host:lumi.csc.fi
 maybe you need to contact your sysadmin  this is an PARAMIKO SSHEXCEPTION: indicates that there is something incompatible in the ssh_config for host:lumi.csc.fi
 maybe you need to contact your sysadmin
[CRITICAL] 2024-07-25 11:57:56,283 Issues while checking the connectivity of platforms. [eCode=7014]
2024-07-25 11:57:56,283 More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
(base) autosubmit@nemo-apptainer-490981-pv4st:/app/autosubmit/experiments/a000/tmp/ASLOGS$
```

So it looks like a PARAMIKO error. Then I also found that on the internet: https://stackoverflow.com/questions/60660919/paramiko-ssh-client-is-unable-to-unpack-ed25519-key

**Comment by kinow** [comment]
I think we had similar reports before, but not sure how that was handled. Thanks for the SO link. Looks like something that we could either call directly based on the key type used, or at least try the current approach, then try this different key type call in an except, and if that fails only then give up and raise a warning. Thanks for reporting it, @slim0 !!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 5, 2024, 11:20

Hello @slim0 , 

Thanks for reporting this. We will check. 

> I think we had similar reports before, but not sure how that was handled.

I find this strange because we always had the reverse case ( mainly for marenostrum5) , RSA didn't work, but ed25519 did work. ( in fact, I was recommending swapping the keys, and I'm currently using an ed25519 one )

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 5, 2024, 11:24

Hello @slim0,

Sorry for the double post, I forgot to mention:

Can you check and tell me your current paramiko version? pip freeze should give you it.

With paramiko==3.4, the ED key should work, but we're currently using paramiko<=3.4, so you could have a lower version...

We should enforce it. Otherwise, newer platforms like marenostrum5 could not work as expected @kinow

**Comment by kinow** [comment]
In GitLab by @slim0 on Aug 5, 2024, 12:01

Hi @dbeltrankyl,

First, I'm now using the latest docker image available on docker hub (autosubmit version 4.1.9).

I confirm that I still encounter the issue.
Paramiko is on version 3.4.0.
I also can tell you that I don't have this issue with RSA key (using the same docker image).

Regards

**Comment by dbeltrankyl** [comment]
Removing milestone ( for now 
)
I'm not entirely sure why this happens, as I'm currently using an ED25519 key

Maybe we can close this issue and open one more generic related to this comment:

> I think we had similar reports before, but not sure how that was handled. Thanks for the SO link. Looks like something that we could either call directly based on the key type used, or at least try the current approach, then try this different key type call in an except, and if that fails only then give up and raise a warning. Thanks for reporting it


@kinow what do you think?

**Comment by dbeltrankyl** [comment]
Hello @MichaelBSC 

That's strange, did it work for you before? 


* You can connect manually without password?
* You can try to connect through an alias

Autosubmit should try every key but you can try this:

.ssh/config

```
Host mn5-gpp #you can change this, it will be your new host name
 User bsc032070 #change it for your user
 HostName glogin4.bsc.es
 ForwardAgent yes
 IdentityFile ~/.ssh/id_rsa # change it for your key
`````

Note: glogin4 only works under ibsc or internal VPN. 

````yaml
PLATFORMS:
 marenostrum5:
    ...
    HOST: mn5-gpp # alias set in .ssh/config

* You can try to use the ssh-agent

eval $(ssh-agent)

**Comment by MichaelBSC** [comment]
That would be entirely my fault I forgot to modify the user in the platform file! I'm sorry, should I delete my comment?

**Comment by dbeltrankyl** [comment]
Hello @MichaelBSC , 

Don't worry! great that is solved
