### ISSUE TITLE
"Cannot allocate memory" issue

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#138]
In GitLab by @fmassonn on May 30, 2016, 11:23

Hi, 
I have a new type of error with my simulation a06q (log: /home/Earth/fmassonn/logs/autosubmit/log_a06q_20160530085411)

NoSuccess: Could not run (/usr/bin/env TERM=vt100 /usr/bin/ssh -t -o IdentityFile=/home/Earth/fmassonn/.ssh/id_rsa -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_fmassonn_%h_%p.cns96177.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=120 cns96177@mn-cns96): [Errno 12] Cannot allocate memory (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +225 (initialize)  :  % (' '.join (self.command), e)))

Many thanks for your help.
François

**Comment by kinow** [comment]
In GitLab by @fmassonn on May 30, 2016, 11:36

I have had the same with a06m, despite running on my own machine (and this was the only autosubmit job submitted on my machine)


^[[31m[CRITICAL] Unhandled exception on Autosubmit: Could not run (/usr/bin/env TERM=vt100 /usr/bin/sftp -o IdentityFile=/home/Earth/fmassonn/.ssh/id_rsa -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_fmassonn_%h_%p.cns96177.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=120 cns96177@mn-cns96): [Errno 12] Cannot allocate memory (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +225 (initialize)  :  % (' '.join (self.command), e)))
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.5.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.5.0-py2.7.egg/autosubmit/autosubmit.py", line 286, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.5.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.5.0-py2.7.egg/autosubmit/autosubmit.py", line 609, in run_experiment
    if prev_status != job.update_status(platform.check_job(job.id)):
  File "/shared/earth/software/autosubmit/3.5.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.5.0-py2.7.egg/autosubmit/job/job.py", line 421, in update_status
    self.get_platform().get_completed_files(self.name)
  File "/shared/earth/software/autosubmit/3.5.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.5.0-py2.7.egg/autosubmit/platforms/platform.py", line 295, in get_completed_files
    if self.get_file('{0}_COMPLETED'.format(job_name), False):
  File "/shared/earth/software/autosubmit/3.5.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.5.0-py2.7.egg/autosubmit/platforms/platform.py", line 214, in get_file
    out.copy("file://{0}".format(local_path))
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/namespace/entry.py", line 266, in copy
    return self._adaptor.copy_self (tgt, flags, ttype=ttype)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_file.py", line 1162, in copy_self
    files_copied = self.shell.obj.stage_from_remote (src.path, tgt.path, rec_flag)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell.py", line 932, in stage_from_remote
    raise ptye.translate_exception (e)
NoSuccess: Could not run (/usr/bin/env TERM=vt100 /usr/bin/sftp -o IdentityFile=/home/Earth/fmassonn/.ssh/id_rsa -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_fmassonn_%h_%p.cns96177.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=120 cns96177@mn-cns96): [Errno 12] Cannot allocate memory (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +225 (initialize)  :  % (' '.join (self.command), e)))

**Comment by kinow** [comment]
In GitLab by @fmassonn on May 30, 2016, 11:37

Should I just avoid the "export SAGA_..."?

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 30, 2016, 12:42

Hi @fmassonn I think there's an issue in the mn1.bsc.es login node.
I have checked the load average and it is quite high. I have contacted support.
```
bsc32704@login1:~> top

top - 12:40:56 up 82 days, 23:26, 77 users,  load average: 5.29, 5.29, 5.79
Tasks: 554 total,   4 running, 549 sleeping,   1 stopped,   0 zombie
Cpu(s): 17.1%us,  5.8%sy,  0.0%ni, 76.3%id,  0.0%wa,  0.0%hi,  0.7%si,  0.0%st
Mem:     32212M total,     7454M used,    24757M free,        0M buffers
Swap:    11442M total,     7185M used,     4257M free,     1187M cached

  PID USER      PR  NI  VIRT  RES  SHR S   %CPU %MEM    TIME+  COMMAND                                                                                                                  
 4589 bsc18725  20   0  969m 734m  22m S     38  2.3   0:15.60 wxparaver.bin  
```
Could you try login to mn2.bsc.es or mn3.bsc.es ?

**Comment by kinow** [comment]
In GitLab by @fmassonn on Jun 9, 2016, 09:25

Hi,

I have had the same problem with Autosubmit3.6. Do you think this can be related to a problem with the login node?

Log:
`/home/Earth/fmassonn/logs/autosubmit/log_a06a_20160608102554_bscesautosubmit01`


`9820 of 11666 jobs remaining (16:51)
^[[31m[CRITICAL] Unhandled exception on Autosubmit: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 287, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 615, in run_experiment
    if prev_status != job.update_status(platform.check_job(job.id)):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 188, in check_job
    while not self.send_command(self.get_checkjob_cmd(job_id)) and retries >= 0:
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/platforms/locplatform.py", line 93, in send_command
    output = subprocess.check_output(command, shell=True)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
`

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jun 9, 2016, 10:44

Hi @fmassonn since Autosubmit 3.6 uses Paramiko I would rather say that the problem is in the bscesautosubmi01 virtual machine. @omula could you look at the logs of the vmachine to see if there were memory usage problems with autosubmit instances ?
@fmassonn How many experiments with `TOTAL_JOBS=30` where you running at the same time ?

**Comment by kinow** [comment]
In GitLab by @ root on Jun 9, 2016, 11:09

@fmassonn can you please stop a06q? it seems its using 1.6GB of RAM we need to see why. Thanks

**Comment by kinow** [comment]
In GitLab by @fmassonn on Jun 9, 2016, 11:39

Hi @dmanubens 

I was running two such jobs: a06q and a06a

`
fmassonn@ bscesautosubmit01: ~/logs/autosubmit >> for exp in a06a a06q; do grep TOTALJOBS /esnas/autosubmit/a06a/conf/autosubmit_a06a.conf ; done 
TOTALJOBS = 30
TOTALJOBS = 30
`


François

**Comment by kinow** [comment]
In GitLab by @fmassonn on Jun 9, 2016, 17:25

Hi @omula @dmanubens 

Did you have the opportunity to investigate the problem? Can I restart `a06q`?

François

**Comment by kinow** [comment]
In GitLab by @fmassonn on Jun 10, 2016, 16:00

Okay, thanks for letting me know.
