### ISSUE TITLE
Flushing Failed

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#139]
In GitLab by @fmassonn on May 30, 2016, 15:27

Hi,
Sorry, it's me again!

Now I'm running on MareNostrum2 but I have another issue

exp: a06q
log: /home/Earth/fmassonn/logs/autosubmit/log_a06q_20160530145956

2016-05-30 15:27:44,966: radical.saga.pty    : MainProcess                     : MainThread     : ERROR   : flushing failed
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (RARY_PATH)
load HDF5/1.8.10 (PATH, LD_LIBRARY_PATH)
load UDUNITS/2.1.24 (PATH)
load CDO/1.7.0 (PATH)
cns96177@mn1.bsc.es:/gpfs/scratch/cns96/cns96177 >> $$HELLO_1_SAGA
$login2:/gpfs/scratch/cns96/cns96177> PROMPT-0->Shared connection to mn2.bsc.es closed.
) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
[ERROR] a06q_19740101_fc24_23_POST submission failed

François

**Comment by kinow** [comment]
In GitLab by @fmassonn on May 30, 2016, 17:23

I'm sorry, but I have this error again. This did not happen when I was using mn1 as the default connection node.

log: /home/Earth/fmassonn/logs/autosubmit/log_a071_20160530143204

PROMPT-0->Shared connection to mn2.bsc.es closed.
) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))

**Comment by kinow** [comment]
In GitLab by @fmassonn on May 30, 2016, 17:31

And also my log files become super big! That did not happen before.

  12G -rw-r--r-- 1 fmassonn Earth   12G May 30 17:31 log_a071_20160530143204

**Comment by kinow** [comment]
In GitLab by @dmanubens on May 30, 2016, 19:37

hi @fmassonn this huge log output is not normal. Your experiment was still consuming 100% CPU and SAGA went crazy with the flushing and wrote a lot of SAGA outputsto the log file. Although the SAGA logs are not necessary in normal conditions now that we are trying to sort out the issue they are quite useful... but in this case it was just too much crap. You can remove the big file.
I have killed and started again your experiment using Mario's account. 
Let's see if it reproduces with the reduced number of `TOTAL_JOBS` and higher `SAFETYSLEEPTIME`

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 15:33

closed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 15:33

closed due being related to saga(discontinued) and marenostrum2.
