### ISSUE TITLE
Problem with "authentication" with Autosubmit 3.5.0

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#140]
In GitLab by @ mariag on Jun 1, 2016, 18:14

Hi,

Just to report that I got an error with Autosubmit 3.5.0 regarding some authentication issue (see below or in  
/esnas/autosubmit/a046/logs/20160604_a046.log) that causes the process to crash. 

Using a previous version solves the problem. 

------------ERROR MESSAGE:
2016-06-01 17:41:08,537: radical.saga.pty    : MainProcess                     : MainThread     : ERROR   : prompted for unknown password (Password: ) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +313 (_initialize_pty)  :  % match))
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 313, in _initialize_pty
    % match)
AuthenticationFailed: prompted for unknown password (Password: ) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +313 (_initialize_pty)  :  % match))
2016-06-01 17:41:13,681: radical.saga.pty    : MainProcess                     : MainThread     : ERROR   : prompted for unknown password (Password: ) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py +313 (_initialize_pty)  :  % match))
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 313, in _initialize_pty
    % match)

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jun 2, 2016, 10:45

Hi @ mariag 
Thanks for reporting.
We already have a solution in the develop branch, we'll announce the release soon.

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jun 7, 2016, 11:55

Status changed to closed by commit 26ad8d5ba7e643d0a4fb1811d78027a0b893b647
