### ISSUE TITLE
How to handle data downloads every 5 minutes

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1425]
In GitLab by @ainagaya on Sep 26, 2024, 13:11

Hi @dbeltrankyl @kinow ,

As I think that Francesca explained to you today, for `auto-PHENOMENA` we will have to download data from a webpage every 5 minutes. We were thinking on how to set that up with Autosubmit. 

My first idea would be to use `RETRY_DELAY_TIME` + soft dependency (FAILED). That would mean:
1) We start the experiment, let's say, at 00:00. Data is downloaded. Job successful -> Next chunk submitted.
2) The next chunk is submitted at 00:00+run time of the previous chunk. If more than 5 minutes passed, the task is failed (the data was already downloaded). Autosubmit waits for something like 3 minutes (RETRY_DELAY_TIME) to submit the retrial. In the meantime, it submits the next chunk, that will fail, wait for 3 minutes, and try again.

I see a lot of gaps in my approach. For example, if the first chunk takes more than 5 minutes to run, we would be losing data. But if the soft dependency is with RUNNING, we will have too many "attempts" at the same time, I think.

I believe that @kinow had some ideas! 

cc @lauherrero @f-macchia @charlio86 @CarmenPinero @arturvinas (am I missing someone?)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 26, 2024, 14:20

Hello @ainagaya 

Without touching anything in Autosubmit...

Is there a wallclock in the platform you want to run that? 

How many chunks do you want to run? 

Perhaps you can set something with the as_checkpoints + running


Some ideas

1) Using Autosubmit checkpoints: 

Template: ( bash equivalent, it is a quick pseudocode)

something similar could work...

```python

while True: # or any other condition
   if #download_function is true:
      as_checkpoint # note it is a function included in the template, not a placeholder and must be in lowercase
   else:
     # not sure
   sleep(60*5)
```

```yaml
JOBS:
  DOWNLOAD:
    file: download.sh
    wallclock: infinite?
  somethingelse:
    file: dummy.sh
    RUNNING: chunk  
    DEPENDENCIES:  # This would be the difficult part to set
     DOWNLOAD: 
      CHUNKS_FROM:
        1:   
           STATUS: "RUNNING"
           FROM_STEP: 1
        2:
           STATUS: "RUNNING"
           FROM_STEP: 2
        ....
```

*DISCLAIMER: From_step has not been tested by users but in case of issues I could apply a fix

2) Generate a new experiment for download each 5 minutes

**t034 = download_workflow = autosubmit expid ...**

```
Script.sh
  while...
    autosubmit create t034
    autosubmit run t034
    sleep 60*5 # or better make run blocking
```

Templates of t034, download and move? to a common shared place?

**t035 = real_experiment = autosubmit expid ...**

autosubmit create, run 

* Datachecker, run by chunk: check if the download is in the right place; add delay_retrials to this job if it is not. 

* somethingelse job: depends on data checker,

**Comment by kinow** [comment]
In GitLab by @ainagaya on Oct 1, 2024, 15:37

Hi @dbeltrankyl !

Thanks for the answer. 

> Is there a wallclock in the platform you want to run that?

For now we are running in the login of the HUB, so there is no wallclock. The future plans are not very clear yet. 

> How many chunks do you want to run?

This is planned to be an operational download. So as far as I know, it has to run every five minutes, "forever". But the other day in a meeting Francesca said that it is not very safe to have an experiment running indefinitely. So we are thinking about it. 

#### About option 1

I never used autosubmit checkpoints before. We will prepare a prototype with @lauherrero and come back to you. FYI Laura: https://autosubmit.readthedocs.io/en/master/userguide/defining_workflows/index.html#start-conditions

#### About option 2

It is something that we thought could work, but we are a bit concerned about it because depending on how long it takes to download the data, we will potentially have the same experiment in two different instances, and autosubmit will fail. But its an option to consider too. 


Many thanks for your answer. Best!

**Comment by kinow** [comment]
In GitLab by @ainagaya on Oct 2, 2024, 12:27

mentioned in issue nextgeneu/internal/PHENOMENA#63

**Comment by kinow** [comment]
In GitLab by @lauherrero on Oct 2, 2024, 14:43

Hi @dbeltrankyl ,
Thank you very much for helping us :smile:
We are following the first option but `autosubmit create` outputs this error because of the names of the CHUNKS_FROM list:
```bash
 [CRITICAL] A not admitted configuration or error in the code has happened: 'int' object has no attribute 'lower'.
 Please report it to Autosubmit Developers through Git
```
Our job list looks like this:
```yml
JOBS:
  DOWNLOAD_madrid_traffic:
    FILE: templates/download_traffic.sh,templates/downloads/madrid_traffic.yml
    PLATFORM: local
    FILE_TO_DOWNLOAD: madrid_traffic
    RUNNING: chunk
    DEPENDENCIES:
      DOWNLOAD_madrid_traffic:
        CHUNKS_FROM:
          1:
            STATUS: "RUNNING"
            FROM_STEP: 1
          2:
            STATUS: "RUNNING"
            FROM_STEP: 2
```

If we change the CHUNKS_FROM list names with a letter, like (_1_ -> _C1_, _2_ -> _C2_), this error disappears. We think that we need names to be _1_ and _2_ to denote chunks, is there an option to do that? We have also attempted with _"1"_ and _"2"_ but it didn't work.

Just in case it is necessary, this is out expdef:
```yml
experiment:
    # Supply the list of start dates. Available formats: YYYYMMDD YYYYMMDDhh YYYYMMDDhhmm
    # Also you can use an abbreviated syntax for multiple dates with common parts:
    # 200001[01 15] <=> 20000101 20000115
    # DATELIST: 19600101 19650101 19700101
    # DATELIST: 1960[0101 0201 0301]
    DATELIST: 20241002
    # Supply the list of members. LIST: fc0 fc1 fc2 fc3 fc4
    MEMBERS: fc0
    # Chunk size unit. STRING: hour, day, month, year
    CHUNKSIZEUNIT: hour
    # Chunk size. NUMERIC: 4, 6, 12
    CHUNKSIZE: 24
    # Split size. NUMERIC: 4, 6, 12
    SPLITSIZE: 1
    # Total number of chunks in experiment. NUMERIC: 30, 15, 10
    NUMCHUNKS: 1
    # Calendar used. LIST: standard, noleap
    CALENDAR: standard

GENERAL:
    DOWNLOADS_PATH: "%ROOTDIR%/downloads"

```

We are using the experiment at _/esarchive/autosubmit/a7rl_

Thank you!

cc: @ainagaya

**Comment by kinow** [comment]
Until Dani has time to have a look, check if `autosubmit -lc DEBUG create ...` gives you any further information... if it contains the traceback exception info, that could help us to find where in the AS code that's happening.

**Comment by kinow** [comment]
In GitLab by @lauherrero on Oct 2, 2024, 15:00

These are the last lines of `autosubmit -lc DEBUG create a7rl` output:

```bash
2024-10-02 14:56:15,819 Adding dependencies for DOWNLOAD_MADRID_TRAFFIC jobs
2024-10-02 14:56:15,822 Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/EGG-INFO/scripts/autosubmit", line 59, in main
    return_value = Autosubmit.parse_args()
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/autosubmit.py", line 739, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output, args.group_by, args.expand,
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/autosubmit.py", line 4536, in create
    job_list.generate(as_conf,date_list, member_list, num_chunks, chunk_ini, parameters, date_format,
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/job/job_list.py", line 276, in generate
    self._add_dependencies(date_list, member_list, chunk_list, self._dic_jobs)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/job/job_list.py", line 446, in _add_dependencies
    problematic_dependencies = self._manage_job_dependencies(dic_jobs, job, date_list, member_list, chunk_list,
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/job/job_list.py", line 1344, in _manage_job_dependencies
    filters_to_apply = self._filter_current_job(job, copy.deepcopy(dependency.relationships))
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/job/job_list.py", line 920, in _filter_current_job
    filters_to_apply = self._check_chunks(relationships, current_job)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/job/job_list.py", line 764, in _check_chunks
    filters_to_apply = self._unify_to_filters(filters_to_apply)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/job/job_list.py", line 881, in _unify_to_filters
    only_none_values = [filters for filters in unified_filter.values() if "none" == filters.lower()]
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/job/job_list.py", line 881, in <listcomp>
    only_none_values = [filters for filters in unified_filter.values() if "none" == filters.lower()]
AttributeError: 'int' object has no attribute 'lower'

[CRITICAL] 2024-10-02 14:56:15,825 A not admitted configuration or error in the code has happened: 'int' object has no attribute 'lower'.
 Please report it to Autosubmit Developers through Git
2024-10-02 14:56:15,825 More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html

```

Thank you @kinow :)

**Comment by kinow** [comment]
Tha's useful, @lauherrero , looking at the 4.1.9 tag code, I **think** here's where you are getting the `lower` value, https://earth.bsc.es/gitlab/es/autosubmit/-/blob/ebb0aa027f081b27faf18d0909e83cf67476a702/autosubmit/job/job_list.py#L881

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/740180fa20fe186a905fed25e0791b25/image.png)

I'd have to attach the debugger and reproduce to confirm what's causing the error exactly, but I think @dbeltrankyl might be able to tell that just reading the comments and with this info about where the error happened :slight_smile:

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 2, 2024, 16:07

Hello @kinow , @lauherrero 

The issue you mention is because the filter expects a string, if you put it wrapped with "" it works... but I found some issues 

Ideally, what you would want to do is similar to this, right? 

```yaml
JOBS:
  DOWNLOAD_madrid_traffic:
    FILE: templates/download_traffic.sh,templates/downloads/madrid_traffic.yml
    PLATFORM: local
    FILE_TO_DOWNLOAD: madrid_traffic
    RUNNING: once
  DO_WORK:
    file: test.sh
    platform: local
    running: chunk
    dependencies:
      DOWNLOAD_madrid_traffic:
        status: "RUNNING"
        CHUNKS_FROM:
          "1":
            FROM_STEP: "1"
          "2":
            FROM_STEP: "2"
          "3":
            FROM_STEP: "3"
          "4":
            FROM_STEP: "4"
```

[a00a_20241002_1556.pdf](https://earth.bsc.es/gitlab/es/autosubmit/uploads/755b34695a2fc04711c303472979c248/a00a_20241002_1556.pdf)

So then, each do_work chunk can start whenever the download_madrid_traffic reaches a certain checkpoint. 


In https://earth.bsc.es/gitlab/es/autosubmit/-/merge_requests/493 , I've applied a fix so that when only from_step is added, the filter part is not triggered as it shouldn't, so this works.

However, I found some issues with the iteration between once/date jobs and chunk jobs. I require more time for this one because it will affect other workflows, so I have to look at it.

@kinow, maybe I can apply a temporal patched version on the hubs after !https://earth.bsc.es/gitlab/es/autosubmit/-/merge_requests/493 so they can use it?

**Comment by kinow** [comment]
>@kinow, maybe I can apply a temporal patched version on the hubs after !https://earth.bsc.es/gitlab/es/autosubmit/-/merge_requests/493 so they can use it?

Probably easier to deploy the latest version from GitLab to the hub? Maybe from a commit, and just abbreviate the commit hash (e.g. something like `autosubmit-4.1.11-11cf8672` for commit `11cf8672`, version 4.1.11, or even use the [Python version dev suffix](https://peps.python.org/pep-0440/#summary-of-permitted-suffixes-and-relative-ordering), `autosubmit-4.1.11.dev0-11cf8672`)

**Comment by kinow** [comment]
In GitLab by @ainagaya on Oct 15, 2024, 11:10

mentioned in merge request nextgeneu/internal/auto-phenomena!11

**Comment by kinow** [comment]
In GitLab by @ainagaya on Oct 15, 2024, 15:42

mentioned in commit 90749112e667babf56b5f28792a91fc8e1dfda74

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 21, 2024, 11:18

mentioned in commit 56ffbf8462181bef40d75ec7d836e1e1d3e425e3

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 5, 2024, 12:39

I think that the configuration was working and done by @ainagaya , so closing this issue.

Should be working in v4.1.11
