### ISSUE TITLE
Improve Archive Error Message

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1433]
In GitLab by @manuel-g-castro on Oct 9, 2024, 07:17

Hello @dbeltrankyl, @kinow, and @isimo00 

### Autosubmit Version

3.15.15, but probably all.

### Expid affected

a7dc a773 a75j a6zs a74v a74r 

### Summary

Autosubmit throws a random error upon failing to archive due to unpushed changes to the project folder.

### Steps to reproduce

1. Create an experiment with project type git, 
2. make changes on the experiment's project folder located at Autosubmit's local folder (i.e. `/esarchive/autosubmit`) path (according to `.autosubmitrc`). 
3. execute `autosubmit archive expid` 

### What is the current bug behavior?

```
Autosubmit is running with 3.15.15

Checking configuration files...
expdef_a773.conf OK
platforms_a773.conf OK
jobs_a773.conf OK
wrappers OK
autosubmit_a773.conf OK
Configuration files OK

Registering commit SHA...
Cleaning GIT directory...
Changes not committed detected... SKIPPING!
[ERROR] Trace: 'AutosubmitCritical' object has no attribute 'messagee'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.15.15-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.15-py2.7.egg/EGG-INFO/scripts/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/shared/earth/software/autosubmit/3.15.15-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.15-py2.7.egg/autosubmit/autosubmit.py", line 670, in parse_args
    return Autosubmit.archive(args.expid, noclean=args.noclean, uncompress=args.uncompress)
  File "/shared/earth/software/autosubmit/3.15.15-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.15-py2.7.egg/autosubmit/autosubmit.py", line 4192, in archive
    if version is not None and version.startswith('3') and not Autosubmit.clean(expid, True, True, True):
  File "/shared/earth/software/autosubmit/3.15.15-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.15-py2.7.egg/autosubmit/autosubmit.py", line 2783, in clean
    e.messagee)
AttributeError: 'AutosubmitCritical' object has no attribute 'messagee'
 [CRITICAL] None'AutosubmitCritical' object has no attribute 'messagee'
Unhandled error: If you see this message, please report it in Autosubmit's GitLab project
```

### What is the expected correct behavior?

Something along the lines of 

```
Autosubmit is running with 3.15.15

Checking configuration files...
expdef_a773.conf OK
platforms_a773.conf OK
jobs_a773.conf OK
wrappers OK
autosubmit_a773.conf OK
Configuration files OK

Registering commit SHA...
Cleaning GIT directory...
[CRITICAL] Cannot archive an experiment with unpushed local changes to the project folder. 
```

**Comment by kinow** [comment]
Looks like it's a typo on 3.15, https://earth.bsc.es/gitlab/es/autosubmit/-/blob/382abde7dc4b90bf9aedb7b83c67ddd354359ed1/autosubmit/autosubmit.py#L2782-2783

The message seems to indicate you may not have permissions to archive it, but it's likely that in reality this might be some other error that happened in the code. If you need this before a fix is out, `pdb` can be used to set a breakpoint on that line in v3, and then inspect the exception before another exception happens in that catch block.

I just checked `master` branch and we don't have it, so AS 4.x looks OK.

**Comment by kinow** [comment]
In GitLab by @manuel-g-castro on Oct 9, 2024, 08:06

My understanding is that it is not possible to archive an experiment which the project folder does not match a commit on remote. Anddd, indeed, there are local changes (these are Pablo's experiments, which he added a script to the workflow). So the error message is correct (but confusing)!

It is not urgent, I just wanted to cleanup my unused experiments and reduce space on `esarchive`. And since these are experiments that Pablo used in his thesis, and will be mentioned on his upcomming paper, they need to be stored (although I believe experiments under his user were deleted...).

Okay! If the 4.x works, great!

**Comment by kinow** [comment]
In GitLab by @isimo00 on Oct 9, 2024, 08:42

Without being super familiar with this, it looks like it's just a typo for the `message` atribute, right? As @kinow said, it is misspelled as `messagee` in line 2783 of `autosubmit.py`, v3.15.15. I just checked and instead of using `e.message` we use `str(e)` for the same line in further versions: https://earth.bsc.es/gitlab/es/autosubmit/-/blob/master/autosubmit/autosubmit.py#L2888
