### ISSUE TITLE
Can not create experiment

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#144]
In GitLab by @obellprat on Jun 8, 2016, 10:16

Hi,

I have again a python failure when trying to create an experiment. Eventhough autosubmit is working fine, 

obellpra@ bscearth315:~$ module load autosubmit

obellpra@ bscearth315:~$ autosubmit -v
3.6.0

obellpra@ bscearth315:~$ autosubmit create a045
[CRITICAL] Unhandled exception on Autosubmit: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 304, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 1452, in create
    with portalocker.Lock(os.path.join(tmp_path, 'autosubmit.lock'), timeout=1):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/portalocker-0.5.7-py2.7.egg/portalocker/utils.py", line 188, in __enter__
    self.fh = self.acquire()
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/portalocker-0.5.7-py2.7.egg/portalocker/utils.py", line 139, in acquire
    raise AlreadyLocked(exception)
AlreadyLocked: [Errno 11] Resource temporarily unavailable

@dmanubens @ jlope2 @fmassonn @mmenegoz @ cprodhomme @vsicardi @Eleftheriaexarchou

**Comment by kinow** [comment]
In GitLab by @obellprat on Jun 8, 2016, 10:19

It seems it was because the experiment was already running, ignore it :)

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jul 8, 2016, 16:53

Hi @obellprat, since the next release (3.7.0), the message given will be user-friendlier in order to avoid this kind of confusions.

#151

Thanks for the feedback! ;)
