### ISSUE TITLE
files at tmp not created

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1442]
In GitLab by @lauherrero on Oct 28, 2024, 14:30

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v4.1.9

### Expid affected(If applicable)

a7wv

### Summary

I am trying to run autosubmit at the hub sending jobs to bscearth000. The problem is that the files in the _tmp_ directory are not being created when I use the bscearth00 platform, and they are needed to run my job.

I have done it with a simple job without any dependency on the tmp files and it has worked.

I have also run the same job locally and it has worked.

When I run `autosubmit inspect` these files are created, but if I run `autosubmit create` they disappear.

### Steps to reproduce

- Create an experiment with: 
```bash
 $ autosubmit expid -d "my first auto-phenomena test" -H "Marenostrum5" -min --git_as_conf conf/bootstrap --git_repo https://earth.bsc.es/gitlab/nextgeneu/internal/auto-phenomena --git_branch 10-platforms
 $ autosubmit create EXPID
 $ autosubmit run EXPID

```
- Remember to change the user and scratch_dir on the _bscearth_ platform at _/esarchive/autosubmit/EXPID/proj/git_project/conf/platform.yml_

### What is the current bug behavior?

The file _/esarchive/autosubmit/a7wv/tmp/ENTSOE_unit_2024102800_fc0_1_DOWNLOAD_ENTSOE_UNIT_ is not created.

### What is the expected correct behavior?

The file _/esarchive/autosubmit/a7wv/tmp/ENTSOE_unit_2024102800_fc0_1_DOWNLOAD_ENTSOE_UNIT_ created.

### Relevant logs and/or screenshots(if applicable)

This is the error:

```bash
Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/platforms/paramiko_platform.py", line 386, in send_file
    self._ftpChannel.put(local_path, remote_path)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/paramiko/sftp_client.py", line 758, in put
    with open(localpath, "rb") as fl:
FileNotFoundError: [Errno 2] No such file or directory: '/esarchive/autosubmit/a7wv/tmp/ENTSOE_unit_2024102800_fc0_1_DOWNLOAD_ENTSOE_UNIT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/job/job_packages.py", line 203, in submit
    self._send_files()
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/job/job_packages.py", line 246, in _send_files
    self.platform.send_file(os.path.join(self._tmp_path, full_path))
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/platforms/paramiko_platform.py", line 390, in send_file
    raise AutosubmitError('Can not send file {0} to {1}'.format(os.path.join(
log.log.AutosubmitError:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/platforms/platform.py", line 308, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters, inspect, hold=hold)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/job/job_packages.py", line 209, in submit
    raise AutosubmitCritical("Error while submitting jobs: {0}".format(e), 7013)
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/autosubmit.py", line 2229, in run_experiment
    Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence, hold=False)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/autosubmit.py", line 2516, in submit_ready_jobs
    save_1, failed_packages, error_message, valid_packages_to_submit, any_job_submitted = platform.submit_ready_jobs(as_conf,
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/platforms/platform.py", line 346, in submit_ready_jobs
    raise AutosubmitCritical(e.message, e.code, e.trace)
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/EGG-INFO/scripts/autosubmit", line 59, in main
    return_value = Autosubmit.parse_args()
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/autosubmit.py", line 707, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive,args.start_time,args.start_after, args.run_only_members, args.profile)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.9-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.1.9-py3.9.egg/autosubmit/autosubmit.py", line 2340, in run_experiment
    raise AutosubmitCritical(e.message, e.code, e.trace)
log.log.AutosubmitCritical:  

 [CRITICAL] Error while submitting jobs:   [eCode=7013]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html

```

Thank you very much :)

cc: @ainagaya 
()

**Comment by kinow** [comment]
Hmm, I was curious and had a look at this issue. I could reproduce it with 4.1.9 and 4.1.11 dev version on the bsceshub02.

The file is definitely created, but in `platform.send_file(..., check=True)` after performing the "check" it calls `self.delete_file`, which deletes the file. And then it tries to copy the same file :sweat_smile: Looks like a chicken and egg problem, but might be due to both platforms (local/remote) sharing the same remote file system or the additional file being written to the wrong location -- not sure.

@dbeltrankyl any thoughts?

**Comment by kinow** [comment]
In GitLab by @ainagaya on Oct 30, 2024, 11:09

Hi @kinow ,

Thanks for checking!! Yesterday we had a conversation about this with @lauherrero , and simply changing the platform of the job from `bscearth000` to `MareNostrum5` was working smoothly. 

We want to use the `bscearth000` for the downloads, but I suspect that right now this machine is not supported by Autosubmit 4. I don't think that any AS4 workflow is using it yet, could you confirm @eferre1 @f-macchia ?

@lauherrero can you post here the platform configuration? Both what you have in `platforms.yml` and also the ssh configuration, maybe something is not well configured. Also, I thought that maybe you could do some tests by submitting the experiment from your laptop instead of from the hub. 

> Looks like a chicken and egg problem, but might be due to both platforms (local/remote) sharing the same remote file system or the additional file being written to the wrong location -- not sure.

I **think** that bscearth000 has `esarchive` mounted, and the hub too, and the experiment ROOTDIR is `/esarchive/autosubmit/$EXPID`. But in `bscearth000` Laura is using `SCRATCH_DIR: /scratch/Earth/`. So it should not be the same file system? 

cc @charlio86

**Comment by kinow** [comment]
>I **think** that bscearth000 has `esarchive` mounted, and the hub too, and the experiment ROOTDIR is `/esarchive/autosubmit/$EXPID`. But in `bscearth000` Laura is using `SCRATCH_DIR: /scratch/Earth/`. So it should not be the same file system?

That might be the case. I was only going through the issues before starting a review, and I may have missed something... what I did was to set a breakpoint in `send_files` with `pdb`, and then add a `watch -n 1 ls /..../THAT_FILE.yml` to watch what happened... and the file is definitely created at one point, and its variables are correctly replaced (checked the additional file contents in the debugger).

But I think I jumped from one function to another ignoring config/code, and only landed where the code was deleting the same file it created before :dizzy_face: . There might be something else that I'm missing and Dani might spot it from reading the config/logs :slight_smile:

**Comment by kinow** [comment]
In GitLab by @eferre1 on Oct 30, 2024, 11:22

Not from auto-ecearth side, as we only used the 000 machine in the past for the transfer jobs in some cases.

> I **think** that bscearth000 has `esarchive` mounted, and the hub too, and the experiment ROOTDIR is `/esarchive/autosubmit/$EXPID`. But in `bscearth000` Laura is using `SCRATCH_DIR: /scratch/Earth/`. So it should not be the same file system?

Regarding this, yes, the 000 machine has esarchive mounted, and doesn't have gpfs. And it might be that the `scratch_dir` is not properly defined, it should be `/esarchive/scratch/`, not `/scratch` directly. Which might mean that it is trying to copy the file to a scratch path without permissions, and then deleting the file as if it has been transferred.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 30, 2024, 11:31

Hello, 

```yaml
  BSCEARTH:
    TYPE: ps
    HOST: bscearth000
    USER: dbeltran
    PROJECT: Earth
    ADD_PROJECT_TO_HOST: false
    QUEUE: serial
    SCRATCH_DIR: /esarchive/scratch
```

This is working for me, maybe the issue is that the folder. 

`/esarchive/scratch/Earth/$user ` doesn't exist?

**Comment by kinow** [comment]
In GitLab by @ainagaya on Oct 30, 2024, 11:32

Thanks all for the fast answers!

@lauherrero can you try the configs that Dani posted above?

What I don't understand is that Laura showed me yesterday the experiment directory. The directory `/scratch/Earth/lherrero/${EXPID}/LOG_${EXPID}` (or something similar) contained the `.cmd` file, but didn't contain the Additional files.

**Comment by kinow** [comment]
>What I don't understand is that Laura showed me yesterday the experiment directory. The directory `/scratch/Earth/lherrero/${EXPID}/LOG_${EXPID}` (or something similar) contained the `.cmd` file, but didn't contain the Additional files.

At least for me it did contain the additional file... for some seconds... then Autosubmit deleted it -- https://earth.bsc.es/gitlab/es/autosubmit/-/blob/e787950161d3dfc01b94bdb1af15a09c11eee62d/autosubmit/platforms/paramiko_platform.py#L371-381

**Comment by kinow** [comment]
In GitLab by @lauherrero on Oct 30, 2024, 11:59

Hi,

Thanks to everyone! 

I tried to run the experiment `a7wv` by changing the platform information as @dbeltrankyl suggested to:
```yml
  bscearth:
    TYPE: ps
    HOST: bscearth000
    USER: lherrero
    PROJECT: Earth
    ADD_PROJECT_TO_HOST: false
    QUEUE: serial
    SCRATCH_DIR: /esarchive/scratch
```

It is not working for me and the error is the same, the .cmd is being created in bscearth000 but not the additional file. The last lines of the `tmp/ASLOGS/20241030_115034_run.log` file are:
```bash
Jobs ready for BSCEARTH: 1
[WARNING] 2024-10-30 11:50:52,936 Script a7wv_2024102800_fc0_1_DOWNLOAD_ENTSOE_UNIT has some empty variables. An empty value has substituted these variables
2024-10-30 11:50:53,123 Creating Scripts
2024-10-30 11:50:53,184 Sending Files
2024-10-30 11:50:54,007 /esarchive/scratch/Earth/lherrero/a7wv/LOG_a7wv has been created on bscearth000 .
2024-10-30 11:50:56,016 /esarchive/scratch/Earth/lherrero/a7wv/LOG_a7wv has been created on bscearth000 .
[CRITICAL] 2024-10-30 11:50:56,314 Error while submitting jobs:   [eCode=7013]
2024-10-30 11:50:56,314 More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

I created the `a7wv` experiment for this issue, if you need to check the logs you can just search for the experiment or I can send you everything you need.

Thank you very much :)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 30, 2024, 14:26

I see, I did a fast debug and maybe it is not triggered when I don't use templates ( project_type: None ). 

When I finish a pending issue I'll try to debug it with real templates and see if a fix is needed and apply it

**Comment by kinow** [comment]
In GitLab by @eferre1 on Oct 31, 2024, 11:34

Just to update, I didn't recall that we have some experiments in MN5 running with the 000 as transfer machine (on the testing suite to test that the option still works). So I can confirm that in some experiments we still use it, and it works. But that is autosubmit 3.15.19, so it might have some things different to what it has in AS-4.

So I can confirm that both `t0ne` and `t0nf` are running with the SYNC job on the 000 machine, without any issues, if needed they can be checked to compare the configuration for the platform.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 31, 2024, 12:41

Hello @lauherrero 

I don't seem to have access to  https://earth.bsc.es/gitlab/nextgeneu/internal/auto-phenomena


This is what I tried: 

```yaml
CONFIG:
  # Current version of autosubmit.
  AUTOSUBMIT_VERSION: "4.1.9"
  # Maximum number of jobs permitted in the waiting status.
  MAXWAITINGJOBS: 20
  # Total number of jobs in the workflow.
  TOTALJOBS: 20
  SAFETYSLEEPTIME: 0
  RETRIALS: 0
MAIL:
  NOTIFICATIONS: False
  TO:
STORAGE:
  TYPE: pkl
  COPY_REMOTE_LOGS: true
DEFAULT:
  # Job experiment ID.
  EXPID: "a7xr"
  # Default HPC platform name.
  HPCARCH: "bscearth"

EXPERIMENT:
  DATELIST: 20221101
  MEMBERS: fc0
  CHUNKSIZEUNIT: month
  #SPLITSIZEUNIT: day
  CHUNKSIZE: 2
  NUMCHUNKS: 1
  #SPLITSIZE: 1
  SPLITPOLICY: flexible
  CHUNKINI: ''
  CALENDAR: standard
PROJECT:
  # Type of the project.
  PROJECT_TYPE: git
  # Folder to hold the project sources.
  PROJECT_DESTINATION: git_project
GIT:
  PROJECT_ORIGIN: "blabla"
  PROJECT_BRANCH: "blabla"
  PROJECT_COMMIT: ''
  PROJECT_SUBMODULES: ''
  FETCH_SINGLE_BRANCH: true
PLATFORMS:
  bscearth:
    TYPE: ps
    HOST: bscearth000
    USER: dbeltran
    PROJECT: Earth
    ADD_PROJECT_TO_HOST: false
    QUEUE: serial
    SCRATCH_DIR: /esarchive/scratch


JOBS:
  dummy:
    FILE: "conf/test.sh,conf/add_test.yml"
    running: once
```

and this structure 

```bash
[dbeltran@ bsceshub02 a7xr]$ mkdir -p proj/git_project/conf
[dbeltran@ bsceshub02 a7xr]$ touch proj/git_project/conf/test.sh
[dbeltran@ bsceshub02 a7xr]$ touch proj/git_project/conf/add_test.yml
```

In hubs I'm obtaining the same error

```
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/paramiko/sftp_client.py", line 758, in put
    with open(localpath, "rb") as fl:
FileNotFoundError: [Errno 2] No such file or directory: '/esarchive/autosubmit/a7xr/tmp/add_test_DUMMY'
```

However, on my laptop, it works ( v4.1.9 tag)

```bash
a000_DUMMY job seems to have completed: checking...
Job a000_DUMMY is COMPLETED
Updating FAILED jobs
Updating WAITING jobs
Update finished
Saving JobList: /home/dbeltran/autosubmit/a000/pkl/job_list_a000.pkl.tmp
JobList saved in /home/dbeltran/autosubmit/a000/pkl/job_list_a000.pkl
Backing up jobs_data...
Jobs_data database backup completed.
No more jobs to run.
```

I've also tested it with a pip install on my laptop...

```bash
# new venv blablabla
pip install autosubmit==4.1.9 
autosubmit create a000
autosubmit run a000
```

```yaml
Loading JobList
Load finished
Creating jobs...
Adding dependencies to the graph..
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...
Autosubmit is running with v4.1.9
Checking the connection to all platforms in use
[BSCEARTH] Correct user privileges for host bscearth000
[BSCEARTH] Connection successful to host bscearth000


1 of 1 jobs remaining (12:39)
No jobs to check for platform BSCEARTH
File /home/dbeltran/autosubmit/a000/proj/git_project/conf/test.sh exists
Calculating possible ready jobs for BSCEARTH
Section:DUMMY can submit 20 jobs at this time
Script a000_DUMMY OK
a000_DUMMY submitted
Call from a000_DUMMY with status SUBMITTED
Call from a000_DUMMY with status SUBMITTED


1 of 1 jobs remaining (12:39)
Checking 1 jobs for platform BSCEARTH
Job a000_DUMMY is COMPLETED
No more jobs to run.
Waiting for all logs to be updated
Timeout: 180
Run successful
```

So whatever it is happening is at least not happening in all machines

**Comment by kinow** [comment]
@apuiggro could you have a look at the original description from @lauherrero , and at this last comment from @dbeltrankyl ? I **think** you are having the exact same issue with SUNSET+Autosubmit using the hub & your laptop? One works, and the other fails with the same/similar message?

**Comment by kinow** [comment]
In GitLab by @charlio86 on Oct 31, 2024, 14:39

@dbeltrankyl I've provided you access to the PHENOMENA repositories

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 31, 2024, 15:44

Hello all, 

I've found the issue and successfully tested a fix. To use it is easier as do this:

```bash
 1001  git clone https://earth.bsc.es/gitlab/es/autosubmit.git -b gl-1443-ps_platform_additional_files_tmp_not_created

1005  module load Python/3.9.6-GCCcore-11.2.0
 1006  python3 -m venv autosubmitenv
 1007  autosubmitenv activate
 1008  source autosubmitenv/bin/activate
 1010  cd autosubmit
 1013  pip install setup.py .

# It will automatically use the esarchive database
autosubmit create ...
autosubmit run ...
```

Right now, this branch https://earth.bsc.es/gitlab/es/autosubmit/-/merge_requests/508 is working on the hubs, but I want to apply a cleaner fix and revise the tests. ( not time today)

**Comment by kinow** [comment]
In GitLab by @ainagaya on Oct 31, 2024, 16:59

mentioned in issue nextgeneu/internal/PHENOMENA#65

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 5, 2024, 12:33

Merged !508, should be ready for next version (4.1.11)
