### ISSUE TITLE
autosubmit configure depends on a terminal window size

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#145]
In GitLab by @ rbakhshi on Jun 16, 2016, 08:09

Hi,

Running "autosubmit configure" in a non-full screen terminal window leads to the following error:

[CRITICAL] Unhandled exception on Autosubmit:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/autosubmit/autosubmit.py", line 306, in parse_args
    return Autosubmit.configure()
  File "/usr/local/lib/python2.7/dist-packages/autosubmit/autosubmit.py", line 1124, in configure
    title='\Zb\Z1Select path to database\Zn', colors='enable')
  File "/usr/local/lib/python2.7/dist-packages/dialog.py", line 2409, in dselect
    kwargs, raw_help=True)
  File "/usr/local/lib/python2.7/dist-packages/dialog.py", line 1748, in _widget_with_string_output
    code, output = self._perform(args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dialog.py", line 1543, in _perform
    args_file)
  File "/usr/local/lib/python2.7/dist-packages/dialog.py", line 1504, in _handle_program_exit
    child_output_rfd)
  File "/usr/local/lib/python2.7/dist-packages/dialog.py", line 1456, in _wait_for_program_termination
    child_output.strip()))
DialogError

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jul 8, 2016, 16:46

Hi @ rbakhshi,

I'm trying to reproduce this problem but I can't.

Which terminal are you using?

I've tried it with some different sizes with Konsole & GNOME Terminal and everything works correctly.

Thanks!

**Comment by kinow** [comment]
In GitLab by @ rbakhshi on Jul 8, 2016, 21:55

This is GNOME Terminal (v 3.14.1) in a Debian 8 virtualbox image. Full-screen terminal window solves the issue.

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jul 11, 2016, 11:24

Google-ing around, It seems that has to do with the size of the window... (https://github.com/certbot/certbot/issues/2813)
Maximizing the window it works...
When terminal window is not tall enough it fails with this cryptic message. Instead of failing with an error, it should either ask the user to resize their terminal window, or it should work with a shorter window.
We'll go for using autowidgetsize (http://pythondialog.sourceforge.net/doc/Dialog_class_overview.html#autowidgetsize)

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jul 11, 2016, 11:27

I've detected that it only works for the first screen. Then, when I go to the next step, it crashes.

I will check it with the @dmanubens suggestion.

Thanks!

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jul 12, 2016, 11:14

We've added an alert that suggests resize the terminal screen. Now we close the configuration wizard in order to avoid this kind of problems.

Maybe in a future version we will try to implement a better (responsive) solution.

THanks @ rbakhshi
