### ISSUE TITLE
Enabling NOTIFICATIONS may lead to errors with NOTIFY_ON (or if it's not present)

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1467]
### Autosubmit Version

`master`, `4.1.11`

### Summary

If you create a simple workflow, with just one task, and enable notifications with this:

```yaml
mail:
    # Enable mail notifications for remote_failures
    # Default:True
    NOTIFY_ON_REMOTE_FAIL: True
    # Enable mail notifications
    # Default: False
    NOTIFICATIONS: True
    # Mail address where notifications will be received
    TO: bruno@blabla.blabla
```

Without adding `NOTIFY_ON` to the sole job, you will get:

```
Successful check job command: nohup kill -0 623 > /dev/null 2>&1; echo $?
Successful check job command: nohup kill -0 633 > /dev/null 2>&1; echo $?
Job a030_20221101_fc0_1_A is RUNNING
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/bin/autosubmit", line 36, in main
    return_value = Autosubmit.parse_args()
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 711, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive,args.start_time,args.start_after, args.run_only_members, args.profile)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 2264, in run_experiment
    Autosubmit.job_notify(as_conf,expid,job,job_prev_status,job_changes_tracker)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 1837, in job_notify
    if Status.VALUE_TO_KEY[job.status] in job.notify_on:
AttributeError: 'Job' object has no attribute 'notify_on'

 [CRITICAL] Unexpected error: 'Job' object has no attribute 'notify_on'.
 Please report it to Autosubmit Developers through Git
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

The issue was found by @apuiggro.

### Steps to reproduce

```yaml
# local project, you can use SCRIPT instead
EXPERIMENT:
   DATELIST: 20221101 #Startdate
   MEMBERS: fc0
   CHUNKSIZEUNIT: month
   # SPLITSIZEUNIT: day
   NUMCHUNKS: 2
   CHUNKSIZE: 2
   #SPLITSIZE: 1
   CHUNKINIT: ''
   SPLITPOLICY: flexible
   CALENDAR: standard
JOBS:
  A:
    FILE: wait_1_hour.sh
    RUNNING: chunk
    PLATFORM: fake-ssh
    # NOTIFY_ON: RUNNING
PLATFORMS:
  fake-ssh:
    TYPE: ps
    HOST: fake-ssh
    SCRATCH_DIR: /tmp
    USER: autosubmit
mail:
    # Enable mail notifications for remote_failures
    # Default:True
    NOTIFY_ON_REMOTE_FAIL: True
    # Enable mail notifications
    # Default: False
    NOTIFICATIONS: True
    # Mail address where notifications will be received
    TO: bruno@blabla.blabal
```

### What is the current bug behavior?

Python error.

### What is the expected correct behavior?

Nothing, no notification as there is no notify_on.

### Relevant logs and/or screenshots(if applicable)

Above.

### Any other relevant information(if applicable)

()

**Comment by kinow** [comment]
Note, if you enable `NOTIFY_ON` in a job, the error will persist.

From what I could find in Git logs, I think this was removed in the Performance merge request between 4.0.99 and 4.1.0.

https://earth.bsc.es/gitlab/es/autosubmit/-/commit/33028b9cc1c40ae3c38b8f22c8530e8fb3656bf5?expanded=1

![image](https://my-gitlab-bucket.s3.amazonaws.com/902354155/1791f9aa4232a2a03de875404a77ca8a7a688d8cf2dc947b3771171d4ea7e380/image.png)

This fixes the bug,

```diff
diff --git a/autosubmit/job/job_dict.py b/autosubmit/job/job_dict.py
index d72af775..90dc7eb3 100644
--- a/autosubmit/job/job_dict.py
+++ b/autosubmit/job/job_dict.py
@@ -645,6 +645,12 @@ class DicJobs:
             section_data.append(job)
             self.changes["NEWJOBS"] = True
         else:
+            notify_on = self.as_conf.jobs_data.get(section).get("NOTIFY_ON", None)
+            if type(notify_on) == str:
+                self._job_list[name].notify_on = [x.upper() for x in notify_on.split(' ')]
+            else:
+                self._job_list[name].notify_on = ""
+
             self._job_list[name].update_dict_parameters(self.as_conf)
             self._job_list[name].status = Status.WAITING if self._job_list[name].status in [Status.DELAYED,
                                                                                             Status.PREPARED,
```

however, the performance optimization merge request had several improvements, including a function that centralizes the merging of conf-sections/parameters.

I am not sure whether notify_on should be set where the diff above sets it, or in that `update_dict_parameters` function.

I am also not 100% sure if `notify_on` is the only thing missing as that merge request modified some other properties (i.e. not sure if we haven't had a bug because there's none, or because users have not tried something yet).

**Comment by kinow** [comment]
In GitLab by @apuiggro on Nov 28, 2024, 10:03

mentioned in issue sunset#149

**Comment by kinow** [comment]
marked this issue as related to #1484
