### ISSUE TITLE
Error when archiving experiment

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1473]
In GitLab by @apuiggro on Nov 29, 2024, 11:56

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

Autosubmit 4.1.11-foss-2021b-Python-3.9.6

### Expid affected(If applicable)

a83j

### Summary

Error when archiving the experiment in rocrate format. 

### Relevant logs and/or screenshots(if applicable)

```
[apuiggro@ bsceshub02 conf]$ autosubmit -lc DEBUG archive --rocrate a83j
Autosubmit is running with 4.1.11
Archiving in year 2024
Loading JobList
Load finished
Creating jobs...
Creating TRANSFER_RECIPES jobs
Creating VERIFICATION jobs
Creating SCORECARDS jobs
Creating TRANSFER_RESULTS jobs
Creating TRANSFER_PROVENANCE jobs
Adding dependencies to the graph..
Looking if there are changes in the workflow
Changes detected, removing all dependencies
Dependencies deleted, recalculating dependencies
Adding dependencies for TRANSFER_RECIPES jobs
Adding dependencies for VERIFICATION jobs
Adding dependencies for SCORECARDS jobs
Adding dependencies for TRANSFER_RESULTS jobs
Adding dependencies for TRANSFER_PROVENANCE jobs
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...
Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.11-foss-2021b-Python-3.9.6/bin/autosubmit", line 36, in main
    return_value = Autosubmit.parse_args()
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.11-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit/autosubmit.py", line 771, in parse_args
    return Autosubmit.archive(args.expid, noclean=args.noclean, uncompress=args.uncompress, rocrate=args.rocrate)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.11-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit/autosubmit.py", line 4320, in archive
    Autosubmit.rocrate(expid, Path(year_path))
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.11-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit/autosubmit.py", line 4255, in rocrate
    exp_stats.calculate_statistics()
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.11-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit/statistics/statistics.py", line 50, in calculate_statistics
    job_stat = self._name_to_jobstat_dict.setdefault(job.name, JobStat(job.name, parse_number_processors(
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.11-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit/statistics/jobs_stat.py", line 11, in __init__
    self._processors = self._calculate_processing_elements(nodes, processors, tasks, processors_per_node, exclusive)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.11-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit/statistics/jobs_stat.py", line 43, in _calculate_processing_elements
    estimated_nodes = self._estimate_requested_nodes(nodes,processors,tasks,processors_per_node)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.1.11-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit/statistics/jobs_stat.py", line 32, in _estimate_requested_nodes
    return math.ceil(int(processors) / int(tasks))
ZeroDivisionError: division by zero

 [CRITICAL] Unexpected error: division by zero.
 Please report it to Autosubmit Developers through Git

```
()

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 29, 2024, 12:33

Hello @apuiggro 

I may think it is because the experiment was created with 4.0.98 but the archive with 4.1.11, 

Could you try to archive it with 4.0.98 or 4.0.105? 

If that doesn't work, 

Could you do, with 4.1.11, an `autosubmit create a83j -f -np `and then try to archive it?

**Comment by kinow** [comment]
In GitLab by @apuiggro on Dec 4, 2024, 09:57

Hey @dbeltrankyl,

Archiving in version 4.0.15 also gave me the same error. After discussing it with @kinow and adding the TASKS parameter in the jobs configuration, I was able to archive and create the RO-Crate correctly with version 4.1.1.

Thanks for your help, and sorry for the late response!

**Comment by kinow** [comment]
Thanks @apuiggro ! Created the issue explaining more or less what we found yesterday debugging the issue together. I think we can close this issue as you are able to archive it, and move the discussion there for now? https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1480

Cheers
