### ISSUE TITLE
"autosubmit installation" error message

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1476]
In GitLab by @lauherrero on Dec 2, 2024, 14:25

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v4.0.98, oper machine

### Summary

The first time you create an experiment on a machine, you have to run `autosubmit configure` and `autosubmit install`. If you do `autosubmit configure` and then try to create an experiment, autosubmit raises an error suggesting to run `autosubmit installation` instead of `autosubmit install`.

### Relevant logs and/or screenshots(if applicable)

``` bash
lherrero@ bscesoper:~> autosubmit expid -d "auto-phenomena test: oper daily" -H "oper" -min --git_as_conf conf/bootstrap --git_repo https://earth.bsc.es/gitlab/nextgeneu/internal/auto-phenomena --git_branch main
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/4.0.98-foss-2015a-Python-3.7.3/lib/python3.7/site-packages/autosubmit-4.0.98-py3.7.egg/EGG-INFO/scripts/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/shared/earth/software/autosubmit/4.0.98-foss-2015a-Python-3.7.3/lib/python3.7/site-packages/autosubmit-4.0.98-py3.7.egg/autosubmit/autosubmit.py", line 655, in parse_args
    Autosubmit._init_logs(args, args.logconsole, args.logfile, expid)
  File "/shared/earth/software/autosubmit/4.0.98-foss-2015a-Python-3.7.3/lib/python3.7/site-packages/autosubmit-4.0.98-py3.7.egg/autosubmit/autosubmit.py", line 751, in _init_logs
    raise AutosubmitCritical('Experiments database not found in this filesystem. Please run "autosubmit installation" first.',7072)log.log.AutosubmitCritical:  
 [CRITICAL] Experiments database not found in this filesystem. Please run "autosubmit installation" first. [eCode=7072]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
lherrero@ bscesoper:~> autosubmit installation
error: argument command: invalid choice: 'installation' (choose from 'run', 'expid', 'delete', 'monitor', 'stats', 'clean', 'recovery', 'migrate', 'inspect', 'check', 'describe', 'report', 'create', 'configure', 'install', 'setstatus', 'testcase', 'dbfix', 'pklfix', 'updatedescrip', 'test', 'refresh', 'updateversion', 'archive', 'unarchive', 'upgrade', 'readme', 'changelog', 'cat-log')
usage: autosubmit [-h] [-v] [-lf {NO_LOG,INFO,WARNING,DEBUG}]
                  [-lc {NO_LOG,INFO,WARNING,DEBUG}]
                  
                  {run,expid,delete,monitor,stats,clean,recovery,migrate,inspect,check,describe,report,create,configure,install,setstatus,testcase,dbfix,pklfix,updatedescrip,test,refresh,updateversion,archive,unarchive,upgrade,readme,changelog,cat-log}
                  ...

Main executable for autosubmit.

positional arguments:
  {run,expid,delete,monitor,stats,clean,recovery,migrate,inspect,check,describe,report,create,configure,install,setstatus,testcase,dbfix,pklfix,updatedescrip,test,refresh,updateversion,archive,unarchive,upgrade,readme,changelog,cat-log}

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
  -lf {NO_LOG,INFO,WARNING,DEBUG}, --logfile {NO_LOG,INFO,WARNING,DEBUG}
                        sets file's log level.
  -lc {NO_LOG,INFO,WARNING,DEBUG}, --logconsole {NO_LOG,INFO,WARNING,DEBUG}
                        sets console's log level

```
()

**Comment by kinow** [comment]
Hi @lauherrero ,

This was fixed some time ago by @pablogoitia and is included in 4.1.0, https://earth.bsc.es/gitlab/es/autosubmit/-/commit/ffe045d6cb00404b23f633d1859431d32471d321

Once you upgrade to a newer version I trust you should see the correct message. Closing as it's fixed already, but thanks for creating the issue anyway! :muscle:
