### ISSUE TITLE
unable to copy autosubmit experiment

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1486]
In GitLab by @ cponsman on Dec 11, 2024, 12:51

Hello @dbeltrankyl and @kinow, I'm using autosubmit version 3.15.19 and I get this error when trying to copy an experiment: 

```
autosubmit expid -H marenostrum5 -d "copy of t0n5 first test" --copy t0n5
Autosubmit is running with 3.15.19
Autosubmit's database version is 0. Current version is 1. Updating...
Process Process-1:
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/shared/earth/software/autosubmit/3.15.19-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.19-py2.7.egg/autosubmit/database/db_common.py", line 133, in fn_wrapper
    result = database_fn(*args)
  File "/shared/earth/software/autosubmit/3.15.19-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.19-py2.7.egg/autosubmit/database/db_common.py", line 326, in _check_experiment_exists
    (conn, cursor) = open_conn()
  File "/shared/earth/software/autosubmit/3.15.19-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.19-py2.7.egg/autosubmit/database/db_common.py", line 106, in open_conn
    if not _update_database(version, cursor):
  File "/shared/earth/software/autosubmit/3.15.19-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.15.19-py2.7.egg/autosubmit/database/db_common.py", line 536, in _update_database
    'unable to update database version', 7001, e.message)
AutosubmitCritical:  
[ERROR] Trace: The database process exceeded the timeout limit 10s. Check if experiment t0n5 exists failed to complete.
 [CRITICAL] Can not create experiment [eCode=7012]
```
I was able to do that last week with no issues.

Thanks a lot in advance!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 13:25

Hello @ cponsman 

There is currently an issue taking place in BSC machines related to /esarchive filesystem. #1483 

The machines affected are autosubmit01, autosubmit02, and WS machines. 

I recommend you to use the bschubs to launch Autosubmit while the issue persists.

**Comment by kinow** [comment]
Closing as this appears to have happened due to intermittent failures. Feel free to re-open if this is still happening.
