### ISSUE TITLE
autosumit stats -fp fails

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#158]
In GitLab by @obellprat on Jun 30, 2016, 17:34

Hi,

I tried to run the stats command by specifying the period (hours before current time) for which the statistics should be carried out and I get the following python error 

autosubmit stats a045 -fp 24

Loading jobs...
[CRITICAL] Unhandled exception on Autosubmit: String '2016-05-04 10:51:50' can not be converted to date
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 296, in parse_args
    return Autosubmit.statistics(args.expid, args.filter_type, args.filter_period, args.output, args.hide)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 849, in statistics
    jobs = [job for job in jobs if job.check_started_after(period_ini) or job.check_running_after(period_ini)]
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/job/job.py", line 733, in check_started_after
    if any(parse_date(str(date_retrial)) > date_limit for date_retrial in self.check_retrials_start_time()):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/job/job.py", line 733, in <genexpr>
    if any(parse_date(str(date_retrial)) > date_limit for date_retrial in self.check_retrials_start_time()):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/date/chunk_date_lib.py", line 303, in parse_date
    raise ValueError("String '{0}' can not be converted to date".format(string_date))
ValueError: String '2016-05-04 10:51:50' can not be converted to date

@dmanubens @ jlope2

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jul 1, 2016, 14:56

This problem will be solved on the next release.

However, it seems that there is a related issue: trying to parse the date 'COMPLETE'.

Maybe an inconsistency with the STAT files? (Pending to review)

Thanks for your reports @obellprat !!
