### ISSUE TITLE
Missing header on proj.conf

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#160]
In GitLab by @dmanubens on Jul 5, 2016, 16:06

```
[CRITICAL] Unhandled exception on Autosubmit: File contains no section headers.
file: /wkdir/globc/eric/evian/autosubmit/a001/conf/proj_a001.conf, line: 26
'NPROC_ARP_NS=11\n'
Traceback (most recent call last):
  File "/usr/local/anaconda2/lib/python2.7/site-packages/autosubmit/autosubmit.py", line 302, in parse_args
    return Autosubmit.check(args.expid)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/autosubmit/autosubmit.py", line 1023, in check
    if not as_conf.check_conf_files():
  File "/usr/local/anaconda2/lib/python2.7/site-packages/autosubmit/config/config_common.py", line 173, in check_conf_files
    self.reload()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/autosubmit/config/config_common.py", line 376, in reload
    self._proj_parser = AutosubmitConfig.get_parser(self.parser_factory, self._proj_parser_file)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/autosubmit/config/config_common.py", line 801, in get_parser
    parser.read(file_path)
  File "/usr/local/anaconda2/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/local/anaconda2/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: /wkdir/globc/eric/evian/autosubmit/a001/conf/proj_a001.conf, line: 26
'NPROC_ARP_NS=11\n'

```

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jul 5, 2016, 17:15

This is only happening when no [HEADER] in the original .conf file.
A possible solution would be to add one [DEFAULT] when copying

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jul 12, 2016, 12:42

From now, it will append at the beginning of the file the header '[DEFAULT]' if the file does not begin with a section header.

Regarding @dmanubens suggestion, I haven't added this behaviour on the copy process in order to avoid manually errors if the user modifies this file.

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jul 12, 2016, 13:19

mentioned in commit 7a57173c62e8221c048008c07a0c50dfb107cd7f
