### ISSUE TITLE
HPCARCH in expdef.conf in capitals does not work

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#161]
In GitLab by @dmanubens on Jul 5, 2016, 17:32

```
dmanuben@ bscearth309:~/debug/autosubmit/a00i> head conf/expdef_a00i.conf 
[DEFAULT]
# Experiment identifier
# No need to change
EXPID = a00i
# HPC name.
# No need to change
HPCARCH = MN

[experiment]
# Supply the list of start dates. Available formats: YYYYMMDD YYYYMMDDhh YYYYMMDDhhmm
dmanuben@ bscearth309:~/debug/autosubmit/a00i> head conf/platforms_a00i.conf 
[MN]
# Queue type. Options: ps, SGE, LSF, SLURM, PBS, eceaccess
TYPE = lsf
HOST = mn
PROJECT = bsc32
ADD_PROJECT_TO_HOST = true
USER = bsc32704
SCRATCH_DIR = /gpfs/scratch
TEST_SUITE = True

dmanuben@ bscearth309:~/debug/autosubmit/a00i> autosubmit check a00i

Checking configuration files...
autosubmit_a00i.conf OK
platforms_a00i.conf OK
jobs_a00i.conf OK
expdef_a00i.conf  OK
Configuration files OK

[CRITICAL] Unhandled exception on Autosubmit: 'MN'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 302, in parse_args
    return Autosubmit.check(args.expid)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 1051, in check
    job.set_platform(submitter.platforms[job.platform_name])
KeyError: 'MN'
```
Whereas this works well:
```
dmanuben@ bscearth309:~/debug/autosubmit/a00i> head conf/expdef_a00i.conf 
[DEFAULT]
# Experiment identifier
# No need to change
EXPID = a00i
# HPC name.
# No need to change
HPCARCH = mn

[experiment]
# Supply the list of start dates. Available formats: YYYYMMDD YYYYMMDDhh YYYYMMDDhhmm
dmanuben@ bscearth309:~/debug/autosubmit/a00i> head conf/platforms_a00i.conf 
[MN]
# Queue type. Options: ps, SGE, LSF, SLURM, PBS, eceaccess
TYPE = lsf
HOST = mn
PROJECT = bsc32
ADD_PROJECT_TO_HOST = true
USER = bsc32704
SCRATCH_DIR = /gpfs/scratch
TEST_SUITE = True
dmanuben@ bscearth309:~/debug/autosubmit/a00i> autosubmit check a00i

Checking configuration files...
autosubmit_a00i.conf OK
platforms_a00i.conf OK
jobs_a00i.conf OK
expdef_a00i.conf  OK
Configuration files OK

Checking scripts...
Template SIM will not be checked
Scripts OK

```

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jul 8, 2016, 15:09

@dmanubens I'm not able to reproduce this error. 

Did you had this problem with the most recent version?

Thanks!

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jul 11, 2016, 14:36

Sorry @dmanubens, I didn't see that the problem was with the command 'check', I only was trying to create & run an experiment.

I've applied the same solution as for other commands (everything is treated as lowercase).
