### ISSUE TITLE
austosubmit 3.7 setstatus

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#175]
In GitLab by @Eleftheriaexarchou on Aug 10, 2016, 15:56

Hi @ jlope2 @dmanubens  

Testing autosubmit 3.7 with experiment a04e I get:        

```
eexarcho@ bscearth304:/esnas/autosubmit/a04e/conf$  autosubmit setstatus a04e   -fs WAITING   --status_final SUSPENDED -s      
Preparing .lock file to avoid multiple instances with same expid.    
       
Checking configuration files...        
autosubmit_a04e.conf OK        
platforms_a04e.conf OK      
jobs_a04e.conf OK       
expdef_a04e.conf  OK     
Configuration files OK     
    
Creating jobs...      
Loading JobList         
[CRITICAL] Unhandled exception on Autosubmit: iteration over non-sequence        
Traceback (most recent call last):      
  File "/shared/earth/software/autosubmit/3.7.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.0-py2.7.egg/autosubmit/autosubmit.py", line 342, in parse_args       
    args.filter_chunks, args.filter_status, args.filter_type, args.hide)       
  File "/shared/earth/software/autosubmit/3.7.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.0-py2.7.egg/autosubmit/autosubmit.py", line 1826, in set_status       
    job_list = Autosubmit.load_job_list(expid, as_conf)        
  File "/shared/earth/software/autosubmit/3.7.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.0-py2.7.egg/autosubmit/autosubmit.py", line 2197, in load_job_list     
    date_format, as_conf.get_retrials(), as_conf.get_default_job_type(), False)     
  File "/shared/earth/software/autosubmit/3.7.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.0-py2.7.egg/autosubmit/job/job_list.py", line 112, in generate      
    jobs_data = {str(row[0]): row for row in self.load()}        
TypeError: iteration over non-sequence       
     ```        
How I solve it? This command worked in the past

**Comment by kinow** [comment]
In GitLab by @dmanubens on Aug 10, 2016, 16:31

Hi Eleftheria, this has already been reported in #174. It will be solved in 3.7.1. You can use recovery instead. If you need the setstatus operation you can download develop branch and use it within a virtual environment.
```
module unload autosubmit; module unload Python; mkdir -p ~/venvs/as_370/; virtualenv ~/venvs/as_370 ; source ~/venvs/as_370/bin/activate ; pip install https://earth.bsc.es/gitlab/es/autosubmit/repository/archive.zip?ref=develop
```

**Comment by kinow** [comment]
In GitLab by @dmanubens on Aug 10, 2016, 16:32

If you have already created the virtual environment just: `source ~/venvs/as_370/bin/activate`

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on Aug 10, 2016, 19:24


Installing it in the virtual env did not work: 

```       
distutils.errors.LinkError: Command "gcc -pthread /scratch/Earth/eexarcho/tmp/tmp595HsJ/scratch/Earth/eexarcho/tmp/tmp595HsJ/source.o -L/usr/lib64 -lblas -o /scratch/Earth/eexarcho/tmp/tmp595HsJ/a.out" failed with exit status 1

----------------------------------------
Cleaning up...
Command /home/Earth/eexarcho/venvs/as_370/bin/python -c "import setuptools, tokenize;__file__='/home/Earth/eexarcho/venvs/as_370/build/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /scratch/Earth/eexarcho/tmp/pip-trCXxO-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/Earth/eexarcho/venvs/as_370/include/site/python2.7 failed with error code 1 in /home/Earth/eexarcho/venvs/as_370/build/numpy
Storing debug log for failure in /home/Earth/eexarcho/.pip/pip.log             
             
              
(as_370)eexarcho@ bscearth304:/esnas/autosubmit/a04e/conf$ autosubmit 
Traceback (most recent call last):
  File "/shared/earth/software/bin/autosubmit", line 29, in <module>
    from autosubmit.autosubmit import Autosubmit
ImportError: No module named autosubmit.autosubmit
```

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on Aug 10, 2016, 19:47

@dmanubens  if it takes time to solve this issue I cannot afford it: I need to make sure this exp is running tomorrow before @ cprodhomme leaves, since its her exp. I reverted back to v3.6 and I get 
      
```
 eexarcho@ bscearth304:/esnas/autosubmit/a04e/conf$ autosubmit run a04e 
Preparing .lock file to avoid multiple instances with same expid.


Checking configuration files...
autosubmit_a04e.conf OK
platforms_a04e.conf OK
jobs_a04e.conf OK
expdef_a04e.conf  OK
Configuration files OK

Starting job submission...
Checking scripts...
[WARNING] The following set of variables to be substituted in template script is not part of parameters set: set(['d_', 'Y_'])
[WARNING] Invalid parameter substitution in LOCAL_SETUP template!!!
[WARNING] The following set of variables to be substituted in template script is not part of parameters set: set(['d_', 'Y_'])
[WARNING] Invalid parameter substitution in REMOTE_SETUP template!!!
[WARNING] The following set of variables to be substituted in template script is not part of parameters set: set(['d_', 'Y_'])
[WARNING] Invalid parameter substitution in INI template!!!
[WARNING] The following set of variables to be substituted in template script is not part of parameters set: set(['d_', 'Y_'])
[WARNING] Invalid parameter substitution in SIM template!!!
[WARNING] The following set of variables to be substituted in template script is not part of parameters set: set(['d_', 'Y_'])
[WARNING] Invalid parameter substitution in POST template!!!
[WARNING] The following set of variables to be substituted in template script is not part of parameters set: set(['d_', 'Y_'])
[WARNING] Invalid parameter substitution in CLEAN template!!!
[WARNING] The following set of variables to be substituted in template script is not part of parameters set: set(['d_', 'Y_'])
[WARNING] Invalid parameter substitution in TRANSFER template!!!
[ERROR] Scripts check failed
Running after failed scripts check is at your own risk!


452 of 452 jobs remaining (19:46)

Jobs ready for local: 1
Jobs to submit: 1
[CRITICAL] Unhandled exception on Autosubmit: [Errno 1] Operation not permitted: '/esnas/autosubmit/a04e/tmp/a04e_LOCAL_SETUP.cmd'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 287, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 630, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, joblist, platforms_to_test):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 681, in submit_ready_jobs
    scriptname = job.create_script(as_conf)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/job/job.py", line 639, in create_script
    os.chmod(os.path.join(self._tmp_path, scriptname), 0o775)
OSError: [Errno 1] Operation not permitted: '/esnas/autosubmit/a04e/tmp/a04e_LOCAL_SETUP.cmd'

eexarcho@ bscearth304:/esnas/autosubmit/a04e/conf$ 
   
```      
         
even if running local setup mannualy works fine :      
```     
eexarcho@ bscearth304:/esnas/autosubmit/a04e/conf$ /esnas/autosubmit/a04e/tmp/a04e_LOCAL_SETUP.cmd
#
# Architecture
#
STAMP=$(date +%Y_%m_%d_%H_%M)
date +%Y_%m_%d_%H_%M)
date +%Y_%m_%d_%H_%M
++ date +%Y_%m_%d_%H_%M
+ STAMP=2016_08_10_19_47
HPCARCH=marenostrum3
+ HPCARCH=marenostrum3
HPCPROJ=bsc32
+ HPCPROJ=bsc32
HPCUSER=bsc32525
+ HPCUSER=bsc32525
EXPID=a04e
+ EXPID=a04e
SCRATCH_DIR=/gpfs/scratch
+ SCRATCH_DIR=/gpfs/scratch
JOBNAME=a04e_LOCAL_SETUP
+ JOBNAME=a04e_LOCAL_SETUP
ROOTDIR=/esnas/autosubmit/a04e
+ ROOTDIR=/esnas/autosubmit/a04e
LOGDIR=$ROOTDIR/tmp/LOG_$EXPID
+ LOGDIR=/esnas/autosubmit/a04e/tmp/LOG_a04e
PROJDEST=model
+ PROJDEST=model
PROJDIR=/esnas/autosubmit/a04e/proj/model
+ PROJDIR=/esnas/autosubmit/a04e/proj/model

#
# General Paths and Conf.
#
MODEL=ecearth
+ MODEL=ecearth
VERSION=v3.1
+ VERSION=v3.1
OUTCLASS=specs
```
