### ISSUE TITLE
problems with .lock file remaining after normal autosubmit termination

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#179]
In GitLab by @etiennesky on Aug 17, 2016, 15:38

When creating a new experiment and something goes wrong (either a problem with downloading from the git repository or missing conf file in this case), the lock file remains and even though there is no autosubmit process running.

Here is what happened in my case:

```
etourign@ bscearth346:/esnas/autosubmit/a09s> autosubmit create a09s
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
autosubmit_a09s.conf OK
platforms_a09s.conf OK
[WARNING] No remote platforms configured
jobs_a09s.conf OK
expdef_a09s.conf  OK
Configuration files OK

Cloning v3.2.0c https://earth.bsc.es/gitlab/es/auto-ecearth3.git into /esnas/autosubmit/a09s/proj
Cloning into 'auto-ecearth3'...
ksshaskpass(25785)/kdeui (Wallet): The kwalletd service has been disabled 

[...]

Cloning into 'specs2cmor'...
remote: Counting objects: 3361, done.
remote: Compressing objects: 100% (1169/1169), done.
remote: Total 3361 (delta 2461), reused 2787 (delta 2120)
Receiving objects: 100% (3361/3361), 67.92 MiB | 14.02 MiB/s, done.
Resolving deltas: 100% (2461/2461), done.
Checking connectivity... done.
[CRITICAL] Unhandled exception on Autosubmit: [Errno 2] No such file or directory: '/esnas/autosubmit/a09s/proj/auto-ecearth3/templates/common/jobs.conf'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 304, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 1468, in create
    Autosubmit._create_project_associated_conf(as_conf, False, update_job)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 1420, in _create_project_associated_conf
    jobs_destiny)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/esnas/autosubmit/a09s/proj/auto-ecearth3/templates/common/jobs.conf'
```

[fix the issue]

```
etourign@ bscearth346:/esnas/autosubmit/a09s> autosubmit create a09s
[CRITICAL] Unhandled exception on Autosubmit: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 304, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 1452, in create
    with portalocker.Lock(os.path.join(tmp_path, 'autosubmit.lock'), timeout=1):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/portalocker-0.5.7-py2.7.egg/portalocker/utils.py", line 188, in __enter__
    self.fh = self.acquire()
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/portalocker-0.5.7-py2.7.egg/portalocker/utils.py", line 139, in acquire
    raise AlreadyLocked(exception)
AlreadyLocked: [Errno 11] Resource temporarily unavailable
```

If I delete tmp/autosubmit.lock then I can continue

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Aug 18, 2016, 15:15

Hi @etiennesky,

I'm sorry but I can't reproduce your problem.

I've tried to configure a wrong branch, then autosubmit has finished with an error message (cannot clone).
But the lock system has worked right, I could run the autosubmit create command again.

Is this your casuistic?

Can you reproduce your problem?

Thanks!

**Comment by kinow** [comment]
In GitLab by @etiennesky on Aug 18, 2016, 15:25

Hi @ jlope2 

I cannot say this happens every time, I will update this ticket the next time it happens!

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Aug 18, 2016, 15:36

It's rare that the same error produces different situations.
But, of course, any execution can finish with this kind of errors.

Theoretically, as you can check, the errors produced by a wrong configuration are handled and shouldn't produce errors with the lock system.

Anyway, we can remain this issue open and if it appears again, you can share with us more information.

Finally, as I said, and only to clarify, we cannot contemplate the strange situations produced in extreme cases.

Many thanks for you help!

**Comment by kinow** [comment]
In GitLab by @ rfernand on Aug 24, 2016, 17:24

Hello, we had the same issue with @ rfernand 

1) autosubmit create a0a1
2) git pull exited because of lack of permissions on ecearth-mirror.git/
3) @ macosta fixed the permissions
4) autosubmit create a0a1
5) -> autosubmit is locked!!!!

we did everything in the same terminal, so this is the same bug as @etiennesky reported (the second case)

```
Cloning into 'sources'...
remote: Not Found
fatal: repository 'https://earth.bsc.es/gitlab/svn/ecearth-mirror.git/' not found
Clone of 'https://earth.bsc.es/gitlab/svn/ecearth-mirror.git' into submodule path 'sources' failed
[ERROR] Can not clone 3.2.0c_develop https://earth.bsc.es/gitlab/es/auto-ecearth3.git into /esnas/autosubmit/a0a1/proj
rfernand@ bscearth335:/esnas/autosubmit/a0a1/conf> autosubmit create a0a1
[CRITICAL] Unhandled exception on Autosubmit: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 304, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 1452, in create
    with portalocker.Lock(os.path.join(tmp_path, 'autosubmit.lock'), timeout=1):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/portalocker-0.5.7-py2.7.egg/portalocker/utils.py", line 188, in __enter__
    self.fh = self.acquire()
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/portalocker-0.5.7-py2.7.egg/portalocker/utils.py", line 139, in acquire
    raise AlreadyLocked(exception)
AlreadyLocked: [Errno 11] Resource temporarily unavailable

rfernand@ bscearth335:/esnas/autosubmit/a0a1/conf> ps
  PID TTY          TIME CMD
 1641 pts/1    00:00:00 ps
13213 pts/1    00:00:00 bash
32453 pts/1    00:00:00 git-credential-

```

**Comment by kinow** [comment]
In GitLab by @ rfernand on Aug 24, 2016, 17:25

after removing the lock file, we were able to create the experiment.

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Aug 26, 2016, 08:32

Thanks @ rfernand!

We will review it. But it's very rare that the same casuistic produces sometimes a behaviour and sometimes another.

BTW, I'm not sure if 'autosubmit' appears with a simple ```ps``` command. Can you try: ```ps -u | grep autosubmit``` next time?

Thanks a lot :)

**Comment by kinow** [comment]
In GitLab by @etiennesky on Aug 26, 2016, 10:55

Hello. Yes it does seem like an intermittent problem. 

We will try your suggestion next time this problem shows up!

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Aug 26, 2016, 11:17

Thanks a lot @etiennesky :)

**Comment by kinow** [comment]
In GitLab by @fmassonn on Oct 4, 2016, 11:04

I had a similar problem. My `/esnas/autosubmit/a09p/tmp` folder was missing because I had deleted it since I wanted to re-create the whole experiment. Then I had a message like:

```
fmassonn@ bscearth321: ~ >> autosubmit create a09p            
[CRITICAL] Unhandled exception on Autosubmit: [Errno 2] No such file or directory: '/esnas/autosubmit/a09p/tmp/autosubmit.lock'
```

I fixed this by simply creating an empty folder `tmp`.

Maybe Autosubmit should create `tmp` if it does not exist, at the start of the `create` command.

François

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Oct 4, 2016, 11:15

Hi @fmassonn,

I'm agree with you. 
Maybe Autosubmit could create this folder at the beginning of the ```create``` command.

But this folder should be created on the ```expid``` command.
So, if it does not exists, it could mean that something was wrong with the ```expid```.

What do you think?

Thanks!

**Comment by kinow** [comment]
In GitLab by @fmassonn on Oct 4, 2016, 11:26

Hi,

I think `expid`creates it any way. The problem is that if the user deletes the `tmp` folder after that. In my case, I had created the experiment long time ago, then wanted to re-create it. I first deleted `proj` and `tmp` because I wanted to start from scratch, then autosubmit complained about not finding tmp. 

So I would just make sure, at the beginning of `create`, that `tmp` exists and if not, create it.

Thanks!

François

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Oct 4, 2016, 11:27

Okay!

Thanks for your feedback, @fmassonn.

It will be available soon.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Nov 9, 2016, 11:30

Hi, using latest autosubmit version I experienced this again while doing everything in the same terminal on the bscesautosubmit01 host...

I first ran autosubmit create which failed because of an error in the config file. I fixed this then ran create again, had a look at the pdf. I changed the jobs_a0ch.conf file then ran create again, autosubmit complained about missing lock file. I checked and there are no autosubmit processes running under my username.

```
etourign@ bscesautosubmit01:~> autosubmit create a0ch
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
autosubmit_a0ch.conf OK
[ERROR] Option USER in section marenostrum3 not found
[CRITICAL] platforms_a0ch.conf is not a valid config file
[ERROR] Configuration files invalid

[CRITICAL] Can not create with invalid configuration
etourign@ bscesautosubmit01:~> autosubmit create a0ch
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
autosubmit_a0ch.conf OK
platforms_a0ch.conf OK
jobs_a0ch.conf OK
expdef_a0ch.conf  OK
Configuration files OK

Cloning v3.2.0d https://earth.bsc.es/gitlab/es/auto-ecearth3.git into /esnas/autosubmit/a0ch/proj
Cloning into 'auto-ecearth3'...
Username for 'https://earth.bsc.es': etourign
Password for 'https://etourign@ earth.bsc.es': 
remote: Counting objects: 4931, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 4931 (delta 1), reused 0 (delta 0)
Receiving objects: 100% (4931/4931), 776.57 KiB | 110.00 KiB/s, done.
Resolving deltas: 100% (3216/3216), done.
Checking connectivity... done.
Note: checking out '0b7043098387007f97adac8bcb9e5f9cde55061f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Checking out files: 100% (242/242), done.
Cloning into 'plugins'...
remote: Counting objects: 15500, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 15500 (delta 7), reused 0 (delta 0)
Receiving objects: 100% (15500/15500), 22.60 MiB | 1.49 MiB/s, done.
Resolving deltas: 100% (5164/5164), done.
Checking connectivity... done.
Cloning into 's2dverification'...
remote: Counting objects: 9205, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 9205 (delta 9), reused 0 (delta 0)
Receiving objects: 100% (9205/9205), 62.45 MiB | 7.75 MiB/s, done.
Resolving deltas: 100% (6278/6278), done.
Checking connectivity... done.
Cloning into 'sources'...
remote: Counting objects: 63316, done.
remote: Total 63316 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (63316/63316), 182.07 MiB | 3.34 MiB/s, done.
Resolving deltas: 100% (35267/35267), done.
Checking connectivity... done.
Cloning into 'specs2cmor'...
remote: Counting objects: 3561, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 3561 (delta 7), reused 0 (delta 0)
Receiving objects: 100% (3561/3561), 67.96 MiB | 7.36 MiB/s, done.
Resolving deltas: 100% (2556/2556), done.
Checking connectivity... done.
Loading parameters...

Creating joblist...
Creating jobs...
Adding dependencies...
Removing redundant dependencies...

Saving joblist...

Ploting joblist...
Plotting...
Plot created at /esnas/autosubmit/a0ch/plot/a0ch_20161109_1125.pdf
START /usr/bin/evince /esnas/autosubmit/a0ch/plot/a0ch_20161109_1125.pdf

Job list created succesfully
Remember to MODIFY the MODEL config files!
etourign@ bscesautosubmit01:~> autosubmit create a0ch
[WARNING] We have detected that there is another Autosubmit instance using the experiment a0ch.
[WARNING] We have stopped this execution in order to prevent incoherency errors.
[WARNING] Stop other Autosubmit instances that are using the experiment a0ch and try it again.
etourign@ bscesautosubmit01:~> ps auxf | grep auto
avahi      488  0.1  0.0  51200  2664 ?        Ss   Nov03  15:34 avahi-daemon: running [bscesautosubmit01.local]
root       518  0.0  0.0  29324    12 ?        SLs  Nov03   0:00 /usr/lib/wicked/bin/wickedd-auto4 --systemd --foreground
etourign 17541  0.0  0.0  10552  1580 pts/0    S+   11:27   0:00              \_ grep --color=auto auto
root      1179  0.0  0.0  44640     4 ?        Ssl  Nov03   0:00 /usr/sbin/automount  -p /var/run/automount.pid
fmassonn 13555  1.4  3.7 544736 152788 ?       Sl   Nov07  44:17 /shared/earth/software/Python/2.7.9-foss-2015a/bin/python /shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/bin/autosubmit run a0al
rfernand 26544  0.3  1.9 455976 80544 ?        Sl   Nov08   5:46 /shared/earth/software/Python/2.7.9-foss-2015a/bin/python /shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/bin/autosubmit run a091
etourign@ bscesautosubmit01:~> ps auxf | grep auto | grep etourign
etourign 17545  0.0  0.0  10552  1584 pts/0    S+   11:27   0:00              \_ grep --color=auto auto
etourign 17546  0.0  0.0  10552  1552 pts/0    S+   11:27   0:00              \_ grep --color=auto etourign
```

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Nov 9, 2016, 11:48

Thanks @etiennesky!

We will explore it deeper.

Two weeks ago we contacted  the ```portalocker``` library developer. 

He improved the lock functionality so we are pending to test the new version of the library.

Maybe this will fix the issues. Will see!

**Comment by kinow** [comment]
In GitLab by @etiennesky on Jan 11, 2017, 12:57

Today I created a new experiment a0ea and I did a create, waited for code to download (no errors) and modified some files. 

When I did an autosubmit run, it failed because the lock file was still present. This time the problem appeared even though there were no errors.

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jan 11, 2017, 13:26

Thanks a lot for the info @etiennesky  :)

**Comment by kinow** [comment]
In GitLab by @etiennesky on Jan 12, 2017, 11:34

Hi again @ jlope2 the same thing happened today, using AS 3.7.7.

```
etourign@ bscesautosubmit01:/esnas/autosubmit/a0ea/proj/auto-ecearth3/templates> autosubmit expid -H marenostrum3 -y t00o -d "3.2.1 development - LR"
The new experiment "a0ed" has been registered.
Copying previous experiment config directories
Experiment registered successfully
Remember to MODIFY the config files!
etourign@ bscesautosubmit01:/esnas/autosubmit/a0ea/proj/auto-ecearth3/templates> autosubmit create a0ed
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
autosubmit_a0ed.conf OK
platforms_a0ed.conf OK
jobs_a0ed.conf OK
expdef_a0ed.conf  OK
Configuration files OK

Cloning 3.2.1a_develop https://earth.bsc.es/gitlab/es/auto-ecearth3.git into /esnas/autosubmit/a0ed/proj
Cloning into 'auto-ecearth3'...
Username for 'https://earth.bsc.es': etourign 
Password for 'https://etourign@ earth.bsc.es': 
remote: Counting objects: 4988, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 4988 (delta 1), reused 0 (delta 0)
Receiving objects: 100% (4988/4988), 797.23 KiB | 660.00 KiB/s, done.
Resolving deltas: 100% (3252/3252), done.
Checking connectivity... done.
Cloning into 'plugins'...
remote: Counting objects: 15506, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 15506 (delta 8), reused 0 (delta 0)
Receiving objects: 100% (15506/15506), 22.61 MiB | 1.85 MiB/s, done.
Resolving deltas: 100% (5165/5165), done.
Checking connectivity... done.
Cloning into 's2dverification'...
remote: Counting objects: 9383, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 9383 (delta 7), reused 0 (delta 0)
Receiving objects: 100% (9383/9383), 62.50 MiB | 12.45 MiB/s, done.
Resolving deltas: 100% (6426/6426), done.
Checking connectivity... done.
Cloning into 'sources'...
remote: Counting objects: 65112, done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 65112 (delta 10), reused 0 (delta 0)
Receiving objects: 100% (65112/65112), 183.13 MiB | 4.16 MiB/s, done.
Resolving deltas: 100% (36636/36636), done.
Checking connectivity... done.
Cloning into 'specs2cmor'...
remote: Counting objects: 3567, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 3567 (delta 10), reused 0 (delta 0)
Receiving objects: 100% (3567/3567), 67.96 MiB | 8.64 MiB/s, done.
Resolving deltas: 100% (2559/2559), done.
Checking connectivity... done.
Loading parameters...

Creating joblist...
Creating jobs...
Adding dependencies...
Removing redundant dependencies...

Saving joblist...

Ploting joblist...
Plotting...
Plot created at /esnas/autosubmit/a0ed/plot/a0ed_20170112_1132.pdf
START /usr/bin/evince /esnas/autosubmit/a0ed/plot/a0ed_20170112_1132.pdf

Job list created succesfully
Remember to MODIFY the MODEL config files!
etourign@ bscesautosubmit01:/esnas/autosubmit/a0ea/proj/auto-ecearth3/templates> autosubmit run a0ed
[WARNING] We have detected that there is another Autosubmit instance using the experiment a0ed.
[WARNING] We have stopped this execution in order to prevent incoherency errors.
[WARNING] Stop other Autosubmit instances that are using the experiment a0ed and try it again.
```

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jan 12, 2017, 12:39

Probably it's an stupid idea but:

- It's possible that this error appears more often when working remotely (in ```bscesautosubmit01```)?

Do you do the ```autosubmit create``` usually from this machine?

Thanks!

PS: I'm not saying that there are no problems, but it could be great if we detect a way of work to avoid this kind of problems till we solve it.

**Comment by kinow** [comment]
In GitLab by @fmassonn on Jan 12, 2017, 12:48

Hi,

My experience indeed is to do everything from `bscesautosubmit01`, otherwise you cannot guarantee that such problems don't arise.

François

**Comment by kinow** [comment]
In GitLab by @etiennesky on Jan 12, 2017, 13:39

I am not sure which machine I used last time, but since the recommendation is to use bscesautosubmit01 (and not our local machine), I am now always using it.

BTW why would there be a difference because of the machine used? /esnas is on the network anyway.

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jan 12, 2017, 13:43

I usually do `autosubmit create` on my local machine and I found the lock problem several times. I wouldn't blame the server.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 19, 2017, 15:11

mentioned in issue auto-ecearth3#266

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 13:28

closed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 13:28

Due this being an intermittent issue over the years and I was unable to reproduce it, could someone tell me if this is still happening in lastest version? I will keep this open with the new outdated label that I will being using in multiple old issues to ask for  updated information since I joined to bsc recently and @dmanubens is not in bsc anymore.

Thanks to all.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Dec 4, 2018, 13:40

It happened to me last week.  I think it happens when creating an experiment on autosubmit02, it if fine if using a local workstation.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Dec 4, 2018, 13:40

reopened

**Comment by kinow** [comment]
In GitLab by @ mariag on Feb 14, 2019, 10:01

Hi, 
I just happen to have the same error (your discussion was very useful as I didn't know that the origin was related to the autosubmit.lock file).
I was creating and running the experiment from bscesautosubmit01

**Comment by kinow** [comment]
In GitLab by @etiennesky on Feb 14, 2019, 18:47

I am having the same problem with the dev version on bscesautosubmit02, after running 'autosubmit inspect expid' the lock file remains even if the inspect job ran successfully.

Oh inspect works fine BTW, thanks!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 15, 2019, 09:24

Hi,

This issue was still in the backlog so I did nothing to solve it in the last testing release. I will try to fix it for a future version.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Feb 15, 2019, 11:55

Hi @dbeltrankyl, sorry my mistake, I thought that the new "inspect" feature triggered the bug every time, but I was wrong. I think it happened because I killed AS with ctrl-c.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 15, 2019, 13:02

Hi, 

The only commands that generates .lock file are:

*  create
*  setstatus
*  run

I think that the .lock file only fails to be erased when you perform control+C (or a shutdown in the node in which AS is running)  in any of these commands, However, the autosubmit run has a mechanism to always erase the .lock when it is stopped even with control + c .

I just noticed that this was also causing problems with the mail_notifier issue that sometimes, did not work. So, with the changes I made, maybe the .lock is now being erased more frequently. Do you know in which command did you control + c?  

I think this issue is a bit tricky together with the mail issue, because depending on the moment that the autosubmit run crash, it couldn't be handled. 

SideNote: the inspect command  looks if there is a .lock file but does not generate one.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Mar 20, 2019, 11:45

Hi @dbeltrankyl this problem happens to me every time I create and experiment from bscesautosubmit02 and bscearth346, using AS autosubmit/3.11.0-hotfix.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Jul 29, 2019, 13:13

Hi @mcastril @dbeltrankyl 

After taking a look at this issue, and seeing that it's still happening and confusing our users. I think the best way to handle it is to prevent the user from killing Autosubmit by pressing CTRL+C. For that purpose, I will be testing the following approach:

* Handle KeyboardInterrupt exception in the main autosubmit loop (that is run_experiment())
* When CTRL-C is pressed, the exception code will set the signal (signal library) to handle the following impatient CTRL-C keystrokes. And then Autosubmit enters a loop. So, whenever the user insists in killing Autosubmit, a message will be shown, something like: "Autosubmit is doing some cleanup before exiting. Please wait.". (Entering the loop after KeyboardInterrupt is captured has been already proven to work, the user would need faster than light key stroking capabilities to prevent this.)
* While in the loop autosubmit will perform all the necessary cleanup. For the first iteration of this feature, that will be: releasing the lock.

That should do the trick. I will be working on this the following days.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 29, 2019, 13:15

mentioned in issue auto-monarch#239

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 29, 2019, 13:22

Hi @wuruchi,

Thanks for looking it,  

Seems a good approach, about the cleanup, keep in mind what we discussed in the last meeting, we should handle the running/queued jobs in the remote platforms.

*  Running job -> cancel in remote (within autosubmit) and set into failed status.

*  Queued job -> cancel in remote (within autosubmit)  and set into ready or waiting status.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Jul 29, 2019, 13:59

I think we are not on the same page.

This issue is about autosubmit not removing the .lock file after running "autosubmit create", The issue about the .lock file remaining when the user kills autosubmit with ctrl-c  is something entirely different, and only happened a few times using a dev version.

Also, please do NOT kill remote jobs when stopping autosubmit, many times I stop autosubmit because I don't want further jobs to be submitted, but I want the last job submitted (e.g. SIM) to keep on going.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 29, 2019, 14:36

Hi @etiennesky , 

You're right, we discussed general issues with lock and I guess this was the last one active,

About the last part, I get your point and maybe we must not change the behavior of control + c in order to not disturb users like you that uses it in that particular way. 

However, I mention it due I think that it should be the "normal" way to interrupt autosubmit , since in my mind I see logical that if a task is finished it shouldn't let tasks ongoing since it won't be anymore controlled by the tool and thus that job  will be in unknown status although autosubmit is able to recover it if it runs again. 

For the case you mentioned, is that why Autosubmit allows setting jobs to suspended status although I can see that it isn't used by being tedious ( a GUI could help there).

Last comment, the case that made me think about this is, to stop the experiment due you may find a bug in jobs script and you know that they will fail and is wasting resources into the platform for everybody and maybe the user is unaware.  

Anyway, for now, I prefer not to change to not disturb the normal use of autosubmit.

@wuruchi could you see in addition to the lock's improvement,  why create is not erasing .lock and fix it? (maybe it's due the `return True` inside the `with clausure` that I saw in a quick look of the code ) about the status then, let them unchanged.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Jul 29, 2019, 15:05

perfect @dbeltrankyl thanks! Perhaps when you implement the change in cleanup remote jobs, make this the new default, but add a variable in autosubmit.conf to use previous behaviour.  This would be fine for me.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Jul 29, 2019, 15:12

@dbeltrankyl Now that you mention it. Let me point that the current implementation of autosubmit does not handle signals (KeyInterrupt) in the create() procedure. So, it is expected that if create is cancelled with CTRL-C, any lock will not be released. Currently, signal handling is only implemented in inspect() and run_experiment(), being the latter the more important.

Anyway, I guess I should focus my work on a first branch implementing signal handling in create() to fix the majority of the current problems of our users, and then we focus on another branch that deals with jobs after Autosubmit is closed while executing run_experiment().

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 29, 2019, 15:19

> but add a variable in autosubmit.conf to use previous behaviour

Good idea, in any case, I rather prefer to @mcastril finish it vacations to discuss it. 

>  Let me point that the current implementation of autosubmit does not handle signals (KeyInterrupt) in the create() procedure

the point is that it is not erasing the file even if the create finish without interruptions, also `create` is working even if an autosubmit.lock is found, atleast in 3.12.1

**Comment by kinow** [comment]
In GitLab by @wuruchi on Jul 29, 2019, 15:32

@dbeltrankyl Ok, I will focus on the create() procedure, and we discuss about other features when @mcastril returns.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Jul 29, 2019, 15:43

Hi @dbeltrankyl another reason to not kill the running jobs is if you want to change something in proj.conf or expdef.conf which has an impact on future jobs, not the currently running ones. 

It would be hard for the user to do this with the new change, because the user would have to manually set the killed jobs to READY and re-run AS again.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Aug 1, 2019, 11:45

mentioned in commit e430edf7580c5461535c57ae6774fe712ab9eccb

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 9, 2019, 13:00

Hi,

I agree with @dbeltrankyl about the "normal" Autosubmit usage: when you kill the tool you should expect the experiment to stop. On the other hand @etiennesky is right about the "real" usage: sometimes you temporally exit from Autosubmit to do changes. On the other hand this is what we do because we know Autosubmit doesn't kill remote jobs, if not we would just open another window to do changes or use the SUSPEND feature.

Maybe a compromise solution is to create a prompt on exit asking the user if he/she wants remote jobs to be cancelled... Is this possible? Could it lead to any problem?

> (Entering the loop after KeyboardInterrupt is captured has been already proven to work, the user would need faster than light key stroking capabilities to prevent this.) 

@wuruchi , do you think it will work if Ctrl+C is pressed for some seconds? Maybe we cannot handle all circumstances but it would be good to know.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 9, 2019, 13:10

> Maybe a compromise solution is to create a prompt on exit asking the user if he/she wants remote jobs to be cancelled... Is this possible? Could it lead to any problem?

I think that it is possible, what should be the default value if the user presses an empty answer? the actual one? This question will be prompted just after a user press control+c so it shouldn't be any problems

**Comment by kinow** [comment]
In GitLab by @wuruchi on Aug 9, 2019, 13:13

Hi @mcastril 

We can keep the user in a loop after CTRL-C has been pressed, so the user wouldn't be able to close the program until the prompt you suggest has been answered. 

The behavior would be the following:
* User presses CTRL-C and Autosubmit enters a loop.
* User is presented with a prompt asking if remote jobs should be canceled.
* No matter how many times the user presses CTRL-C, the prompt keeps appearing.
* Only after the prompt has been answered, and the necessary actions have been executed, the flag inside Autosubmit is set so the program exits the loop.
* Program halts.

Development of this approach can start as soon as esarchive is back online.

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 9, 2019, 13:35

Thank you. I think the jobs should only be cancelled if user types "Y", "y" or "yes". "N", "n" or "no" would close the application and any other combination would print again the prompt as @wuruchi put in the workflow.

My concern is about different use cases, as Autosubmit being run in the background (kill is not Ctrl+C so I guess the prompt would not appear) or running in Jenkins.

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 13, 2019, 12:31

Ctrl+C should only work when Autosubmit is working in the foreground. Therefore it should not interfere with Jenkins or runnning it on the background. We will do some tests anyway.

@pablohe @gmontanepinto

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 3, 2019, 11:18

closed via merge request !140
