### ISSUE TITLE
Describe upgrade - [merged]

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1796]
In GitLab by @dbeltrankyl on Feb 6, 2023, 10:35

_Merges describe_upgrade -> master_

Since I'm usually working in a non-GUI environment, I think the current describe solution wasn't good enough at all to find a specific experiment

I've upgraded it to describe all experiments from a specific user or describe multiple experiments at once.

Also, I had to add a no-log option in the config checker as all 3.X experiments were giving too much noise.

The docs are pending, I'll commit them later today

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2023, 12:42

added 1 commit

<ul><li>df3aa84f - path to images not working properly ( also in master but not sure why)</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12192&start_sha=4719341d6ea58b3dcde7a01a3922f53fe5fff5c4)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2023, 12:46

added 1 commit

<ul><li>7c1e82fa - Revert &quot;path to images not working properly ( also in master but not sure why)&quot;</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12193&start_sha=df3aa84f59c14e2557cd019e1f618a45f03431cc)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2023, 12:49

added 1 commit

<ul><li>ca6b17a8 - reverted last commit and changed only what is affecting to describe itself</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12194&start_sha=7c1e82fadc478147e277a6006560359c2f981e07)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2023, 12:51

added 1 commit

<ul><li>e68a8ff6 - erased spaces from folders ( messing with fig links )</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12195&start_sha=ca6b17a8c70e0f9cc402000eac5ec6e1155a6c73)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2023, 12:56

added 1 commit

<ul><li>55d16c3b - Paramiko new version requires Pynalc 1.5</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12196&start_sha=e68a8ff67fd6d5ca6297fe68cffa275f5d16a8e9)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2023, 13:00

added 1 commit

<ul><li>a5f2dcab - Paramiko new version requires Pynalc 1.5</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12197&start_sha=55d16c3b428fef07e1977a174ab6edef07ea4e9c)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2023, 13:05

added 1 commit

<ul><li>ad4a006f - update python version in rst</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12198&start_sha=a5f2dcab465913dadddfc3f18ed28bb8c033e42c)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2023, 13:12

added 1 commit

<ul><li>6ed6521e - autoconfigparser was messing with pynacl</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12201&start_sha=ad4a006f88acc45d72c001a78c4ab8449c969d4a)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2023, 13:13

added 1 commit

<ul><li>3c277ed5 - autoconfigparser was messing with pynacl</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12202&start_sha=6ed6521ee9bb0b5b0f3d385ed61a76cdddd9b801)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2023, 13:22

added 1 commit

<ul><li>d1ee7cd4 - autoconfigparser version updated ( to fix pynalc</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12206&start_sha=3c277ed55d5f02a9de5d79f6e23a0b1b5ede838d)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2023, 13:49

added 1 commit

<ul><li>aeb49d38 - links working again</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12207&start_sha=d1ee7cd4eb92ef820c30a6a6d82d49b387c346fa)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 8, 2023, 10:38

Regarding the issue itself, I've changed the describe command to be useful, so now it is able to describe multiple experiments at once, by user or by a list


I had some issues with readthedocs not building the docs, and it was due to the Pynacl dependency inside autosubmitconfigparser. I fixed it on this one.

Also, there were issues with images when the folder had spaces, so I get rid of them ( spaces)

**Comment by kinow** [comment]
I think the `help` attribute needs to be updated.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 8, 2023, 11:26

Commented on [autosubmit/autosubmit.py line 393](https://github.com/BSC-ES/autosubmit/compare/0b8038ae581efd79a8cb0a47715c96b75c92c2af..aeb49d385b7bcc9f980ea6250c45ad9d5bc4b635#diff-fb87ba4e4225b357016f4298108bcf0dR393)



changed this line in [version 13 of the diff](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12269&start_sha=aeb49d385b7bcc9f980ea6250c45ad9d5bc4b635#6bde465286156a9da245a31e64df703a55c76323_393_392)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 8, 2023, 11:26

added 1 commit

<ul><li>07f1bc2c - args update</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12269&start_sha=aeb49d385b7bcc9f980ea6250c45ad9d5bc4b635)

**Comment by kinow** [comment]
Code looking good @dbeltrankyl !

Quick question. Is it supposed to work locally and remotely, or remotely only? I tried locally, but it failed with the following:

```bash
(pyflow) kinow@ranma:~/Development/python/workspace/autosubmit$ git log -n 1
commit 9058e352fd5da707f835ac8cc86dfa199b69d74c (HEAD -> describe_upgrade, upstream/describe_upgrade)
Author: dbeltran <daniel.beltran@ bsc.es>
Date:   Wed Feb 8 11:27:58 2023 +0100

    args update
(pyflow) kinow@ranma:~/Development/python/workspace/autosubmit$ autosubmit describe a000,a001
Autosubmit is running with 4.0.0b
[ERROR] Trace: [Errno 6] No such device or address
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 660, in parse_args
    return Autosubmit.describe(args.expid,args.user)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 3447, in describe
    get_from_user = os.getlogin()
OSError: [Errno 6] No such device or address
 [CRITICAL] None[Errno 6] No such device or address
Unhandled error: If you see this message, please report it in Autosubmit's GitLab project
```

But maybe that works in HPC via SSH?

I get the same error if I run that `os.getlogin()` in the Python terminal. I found [this SO](https://stackoverflow.com/a/4399639) that suggests the `pwd` module.

```bash
(pyflow) kinow@ranma:~/Development/python/workspace/autosubmit$ python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> 
>>> os.getlogin()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 6] No such device or address
>>> 
>>> 
>>> 
>>> import pwd
>>> pwd.getpwuid(os.getuid())[0]
'kinow'
>>> 
```

WDYT?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 8, 2023, 11:41

In fact, it is like that in the delete command, so I'll do as you say

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 8, 2023, 11:42

aborted the automatic merge because source branch was updated

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 8, 2023, 11:42

added 1 commit

<ul><li>cc9e2bd5 - changed getlogin for pwd</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12277&start_sha=9058e352fd5da707f835ac8cc86dfa199b69d74c)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 8, 2023, 11:47

added 1 commit

<ul><li>c2a0ad4a - strip &quot; &quot; if any</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12279&start_sha=cc9e2bd51d225702b0c23b0800c28f7ecac78db2)

**Comment by kinow** [comment]
Works for me after your change, @dbeltrankyl 

```bash
$ autosubmit describe a000,a002
Autosubmit is running with 4.0.0b
Describing a000
Owner: kinow
Created: 2023-02-08 09:53:44.432780
Model: Not Found
Branch: master
HPC: LOCAL
Description: test
Describing a002
Owner: kinow
Created: 2023-02-08 11:48:27.632107
Model: Not Found
Branch: master
HPC: LOCAL
Description: test

```

**Comment by kinow** [comment]
approved this merge request

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 8, 2023, 11:57

added 1 commit

<ul><li>8b29cac7 - Some of the docs related to describe were deleted not sure how</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/308/diffs?diff_id=12281&start_sha=c2a0ad4aa5a018f7c426878e7eb360dbbb57faed)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 8, 2023, 11:59

thanks for testing it!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 8, 2023, 11:59

enabled an automatic merge when the pipeline for 8b29cac7288bccfd98823b050b31423c331b2535 succeeds

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 8, 2023, 12:03

mentioned in commit 35f7e1f186f09bfc04c5ed262bdea49c9c09214f
