### ISSUE TITLE
AS 3.7.2 autosubmit monitor does not work

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#184]
In GitLab by @Eleftheriaexarchou on Sep 12, 2016, 14:22

The error is 

```
eexarcho@ bscearth304:/esnas/autosubmit/a00p/conf$ autosubmit monitor a00p 
Getting job list...

Checking configuration files...
autosubmit_a00p.conf OK
platforms_a00p.conf OK
jobs_a00p.conf OK
expdef_a00p.conf  OK
Configuration files OK
 Creating jobs...
Loading JobList
[CRITICAL] Unhandled exception on Autosubmit: iteration over non-sequence
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.7.2-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.2-py2.7.egg/autosubmit/autosubmit.py", line 330, in parse_args
    args.filter_type, args.hide)
  File "/shared/earth/software/autosubmit/3.7.2-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.2-py2.7.egg/autosubmit/autosubmit.py", line 780, in monitor
    job_list = Autosubmit.load_job_list(expid, as_conf)
  File "/shared/earth/software/autosubmit/3.7.2-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.2-py2.7.egg/autosubmit/autosubmit.py", line 2252, in load_job_list
    date_format, as_conf.get_retrials(), as_conf.get_default_job_type(), False)
  File "/shared/earth/software/autosubmit/3.7.2-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.2-py2.7.egg/autosubmit/job/job_list.py", line 112, in generate
    jobs_data = {str(row[0]): row for row in self.load()}
TypeError: iteration over non-sequence
```

@ jlope2  @dmanubens

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on Sep 12, 2016, 14:22

Title changed from **AS 7.2 autosubmit monitor does not work ** to **AS 3.7.2 autosubmit monitor does not work **

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Sep 12, 2016, 14:44

Hi @Eleftheriaexarchou,

Did you 'create' the experiment with the same version you are trying to do the 'monitor'?

Thanks!
