### ISSUE TITLE
Additional files bugfix2 - [merged]

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1880]
In GitLab by @dbeltrankyl on Nov 20, 2023, 12:22

_Merges additional-files-bugfix2 -> 4.0.XXX-branch_

Fixes #1158 issue, this is a continuation of a fix fixed in 4.0.99

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 20, 2023, 12:22

requested review from @kinow

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 20, 2023, 12:22

Hello @kinow ,

Could you look at this one? Seems that the fix in 4.0.99 was not enough. I've rewritten that part to look only for variables in the additional file, and now works.

**Comment by kinow** [comment]
approved this merge request

**Comment by kinow** [comment]
Code looks good!

**Comment by kinow** [comment]
Approved :bomb:

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 20, 2023, 12:26

Thanks for the quick review!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 20, 2023, 12:26

enabled an automatic merge when the pipeline for 5db2b6aaeae0eaf050643b3d7fc710fb46eff5c3 succeeds

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 20, 2023, 12:37

mentioned in commit b55e8e480dee28b5be1490c8b26eb2974f17c143

**Comment by kinow** [comment]
In GitLab by @abaer-kit on Nov 27, 2023, 14:37

Hi @dbeltrankyl, @kinow,

I think this merge is not yet updated on PyPi? I have some issues with v4.0.100 and additional files, but I suppose they are fixed with this MR. Is this intentional?

Best,
Andreas

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 27, 2023, 16:13

Hello @abaer-kit ,

Sorry, the last version was not in pip

Could you test with v4.0.101?

**Comment by kinow** [comment]
In GitLab by @abaer-kit on Nov 27, 2023, 16:35

Hello @dbeltrankyl,

with v4.0.101 my whole experiment works.

However, I get the following error (that still does not fail the whole experiment chain, though):
```python
Exception in thread JOB_a00a_PREPARE_EXPERIMENT:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/pool/autosubmit-venv/latest/lib/python3.10/site-packages/autosubmit/job/job.py", line 1155, in retrieve_logfiles
    platform.get_logs_files(self.expid, remote_logs)
  File "/pool/autosubmit-venv/latest/lib/python3.10/site-packages/autosubmit/platforms/platform.py", line 528, in get_logs_files
    self.get_files([job_out_filename, job_err_filename], False, 'LOG_{0}'.format(exp_id))
  File "/pool/autosubmit-venv/latest/lib/python3.10/site-packages/autosubmit/platforms/platform.py", line 504, in get_files
    self.get_file(filename, must_exist, relative_path)
  File "/pool/autosubmit-venv/latest/lib/python3.10/site-packages/autosubmit/platforms/paramiko_platform.py", line 406, in get_file
    os.makedirs(local_path)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/pool/experiments/a00a/tmp/LOG_a00a'
```
If this is a non-trivial thing, I would file a new issue as this seems to me somewhat unrelated.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 27, 2023, 16:48

I'm not sure what is the issue because

```
        local_path = os.path.join(self.tmp_path, relative_path)
        if not os.path.exists(local_path):
            os.makedirs(local_path)
```

It should not reach that part if the file exists. I'm a bit lost.

Does `/pool/experiments/a00a/tmp/LOG_a00a` all folders of this exist?

**Comment by kinow** [comment]
In GitLab by @abaer-kit on Nov 27, 2023, 17:00

They should have existed at this point, but I can't tell right now, as my pipeline does a quite good clean-up and the pipeline finished successfully.
Further, I cannot reproduce this myself, so I think we can consider this as fully solved. If it occurs again, I will open an issue.
