### ISSUE TITLE
Wrapper fix - rebased - [merged]

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1896]
In GitLab by @dbeltrankyl on Mar 5, 2024, 12:57

_Merges wrapper-fix-rebased -> master_

This fixes #1226 , 

I've changed the logic following the following points:

        # It is a deadlock when:
        # 1. There are no more non-wrapped jobs in ready status
        # 2. And there are no more jobs in the queue ( submitted, queuing, running, held )
        # 3. And all current wrappers being processed at this time are not wrappable.

The unit test seems to work fine with this version as well

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 5, 2024, 12:57

requested review from @kinow

**Comment by kinow** [comment]
`any_simple_packages = len(non_wrapped_jobs) > 0`

**Comment by kinow** [comment]
A comment where code could be simplified, but not a blocker. Also not easy to write a unit test for this, so +1 :muscle: 

Thank you @dbeltrankyl !

**Comment by kinow** [comment]
approved this merge request

**Comment by kinow** [comment]
CICD is borked... but I got some errors. @dbeltrankyl , can you try too to see if it's in this branch only?

**Comment by kinow** [comment]
```
test_returned_packages_parent_failed_mixed_wrapper (test.unit.test_wrappers.TestWrappers) ... ok
test_returned_packages_section_not_self_dependent (test.unit.test_wrappers.TestWrappers) ... ok

======================================================================
ERROR: Test if header and tailer are being properly substituted onto the final .cmd file without
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/home/bdepaula/Development/python/workspace/autosubmit/test/unit/test_job.py", line 816, in test_header_tailer
    job_list_obj.generate(
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 240, in generate
    raise AutosubmitCritical("Autosubmit couldn't load the workflow graph. Please run autosubmit create first. If the pkl file exists and was generated with Autosubmit v4.1+, try again.",7013)
log.log.AutosubmitCritical:  

======================================================================
ERROR: Test job platforms with a platform. Builds job and platform using YAML data, without mocks.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/home/bdepaula/Development/python/workspace/autosubmit/test/unit/test_job.py", line 596, in test_hetjob
    job_list_obj.generate(
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 240, in generate
    raise AutosubmitCritical("Autosubmit couldn't load the workflow graph. Please run autosubmit create first. If the pkl file exists and was generated with Autosubmit v4.1+, try again.",7013)
log.log.AutosubmitCritical:  

======================================================================
ERROR: Test job platforms with a platform. Builds job and platform using YAML data, without mocks.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/home/bdepaula/Development/python/workspace/autosubmit/test/unit/test_job.py", line 960, in test_job_parameters
    job_list_obj.generate(
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 240, in generate
    raise AutosubmitCritical("Autosubmit couldn't load the workflow graph. Please run autosubmit create first. If the pkl file exists and was generated with Autosubmit v4.1+, try again.",7013)
log.log.AutosubmitCritical:  

======================================================================
ERROR: test_create_dictionary (test.unit.test_job_list.TestJobList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/test/unit/test_job_list.py", line 354, in test_create_dictionary
    job_list.generate(
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 240, in generate
    raise AutosubmitCritical("Autosubmit couldn't load the workflow graph. Please run autosubmit create first. If the pkl file exists and was generated with Autosubmit v4.1+, try again.",7013)
log.log.AutosubmitCritical:  

======================================================================
ERROR: test_generate_job_list_from_monitor_run (test.unit.test_job_list.TestJobList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/test/unit/test_job_list.py", line 437, in test_generate_job_list_from_monitor_run
    job_list.generate(
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 240, in generate
    raise AutosubmitCritical("Autosubmit couldn't load the workflow graph. Please run autosubmit create first. If the pkl file exists and was generated with Autosubmit v4.1+, try again.",7013)
log.log.AutosubmitCritical:  

======================================================================
ERROR: test_run_member (test.unit.test_job_list.TestJobList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/test/unit/test_job_list.py", line 308, in test_run_member
    job_list.generate(
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 240, in generate
    raise AutosubmitCritical("Autosubmit couldn't load the workflow graph. Please run autosubmit create first. If the pkl file exists and was generated with Autosubmit v4.1+, try again.",7013)
log.log.AutosubmitCritical:  

======================================================================
ERROR: test_that_create_method_makes_the_correct_calls (test.unit.test_job_list.TestJobList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/test/unit/test_job_list.py", line 239, in test_that_create_method_makes_the_correct_calls
    job_list.generate(
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/job/job_list.py", line 240, in generate
    raise AutosubmitCritical("Autosubmit couldn't load the workflow graph. Please run autosubmit create first. If the pkl file exists and was generated with Autosubmit v4.1+, try again.",7013)
log.log.AutosubmitCritical:  

Name                                                                    Stmts   Miss  Cover
-------------------------------------------------------------------------------------------
autosubmit/__init__.py                                                      0      0   100%
autosubmit/autosubmit.py                                                 3747   3056    18%
autosubmit/database/__init__.py                                             0      0   100%
autosubmit/database/db_common.py                                          254    223    12%
autosubmit/database/db_manager.py                                         112     34    70%
autosubmit/database/db_structure.py                                        85     72    15%
autosubmit/experiment/__init__.py                                           0      0   100%
autosubmit/experiment/experiment_common.py                                 61     32    48%
autosubmit/git/__init__.py                                                  0      0   100%
autosubmit/git/autosubmit_git.py                                          181     95    48%
autosubmit/helpers/__init__.py                                              0      0   100%
autosubmit/helpers/autosubmit_helper.py                                    61     49    20%
autosubmit/helpers/data_transfer.py                                         2      0   100%
autosubmit/helpers/parameters.py                                           46      0   100%
autosubmit/helpers/utils.py                                                25     19    24%
autosubmit/history/__init__.py                                              0      0   100%
autosubmit/history/data_classes/__init__.py                                 0      0   100%
autosubmit/history/data_classes/experiment_run.py                          37     32    14%
autosubmit/history/data_classes/job_data.py                               164     60    63%
autosubmit/history/database_managers/__init__.py                            0      0   100%
autosubmit/history/database_managers/database_manager.py                   85     62    27%
autosubmit/history/database_managers/database_models.py                    20      0   100%
autosubmit/history/database_managers/experiment_history_db_manager.py     180    128    29%
autosubmit/history/database_managers/experiment_status_db_manager.py       69     47    32%
autosubmit/history/experiment_history.py                                  211    174    18%
autosubmit/history/experiment_status.py                                    22     14    36%
autosubmit/history/internal_logging.py                                     26      3    88%
autosubmit/history/platform_monitor/__init__.py                             0      0   100%
autosubmit/history/platform_monitor/output_examples/__init__.py             0      0   100%
autosubmit/history/platform_monitor/platform_monitor.py                     7      0   100%
autosubmit/history/platform_monitor/platform_utils.py                      34      9    74%
autosubmit/history/platform_monitor/slurm_monitor.py                       44      5    89%
autosubmit/history/platform_monitor/slurm_monitor_item.py                  54      4    93%
autosubmit/history/strategies.py                                          162     69    57%
autosubmit/history/utils.py                                                40     17    58%
autosubmit/job/__init__.py                                                  0      0   100%
autosubmit/job/job.py                                                    1756    777    56%
autosubmit/job/job_common.py                                              126     34    73%
autosubmit/job/job_dict.py                                                402    122    70%
autosubmit/job/job_grouping.py                                            238     21    91%
autosubmit/job/job_list.py                                               1908   1065    44%
autosubmit/job/job_list_persistence.py                                     59     24    59%
autosubmit/job/job_package_persistence.py                                  33     22    33%
autosubmit/job/job_packager.py                                            617    299    52%
autosubmit/job/job_packages.py                                            606    274    55%
autosubmit/job/job_utils.py                                               124     97    22%
autosubmit/monitor/__init__.py                                              0      0   100%
autosubmit/monitor/diagram.py                                             156    128    18%
autosubmit/monitor/monitor.py                                             381    202    47%
autosubmit/notifications/__init__.py                                        0      0   100%
autosubmit/notifications/mail_notifier.py                                  41     28    32%
autosubmit/notifications/notifier.py                                        9      3    67%
autosubmit/platforms/__init__.py                                            0      0   100%
autosubmit/platforms/ecplatform.py                                        230    174    24%
autosubmit/platforms/headers/__init__.py                                    0      0   100%
autosubmit/platforms/headers/ec_cca_header.py                              31     21    32%
autosubmit/platforms/headers/ec_header.py                                  10      4    60%
autosubmit/platforms/headers/local_header.py                                6      0   100%
autosubmit/platforms/headers/lsf_header.py                                 30     17    43%
autosubmit/platforms/headers/pbs10_header.py                               10      4    60%
autosubmit/platforms/headers/pbs11_header.py                               10      4    60%
autosubmit/platforms/headers/pbs12_header.py                               10      4    60%
autosubmit/platforms/headers/pjm_header.py                                 33     22    33%
autosubmit/platforms/headers/ps_header.py                                   8      2    75%
autosubmit/platforms/headers/sge_header.py                                 12      6    50%
autosubmit/platforms/headers/slurm_header.py                              163     66    60%
autosubmit/platforms/locplatform.py                                       172    111    35%
autosubmit/platforms/lsfplatform.py                                        73     52    29%
autosubmit/platforms/paramiko_platform.py                                 845    607    28%
autosubmit/platforms/paramiko_submitter.py                                140     40    71%
autosubmit/platforms/pbsplatform.py                                        76     54    29%
autosubmit/platforms/pjmplatform.py                                       301    208    31%
autosubmit/platforms/platform.py                                          430    205    52%
autosubmit/platforms/psplatform.py                                         76     55    28%
autosubmit/platforms/sgeplatform.py                                        72     48    33%
autosubmit/platforms/slurmplatform.py                                     423    273    35%
autosubmit/platforms/submitter.py                                           4      1    75%
autosubmit/platforms/wrappers/__init__.py                                   0      0   100%
autosubmit/platforms/wrappers/wrapper_builder.py                          290    173    40%
autosubmit/platforms/wrappers/wrapper_factory.py                          155     87    44%
autosubmit/profiler/__init__.py                                             0      0   100%
autosubmit/profiler/profiler.py                                            61      0   100%
autosubmit/provenance/__init__.py                                           1      0   100%
autosubmit/provenance/rocrate.py                                          179      0   100%
autosubmit/statistics/__init__.py                                           0      0   100%
autosubmit/statistics/jobs_stat.py                                         68     13    81%
autosubmit/statistics/statistics.py                                       110     57    48%
autosubmit/statistics/stats_summary.py                                     19      3    84%
autosubmit/statistics/utils.py                                             37     21    43%
-------------------------------------------------------------------------------------------
TOTAL                                                                   16270   9632    41%
----------------------------------------------------------------------
Ran 275 tests in 2.733s

FAILED (SKIP=34, errors=7)
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 5, 2024, 16:03

I'll check. maybe it is derived from the cherry-pick

**Comment by kinow** [comment]
The code itself is looking good. So feel free to merge it if you get a clean build.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 6, 2024, 10:36

added 1 commit

<ul><li>ffbb41b3 - fixed tests</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/408/diffs?diff_id=22290&start_sha=c91ebb1f2fb4b1c6bb6f64aee872888c3b6f7f89)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 6, 2024, 10:37

Hello Bruno. 

Forget to update the function generate from the tests in the last commit of the major branch request. 

Now it is fixed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 6, 2024, 10:40

Commented on [autosubmit/job/job_packager.py line 444](https://github.com/BSC-ES/autosubmit/compare/f32a168b38293fcaef3899e359d67cf3719ba316..ffbb41b316be65db22d4de3525ca7c4f2125f7a5#diff-4cd1666eaa9d850b5be44894b5b50606R444)



changed this line in [version 3 of the diff](/gitlab/es/autosubmit/-/merge_requests/408/diffs?diff_id=22294&start_sha=ffbb41b316be65db22d4de3525ca7c4f2125f7a5#5f0b94200cd6fe21f04541be00275830df01b4b4_444_441)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 6, 2024, 10:40

added 1 commit

<ul><li>50cbd9bf - fix feedback</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/408/diffs?diff_id=22294&start_sha=ffbb41b316be65db22d4de3525ca7c4f2125f7a5)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 6, 2024, 10:40

Commented on [autosubmit/job/job_packager.py line 444](https://github.com/BSC-ES/autosubmit/compare/f32a168b38293fcaef3899e359d67cf3719ba316..ffbb41b316be65db22d4de3525ca7c4f2125f7a5#diff-4cd1666eaa9d850b5be44894b5b50606R444)



thanks!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 6, 2024, 10:41

resolved all threads

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 6, 2024, 10:41

mentioned in commit d3446032607a01ba4f415a26e2d3db2a0dad876b

**Comment by kinow** [comment]
Thank you @dbeltrankyl ! I see our CICD is still broken, so I will open an issue in the CES requests repo for that :thumbsup:

**Comment by kinow** [comment]
Reported https://earth.bsc.es/gitlab/es/requests/-/issues/2403
