### ISSUE TITLE
Fix error autosubmit version - [merged]

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1899]
In GitLab by @dbeltrankyl on Mar 7, 2024, 11:35

_Merges fix-error-autosubmitversion -> master_

Fixes a false Raised AutosubmitCritical when launching autosubmit -v

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 7, 2024, 11:35

requested review from @kinow

**Comment by kinow** [comment]
Sorry, got sidetracked. Reviewing it now!

**Comment by kinow** [comment]
No biggie, but why are we skipping `4.1.1`?

**Comment by kinow** [comment]
Maybe we could fix it in a different way. Looks like the issue was caused by the new function `exit_from_error`, which takes an `e` (any type), but assuming that the type contains `.code`, `.message`, `.trace`.

My PyCharm is complained about that when I imported the code.

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/1aa885e9ed854c13f089ef1bbc585e97/image.png)

I think here you are solving it by checking if it contains `e.trace`. If not, then you only log `Log.critical("{1} [eCode={0}]", e.code, e.message)`.

But following what PyCharm says, I think `e.code` will result in a `AttributeError`?

**Comment by kinow** [comment]
I reproduced the issue on `master`,

```bash
(autosubmit4) bdepaula@ bsces107921:~/Development/python/workspace/autosubmit$ autosubmit -v
/home/bdepaula/mambaforge/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.1.0')
4.1.0
 [CRITICAL] An Unknown error occurred: 0.
 Please report it to Autosubmit Developers through Git
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

The error message doesn't give much to the user. Why don't we use the `Log.log.log` (this is Python logging) passing the exception for context, @dbeltrankyl ?

This

```diff
(autosubmit4) bdepaula@ bsces107921:~/Development/python/workspace/autosubmit$ git diff
diff --git a/bin/autosubmit b/bin/autosubmit
index 21c05601..41de7455 100755
--- a/bin/autosubmit
+++ b/bin/autosubmit
@@ -39,8 +39,10 @@ def exit_from_error(e):
         if not e.trace:
             Log.debug("Trace: {0}", str(e.trace))
         Log.critical("{1} [eCode={0}]", e.code, e.message)
-    except:
-        Log.critical("An Unknown error occurred: {0}.\n Please report it to Autosubmit Developers through Git", str(e))
+    except BaseException as exp:
+        msg = "An Unknown error occurred: {0}.\n Please report it to Autosubmit Developers through Git"
+        args = [str(exp)]
+        Log.log.log(Log.CRITICAL, msg.format(*args), exc_info=exp)
     Log.info("More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html")
     os._exit(1)
 
```

includes the stacktrace, and then it's super fast to spot what was the problem, without the need to look at the code (what I commented to @mcastril /others in the production runs incidents about improving how we log).

```bash
(autosubmit4) bdepaula@ bsces107921:~/Development/python/workspace/autosubmit$ autosubmit -v
/home/bdepaula/mambaforge/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.1.0')
4.1.0
 [CRITICAL] An Unknown error occurred: 'SystemExit' object has no attribute 'trace'.
 Please report it to Autosubmit Developers through Git
Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/bin/autosubmit", line 52, in main
    return_value = Autosubmit.parse_args()
  File "/home/bdepaula/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 647, in parse_args
    args = parser.parse_args()
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/argparse.py", line 1071, in __call__
    parser.exit()
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.8/argparse.py", line 2508, in exit
    _sys.exit(status)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bdepaula/Development/python/workspace/autosubmit/bin/autosubmit", line 39, in exit_from_error
    if not e.trace:
AttributeError: 'SystemExit' object has no attribute 'trace'
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

While the output may look more intimidating to users, for workflow managers it probably makes sense since some users might benefit from having more context to troubleshoot their errors and report to us.

And I think the error is coming because we have a bug in how we are using `argparse`'s `action=version`. That value does not exist. And setting it to a string that is not supported will result in an `ArgumentError` (which we get but are hiding right now).

>The recommended way to create a custom action is to extend Action, overriding the __call__ method and optionally the __init__ and format_usage method

https://docs.python.org/3/library/argparse.html#argparse.Action

I think somebody else did that, not sure why. But we can fix by using `store_true` and then when asked for the version, print it and return `0`.

Then in `exit_from_error` we check for instance for our AS exception, and only if those types are passed we call the `.code`, `.trace`, etc.

WDYT?

**Comment by kinow** [comment]
Oh, here's my latest diff

```diff
diff --git a/autosubmit/autosubmit.py b/autosubmit/autosubmit.py
index bb243e0d..d59820e2 100644
--- a/autosubmit/autosubmit.py
+++ b/autosubmit/autosubmit.py
@@ -167,8 +167,7 @@ class Autosubmit:
             BasicConfig.read()
             parser = MyParser(
                 description='Main executable for autosubmit. ')
-            parser.add_argument('-v', '--version', action='version',
-                                version=Autosubmit.autosubmit_version)
+            parser.add_argument('-v', '--version', dest='version', action='store_true')
             parser.add_argument('-lf', '--logfile', choices=('NO_LOG', 'INFO', 'WARNING', 'DEBUG'),
                                 default='DEBUG', type=str,
                                 help="sets file's log level.")
@@ -644,13 +643,17 @@ class Autosubmit:
                                    help='Read job files generated by the inspect subcommand.')
             subparser.add_argument('ID', metavar='ID', help='An ID of a Workflow (eg a000) or a Job (eg a000_20220401_fc0_1_1_APPLICATION).')
 
-            args = parser.parse_args()
+            args, unknown = parser.parse_known_args()
 
-            if args.command is None:
+            if args.version:
+                print(Autosubmit.autosubmit_version)
+                return 0
+
+            if unknown or args.command is None:
                 parser.print_help()
-                parser.exit()
+                return 0
 
-        except Exception as e:
+        except BaseException as e:
             if type(e) is SystemExit:  # todo check
                 # Version keyword force an exception in parse arg due and os_exit(0) but the program is successfully finished
                 if "0" in str(e):
diff --git a/bin/autosubmit b/bin/autosubmit
index 21c05601..37cd7e11 100755
--- a/bin/autosubmit
+++ b/bin/autosubmit
@@ -30,17 +30,21 @@ sys.path.append(os.path.normpath(os.path.join(scriptdir, os.pardir)))
 # noinspection PyUnresolvedReferences
 from log.log import Log, AutosubmitCritical , AutosubmitError
 from autosubmit.autosubmit import Autosubmit
+from typing import Union
 
 
-def exit_from_error(e):
+def exit_from_error(e: BaseException):
     with suppress(FileNotFoundError, PermissionError):
         os.remove(os.path.join(Log.file_path, "autosubmit.lock"))
-    try:
+    if isinstance(e, (AutosubmitCritical, AutosubmitError)):
+        e: Union[AutosubmitError, AutosubmitCritical] = e
         if not e.trace:
             Log.debug("Trace: {0}", str(e.trace))
         Log.critical("{1} [eCode={0}]", e.code, e.message)
-    except:
-        Log.critical("An Unknown error occurred: {0}.\n Please report it to Autosubmit Developers through Git", str(e))
+    else:
+        msg = "An Unknown error occurred: {0}.\n Please report it to Autosubmit Developers through Git"
+        args = [str(e)]
+        Log.log.log(Log.CRITICAL, msg.format(*args), exc_info=e)
     Log.info("More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html")
     os._exit(1)
 

```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 7, 2024, 16:35

Commented on [VERSION line 1](https://github.com/BSC-ES/autosubmit/compare/db907829a385ee97556717b2a3a2325842fe0753..d2630cb646368a15348ce94de194c7ba7b5ad6d7#diff-021321e8c168ba3ae39ce3a2e7b3ec87R1)



Because the 4.1.1 tag exists ( the one that is being tested by Rohan ) but I forgot to update the version file

**Comment by kinow** [comment]
>But the users were complaining about the long trace
>
>I wanted to move it to log.debug is only shown in the Log files or when you're using -LC debug I remember that I did it, but I'm not sure when I deleted that part. I'll re-add it

Doesn't need to be done in this MR, but if you do that that might fix (either completely, or partially) #1199. Thanks for the explanation.

>I'll revise the rest of the feedback tomorrow, thanks!

Roger that! I'm watching this so I should get an email once you push something, but I will wait for your message to take another look at this one.

Thanks Dani!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 10:12

Commented on [bin/autosubmit line 42](https://github.com/BSC-ES/autosubmit/compare/db907829a385ee97556717b2a3a2325842fe0753..413968dd91c89a0839c8dc4e8dea21c8bef9955d#diff-2fe7b98febd0e3dbdfc7ac517eb3edceR42)



changed this line in [version 2 of the diff](/gitlab/es/autosubmit/-/merge_requests/411/diffs?diff_id=22458&start_sha=413968dd91c89a0839c8dc4e8dea21c8bef9955d#3fb811c119645eeeaa71b2047922e825335e6520_42_45)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 10:12

added 1 commit

<ul><li>b8c6fec7 - Address feedback</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/411/diffs?diff_id=22458&start_sha=413968dd91c89a0839c8dc4e8dea21c8bef9955d)

**Comment by kinow** [comment]
Quick test and it worked!

```bash
(autosubmit4) kinow@ranma:~/Development/python/workspace/autosubmit$ autosubmit -v
/home/kinow/micromamba/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.1.0')
4.1.2
```

And an unknown command

```bash
(autosubmit4) kinow@ranma:~/Development/python/workspace/autosubmit$ autosubmit -vfdkjfhdskjs
/home/kinow/micromamba/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.1.0')
error: argument -v/--version: ignored explicit argument 'fdkjfhdskjs'
usage: autosubmit [-h] [-v] [-lf {NO_LOG,INFO,WARNING,DEBUG}] [-lc {NO_LOG,INFO,WARNING,DEBUG}]
                  {run,expid,delete,monitor,stats,clean,recovery,migrate,inspect,check,describe,report,create,configure,install,setstatus,testcase,dbfix,pklfix,updatedescrip,test,refresh,updateversion,archive,unarchive,upgrade,readme,changelog,cat-log}
                  ...

Main executable for autosubmit.

positional arguments:
  {run,expid,delete,monitor,stats,clean,recovery,migrate,inspect,check,describe,report,create,configure,install,setstatus,testcase,dbfix,pklfix,updatedescrip,test,refresh,updateversion,archive,unarchive,upgrade,readme,changelog,cat-log}

optional arguments:
  -h, --help            show this help message and exit
  -v, --version
  -lf {NO_LOG,INFO,WARNING,DEBUG}, --logfile {NO_LOG,INFO,WARNING,DEBUG}
                        sets file's log level.
  -lc {NO_LOG,INFO,WARNING,DEBUG}, --logconsole {NO_LOG,INFO,WARNING,DEBUG}
                        sets console's log level
```

And a valid command

```bash
$ autosubmit create a002 -v -np
/home/kinow/micromamba/envs/autosubmit4/bin/autosubmit:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('autosubmit==4.1.0')
The a002 experiment 4.1.0 version is being updated to 4.1.2 for match autosubmit version
Autosubmit is running with 4.1.2
Preparing .lock file to avoid multiple instances with same expid.
Using project folder: /home/kinow/autosubmit/a002/proj

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Loading parameters...

Creating the jobs list...
Loading JobList
Loading JobList
Creating jobs...
Load finished
Adding dependencies to the graph..
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...

Saving the jobs list...

Job list created successfully

```

:tada: going to read the code now...

**Comment by kinow** [comment]
>( the error is raised due to the "auto" keyword being only available in the branch of the calendar split)

:pray: if we get that working, and we can start modifying our errors so that we can reply to bugs (or have in the issue template) with something like "Please, include the information of the command-line error with `autosubmit -lc DEBUG` , and if that brings extra information like that nice stacktrace, it will be **really useful** @dbeltrankyl !! :clap: :bow:

**Comment by kinow** [comment]
Do we still need the `SystemExit` here? That should not happen anymore.

Previously, we were using the wrong API in `argparse`, which caused it to call `_sys.exit(...)`, which raises this error.

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/ff28d7b58db5ae7c248c431eebfaefc7/image.png)

Now that we are not doing that, `argparse` should not raise any `SystemExit`. If somewhere else, some other code does that, it might be OK to let the exception blow so we learn what's going on and see if it needs to be fixed.

**Comment by kinow** [comment]
I like your new version! PyCharm is happy too. I think we can remove this version commented out. Thanks @dbeltrankyl !

**Comment by kinow** [comment]
One last question (promise!). About the `SystemExit`. Other than that everything looks good!

**Comment by kinow** [comment]
Ah, and here I wonder if we should not return `1` or another code `> 0`?

**Comment by kinow** [comment]
Then we can also maybe add a test, so that it fails earlier, before the testing suite is launched (I think that's how @rohanali1798 found this bug?),

```py
import subprocess
from pathlib import Path
from unittest import TestCase

import sys

from autosubmit.autosubmit import Autosubmit


class TestAutosubmit(TestCase):

    def testAutosubmitVersion(self):
        bin_path = Path(__file__, '../../../bin/autosubmit').resolve()
        out = subprocess.getoutput(' '.join([sys.executable, str(bin_path), '-v']))
        self.assertEquals(Autosubmit.autosubmit_version, out.strip())

    def testAutosubmitVersionBroken(self):
        bin_path = Path(__file__, '../../../bin/autosubmit').resolve()
        exit_code, _ = subprocess.getstatusoutput(' '.join([sys.executable, str(bin_path), '-abcdefg']))
        self.assertEquals(1, exit_code)

```

(Not super nice to locate the script that way, but we can fix that later using a Python entry point... later)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 11:39

By default, it is already saved in the aslogs/run, so maybe we could just say something like please open an issue in git and attach the tmp/aslogs/${command_timestamp}.log

**Comment by kinow** [comment]
:100: yes!!! :pray:

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 11:41

The default levels are: 

autosubmit -lc INFO -lf DEBUG $command

**Comment by kinow** [comment]
I thought the default was INFO for both. #TodayILearned, so now I will just set `-lc DEBUG`. Thanks @dbeltrankyl !

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 11:46

Commented on [autosubmit/autosubmit.py line 655](https://github.com/BSC-ES/autosubmit/compare/db907829a385ee97556717b2a3a2325842fe0753..b8c6fec70d6505114f44a98c2e4d50e4e4029ba9#diff-fb87ba4e4225b357016f4298108bcf0dR655)



Sure, forgot to delete it

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 12:17

Commented on [autosubmit/autosubmit.py line 655](https://github.com/BSC-ES/autosubmit/compare/db907829a385ee97556717b2a3a2325842fe0753..b8c6fec70d6505114f44a98c2e4d50e4e4029ba9#diff-fb87ba4e4225b357016f4298108bcf0dR655)



changed this line in [version 3 of the diff](/gitlab/es/autosubmit/-/merge_requests/411/diffs?diff_id=22476&start_sha=b8c6fec70d6505114f44a98c2e4d50e4e4029ba9#6bde465286156a9da245a31e64df703a55c76323_655_654)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 12:17

Commented on [bin/autosubmit line 64](https://github.com/BSC-ES/autosubmit/compare/db907829a385ee97556717b2a3a2325842fe0753..b8c6fec70d6505114f44a98c2e4d50e4e4029ba9#diff-2fe7b98febd0e3dbdfc7ac517eb3edceR64)



changed this line in [version 3 of the diff](/gitlab/es/autosubmit/-/merge_requests/411/diffs?diff_id=22476&start_sha=b8c6fec70d6505114f44a98c2e4d50e4e4029ba9#3fb811c119645eeeaa71b2047922e825335e6520_64_54)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 12:17

added 1 commit

<ul><li>e3d36c35 - Deleted systemexit</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/411/diffs?diff_id=22476&start_sha=b8c6fec70d6505114f44a98c2e4d50e4e4029ba9)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 12:17

> By default, it is already saved in the aslogs/run, so maybe we could just say something like please open an issue in git and attach the tmp/aslogs/${command_timestamp}.log

About this, I'm not able to retrieve the log.file_name I'll look into it on another issue

> if we get that working, and we can start modifying our errors so that we can reply to bugs (or have in the issue template) with something like "Please, include the information of the command-line error with `autosubmit -lc DEBUG` , and if that brings extra information like that nice stacktrace, it will be **really useful** @dbeltrankyl !! :clap: :bow:

About this, 

I saw that if an error has a f-string it is making the log.debug to crash, will also look in another issue

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 12:19

> About this, I saw that if an error has a f-string it is making the log.debug to crash, will also look in another issue

I added a try: except for now

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 12:23

Commented on [autosubmit/autosubmit.py line 653](https://github.com/BSC-ES/autosubmit/compare/db907829a385ee97556717b2a3a2325842fe0753..e3d36c353e5c73502d552d33f9fc977c84dd8ec7#diff-fb87ba4e4225b357016f4298108bcf0dR653)



changed this line in [version 4 of the diff](/gitlab/es/autosubmit/-/merge_requests/411/diffs?diff_id=22478&start_sha=e3d36c353e5c73502d552d33f9fc977c84dd8ec7#6bde465286156a9da245a31e64df703a55c76323_653_653)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 12:23

added 1 commit

<ul><li>fc97d037 - added unit test</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/411/diffs?diff_id=22478&start_sha=e3d36c353e5c73502d552d33f9fc977c84dd8ec7)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 12:23

Commented on [autosubmit/autosubmit.py line 653](https://github.com/BSC-ES/autosubmit/compare/db907829a385ee97556717b2a3a2325842fe0753..e3d36c353e5c73502d552d33f9fc977c84dd8ec7#diff-fb87ba4e4225b357016f4298108bcf0dR653)



added!

Rohan found it because he always launch autosubmit -v manually ( I think )

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 12:23

resolved all threads

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 12:24

Thanks for the feedback and the unit test, I've addressed your feedback

**Comment by kinow** [comment]
(And thanks for the prompt replies to the feedback too!!)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 12:29

added 4 commits

<ul><li>fc8ab838 - Fixes &quot;attempt to cancel an het job&quot; failure message</li><li>fb0de45f - Changes &quot;backup error message&quot;</li><li>76da0d0b - Changed the location of pkl.tmp as pkl is not Writeable for the users</li><li>47cefe7b - added unit test changed code based on feedback</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/411/diffs?diff_id=22482&start_sha=fc97d0370bcda1ea9b643edc3a9deb1e08c9bd06)

**Comment by kinow** [comment]
Sorry, I think only the unknown command must return non `0`. Here if a user requested to print the version, we can print the version and exit `0` (in case someone is using that in a script it won't fail their script)

**Comment by kinow** [comment]
Then maybe here we can check for `0` and the output... sorry.

Although the tests pass on PyCharm, but not with `unittest` :disappointed_relieved:

**Comment by kinow** [comment]
With this patch

```diff
(autosubmit4) kinow@ranma:~/Development/python/workspace/autosubmit$ git diff
diff --git a/autosubmit/autosubmit.py b/autosubmit/autosubmit.py
index 980ed474..f40c65b8 100644
--- a/autosubmit/autosubmit.py
+++ b/autosubmit/autosubmit.py
@@ -647,7 +647,7 @@ class Autosubmit:
             args, unknown = parser.parse_known_args()
             if args.version:
                 print(Autosubmit.autosubmit_version)
-                return 1
+                return 0
             if unknown or args.command is None:
                 parser.print_help()
                 return 1
diff --git a/test/unit/test_version.py b/test/unit/test_version.py
index 767f3808..85697976 100644
--- a/test/unit/test_version.py
+++ b/test/unit/test_version.py
@@ -11,10 +11,11 @@ class TestAutosubmit(TestCase):
 
     def testAutosubmitVersion(self):
         bin_path = Path(__file__, '../../../bin/autosubmit').resolve()
-        out = subprocess.getoutput(' '.join([sys.executable, str(bin_path), '-v']))
-        self.assertEquals(Autosubmit.autosubmit_version, out.strip())
+        exit_code, out = subprocess.getstatusoutput(' '.join([sys.executable, str(bin_path), '-v']))
+        self.assertEqual(0, exit_code)
+        self.assertEqual(Autosubmit.autosubmit_version, out.strip())
 
     def testAutosubmitVersionBroken(self):
         bin_path = Path(__file__, '../../../bin/autosubmit').resolve()
         exit_code, _ = subprocess.getstatusoutput(' '.join([sys.executable, str(bin_path), '-abcdefg']))
-        self.assertEquals(1, exit_code)
+        self.assertEqual(1, exit_code)
```

With pytest

```
FAILED test/unit/test_catlog.py::TestJob::test_command_line_help - log.log.AutosubmitCritical:
FAILED test/unit/test_job_list.py::TestJobList::test_load - AssertionError: AutosubmitCritical not raised
FAILED test/unit/test_version.py::TestAutosubmit::testAutosubmitVersion - AssertionError: '4.1.2' != ''
```

And with unittest (gitlab-ci command)

```bash
...
test_returned_packages_section_not_self_dependent (test.unit.test_wrappers.TestWrappers) ... ok

======================================================================
ERROR: test_command_line_help (test.unit.test_catlog.TestJob)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 647, in parse_args
    args, unknown = parser.parse_known_args()
  File "/home/kinow/micromamba/envs/autosubmit4/lib/python3.9/argparse.py", line 1858, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/kinow/micromamba/envs/autosubmit4/lib/python3.9/argparse.py", line 2049, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/home/kinow/micromamba/envs/autosubmit4/lib/python3.9/argparse.py", line 2026, in consume_positionals
    take_action(action, args)
  File "/home/kinow/micromamba/envs/autosubmit4/lib/python3.9/argparse.py", line 1935, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/kinow/micromamba/envs/autosubmit4/lib/python3.9/argparse.py", line 1214, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/home/kinow/micromamba/envs/autosubmit4/lib/python3.9/argparse.py", line 1858, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/kinow/micromamba/envs/autosubmit4/lib/python3.9/argparse.py", line 2067, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/kinow/micromamba/envs/autosubmit4/lib/python3.9/argparse.py", line 2007, in consume_optional
    take_action(action, args, option_string)
  File "/home/kinow/micromamba/envs/autosubmit4/lib/python3.9/argparse.py", line 1935, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/kinow/micromamba/envs/autosubmit4/lib/python3.9/argparse.py", line 1100, in __call__
    parser.exit()
  File "/home/kinow/micromamba/envs/autosubmit4/lib/python3.9/argparse.py", line 2569, in exit
    _sys.exit(status)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/test/unit/test_catlog.py", line 124, in test_command_line_help
    assert Autosubmit.parse_args()
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 655, in parse_args
    raise AutosubmitCritical(
log.log.AutosubmitCritical:  

======================================================================
FAIL: test_load (test.unit.test_job_list.TestJobList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/test/unit/test_job_list.py", line 119, in test_load
    job_list_to_load.load(False)
AssertionError: AutosubmitCritical not raised

======================================================================
FAIL: testAutosubmitVersion (test.unit.test_version.TestAutosubmit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/test/unit/test_version.py", line 16, in testAutosubmitVersion
    self.assertEqual(Autosubmit.autosubmit_version, out.strip())
AssertionError: '4.1.2' != ''
- 4.1.2
+ 

...
-------------------------------------------------------------------------------------------
TOTAL                                                                   16281   8857    46%
----------------------------------------------------------------------
Ran 278 tests in 11.935s

FAILED (SKIP=34, errors=1, failures=2)

```
With

**Comment by kinow** [comment]
But the two for this merge request pass with this patch, on PyCharm... WDYT @dbeltrankyl ?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 13:18

Commented on [autosubmit/autosubmit.py line 650](https://github.com/BSC-ES/autosubmit/compare/db907829a385ee97556717b2a3a2325842fe0753..47cefe7be8840be5e43627e657e6c7a5bf616aa3#diff-fb87ba4e4225b357016f4298108bcf0dR650)



changed this line in [version 6 of the diff](/gitlab/es/autosubmit/-/merge_requests/411/diffs?diff_id=22488&start_sha=47cefe7be8840be5e43627e657e6c7a5bf616aa3#6bde465286156a9da245a31e64df703a55c76323_650_650)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 13:18

Commented on [test/unit/test_version.py line 15](https://github.com/BSC-ES/autosubmit/compare/db907829a385ee97556717b2a3a2325842fe0753..47cefe7be8840be5e43627e657e6c7a5bf616aa3#diff-b250300cfd022705060c8fdbe3c5cae4R15)



changed this line in [version 6 of the diff](/gitlab/es/autosubmit/-/merge_requests/411/diffs?diff_id=22488&start_sha=47cefe7be8840be5e43627e657e6c7a5bf616aa3#e2af96106ed36c92eb84cae10d1d2e374cf04998_15_14)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 13:18

added 1 commit

<ul><li>d2630cb6 - Patched</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/411/diffs?diff_id=22488&start_sha=47cefe7be8840be5e43627e657e6c7a5bf616aa3)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 13:19

Patched, thanks @kinow ! 

Yes, I don't know why pytest works but not with the other testers. I think we can fix it in another merge?

**Comment by kinow** [comment]
Agreed!!! :pray: 


Tested

```bash
(autosubmit4) kinow@ranma:~/Development/python/workspace/autosubmit$ git show
commit d2630cb646368a15348ce94de194c7ba7b5ad6d7 (HEAD -> fix-error-autosubmitversion, upstream/fix-error-autosubmitversion)
Author: Daniel Beltran Mora <daniel.beltran@ bsc.es>
Date:   Fri Mar 8 13:18:20 2024 +0100

    Patched

```

The `autosubmit -v`, `autosubmit -balablabla`, and `autosubmit create a001 -np -v` all worked as expected, right exit code.

Sorry the delay, and LGTM!

**Comment by kinow** [comment]
approved this merge request

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2024, 13:21

mentioned in commit 36420962042f5235d6a9b004e1d96f2713992bed
