### ISSUE TITLE
Errors with autosubmit monitor and autosubmit run

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#192]
In GitLab by @mcastril on Sep 17, 2016, 15:54

Created experiment t00y using AS 3.7.0 (I think)

Tried autosubmit setstatus t00y -s -t COMPLETED -fl t00y_19900101_fc0_1_SIM

Had this error:
````
Preparing .lock file to avoid multiple instances with same expid.
[CRITICAL] Unhandled exception on Autosubmit: 'list' object has no attribute 'get_job_list'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 311, in parse_args
    args.filter_chunks, args.filter_status, args.filter_type, args.hide)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 1705, in set_status
    for job in job_list.get_job_list():
AttributeError: 'list' object has no attribute 'get_job_list'
````

Tried autosubmit monitor t00y

````
Getting job list...
[CRITICAL] Unhandled exception on Autosubmit: local variable 'jobs' referenced before assignment
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 294, in parse_args
    args.filter_type, args.hide)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 789, in monitor
    for job in jobs:
UnboundLocalError: local variable 'jobs' referenced before assignment
````

Then loaded Autosubmit 3.7.0 module (because in that moment I had AS 3.6):

autosubmit setstatus t00y -s -t COMPLETED -fl t00y_19900101_fc0_1_SIM 

Worked

autosubmit run t00y

Error:

````
[CRITICAL] Unhandled exception on Autosubmit: iteration over non-sequence
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.7.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.0-py2.7.egg/autosubmit/autosubmit.py", line 313, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.7.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.0-py2.7.egg/autosubmit/autosubmit.py", line 592, in run_experiment
    job_list = Autosubmit.load_job_list(expid, as_conf)
  File "/shared/earth/software/autosubmit/3.7.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.0-py2.7.egg/autosubmit/autosubmit.py", line 2197, in load_job_list
    date_format, as_conf.get_retrials(), as_conf.get_default_job_type(), False)
  File "/shared/earth/software/autosubmit/3.7.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.0-py2.7.egg/autosubmit/job/job_list.py", line 112, in generate
    jobs_data = {str(row[0]): row for row in self.load()}
TypeError: iteration over non-sequence
````

@dmanubens @ jlope2

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Sep 19, 2016, 08:16

Hi @mcastril,

Did you try to ```create``` and ```run``` (or ```setstatus```) your experiment with the same Autosubmit version?

Thanks!

**Comment by kinow** [comment]
In GitLab by @fmassonn on Sep 19, 2016, 08:58

Hi @dmanubens and @ jlope2 

Not sure it's the same error, but maybe.

I'm trying to run a new ensemble experiment

```
exp=a0an; nohup autosubmit run ${exp} >& ~/logs/autosubmit/log_${exp}_`date +%Y%m%d%H%M%S`_${HOST} &
```

Autosubmit starts, but then quits without any message:

```
tail  /fmassonn@ bscearth321: ~/logs/autosubmit >> home/Earth/fmassonn/logs/autosubmit/log_a0an_20160919084158_bscesautosubmit01
Checking configuration files...
autosubmit_a0an.conf OK
platforms_a0an.conf OK
jobs_a0an.conf OK
expdef_a0an.conf  OK
Configuration files OK

Starting job submission...
```

The experiment has a very large number of chunks and it is not possible to ask ausosubmit to plot the tree.

Thanks

François

**Comment by kinow** [comment]
In GitLab by @mcastril on Sep 19, 2016, 09:56

Hi,

That's what I don't know, because as I am running the testing suite I used different versions. I started using 3.7 but as I had to run on ECMWF I switched later to 3.6, and when I run this commands, as they were not working I switched again to 3.7.

Isn't there a way to know with which version did you create an experiment? I know there is a Version parameter in autosubmit.conf... but I think this is only set the first time you create the experiment, isn't it?

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Sep 19, 2016, 10:37

@mcastril,

There's no way no know with what version did you do the ```create```.

Anyway, my recommendation is run always all the commands with the same version: ```create```, ```monitor```, ```run```, ```setstatus```, etc.

If this way does not work, let me know it.



@fmassonn,

Your error does not seem the Miguel's error. We'll research about it. Thanks!

**Comment by kinow** [comment]
In GitLab by @mcastril on Sep 19, 2016, 11:31

mentioned in issue es/auto-ecearth3#79

**Comment by kinow** [comment]
In GitLab by @fmassonn on Sep 20, 2016, 14:41

Hi @ jlope2 ,

Have you been able to look into this? Should I re-create and re-run?

François

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Sep 20, 2016, 15:00

No, I'm sorry.

This corresponds to the last ```autosubmit run``` of the experiment ```a0an```?

Thanks!

**Comment by kinow** [comment]
In GitLab by @fmassonn on Sep 20, 2016, 15:11

yes exactly! thanks

**Comment by kinow** [comment]
In GitLab by @fmassonn on Sep 23, 2016, 15:12

Hi Joan,

Did you have time to look into this? Am I the only one having this problem?

François

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Sep 23, 2016, 16:15

@fmassonn how long it takes to make the ```create``` command?

Thanks!

**Comment by kinow** [comment]
In GitLab by @fmassonn on Sep 23, 2016, 16:30

Hi, quite long (about 30 min) you should use with the -np option because otherwise it won't be able to plot it.

**Comment by kinow** [comment]
In GitLab by @vsicardi on Oct 10, 2016, 12:42

Hi @fmassonn,
I am having the same problem with monitor when experiments have many chunks (>150). I do the same  you do, using the -np filter, but I am wondering if  you found  a real solution to this problem. 
Thank you

**Comment by kinow** [comment]
In GitLab by @fmassonn on Oct 10, 2016, 12:43

There has been no progress on this issue as far as I know.

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Oct 13, 2016, 23:39

Milestone removed

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Oct 28, 2016, 09:54

Mentioned in commit 83f8c829395b5395e330721e8c936725a5ba97dd

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 16:50

related to #353, continue there please.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 16:50

closed
