### ISSUE TITLE
inconvenient "6" appeared in my jobs configuration files

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#203]
In GitLab by @fmassonn on Oct 14, 2016, 13:37

Hi,

I think this issue is related to the fact that the parameter `TASKS` was removed automatically from all jobs_????.conf files.

All my jobs_????.conf files now have a "6" that appears in one additional line. This gives rise to the issue:

```
fmassonn@ bscearth321: ~/logs/autosubmit >> autosubmit setstatus -s -t COMPLETED -fl "a0al_19580101_fc00_64_SIM" a0al -np
Preparing .lock file to avoid multiple instances with same expid.
[CRITICAL] Unhandled exception on Autosubmit: File contains parsing errors: /esnas/autosubmit/a0al/conf/jobs_a0al.conf
        [line 23]: '6\n'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 311, in parse_args
    args.filter_chunks, args.filter_status, args.filter_type, args.hide)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 1644, in set_status
    as_conf.reload()
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/config/config_common.py", line 371, in reload
    self.jobs_parser = AutosubmitConfig.get_parser(self.parser_factory, self._jobs_parser_file)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/config/config_common.py", line 801, in get_parser
    parser.read(file_path)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ParsingError: File contains parsing errors: /esnas/autosubmit/a0al/conf/jobs_a0al.conf
        [line 23]: '6\n'
```

Look for example in `/esnas/autosubmit/a07m/conf/jobs_a07m.conf ` after the THREADS variable.

Did you introduce this by mistake when looping over all jobs_????.conf files??

@dmanubens @ jgarcia @ jlope2 

François

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Oct 14, 2016, 14:18

I think this task has been done by the operations department.

It seems that they've replace the ```TASKS = 16``` too...

We're working on it, thanks!

**Comment by kinow** [comment]
In GitLab by @dmanubens on Oct 14, 2016, 15:29

Hi @fmassonn yes the `sed` for correcting es/auto-ecearth3#80 was wrong. Now it should be fixed.
