### ISSUE TITLE
autosubmit 3.7.5 is not backward-compatible with experiments created with autosubmit 3.6.0

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#217]
In GitLab by @etiennesky on Nov 25, 2016, 16:48

I created the experiment with autosubmit-3.6.0 and when using version 3.7.5, I cannot do operation on the experiment, even after running autosubmit create with the new autosubmit version.

Here is the error

```
etourign@ bscearth346:/esnas/autosubmit/a0af/conf> module load autosubmit/3.7.5-foss-2015a-Python-2.7.9

The following have been reloaded with a version change:
  1) autosubmit/3.6.0-foss-2015a-Python-2.7.9 => autosubmit/3.7.5-foss-2015a-Python-2.7.9

etourign@ bscearth346:/esnas/autosubmit/a0af/conf> autosubmit create a0af
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
autosubmit_a0af.conf OK
platforms_a0af.conf OK
jobs_a0af.conf OK
expdef_a0af.conf  OK
Configuration files OK

Using project folder: /esnas/autosubmit/a0af/proj
Loading parameters...

Creating joblist...
Creating jobs...
Adding dependencies...
Removing redundant dependencies...

Saving joblist...

Ploting joblist...
Plotting...
Plot created at /esnas/autosubmit/a0af/plot/a0af_20161125_1645.pdf
kioclient(27651) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-excel.sheet.binary.macroEnabled.12" 
kioclient(27651) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-excel.addin.macroEnabled.12" 
kioclient(27651) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-powerpoint.slideshow.macroEnabled.12" 
kioclient(27651) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-excel.sheet.macroEnabled.12" 
kioclient(27651) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-powerpoint.presentation.macroEnabled.12" 
kioclient(27651) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-word.template.macroEnabled.12" 
kioclient(27651) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-excel.template.macroEnabled.12" 
kioclient(27651) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-powerpoint.template.macroEnabled.12" 
kioclient(27651) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-word.document.macroEnabled.12" 
kioclient(27651) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-powerpoint.slide.macroEnabled.12" 

Job list created succesfully
Remember to MODIFY the MODEL config files!
etourign@ bscearth346:/esnas/autosubmit/a0af/conf> autosubmit refresh a0af
[CRITICAL] Unhandled exception on Autosubmit: AutosubmitConfig instance has no attribute '_exp_parser'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.7.5-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.5-py2.7.egg/autosubmit/autosubmit.py", line 361, in parse_args
    return Autosubmit.refresh(args.expid, args.model_conf, args.jobs_conf)
  File "/shared/earth/software/autosubmit/3.7.5-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.5-py2.7.egg/autosubmit/autosubmit.py", line 1451, in refresh
    if not as_conf.check_expdef_conf():
  File "/shared/earth/software/autosubmit/3.7.5-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.5-py2.7.egg/autosubmit/config/config_common.py", line 340, in check_expdef_conf
    parser = self._exp_parser
AttributeError: AutosubmitConfig instance has no attribute '_exp_parser'
```

**Comment by kinow** [comment]
In GitLab by @etiennesky on Nov 25, 2016, 16:59

closing as it is a duplicate of #211 which has been solved!
