### ISSUE TITLE
Long experiments with many jobs: autosubmit run fails.

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#221]
In GitLab by @fmassonn on Dec 15, 2016, 23:11

Hi @ jlope2 and @dmanubens 

One month ago I started to run an experiment `a0dc` over 1974-2015 with monthly chunks (i.e., a total of 504 chunks to be run). The experiment comprises 25 ensemble members. Initially, I inadvertently asked to run 120 chunks. This experiment has successfully finished. Now I would like to run the remaining 384 chunks. To this end, I simply re-created the experiment by changing NUMCHUNKS to 504,  re-covered the experiment, put the restarts of chunk 119 at the right place, etc.

The problem I have now is related to autosubmit itself:
- I have been able to create the experiment
- But I can't do an `autosubmit monitor`, this just takes too long. I get this message:

```
Getting job list...
Plotting...
^[[31m[CRITICAL] Unhandled exception on Autosubmit: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 294, in parse_args
    args.filter_type, args.hide)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 802, in monitor
    monitor_exp.generate_output(expid, jobs, file_format, not hide)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/monitor/monitor.py", line 169, in generate_output
    graph = self.create_tree_list(expid, joblist)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/monitor/monitor.py", line 125, in create_tree_list
    self._add_children(job, exp, node_job)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/monitor/monitor.py", line 148, in _add_children
    self._add_children(child, exp, node_child)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/monitor/monitor.py", line 148, in _add_children
    self._add_children(child, exp, node_child)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/monitor/monitor.py", line 148, in _add_children
    self._add_children(child, exp, node_child)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/monitor/monitor.py", line 148, in _add_children
    self._add_children(child, exp, node_child)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/monitor/monitor.py", line 148, in _add_children
    self._add_children(child, exp, node_child)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/monitor/monitor.py", line 148, in _add_children
    self._add_children(child, exp, node_child)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```
I have tried  to filter the results by only showing the `READY` jobs, that works, but this command can only be executed through a SBATCH (otherwise, the command is killed because it takes too long).

- I can't run autosubmit. When doing `autosubmit run a0dc` I get this output, then the process stops and nothing happens:

```
fmassonn@ bscesautosubmit01: ~/logs/autosubmit >> tail -f log_a0dc_2016.12.15_19h42m13s_bscesautosubmit01
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
autosubmit_a0dc.conf OK
platforms_a0dc.conf OK
jobs_a0dc.conf OK
expdef_a0dc.conf  OK
Configuration files OK

Starting job submission...
```

So I'm in the very uncomfortable situation of not being able to run my experiment... Could you help?

Thanks,

François

**Comment by kinow** [comment]
In GitLab by @fmassonn on Dec 19, 2016, 13:59

Could @dmanubens or @ jlope2 try to replicate my error? That would simply mean to run autosubmit on `a0dc` and see if the process is also interrupted.

If you have the same problem (i.e. unable to run this experiment), should I split my experiment in sub-experiments? Can you confirm this?

Thanks!

François

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Dec 20, 2016, 10:47

Hi @fmassonn,

As I said you, this problems are quite hard to solve.

However we're working to provide you a solution. The approach will be by the splitting way.

Thanks!

**Comment by kinow** [comment]
In GitLab by @dmanubens on Dec 20, 2016, 17:52

Hi @fmassonn , @ jlope2 has introduced a change in autosubmit in which we inculde a new variable in `expdef.conf`called `CHUNKINI` defualting to 1. This will allow you to set it to `CHUNKINI=120` and create your experiment starting from chunk 120 onwards. Additionally he is working in a fix for #150 since rerun feature was broken after adding synchronization. Note that a rerun of all members and chunks [120-504] would also work for you. 
When testing we would like you to check also the new LSF arrays feature. See #223
Best regards

**Comment by kinow** [comment]
In GitLab by @fmassonn on Dec 20, 2016, 17:55

Dear @dmanubens 

Thanks a lot for fixing this. 

Should I then test these changes in a virtual environment? Can you just remind me how to do this? Or is it already included in the default autosubmit version?

I'm happy to test the LSF feature, but can't do it on this experiment because this one is running and is for production. I'll create a new one.

François

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Dec 20, 2016, 18:53

Hi @fmassonn,

This commit: https://earth.bsc.es/gitlab/es/autosubmit/commit/1322ac346129601afb227a19618ec156138ee5a6 contains the changes needed to use the mentioned ```CHUNKINI``` configuration option.

However, you have to be aware that this one also contains the LSF arrays feature, which is enabled by default and can't be disabled (by the moment).
This only should affect in the way the jobs are sent to MareNostrum, but if you worry about that, we can release a new 3.7.X version with the ```CHUNKINI````feature and w/o arrays.

Do you consider this necessary? Or you can try with this one?

Thanks!

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Dec 20, 2016, 18:59

Here you can see how to test this version in a Python ```virtualenv```:

https://earth.bsc.es/gitlab/es/autosubmit/issues/148

We will add this into the documentation soon.

**Comment by kinow** [comment]
In GitLab by @fmassonn on Dec 21, 2016, 17:45

Hi @ jlope2 ,

I would prefer not to run an autosubmit version that has both the `CHUNKINI` new feature __and__ the LSF, because if a problem arises I won't know where it could potentially come from. I think it's safer to separate the two upgrades from one another.

François

**Comment by kinow** [comment]
In GitLab by @fmassonn on Dec 21, 2016, 17:50

Mentioned in issue es/Experiments#118

**Comment by kinow** [comment]
In GitLab by @fmassonn on Dec 22, 2016, 10:44

As explained above, I could not run a large number of chunks by doing a classic
```
nohup autosubmit run a0dc >& log &
```
because the job would be killed after about 10 minutes: the end of the log file looked like:
```
Checking configuration files...
autosubmit_a0dc.conf OK
platforms_a0dc.conf OK
jobs_a0dc.conf OK
expdef_a0dc.conf  OK
Configuration files OK

Starting job submission...
```
and then nothing happens.

I found a temporary solution, until the fixes above are separately implemented.

The "trick" is to run autosubmit inside a bash script that is submitted as a job itself.

```
#!/bin/bash
#SBATCH -n 1
#SBATCH -t 120:00:00
#SBATCH -J autosubmit
#SBATCH -o slurm_as-%j.out
#SBATCH -e slurm_as-%j.err

#autosubmit create a0dc -np
#autosubmit recovery -s -all a0dc
autosubmit run a0dc
```

and then do

```
sbatch ${FILE}.bash
```

Requesting a long run time (here put to 5 days) is necessary, otherwise the "run" command will stop.

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Dec 23, 2016, 16:51

Hi @fmassonn,

The next version (3.7.7) of Autosubmit is now available from both ```pip``` and ```module```.

This version does not contain any feature related with jobs wrappers so you can  try it.

You can try to configure a ```CHUNKINI``` option on the ```expdef.conf``` file in order to split your experiments.

Any other suggestion will be appreciated.

Thanks!

**Comment by kinow** [comment]
In GitLab by @dmanubens on Oct 25, 2017, 12:06

closed

**Comment by kinow** [comment]
In GitLab by @dmanubens on Nov 27, 2018, 16:07

removed milestone
