### ISSUE TITLE
MPMD jobs ECMWF cca

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#226]
In GitLab by @dmanubens on Dec 20, 2016, 18:21

In the past we could specify following geometry in reservations (instead of single number SPMD):
```
[SIM]
FILE = runtime/autosubmit/ece-ifs+nemo.sh
DEPENDENCIES = REMOTE_SETUP SIM-1
RUNNING = chunk
WALLCLOCK = 00:20
#PROCESSORS = 504
PROCESSORS = 144:288:1:1
#THREADS = 1
THREADS = 1:1:1:1
TASKS = 36

```
With above conf the following error raises:
```
Jobs ready for cca-intel: 1
Jobs to submit: 1
[ERROR] cca-intel submission failed
```
Similarly check fails:
```
dmanuben@ bscearth309:~/debug/autosubmit/a017> autosubmit check a017

Checking configuration files...
autosubmit_a017.conf OK
platforms_a017.conf OK
jobs_a017.conf OK
expdef_a017.conf  OK
Configuration files OK

Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
[CRITICAL] Unhandled exception on Autosubmit: invalid literal for int() with base 10: '144:288:1:1'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.8.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.8.0-py2.7.egg/autosubmit/autosubmit.py", line 340, in parse_args
    return Autosubmit.check(args.expid)
  File "/shared/earth/software/autosubmit/3.8.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.8.0-py2.7.egg/autosubmit/autosubmit.py", line 1084, in check
    job.update_parameters(as_conf, job_list.parameters)
  File "/shared/earth/software/autosubmit/3.8.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.8.0-py2.7.egg/autosubmit/job/job.py", line 556, in update_parameters
    self.processors = as_conf.get_processors(self.section)
  File "/shared/earth/software/autosubmit/3.8.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.8.0-py2.7.egg/autosubmit/config/config_common.py", line 146, in get_processors
    return int(AutosubmitConfig.get_option(self.jobs_parser, section, 'PROCESSORS', 1))
ValueError: invalid literal for int() with base 10: '144:288:1:1'
```

The option should be reintroduced to avoid problems in the future.

**Comment by kinow** [comment]
In GitLab by @dmanubens on Dec 20, 2016, 18:22

Mentioned in issue es/auto-ecearth3#133

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Dec 20, 2016, 18:45

@dmanubens, if we change the ```PROCESSORS```  type by an string, what do you consider a serial job?  which has exactly "1" processors?

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Dec 23, 2016, 16:47

Implemented @ 3dadfd3efa665dc897e5bb43a45c2af6723e48bb

**Comment by kinow** [comment]
In GitLab by @fmassonn on Jan 24, 2017, 14:49

Hi, I have had the same issue here:

```
fmassonn@ bscesautosubmit01: /esnas/autosubmit/a0f1/conf >> autosubmit -v
3.7.7

fmassonn@ bscesautosubmit01: /esnas/autosubmit/a0f1/conf >> autosubmit create a0f1
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
autosubmit_a0f1.conf OK
platforms_a0f1.conf OK
jobs_a0f1.conf OK
expdef_a0f1.conf  OK
Configuration files OK

Cloning develop-nemo3.6-standalone http://earth.bsc.es/gitlab/es/auto-nemo.git into /esnas/autosubmit/a0f1/proj
Cloning into 'model'...
Username for 'http://earth.bsc.es': fmassonnet
Password for 'http://fmassonnet@ earth.bsc.es':
remote: Counting objects: 931, done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 931 (delta 26), reused 0 (delta 0)
Receiving objects: 100% (931/931), 219.98 KiB | 0 bytes/s, done.
Resolving deltas: 100% (529/529), done.
Checking connectivity... done.
Cloning into 'ocean_diagnostics'...
remote: Counting objects: 2898, done.
remote: Compressing objects: 100% (2467/2467), done.
remote: Total 2898 (delta 2105), reused 549 (delta 390)
Receiving objects: 100% (2898/2898), 2.86 MiB | 1.96 MiB/s, done.
Resolving deltas: 100% (2105/2105), done.
Checking connectivity... done.
Cloning into 'plugins'...
remote: Counting objects: 15528, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 15528 (delta 5), reused 0 (delta 0)
Receiving objects: 100% (15528/15528), 22.61 MiB | 1.68 MiB/s, done.
Resolving deltas: 100% (5179/5179), done.
Checking connectivity... done.
Cloning into 'sources-nemo'...
Username for 'https://earth.bsc.es': fmassonnet
Password for 'https://fmassonnet@ earth.bsc.es':
remote: Counting objects: 47922, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 47922 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (47922/47922), 816.29 MiB | 6.04 MiB/s, done.
Resolving deltas: 100% (37864/37864), done.
Checking connectivity... done.
Cloning into 'sources-xios'...
remote: Counting objects: 901, done.
remote: Compressing objects: 100% (515/515), done.
remote: Total 901 (delta 396), reused 882 (delta 380)
Receiving objects: 100% (901/901), 4.52 MiB | 4.74 MiB/s, done.
Resolving deltas: 100% (396/396), done.
Checking connectivity... done.
Cloning into 'specs2cmor'...
remote: Counting objects: 3585, done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 3585 (delta 19), reused 0 (delta 0)
Receiving objects: 100% (3585/3585), 67.98 MiB | 5.84 MiB/s, done.
Resolving deltas: 100% (2568/2568), done.
Checking connectivity... done.
Loading parameters...
[CRITICAL] Unhandled exception on Autosubmit: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/autosubmit.py", line 342, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/autosubmit.py", line 1676, in create
    chunk_ini = as_conf.get_chunk_ini()
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/config/config_common.py", line 663, in get_chunk_ini
    return int(self.get_option(self._exp_parser, 'experiment', 'CHUNKINI', 1))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by kinow** [comment]
In GitLab by @dmanubens on Feb 21, 2017, 14:42

I am reopening this issue, because would need to  follow the same strategy for`THREADS` variable as has been implemented for `PROCESSORS`.

With version 3.7.7 I have the following:
```
Jobs ready for cca-intel: 1
Jobs to submit: 1
[CRITICAL] Unhandled exception on Autosubmit: invalid literal for int() with base 10: '1:1:1:1'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/autosubmit.py", line 324, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/autosubmit.py", line 677, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test):
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/autosubmit.py", line 730, in submit_ready_jobs
    job.update_parameters(as_conf, job_list.parameters)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/job/job.py", line 557, in update_parameters
    self.threads = as_conf.get_threads(self.section)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/config/config_common.py", line 156, in get_threads
    return int(AutosubmitConfig.get_option(self.jobs_parser, section, 'THREADS', 1))
ValueError: invalid literal for int() with base 10: '1:1:1:1'
```

**Comment by kinow** [comment]
In GitLab by @dmanubens on Feb 22, 2017, 13:15

Hi, It seems that we'll need also the same for `TASKS`.

More info in es/auto-ecearth3#133

**Comment by kinow** [comment]
In GitLab by @dmanubens on Apr 12, 2017, 18:44

Mentioned in commit 04eba8fb617ebb0650368b69519eae1b5e215960

**Comment by kinow** [comment]
In GitLab by @dmanubens on Aug 29, 2017, 12:06

removed milestone

**Comment by kinow** [comment]
In GitLab by @dmanubens on Aug 29, 2017, 12:07

closed
