### ISSUE TITLE
Autosubmit monitor error

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#230]
In GitLab by @fmassonn on Dec 28, 2016, 22:00

Hello,

Is it possible that since the release of 3.7.0, the command `autosubmit monitor` has a problem?:

```
fmassonn@ bscesautosubmit01: ~ >> autosubmit monitor a0d6
Getting job list...

Checking configuration files...
autosubmit_a0d6.conf OK
platforms_a0d6.conf OK
jobs_a0d6.conf OK
expdef_a0d6.conf  OK
Configuration files OK

Creating jobs...
Loading JobList
[CRITICAL] Unhandled exception on Autosubmit: in constructor for Job: __init__() takes exactly 5 arguments (1 given)
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/autosubmit.py", line 332, in parse_args
    args.filter_type, args.hide)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/autosubmit.py", line 787, in monitor
    job_list = Autosubmit.load_job_list(expid, as_conf)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/autosubmit.py", line 2262, in load_job_list
    as_conf.get_default_job_type(), False)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/job/job_list.py", line 130, in generate
    jobs_data = {str(row[0]): row for row in self.load()}
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/job/job_list.py", line 509, in load
    return self._persistence.load(self._persistence_path, self._persistence_file)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/job/job_list_persistence.py", line 72, in load
    return pickle.load(fd)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 1070, in load_inst
    self._instantiate(klass, self.marker())
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 1060, in _instantiate
    value = klass(*args)
TypeError: in constructor for Job: __init__() takes exactly 5 arguments (1 given)
```

Or is the problem on my side? (I have the same problem for other experiments)

François

**Comment by kinow** [comment]
In GitLab by @obellprat on Jan 3, 2017, 10:28

Same problem here!

@dmanubens  @ jlope2

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jan 3, 2017, 11:14

Did you run the ```create``` command with the new version?

Thanks!

**Comment by kinow** [comment]
In GitLab by @fmassonn on Jan 3, 2017, 11:24

I personally did, but not on `a0d6` (on `a0dc` for which I had the same error)

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jan 3, 2017, 12:01

Hi @fmassonn,

Can you paste here the error of monitoring the ```a0dc``` after doing an ```autosubmit create a0dc```.

Thanks!

**Comment by kinow** [comment]
In GitLab by @fmassonn on Jan 3, 2017, 12:49

I can't create a0dc, because this experiment is running.

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jan 3, 2017, 13:03

And are you sure that you have ```create``` and ```run``` the experiment with the version 3.7.7.

Otherwise you have to monitor the experiment with the same version you created and run it.

**Comment by kinow** [comment]
In GitLab by @fmassonn on Jan 3, 2017, 13:31

OK, that's maybe the problem. I'll keep this in mind anyway. Thanks!

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jan 24, 2017, 12:03

I think we can close this issue (not related with performance).

Open another one if you consider it necessarily.

Thanks!
