### ISSUE TITLE
Error on re-run a experiment

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#231]
In GitLab by @charlio86 on Dec 30, 2016, 11:56

I have stopped my experiment and then do the run again to continue with it (in bscesautosubmit01.bsc.es).

It generate this error message:
[CRITICAL] Unhandled exception on Autosubmit: [Errno 21] Is a directory: '/esnas/autosubmit/a029/tmp/LOG_a029/'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.7.6-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.6-py2.7.egg/autosubmit/autosubmit.py", line 324, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.7.6-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.6-py2.7.egg/autosubmit/autosubmit.py", line 660, in run_experiment
    as_conf.get_copy_remote_logs() == 'true'):
  File "/shared/earth/software/autosubmit/3.7.6-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.6-py2.7.egg/autosubmit/job/job.py", line 434, in update_status
    self.get_platform().get_logs_files(self.expid, self.out_filename, self.err_filename)
  File "/shared/earth/software/autosubmit/3.7.6-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.6-py2.7.egg/autosubmit/platforms/platform.py", line 176, in get_logs_files
    self.get_files([job_out_filename, job_err_filename], False, 'LOG_{0}'.format(exp_id))
  File "/shared/earth/software/autosubmit/3.7.6-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.6-py2.7.egg/autosubmit/platforms/platform.py", line 152, in get_files
    self.get_file(filename, must_exist, relative_path)
  File "/shared/earth/software/autosubmit/3.7.6-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.6-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 117, in get_file
    os.remove(local_path)
OSError: [Errno 21] Is a directory: '/esnas/autosubmit/a029/tmp/LOG_a029/'

To fix it I have changed the "LOG_a029" folder name and it runs perfectly

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jan 2, 2017, 11:13

Same as https://earth.bsc.es/gitlab/es/autosubmit/issues/212

Already fixed in Autosubmit 3.7.7.

Thanks!
