### ISSUE TITLE
Autosubmit stats error

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#233]
In GitLab by @obellprat on Jan 20, 2017, 12:26

Hi,

I get the following problem when running the statistics in autosubmit (v.3.7.7). @ jlope2 could you have  a look?

```
obellpra@ bscearth315:~/R/eval_nudging$ module purge
obellpra@ bscearth315:~/R/eval_nudging$ module load autosubmit
obellpra@ bscearth315:~/R/eval_nudging$ autosubmit stats a03l
Loading jobs...

Checking configuration files...
autosubmit_a03l.conf OK
platforms_a03l.conf OK
jobs_a03l.conf OK
expdef_a03l.conf  OK
Configuration files OK

Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Plotting stats...
Creating stats file
[CRITICAL] Unhandled exception on Autosubmit: time data 'FAILED' does not match format '%Y%m'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/autosubmit.py", line 334, in parse_args
    return Autosubmit.statistics(args.expid, args.filter_type, args.filter_period, args.output, args.hide)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/autosubmit.py", line 919, in statistics
    monitor_exp.generate_output_stats(expid, job_list, file_format, period_ini, period_fi, not hide)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/monitor/monitor.py", line 216, in generate_output_stats
    self.create_bar_diagram(expid, joblist, output_file, period_ini, period_fi)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/monitor/monitor.py", line 304, in create_bar_diagram
    end_times = job.check_retrials_end_time()
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/job/job.py", line 415, in check_retrials_end_time
    return self._get_from_total_stats(2)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/job/job.py", line 378, in _get_from_total_stats
    lst.append(parse_date(fields[index]))
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/date/chunk_date_lib.py", line 293, in parse_date
    return datetime.datetime.strptime(string_date, "%Y%m")
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'FAILED' does not match format '%Y%m'
```

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jan 24, 2017, 12:01

I think this error is due to a backwards compatibility between Autosubmit versions.
So, those jobs that haven't been run with the most recent versions are don't have the properly stats files.

You can use the filter options in order to avoid this kind of problems.

Thanks!
