### ISSUE TITLE
Autosubmit 3.7.7 ERROR: Transitive reduction only uniquely defined on directed acyclic graphs.

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#246]
In GitLab by @xyepes on Mar 8, 2017, 14:58

Hello,

I was trying to create dependencies between jobs of the same type that have a frequency of 6, but I got an error. The configuration is the following:

`[LOCALPOST]
FILE = templates/common/common.localpost
PLATFORM = moore
DEPENDENCIES = TRANSFER LOCALPOST-1
RUNNING = chunk
FREQUENCY = 6`

And the error is this one:

`[CRITICAL] Unhandled exception on Autosubmit: Transitive reduction only uniquely defined on directed acyclic graphs.
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/autosubmit.py", line 342, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/autosubmit.py", line 1696, in create
    as_conf.get_default_job_type())
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/job/job_list.py", line 137, in generate
    self.update_genealogy(new)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/job/job_list.py", line 611, in update_genealogy
    self.graph = transitive_reduction(self.graph)
  File "/shared/earth/software/autosubmit/3.7.7-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.7.7-py2.7.egg/autosubmit/job/job_utils.py", line 11, in transitive_reduction
    raise NetworkXError("Transitive reduction only uniquely defined on directed acyclic graphs.")
NetworkXError: Transitive reduction only uniquely defined on directed acyclic graphs.`

I've been investigating the problem and I've realized that if there wasn't the check to avoid cycles in the workflow, it would happen things like this plot:

[workflow_with_cycles](https://earth.bsc.es/gitlab/es/autosubmit/uploads/a9b33a8f41c84e4479e752df4024e6d6/workflow_with_cycles.png)

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Mar 8, 2017, 15:07

Thanks a lot @xyepes !

I will work on it!

**Comment by kinow** [comment]
In GitLab by @ lbatista on Jul 20, 2018, 17:49

Fixed in 3.10

**Comment by kinow** [comment]
In GitLab by @ lbatista on Jul 20, 2018, 17:49

closed

**Comment by kinow** [comment]
In GitLab by @ebergas on Sep 30, 2019, 11:30

mentioned in issue auto-ecearth3#1049
