### ISSUE TITLE
SVN project creation fails

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#248]
In GitLab by @dmanubens on Mar 21, 2017, 12:24

```
dmanubens@galadriel:~/autosubmit/a003$ autosubmit create a003
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
autosubmit_a003.conf OK
platforms_a003.conf OK
jobs_a003.conf OK
expdef_a003.conf  OK
Configuration files OK

Checking out revision 4090 https://svn.ec-earth.org/ecearth3/trunk/runtime/autosubmit into /home/dmanubens/autosubmit/a003/proj
[CRITICAL] Unhandled exception on Autosubmit: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/autosubmit/autosubmit.py", line 342, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output)
  File "/usr/local/lib/python2.7/dist-packages/autosubmit/autosubmit.py", line 1652, in create
    if not Autosubmit._copy_code(as_conf, expid, project_type, False):
  File "/usr/local/lib/python2.7/dist-packages/autosubmit/autosubmit.py", line 1753, in _copy_code
    Log.debug("{0}" % output)
TypeError: not all arguments converted during string formatting
```

expdef:

```
# If PROJECT_TYPE is not svn, no need to change
[svn]
# type = STRING, help = 'https://svn.ec-earth.org/ecearth3'
PROJECT_URL = https://svn.ec-earth.org/ecearth3/trunk/runtime/autosubmit
# Select revision number. NUMERIC = 1778
PROJECT_REVISION = 4090

```

**Comment by kinow** [comment]
In GitLab by @dmanubens on Mar 21, 2017, 12:34

It seems that this line (autosubmit.py, 1753) should be changed:
```
Log.debug("{0}" % output)
```
to 
```
Log.debug("{0}", output)
```

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Mar 21, 2017, 13:00

Mentioned in commit b28bf1d1e1624509a2cc92988273bfe2671c6539

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Mar 21, 2017, 13:01

Hi,

I've already done this change.

Thanks a lot @dmanubens!

**Comment by kinow** [comment]
In GitLab by @dmanubens on Aug 29, 2017, 12:04

removed milestone
