### ISSUE TITLE
Not all valid YAML files are supported by Autosubmit at the moment

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit#2511]
In GitLab by @kinow on May 31, 2023, 12:50

( This is a template for bug reports. Please fill in the relevant information and delete the rest. )

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

Latest & latest autosubmit4-config-parser

### Expid affected(If applicable)

NA

### Which task has issues? Where is the log(If applicable)

NA

### Summary

See linked ticket in the parser: https://earth.bsc.es/gitlab/ces/autosubmit4-config-parser/-/issues/3

Not all valid YAML files are supported by Autosubmit. This could be an issue, for example, if users are assuming they can use existing YAML configuration files, and if those files use something like an array with dictionaries.

Found while working on the RO-Crate issue this morning autosubmit#929 

### Steps to reproduce

Use anything like this in an Autosubmit configuration:

```yaml
ROCRATE:
  INPUT:
    - name: "DATELIST"
      value: "%EXPERIMENT.DATELIST%"
      additionalType: "String"
      valueRequired: "True"
```

### What is the current bug behavior?

```bash
(autosubmit4) kinow@ranma:~/Development/python/workspace/autosubmit4-config-parser$ autosubmit archive --rocrate a008 && unzip -p ~/autosubmit/a008/rocrate.zip ro-crate-metadata.json > ~/autosubmit/a008/ro-crate-metadata.json && subl ~/autosubmit/a008/ro-crate-metadata.json
Autosubmit is running with 4.0.0b
[ERROR] Trace: unhashable type: 'dict'
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 713, in parse_args
    return Autosubmit.rocrate(args.expid)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 4231, in rocrate
    as_configuration.reload(True)
  File "/home/kinow/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/config/configcommon.py", line 1382, in reload
    custom_conf_pre = self.load_custom_config_section({}, filenames_to_load["PRE"])
  File "/home/kinow/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/config/configcommon.py", line 1338, in load_custom_config_section
    current_data_pre,current_data_post = self.load_custom_config(current_data, filenames_to_load)
  File "/home/kinow/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/config/configcommon.py", line 1305, in load_custom_config
    current_data_pre,current_data_post = self.load_config_folder(copy.deepcopy(current_data),filename)
  File "/home/kinow/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/config/configcommon.py", line 612, in load_config_folder
    return self.load_custom_config(current_data, filenames_to_load)
  File "/home/kinow/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/config/configcommon.py", line 1317, in load_custom_config
    current_data_pre = self.unify_conf(current_data_pre,self.load_custom_config_section(copy.deepcopy(current_data), filenames_to_load_level["PRE"]))
  File "/home/kinow/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/config/configcommon.py", line 1338, in load_custom_config_section
    current_data_pre,current_data_post = self.load_custom_config(current_data, filenames_to_load)
  File "/home/kinow/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/config/configcommon.py", line 1305, in load_custom_config
    current_data_pre,current_data_post = self.load_config_folder(copy.deepcopy(current_data),filename)
  File "/home/kinow/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/config/configcommon.py", line 612, in load_config_folder
    return self.load_custom_config(current_data, filenames_to_load)
  File "/home/kinow/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/config/configcommon.py", line 1310, in load_custom_config
    current_data = self.substitute_dynamic_variables(self.unify_conf(self.substitute_dynamic_variables(current_data), self.load_config_file(current_data,filename)))
  File "/home/kinow/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/config/configcommon.py", line 583, in load_config_file
    return self.unify_conf(current_folder_data,self.deep_normalize(new_file.data))
  File "/home/kinow/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/config/configcommon.py", line 657, in unify_conf
    current_data = self.deep_update(current_data, new_data)
  File "/home/kinow/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/config/configcommon.py", line 490, in deep_update
    tmp = self.deep_update(unified_config.get(key, {}), val)
  File "/home/kinow/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/config/configcommon.py", line 494, in deep_update
    if current_list != set(val):
TypeError: unhashable type: 'dict'
 [CRITICAL] Noneunhashable type: 'dict'
Unhandled error: If you see this message, please report it in Autosubmit's GitLab project
```

The linked issue in autosubmit4-config-parser has more information.

### What is the expected correct behavior?

Either support every valid YAML file, or document & warn users about what is supported or not.

### Relevant logs and/or screenshots(if applicable)

Done above, and also in the linked issue in autosubmit4-config-parser.

### Any other relevant information(if applicable)

()

**Comment by kinow** [comment]
Updated because I linked elsewhere. Nothing to see here 👍
