### ISSUE TITLE
Integer conversion problem when calculating CPU consumption for regression test on ecmwf

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#280]
In GitLab by @ lbatista on Oct 17, 2017, 10:11

Running the regression test for ecmwf with paramiko, when creating the stats file it tries to convert the `PROCESSORS = 24:72:1:1` defined in the job GEO_REMOTE to integer, raising an exception. In this case it needs to be parsed as string before calculating the CPU consumption.

Stack trace:

```
2017-10-17 09:31:58,558 Creating stats file
[CRITICAL] 2017-10-17 09:31:58,573 Unhandled exception on Autosubmit: invalid literal for int() with base 10: '24:72:1:1'
Traceback (most recent call last):
  File "/home/Earth/lbatista/PycharmProjects/autosubmit/autosubmit/autosubmit.py", line 344, in parse_args
    return Autosubmit.statistics(args.expid, args.filter_type, args.filter_period, args.output, args.hide)
  File "/home/Earth/lbatista/PycharmProjects/autosubmit/autosubmit/autosubmit.py", line 910, in statistics
    monitor_exp.generate_output_stats(expid, job_list, file_format, period_ini, period_fi, not hide)
  File "/home/Earth/lbatista/PycharmProjects/autosubmit/autosubmit/monitor/monitor.py", line 217, in generate_output_stats
    create_bar_diagram(expid, joblist, self.get_general_stats(expid), output_file, period_ini, period_fi)
  File "/home/Earth/lbatista/PycharmProjects/autosubmit/autosubmit/monitor/diagram.py", line 48, in create_bar_diagram
    exp_stats = ExperimentStats(jobs_list, period_ini, period_fi)
  File "/home/Earth/lbatista/PycharmProjects/autosubmit/autosubmit/experiment/statistics.py", line 59, in __init__
    self._calculate_stats()
  File "/home/Earth/lbatista/PycharmProjects/autosubmit/autosubmit/experiment/statistics.py", line 108, in _calculate_stats
    self._cpu_consumption += self.run[i] * int(processors)
ValueError: invalid literal for int() with base 10: '24:72:1:1'
```

**Comment by kinow** [comment]
In GitLab by @ lbatista on Oct 23, 2017, 16:59

mentioned in commit 9cb137de5714c050011866352b07059e680b8425

**Comment by kinow** [comment]
In GitLab by @ lbatista on Oct 23, 2017, 17:01

closed via commit 0722fe8cade827e4b636b7cee794ff756162df80

**Comment by kinow** [comment]
In GitLab by @ lbatista on Oct 23, 2017, 17:01

closed via commit 9cb137de5714c050011866352b07059e680b8425

**Comment by kinow** [comment]
In GitLab by @ lbatista on Oct 23, 2017, 17:01

closed via merge request !106

**Comment by kinow** [comment]
In GitLab by @ lbatista on Nov 13, 2017, 10:16

mentioned in commit 0722fe8cade827e4b636b7cee794ff756162df80
