### ISSUE TITLE
autosubmit "refuses" to change status

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#299]
In GitLab by @ rbernard on Feb 8, 2018, 13:09

Hi,
I'm trying to change status of a job in experiment a0ux and this happens:

autosubmit setstatus a0ux -fl "a0ux_18500101_fc0_1_SIM" -t WAITING -s
[CRITICAL] Unhandled exception on Autosubmit: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 366, in parse_args
    args.filter_chunks, args.filter_status, args.filter_type, args.hide)
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 1923, in set_status
    with portalocker.Lock(os.path.join(tmp_path, 'autosubmit.lock'), timeout=1):
  File "build/bdist.linux-x86_64/egg/portalocker/utils.py", line 195, in __enter__
    return self.acquire()
  File "build/bdist.linux-x86_64/egg/portalocker/utils.py", line 155, in acquire
    raise exceptions.LockException(exception)
LockException: [Errno 11] Resource temporarily unavailable

some jobs are in UNKNOWN status. The same happens when trying to change status of those.

thanks

Raffa

**Comment by kinow** [comment]
In GitLab by @ lbatista on Feb 8, 2018, 14:37

Hi @ rbernard this is an issue that happens every once in a while, and as far as we know, it's a problem with the portallocker library that we use (find more in https://earth.bsc.es/gitlab/es/autosubmit/issues/179). The solution in the mean time is removing the autosubmit.lock in the tmp folder of your project

**Comment by kinow** [comment]
In GitLab by @ lbatista on Jun 6, 2018, 15:06

closed
