### ISSUE TITLE
IOError: Failure marenostrum4 submission failed

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#301]
In GitLab by @ lbatista on Feb 9, 2018, 15:27

The following error happened in @ editomas a0vs experiment. We believe it was a problem when connecting to mn4.

`2018-02-08 18:53:15,072 /gpfs/scratch/pr1edr00/pr1edr02/a0vs/LOG_a0vs has been created on mn4_prace .
2018-02-08 18:53:33,387 Could not remove file /gpfs/scratch/pr1edr00/pr1edr02/a0vs/LOG_a0vs/a0vs_20120201_008_58_POST.cmd
[ERROR] 2018-02-08 18:53:33,487 Can not send file /esnas/autosubmit/a0vs/tmp/a0vs_20120201_008_58_POST.cmd to /gpfs/scratch/pr1edr00/pr1edr02/a0vs/LOG_a0vs/a0vs_20120201_008_58_POST.cmd
[ERROR] 2018-02-08 18:53:33,488 marenostrum4 submission failed
[CRITICAL] 2018-02-08 18:53:33,626 Unhandled exception on Autosubmit: Failure
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 334, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 692, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test):
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 730, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters)
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/job/job_packages.py", line 87, in submit
    self._send_files()
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/job/job_packages.py", line 115, in _send_files
    self.platform.send_file(self._job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 103, in send_file
    ftp.put(os.path.join(self.tmp_path, filename), os.path.join(self.get_files_path(), filename))
  File "build/bdist.linux-x86_64/egg/paramiko/sftp_client.py", line 669, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
  File "build/bdist.linux-x86_64/egg/paramiko/sftp_client.py", line 621, in putfo
    with self.file(remotepath, 'wb') as fr:
  File "build/bdist.linux-x86_64/egg/paramiko/sftp_client.py", line 327, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "build/bdist.linux-x86_64/egg/paramiko/sftp_client.py", line 729, in _request
    return self._read_response(num)
IOError: Failure
`

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 16:58

Need updated info about this issue, if this is still happening reopen this issue, please.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 16:58

closed
