### ISSUE TITLE
issue when trying to recover an experiment

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#309]
In GitLab by @mmenegoz on Feb 26, 2018, 13:44

Hi,

I do not manage to recover an experiment:

autosubmit recovery -all -s a0wx

I get:

Looking for COMPLETED files

CHANGED job 'a0wx_LOCAL_SETUP' status to COMPLETED

CHANGED job 'a0wx_REMOTE_SETUP' status to COMPLETED

CHANGED job 'a0wx_19900101_fc0_INI' status to COMPLETED

CHANGED job 'a0wx_19900101_fc0_1_SIM' status to COMPLETED

CHANGED job 'a0wx_19900101_fc0_2_SIM' status to WAITING

...

CHANGED job 'a0wx_19900101_fc0_CLEAN_MEMBER' status to WAITING
[CRITICAL] Unhandled exception on Autosubmit: Authentication failed.
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 348, in parse_args
    return Autosubmit.recovery(args.expid, args.noplot, args.save, args.all, args.hide)
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 1039, in recovery
    if job.platform.get_completed_files(job.name, 0):
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/platforms/platform.py", line 222, in get_completed_files
    if self.get_file('{0}_COMPLETED'.format(job_name), False):
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 136, in get_file
    if not self.connect():
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 81, in connect
    key_filename=self._host_config_id)
  File "build/bdist.linux-x86_64/egg/paramiko/client.py", line 307, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "build/bdist.linux-x86_64/egg/paramiko/client.py", line 519, in _auth
    raise saved_exception
AuthenticationException: Authentication failed.

Any idea?

**Comment by kinow** [comment]
In GitLab by @dmanubens on Feb 26, 2018, 15:23

Bonjour Martin,

Your experiment seems to be a copy of a @pablohe 's one. When you copied it the `platfroms_a0wx.conf` was taken from @pablohe experiment so the user for `moore` and `data_transfer` machine has to be changed by yours.

Does that help?

**Comment by kinow** [comment]
In GitLab by @mmenegoz on Feb 26, 2018, 15:54

Bonjour Mingu,

ça marche !

Merci, c'était bien l'erreur!

Bonne semaine

**Comment by kinow** [comment]
In GitLab by @mmenegoz on Feb 26, 2018, 15:54

closed
