### ISSUE TITLE
SSHException: Error reading SSH protocol banner in AS

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#320]
In GitLab by @Eleftheriaexarchou on Mar 22, 2018, 11:44

Hi @ lbatista  I have an issue with exp a0xi 

```
[ERROR] Scripts check failed
Running after failed scripts check is at your own risk!


1631 of 1903 jobs remaining (11:42)
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 1579, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 1706, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
[CRITICAL] Unhandled exception on Autosubmit: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 334, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 674, in run_experiment
    if prev_status != job.update_status(platform.check_job(job.id),
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 234, in check_job
    while not self.send_command(self.get_checkjob_cmd(job_id)) and retries >= 0:
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 281, in send_command
    if not self.connect():
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 81, in connect
    key_filename=self._host_config_id)
  File "build/bdist.linux-x86_64/egg/paramiko/client.py", line 265, in connect
    t.start_client()
  File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 406, in start_client
    raise e
SSHException: Error reading SSH protocol banner

```
which is also mentioned here 
https://earth.bsc.es/gitlab/es/auto-ecearth3/issues/491#note_19255

Also cannot login to bscearth000 , are those 2 related?

**Comment by kinow** [comment]
In GitLab by @ lbatista on Mar 22, 2018, 17:39

Hi @Eleftheriaexarchou in fact it seemed related to the problem in bscearth000. Has the problem happened again?

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on Mar 22, 2018, 17:54

closed

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on Mar 22, 2018, 17:54

I dont think so. OK thanks! I ll close the issue then.
