### ISSUE TITLE
Issue while plotting in exp a0yi with many chunks

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#321]
In GitLab by @ jacosta on Mar 22, 2018, 16:28

Hi,

I tried "autosubmit create a0yi" but it crashes when generating the plot with the following error: 

```

[CRITICAL] Unhandled exception on Autosubmit: Program terminated with status: -11. stderr follows: []
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 354, in parse_args
    return Autosubmit.create(args.expid, args.noplot, args.hide, args.output)
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 1800, in create
    monitor_exp.generate_output(expid, job_list.get_job_list(), output, not hide)
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/monitor/monitor.py", line 178, in generate_output
    graph.write_pdf(output_file)
  File "build/bdist.linux-x86_64/egg/pydotplus/graphviz.py", line 1810, in <lambda>
    prog=self.prog: self.write(path, format=f, prog=prog)
  File "build/bdist.linux-x86_64/egg/pydotplus/graphviz.py", line 1918, in write
    fobj.write(self.create(prog, format))
  File "build/bdist.linux-x86_64/egg/pydotplus/graphviz.py", line 2032, in create
    status, stderr_output))
InvocationException: Program terminated with status: -11. stderr follows: []

```

I think is due to the number of chunks because when I reduce them it works fine. 

Any clues?

Thanks in advance!

Juan

**Comment by kinow** [comment]
In GitLab by @ jacosta on Mar 22, 2018, 16:30

@ lbatista @dmanubens

**Comment by kinow** [comment]
In GitLab by @ jacosta on Mar 22, 2018, 18:06

Thanks @ lbatista, that would be quite helpful since I will neeed to make a series of exps with many chunks. Maybe a grouping option would do the job?

**Comment by kinow** [comment]
In GitLab by @ lbatista on Mar 22, 2018, 18:13

Yes, I think it's worth a try!

**Comment by kinow** [comment]
In GitLab by @ jacosta on Dec 5, 2018, 11:41

Hi @dbeltrankyl,

Yes thanks, I think we can close this issue now.

Juan
