### ISSUE TITLE
[CRITICAL] Unhandled exception on Autosubmit: [Errno 2] No such file or directory: '/esnas/autosubmit/ASlogs/20180322_150654_expid.log'

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#322]
In GitLab by @mcastril on Mar 22, 2018, 17:12

Hi,

Maybe this is a random error, but it would be good that this is reported and also how to proceed.

I created two experiments and the same time: 

```
autosubmit expid -y a0yi -H marenostrum4 -d "Copy of a0yi to test LIM3 timestep at 900s" 
autosubmit expid -y a0yi -H marenostrum4 -d "Copy of a0yi to test LIM3 timestep at 1800s"
```

The second one did it as expected, but the first one crashed:

```
mcastril@ bscearth339:~> autosubmit expid -y a0yi -H marenostrum4 -d "Copy of a0yi to test LIM3 timestep at 900s" 
[CRITICAL] Unhandled exception on Autosubmit: [Errno 2] No such file or directory: '/esnas/autosubmit/ASlogs/20180322_150654_expid.log'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 337, in parse_args
    args.operational) != ''
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 443, in expid
    Log.set_file(log_path)
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/bscearth.utils-0.5.2-py2.7.egg/bscearth/utils/log.py", line 141, in set_file
    os.remove(os.path.join(directory, files[0]))
OSError: [Errno 2] No such file or directory: '/esnas/autosubmit/ASlogs/20180322_150654_expid.log
```

I tried again:

```
mcastril@ bscearth339:~> autosubmit expid -y a0yi -H marenostrum4 -d "Copy of a0yi to test LIM3 timestep at 900s" 
The new experiment "a0yo" has been registered.
Copying previous experiment config directories
Experiment registered successfully
Remember to MODIFY the config files!
```

Seems that it worked now! But the experiment's folder is corrupted:

```
mcastril@ bscearth339:/esarchive/autosubmit/a0yo/conf> ll
total 621056
-rw-rw-r--+ 1 mcastril Earth 635633664 mar 22 16:56 auto-ecearth3.tar.gz
-rw-rw-r--+ 1 mcastril Earth       686 mar 22 16:56 autosubmit_a0yo.conf
-rw-rw-r--+ 1 mcastril Earth      2296 mar 22 16:56 expdef_a0yo.conf
-rw-rw-r--+ 1 mcastril Earth      1646 mar 22 16:55 jobs_a0yo.conf
-rw-rw-r--+ 1 mcastril Earth      1118 mar 22 16:55 platforms_a0yo.conf
-rw-rw-r--+ 1 mcastril Earth      5789 mar 22 16:55 proj_a0yo.conf
-rw-rw-r--+ 1 mcastril Earth         0 mar 22 16:55 sedUmsbsP

```

So it seems that instead of giving me another expid it gave me the first one that failed. Could I just untar `auto-ecearth3.tar.gz` and move the conf files to conf/ , or maybe better I create a brand new one?

@ lbatista @dmanubens

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 5, 2018, 17:13

closed
