### ISSUE TITLE
Workflow cannot run after experiment being recovered

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#337]
In GitLab by @mcastril on Jun 25, 2018, 14:59

I did `autosubmit refresh` to a17m experiment because I had to do some changes in the workflow (removing the FREQUENCY parameter from TRANSFER).

After recovered, I changed the status of SIM_9 to RUNNING, because it was already running when I stopped Autosubmit. When I type `autosubmit run` I see the following:

```
204 of 213 jobs remaining (14:34)
Job a17m_19900101_fc0_7_SIM is FAILED. Checking completed files to confirm the failure...
[WARNING] Job a17m_19900101_fc0_7_SIM completion check failed. There is no COMPLETED file
[CRITICAL] Unhandled exception on Autosubmit: [Errno 21] Is a directory: '/esarchive/autosubmit/a17m/tmp/LOG_a17m/'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 334, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 675, in run_experiment
    as_conf.get_copy_remote_logs() == 'true'):
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/job/job.py", line 515, in update_status
    self.platform.get_logs_files(self.expid, self.remote_logs)
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/platforms/platform.py", line 207, in get_logs_files
    self.get_files([job_out_filename, job_err_filename], False, 'LOG_{0}'.format(exp_id))
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/platforms/platform.py", line 184, in get_files
    self.get_file(filename, must_exist, relative_path)
  File "/shared/earth/software/autosubmit/3.9.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 133, in get_file
    os.remove(file_path)
OSError: [Errno 21] Is a directory: '/esarchive/autosubmit/a17m/tmp/LOG_a17m/'
```

About the SIM failing, after verifying it is still running in MN4, I suspected Autosubmit was not able to recognize the job. I verified in the log that:

```
204 of 213 jobs remaining (14:39)
2018-06-25 14:39:30,235 Sleep: 10
2018-06-25 14:39:30,235 Number of retrials: 0
2018-06-25 14:39:35,726 Command sacct -n -j 0 -o "State" in mn-pr1egi00 successful with out message:     FAILED
```
`/esarchive/autosubmit/a17m/tmp/20180625_143930_run.log`

I also checked if the jobid was inside the pkl file, but it isn't.

I did the same procedure (at least I think I did the same steps) with a twin experiment (the only difference is that this one is a standalone one, instead of coupled), called a17l, and it worked.

About the SIM, I can wait till it finishes and set it as COMPLETED. What is more worrysome is the exception given by Autosubmit.

@ lbatista @dmanubens

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 15:48

Hi @mcastril, do you know if this was solved? the label was 3.9.1 so I guess that was resolved in that version?

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 4, 2018, 16:14

Sincerely I don't know if it was. I rather think it was never reproduced.

Taking into account that this is a strange issue, and that it has not been reported again, I will close it.

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 4, 2018, 16:14

closed
