### ISSUE TITLE
fix for when autosubmit does not check for a long time the state of jobs

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#340]
In GitLab by @ editomas on Jul 6, 2018, 14:02

@ lbatista here are extracts from our emails on this issue:

I have seen this once before, when it had been hours without autosubmit
checking for the state of jobs in marenostrum (we had alternating jobs
running in mn4 and locally). If this happens, than there is this timeout
that you see on the log.
At the time we added a temporary solution which seemed to have worked,
but we didn't include it in the release.

The error message is:

```
ERROR:paramiko.transport:Exception: Key-exchange timed out waiting for key negotiation
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.11.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1614, in run
ERROR:paramiko.transport: self._channel_handler_table[ptype](chan, m)
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.11.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/channel.py", line 1048, in _handle_close
ERROR:paramiko.transport:    self.transport._send_user_message(m)
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.11.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1463, in _send_user_message
ERROR:paramiko.transport:    raise SSHException('Key-exchange timed out waiting for key negotiation')
ERROR:paramiko.transport:SSHException: Key-exchange timed out waiting for key negotiation
ERROR:paramiko.transport:
^[[31m[ERROR] Can not send command sacct -n -j 1906601 -o "State" to mn4_prace_fd: Key-exchange timed out waiting for key negotiation^[[0m^[[39m
^[[33m[WARNING] Retrying check job command: sacct -n -j 1906601 -o "State"^[[0m^[[39m
^[[31m[ERROR] Can not get job status for job id (1906601), retrying in 10 sec^[[0m^[[39m
```

**Comment by kinow** [comment]
In GitLab by @mcastril on Jul 23, 2019, 12:45

closed
