### ISSUE TITLE
can't use SPLITS = 1 in jobs.conf

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#351]
In GitLab by @pablohe on Sep 17, 2018, 18:12

I'm try to generalize the case for any type of experiment with CMORIZATION for (1,2,3...) months and need `SPLIT=1` for one month 

```
[CMORATM]
FILE = templates/ecearth3/ecearth3.cmoratm
DEPENDENCIES = SIM
WALLCLOCK = 1:00
RUNNING = chunk
THREADS = 4
NOTIFY_ON = FAILED COMPLETED
TASKS = 8
SPLITS = 1
THREADS = 4
```

but autosubmit crash, I don't know if I'm using in a wrong way.

```
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
platforms_t025.conf OK
jobs_t025.conf OK
autosubmit_t025.conf OK
expdef_t025.conf  OK
Configuration files OK

Using project folder: /esarchive/autosubmit/t025/proj
Loading parameters...

Creating the jobs list...
Creating jobs...
Adding dependencies...
[CRITICAL] Unhandled exception on Autosubmit: 'list' object has no attribute 'chunk'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.11.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.10.0-py2.7.egg/autosubmit/autosubmit.py", line 398, in parse_args
    args.expand_status, args.notransitive)
  File "/shared/earth/software/autosubmit/3.11.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.10.0-py2.7.egg/autosubmit/autosubmit.py", line 1945, in create
    as_conf.get_wrapper_type(), as_conf.get_wrapper_jobs(), notransitive=notransitive)
  File "/shared/earth/software/autosubmit/3.11.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.10.0-py2.7.egg/autosubmit/job/job_list.py", line 143, in generate
    self._add_dependencies(date_list, member_list, chunk_list, dic_jobs, jobs_parser, self.graph)
  File "/shared/earth/software/autosubmit/3.11.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.10.0-py2.7.egg/autosubmit/job/job_list.py", line 173, in _add_dependencies
    dependencies, graph)
  File "/shared/earth/software/autosubmit/3.11.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.10.0-py2.7.egg/autosubmit/job/job_list.py", line 225, in _manage_job_dependencies
    skip, (chunk, member, date) = JobList._calculate_dependency_metadata(job.chunk, chunk_list,
AttributeError: 'list' object has no attribute 'chunk'
```

**Comment by kinow** [comment]
In GitLab by @pablohe on Sep 17, 2018, 18:15

mentioned in commit auto-ecearth3@baa84f53d54ec61c4ad4f2cc54be744bfa969c19

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 31, 2018, 15:18

mentioned in issue auto-ecearth3#735

**Comment by kinow** [comment]
In GitLab by @pablohe on Oct 31, 2018, 16:25

I hack it here: https://earth.bsc.es/gitlab/es/auto-ecearth3/commit/baa84f53d54ec61c4ad4f2cc54be744bfa969c19
and 

add this note in the jobs.conf:

```
#SPLITS = 1   # corresponds to the number of cmoratm jobs by chunk you have to run. Currently one month, SPLITS = 1 doesn't work, a bugfix was implemented in the template https://earth.bsc.es/gitlab/es/autosubmit/issues/351
```

**Comment by kinow** [comment]
In GitLab by @dmanubens on Nov 26, 2018, 11:58

related to #290

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 28, 2018, 15:01

closed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 28, 2018, 16:09

cda7368eafcc7f94c1a5cb3e5f46a81ccd0fbeb2
