### ISSUE TITLE
AttributeError: _dep_map

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#355]
In GitLab by @pablohe on Nov 10, 2018, 08:00

Hello, 
@dmanubens @mcastril @kserradell 

I'm experimenting this error, looks like random:

could you take a look? 

```
bscesautosubmit02 > autosubmit
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.11.0b-foss-2015a-Python-2.7.9/bin/autosubmit", line 4, in <module>
    __import__('pkg_resources').run_script('autosubmit==3.10.0', 'autosubmit')
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2607, in requires
    dm = self._dep_map
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2663, in __getattr__
    raise AttributeError(attr)
AttributeError: _dep_map
```

```
> which autosubmit
/shared/earth/software/autosubmit/3.11.0b-foss-2015a-Python-2.7.9/bin/autosubmit
```

**Comment by kinow** [comment]
In GitLab by @pablohe on Nov 10, 2018, 10:44

In my machine 315, works fine

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 12, 2018, 09:41

Hi @pablohe ,

I am not able to reproduce it. I see it working fine in autosubmit01 as also as autosubmit02.

I tested `autosubmit` and `autosubmit monitor`

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 12, 2018, 11:02

```
mcastril@ bscesautosubmit01:/esarchive/autosubmit/a1c2> autosubmit --version
3.11.0
```

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 12, 2018, 11:03

```
mcastril@legio:~> ssh bscesautosubmit02
Last login: Mon Nov 12 09:43:43 2018 from 84.88.188.165
Have a lot of fun...
mcastril@ bscesautosubmit02:~> module load autosubmit
mcastril@ bscesautosubmit02:~> autosubmit --version
3.11.0
```

**Comment by kinow** [comment]
In GitLab by @pablohe on Nov 14, 2018, 17:34

was solved removing the tmp folder

```
/home/Earth/pechevar  > rm .python-eggs/ -r
```

**Comment by kinow** [comment]
In GitLab by @pablohe on Nov 14, 2018, 17:34

closed

**Comment by kinow** [comment]
In GitLab by @pablohe on Nov 14, 2018, 17:34

thanks @kserradell

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 14, 2018, 18:29

Hi @pablohe 

In Jenkins I still see that error. 

`http://bscearth200.int.bsc.es:8080/job/compilers%20testing%20suite%20issue%20752/2/console`

Also, as @dmanubens says, it is using `autosubmit/3.11.0b-foss-2015a-Python-2.7.9` and it would rather use 3.11.

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 14, 2018, 18:30

mentioned in issue auto-ecearth3#752

**Comment by kinow** [comment]
In GitLab by @pablohe on Nov 15, 2018, 06:16

indeed

@kserradell you can check the logs in 

http://bscearth200.int.bsc.es:8080/job/compilers%20testing%20suite%20issue%20752

it happen even if the folder doesn't exits

we can talk latter

**Comment by kinow** [comment]
In GitLab by @pablohe on Nov 15, 2018, 06:16

reopened

**Comment by kinow** [comment]
In GitLab by @kserradell on Nov 15, 2018, 09:23

Ok. I'll take a look.

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 15, 2018, 10:14

```
rm ~/.python-eggs/ -r 
root_directory=/esarchive/exp/ecearth/auto-ecearth/testing_suites/testing_suite_compilers/source
cd  $root_directory

module load autosubmit/3.11.0b-foss-2015a-Python-2.7.9
module load ECAC
module load PyYAML/3.12-foss-2015a-Python-2.7.9
```

Thanks @kserradell 

In any case @pablohe , I insist, there is a `module load 3.11.0b` . Why?

**Comment by kinow** [comment]
In GitLab by @pablohe on Nov 15, 2018, 10:22

Hi, it was copy from an old case.

Anyway I tested the default autosubmit version (3.11) and it failed too

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 15, 2018, 10:35

I already supposed they are separate issues, but we should use the Autosubmit stable versions for the tests, specially because it is the only version that we say we support.

**Comment by kinow** [comment]
In GitLab by @pablohe on Nov 19, 2018, 15:13

@dmanubens found the solution!

aparently the platforms package name colition with the autosubmit's one  and it keep in memory and broke autosubmit

so the fix is change it in testing suite

@ jberlin 


```
> autosubmit monitor  t01q
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/bin/autosubmit", line 4, in <module>
    __import__('pkg_resources').run_script('autosubmit==3.11.0', 'autosubmit')
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2607, in requires
    dm = self._dep_map
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2663, in __getattr__
    raise AttributeError(attr)
AttributeError: _dep_map
```
```
> mv platform/  platform_testing_suite
```

```
WS/esarchive/exp/ecearth/auto-ecearth/testing_suites/testing_suite_weekly/source[master]  > autosubmit monitor  t01q
Getting job list...

Checking configuration files...
platforms_t01q.conf OK
jobs_t01q.conf OK
autosubmit_t01q.conf OK
expdef_t01q.conf  OK
Configuration files OK

Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Plotting...
Plot created at /esarchive/autosubmit/t01q/plot/t01q_20181119_1511.pdf
START /usr/bin/evince /esarchive/autosubmit/t01q/plot/t01q_20181119_1511.pdf
Writing status txt...
Status txt created at <closed file '/esarchive/autosubmit/t01q/status/t01q_20181119_1511.txt', mode 'w+' at 0x7fc3708a18a0>
```
```
WS/esarchive/exp/ecearth/auto-ecearth/testing_suites/testing_suite_weekly/source[master]  > mv platform_testing_suite/  platform
```

```
WS/esarchive/exp/ecearth/auto-ecearth/testing_suites/testing_suite_weekly/source[master]  > autosubmit monitor  t01q
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/bin/autosubmit", line 4, in <module>
    __import__('pkg_resources').run_script('autosubmit==3.11.0', 'autosubmit')
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2607, in requires
    dm = self._dep_map
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2663, in __getattr__
    raise AttributeError(attr)
AttributeError: _dep_map
```

**Comment by kinow** [comment]
In GitLab by @pablohe on Nov 19, 2018, 15:13

closed

**Comment by kinow** [comment]
In GitLab by @pablohe on Nov 19, 2018, 15:28

mentioned in commit testing_suite@f93d9f5c938a6522e0e9e942e999bb30ecab6383

**Comment by kinow** [comment]
In GitLab by @pablohe on Jul 5, 2019, 13:01

mentioned in commit testing_suite@8f856a0efb8f05cf4bf0796f836359f7ae1f53cd

**Comment by kinow** [comment]
In GitLab by @pablohe on Jul 5, 2019, 14:45

mentioned in commit testing_suite@b709816403a98690ad0812d1390d590403c812cc
