### ISSUE TITLE
platform = platforms[as_conf.get_platform().lower()]    KeyError: 'marenostrum4'

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#357]
In GitLab by @pablohe on Nov 21, 2018, 16:01

@thomasarsouze reported: 

the auto-ecearth experiment a1c3 have this issue

```
[CRITICAL] Unhandled exception on Autosubmit: 'marenostrum4'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0-py2.7.egg/autosubmit/autosubmit.py", line 374, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0-py2.7.egg/autosubmit/autosubmit.py", line 680, in run_experiment
    Autosubmit._load_parameters(as_conf, job_list, submitter.platforms)
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0-py2.7.egg/autosubmit/autosubmit.py", line 608, in _load_parameters
    platform = platforms[as_conf.get_platform().lower()]
KeyError: 'marenostrum4'
```

this problem was reported already and aparently solved,  https://earth.bsc.es/gitlab/search?group_id=&project_id=58&repository_ref=master&scope=issues&search=KeyError%3A+

I'm try to reproduce it in `t04g`

@dmanubens @mcastril

**Comment by kinow** [comment]
In GitLab by @pablohe on Nov 21, 2018, 16:20

this experiment have defined only one job:


```
[BARAKUDA]
FILE = templates/common/common.barakuda
PLATFORM = moore
WALLCLOCK = 05:00
PROCESSORS = 1
```

**Was solve setting in expdef.conf**

```
HPCARCH = moore
```

I don't know is it a bug

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 21, 2018, 17:01

Hi @pablohe , as I see in the query, the problem that was solved was typing the HPCARCH value in capitals. For example, MARENOSTRUM4.

This was solved with the `platforms[as_conf.get_platform().lower()]`

So I guess in expdef.conf, originally the HPCARCH was 

`HPCARCH = marenostrum4`

It is strange, like it wasn't unable to find marenostrum4 in platforms.conf

**Comment by kinow** [comment]
In GitLab by @pablohe on Nov 21, 2018, 17:03

Indeed this was my first guess, but not marenostrum 4 was defined, and still fail.

other way to "solve it" is defined a dummy job that use marenostrum4

We are agree that is a border case, defined a hpc and don't use it.

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 21, 2018, 17:09

You are right, I understand, it reads the job list and does not find anyone with the marenostrum4 key.

It is a border case and also the wrong way to use Autosubmit (sorry @thomasarsouze ). Defining a dummy job is a way to skip the problem, but the right way to do it I guess is to do:

`autosubmit expid -y a1c3 -H moore -d "Post-processing experiment running in Moore"`

In any case I understand that a proper error message would give the user more hints so he can realize what he is doing wrong.

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 21, 2018, 17:30

closed

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 22, 2018, 10:25

By the "correct way to use Autosubmit" I do not mean that it cannot be used to launch only post-processing jobs, but the target platform should always be the main computing resource in which the core of the work will be done.

**Comment by kinow** [comment]
In GitLab by @orioltinto on Jun 4, 2020, 13:29

I had the same issue.
I agree that probably has no sense to specify a HPC platform that is not used in the jobs but maybe a more informative Error message could help.
Also, I see no reason to prevent to run the jobs defined even if the original HPC is not in the list of platforms.

**Comment by kinow** [comment]
In GitLab by @orioltinto on Jun 4, 2020, 13:29

reopened

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 4, 2020, 13:32

unassigned @pablohe

**Comment by kinow** [comment]
In GitLab by @wuruchi on Jun 4, 2020, 13:34

I will be working on it.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 4, 2020, 13:45

I had been working a bit on a rework of the log system, however, it was delayed a week to week for more important issues, but I guess we can do a quick solution to this one in particular

**Comment by kinow** [comment]
In GitLab by @wuruchi on Jun 4, 2020, 14:28

@mcastril @dbeltrankyl 

!174 Should handle this error. Please take a look.

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 4, 2020, 16:46

Thanks I think the error is clear enough

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 30, 2020, 13:04

closed
