### ISSUE TITLE
error when conecting to dt02

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#361]
In GitLab by @ mtpay on Dec 13, 2018, 10:32

Hi,

I've just had this error with autosubmit when running a job that tries to move files to bsc32 esarchive using the prace account pr1ehu00.

We have been facing disc quota exceedances in esarchive with the project pr1ehu00, but I've noticed that the quota in esarchive for that project has been increased. So, I do not understand my error. Do you have any idea?

Thank you

```
[ERROR] Can not send command mkdir -p /gpfs/scratch/pr1ehu00/pr1ehu14/a148/LOG_a148 to dt02.bsc.es: SSH session not active                                                                                                              
[ERROR] Could not create the DIR /gpfs/scratch/pr1ehu00/pr1ehu14/a148/LOG_a148 on HPC dt02.bsc.es
[ERROR] Can not send file /esarchive/autosubmit/a148/tmp/a148_20151006_1_1_ARCHIVE_REDUCED.cmd to /gpfs/scratch/pr1ehu00/pr1ehu14/a148/LOG_a148/a148_20151006_1_1_ARCHIVE_REDUCED.cmd                                                   
[ERROR] marenostrum_archive submission failed
[CRITICAL] Unhandled exception on Autosubmit: SSH session not active
Traceback (most recent call last):                                                                                  
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0-py2.7.egg/autosubmit/autosubmit.py", line 374, in parse_args                                                     
    return Autosubmit.run_experiment(args.expid, args.notransitive)                                                 
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0-py2.7.egg/autosubmit/autosubmit.py", line 785, in run_experiment                                                 
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):                    
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0-py2.7.egg/autosubmit/autosubmit.py", line 828, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters)
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0-py2.7.egg/autosubmit/job/job_packages.py", line 87, in submit
    self._send_files()
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0-py2.7.egg/autosubmit/job/job_packages.py", line 115, in _send_files
    self.platform.send_file(self._job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 128, in send_file
    ftp = self._ssh.open_sftp()
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/client.py", line 379, in open_sftp
    return self._transport.open_sftp_client()
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 811, in open_sftp_client
    return SFTPClient.from_transport(self)
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/sftp_client.py", line 127, in from_transport
    max_packet_size=max_packet_size)
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 615, in open_session
    max_packet_size=max_packet_size)
SSHException: SSH session not active
```

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 13, 2018, 11:06

Hi. It seems there was an issue with the SSH session that prevents Autosubmit to submit the Archive job. To be honest it is the first time that I see that problem, and I would expect that Autosubmit retries de SSH connection if there's any problem. 

I would retry or I would use dt01 instead of dt02

@dbeltrankyl , could you find if MN4 supports retries when these kind of problems appear?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 13, 2018, 11:43

Hi,

Every command that autosubmit send to remote machines and uses ssh protocol is handle by send_command and the first thing that it does is to check if there is  an ssh session established and if there is not one it tries to connect. At the connecting step, the paramiko library tries to establish connection many times.

If the connection can not be established, autosubmit will return none but I can not see at this moment if it try to retry the same command, later, I will check it again.

However, in that log it seems that autosubmit did in fact a successful connection via ssh but somehow the connection ended before autosubmit could really send any command and thus this error.

My guess is that dt02 stopped working or any other issue just after the connection was established

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 18, 2019, 13:20

I think we can close the issue since it was not reported again by anybody. We can assume it was an isolated problem with dt02 as @dbeltrankyl suggested.

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 18, 2019, 13:20

closed
