### ISSUE TITLE
Autosubmit with vertical wrapper error

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#373]
In GitLab by @ xlevine on Feb 28, 2019, 11:25

Hello @mcastril 

I have been running a PRIMAVERA STREAM II simulation with the vertical wrapper. 

expid: a1qg 

The first batch was running fine (it completed 3 SIM) until failing prematurely this morning with the error message below appearing. When trying to resubmit the job, the same error message keeps appearing. 

Let me know if I am doing anything incorrectly. Thank you very much for any help you may provide.

Xavier.

[ERROR] marenostrum4 submission failed
[CRITICAL] Unhandled exception on Autosubmit: 'JobPackageSimple' object has no attribute 'name'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 375, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 790, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 828, in submit_ready_jobs
    if remote_dependencies_dict and package.name in remote_dependencies_dict['dependencies']:
AttributeError: 'JobPackageSimple' object has no attribute 'name'

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 28, 2019, 11:44

@dbeltrankyl can know better what this error could mean. I have never seen it before.
