### ISSUE TITLE
recovery broken in autosubmit/3.12.0b-foss-2015a-Python-2.7.9

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#378]
In GitLab by @etiennesky on Mar 15, 2019, 17:46

I just tried autosubmit recovery with autosubmit/3.12.0b-foss-2015a-Python-2.7.9 and got theses errors.

After switching back to autosubmit/3.11.1-foss-2015a-Python-2.7.9 the command runs fine.

```
etourign@ bscesautosubmit02:/esarchive/autosubmit/a1po/tmp/LOG_a1po> autosubmit recovery -s --all a1tz

Checking configuration files...
platforms_a1tz.conf OK
jobs_a1tz.conf OK
autosubmit_a1tz.conf OK
expdef_a1tz.conf  OK
Configuration files OK

Recovering experiment a1tz
Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...

Checking configuration files...
platforms_a1tz.conf OK
jobs_a1tz.conf OK
autosubmit_a1tz.conf OK
expdef_a1tz.conf  OK
Configuration files OK

Looking for COMPLETED files


CHANGED job 'a1tz_1979020100_GET_INI_ECMWF' status to WAITING
[CRITICAL] Unhandled exception on Autosubmit: [Errno 21] Is a directory: '/esarchive/autosubmit/a1tz/tmp/LOG_a1tz/'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 428, in parse_args
    args.expand, args.expand_status, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1496, in recovery
    job.platform.get_logs_files(expid, job.remote_logs)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/platform.py", line 208, in get_logs_files
    self.get_files([job_out_filename, job_err_filename], False, 'LOG_{0}'.format(exp_id))
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/platform.py", line 185, in get_files
    self.get_file(filename, must_exist, relative_path)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/ecplatform.py", line 156, in get_file
    os.remove(file_path)
OSError: [Errno 21] Is a directory: '/esarchive/autosubmit/a1tz/tmp/LOG_a1tz/'
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 18, 2019, 12:47

Thanks for the report I will check this

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 18, 2019, 14:12

Will be fixed on next 3.12b update, seems like it was falling in some job status.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 18, 2019, 14:12

closed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 18, 2019, 14:12

mentioned in commit c8a33623ebabded56c82f858d6b86ec66a4618bb

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 22, 2019, 13:12

Sorry, yesterday I updated it on 3.12b and forgot to mention.
