### ISSUE TITLE
autosubmit 3.12.0b monitor EXPID --txt crash

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#379]
In GitLab by @pablohe on Mar 18, 2019, 09:34

```sh
  > module purge
  > module load autosubmit/3.12.0b-foss-2015a-Python-2.7.9
  > autosubmit monitor t04x --txt
Getting job list...

Checking configuration files...
platforms_t04x.conf OK
jobs_t04x.conf OK
autosubmit_t04x.conf OK
expdef_t04x.conf  OK
Configuration files OK

Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Writing status txt...
[CRITICAL] Unhandled exception on Autosubmit: unsupported operand type(s) for +: 'module' and 'str'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 420, in parse_args
    args.expand_status, args.hide_groups, args.notransitive,args.checkwrapper)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1293, in monitor
    monitor_exp.generate_output_txt(expid, jobs, exp_path+"/tmp/LOG_"+expid)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/monitor/monitor.py", line 315, in generate_output_txt
    self.write_output_txt_recursive(joblist[0],output_file,"")
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/monitor/monitor.py", line 323, in write_output_txt_recursive
    log_out = path + "/" + job.local_logs[0]
TypeError: unsupported operand type(s) for +: 'module' and 'str'
```

Hi! @dbeltrankyl testing suite require the txt output

@mcastril

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 18, 2019, 12:04

Hi, Still not sure why this was broken (because it was failing with all cases and it was working properly maybe in a refactor )  but I already solved it.

I will upload this later because I want to make it retro-compatible so it uses the new version but will add an option in monitor ( -ct , --classic_txt) if someone needs the old version

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 20, 2019, 11:26

Thanks for the detailed explanation @dbeltrankyl . Maybe instead of --classic_txt you can use --txt_logfiles or something that is self explaining.

User's can understand that the format change if they want to see the logfiles for the sake of readability.
