### ISSUE TITLE
autosubmit 3.12.0b monitor EXPID --txt crash

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#379]
In GitLab by @pablohe on Mar 18, 2019, 09:34

```sh
  > module purge
  > module load autosubmit/3.12.0b-foss-2015a-Python-2.7.9
  > autosubmit monitor t04x --txt
Getting job list...

Checking configuration files...
platforms_t04x.conf OK
jobs_t04x.conf OK
autosubmit_t04x.conf OK
expdef_t04x.conf  OK
Configuration files OK

Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Writing status txt...
[CRITICAL] Unhandled exception on Autosubmit: unsupported operand type(s) for +: 'module' and 'str'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 420, in parse_args
    args.expand_status, args.hide_groups, args.notransitive,args.checkwrapper)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1293, in monitor
    monitor_exp.generate_output_txt(expid, jobs, exp_path+"/tmp/LOG_"+expid)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/monitor/monitor.py", line 315, in generate_output_txt
    self.write_output_txt_recursive(joblist[0],output_file,"")
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/monitor/monitor.py", line 323, in write_output_txt_recursive
    log_out = path + "/" + job.local_logs[0]
TypeError: unsupported operand type(s) for +: 'module' and 'str'
```

Hi! @dbeltrankyl testing suite require the txt output

@mcastril

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 18, 2019, 12:04

Hi, Still not sure why this was broken (because it was failing with all cases and it was working properly maybe in a refactor )  but I already solved it.

I will upload this later because I want to make it retro-compatible so it uses the new version but will add an option in monitor ( -ct , --classic_txt) if someone needs the old version

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 18, 2019, 12:46

Updated into 3.12b(docs also updated) (if you test right now maybe it is still being updated)

-ctxt, -classictxt uses the old version as well as all commands that plot the graph.

-txt uses the new version.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 18, 2019, 12:46

closed

**Comment by kinow** [comment]
In GitLab by @pablohe on Mar 18, 2019, 12:52

Nice!!
thanks @dbeltrankyl 

One style step forward, follow the nix convention could you please put double minus as prefix for long option and a minus to split words to read easily.

```
--classic-txt
```

**Comment by kinow** [comment]
In GitLab by @pablohe on Mar 18, 2019, 13:01

https://www.gnu.org/prep/standards/html_node/Option-Table.html#Option-Table

ups, it seems autosubmit use other convention... 

anyway this 

```
--classic_txt
```

follow the current standard

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 18, 2019, 14:13

fixed, but not uploaded

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 20, 2019, 11:13

Hi @dbeltrankyl ,

Just to understand this better:

- What did it changed recently with the monitor? Wrappers?
- What's the difference between txt (is it the tree form?) and classic txt ?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 20, 2019, 11:21

>  What did it changed recently with the monitor? Wrappers?

The last thing that was changed in AS monitor was the -check_wrappers flag but it didn't touch -txt option

> What's the difference between txt (is it the tree form?) and classic txt ?

The -txt is the tree version grouped by fc,date , the classic txt is the old version which it is just plain text moreover, the -txt tree doesn't print the name of log files while the classic_txt yes, that decision was made for legibility because it was a mess if I print it also in the new version. However, at that time, I didn't take into account that it could cause trouble(don't see the log files name) with some scripts so for that I added the classic version. Although, I could add a flag into -txt to print also log files names if it is neccesary.

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 20, 2019, 11:26

Thanks for the detailed explanation @dbeltrankyl . Maybe instead of --classic_txt you can use --txt_logfiles or something that is self explaining.

User's can understand that the format change if they want to see the logfiles for the sake of readability.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 20, 2019, 11:27

That's a good idea, I will change the name to that, thanks @mcastril.
