### ISSUE TITLE
check host crash

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#38]
In GitLab by @aldepp on Jun 17, 2015, 11:26

a015 and a016: autosubmit crashed (on enterprise, job was on ecmwf)
my experiment crashed on either enterprise or ecmwf, autosubmit monitor still tells me it's running but there aren't any jobs on enterprise nor on cca anymore. the job ids are a015 and a016

**Comment by kinow** [comment]
In GitLab by @aldepp on Jun 17, 2015, 11:27

here is the runlog 
 [20150616_160653_run.log](https://earth.bsc.es/gitlab/es/autosubmit/uploads/2cb879a46210e3953b1f477b1d6d42c4/20150616_160653_run.log)

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jun 17, 2015, 15:17

```
2015-06-16 20:48:04,251
Jobs in ecmwf-cca queue: 16
[ERROR] 2015-06-16 20:48:05,062 Could not execute command ecaccess-certificate-list on cca
[ERROR] 2015-06-16 20:48:05,581 Could not execute command ecaccess-certificate-list on cca
2015-06-16 20:48:05,581 The host cca is down
[CRITICAL] 2015-06-16 20:48:05,612 Unhandled exception on Autosubmit: tuple index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/autosubmit/autosubmit.py", line 228, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/usr/lib/python2.7/dist-packages/autosubmit/autosubmit.py", line 567, in run_experiment
    Log.debug("{0} is not available")
  File "/usr/lib/python2.7/dist-packages/autosubmit/config/log.py", line 183, in debug
    Log.log.debug(msg.format(*args))
IndexError: tuple index out of range
```

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jun 17, 2015, 15:21

mentioned in commit 380b20
