### ISSUE TITLE
Delete experiment from users no longer at BSC

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#386]
In GitLab by @pabretonniere on Apr 4, 2019, 10:08

Hi @dbeltrankyl 

I'm trying to delete experiments from a user no longer working in the department (Muhammad Asif/masif/1244) but autosubmit is failing because it can't associate the uid with a real user name:

```
pbretonn@ bscesautosubmit01:~$ autosubmit delete a00t
Do you want to delete a00t ? [y/n]
y
Removing experiment directory...
[CRITICAL] Unhandled exception on Autosubmit: 'getpwuid(): uid not found: 1244'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 380, in parse_args
    return Autosubmit.delete(args.expid, args.force)
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 596, in delete
    return Autosubmit._delete_expid(expid)
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 456, in _delete_expid
    if pwd.getpwuid(os.stat(os.path.join(BasicConfig.LOCAL_ROOT_DIR, expid_delete)).st_uid).pw_name == os.getlogin():
KeyError: 'getpwuid(): uid not found: 1244'
```

It's not a major issue because I can delete the experiments by hand from esarchive and the autosubmit database, but if you have time at some point, it could be useful to fix this.

Thanks!

@mcastril

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 4, 2019, 10:20

Hi there,

I'm afraid that this is not an error, this was a fix done in the 3.11-hotfix version due the incident with Jaime Benavides experiment #359,#360 which have as side effect this issue. However, I think that is more important the added security since it can be solved via other methods. 

Although , I'm just thinking that maybe I could add a mechanism to bypass this particular issue by checking if the user is still in the bsc/system and if not, be able to delete it. But, I'm not sure how to retrieve this info

**Comment by kinow** [comment]
In GitLab by @pabretonniere on Apr 4, 2019, 10:27

Thanks for the quick answer. Indeed, this is better like this... 

We can think about testing it like this:


case in which the user is still in the department:
```
pbretonn@ bscearth319:~$ id -nu 1242
pbretonn
```

case in which he is not:
```
pbretonn@ bscearth319:~$ id -nu 1244
id: ‘1244’: no such user
```

**Comment by kinow** [comment]
In GitLab by @mcastril on Apr 9, 2019, 19:29

More than deleting users that are not in the department (that could also have important experiments), I think we could let this feature only be accessible to privileged users. I have two ideas:

- @dbeltrankyl being the only able to delete experiments. In that case we should give him a list when we want to remove experiments.

- Let some privileged users to delete experiments (for example, @pabretonniere , @kserradell and myself) but only using a special flag `autosubmit delete -f ` to avoid accidents.

What do you think?

**Comment by kinow** [comment]
In GitLab by @pabretonniere on Apr 9, 2019, 20:12

Good idea. To adopt a strategy similar to esarchive's permissions, as
presented in last CES meeting, I would suggest to have only eadmin (and
maybe @dbeltrankyl) users being able to delete experiments (with the -f
flag to avoid accidents).

**Comment by kinow** [comment]
In GitLab by @kserradell on Apr 10, 2019, 10:37

I would restrict this feature only to eadmin.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Jul 17, 2019, 11:37

mentioned in commit cc712fee6d1837da589ff17f751171ec7258bd84

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 25, 2019, 09:14

mentioned in commit 93409d8c22dd625816706428a5b92b0586a10657

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 25, 2019, 09:16

Hi there, 

@wuruchi finished the implementation and what it remains is to test the issue from my side.

However, I'll test this issue when tag 3.12.1b is updated as a module since I'm unable to use my workenv as eadmin.

**Comment by kinow** [comment]
In GitLab by @pabretonniere on Aug 1, 2019, 16:03

Hi @dbeltrankyl <https://earth.bsc.es/gitlab/dbeltran> ,  @wuruchi
<https://earth.bsc.es/gitlab/wuruchi>


You can test it with a00w. In general, any experiment belonging to 1216
(used to be "masif") is a good candidate for deletion (but ask me or
@ lcaron before deleting anyway just in case).

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 1, 2019, 16:36

Hi @wuruchi ,

It was not working you missed strip() in function `os.popen("id -u eadmin").read() `since it was returning "1004\n" while `os.getuid() `returns "1004". Also changed the log in case eadmin not using -f flag. 

I'll test again when I reupload the module 3.12.1b which will likely be tomorrow.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 1, 2019, 16:40

mentioned in commit bb8a88deafafe0963e41e6df68a6ca7529498ccb

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 1, 2019, 16:40

mentioned in commit 6fe85ca47c2935fa4930b556d08729a0e0a4c455

**Comment by kinow** [comment]
In GitLab by @wuruchi on Aug 2, 2019, 09:21

Hi @dbeltrankyl 

Thanks for pointing that out. I guess you are going to change it?

**Comment by kinow** [comment]
In GitLab by @wuruchi on Aug 2, 2019, 16:03

closed
