### ISSUE TITLE
Problem with DEPENDENCIES with the vertical wrapper with auto-ecearth3

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#387]
In GitLab by @thomasarsouze on Apr 4, 2019, 15:21

Hi,

I use the vertical wrapper for my SIM jobs in auto-ecearth3.

At some point in the workflow, one of my job failed (TRANSFER, because of writing permissions) and autosubmit failed in launching following jobs in marenostrum. I have the following error:

```
Jobs ready for marenostrum4: 2

^[[31m[ERROR] marenostrum4 submission failed^[[0m^[[39m

^[[31m[CRITICAL] Unhandled exception on Autosubmit: 'JobPackageSimple' object has no attribute 'name'
Traceback (most recent call last):

  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 417, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)

  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1064, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):

  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1112, in submit_ready_jobs
    if remote_dependencies_dict and package.name in remote_dependencies_dict['dependencies']:

AttributeError: 'JobPackageSimple' object has no attribute 'name'
```

When switching DEPENDENCIES to False, everything goes back to normal... but another problem arose: even though I have 

`MAX_WRAPPED = 4`

Autosubmit created me a wrapper with 5 SIM jobs.

EXPID: a1i2

Hope I'm clear enough.

@dbeltrankyl @mcastril

**Comment by kinow** [comment]
In GitLab by @thomasarsouze on Apr 5, 2019, 13:39

Follow up to the issue: 

my second chunk embedded in the wrapper failed. After changing the status of the jobs to their expected state, I relaunched the simulation and I now have 6 SIM jobs in the wrapper.

It definitively looks like a counter is not properly reset when the simulation fails.

**Comment by kinow** [comment]
In GitLab by @thomasarsouze on Apr 12, 2019, 09:58

New update of the situation for experiment a142:
vertical wrapper still doing crazy things: MAX_WRAPPED = 4 and DEPENDENCIES = False I now have a job that includes 8 SIM chunks.

It looks like it is quite lost, probably because at some point I changed the dependancies of SIM that is wrapped.

Right now, this is not a big deal beacause there is now queue time on MN4, and the model doesn't crash, so I don't mind if DEPENDENCIES doesn't work, but I'm sure this could be even more efficient and under control.

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 3, 2019, 10:48

Thank you @dbeltrankyl 

@thomasarsouze do you think you can try this version in one of your simulations?

**Comment by kinow** [comment]
In GitLab by @thomasarsouze on Jun 4, 2019, 10:24

Thanks @dbeltrankyl .

I'll test it and let you know

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 5, 2019, 11:26

Hi @thomasarsouze ,

Any update on this?

**Comment by kinow** [comment]
In GitLab by @thomasarsouze on Aug 12, 2019, 11:58

closed
