### ISSUE TITLE
autosubmit recovery --all -s t079 crash

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#389]
In GitLab by @pablohe on Apr 24, 2019, 13:13

```
[CRITICAL] Unhandled exception on Autosubmit: [Errno 21] Is a directory: '/esarchive/autosubmit/t079/tmp/LOG_t079/'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 434, in parse_args
    args.expand, args.expand_status, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1499, in recovery
    job.platform.get_logs_files(expid, job.remote_logs)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/platform.py", line 208, in get_logs_files
    self.get_files([job_out_filename, job_err_filename], False, 'LOG_{0}'.format(exp_id))
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/platform.py", line 185, in get_files
    self.get_file(filename, must_exist, relative_path)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 159, in get_file
    os.remove(file_path)
OSError: [Errno 21] Is a directory: '/esarchive/autosubmit/t079/tmp/LOG_t079/'
```

```
/esarchive/autosubmit/t079/tmp  > autosubmit --version
3.12.0b0
```

and with

```
> module load autosubmit

The following have been reloaded with a version change:
  1) autosubmit/3.12.0b-foss-2015a-Python-2.7.9 => autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9

> autosubmit recovery --all -s t079

Checking configuration files...
platforms_t079.conf OK
jobs_t079.conf OK
autosubmit_t079.conf OK
expdef_t079.conf  OK
Configuration files OK

Recovering experiment t079
Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...

Checking configuration files...
platforms_t079.conf OK
jobs_t079.conf OK
autosubmit_t079.conf OK
expdef_t079.conf  OK
Configuration files OK

Looking for COMPLETED files
CHANGED job 't079_LOCAL_SETUP' status to COMPLETED
CHANGED job 't079_SYNCHRONIZE' status to COMPLETED
CHANGED job 't079_REMOTE_SETUP' status to COMPLETED
CHANGED job 't079_19900101_fc0_INI' status to COMPLETED
CHANGED job 't079_19900101_fc0_1_SIM' status to WAITING
CHANGED job 't079_19900101_fc0_1_POST' status to COMPLETED
CHANGED job 't079_19900101_fc0_1_CLEAN' status to COMPLETED
CHANGED job 't079_19900101_fc0_1_SAVEIC' status to COMPLETED
CHANGED job 't079_19900101_fc0_CLEAN_MEMBER' status to COMPLETED
CHANGED job 't079_19900101_fc0_1_TRANSFER' status to COMPLETED
CHANGED job 't079_PERFORMANCE_METRICS' status to COMPLETED
CHANGED job 't079_19900101_fc0_TRANSFER_MEMBER' status to COMPLETED
Time spent: '0:00:05.688243'
Updating the jobs list
Recovery finalized

Plotting the jobs list...
Plotting...
Plot created at /esarchive/autosubmit/t079/plot/t079_20190424_1312.pdf
Writing status txt...
Status txt created at <closed file '/esarchive/autosubmit/t079/status/t079_20190424_1312.txt', mode 'w+' at 0x7f8ef052f5d0>
WS/esarchive/autosubmit/t079/tmp  > 

```

works fine

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 25, 2019, 11:25

Hi,

Could you explain more the context? I'm trying to reproduce it but it is working for me, this is related to #378 and this error is due to  3.12b recovery also recovers the logs files (when the -s  flag is used) from remote platforms, but the function that it is using was already done and unchanged in  the previous version.

So, what was the state of the experiment at that moment?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 14, 2019, 11:38

Hi, 

This will be fixed on 3.12.1b (related to #391) , the issue was that Autosubmit was trying to recover local logs(no sense) as if they was placed on a remote machine.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 14, 2019, 11:38

closed

**Comment by kinow** [comment]
In GitLab by @pablohe on May 14, 2019, 12:08

thanks @dbeltrankyl I'll test it.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 14, 2019, 12:09

note that the actual 3.12.1b is not the release version that I'll perform this week, I will send an email to bsc-mail list when it is ready.
