### ISSUE TITLE
corrupted job list ob_list_$exp.pkl

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#397]
In GitLab by @ editomas on May 6, 2019, 17:44

@dbeltrankyl a summary of what we have discussed in the chat:

- while trying to re-run a failed experiment I got this error:

`[CRITICAL] Unhandled exception on Autosubmit: 
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 459, in parse_args
    args.group_by, args.expand, args.expand_status, args.notransitive,args.check_wrapper)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 2593, in set_status
    job_list = Autosubmit.load_job_list(expid, as_conf, notransitive=notransitive)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 3066, in load_job_list
    new=False, notransitive=notransitive)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/job/job_list.py", line 139, in generate
    jobs_data = {str(row[0]): row for row in self.load()}
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/job/job_list.py", line 779, in load
    return self._persistence.load(self._persistence_path, self._persistence_file)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/job/job_list_persistence.py", line 73, in load
    return pickle.load(fd)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError`

- the experiment had been previously failed with: /esarchive/autosubmit/a1wo/nohup.out_fail_missing_boco The experiment was killed because some SIM jobs failed and there were wrapped in bigger jobs.

- for some reason the joblist of the experiment has been corrupted. This corruption is usually due by a sudden crash in autosubmit that did not arrive to the safe quit. 

- why this was the case for this experiment is not clear yet.  

- one has necessary run a create and then a recovery (the recovery on its own is not enough since the job list is empty).

**Comment by kinow** [comment]
In GitLab by @ editomas on May 6, 2019, 18:05

@dbeltrankyl I've run:
- nohup autosubmit create a1wo -np & 
moved the log to /esarchive/autosubmit/a1wo/nohup.out_create
- nohup autosubmit recovery --all -s a1wo -np &
moved the log to /esarchive/autosubmit/a1wo/nohup.out_recovery_failed2

Am I doing something wrong? as you see the recovery fails with:

`Looking for COMPLETED files
CHANGED job 'a1wo_20110104_000_LOCAL_SEND_INITIAL' status to COMPLETED
^[[31m[CRITICAL] Unhandled exception on Autosubmit: [Errno 21] Is a directory: '/esarchive/autosubmit/a1wo/tmp/LOG_a1wo/'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 434, in parse_args
    args.expand, args.expand_status, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1499, in recovery
    job.platform.get_logs_files(expid, job.remote_logs)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/platform.py", line 208, in get_logs_files
    self.get_files([job_out_filename, job_err_filename], False, 'LOG_{0}'.format(exp_id))
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/platform.py", line 185, in get_files
    self.get_file(filename, must_exist, relative_path)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 159, in get_file
    os.remove(file_path)
OSError: [Errno 21] Is a directory: '/esarchive/autosubmit/a1wo/tmp/LOG_a1wo/`

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 7, 2019, 11:41

I'll revise recovery in the next 3.12 update, use 3.11 for recovery and then run in 3.12b it should work properly , if not I'll try to do a quick update

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 14, 2019, 11:43

Let me know if it worked with 3.11 ( I guess yes) , anyway recovery will be fixed on 3.12.1b (more info in #389 also related to #391)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 14, 2019, 11:43

closed

**Comment by kinow** [comment]
In GitLab by @ editomas on May 14, 2019, 19:05

@dbeltrankyl yes with 3.11 the recovery runs.

I can't say for sure if it is considering correctly the status of all the many jobs. When I re-run the experiment after the recovery I have the impression that it finds only few jobs ready for submission when in reality there should be many more. But it is hard to say with a complex workflow that I cannot plot.

a small kind note: can you please give me the chance to answer a question you have for me before closing an issue? I'm following a conference at the moment or anyway might not always answer immediately. thanks for understanding!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 15, 2019, 09:05

Hi,
You can't plot the experiment but you can perform an autosubmit monitor -txt, it will generate a txt file representing the plot 

note answer: sry, I clicked on comment & close issue  by mistake instead of comment

**Comment by kinow** [comment]
In GitLab by @ aamaral on Jun 23, 2020, 11:41

reopened

**Comment by kinow** [comment]
In GitLab by @ aamaral on Jun 23, 2020, 11:43

Hi, @dbeltrankyl 

After the crash this morning, I tried changing the status of some of my FAILED jobs and now I get the same EOF error:

```
Checking configuration files...
platforms_a2y7.conf OK
jobs_a2y7.conf OK
autosubmit_a2y7.conf OK
expdef_a2y7.conf  OK
Configuration files OK

Creating jobs...
Loading JobList
[CRITICAL] Unhandled exception on Autosubmit:
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 458, in parse_args
    args.group_by, args.expand, args.expand_status, args.notransitive,args.check_wrapper)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 2683, in set_status
    job_list = Autosubmit.load_job_list(expid, as_conf, notransitive=notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 3154, in load_job_list
    new=False, notransitive=notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_list.py", line 140, in generate
    jobs_data = {str(row[0]): row for row in self.load()}
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_list.py", line 780, in load
    return self._persistence.load(self._persistence_path, self._persistence_file)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_list_persistence.py", line 73, in load
    return pickle.load(fd)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError
```

What are the steps here to fix it? Autosubmit Create and change the status by hand? 

Thanks!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 23, 2020, 12:17

Hi @ aamaral ,
Sorry for the delay, the mail notification didn't pop up. 

autosubmit create and then recovery -all -s. 

Since autosubmit was running, it couldn't save the status of the pkl correctly with the esarchive crash

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 30, 2020, 13:04

closed
