### ISSUE TITLE
MAX_WAITING_JOBS and TOTAL_JOBS read from platform configuration are not int

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#40]
In GitLab by @dmanubens on Jun 19, 2015, 17:04

```
Jobs ready for ecmwf-cca: 1
^[[31m[CRITICAL] Unhandled exception on Autosubmit: unsupported operand type(s) for -: 'str' and 'int'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/autosubmit/autosubmit.py", line 228, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/usr/lib/python2.7/dist-packages/autosubmit/autosubmit.py", line 615, in run_experiment
    available = max_waiting_jobs - waiting
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jun 29, 2015, 10:09

Status changed to closed by commit 684eae
