### ISSUE TITLE
autosubmit test case show an error

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#408]
In GitLab by @pablohe on Jun 6, 2019, 12:04

```sh
 > autosubmit testcase -y t01q -H marenostrum -d"test case: T255L91-ORCA1L75 cold start. Singularity"
The new experiment "t07j" has been registered.
Copying previous experiment config directories

Checking configuration files...
platforms_t01q.conf OK
jobs_t01q.conf OK
autosubmit_t01q.conf OK
expdef_t01q.conf  OK
Configuration files OK

checking model version...
test
[WARNING] There are local changes not commited to Git
[CRITICAL] Unhandled exception on Autosubmit: 'module' object has no attribute 'join'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 463, in parse_args
    args.HPC, args.branch)
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 3018, in testcase
    testcaseid = Autosubmit.expid(hpc, description, copy_id, False, True)
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 626, in expid
    os.mkdir(os.join(tmp_path , BasicConfig.LOCAL_ASLOG_DIR))
AttributeError: 'module' object has no attribute 'join'

> autosubmit --version
3.12.1b0

```

The `t07j` looks ok

A word `test` is a debugging remainder... ?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 6, 2019, 12:19

Hi, 
seems a log issue that took place when I changed the ASLog location I'll fix
and yes the test word was also for debug I'll erase it

**Comment by kinow** [comment]
In GitLab by @pablohe on Jun 6, 2019, 12:25

Hi  @dbeltrankyl, ok great thanks

in other hand the experiment looks like not healthy 


```
 > autosubmit create t07j
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
platforms_t07j.conf OK
jobs_t07j.conf OK
autosubmit_t07j.conf OK
expdef_t07j.conf  OK
Configuration files OK

Using project folder: /esarchive/autosubmit/t07j/proj
Loading parameters...

Creating the jobs list...
Creating jobs...
Adding dependencies...
Removing redundant dependencies...

Saving the jobs list...
[CRITICAL] Unhandled exception on Autosubmit: [Errno 2] No such file or directory: '/esarchive/autosubmit/t07j/pkl/job_list_t07j.pkl'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 447, in parse_args
    args.expand_status, args.notransitive,args.check_wrapper)
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 2455, in create
    job_list.save()
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/job/job_list.py", line 786, in save
    self._persistence.save(self._persistence_path, self._persistence_file, self._job_list)
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/job/job_list_persistence.py", line 87, in save
    fd = open(path, 'w')
IOError: [Errno 2] No such file or directory: '/esarchive/autosubmit/t07j/pkl/job_list_t07j.pkl'
```


I have to use 3.12.0b0  to create the new one?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 6, 2019, 12:29

Wait, I'll fix the bug in few minutes so you can use the version

**Comment by kinow** [comment]
In GitLab by @pablohe on Jun 6, 2019, 12:34

Ok thanks!!

The new log folder is here again :)

The delete function need some check:

```sh
 > autosubmit delete t07j
Do you want to delete t07j ? [y/n]
y
Removing experiment directory...
[WARNING] Can not delete experiment folder: [Errno 39] Directory not empty: '/esarchive/autosubmit/t07j/tmp/ASLOGS'
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 6, 2019, 13:01

I didn't think about delete function, thanks for the report I'll fix it and upload both fixes. However, this will mean that if an experiment that uses 3.12.0b or lower wants to delete an experiment that used at least once the version 3.12.1b it will fail at that point

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 6, 2019, 13:37

Uploaded, sorry the delay I had to restart the pc I was unable to commit or push

**Comment by kinow** [comment]
In GitLab by @pablohe on Jun 6, 2019, 14:27

tanks @dbeltrankyl 

It is a new problem 

```
> autosubmit run t07k
Preparing .lock file to avoid multiple instances with same experiment id


Checking configuration files...
platforms_t07k.conf OK
jobs_t07k.conf OK
autosubmit_t07k.conf OK
expdef_t07k.conf  OK
Configuration files OK

Starting job submission...
Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Checking scripts...
[WARNING] The following set of variables to be substituted in template script is not part of parameters set, and will be replaced by a blank value: set(['PISCES_timestep', 'LIM_timestep', 'IFS_timestep', 'NEM_FORCING_SET', 'RUN_coupFreq', 'NEMO_timestep'])
[WARNING] Invalid parameter substitution in LOCAL_SETUP template
[WARNING] The following set of variables to be substituted in template script is not part of parameters set, and will be replaced by a blank value: set(['USE_DT_MACHINE', 'UPDATE_MODEL', 'DT_HOST', 'DTHOSTMACHINE', 'DT_USER'])
[WARNING] Invalid parameter substitution in SYNCHRONIZE template
[WARNING] The following set of variables to be substituted in template script is not part of parameters set, and will be replaced by a blank value: set(['LPJG_CONFIG', 'MODEL_CLEAN', 'MODEL_EXTRACT', 'LPJG'])
[WARNING] Invalid parameter substitution in REMOTE_SETUP template
[WARNING] The following set of variables to be substituted in template script is not part of parameters set, and will be replaced by a blank value: set(['NEM_FIXED_FORCING_YEAR', 'NEM_FORCING_SET'])
[WARNING] Invalid parameter substitution in INI template
[WARNING] Template SIM will be checked without logs
[CRITICAL] Unhandled exception on Autosubmit: [Errno 2] No such file or directory: '/esarchive/autosubmit/t07k/proj/auto-ecearth3/sources/runtime/autosubmit/ece-esm.sh'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 418, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 956, in run_experiment
    job_list.check_scripts(as_conf)
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/job/job_list.py", line 934, in check_scripts
    if not job.check_script(as_conf, self.parameters,show_logs):
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/job/job.py", line 827, in check_script
    template_content = self.update_content(as_conf)
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/job/job.py", line 705, in update_content
    template_file = open(os.path.join(as_conf.get_project_dir(), self.file), 'r')
IOError: [Errno 2] No such file or directory: '/esarchive/autosubmit/t07k/proj/auto-ecearth3/sources/runtime/autosubmit/ece-esm.sh'
```
```
> autosubmit --version
3.12.1b0
```
```
> cat jobs_t07k.conf 
...
[SIM]
FILE = sources/runtime/autosubmit/ece-esm.sh
DEPENDENCIES = INI SIM-1
RUNNING = chunk
WALLCLOCK = 2:00
PROCESSORS = 768
TASKS = 48
THREADS = 1
CHECK = on_summision
QUEUE = debug
...
```

looks likes the `on_summision` check is not working again... I should open a new issue ?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 25, 2019, 09:57

Tested completed ( I believe) closing this.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 25, 2019, 09:57

closed
