### ISSUE TITLE
marenostrum4 submission failed due to Unknown error

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#415]
In GitLab by @f-macchia on Jun 13, 2019, 11:41

I'm using autosubmit/3.12.1b-foss-2015a-Python-2.7.9.

After a `autosubmit recovery -s --all`, I run again the experiment. Some job were succesfully submitted on power9, but the submission fails on marenostrum4 with this error:
```
[ERROR] marenostrum4 submission failed due to Unknown error
[CRITICAL] Unhandled exception on Autosubmit: Submission failed
Traceback (most recent call last):                                                                    
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 418, in parse_args                      
    return Autosubmit.run_experiment(args.expid, args.notransitive)                                   
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 1079, in run_experiment                 
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):      
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 1132, in submit_ready_jobs              
    package.submit(as_conf, job_list.parameters, inspect)
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/job/job_packages.py", line 95, in submit
    self._do_submission()
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/job/job_packages.py", line 320, in _do_submission
    raise Exception('Submission failed')
Exception: Submission failed
```

You can find a log here: `/esarchive/autosubmit/a1yg/tmp/ASLOGS/20190613_110530_run.log`

Thanks!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 17, 2019, 11:38

Hi @f-macchia,

3\.12.1b should be working again, there was a mess with commits from early last week via an isssue with my installed pycharm, also I added and adapted all features of 3.12.0b on this version (included the done on Friday).

So , from now as discussed with @mcastril this will be the testing version and the 3.12.0b will be "a non-default release" that need some polish but it only will receive critical updates.

FYI: @jvegreg , @gmontanepinto , @pablohe, @ jberlin , @mcastril. this mention is only to let you know that 3.12.1b is working again if you want to test it or need speed.

Edit Sorry wrong issue on #410 moved there

**Comment by kinow** [comment]
In GitLab by @f-macchia on Jun 17, 2019, 17:52

Tested with 3.12.1b and working! Thanks!

**Comment by kinow** [comment]
In GitLab by @f-macchia on Jun 17, 2019, 17:52

closed
