### ISSUE TITLE
problems with CHECK in SIM job

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#416]
In GitLab by @etiennesky on Aug 29, 2016, 18:22

If you run an experiment for the first time with the CHECK=True flag inside the SIM job, autosubmit fails with the following error:

```
[CRITICAL] Unhandled exception on Autosubmit: [Errno 2] No such file or directory: '/esnas/autosubmit/a09t/proj/auto-ecearth3/sources/runtime/autosubmit/ece-ifs+nemo.sh'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 287, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/autosubmit.py", line 586, in run_experiment
    joblist.check_scripts(as_conf)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/job/job_list.py", line 583, in check_scripts
    if not job.check_script(as_conf, self.parameters):
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/job/job.py", line 658, in check_script
    template_content = self.update_content(as_conf)
  File "/shared/earth/software/autosubmit/3.6.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.6.0-py2.7.egg/autosubmit/job/job.py", line 574, in update_content
    template_file = open(os.path.join(as_conf.get_project_dir(), self.file), 'r')
IOError: [Errno 2] No such file or directory: '/esnas/autosubmit/a09t/proj/auto-ecearth3/sources/runtime/autosubmit/ece-ifs+nemo.sh'
```

This is because the ece-ifs+nemo.sh file has not yet been created by ec-conf, which is done in the LOCALSETUP job.

To fix this, the user must set CHECK=FALSE (at least for the first time), which has the unwanted effect that any errors in the script itself will not be detected, which can cause loss of time and resources.

I understand now why CHECK = False is the default value for the SIM job only.

I think that something has to be fixed in autosubmit or the jobs scripts, because

1) the checking of the SIM script should be done by default

2) it should be done AFTER the SIM script (e.g. ece-ifs+nemo.sh) has been generated by ec-conf, to check that the correct values are present

see related issues auto-ecearth3#61 and auto-ecearth3#64 

@mcastril @ jlope2

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Aug 31, 2016, 12:59

We will review it with @dmanubens when he come back from vacation. 

I think what could be a good solution but I don't know the implications for all different kind of the experiments that are run with Autosubmit, so I prefer wait him.

Thanks! :)

**Comment by kinow** [comment]
In GitLab by @etiennesky on Aug 31, 2016, 13:03

Yes for sure this is a topic that would require some thinking and discussion. merci!

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Sep 8, 2016, 12:50

mentioned in issue auto-ecearth3#64

**Comment by kinow** [comment]
In GitLab by @etiennesky on Sep 8, 2016, 12:56

mentioned in issue auto-ecearth3#64

**Comment by kinow** [comment]
In GitLab by @etiennesky on Nov 10, 2016, 15:57

Mentioned in issue auto-ecearth3#115

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jan 20, 2017, 12:16

We are considering to introduce in autosubmit a `CHECK=TRUE_JUST_BEFORE_SUBMIT` or something similar...

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jan 20, 2017, 12:16

Changed title: **problems with CHECK in SIM job{- -}** → **problems with CHECK in SIM job**

**Comment by kinow** [comment]
In GitLab by @etiennesky on Jan 20, 2017, 12:36

I am unsure if this will solve the problem as the output of the check command will never be seen by the user... Unless autosubmit stops when the check test fails. again the user might loose precious time before he/she finds out the experiment has stopped.

Would you consider adding a "pre-check hook" command? In this case it would be a short script/code snippet which would run ec-conf, which produces the runtime file from the ec-conf template.

So you could have a special syntax to CHECK which could be TRUE/FALSE/script_name and have the SIM job like this
```
[SIM]
FILE = sources/runtime/autosubmit/ece-ifs+nemo.sh
DEPENDENCIES = INI SIM-1
RUNNING = chunk
WALLCLOCK = 16:00
PROCESSORS = 2032
THREADS = 1
TASKS = 16
CHECK = templates/ecearth3/ecearth3.checksim
```

and the script templates/ecearth3/ecearth3.checksim would contain just this
```
cd $PROJDIR/sources/runtime/autosubmit
../../sources/util/ec-conf/ec-conf --platform %HPCARCH% config-run.xml
```

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jan 26, 2017, 17:23

Since next version, three values will be available for the ```CHECK``` parameter:

*  True
*  False
*  On_Submission

The use cases will be:

*  It will be checked on ```autosubmit check``` and at the beginning of the ```autosubmit run```.
*  It will not be checked.
*  It will be checked just before being submitted in ```autosubmit run```.

-Do you think it is enough?

-Has the ```True``` value to be checked also before being submitted?

-Currently, the ```autosubmit run``` is not stopped when the check fails. Should it be stopped? And in the check before submission?

Now I've finished the first implementation of this, however I think there are some things that we have to discuss about.

Thanks!

@dmanubens @etiennesky

**Comment by kinow** [comment]
In GitLab by @etiennesky on Jan 26, 2017, 17:34

sorry I don't understand what you mean by "Has the True value to be checked also before being submitted?"

Now that false warnings do not happen (see auto-ecearth3#61), autosubmit should stop if the check has failed, in both True and On_Submission cases. But in the second case, an email should be sent to the user. BTW we should encourage users to add email notification to their experiments!

In any case we would need other user's input before making this change. Who would be the best candidate(s) to discuss this with?

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 30, 2017, 11:29

Sorry, I never tested this feature

**Comment by kinow** [comment]
In GitLab by @mcastril on Sep 3, 2018, 18:06

@pablohe will test it

**Comment by kinow** [comment]
In GitLab by @pablohe on Sep 6, 2018, 17:31

mentioned in issue auto-ecearth3#667

**Comment by kinow** [comment]
In GitLab by @pablohe on Sep 10, 2018, 12:06

@dmanubens 

the SIM job with `CHECK = On_Submission` show the error 

```
[ERROR] 2018-09-10 12:00:09,305 Invalid parameter substitution in t025_19900101_fc0_1_SIM template
```

do you know where I can see who is the guilty (the parameter invalid) ?

**Comment by kinow** [comment]
In GitLab by @mcastril on Jan 17, 2019, 17:43

closed

**Comment by kinow** [comment]
In GitLab by @mcastril on Jan 17, 2019, 17:44

To open this issue in Autosubmit project.

**Comment by kinow** [comment]
In GitLab by @mcastril on Jan 17, 2019, 17:44

reopened

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 13, 2019, 16:57

moved from auto-ecearth3#67

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 13, 2019, 16:57

@dbeltrankyl thinks he can fix this long-living issue to check jobs On_Submission (SIM in Auto-EC-Earth for example)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 14, 2019, 13:57

It should work now with `check=On_submission`, please follow the discussion on #404 and for info how it will work now.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 14, 2019, 13:57

closed
