### ISSUE TITLE
Problem with "recovery" in version 3.12.0b

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#421]
In GitLab by @thomasarsouze on Jul 17, 2019, 16:58

Trying to do a recovery of an experiment and get this error :

```
tarsouze@ bscesautosubmit01:/esarchive/autosubmit/a142> autosubmit recovery --all -s a142
...
Looking for COMPLETED files
CHANGED job 'a142_LOCAL_SETUP' status to COMPLETED
[CRITICAL] Unhandled exception on Autosubmit: [Errno 21] Is a directory: '/esarchive/autosubmit/a142/tmp/LOG_a142/'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 434, in parse_args
    args.expand, args.expand_status, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1502, in recovery
    job.platform.get_logs_files(expid, job.remote_logs)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/platform.py", line 208, in get_logs_files
    self.get_files([job_out_filename, job_err_filename], False, 'LOG_{0}'.format(exp_id))
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/platform.py", line 185, in get_files
    self.get_file(filename, must_exist, relative_path)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 160, in get_file
    os.remove(file_path)
OSError: [Errno 21] Is a directory: '/esarchive/autosubmit/a142/tmp/LOG_a142/'
```

This works fine if I change to version 3.12.1b

@mcastril @dbeltrankyl

**Comment by kinow** [comment]
In GitLab by @mcastril on Apr 7, 2020, 14:07

closed
