### ISSUE TITLE
autosubmit monitor crashing

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#422]
In GitLab by @ mguevara on Jul 19, 2019, 13:00

Hi, the autosubmit monitor function crashes with the following error:
```
autosubmit monitor a21m
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/bin/autosubmit", line 4, in <module>
    __import__('pkg_resources').run_script('autosubmit===3.11.0-hotfix', 'autosubmit')
  File "/shared/earth/software/Python/3.7.3-foss-2015a/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg/pkg_resources/__init__.py", line 666, in run_script
  File "/shared/earth/software/Python/3.7.3-foss-2015a/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg/pkg_resources/__init__.py", line 1446, in run_script
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/EGG-INFO/scripts/autosubmit", line 29, in <module>
    from autosubmit.autosubmit import Autosubmit
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 81, in <module>
    from monitor.monitor import Monitor
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/monitor/monitor.py", line 39, in <module>
    from diagram import create_bar_diagram
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/monitor/diagram.py", line 21, in <module>
    import numpy as np
  File "/shared/earth/software/numpy/1.16.4-foss-2015a-Python-3.7.3/lib/python3.7/site-packages/numpy-1.16.4-py3.7-linux-x86_64.egg/numpy/__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
```
I am using the default module of autosubmit. It looks like is trying to use some libraries from Python 3

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 19, 2019, 13:03

Hi @ mguevara,

I will fyi and  contact @kserradell , @mcastril.

**Comment by kinow** [comment]
In GitLab by @kserradell on Jul 19, 2019, 13:07

@ mguevara, I think the problem is you're mixing Python2 and Python3 modules.

Could you please paste the output of `module list`?

**Comment by kinow** [comment]
In GitLab by @ mguevara on Jul 19, 2019, 13:08

@kserradell , I think you are right:

```
Currently Loaded Modules:
  1) GCC/4.9.2                                                 20) cURL/7.40.0-foss-2015a                    39) SIP/4.19.18-foss-2015a-Python-3.7.3      58) ESMPy/7.1.0r-foss-2015a-Python-2.7.9
  2) numactl/2.0.10-GCC-4.9.2                                  21) UDUNITS/2.2.19-foss-2015a                 40) libxml2/2.9.3-foss-2015a                 59) cf_units/1.1.3-foss-2015a-Python-2.7.9
  3) hwloc/1.10.0-GCC-4.9.2                                    22) RStudio/1.1.85-foss-2015a                 41) Qt/5.13.0-foss-2015a                     60) Cython/0.23.4-foss-2015a-Python-2.7.9
  4) OpenMPI/1.8.4-GCC-4.9.2                                   23) R/3.2.0-foss-2015a-bare                   42) PyQt5/5.13.0-foss-2015a-Python-3.7.3     61) GEOS/3.5.0-foss-2015a-Python-2.7.9
  5) OpenBLAS/0.2.13-GCC-4.9.2-LAPACK-3.5.0                    24) ncview/2.1.5-foss-2015a                   43) pandas/0.24.2-foss-2015a-Python-3.7.3    62) Shapely/1.5.17-foss-2015a-Python-2.7.9
  6) gompi/2015a                                               25) CDO/1.6.3-foss-2015a                      44) flex/2.5.39-foss-2015a                   63) pyshp/1.2.10-foss-2015a-Python-2.7.9
  7) FFTW/3.3.4-gompi-2015a                                    26) GSL/1.16-foss-2015a                       45) Bison/3.0.2-foss-2015a                   64) PROJ/4.9.3-foss-2015a
  8) ScaLAPACK/2.0.2-gompi-2015a-OpenBLAS-0.2.13-LAPACK-3.5.0  27) NCO/4.4.9-foss-2015a                      46) HDF/4.2.13-foss-2015a                    65) Cartopy/0.14.2-foss-2015a-Python-2.7.9
  9) foss/2015a                                                28) NCL/6.3.0-foss-2015a                      47) spatialindex/1.8.5-foss-2015a            66) pyke/1.1.1-foss-2015a-Python-2.7.9
 10) ant/1.9.3-Java-1.7.0_80                                   29) libfreetype/2.7-foss-2015a                48) GDAL/2.4.2-foss-2015a                    67) Biggus/0.14.0-foss-2015a-Python-2.7.9
 11) bzip2/1.0.6-foss-2015a                                    30) Pillow/3.4.2-foss-2015a-Python-2.7.9      49) Fiona/1.8.6-foss-2015a-Python-3.7.3      68) Iris/1.10.0-foss-2015a-Python-2.7.9
 12) zlib/1.2.8-foss-2015a                                     31) basemap/1.0.7-foss-2015a-Python-2.7.9     50) pyproj/2.2.1-foss-2015a-Python-3.7.3     69) ConfigArgParse/0.11.0-foss-2015a-Python-2.7.9
 13) ncurses/5.9-foss-2015a                                    32) libreadline/7.0-foss-2015a                51) geopandas/0.5.1-foss-2015a-Python-3.7.3  70) timezonefinder/2.1.0-foss-2015a-Python-2.7.9
 14) Tcl/8.6.3-foss-2015a                                      33) OpenSSL/1.1.1b-foss-2015a                 52) HDF5/1.8.14-foss-2015a                   71) Java/1.8.0_144
 15) SQLite/3.8.8.1-foss-2015a                                 34) numpy/1.16.4-foss-2015a-Python-3.7.3      53) netCDF-Fortran/4.2-foss-2015a            72) Panoply/4.9.1-foss-2015a
 16) Szip/2.1-foss-2015a                                       35) numexpr/2.6.9-foss-2015a-Python-3.7.3     54) netCDF-C++/4.2-foss-2015a                73) Python/2.7.9-foss-2015a
 17) Boost/1.58.0-foss-2015a-Python-2.7.9                      36) Bottleneck/1.2.1-foss-2015a-Python-3.7.3  55) ESMF/7.1.0r-foss-2015a                   74) matplotlib/1.5.1-foss-2015a-Python-2.7.9
 18) NASM/2.11.06-foss-2015a                                   37) scipy/1.3.0-foss-2015a-Python-3.7.3       56) netCDF/4.3.3.1-foss-2015a                75) autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9
 19) libjpeg-turbo/1.4.0-foss-2015a                            38) libpng/1.2.58-foss-2015a                  57) nose/1.3.7-foss-2015a-Python-2.7.9
```

**Comment by kinow** [comment]
In GitLab by @kserradell on Jul 19, 2019, 13:09

Yes, you have some Python3 modules.

I'm sorry but there is no elegant solution to deal with both versions.

**Comment by kinow** [comment]
In GitLab by @ mguevara on Jul 19, 2019, 13:10

Ok, no worries. I will change my bash. Thanks and sorry for the inconvenience!

**Comment by kinow** [comment]
In GitLab by @ mguevara on Jul 19, 2019, 13:10

closed
