### ISSUE TITLE
autosubmit problem

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#432]
In GitLab by @ mtpay on Sep 20, 2019, 09:57

Hi,
I am having this error with autosubmit and I am not sure how to fix it. I have already remove the autosubmit.lock and job status are correct. Any help? Thanks

```python

mtpay@ bscesautosubmit01:~/Documents/exp/nohup_a1yv> tail -f nohup.out 
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/bin/autosubmit", line 4, in <module>
    __import__('pkg_resources').run_script('autosubmit==3.11.0', 'autosubmit')
  File "/shared/earth/software/Python/3.7.3-foss-2015a/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg/pkg_resources/__init__.py", line 666, in run_script
  File "/shared/earth/software/Python/3.7.3-foss-2015a/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg/pkg_resources/__init__.py", line 1446, in run_script
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0-py2.7.egg/EGG-INFO/scripts/autosubmit", line 29, in <module>
    from autosubmit.autosubmit import Autosubmit
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0-py2.7.egg/autosubmit/autosubmit.py", line 80, in <module>
    from monitor.monitor import Monitor
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0-py2.7.egg/autosubmit/monitor/monitor.py", line 39, in <module>
    from diagram import create_bar_diagram
  File "/shared/earth/software/autosubmit/3.11.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0-py2.7.egg/autosubmit/monitor/diagram.py", line 21, in <module>
    import numpy as np
  File "/shared/earth/software/numpy/1.16.4-foss-2015a-Python-3.7.3/lib/python3.7/site-packages/numpy-1.16.4-py3.7-linux-x86_64.egg/numpy/__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 20, 2019, 10:09

Hi @ mtpay ,

It seems that you're using a package that contains python 3.7 which is incompatible (for now ) with autosubmit, you must do a module purge and use only autosubmit or packages which contains python 2.7

As you can see there, 

```python
File "/shared/earth/software/numpy/1.16.4-foss-2015a-Python-3.7.3/lib/python3.7/site-packages/numpy-1.16.4-py3.7-linux-x86_64.egg/numpy/__init__.py", line 140, in <module>
    from . import _distributor_init
```

it is trying to use 3.7.3.

you can see #422 for more info.

**Comment by kinow** [comment]
In GitLab by @ mtpay on Sep 20, 2019, 12:02

Hi @dbeltrankyl,

Thank you very much. I've fixed the problem with modules' version in my .bashrc

I close the issue.
