### ISSUE TITLE
recovery broken

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#433]
In GitLab by @etiennesky on Sep 22, 2019, 20:50

I ran recovery and it crashed when getting a remote job status on MN4

```
etourign@ bscesautosubmit01:/esarchive/autosubmit/a28h/proj/auto-ecearth3> autosubmit recovery -s -np --all a28h

Checking configuration files...
platforms_a28h.conf OK
jobs_a28h.conf OK
autosubmit_a28h.conf OK
expdef_a28h.conf  OK
Configuration files OK

Recovering experiment a28h
Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...

Checking configuration files...
platforms_a28h.conf OK
jobs_a28h.conf OK
autosubmit_a28h.conf OK
expdef_a28h.conf  OK
Configuration files OK

Looking for COMPLETED files
CHANGED job 'a28h_LOCAL_SETUP' status to COMPLETED
CHANGED job 'a28h_SYNCHRONIZE' status to COMPLETED
CHANGED job 'a28h_REMOTE_SETUP' status to COMPLETED


CHANGED job 'a28h_19790101_fc00_INI' status to COMPLETED
[CRITICAL] Unhandled exception on Autosubmit: [Errno 21] Is a directory: '/esarchive/autosubmit/a28h/tmp/LOG_a28h/'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 434, in parse_args
    args.expand, args.expand_status, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1503, in recovery
    job.platform.get_logs_files(expid, job.remote_logs)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/platform.py", line 208, in get_logs_files
    self.get_files([job_out_filename, job_err_filename], False, 'LOG_{0}'.format(exp_id))
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/platform.py", line 185, in get_files
    self.get_file(filename, must_exist, relative_path)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 160, in get_file
    os.remove(file_path)
OSError: [Errno 21] Is a directory: '/esarchive/autosubmit/a28h/tmp/LOG_a28h/'
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 23, 2019, 08:18

Hi @etiennesky ,

This bug is fixed but only on 3.12.1b.

In last AS meeting we closed this issue(#378) , @mcastril but maybe I should apply the fix  on 3.12.0b? 

In any case, I recommend use 3.12.1b for do the recovery and switch back to 3.12.0b when it ends because it will be much faster

**Comment by kinow** [comment]
In GitLab by @etiennesky on Sep 23, 2019, 10:26

sorry, I forgot I myself had opened an issue on this, should have re-opened it!  

I am personally reluctant to use 3\.12.1b because I have had problems with it, but maybe your approach (to use it just for recovery) is the best idea.

**Comment by kinow** [comment]
In GitLab by @mcastril on Sep 23, 2019, 12:36

Using it only for recovery should be safe. On the other hand to have a bugged 3.12.0b is not very optimistic. What are the chances that fixing 3.12.0b recovery impacts in the running of the jobs ?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 23, 2019, 13:57

I'm mostly certain that it wouldn't affect run since the bug fix done in 3.12.1b would be almost 1:1 and it is running fine there

**Comment by kinow** [comment]
In GitLab by @mcastril on Sep 23, 2019, 14:30

In that case I think we could fix the feature and not force people to use another version.

**Comment by kinow** [comment]
In GitLab by @mcastril on Apr 7, 2020, 14:07

closed
