### ISSUE TITLE
Error on job submission : AttributeError: 'bool' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#435]
In GitLab by @etiennesky on Oct 3, 2019, 15:09

Hi @dbeltrankyl @pablohe 

I am running an experiment on my bsc32 account using autosubmit-3.12.0b0 .

After doing some basic changes to jobs.conf and expdef.conf (which I subsequently reverted), I always get this error when submitting jobs.

see in : /esarchive/autosubmit/a29g/tmp/20191003_150549_run.log

The logs are not helpful, since they do not give any information on the job being submitted nor the file it tries to delete.

```
Jobs ready for marenostrum4: 3
2019-10-03 15:06:06,231 Number of jobs ready: 3
2019-10-03 15:06:06,231 Number of jobs available: 59
2019-10-03 15:06:06,232 Jobs ready for marenostrum4: 3
2019-10-03 15:06:09,646 Command mkdir -p /gpfs/scratch/bsc32/bsc32051/a29g/LOG_a29g in mn1.bsc.es successful with out message: 
2019-10-03 15:06:09,647 /gpfs/scratch/bsc32/bsc32051/a29g/LOG_a29g has been created on mn1.bsc.es .
[ERROR] 2019-10-03 15:06:12,812 marenostrum4 submission failed
[CRITICAL] 2019-10-03 15:06:12,819 Unhandled exception on Autosubmit: 'bool' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 417, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1065, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1121, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters,inspect)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/job/job_packages.py", line 96, in submit
    self._send_files()
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/job/job_packages.py", line 129, in _send_files
    self.platform.send_file(self._job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 126, in send_file
    self.delete_file(filename)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 200, in delete_file
    Log.debug('Could not remove file {0}'.format(os.path.join(self.get_files_path(), filename)))
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'bool' object has no attribute 'startswith'
```

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 3, 2019, 15:24

Oh and I am also able to submit jobs on mn4 with same account using exp a21o, from bscesautosubmit01

The failures with a29g are on bscesautosumit02 - maybe this is the issue.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 3, 2019, 15:26

I'm looking at it, somehow the filename is detected as boolean and thus the log.debug fails but not sure why and how

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 3, 2019, 15:27

I tried this on bscesautosubmit01 and get the same error.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 3, 2019, 15:41

@etiennesky I think the issue is on your jobs.conf [POST] the path that you specified doesn't exist 

[POST]

#FILE = templates/ecearth3/ecearth3.post

FILE = templates/lsm/lsm.post


```
dbeltran@ bscearth375:/esarchive/autosubmit/a29g> cat proj/auto-ecearth3/templates/lsm/lsm.post
cat: cannot access 'proj/auto-ecearth3/templates/lsm/lsm.post': No such file or directory
```

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 3, 2019, 16:45

oh you are right - user error... sorry about troubling you.

Would it be possible to make the error more informative?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2019, 10:28

Hi @etiennesky ,

We did minor changes to logs on 3.12.1b, but since we'll  have to migrate to python 3 we will likely change the log class(since it is only for 2.7) for future versions. So a refactor is expected.

Don't worry I'm glad that it wasn't a version breaking issue

 Since it is working I'll close the issue.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 4, 2019, 10:29

closed

**Comment by kinow** [comment]
In GitLab by @orioltinto on Jun 11, 2020, 10:29

Had the same problem and Gitlab pointed me here.
I agree with Etienne, even though it was my fault the error message is quite unintelligible.
