### ISSUE TITLE
autosubmit not submitting jobs

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#442]
In GitLab by @ rmahmood on Oct 30, 2019, 15:28

Hi @dbeltrankyl , @wuruchi , @mcastril , @pablohe , @ rfernand 

I am running an experiment (a22k) which was working fine till last weekend. However, somehow all jobs crashed and now the autosubmit is not submitting the jobs. Below is the map which shows that several jobs are in WAITING, however when I do "nohup autosubmit run a22d &" no job is being submitted. The messages printed is "no more jobs to submit"

`file:///esarchive/autosubmit/a22k/plot/a22k_20191030_1201.pdf`

Any possible solution/s?
Thanks

Rashed

**Comment by kinow** [comment]
In GitLab by @wuruchi on Oct 30, 2019, 15:55

Hello @ rmahmood 

Although I cannot give you an answer right now, here is a more accessible representation of the current state of your experiment: [http://bscesweb04.bsc.es/autosubmitapp/experiment/a22k](http://bscesweb04.bsc.es/autosubmitapp/experiment/a22k) (Press the `SHOW GRAPH` button).

Also, you can try `GROUP BY` and select Date, to see a compressed representation grouped by Date.

I can see that many of your jobs, especially those at the end of the experiment, are in `SUSPENDED` status, is that correct?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 30, 2019, 16:05

Hi @ rmahmood ,

The job failure was due a slurm problem that happened on Monday I think, (outscope of autosubmit)

I guess you're running with 3-11-hotfix, I suggested you to swap to 3.12.0b and try again because I remind that in 3.11 there is a bug like the one you're describing. 

If you want to continue using 3.11 , put the jobs that has all it's parent completed to ready instead of waiting  and autosubmit will be able to proceed with normality (maybe there is only need to put one of them on ready you can try it first and if not work proceed to the complete solution or use 3.12.0b )

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Oct 30, 2019, 16:18

Hi @wuruchi ,

The SUSPENDED jobs at the end are deliberate, so that we could run more chunks in future, if needed.

@dbeltrankyl ,

I had tried to use the latest version "3.12.1b", however it did not work.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 30, 2019, 16:33

Hi @ rmahmood ,

That is weird then,

In 3.11, autosubmit run only can start if there are jobs active (ready,queue,submited and running)
 
While in 3.12.X ( I recommend use 3.12.0b not 3.12.1) autosubmit run first checks if any job can be set into ready status, set them and then proceed to run.

Did you tried to manually put the status into ready of the jobs that it's parents are completed ? if nothing help the last resolt is  to force all waiting jobs into ready status and autosubmit will revert the jobs that can't be put in ready but not enterily sure  if this will work as I describe so first use the other option. ( EDIT: or well you can test it using `setstatus ` without `-s` flag

edit 2: if you do a recovery --all it will recover all completed jobs and I think this also put the ones that can be set into ready, but I would explore first the other options

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Oct 30, 2019, 16:47

Hi @dbeltrankyl ,

There are so many jobs waiting, Is there any automatic way of setting parent jobs to Ready?

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Oct 31, 2019, 14:46

The autosubmit recovery crashes:

`WS- /esarchive/autosubmit/a22k  > module load autosubmit/3.12.0b-foss-2015a-Python-2.7.9`

`The following have been reloaded with a version change:
  1) netCDF/4.4.1.1-foss-2015a => netCDF/4.3.3.1-foss-2015a`

`WS- /esarchive/autosubmit/a22k  > autosubmit recovery a22k --all -s`


Looking for COMPLETED files

CHANGED job 'a22k_LOCAL_SETUP' status to COMPLETED

CHANGED job 'a22k_SYNCHRONIZE' status to COMPLETED

CHANGED job 'a22k_REMOTE_SETUP' status to COMPLETED

CHANGED job 'a22k_19601101_fc00_INI' status to COMPLETED

CHANGED job 'a22k_19601101_fc01_INI' status to COMPLETED

[CRITICAL] Unhandled exception on Autosubmit: [Errno 21] Is a directory: '/esarchive/autosubmit/a22k/tmp/LOG_a22k/'

Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 434, in parse_args
    args.expand, args.expand_status, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1503, in recovery
    job.platform.get_logs_files(expid, job.remote_logs)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/platform.py", line 208, in get_logs_files
    self.get_files([job_out_filename, job_err_filename], False, 'LOG_{0}'.format(exp_id))
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/platform.py", line 185, in get_files
    self.get_file(filename, must_exist, relative_path)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 160, in get_file
    os.remove(file_path)
OSError: [Errno 21] Is a directory: '/esarchive/autosubmit/a22k/tmp/LOG_a22k/'

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 31, 2019, 17:47

Hi @ rmahmood , you can use setstatus filtering by STATUS, CHUNK, TYPE, etc:

https://autosubmit.readthedocs.io/en/latest/usage/setstatus.html

There's even a newer option combining different filters that @wuruchi can explain. But I guess it would be enough using CHUNK.

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Nov 4, 2019, 10:34

Hi All,

Thank you for the suggestions. Somehow, the autosubmit recovery works with the default version of the autosubmit, it was not working with 3.12.0b and 3.12.1b. 

After doing recovery, I can now run the simulation using default version of the autosubmit.
I do not know what has changed between previous week and today (Monday) but jobs are being submitted normally, so far! 

Thanks
Rashed

**Comment by kinow** [comment]
In GitLab by @pablohe on Nov 4, 2019, 10:52

Good to know @ rmahmood 

Let me know if you have any problem.

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Nov 4, 2019, 10:55

Hi @pablohe ,

I see some error messages:

`[ERROR] Command sbatch -D /gpfs/scratch/bsc32/bsc32663/a22k/LOG_a22k /gpfs/scratch/bsc32/bsc32663/a22k/LOG_a22k/a22k_20071101_fc09_4_CMORATM.cmd in mn2.bsc.es failed with error message: sbatch: error: Batch job submission failed: Socket timed out on send/recv operation`

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 4, 2019, 10:57

hi @ rmahmood ,

I'm also having problems with the sockets, seems like mn4 is acting wrongly( it is not from AS)

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Nov 4, 2019, 10:59

Thanks @dbeltrankyl ,
Good to know that I am not the only one with this issue.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 4, 2019, 11:03

I reported to support, will notify the news

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 4, 2019, 15:00

Hi @ rmahmood 

Sorry for the issues, support said that It should work properly again, also recovery should work on 3.12.0b again in a few minutes

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Nov 6, 2019, 14:12

Hi @dbeltrankyl ,

I am not sure if autosubmit is running, it seems it is:

`(base) WS- /esarchive/autosubmit/a22k  > ps aux | grep a22k`

`rmahmood  7548  0.0  0.0  10548  1552 pts/0    S+   14:06   0:00 grep --color=auto a22k
rmahmood 20403  0.4  2.0 845024 258720 pts/0   Sl   Nov04  14:46 /shared/earth/software/Python/2.7.9-foss-2015a/bin/python /shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/bin/autosubmit run a22k`

However, I do not see any jobs running/queuing on MN4. Any thoughts?

Thanks
Rashed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 6, 2019, 14:58

Hi @ rmahmood ,

I don't know, if it is running it should trying to do something otherwise it just stop the ejecution , try to relaunch autosubmit it shouldn't affect to anything however, I still recomend to use 3.12.0b instead of 3.11-hotfix since 3.11 doesn't have updates since 1+year ago

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 18, 2019, 09:23

Hi @ rmahmood , where you able to run the experiment?

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Nov 18, 2019, 09:26

Hi @mcastril ,

Yes, Thank you. I would close this issue.

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Nov 18, 2019, 09:26

closed
