### ISSUE TITLE
[ERROR] Can not create ssh connection to mn2.bsc.es: Connection refused

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#458]
In GitLab by @ rmahmood on Dec 28, 2019, 12:19

Hi @dbeltrankyl , @mcastril ,@kserradell , @pablohe , @pabretonniere 

I am trying to run simulation using "nohup autosubmit run a22k &" , however, I am getting the following connection refusal errors:

`316 of 8584 jobs remaining (12:09)
Jobs ready for marenostrum4: 15
[ERROR] Can not create ssh connection to mn2.bsc.es: Connection refused
[ERROR] Could not create the DIR /gpfs/scratch/bsc32/bsc32663/a22k/LOG_a22k on HPC mn2.bsc.es
[ERROR] Can not send command rm  /gpfs/scratch/bsc32/bsc32663/a22k/LOG_a22k/a22k_19611101_fc00_1_SIM.cmd /gpfs/scratch/bsc32/bsc32663/a22k/LOG_a22k/a22k_19611101_fc00_2_SIM.cmd /gpfs/scratch/bsc32/bsc32663/a22k/LOG_a22k/a22k_19611101_fc00_3_SIM.cmd /gpfs/scratch/bsc32/bsc32663/a22k/LOG_a22k/a22k_19611101_fc00_4_SIM.cmd /gpfs/scratch/bsc32/bsc32663/a22k/LOG_a22k/a22k_19611101_fc00_5_SIM.cmd to mn2.bsc.es: 'NoneType' object has no attribute 'open_session'
[ERROR] Can not send file /esarchive/autosubmit/a22k/tmp/a22k_19611101_fc00_1_SIM.cmd to /gpfs/scratch/bsc32/bsc32663/a22k/LOG_a22k/a22k_19611101_fc00_1_SIM.cmd
[ERROR] marenostrum4 submission failed
[CRITICAL] Unhandled exception on Autosubmit: 'NoneType' object has no attribute 'open_sftp_client'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 375, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 790, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 833, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters)
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/job/job_packages.py", line 87, in submit
    self._send_files()
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/job/job_packages.py", line 293, in _send_files
    self.platform.send_file(self._job_scripts[job.name], check=False)
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 128, in send_file
    ftp = self._ssh.open_sftp()
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/client.py", line 379, in open_sftp
    return self._transport.open_sftp_client()
AttributeError: 'NoneType' object has no attribute 'open_sftp_client'`

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Dec 28, 2019, 16:59

It seems to work now...

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Dec 28, 2019, 17:00

closed
