### ISSUE TITLE
Pipeline for test phase is failing when using python 2.

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#460]
In GitLab by @dbeltrankyl on Jan 7, 2020, 09:41

Hi @wuruchi , @mcastril , @kserradell.

On Friday, I pushed some changes to 3.12.1 version and I notice today that the pipeline is displaying an [issue](https://earth.bsc.es/gitlab/es/autosubmit/-/jobs/7434)

So far I test:

* 4.0 (python 3) working properly.
* 3.12.1 failing, older commits fail as well when using the retry option on the test phase.
* 3.12.0 failing, same error.

Edit: note that this only affects to the mock tests that autosubmit perform

**Comment by kinow** [comment]
In GitLab by @kserradell on Jan 7, 2020, 10:03

@dbeltrankyl in the logs I see:

```
--------------------------------------------------------------------------------
    WARNING: saga-python is deprecated!

    Your application will still work - but "saga-python" has been renamed to
    "radical.saga".  Please change your imports from

        import saga

    to

        import radical.saga as saga

    No other changes are needed.  This backward compatibility package will
    disappear in version 1.0, planned for end 2019.
--------------------------------------------------------------------------------
```
Is this the error?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 7, 2020, 10:06

No, it is just a warning that was happening before this issue.

the issue is there:

```
Traceback (most recent call last):
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/nose/core.py", line 66, in run
    result.printErrors()
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/nose/result.py", line 110, in printErrors
    self.config.plugins.report(self.stream)
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/nose/plugins/cover.py", line 183, in report
    self.coverInstance.stop()
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/coverage/control.py", line 670, in combine
    self.get_data()
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/coverage/control.py", line 696, in get_data
    if self._collector and self._collector.flush_data():
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/coverage/collector.py", line 425, in flush_data
    self.covdata.add_lines(self.mapped_file_dict(self.data))
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/coverage/sqldata.py", line 436, in add_lines
    self._choose_lines_or_arcs(lines=True)
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/coverage/sqldata.py", line 493, in _choose_lines_or_arcs
    with self._connect() as con:
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/coverage/sqldata.py", line 1017, in __enter__
    self.con.__enter__()
  File "/home/gitlab-runner/miniconda2/envs/autosubmit2/lib/python2.7/site-packages/mock/mock.py", line 697, in __getattr__
    raise AttributeError(name)
AttributeError: __enter__
```

Apparently, is an issue with the sql

**Comment by kinow** [comment]
In GitLab by @kserradell on Jan 7, 2020, 10:09

Can we have a look together?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 7, 2020, 11:46

closed

**Comment by kinow** [comment]
In GitLab by @kserradell on Jan 7, 2020, 11:47

Great!
