### ISSUE TITLE
my runs crash

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#463]
In GitLab by @ ekarnezi on Jan 15, 2020, 15:51

Hello. I have four experiments (a2cw, a2cx, a2cy and a2cz) and all crash with the same reason. For example for a2cw:

a2cw_20151130_000_3_ARCHIVE submitted
Jobs ready for power9: 1
^[[31m[ERROR] Can not send command mkdir -p /gpfs/scratch/bsc32/bsc32403/a2cw/LOG_a2cw to power9: 'NoneType' object has no attribute 'open_session'^[[0m^[[39m
^[[31m[ERROR] Could not create the DIR /gpfs/scratch/bsc32/bsc32403/a2cw/LOG_a2cw on HPC power9^[[0m^[[39m
^[[31m[ERROR] Can not send file /esarchive/autosubmit/a2cw/tmp/a2cw_20151130_000_1_REDUCE.cmd to /gpfs/scratch/bsc32/bsc32403/a2cw/LOG_a2cw/a2cw_20151130_000_1_REDUCE.cmd^[[0m^[[39m
^[[31m[ERROR] power9 submission failed^[[0m^[[39m
^[[31m[CRITICAL] Unhandled exception on Autosubmit: 'NoneType' object has no attribute 'open_sftp_client'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 375, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 790, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 833, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters)
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/job/job_packages.py", line 87, in submit
    self._send_files()
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/job/job_packages.py", line 115, in _send_files
    self.platform.send_file(self._job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 128, in send_file
    ftp = self._ssh.open_sftp()
  File "/shared/earth/software/autosubmit/3.11.0-hotfix-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/client.py", line 379, in open_sftp
    return self._transport.open_sftp_client()
AttributeError: 'NoneType' object has no attribute 'open_sftp_client'

what could be the reason?

Thanks,
Elina

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 20, 2020, 09:40

Hi @ebergas, 

Sorry, I was on sick leave.

If you still have troubles, seems like a:

* permissions issue 
* Or most likely, login of power9 was having issues

**Comment by kinow** [comment]
In GitLab by @ebergas on Jan 20, 2020, 10:03

@ ekarnezi

**Comment by kinow** [comment]
In GitLab by @ ekarnezi on Jan 20, 2020, 11:33

Hi @dbeltrankyl, thank you for answering. Yes eventually in platforms_expid.conf file I had written something wrong and it couldn't log in power9. The issue is solved.

**Comment by kinow** [comment]
In GitLab by @ ekarnezi on Jan 20, 2020, 11:33

closed
