### ISSUE TITLE
setstatus failes for some job types with AS 3.12.1b

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#467]
In GitLab by @ mklose on Jan 14, 2020, 17:22

It seems that with the autosubmit version 3.12.1b, the setstatus -ft command fails for some job types. Specifically, I cam having problems with LOCAL_SEND_SOURCE, LOCAL_SEND_INITIAL, and LOCAL_SEND_STATIC. Could that be related to them having two underscores in their name (REMOTE_COMPILE works). Or am I doing anything wrong? I am trying, for example 
`autosubmit setstatus -s -t WAITING -ft "LOCAL_SEND_SOURCE REMOTE_COMPILE" -np <expid>`

and I get the error 

`Section Validation Message
        List of sections provided has a format error. Perhaps you were trying to use -fl instead.
[CRITICAL] Error in the supplied input for -ft.`

@gmontanepinto Does this work for you or is this an issue (and if so, of auto-monarch or of autosubmit)? 

Thanks!

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Jan 14, 2020, 18:04

I'm getting the same error, so it seems a problem with the underscores. @dbeltrankyl, is this a bug or should we definitely change the name of our jobs?

**Comment by kinow** [comment]
In GitLab by @ mklose on Jan 17, 2020, 08:56

Hi @gmontanepinto @dbeltrankyl 

Any news on this? 

Thanks!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 20, 2020, 09:26

Hi @ mklose , @gmontanepinto  

Sorry I was on sick leave, 

I believe this was fixed on 4.0 where I found a bug with the regex, I'll look for propagate that change into 3.12.1b aswell

**Comment by kinow** [comment]
In GitLab by @ mklose on Jan 20, 2020, 09:28

Excellent! Thanks @dbeltrankyl Could you drop us a line when this is done? Thanks! 

Hope you are well again!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 20, 2020, 16:44

Hi @ mklose , 

I just updated 3.12.1b with this and more changes, it should work now I changed again the regex of the .conf parser since the current one and the one that I did on 4.0 had some bugs.

I tested it so hopefully, there are no issues.

All chars inside a [] are now avaliable except: 
```
 1. [ 
 2. ]
 3. #
 4.  (white space)
 5. \t (tabs)
 6. \n (new lines)
```

**Comment by kinow** [comment]
In GitLab by @ mklose on Jan 20, 2020, 16:51

Hi @dbeltrankyl 

Thanks very much. I have tried and for any setstatus, I now get the following error message: 

`[CRITICAL] Unhandled exception on Autosubmit: global name '_check_Ownership' is not defined
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 482, in parse_args
    args.group_by, args.expand, args.expand_status, args.notransitive,args.check_wrapper, args.detail)
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 2997, in set_status
    if not _check_Ownership(expid):
NameError: global name '_check_Ownership' is not defined`

Any idea what's going wrong?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 20, 2020, 16:54

oh, my mistake there was a commit unpushed, I'll solve in a few minutes

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 20, 2020, 17:06

Hi, It should work now.

the issue was related to a new security option now all commands that are able to modify something of your experiment ( like run, create..) can't be used if you aren't the owner ( to change owner there is the command migrate) 

Also, if you have issues with autosubmit run, use once autosubmit run -v. Related to another security mechanism to only run an experiment if the experiment version is equal to the autosubmit current version. What does -v is to update AUTOSUBMIT_VERSION parameter of autosubmit.conf, if that parameter is empty or equal to the autosubmit version that is running, you can use autosubmit run.

**Comment by kinow** [comment]
In GitLab by @ mklose on Jan 20, 2020, 17:24

Thanks @dbeltrankyl 

Hmm, still looks like there is a problem. Here is what I did: 

mklose@ bscearth362:/arbitrary_folder/> autosubmit setstatus -s -t WAITING -ft LOCAL_SEND_SPINUP -np a2f0 
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
platforms_a2f0.conf OK
jobs_a2f0.conf OK
autosubmit_a2f0.conf OK
expdef_a2f0.conf  OK
Configuration files OK


Section Validation Message 
	List of sections provided has a format error. Perhaps you were trying to use -fl instead.
[CRITICAL] Error in the supplied input for -ft.


Sorry about the messed up formatting...

**Comment by kinow** [comment]
In GitLab by @mcastril on Jan 20, 2020, 17:25

I move this issue to Autosubmit project.

As @dbeltrankyl said, we included these two new checks for the tranquillity of our users:

* Users can only "change status"/"run"/"delete" and experiment of their ownership. Avoid problems due to mistakes typing experiments names.
* Users can only run an experiment with the Autosubmit version that was used to create that experiment/config. Unless "run -v" is used or the autosubmit.conf value is updated.

**Comment by kinow** [comment]
In GitLab by @mcastril on Jan 20, 2020, 17:25

moved from auto-monarch#264

**Comment by kinow** [comment]
In GitLab by @ mklose on Jan 20, 2020, 17:27

Thanks @mcastril 

Yes, I noticed the second point about the version - but there was a helpful prompt telling me what I need to do. Thanks for that :)

**Comment by kinow** [comment]
In GitLab by @ mklose on Jan 20, 2020, 18:04

As my previous post overlapped with moving this issue, I just want to make sure you saw that there still seems to be a problem...

No rush, just making sure you saw it @dbeltrankyl @mcastril 

Thanks!!!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 21, 2020, 16:05

Hello, 

It seems that there were some over-restrictions on the set status filters when a section had more than one _.

it should work properly now.

**Comment by kinow** [comment]
In GitLab by @ mklose on Jan 24, 2020, 10:54

Great. I just tried and it seems to work now. 

Thanks @dbeltrankyl

**Comment by kinow** [comment]
In GitLab by @ mklose on Jan 24, 2020, 10:54

closed
