### ISSUE TITLE
Error in 3.12.0b

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#486]
In GitLab by @mcastril on Feb 17, 2020, 13:10

Hi @dbeltrankyl , do you know what could be happening?

Seems an error when parsing the arguments for Autosubmit run.

```
nohup autosubmit run a28v &
[ERROR] marenostrum4 submission failed
[CRITICAL] Unhandled exception on Autosubmit: list index out of range
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 417, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1077, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1133, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters,inspect)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/job/job_packages.py", line 97, in submit
    self._do_submission()
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/job/job_packages.py", line 137, in _do_submission
    job.id = self.platform.submit_job(job, job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 245, in submit_job
    job_id = self.get_submitted_job_id(self.get_ssh_output())
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/platforms/slurmplatform.py", line 77, in get_submitted_job_id
    return output.split(' ')[3]
IndexError: list index out of range
```

The run by @thomasarsouze was:

`nohup autosubmit run a28v &`

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 17, 2020, 13:53

Hi @mcastril @thomasarsouze ,

Queue is invalid for POST job (has CNS account permissions for `queue=debug? )`

```
[WARNING] 2020-02-17 09:13:38,616 Command sbatch -D /gpfs/scratch/cns61/cns61280/a28v/LOG_a28v /gpfs/scratch/cns61/cns61280/a28v/LOG_a28v/a28v_19500101_fc0_225_POST.cmd in mn4-res2 warning: sbatch: error: Batch job submission failed: Invalid qos specification

2020-02-17 09:13:38,617 Command sbatch -D /gpfs/scratch/cns61/cns61280/a28v/LOG_a28v /gpfs/scratch/cns61/cns61280/a28v/LOG_a28v/a28v_19500101_fc0_225_POST.cmd in mn4-res2 successful with out message: 
 
```

It just failed to submit the job

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 17, 2020, 14:44

Thanks @dbeltrankyl , so in the end is an error similar to the one I had this morning https://earth.bsc.es/gitlab/es/autosubmit/issues/485:

However, while the logfile is correctly pointing out the cause, the Unhandled exception is misleading (I didn't realize there could be a different error in the log). Could you ensure the exception is caught so the user knows it is not an internal AS error?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 17, 2020, 14:45

I did that catch on 3.12.1b, do you mean to also update the 3.12.0b with that exception?

**Comment by kinow** [comment]
In GitLab by @thomasarsouze on Feb 17, 2020, 14:48

thx @dbeltrankyl for point this out.

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 17, 2020, 14:48

Thanks @dbeltrankyl . If it's corrected in 3.12.1b I think it is enough by now. We said to only do critical bugfixes on 3.12.0b.

Anyway, having the issue created people can find this conversation.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 20, 2020, 15:34

closed

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 24, 2020, 10:41

Reported by @wuruchi in #491:

```
[WARNING] Command /gpfs/scratch/bsc32/bsc32985/a294/LOG_a294/submit_marenostrum4.sh in mn1.bsc.es warning: sbatch: fatal: a294_20000101_fc0_1_ASIM.cmd: line 14: Unexpected `:` in [ :00]

sbatch: fatal: a294_20000101_fc1_1_ASIM.cmd: line 14: Unexpected `:` in [ :00]

sbatch: fatal: a294_20000101_fc2_1_ASIM.cmd: line 14: Unexpected `:` in [ :00]

[ERROR] marenostrum4 submission failed
[CRITICAL] Unhandled exception on Autosubmit: list index out of range
Traceback (most recent call last):
  File "/home/Earth/wuruchi/AutosubmitRealDeal/autosubmit-master/autosubmit/autosubmit/autosubmit.py", line 438, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive,args.update_version)
  File "/home/Earth/wuruchi/AutosubmitRealDeal/autosubmit-master/autosubmit/autosubmit/autosubmit.py", line 1264, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence,hold=False):
  File "/home/Earth/wuruchi/AutosubmitRealDeal/autosubmit-master/autosubmit/autosubmit/autosubmit.py", line 1362, in submit_ready_jobs
    job.id = str(jobs_id[i])
IndexError: list index out of range
```

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 24, 2020, 10:41

reopened

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 24, 2020, 11:06

Hi @mcastril ,

I'll check but the issue is on 3.12.1b not 3.12.0b no? It is on the master branch

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 24, 2020, 11:54

Yes, that is what @wuruchi said but ask him please, if you need more details

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 25, 2020, 09:29

Thanks @dbeltrankyl
