### ISSUE TITLE
Deploying As in the new image

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#487]
In GitLab by @kserradell on Feb 17, 2020, 14:41

I'm installing AS in the new image. For other reasons, I can only install `saga-python==0.60`. The tools seems to be installed correctly but on execution I have this annoying message:

```
[kserrade@ bscearth408 ~ ]$ autosubmit -v


--------------------------------------------------------------------------------
    WARNING: saga-python is deprecated!

    Your application will still work - but "saga-python" has been renamed to
    "radical.saga".  Please change your imports from

        import saga

    to

        import radical.saga as saga

    No other changes are needed.  This backward compatibility package will
    disappear in version 1.0, planned for end 2019.
--------------------------------------------------------------------------------

3.11.0-hotfix
```

Should these imports be updated?

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 17, 2020, 14:46

Yes we should, I agree. We should not load any dependency that is not used.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 17, 2020, 15:10

`coverage=4.5.4`
`matplotlib == 2.2.3`
`networkx == 2.2`
`pydotplus == 2.0.2`


```
[CRITICAL] Unhandled exception on Autosubmit: Program terminated with status: -11. stderr follows: []
Traceback (most recent call last):
  File "/shared/earth/easybuild/opensuse-leap/15.1/x86_64/software/autosubmit/3.11.0-hotfix-foss-2019b-Python-2.7.16/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 399, in parse_args
    args.expand_status, args.notransitive)
  File "/shared/earth/easybuild/opensuse-leap/15.1/x86_64/software/autosubmit/3.11.0-hotfix-foss-2019b-Python-2.7.16/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/autosubmit.py", line 1983, in create
    groups=groups_dict)
  File "/shared/earth/easybuild/opensuse-leap/15.1/x86_64/software/autosubmit/3.11.0-hotfix-foss-2019b-Python-2.7.16/lib/python2.7/site-packages/autosubmit-3.11.0_hotfix-py2.7.egg/autosubmit/monitor/monitor.py", line 273, in generate_output
    graph.write_pdf(output_file)
  File "build/bdist.linux-x86_64/egg/pydotplus/graphviz.py", line 1810, in <lambda>
    prog=self.prog: self.write(path, format=f, prog=prog)
  File "build/bdist.linux-x86_64/egg/pydotplus/graphviz.py", line 1918, in write
    fobj.write(self.create(prog, format))
  File "build/bdist.linux-x86_64/egg/pydotplus/graphviz.py", line 2032, in create
    status, stderr_output))
InvocationException: Program terminated with status: -11. stderr follows: []
```

Now that I remember, I had this error on python 3, not on python 2

**Comment by kinow** [comment]
In GitLab by @kserradell on Feb 17, 2020, 17:00

I'm using Python 2.7.16...

**Comment by kinow** [comment]
In GitLab by @kserradell on Feb 17, 2020, 17:18

@dbeltrankyl, I've been able to use pydotplus in the new image

```
[kserrade@ bscearth408 ~ ]$ module load Python/2.7.16-GCCcore-8.3.0
[kserrade@ bscearth408 ~ ]$ python
Python 2.7.16 (default, Feb 12 2020, 19:10:22)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydotplus
>>> graph_a = pydotplus.graph_from_dot_file('example.dot')
>>> graph_a.write_svg('test.svg')
True
>>> graph_a.write_pdf('test.pdf')
True
>>>
```

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 18, 2020, 10:34

I think you were right @dbeltrankyl . We have seen this error multiple times. Some times it was a problem with Codacy:

https://earth.bsc.es/gitlab/es/autosubmit/issues/460#note_65303
https://earth.bsc.es/gitlab/es/autosubmit/issues/446#note_62046

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 18, 2020, 14:06

hi @kserradell ,

I reduced the failure into subprocess or the command itself (think the issue is on this command):

```
eadmin@ bscearth408:~/easybuild> /shared/earth/easybuild/opensuse-leap/15.1/x86_64/software/Graphviz/2.40.1-foss-2019b/bin/dot "-Tpdf" /tmp/tmpRNgFzQ
Segmentation fault (core dumped)
```

The folder where store a temporal file with the graph contents `/tmp`

File generated: `/tmp/tmpRNgFzQ `( apparently is totally fine)

```
eadmin@ bscearth408:~/easybuild> cat /tmp/tmpRNgFzQ 
digraph G {
subgraph Legend {
label=Legend;
rank=source;
UNKNOWN [fillcolor=white, shape=box, style=""];
WAITING [fillcolor=gray, shape=box, style=filled];
READY [fillcolor=lightblue, shape=box, style=filled];
SUBMITTED [fillcolor=cyan, shape=box, style=filled];
HELD [fillcolor=salmon, shape=box, style=filled];
QUEUING [fillcolor=pink, shape=box, style=filled];
RUNNING [fillcolor=green, shape=box, style=filled];
COMPLETED [fillcolor=yellow, shape=box, style=filled];
FAILED [fillcolor=red, shape=box, style=filled];
SUSPENDED [fillcolor=orange, shape=box, style=filled];
}

subgraph Experiment {
label=a2lp;
a2lp_LOCAL_SETUP [fillcolor=lightblue, shape=box, style=filled];
a2lp_REMOTE_SETUP [fillcolor=gray, shape=box, style=filled];
a2lp_LOCAL_SETUP -> a2lp_REMOTE_SETUP;
a2lp_20000101_fc0_INI [fillcolor=gray, shape=box, style=filled];
a2lp_REMOTE_SETUP -> a2lp_20000101_fc0_INI;
a2lp_20000101_fc0_1_SIM [fillcolor=gray, shape=box, style=filled];
a2lp_20000101_fc0_INI -> a2lp_20000101_fc0_1_SIM;
a2lp_20000101_fc0_1_POST [fillcolor=gray, shape=box, style=filled];
a2lp_20000101_fc0_1_SIM -> a2lp_20000101_fc0_1_POST;
a2lp_20000101_fc0_1_CLEAN [fillcolor=gray, shape=box, style=filled];
a2lp_20000101_fc0_1_POST -> a2lp_20000101_fc0_1_CLEAN;
a2lp_20000101_fc0_1_TRANSFER [fillcolor=gray, shape=box, style=filled];
a2lp_20000101_fc0_1_CLEAN -> a2lp_20000101_fc0_1_TRANSFER;
a2lp_20000101_fc0_LOCALPOST [fillcolor=gray, shape=box, style=filled];
a2lp_20000101_fc0_1_TRANSFER -> a2lp_20000101_fc0_LOCALPOST;
a2lp_20000101_fc0_PLOT [fillcolor=gray, shape=box, style=filled];
a2lp_20000101_fc0_LOCALPOST -> a2lp_20000101_fc0_PLOT;
}

}
```

subprocess parameters: `['/shared/earth/easybuild/opensuse-leap/15.1/x86_64/software/Graphviz/2.40.1-foss-2019b/bin/dot', '-Tpdf', '/tmp/tmpRNgFzQ']`

Status reported code:` -11.` (the expected output is 0)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 18, 2020, 14:16

Simplifying the graph:


if subgraph legend is deleted...

```
digraph G {
subgraph Experiment {
label=a2lp;
a2lp_LOCAL_SETUP [fillcolor=lightblue, shape=box, style=filled];
a2lp_REMOTE_SETUP [fillcolor=gray, shape=box, style=filled];
a2lp_LOCAL_SETUP -> a2lp_REMOTE_SETUP;
a2lp_20000101_fc0_INI [fillcolor=gray, shape=box, style=filled];
a2lp_REMOTE_SETUP -> a2lp_20000101_fc0_INI;
a2lp_20000101_fc0_1_SIM [fillcolor=gray, shape=box, style=filled];
a2lp_20000101_fc0_INI -> a2lp_20000101_fc0_1_SIM;
a2lp_20000101_fc0_1_POST [fillcolor=gray, shape=box, style=filled];
a2lp_20000101_fc0_1_SIM -> a2lp_20000101_fc0_1_POST;
a2lp_20000101_fc0_1_CLEAN [fillcolor=gray, shape=box, style=filled];
a2lp_20000101_fc0_1_POST -> a2lp_20000101_fc0_1_CLEAN;
a2lp_20000101_fc0_1_TRANSFER [fillcolor=gray, shape=box, style=filled];
a2lp_20000101_fc0_1_CLEAN -> a2lp_20000101_fc0_1_TRANSFER;
a2lp_20000101_fc0_LOCALPOST [fillcolor=gray, shape=box, style=filled];
a2lp_20000101_fc0_1_TRANSFER -> a2lp_20000101_fc0_LOCALPOST;
a2lp_20000101_fc0_PLOT [fillcolor=gray, shape=box, style=filled];
a2lp_20000101_fc0_LOCALPOST -> a2lp_20000101_fc0_PLOT;
}

}
```

`eadmin@ bscearth408:~/easybuild> /shared/earth/easybuild/opensuse-leap/15.1/x86_64/software/Graphviz/2.40.1-foss-2019b/bin/dot -Tpdf /tmp/tmpRNgFzQ > example.pdf`

A pdf was generated correctly ( without job status cause they was deleted)

**Comment by kinow** [comment]
In GitLab by @kserradell on Feb 18, 2020, 14:22

Thanks for the effort, @dbeltrankyl. I'm in a telco. As soon as I finish, I'll take a look.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 18, 2020, 14:25

@kserradell thanks Kim.

The last thing, apparently this was a bug in GraphViz/2.40.1 so only should be a matter of changing the version to one that works like 2.38 (based on below link) or in the one superior that has this bug solved ( based on a commit in the comment section)


https://gitlab.com/graphviz/graphviz/issues/1225

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 18, 2020, 14:31

```
62) Graphviz/2.40.1-foss-2019b
eadmin@ bscearth408:~> module unload Graphviz/2.40.1-foss-2019b
eadmin@ bscearth408:~> autosubmit monitor a2lp

same error 
but.. now is being used..

eadmin@ bscearth408:~> /usr/bin/dot -v

```
dot - graphviz version 2.40.1 (20161225.0304) 

which is the same version that have the mentioned bug

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 18, 2020, 14:38

And finally, 

```
dbeltran@ bscearth375:~> /usr/bin/dot -v
dot - graphviz version 2.38.0 (20140413.2041)
```

So it must be the difference between the actual image and the newer.

Edit: I guess that the ideal should use this version in the newer image(or other functional) (although I don't know if that can be changed if isn't with modules). Like AutoSubmit has this problem,  other software could also rely on `/usr/bin/dot` in some part of its code and will break with the same bug.

**Comment by kinow** [comment]
In GitLab by @kserradell on Feb 18, 2020, 14:57

Great debug @dbeltrankyl!

I've built `Graphviz/2.38.0-foss-2019b` and it works fine now!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 20, 2020, 15:30

closed

**Comment by kinow** [comment]
In GitLab by @mcastril on Apr 22, 2020, 16:44

Hi @dbeltrankyl . I think Saga was not removed in the end. Could you remove it ? I gives problems on new installations.

**Comment by kinow** [comment]
In GitLab by @mcastril on Apr 23, 2020, 19:39

Well, if we are sure by searching in the code (that I guess we are) that the library is not used **anywhere**... Then by doing some simple tests we could go on, because I don't think it only would fail in very certain circumstances but it would prompt more obvious errors when importing libraries and so.

**Comment by kinow** [comment]
In GitLab by @kserradell on Apr 27, 2020, 11:09

Sorry. I had to update the server and it seems I broke something. Let me take a look.
