### ISSUE TITLE
Autosubmit removing the first line of the log .out

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#491]
In GitLab by @mcastril on Feb 20, 2020, 18:48

This is a very odd issue. 

You maybe know that in Auto-EC-Earth we output in the SIM templates the JOB_ID of the SIM job. After a refactor I moved this echo to the beginning of the log, so it would be the very first line of the log.

On the other hand, Autosubmit 3.12.1b prepends every log with the JOBID of that log. 

What it is strange is that in my run Autosubmit **substituted** my JOB_ID output with the one it prints in the local copy of the log. The fact that both lines refer to the JOB_ID I think it is just a coincidence, but I think it could occur that it overwrites the first line of other logs with other information.

Example:

Remote log: /gpfs/scratch/bsc32/bsc32252/a2jn/LOG_a2jn/a2jn_19900101_fc00_1_SIM.20200220162907.out

```
SLURM_JOB_ID: 8883113
*II* !!!! CMIP FIX YEAR SETTINGS:
*II* ifs_cmip_fixyear:  1850
*II* lpjg_fixNDepAfter: -1
*II* lpjg_fixLUAfter:   -1
*II* !!!!
```

Local log: /esarchive/autosubmit/a2jn/tmp/LOG_a2jn/a2jn_19900101_fc00_1_SIM.20200220162907.out

```
[INFO] JOBID=8883113

*II* !!!! CMIP FIX YEAR SETTINGS:
*II* ifs_cmip_fixyear:  1850
*II* lpjg_fixNDepAfter: -1
*II* lpjg_fixLUAfter:   -1
*II* !!!!
```

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 21, 2020, 10:46

Yep, it's a bug. Working on it, since I introduced that feature.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 21, 2020, 11:01

[https://earth.bsc.es/gitlab/es/autosubmit/merge_requests/157](https://earth.bsc.es/gitlab/es/autosubmit/merge_requests/157)

A fix has been implemented. Let's hope it has not caused much trouble!

By the way, I got the index out of bounds error while running a294 under the most recent code in the master branch.

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 21, 2020, 12:31

Thanks @wuruchi . 

> I got the index out of bounds error while running a294 

Which was that error?

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 21, 2020, 12:38

Something similar to: https://earth.bsc.es/gitlab/es/autosubmit/issues/486

I will run it again to show the exact message.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 21, 2020, 12:45

@mcastril 

```
[WARNING] Command /gpfs/scratch/bsc32/bsc32985/a294/LOG_a294/submit_marenostrum4.sh in mn1.bsc.es warning: sbatch: fatal: a294_20000101_fc0_1_ASIM.cmd: line 14: Unexpected `:` in [ :00]

sbatch: fatal: a294_20000101_fc1_1_ASIM.cmd: line 14: Unexpected `:` in [ :00]

sbatch: fatal: a294_20000101_fc2_1_ASIM.cmd: line 14: Unexpected `:` in [ :00]

[ERROR] marenostrum4 submission failed
[CRITICAL] Unhandled exception on Autosubmit: list index out of range
Traceback (most recent call last):
  File "/home/Earth/wuruchi/AutosubmitRealDeal/autosubmit-master/autosubmit/autosubmit/autosubmit.py", line 438, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive,args.update_version)
  File "/home/Earth/wuruchi/AutosubmitRealDeal/autosubmit-master/autosubmit/autosubmit/autosubmit.py", line 1264, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence,hold=False):
  File "/home/Earth/wuruchi/AutosubmitRealDeal/autosubmit-master/autosubmit/autosubmit/autosubmit.py", line 1362, in submit_ready_jobs
    job.id = str(jobs_id[i])
IndexError: list index out of range
```

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 24, 2020, 10:40

Thanks @wuruchi I am adding your comment to #486.
