### ISSUE TITLE
autosubmit refresh fails

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#492]
In GitLab by @hervepetetin on Feb 21, 2020, 12:19

Hi , 
I don't know if it's related to the recent issues with autosubmit and esarchive but I cannot refresh my exp :

```
hpetetin@ bscesautosubmit01:/esarchive/autosubmit/a2kf> autosubmit refresh a2kf 
expdef_a2kf.conf  OK
Using project folder: /esarchive/autosubmit/a2kf/proj
Cloning master https://earth.bsc.es/gitlab/hpetetin/opmos.git into none/esarchive/autosubmit/a2kf/proj
[WARNING] Command cd none/esarchive/autosubmit/a2kf/proj;  git clone --single-branch  --recursive -b master https://earth.bsc.es/gitlab/hpetetin/opmos.git opmos in plogin1 warning: bash: line 0: cd: none/esarchive/autosubmit/a2kf/proj: No such file or directory

fatal: unable to access 'https://earth.bsc.es/gitlab/hpetetin/opmos.git/': Failed to connect to earth.bsc.es port 443: Connection timed out

Project folder updated
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 21, 2020, 12:21

Hi,

I think is my fault let me check 10 min

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 21, 2020, 12:22

@hervepetetin ,

As a workaround, until I fix it load 3.12.0b, refresh the experiment and load again 3.12.1b

**Comment by kinow** [comment]
In GitLab by @hervepetetin on Feb 21, 2020, 12:24

ok thanks

**Comment by kinow** [comment]
In GitLab by @hervepetetin on Feb 21, 2020, 12:24

let me know when I can use again the 3.12.1b

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 21, 2020, 12:30

It should be solved now. Can you check? thanks and apologies ,

there was one commit that shouldn't go throught

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 27, 2020, 13:48

closed

**Comment by kinow** [comment]
In GitLab by @hervepetetin on Jul 3, 2020, 13:02

reopened

**Comment by kinow** [comment]
In GitLab by @hervepetetin on Jul 3, 2020, 13:04

Hi, 
I am trying an old script with AS, and there is an issue when I refresh:
```
hpetetin@ bscesautosubmit01:/esarchive/autosubmit/a2js/conf> module load autosubmit/3.13.0b-foss-2015a-Python-2.7.9
hpetetin@ bscesautosubmit01:/esarchive/autosubmit/a2js/conf> autosubmit refresh a2js
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/bin/autosubmit", line 4, in <module>
    __import__('pkg_resources').run_script('autosubmit==3.13.0b0', 'autosubmit')
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/EGG-INFO/scripts/autosubmit", line 29, in <module>
    from autosubmit.autosubmit import Autosubmit
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/autosubmit.py", line 29, in <module>
    from monitor.monitor import Monitor
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/monitor/monitor.py", line 39, in <module>
    from diagram import create_bar_diagram
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/monitor/diagram.py", line 22, in <module>
    import matplotlib.pyplot as plt
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/shared/earth/software/matplotlib/1.5.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

Any idea what I am doing wrong here? Thanks

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 3, 2020, 15:11

Hi @hervepetetin , Sorry I didn't know that the mail notifications weren't working

It is the first time I see this error, did you loaded some other module or have something being loaded on the bashrc? @mcastril do you have any clue?

**Comment by kinow** [comment]
In GitLab by @hervepetetin on Jul 3, 2020, 15:22

actually refresh is working in my exp a2qw, so maybe something went wrong with a2js, I'll try with a new exp

**Comment by kinow** [comment]
In GitLab by @mcastril on Jul 3, 2020, 16:22

It reminds me to this issue #551 . But I don't think it is related, because that was in the remote , and this problem seems a local one.

In any case I think it's normal to have UTF locale encoding:

```
env | grep UTF
LANG=es_ES.UTF-8
```

**Comment by kinow** [comment]
In GitLab by @hervepetetin on Jul 3, 2020, 16:24

Maybe it was due to the fact that the exp was created with another version of AS?

I started a new exp (a2z6) to see if the issue persists, and when creating the exp, the content of my git is not copied to `./proj` :
```

hpetetin@ bscesautosubmit01:/esarchive/autosubmit/a2z6/conf> autosubmit create a2z6
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
platforms_a2z6.conf OK
jobs_a2z6.conf OK
autosubmit_a2z6.conf OK
expdef_a2z6.conf  OK
Configuration files OK

Using project folder: /esarchive/autosubmit/a2z6/proj
Loading parameters...

Creating the jobs list...
Creating jobs...
Adding dependencies...
Removing redundant dependencies...
Updating structure persistence...

Saving the jobs list...

Plotting the jobs list...
Plotting...
Fontconfig warning: ignoring UTF-8: not a valid region tag

Plot created at /esarchive/autosubmit/a2z6/plot/a2z6_20200703_1621.pdf
START /usr/bin/evince /esarchive/autosubmit/a2z6/plot/a2z6_20200703_1621.pdf

(process:25350): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Unable to init server: Could not connect: Connection refused
Cannot parse arguments: Cannot open display: 
Writing status txt...
Status txt created at <open file '/esarchive/autosubmit/a2z6/status/a2z6_20200703_1621.txt', mode 'w+' at 0x7fa03ae02c90>

Job list created successfully
Remember to MODIFY the MODEL config files!
```


and thus checks fails : 
```
hpetetin@ bscesautosubmit01:/esarchive/autosubmit/a2z6/conf> autosubmit check a2z6

Checking configuration files...
platforms_a2z6.conf OK
jobs_a2z6.conf OK
autosubmit_a2z6.conf OK
expdef_a2z6.conf  OK
Configuration files OK

Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Updating structure persistence...
Checking scripts...
[CRITICAL] Unhandled exception on Autosubmit: [Errno 2] No such file or directory: '/esarchive/autosubmit/a2z6/proj/opmos/one.sh'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/autosubmit.py", line 529, in parse_args
    return Autosubmit.check(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/autosubmit.py", line 2334, in check
    return job_list.check_scripts(as_conf)
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/job/job_list.py", line 1310, in check_scripts
    if not job.check_script(as_conf, self.parameters, show_logs):
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/job/job.py", line 932, in check_script
    template_content = self.update_content(as_conf)
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/job/job.py", line 804, in update_content
    as_conf.get_project_dir(), self.file), 'r')
IOError: [Errno 2] No such file or directory: '/esarchive/autosubmit/a2z6/proj/opmos/one.sh'
```

**Comment by kinow** [comment]
In GitLab by @hervepetetin on Jul 3, 2020, 16:29

oh sorry, the issue is solved with the new exp, so I guess it was due to the different AS versions (?)

**Comment by kinow** [comment]
In GitLab by @hervepetetin on Jul 3, 2020, 16:29

closed
