### ISSUE TITLE
AttributeError: 'list' object has no attribute 'status'

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#527]
In GitLab by @pablohe on May 5, 2020, 09:56

Hi, 

t0c6 was in a death lock with this message:

```
29 of 62 jobs remaining (09:48)
Wrapper job t0c6_ASThread_1588251783421_1248_1 is COMPLETED
Waiting for wrapper check time: 10
```

in `/esarchive/autosubmit/t0c6/tmp/20200505_094621_run.log` I found this error:

```
2020-05-05 09:49:35,415 Wrapper job t0c6_ASThread_1588251783421_1248_1 is COMPLETED
2020-05-05 09:49:35,415 Waiting for wrapper check time: 10

2020-05-05 09:49:35,416 Updating FAILED jobs
2020-05-05 09:49:35,416 Update finished
2020-05-05 09:49:35,416 Updating WAITING jobs
2020-05-05 09:49:35,416 Update finished
2020-05-05 09:49:35,419 Saving JobList: /esarchive/autosubmit/t0c6/pkl/job_list_t0c6.pkl
2020-05-05 09:49:35,421 Job list saved
[CRITICAL] 2020-05-05 09:49:35,532 Unhandled exception on Autosubmit: 'list' object has no attribute 'status'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1066, in run_experiment
    prev_status = job.status
AttributeError: 'list' object has no attribute 'status'
```

**Comment by kinow** [comment]
In GitLab by @pablohe on May 5, 2020, 09:57

mentioned in issue auto-ecearth3#1253

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 5, 2020, 10:51

Hi @pablohe ,

Weird error, I checked your logs and I don't see anything wrong. 

The only thing I could think of is that, on being the wrapper job completed, something went wrong with the pkl saving.. but doesn't appears to be the case since you're running it again without issues ( I think) and the pkl doesn't appear to be corrupted. 

Also, the error indicates that somehow, a job was set as joblist instead of job type that is even weirder. @wuruchi do you have any clue? 

If it happens again, report it back please.

**Comment by kinow** [comment]
In GitLab by @wuruchi on May 5, 2020, 11:20

Hi @dbeltrankyl 

The problem seems to originate in `queuing_jobs = job_list.get_in_queue_grouped_id(platform)` where a list of lists is generated at some point and under unclear circumstances.

The main issue seems to be an inappropriate implementation of list extension:


```
in_queue = self.get_submitted(platform) + self.get_running(platform) + self.get_queuing(
            platform) + self.get_unknown(platform) + self.get_held_jobs(platform)
```

`job_list.py` line 875

I would recommend the usage of `list1.extend(list2)` instead of `+`.

As for a quick fix for this particular problem. I'd advise @pablohe to stop Autosubmit and let all queuing or running jobs finish, and then resume Autosubmit, so the input fo the list addition code is simplified and the probability of error decreases. At least until a fix is implemented.

**Comment by kinow** [comment]
In GitLab by @mcastril on May 5, 2020, 11:33

Thanks @wuruchi ,

> I would recommend the usage of `list1.extend(list2)` instead of `+`. 

Why in this particular? I think the behavior is similar, the main difference being that the `+` operator creates a new list instance, while .extend() concatenates items to an existent list.

If the problem is that one of the input lists is empty I think that the change would not solve the problem.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 5, 2020, 12:32

Thanks @wuruchi , 

In any case, this is about 3.12.0b so we must be sure, also we should see the reproduction rate because if he issue is in that list.. it should happen with more frequency and I believe this experiment has run before so is weird that it happens just now.  

For clarify, This list is created to group by id ( jobs containing the same ID means that they're in the same wrapper) 

The main issue is that the error output is unclear, and I think we should see the reproduction rate to see if a fix is needed because: 

- There are a lot of changes related to wrappers on 3.12.1b, so maybe it is already fixed on there
- If the changes are intrusive, I don't really want to touch 3.12.0b again because last time it went wrongly

**Comment by kinow** [comment]
In GitLab by @mcastril on Jul 28, 2020, 13:31

@pablohe , have you seen this error again, ever?

**Comment by kinow** [comment]
In GitLab by @pablohe on Jul 28, 2020, 13:33

I don't think so.

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 10, 2020, 13:03

Please re-open it in case you see it again. As told in other issues, should be easier to debug with more log information (in 3.13.0).

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 10, 2020, 13:03

closed
