### ISSUE TITLE
Autosubmit cannot change status of experiment

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#531]
In GitLab by @ xlevine on May 19, 2020, 16:24

Dear Daniel and CES teammembers, 

Since yesterday I have been unable to use autosubmit to run my EC-EARTH experiment. 

For example, whenever I try to change the status of my experiment: 

autosubmit setstatus a2sn -fs "RUNNING" -t COMPLETED -s

I get the following error message:

*[CRITICAL] Unhandled exception on Autosubmit: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 458, in parse_args
    args.group_by, args.expand, args.expand_status, args.notransitive,args.check_wrapper)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 2666, in set_status
    with portalocker.Lock(os.path.join(tmp_path, 'autosubmit.lock'), timeout=1):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/portalocker-1.7.0-py2.7.egg/portalocker/utils.py", line 199, in __enter__
    return self.acquire()
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/portalocker-1.7.0-py2.7.egg/portalocker/utils.py", line 158, in acquire
    raise exceptions.LockException(exception)
LockException: [Errno 11] Resource temporarily unavailable*

I suspect it has to do with the autosubmit version update, but I have been unable to resolve this problem. Would you happen to know the source of the problem?

Thank you very much for any help you may give,

Best, X.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 19, 2020, 16:35

Hi @ xlevine ,

When this error is displayed is usually related to the autosubmit.lock file located in /esarchive/autosubmit/a2sn/tmp.

Try to remove that file and then use the same setstatus command.

Autosubmit use this file to set that an experiment is running, however, sometimes the filesystem can have issues and don't unlock this file when the experiment is stopped.

**Comment by kinow** [comment]
In GitLab by @ xlevine on May 19, 2020, 17:07

Thanks @dbeltrankyl , your suggestion worked!

**Comment by kinow** [comment]
In GitLab by @ xlevine on May 19, 2020, 17:07

closed

**Comment by kinow** [comment]
In GitLab by @mcastril on May 19, 2020, 17:31

This is covered in the FAQ section from the documentation: https://autosubmit.readthedocs.io/en/latest/faq.html (don't worry, many people ask about it). Just to spread the word and in any case any other tip is useful to you.

Thanks for the feedback !
