### ISSUE TITLE
transfer_node submission failed

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#534]
In GitLab by @Eleftheriaexarchou on May 20, 2020, 12:25

Hi @pablohe  @dbeltrankyl  I have an issue while running a2v6, might be a silly issue like something in the conf files. The error is: 

```
a2v6_19900601_fc04_1_CMORATM submitted
a2v6_19910601_fc00_1_CMORATM submitted
Jobs ready for transfer_node: 1
[ERROR] transfer_node submission failed
[CRITICAL] Unhandled exception on Autosubmit: 'bool' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1076, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1132, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters,inspect)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 96, in submit
    self._send_files()
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 129, in _send_files
    self.platform.send_file(self._job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 126, in send_file
    self.delete_file(filename)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 200, in delete_file
    Log.debug('Could not remove file {0}'.format(os.path.join(self.get_files_path(), filename)))
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'bool' object has no attribute 'startswith'
```

I run with default AS version. Do you know what happened?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 20, 2020, 13:43

Hi @Eleftheriaexarchou ,

When this error happens, it is caused by a setting a FILE = <template_name> that does not exist. This is located inside jobs.conf. I've checked your configuration and it seems that:

```
[CLEAN_MEMBER]
FILE = templates/common/clean_member.tmpl.sh
```

this does not exist, did you want to point to templates/common/common.clean_member ?

**Comment by kinow** [comment]
In GitLab by @pablohe on May 20, 2020, 13:43


@dbeltrankyl is it possibly improve the error message, it happens often.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 20, 2020, 13:44

for 3.12.0, I prefer don't touch anymore the version, for 3.13.0b I think I've implemented a better message but I believe that it is still not into master branch

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on May 20, 2020, 14:10

thanks @dbeltrankyl this must be it ! Will try now. Thanks!

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on May 20, 2020, 14:19

yes this seems to be the error, thank you @dbeltrankyl  I close the issue!
