### ISSUE TITLE
Problem with authentication with PRACE user

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#536]
In GitLab by @ mguevara on May 28, 2020, 10:46

Hi @wuruchi , I am trying to run auto-monarch with Kim's PRACE account but autosubmit is crashing:

```
/[ERROR] marenostrum_archive submission failed
[CRITICAL] Unhandled exception on Autosubmit: Authentication failed.
Traceback (most recent call last):
   File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
     return Autosubmit.run_experiment(args.expid, args.notransitive)
   File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1076, in run_experiment
     if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
   File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1132, in submit_ready_jobs
     package.submit(as_conf, job_list.parameters,inspect)
   File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 96, in submit
     self._send_files()
   File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 129, in _send_files
     self.platform.send_file(self._job_scripts[job.name])
   File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 122, in send_file
     if not self.connect():
   File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 82, in connect
     key_filename=self._host_config_id)
   File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/client.py", line 307, in connect
     look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
   File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/client.py", line 519, in _auth
     raise saved_exception
AuthenticationException: Authentication failed/ 
```

I already created a public key that Kim added to his PRACE user: ```/home/Earth/mguevara/.ssh/id_rsa_prace_kim```

I also added the necessary information in my ```/home/Earth/mguevara/.ssh/config```:

```
/Host prace_fragment_kim//
//  User pr1eld04//
//  Hostname mn1.bsc.es//
//  ForwardAgent yes//
//  IdentityFile ~/.ssh/id_rsa_prace_kim//
//  ForwardX11 yes//
//
//Host prace_fragment_kim_dt//
//  HostName dt02.bsc.es//
//  User pr1eld04//
//  ForwardX11 yes//
//  Compression yes//
//  IdentityFile ~/.ssh/id_rsa_prace_kim/ 
```
When I do ```ssh prace_fragment_kim``` or ```ssh prace_fragment_kim_dt```I have no problem to connect to MN or DT, so I do not understand which can be the problem.

The experiment I am trying to run is:
```/esarchive/autosubmit/a2vn```

I am using ```autosubmit/3.12.0-foss-2015a-Python-2.7.9```

Thanks for the help!

FYI: @kserradell

**Comment by kinow** [comment]
In GitLab by @wuruchi on May 28, 2020, 15:03

Hello @ mguevara 

We will look into it.

@mcastril @dbeltrankyl Have you seen this error before?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 28, 2020, 16:22

Hello @ mguevara ,

I believe that the issue is in your platforms.conf

You have to put the alias that you configured in your `/home/Earth/mguevara/.ssh/config` otherwise it will do a direct connection.
Your current configuration is:

```
[marenostrum4]
# Queue type. Options: ps, SGE, LSF, SLURM, PBS, eceaccess
TYPE = slurm
HOST = mn1.bsc.es
PROJECT = pr1eld00
USER = pr1eld04
SCRATCH_DIR = /gpfs/scratch
ADD_PROJECT_TO_HOST = False
TEST_SUITE = False
# use 72:00 if you are using a PRACE account, 48:00 for the bsc account
MAX_WALLCLOCK = 72:00
# use 19200 if you are using a PRACE account, 2400 for the bsc account
MAX_PROCESSORS = 19200
PROCESSORS_PER_NODE = 48



[marenostrum_archive]
TYPE = ps
HOST = dt02.bsc.es
PROJECT = pr1eld00
USER = pr1eld04
SCRATCH_DIR = /gpfs/scratch
ADD_PROJECT_TO_HOST = False
TEST_SUITE = False
```

This would translate into
```
ssh pr1eld04:mn1.bsc.es
ssh pr1eld04:dt02.bsc.es
```

and what you want to perform is 

`ssh prace_fragment_kim`


To archieve this just change the 
```
HOST = mn1.bsc.es to  HOST= prace_fragment_kim
HOST = dt02.bsc.es to HOST= prace_fragment_kim_dt
```

Also, I noticed that you have a typo in your ssh config file 

`// IdentityFile ~/.ssh/id_rsa_prace_kim//` => `// IdentityFile ~/.ssh/id_rsa_prace_kim/`

I hope this is the solution.

**Comment by kinow** [comment]
In GitLab by @ mguevara on May 28, 2020, 19:31

@dbeltrankyl , @wuruchi , thank you very much for your fast response.
The problem was indeed the issue you highlighted in you comment. I did the changes that you suggested and now my simulation is running perfectly. Thanks a lot!

**Comment by kinow** [comment]
In GitLab by @ mguevara on May 28, 2020, 19:31

closed
