### ISSUE TITLE
flag -cw not showing preview of wrappers

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#543]
In GitLab by @ editomas on Jun 9, 2020, 13:12

the command "`autosubmit monitor -cw expid`" does not show anymore the preview of the wrapper structure when run with `3.13.0b-foss-2015a-Python-2.7.9`.
eg here:
`/esarchive/autosubmit/a2wk/plot/a2wk_20200608_1746.pdf`

while after running it, one can see that the wrapper was used:
`/esarchive/autosubmit/a2wk/plot/a2wk_20200609_1132.pdf`

thoughts by @dbeltrankyl:  the job structure now is only generated when autosubmit create is used, maybe that change broke that feature. I believe it is due changes to the way of handle the job structures

@gmontanepinto

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 9, 2020, 13:15

Thanks for the feedback @ editomas . The behavior will be verified in both 3.12.0 and 3.13.0b versions.

**Comment by kinow** [comment]
In GitLab by @pablohe on Jun 22, 2020, 13:26

with  3.12.0 I got:

```
bscearth315 /esarchive/autosubmit/a2xy/conf  > autosubmit inspect t0f8 -cw -f 
Starting inspect command


Checking configuration files...
platforms_t0f8.conf OK
jobs_t0f8.conf OK
autosubmit_t0f8.conf OK
expdef_t0f8.conf  OK
Configuration files OK

Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
[CRITICAL] Unhandled exception on Autosubmit: maximum recursion depth exceeded in cmp
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 438, in parse_args
    args.filter_type,args.notransitive , args.force,args.check_wrapper)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 728, in inspect
    job_list = copy.deepcopy(job_list_original)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/copy.py", line 298, in _deepcopy_inst
    state = deepcopy(state, memo)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
RuntimeError: maximum recursion depth exceeded in cmp
```

With  3.13.0b 

finish without errors but the wapper is not created

https://earth.bsc.es/autosubmitapp/experiment/t0f8

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 22, 2020, 13:28

Hi @ editomas I'll revise all issues on tomorrow since I have been busy with another project, I expect to have time again for issues from tomorrow

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 23, 2020, 13:49

Hi @ editomas , @pablohe 

Detected and resolved the issue, seems to work in a local branch. I'm performing more test and will be updated into the module later today.

I'll update this issue when the bugfix is uploaded.

Edit: 3.13.0b *

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 23, 2020, 16:32

Hi, I had this prepared for being updated now, but right now I don't have permissions to install modules on esarchive so I'm waiting for helpdesk (build installation changes) 

I guess it will be ready tomorrow.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 23, 2020, 17:32

Hi again, sorry spam. I already have permissions, It has been updated.

**Comment by kinow** [comment]
In GitLab by @pablohe on Jun 23, 2020, 17:59

Hi!
I got the same result

```
> autosubmit --version
3.13.0b0

>  autosubmit inspect t0f8 -cw -f
Starting inspect command


Checking configuration files...
platforms_t0f8.conf OK
jobs_t0f8.conf OK
autosubmit_t0f8.conf OK
expdef_t0f8.conf  OK
Configuration files OK

Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Using existing valid structure.
Starting to generate cmd scripts
Generating all cmd script adapted for wrappers
Checking scripts...
Template SIM will be checked in running time
Template SIM will be checked in running time
...
Jobs ready for nord3: 2
Jobs ready for transfer_node: 1
Jobs ready for local: 1
Jobs ready for nord3: 2
Jobs ready for transfer_node: 1
Jobs ready for transfer_node: 1
Jobs ready for nord3: 1
no more scripts to generate, now proceed to check them manually
```


https://earth.bsc.es/autosubmitapp/experiment/t0f8

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 25, 2020, 08:52

Did you use autosubmit monitor -cw? inspect is for check cmd's only.

**Comment by kinow** [comment]
In GitLab by @pablohe on Jun 25, 2020, 11:20

no, I run `autosubmit inspect t0f8 -cw -f`

**Comment by kinow** [comment]
In GitLab by @pablohe on Jun 25, 2020, 11:22

is is possible add an option only to create the wappers? (without run the monitor)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 25, 2020, 11:30

Well, the `-cw` flag in `inspect `is to create the cmd of the wrappers and I believe it was also creating the wrapper itself to be visualized however the main task is to create the cmd. 

Meanwhile, the `-cw `flag in the `monitor `is meant to visualize it, you could do `autosubmit monitor t0f8 -cw -np `and then visualize it on the GUI ( I think) 

However, maybe you don't achieve the result that you want because you have the wrapper section commented on the experiment t0f8 

`/esarchive/autosubmit/t0f8/conf/autosubmit_t0f8.conf`

```
#[wrapper]
#TYPE = Vertical
```

**Comment by kinow** [comment]
In GitLab by @pablohe on Jun 25, 2020, 11:36

Ups! fixed, I'm trying it now. 

In any case, could you test it, because AS was frizzed (when the wapper section was disabled), no error, nothing

**Comment by kinow** [comment]
In GitLab by @pablohe on Jun 25, 2020, 12:06

Looks like something is wrong 

```
/esarchive/autosubmit/t0f8/conf  > cat autosubmit_t0f8.conf
...
[wrapper]
TYPE = Vertical
JOBS_IN_WRAPPER = SIM
```

`autosubmit monitor -cw t0f8 --hide -nt`

the monitor is quite big: `87M Jun 25 12:04 20200625_113327_monitor.log`

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 25, 2020, 14:42

could you try it without -nt? I tried to copy your experiment but again the issues of no permissions for copy the experiment even with the right to read(I lost time trying to solve that)

**Comment by kinow** [comment]
In GitLab by @ editomas on Jun 25, 2020, 23:05

@dbeltrankyl with 3.13.0b your fix seems to work for us. I've asked @ abunuel to run `autosubmit monitor -cw expid` for the experiment that he was setting and the plot shows the wrappers: `/esarchive/autosubmit/a2yj/plot/a2yj_20200625_1950.pdf`. thanks to all.

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 26, 2020, 10:26

@pablohe , if SIM needs CLEAN-3, CLEAN needs CMORATM+1 and CMORATM needs SIM+1, that means that you cannot run two consecutive SIMs in a wrapper. This is because CLEAN-3 will be delayed 2 chunks, and therefore run after CMORATM-2 and SIM-1.

**Comment by kinow** [comment]
In GitLab by @pablohe on Jun 26, 2020, 10:50

Hi, this is defined in wiki, because the data flow:


| JOB | - |
| ----| -- | 
| SIM | SIM-1 NCTIME-3 CLEAN-10<sup>1</sup>|  
| CMORATM | SIM SIM+1 |
| CLEAN | SIM SIM+1 CMOR{TM5, LPJG, OCE, ATM} POST CMORATM+1 SAVE_IC |


- <sup>1</sup> Default in weekly tests: valid also CLEAN-$N, $N>=3 


https://earth.bsc.es/gitlab/es/auto-ecearth3/-/wikis/job_dependencies

the 3 in CLEAN should be 4 or more?

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 26, 2020, 11:54

It is under the user consideration to set any value from 3 to 10. CLEAN-3 is the more restrictive, and not compatible with wrappers. CLEAN-10 is the less restrictive, and should allow for ~7 jobs to be in the wrapper.

**Comment by kinow** [comment]
In GitLab by @pablohe on Jun 26, 2020, 12:05

ok, I run
```
autosubmit monitor -cw t0f8 --hide -nt
```

it with 3 and 10, 

no errors and no wapper is shown

see https://earth.bsc.es/autosubmitapp/experiment/t0f8

@dbeltrankyl did you run it a copy of t0f8?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 26, 2020, 12:24

Yes, a2yl. However I didn't use the GUI. I used autosubmit monitor -cw t0f8. I just tried again and it is working, if it doesn't show in the GUI it is a different issue I guess. Since it is being done in a different table than the one that  will be actually be used on the runtime perhaps the gui can't illustrate it

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 2, 2020, 10:36

I'll close this issue since the command itself is running. @pablohe, please if the -cw command still doesn't work with the GUI open a different issue.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 2, 2020, 10:36

closed
