### ISSUE TITLE
v3.13 wrapper jobs failing

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#552]
In GitLab by @ mfalls on Jun 26, 2020, 12:47

Hi all, 

I just ran a small experiment, and some of the jobs in a wrapper have failed.

[ERROR] Job a27e_19600101_fc0007_7_SIM inside wrapper a27e_ASThread_15931666325277_10_10 is running for longer than it's wallclock! Cancelling...
Job a27e_19600101_fc0007_7_SIM is FAILED. Checking completed files to confirm the failure...
[WARNING] Job a27e_19600101_fc0007_7_SIM seems to have failed but there is a COMPLETED file

This error was produced after less than 1 minute (the wallclock for these particular jobs are ~30 mins) 

I'll not clear the log directory while this issue is here, so let me know if you need me to lookat or show you any log file. 

Any other questions, let me know.

Cheers,
Marcus

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 26, 2020, 13:15

Hi @ mfalls,

The job inside of the wrapper apparently, it was recovered well. There was a desynchronization(not sure why) between the remote platform and autosubmit however the job was recovered with the logs and the completed file and the job finished successfully 

`\[WARNING\] Job a27e_19600101_fc0007_7_SIM seems to have failed but there is a COMPLETED file` this indicates that will be recovered.


However, it seems that the job that failed was the post one :

```
END
++ python - /gpfs/scratch/bsc32/bsc32786/a27e/EXP00/ fc0007
Traceback (most recent call last):
  File "<stdin>", line 38, in <module>
  File "/apps/PYTHON/3.6.1/INTEL/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1772, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/apps/PYTHON/3.6.1/INTEL/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/apps/PYTHON/3.6.1/INTEL/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: bbp700bias.csv not found.
+ parameters=
```

I'm not sure if the Sim job output is correct but otherwise, there shouldn't be a completed file and they shouldn't be on COMPLETED Status.
