### ISSUE TITLE
Only monitors done by experiment owner should trigger workflow updates and log writing

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#555]
In GitLab by @mcastril on Jul 7, 2020, 13:23

The aim of this issue is to let other users monitor the workflow without actually modifying the workflow.

We could even extend this possibility to the owner, by giving an argument to not touch the experiment when it is being monitored.

This is related with the separation of the workflow structure and status to improve the performance of monitor and GUI.

@dbeltrankyl @wuruchi

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 24, 2020, 11:29

To place the log and output files in tmp/ when the user is not the owner (or always and then move to plt/ and LOG if it is the owner).

This way we will be able to protect all the folders from writing except tmp.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 13, 2021, 13:04

I can implement this one

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 21, 2021, 10:44

This has been implemented on 3.14.0b. 

- When the command launched has an EXPID ( example autosubmit monitor expid), and the user doesn't own the experiment, the command log will be encountered on {expid_root}/tmp folder.
- When the command launched doesn't have an EXPID, the command log will be encountered on {autosubmit_exp_folder}/Aslogs
- Else, the log will be on {expid_root}/tmp/ASLOGS/ 

Permisions are now:

755 for each folder, except plot and tmp

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 22, 2021, 13:31

> When the command launched doesn't have an EXPID, the command log will be encountered on {autosubmit_exp_folder}/Aslogs

Hi @dbeltrankyl. Does this folder exist? (Aslogs in rootdir). In that case, what can happen if the user doesn't own the experiment?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 22, 2021, 13:45

Hi @mcastril ,

I meant {/esarchive/autosubmit}/Aslogs

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 3, 2022, 16:08

Would it be possible to do the same for `autosubmit stats` ?

Only if it doesn't need a lot of work. If not we can postpone.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 9, 2022, 16:02

I added stats logs to act as monitor logs.

On a side note, I added a fallback to global logs in case there are no valid permissions for the tmp folder of that experiment.

Also, I fixed a minor bug with job_Status , since these logs we're being set each time the owner of the experiment was doing any command with that experiment. This file should've only updated with the run command

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 9, 2022, 16:12

It seems that only fixing the logs is not enough. 

@wuruchi , I can't get other's people experiments stats due to permissions. Although the message is not very clear

```
emoving redundant dependencies...
Using existing valid structure.
Job list restored from /esarchive/autosubmit/a3og/pkl files
Plotting stats...
Creating stats file
[ERROR] Trace: Stats couldn't be shown
 [CRITICAL] Stats couldn't be generated. Check trace for more details [eCode=7061]
```

I believe that there are two issues 

* stats folder doesn't exist. [a3og] likely due to the experiment has not run yet.
* Permissions of the experiment. [a45k]

```
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.14.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.14.0b0-py2.7.egg/autosubmit/database/db_structure.py", line 180, in _delete_table_content
    cur.execute(sql)
OperationalError: attempt to write a readonly database

[WARNING] Error on Delete : OperationalError
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.14.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.14.0b0-py2.7.egg/autosubmit/database/db_structure.py", line 166, in _create_edge
    cur.executemany(sql, data)
OperationalError: attempt to write a readonly database

[WARNING] Error on Insert : OperationalError
Job list restored from /esarchive/autosubmit/a45k/pkl files
Plotting stats...
Creating stats file
```

Perhaps for the second case, we can add a fallback folder? like with the logs

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 10, 2022, 15:02

Hello @dbeltrankyl 

Perhaps the main issue is that the stats folder doesn't exist and the user doesn't have enough permissions to create it.

In the case of:

```
[WARNING] Error on Delete : OperationalError
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.14.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.14.0b0-py2.7.egg/autosubmit/database/db_structure.py", line 166, in _create_edge
    cur.executemany(sql, data)
OperationalError: attempt to write a readonly database

[WARNING] Error on Insert : OperationalError
```
It is only a warning. The block of code that updates the structure only prints into the log.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 15, 2022, 16:21

Hello @mcastril @dbeltrankyl 

I have implemented the necessary changes in https://earth.bsc.es/gitlab/es/autosubmit/-/commit/b33212e6c12152fbe22917d4debef885cfe4e9fe so the behavior should be:

- If the user doesn't have write permission in the experiment folder:
    - Autosubmit checks if the `DEFAULT_OUTPUT_DIR` (+ `stats` subfolder) setting exists, if not, it creates the `DEFAULT_OUTPUT_DIR` folder plus the `stats` subfolder.
    - Autosubmit saves the stats output in that location. Autosubmit notifies the user.
- If the user has write permissions:
    - Save output in the `stats` folder of the experiment as usual.

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 17, 2022, 11:57

> `DEFAULT_OUTPUT_DIR`

Is this `tmp` ?

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 17, 2022, 11:59

>Is this `tmp` ?

The default value of that setting is: `/esarchive/autosubmit/as_output`

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 17, 2022, 13:10

Hi @wuruchi.

However, we said that it would be:

1. stats
2. tmp
3. as_output

right?

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 17, 2022, 13:20

Hello @mcastril 

Now that you mention it, yep. I will change the output path default configuration, it's no problem.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 18, 2022, 12:16

mentioned in commit cae2bd9f39d56d5536022938d7dd64e2d0db9b4e

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 22, 2022, 12:54

$EXPID/stats should only be created by the experiment owner (it can be used if it's been already created).

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 23, 2022, 21:15

Hello @mcastril @dbeltrankyl 

I have implemented the changes discussed in the last meeting. The behavior is now the following:

The priority for selecting the output folder of the statistics will follow: `LOCAL_ROOT_FOLDER/expid/stats` -> `LOCAL_ROOT_FOLDER/expid/tmp` -> `LOCAL_ROOT_FOLDER/DEFAULT_OUTPUT_FOLDER/stats/` . This order will be bypassed if the user executing autosubmit is `eadmin`. Regular users cannot create any folder inside another users' experiment folder, even when having `write` permissions on that folder.

Only implemented in `3.14.0`

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 25, 2022, 15:20

Thank you @wuruchi. I tested it with 2 experiments from Aude and it's working fine.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Jun 1, 2022, 12:37

mentioned in commit ee87230d1cf1fb5ca5ca5a00aebf1ecad30f39e8

**Comment by kinow** [comment]
In GitLab by @wuruchi on Jun 1, 2022, 12:37

mentioned in commit 53574f476b27f30544b70161ad8efc9e10b11f71
