### ISSUE TITLE
Implement a pkl backup, to avoid losing the database if there is an I/O problem and the pkl gets corrupted

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#563]
In GitLab by @etiennesky on Jul 27, 2020, 19:58

I killed AS because it was hanging after today's esarchive failure

```
[ERROR] Can not send command nohup kill -0 22367 >& /dev/null; echo $? to dt01.bsc.es: SSH session not active
[WARNING] Retrying check job command: nohup kill -0 22367 >& /dev/null; echo $?
[ERROR] Can not get job status for job id (22367), retrying in 10 sec
```

and now I am unable to run AS, get status no recover 

```
etourign@ bscesautosubmit01 : /esarchive/autosubmit > autosubmit run a2yy
Preparing .lock file to avoid multiple instances with same experiment id

Checking configuration files...
platforms_a2yy.conf OK
jobs_a2yy.conf OK
autosubmit_a2yy.conf OK
expdef_a2yy.conf  OK
Configuration files OK

Starting job submission...
Creating jobs...
Loading JobList
[CRITICAL] Unhandled exception on Autosubmit: 
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 936, in run_experiment
    job_list = Autosubmit.load_job_list(expid, as_conf, notransitive=notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 3154, in load_job_list
    new=False, notransitive=notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_list.py", line 140, in generate
    jobs_data = {str(row[0]): row for row in self.load()}
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_list.py", line 780, in load
    return self._persistence.load(self._persistence_path, self._persistence_file)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_list_persistence.py", line 73, in load
    return pickle.load(fd)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError
```

looks like some files are missing in my pkl directory

```
etourign@ bscesautosubmit01 : /esarchive/autosubmit/a2yy/pkl > ls -ltr
total 527
-rw-rw-r--+ 1 etourign Earth    34 Jul  3 12:48 updated_list_a2yy.txt_20200703_1249
-rw-rw-r--+ 1 etourign Earth    68 Jul  3 12:50 updated_list_a2yy.txt_20200703_1250
-rw-rw-r--+ 1 etourign Earth     0 Jul  3 13:00 updated_list_a2yy.txt_20200703_1301
-rw-rw-r--+ 1 etourign Earth    35 Jul  3 13:00 #updated_list_a2yy.txt_20200703_1249#
-rw-rw-r--+ 1 etourign Earth    72 Jul  3 13:15 updated_list_a2yy.txt_20200703_1316
-rw-rw-r--+ 1 etourign Earth    31 Jul  3 16:01 updated_list_a2yy.txt_20200703_1601
-rw-rw-r--+ 1 etourign Earth    64 Jul  3 16:16 updated_list_a2yy.txt_20200703_1617
-rw-rw-r--+ 1 etourign Earth    31 Jul  3 16:56 updated_list_a2yy.txt_20200703_1656
-rw-rw-r--+ 1 etourign Earth    31 Jul  3 16:58 updated_list_a2yy.txt_20200703_1658
-rw-rw-r--+ 1 etourign Earth    31 Jul  3 17:00 updated_list_a2yy.txt_20200703_1700
-rw-rw-r--+ 1 etourign Earth   768 Jul  7 11:42 updated_list_a2yy.txt_20200707_1142
-rw-rw-r--+ 1 etourign Earth   370 Jul  7 12:23 updated_list_a2yy.txt_20200707_1223
-rw-rw-r--+ 1 etourign Earth  2961 Jul  7 12:28 updated_list_a2yy.txt_20200707_1228
-rw-rw-r--+ 1 etourign Earth   390 Jul  7 13:21 updated_list_a2yy.txt_20200707_1321
-rw-rw-r--+ 1 etourign Earth    37 Jul  7 13:23 updated_list_a2yy.txt_20200707_1324
-rw-rw-r--+ 1 etourign Earth   399 Jul  7 15:49 updated_list_a2yy.txt_20200707_1550
-rw-rw-r--+ 1 etourign Earth    34 Jul  7 15:51 updated_list_a2yy.txt_20200707_1551
-rw-rw-r--+ 1 etourign Earth    34 Jul  7 16:05 updated_list_a2yy.txt_20200707_1605
-rw-rw-r--+ 1 etourign Earth    34 Jul  7 17:05 updated_list_a2yy.txt_20200707_1705
-rw-rw-r--+ 1 etourign Earth   305 Jul  7 18:21 updated_list_a2yy.txt_20200707_1822
-rw-rw-r--+ 1 etourign Earth    32 Jul 13 09:16 updated_list_a2yy.txt_20200713_0917
-rw-rw-r--+ 1 etourign Earth    70 Jul 15 17:59 updated_list_a2yy.txt_20200715_1801
-rw-rw-r--+ 1 etourign Earth    32 Jul 15 18:39 updated_list_a2yy.txt_20200715_1839
-rw-rw-r--+ 1 etourign Earth   713 Jul 15 19:11 updated_list_a2yy.txt_20200715_1912
-rw-rw-r--+ 1 etourign Earth   747 Jul 16 12:08 updated_list_a2yy.txt_20200716_1216
-rw-rw-r--+ 1 etourign Earth  1426 Jul 16 15:43 updated_list_a2yy.txt_20200716_1706
-rw-rw-r--+ 1 etourign Earth    39 Jul 16 17:46 updated_list_a2yy.txt~
-rw-rw-r--+ 1 etourign Earth  1316 Jul 16 17:54 updated_list_a2yy.txt_20200716_1755
-rw-rw-r--+ 1 etourign Earth    68 Jul 27 13:41 updated_list_a2yy.txt_20200727_1346
-rw-rw-r--+ 1 etourign Earth  2036 Jul 27 13:42 #updated_list_a2yy.txt#
-rw-r--r--+ 1 etourign Earth 30720 Jul 27 14:05 job_packages_a2yy.db
-rw-rw-r--+ 1 etourign Earth    33 Jul 27 14:16 updated_list_a2yy.txt_20200727_1417
-rw-rw-r--+ 1 etourign Earth     0 Jul 27 15:11 job_list_a2yy.pkl
```

**Comment by kinow** [comment]
In GitLab by @etiennesky on Jul 27, 2020, 23:41

@mcastril @pablohe @wuruchi @dbeltrankyl

**Comment by kinow** [comment]
In GitLab by @wuruchi on Jul 28, 2020, 08:29

Hello @mcastril @dbeltrankyl 

It seems that the pkl of this experiment is blank. If there is no other way to fix it, we can try to recreate the current status of this experiment from the `as_times.db` database.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 28, 2020, 08:45

hi @etiennesky ,

I'm afraid that autosubmit couldn't save the pkl due the esarchive crash I think it happened just when there was a write operation on the pkl, the only solution is to do autosubmit create and autosubmit recovery

**Comment by kinow** [comment]
In GitLab by @acarreri on Jul 28, 2020, 11:30

I've got the same problem with two of my experiments. I'll try autosubmit create and recovery.

Thanks.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Jul 28, 2020, 11:32

ok thanks guys. Are you sure that my proj/ folder will not be re-created? 

I suggest someone sends an email to bsc-es users as I am sure many other people suffered from the same problem.

Would it be possible to think about a backup solution to avoid this kind of problem? Perhaps AS could make a (single) backup before overwriting the pkl file.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 28, 2020, 11:42

> ok thanks guys. Are you sure that my proj/ folder will not be re-created? 

 This was a old bug , fixed on https://earth.bsc.es/gitlab/es/autosubmit/issues/493 , but if you are not sure, do a copy of proj. 

> Would it be possible to think about a backup solution to avoid this kind of problem? Perhaps AS could make a (single) backup before overwriting the pkl file.

We can evaluate to perform two write operations each autosubmit step, one of the step-1 and another one of the current step shouldn't consume much space I guess 

> I suggest someone sends an email to bsc-es users as I am sure many other people suffered from the same problem.

I'll contact Miguel

**Comment by kinow** [comment]
In GitLab by @acarreri on Jul 28, 2020, 12:32

Hi,

I'm relatively new with autosubmit, but it's a bit scaring that after I run the commands you said (create and recovery), all the jobs of the experiment are on the waiting status.

See https://earth.bsc.es/autosubmitapp/experiment/a2yd 

If I run a2yd now, it will know what the job status were before the shutdown?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 28, 2020, 12:33

Hi sorry, @acarreri 

the command is `autosubmit recovery --all -s`

**Comment by kinow** [comment]
In GitLab by @acarreri on Jul 28, 2020, 12:36

Thanks @dbeltrankyl, I just saw your e-mail.

It's getting better with that, changing the status of the jobs !

**Comment by kinow** [comment]
In GitLab by @etiennesky on Jul 28, 2020, 12:44

I always make sure the jobs are in the proper state by running `autosubmit monitor -txtlog <expid>`

**Comment by kinow** [comment]
In GitLab by @acarreri on Jul 28, 2020, 12:55

Thanks @dbeltrankyl and @etiennesky 

I think my experiment is re-running correctly now.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 13, 2020, 12:59

Hi, 
A backup of pkl (and restoration) mechanism will be implemented on next release. The code is ready but will be released together with a refactor of the logs and exception mechanism. I'll update the issue when all is ready and tested and uploaded into 3.13.0 version.

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 3, 2020, 15:10

closed
