### ISSUE TITLE
unsupported operand type(s) for +: 'bool' and 'str'

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#565]
In GitLab by @Eleftheriaexarchou on Jul 29, 2020, 12:24

Hi @dbeltrankyl 

I am trying to run a test simulation a30g and I get this error for SIM today  

```
12 of 16 jobs remaining (12:20)
Jobs ready for marenostrum4: 1
[ERROR] marenostrum4 submission failed
[CRITICAL] Unhandled exception on Autosubmit: unsupported operand type(s) for +: 'bool' and 'str'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1076, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1132, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters,inspect)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 95, in submit
    self._create_scripts(configuration)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 287, in _create_scripts
    self._job_scripts[self.jobs[i - 1].name] + ".{0}.out".format(i - 1),
TypeError: unsupported operand type(s) for +: 'bool' and 'str' 
```

and I do not understand where it comes from. I also load the default AS. 

Do you know where this error comes from ? Thank you.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 29, 2020, 12:39

Hi @Eleftheriaexarchou ,


In jobs.conf I see that your sim section contains:

```
[SIM] 
FILE = sources/runtime/autosubmit/ece-esm.sh
...
#CHECK = on_submission 
```

However, in your project folder, I can only see

`/esarchive/autosubmit/a30g/proj/auto-ecearth3/sources/runtime/autosubmit/ece-esm.sh.tmpl`

If this file is being created on running time the check parameter should be uncommented. Otherwise, the FILE = value should match to one that exists. 

I believe this is the issue, let me know if it worked

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 29, 2020, 12:42

Note that if that is created on running time you will have to re-run the job that generates this file

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on Jul 29, 2020, 13:33

so  if i understand correctly: 

If the file ece-esm.sh is there is has to be 

```
FILE = sources/runtime/autosubmit/ece-esm.sh
...
#CHECK = on_submission
```

But if the ece-esm.sh **not** there, there are 2 options: 

1. 

```
FILE = sources/runtime/autosubmit/ece-esm.sh.tmpl 
...
#CHECK = on_submission
```

2.   

```
FILE = sources/runtime/autosubmit/ece-esm.sh  
...
CHECK = on_submission
```

Is this correct?

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on Jul 29, 2020, 13:35

Option 1 from the above message seems to work. I am not sure if option 2 would have worked too.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 29, 2020, 14:24

Hi,

Both options could work, it depends on the model.

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on Jul 29, 2020, 16:57

Thank you, I will keep this in mind. I close the issue then.

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on Jul 29, 2020, 16:57

closed

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on Jul 31, 2020, 13:29

mentioned in issue auto-ecearth3#1364
