### ISSUE TITLE
Error caused by lowercase parameters in jobs.conf shows missleading error message

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#570]
In GitLab by @orioltinto on Aug 10, 2020, 17:53

Hi,
I was having this error, which had a similar message than the issue #486.

```
[ERROR] marenostrum4 submission failed
[CRITICAL] Unhandled exception on Autosubmit: list index out of range
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1076, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1132, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters,inspect)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 97, in submit
    self._do_submission()
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 137, in _do_submission
    job.id = self.platform.submit_job(job, job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 245, in submit_job
    job_id = self.get_submitted_job_id(self.get_ssh_output())
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/slurmplatform.py", line 77, in get_submitted_job_id
    return output.split(' ')[3]
IndexError: list index out of range
```

However I saw that the problem was that I did a mistake in my job configuration file and the parameters were lower-case.
I'm putting this here in case someone has the same problem in the future.
And maybe the configuration file check can be improved.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 13, 2020, 13:08

Hi

This will be resolved when the log_refactor branch is uploaded into 3.13.0b version.

The config files checker has been greatly improved with more precise information  (and will be a little more strict) that will cause fewer issues on running time. 

Also, all exceptions and log (critical/errors) will be more precise and will contain error codes to be easier to identify.  

If there are any handled log error, autosubmit will be able to recover, however, critical logs won't be able to recover automatically by autosubmit.

If any issue is not handled, autosubmit will display a more precise trace ( I hope) and also will display a message to report it into the git in order to be correctly handled by the new system 

I'll update the related issues when it is uploaded into the 3.13.0b version

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 18, 2020, 08:56

The changes have been added into 3.13.0b version. Now it should prompt more clear messages and some new checkers has been added into the config checker.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 12, 2021, 13:36

This was merged and fixed already

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 12, 2021, 13:36

closed
