### ISSUE TITLE
Error due to missing WALLCLOCK parameter for slurm jobs.

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#576]
In GitLab by @orioltinto on Aug 17, 2020, 11:13

```
[WARNING] Command /gpfs/scratch/bsc32/bsc32870/a32j/LOG_a32j/submit_marenostrum4.sh in mn-bsc32 warning: sbatch: fatal: a32j_dummy.cmd: line 14: Unexpected `:` in [ :00]

[ERROR] marenostrum4 submission failed
[CRITICAL] Unhandled exception on Autosubmit: list index out of range
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/autosubmit.py", line 512, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive, args.update_version)
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1424, in run_experiment
    as_conf, job_list, platforms_to_test, packages_persistence, hold=False)
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/autosubmit.py", line 1566, in submit_ready_jobs
    job.id = str(jobs_id[i])
IndexError: list index out of range
```

I encountered this error when running a dummy job, I checked the **.cmd** file and the slurm header contains `#SBATCH -t :00`, which is wrong. I guess that if the wallclock parameter is mandatory it should be checked, or otherwise a reasonable default value could be set.

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 3, 2020, 15:25

3.13.0 warns you if you miss any parameter.

What would happen in PS platform jobs? Recently we agreed that Autosubmit was not checking the job duration of these ones, so maybe it does not have much sense to force specifying a duration.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 19, 2020, 14:20

Hello,

It was working for all platforms as expected, however, I modified it to add a wallclock of 2:00 (since this is the maximum unit that fits in debug) if the parameter is missing, along with a warning in the log debug file.

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 30, 2020, 14:04

This is already merged, right @dbeltrankyl ?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 12, 2021, 12:48

Hi, 

Yes, this was merged already, I'll close the issue since oriol left.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 12, 2021, 12:48

closed
