### ISSUE TITLE
Problem deleting an experiment

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#58]
In GitLab by @xyepes on Oct 27, 2015, 16:04

I can't delete experiments because there is a python error. For example, when I type  "autosubmit delete a001", autosubmit asks me:

Do you want to delete a001 ? [y/n]

I answer "y", but then it gives me the following error:

[CRITICAL] Unhandled exception on Autosubmit: name 'y' is not defined
Traceback (most recent call last):
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 261, in parse_args
    return Autosubmit.delete(args.expid, args.force)
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 453, in delete
    if force or Autosubmit._user_yes_no_query("Do you want to delete " + expid + " ?"):
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 1465, in _user_yes_no_query
    return strtobool(input().lower())
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined

**Comment by kinow** [comment]
In GitLab by @dmanubens on Nov 4, 2015, 12:39

Status changed to closed by commit f1ef016bf50b7d8cad4f2345ebe38e6d7e24e90f
