### ISSUE TITLE
IOError: size mismatch in put!  0 != 33140

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#592]
In GitLab by @Eleftheriaexarchou on Sep 18, 2020, 23:13

Hi @dbeltrankyl , 

Have this error below for a33f , does it ring any bell? Thanks! 

```
[ERROR] marenostrum4 submission failed
[CRITICAL] Unhandled exception on Autosubmit: size mismatch in put!  0 != 33140
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1076, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1132, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters,inspect)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 96, in submit
    self._send_files()
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 129, in _send_files
    self.platform.send_file(self._job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 130, in send_file
    ftp.put(os.path.join(self.tmp_path, filename), os.path.join(self.get_files_path(), filename))
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/sftp_client.py", line 669, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/sftp_client.py", line 635, in putfo
    raise IOError('size mismatch in put!  %d != %d' % (s.st_size, size))
IOError: size mismatch in put!  0 != 33140

```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 21, 2020, 09:22

Hi @Eleftheriaexarchou ,

We had this issue before, but the source is unclear we believe that comes from platform itself, just run again the experiment. 

In 3.13.0b and future versions, autosubmit should be able to recover itself from these failures, but there is no solution available for 3.12.0 (would have to do big changes which don't make sense if we have already another version that covers it)

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on Sep 21, 2020, 10:05

you're right @dbeltrankyl indeed I had restarted in during the weekend and it run. Thanks for the information,  I am closing the issue then.

**Comment by kinow** [comment]
In GitLab by @Eleftheriaexarchou on Sep 21, 2020, 10:05

closed
