### ISSUE TITLE
Autosubmit testing suite

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#602]
In GitLab by @mcastril on Oct 21, 2020, 10:30

The motivation of this work is to create a small testing suite for Autosubmit, with a simple workflow from each of the Auto-models that we have in the department. We could also add the vertical-horizontal multi-threaded that Hervé was using.

So, could you provide please:

- [x] @ jberlin a small SR coupled test from Auto-EC-Earth
- [x] @gmontanepinto @f-macchia a simple case from Auto-MONARCH
- [x] @gmontanepinto @f-macchia a very short MONARCH-DA case
- [x] @molidg a small Auto-CALIOPE workflow

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Oct 21, 2020, 11:13

From Auto-MONARCH you can take experiments t06q and t06t (DUST and DUST_DA).

**Comment by kinow** [comment]
In GitLab by @f-macchia on Oct 21, 2020, 11:38

Probably for the DA, instead of using DUST_DA is better to create a test with crossed date and wrapper. It's bigger, but we will test a "real case." I can create one with fewer members and chunks. @mcastril, what do you think? Is it too heavy as a test?

**Comment by kinow** [comment]
In GitLab by @molidg on Oct 21, 2020, 11:41

@mcastril I'm testing the last changes in the master branch but my experiments take a lot of time. I will create a new experiment with only 1 domain of simulation and I will give you the expID as soon as possible.

**Comment by kinow** [comment]
In GitLab by @ jberlin on Oct 21, 2020, 11:52

marked the checklist item **@ jberlin a small SR coupled test from Auto-EC-Earth** as completed

**Comment by kinow** [comment]
In GitLab by @ jberlin on Oct 21, 2020, 12:15

I am also running the `t0ax` exp just to check all config is up-to-date

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 21, 2020, 14:23

Yes, @dbeltrankyl should be owner to all experiments. Thanks!

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 21, 2020, 14:25

Yes @f-macchia . The idea is to test the functionality, especially if horizontal-vertical wrappers are correctly created and run. A few number of chunks is the ideal, so it can be run in few hours. From that specification, design the test that you think is more useful for your case.

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 21, 2020, 14:25

Yes, I figured it out. Should be a testbed for the basic functionality, so the smaller case that you have should be enough.

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 21, 2020, 14:26

Thanks all for your quick reaction!

**Comment by kinow** [comment]
In GitLab by @mcastril on Jan 19, 2021, 11:25

marked the checklist item **@gmontanepinto @f-macchia a simple case from Auto-MONARCH** as completed

**Comment by kinow** [comment]
In GitLab by @molidg on Jan 19, 2021, 13:18

@mcastril , sorry I forgot this. I will try to do it this week!

**Comment by kinow** [comment]
In GitLab by @f-macchia on Jan 25, 2021, 09:00

Hi guys, sorry for the delay. 

By creating an experiment similar to the DustClim one, I discovered that we have a bug in the auto-monarch master (es/auto-monarch#323). So, it's currently impossible to reproduce this type of experiment. 

I see two possible solutions:
- wait for @gmontanepinto to fix the bug (from what we saw on Friday it shouldn't be very complicated)
- use t07d from the testing suite. It's an experiment with only one start date and only SIMs, but at least it uses horizontal-vertical wrapper.

**Comment by kinow** [comment]
In GitLab by @mcastril on Jan 25, 2021, 10:53

Thanks for the feedback. We can wait for some days and see if the prospects are positive, then we might decide to continue waiting or use a simpler one.

**Comment by kinow** [comment]
In GitLab by @molidg on Jan 28, 2021, 10:59

Hi @mcastril , you can take my t0je experiment.

**Comment by kinow** [comment]
In GitLab by @f-macchia on Jan 29, 2021, 09:46

Experiment to copy: `t0jd`

I worked around the bug by eliminating the preproc steps. I precomputed the files in another experiment, running one start date per time. 

These files are store in my bsc account in marenostrum (`/gpfs/projects/bsc32/bsc32557/preproc4autosubmit`), but you should not have problems accessing them.  

After the setup/installation phase, the model performs the SIMs directly. I also removed the calc_stat from the workflow because it's unstable, in order to avoid failures due to the software and not to autosubmit.

To make sure that the wrapper is optimized, we suspend some jobs and execute the workflow in two steps, using the `strict` policy:
```bash
autosubmit setstatus -s -t SUSPENDED -ftc "[ 20120101 [ Any [1] ] ],REDUCE" t0jd -np
autosubmit setstatus -s -t SUSPENDED -ftc "[ 20120101 [ Any [2] ] ],SIM" t0jd -np
autosubmit setstatus -s -t SUSPENDED -fl t0jd_20120201_1_DA t0jd -np
```
But you can use the `flexible` policy.

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Jan 29, 2021, 10:23

mentioned in issue auto-monarch#323

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 10, 2021, 15:53

marked the checklist item **@gmontanepinto @f-macchia a very short MONARCH-DA case** as completed

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 10, 2021, 15:53

marked the checklist item **@molidg a small Auto-CALIOPE workflow** as completed

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 16, 2021, 15:23

> But you can use the `flexible` policy.

Do you know if is it possible to achieve the same using flexible and `MIN_WRAPPED`? We should get a solution that allows running the workflow without any human intervention.

**Comment by kinow** [comment]
In GitLab by @f-macchia on Feb 16, 2021, 16:31

The problem I see is that SIMs for both of the start dates are ready to run in the first chunk.

Not sure how `MIN_WRAPPED` works, but I guess the constraint is satisfied even if we run a double number of SIMs. 

To apply the 2-crossing-date strategy we would have to solve the dependency of a single day by running the related SIMs, so that the next DA can be crossed with the SIMs of the other date. 

So I suppose `MIN_WRAPPED` will not solve the problem, but I can try if you want. I've run 10-years reanalysis and several re-run with this "human intervention", finding a more automatic solution would be great! :D

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 17, 2021, 10:27

Thanks for refreshing my memory @f-macchia.

I agree that most likely won't work and I think that you will at least need to set `MIN_WRAPPED` and `MAX_WRAPPED`, but then you will need different values for the next packages. 

I don't remember quite well, but I suppose you set `MIN_WRAPPED` and `MAX_WRAPPED` to the same value. In that case, we would need a switch that reduces both numbers to the half in the first chunk. Some kind of crossing startdate mode.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 11, 2021, 14:41

Hello all

I started the testing suite, 

I copied the four experiments, did the create + refresh and changed the platform.conf.

Now I wish to know if I have to **change** some in the [git] section of the expdef in any experiments, thanks.


**Issues:**

I have an issue with T0ky which is a copy of t0ax @ jberlin ,

```
Cloning "1414-precompiled-binaries-alpha" https://earth.bsc.es/gitlab/es/auto-ecearth3.git into /esarchive/autosubmit/t0ky/proj
Cloning into 'auto-ecearth3'...
fatal: Remote branch 1414-precompiled-binaries-alpha not found in upstream origin
 [CRITICAL] Can not clone "1414-precompiled-binaries-alpha" https://earth.bsc.es/gitlab/es/auto-ecearth3.git into /esarchive/autosubmit/t0ky/proj [eCode=7065]
More info at https://autosubmit.readthedocs.io/en/latest/faq.html
```

About **monarch-DA** @mcastril ,@f-macchia 

> I agree that most likely won't work and I think that you will at least need to set `MIN_WRAPPED` and `MAX_WRAPPED`, but then you will need different values for the next packages.
> I don't remember quite well, but I suppose you set `MIN_WRAPPED` and `MAX_WRAPPED` to the same value. In that case, we would need a switch that reduces both numbers to half in the first chunk. Some kind of crossing startdate mode.

@mcastril do you want to try to implement any kind of automatic mechanism for the 3.13.0b that allows launching an experiment with crossing_start? Not sure how to do this in a general approach but I revise the instructions to launch these kinds of experiment and think something. 

O else I could make a script that launches the experiment, a wait until the experiment is stopped ( by checking the run log) and then launch setstatus and the last run. 

About the run itself,
For the launch, a testing suite is there any kind of tool? or I should make a script? I remember (badly) that Pablo was using a tool but not I forget the details @gmontanepinto ,@ jberlin @mcastril 

**Others:**

Lastly, I think I would need also an experiment that uses the ecmwf platform and nimbus, they can be short.

Also, I'll make a dummy test copy of all the experiments included in the testing suite, but only for the workflow structure, they will be running with sleeps and in debug to be easier to debug if something is wrong before the real testing suite

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 15, 2021, 16:41

@dbeltrankyl you can copy `t0j8` to substitute `t0ax`, increase the number of chunks and add a vertical wrapper. For example, 5 monthly chunks running in a vertical-wrapper in debug mode.

**Comment by kinow** [comment]
In GitLab by @molidg on Mar 24, 2021, 12:11

Hi @dbeltrankyl , The problem is that you need to load a specific version of python (that have the netCDF4 module installed). To do this I have this line in my bashrc in MN4:

```
# .bashrc

module load python/2.7.14 > /dev/null 2>&1
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 25, 2021, 09:57

@gmontanepinto ,@mcastril  I have an issue with t0j8 monitor jobs, 

```
+ singularity run /esarchive/software/containers/esmvaltool/esmvaltool-monitor.sif run --check-level relaxed --log-level debug --max-parallel-tasks 4 --config-file /esarchive/autosubmit/t0lb/proj/auto-ecearth3/es-esmvaltool/config-files/config-user.yml --config-developer-file /esarchive/autosubmit/t0lb/proj/auto-ecearth3/es-esmvaltool/config-files/config-developer.yml /gpfs/scratch/bsc32/bsc32070/t0lb/recipe_t0lb_20000101_fc00_5_monitor_ocean.yml
[33mWARNING:[0m seccomp requested but not enabled, seccomp library is missing or too old
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.8/site-packages/conda/cli/main_run.py", line 25, in execute
        script_caller, command_args = wrap_subprocess_call(on_win, context.root_prefix, prefix,
      File "/opt/conda/lib/python3.8/site-packages/conda/utils.py", line 403, in wrap_subprocess_call
        with Utf8NamedTemporaryFile(mode='w', prefix=tmp_prefix, delete=False) as fh:
      File "/opt/conda/lib/python3.8/site-packages/conda/_vendor/auxlib/compat.py", line 81, in Utf8NamedTemporaryFile
        return NamedTemporaryFile(mode=mode, buffering=buffering, encoding=encoding,
      File "/opt/conda/lib/python3.8/tempfile.py", line 541, in NamedTemporaryFile
        (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "/opt/conda/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
        fd = _os.open(file, flags, 0o600)
    OSError: [Errno 30] Read-only file system: '/opt/conda/envs/esmvaltool/.tmp7wk1t3de'
`$ /opt/conda/bin/conda run --name esmvaltool esmvaltool run --check-level relaxed --log-level debug --max-parallel-tasks 4 --config-file /esarchive/autosubmit/t0lb/proj/auto-ecearth3/es-esmvaltool/config-files/config-user.yml --config-developer-file /esarchive/autosubmit/t0lb/proj/auto-ecearth3/es-esmvaltool/config-files/config-developer.yml /gpfs/scratch/bsc32/bsc32070/t0lb/recipe_t0lb_20000101_fc00_5_monitor_ocean.yml`
  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/opt/conda
                    CPATH=/gpfs/projects/bsc32/software/suselinux/11/software/Singularity/3.2.0-
                          GCC-8.3.0/include:/gpfs/projects/bsc32/software/suselinux/11/software/
                          binutils/2.32-GCCcore-8.3.0/include:/gpfs/projects/bsc32/software/suse
                          linux/11/software/zlib/1.2.11-GCCcore-8.3.0/include:/gpfs/projects/bsc
                          32/software/suselinux/11/software/GCCcore/8.3.0/include
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/usr/local/info:/usr/share/info:/usr/info
          LD_LIBRARY_PATH=/gpfs/projects/bsc32/software/suselinux/11/software/Singularity/3.2.0-
                          GCC-8.3.0/lib:/gpfs/projects/bsc32/software/suselinux/11/software/binu
                          tils/2.32-GCCcore-8.3.0/lib:/gpfs/projects/bsc32/software/suselinux/11
                          /software/zlib/1.2.11-GCCcore-8.3.0/lib:/gpfs/projects/bsc32/software/
                          suselinux/11/software/GCCcore/8.3.0/lib/gcc/x86_64-pc-linux-gnu/8.3.0:
                          /gpfs/projects/bsc32/software/suselinux/11/software/GCCcore/8.3.0/lib6
                          4:/gpfs/projects/bsc32/software/suselinux/11/software/GCCcore/8.3.0/li
                          b:/opt/lsf/9.1/linux2.6-glibc2.3-x86_64/lib:/.singularity.d/libs
             LIBRARY_PATH=/gpfs/projects/bsc32/software/suselinux/11/software/Singularity/3.2.0-
                          GCC-8.3.0/lib:/gpfs/projects/bsc32/software/suselinux/11/software/binu
                          tils/2.32-GCCcore-8.3.0/lib:/gpfs/projects/bsc32/software/suselinux/11
                          /software/zlib/1.2.11-GCCcore-8.3.0/lib:/gpfs/projects/bsc32/software/
                          suselinux/11/software/GCCcore/8.3.0/lib64:/gpfs/projects/bsc32/softwar
                          e/suselinux/11/software/GCCcore/8.3.0/lib
                  MANPATH=/gpfs/projects/bsc32/software/suselinux/11/software/Singularity/3.2.0-
                          GCC-8.3.0/share/man:/gpfs/projects/bsc32/software/suselinux/11/softwar
                          e/binutils/2.32-GCCcore-8.3.0/share/man:/gpfs/projects/bsc32/software/
                          suselinux/11/software/zlib/1.2.11-GCCcore-8.3.0/share/man:/gpfs/projec
                          ts/bsc32/software/suselinux/11/software/GCCcore/8.3.0/share/man:/opt/l
                          sf/9.1/man:/usr/local/man:/usr/share/man
               MODULEPATH=/gpfs/projects/bsc32/software/suselinux/11/modules/all
                     PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
                          :/bin
          PKG_CONFIG_PATH=/gpfs/projects/bsc32/software/suselinux/11/software/zlib/1.2.11-GCCcor
                          e-8.3.0/lib/pkgconfig
            PYTHONSTARTUP=/etc/pythonstart
       REQUESTS_CA_BUNDLE=<not set>
     SINGULARITY_BINDPATH=/esarchive,/home/bsc32,/esarchive/autosubmit/t0lb/proj/auto-ecearth3
            SSL_CERT_FILE=<not set>
                USER_PATH=/gpfs/projects/bsc32/software/suselinux/11/software/Singularity/3.2.0-
                          GCC-8.3.0/bin:/gpfs/projects/bsc32/software/suselinux/11/software/binu
                          tils/2.32-GCCcore-8.3.0/bin:/gpfs/projects/bsc32/software/suselinux/11
                          /software/GCCcore/8.3.0/bin:/apps/modules/3.2.10/Modules/3.2.10/bin/:/
                          opt/lsf/9.1/linux2.6-glibc2.3-x86_64/bin:/opt/lsf/9.1/linux2.6-glibc2.
                          3-x86_64/etc:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:
                          /usr/games:/opt/bin:/opt/ibutils/bin:/usr/lib/mit/bin:/usr/lib/mit/sbi
                          n:/opt/intel/mic/bin:.:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/u
                          sr/local/sbin
                 XNLSPATH=/usr/share/X11/nls
     active environment : None
       user config file : /home/bsc32/bsc32070/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __glibc=2.24=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/bsc32/bsc32070/.conda/pkgs
       envs directories : /home/bsc32/bsc32070/.conda/envs
                          /opt/conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.3 Linux/3.0.101-0.47.90-default debian/9 glibc/2.24
                UID:GID : 2466:3100
             netrc file : /home/bsc32/bsc32070/.netrc
           offline mode : False
An unexpected error has occurred. Conda has prepared the above report.
Traceback (most recent call last):
  File "/home/bsc32/bsc32070/.lsbatch/1616621070.313977.shell", line 263, in <module>
    Monitor().run()
  File "/home/bsc32/bsc32070/.lsbatch/1616621070.313977.shell", line 188, in run
    shell=True,
  File "/gpfs/projects/bsc32/software/suselinux/11/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/gpfs/projects/bsc32/software/suselinux/11/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'set -xuve; module purge; module load Singularity; newgrp Earth; singularity run /esarchive/software/containers/esmvaltool/esmvaltool-monitor.sif run --check-level relaxed --log-level debug --max-parallel-tasks 4 --config-file /esarchive/autosubmit/t0lb/proj/auto-ecearth3/es-esmvaltool/config-files/config-user.yml --config-developer-file /esarchive/autosubmit/t0lb/proj/auto-ecearth3/es-esmvaltool/config-files/config-developer.yml  /gpfs/scratch/bsc32/bsc32070/t0lb/recipe_t0lb_20000101_fc00_5_monitor_ocean.yml' returned non-zero exit status 1
```

**Comment by kinow** [comment]
In GitLab by @molidg on Mar 25, 2021, 09:59

thanks @dbeltrankyl !

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Mar 25, 2021, 10:00

I've just reported the same error in https://earth.bsc.es/gitlab/es/auto-ecearth3/-/issues/1513#note_128540

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 25, 2021, 10:27

Thanks @dbeltrankyl, I just found it too. 

@wuruchi, could you create an entry in the How-to for this feature?

**Comment by kinow** [comment]
In GitLab by @wuruchi on Mar 25, 2021, 10:33

Hello @mcastril 

Sure, I will add it.

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 29, 2021, 15:32

@molidg do you know why Python3 does not have the netCDF4 library? It seems that it's not so easy to execute the template without loading the module, but on the other hand I think that we should stop using Python2.

**Comment by kinow** [comment]
In GitLab by @molidg on Mar 29, 2021, 15:43

Hi @mcastril in MN4 the modules python/3.7.4_ES and python/3.7.4 have the netCDF but python/3.8.2 doesn't have it. I started to convert the script of Auto-CALIOPE from python2 to python3 but I need more time to finish the task.
