### ISSUE TITLE
[CRITICAL] Unhandled exception on Autosubmit: attempt to write a readonly database

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#606]
In GitLab by @ mtpay on Oct 29, 2020, 14:02

Hi @dbeltrankyl ,

I was creating the expid a386, and after the create autosubmit gives this error:
```

Saving the jobs list...
[CRITICAL] Unhandled exception on Autosubmit: attempt to write a readonly database
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 445, in parse_args
    args.expand_status, args.notransitive,args.check_wrapper)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 2480, in create
    "job_packages_" + expid).reset_table()
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_package_persistence.py", line 35, in __init__
    self.db_manager.create_table(self.JOB_PACKAGES_TABLE, self.TABLE_FIELDS)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/database/db_manager.py", line 54, in create_table
    cursor.execute(create_command)
OperationalError: attempt to write a readonly database
```

Any idea what is going on? Any help will be appreciate.

Thanks

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 29, 2020, 14:23

Hi @ mtpay ,


This is an error that sometimes the job_packages is created with eadmin privileges.. long time ago that this didn't happen I'll solve it for you give me a  minute

FYI: @mcastril ,@wuruchi

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 29, 2020, 14:24

Hi @ mtpay ,

Try to do the create again, it should work

**Comment by kinow** [comment]
In GitLab by @ mtpay on Oct 29, 2020, 14:44

closed

**Comment by kinow** [comment]
In GitLab by @wuruchi on Jan 7, 2021, 21:00

Hello @pabretonniere 

Please try to create the experiment again, this error is happening more frequently for some reason. It happens because `/a3e5/pkl/job_packages_a3e5.db` is created under `eadmin`. The fix is to change the name of `/a3e5/pkl/job_packages_a3e5.db` so it is created again under the right user. I have already done this so it should work now.

**Comment by kinow** [comment]
In GitLab by @pabretonniere on Jan 7, 2021, 21:03

Working indeed! Thanks a lot!

**Comment by kinow** [comment]
In GitLab by @pabretonniere on Jan 7, 2021, 21:03

closed

**Comment by kinow** [comment]
In GitLab by @mcastril on Jan 8, 2021, 12:37

Hi @wuruchi , I cannot recall if we reported the problem to Helpdesk or how deeply we got into this, but it's definitely starting to be an issue.

Could you send an email to Helpdesk reporting this frequent behaviour? Please CC Kim, PA and me.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Jan 8, 2021, 13:37

Hello @mcastril

Indeed, we had at least 3 cases in the last 3 weeks.

I will send the email.
