### ISSUE TITLE
Problem with canceled wrapper

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#612]
In GitLab by @acarreri on Nov 5, 2020, 17:24

Hi,

I've probable done something unconventional.

I wanted to stop an experiment (expid=a2ye) and to do so, I first stopped autosubmit. I had to kill it, because I've got this error in the console:
~~~
[WARNING] Retrying check job command: sacct -n -j 12248588 -o "State"
[ERROR] Can not get job status for job id (12248588), retrying in 10 sec
[ERROR] Can not send command sacct -n -j 12248588 -o "State" to mn2.bsc.es: SSH session not active
~~~

even if in the GUI, autosubmit was `ACTIVE` with some jobs `QUEUING`.

I changed then the number of chunks in the proj file and I checked the job in mn4. I killed all the jobs that were associated with a2ye in MN4, including one job linked to a wrapper of 2 SIM jobs that had the status `SUBMITTED` in the GUI.

I then modified the different status of the failed, ready and queuing jobs to waiting. 
And I tried to run: autosubmit run a2ye. But I got this error:
~~~
[WARNING] We could not find that job a2ye_22990101_fc0_184_SIM in the list!!!!
[WARNING] We could not find that job a2ye_22990101_fc0_185_SIM in the list!!!!
[CRITICAL] Unhandled exception on Autosubmit: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 970, in run_experiment
    wrapper_job = WrapperJob(package_name, jobs[0].id, Status.SUBMITTED, 0, jobs,
AttributeError: 'NoneType' object has no attribute 'id'
~~~

The 2 SIM jobs are those that were concerned by the wrapper I killed in mn4.

Is there a log file that I need to modify to be able to relaunched autosubmit? (I'm using for this experiment the 3.12.0 version of autosubmit).

Thanks!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 6, 2020, 10:24

Hi @acarreri , 

I just saw this issue, apologies.

```
[WARNING] Retrying check job command: sacct -n -j 12248588 -o "State"
[ERROR] Can not get job status for job id (12248588), retrying in 10 sec
[ERROR] Can not send command sacct -n -j 12248588 -o "State" to mn2.bsc.es: SSH session not active
```

This is a reported error, we believe that it happens when ecmwf or bscearth000 became slowish. 

To avoid this, we released a "fixed" version of 3.12 called **3.12-fixed**, feel free of use that version instead of the default since we heard from users(ettiene) that is stable and the error is much more bearable.

The versions are essentially the same, the difference is that instead of being hung forever what Autosubmit will do is put these jobs in Unknown and send you a message via e-mail(if active) ( also it maybe can be recovered by autosubmit without stopping the execution)

Alternatively, you can use 3.13.0b, however, is on weekly development so any update can cause instabilities(or not), some people are using it already as it is much faster


> I killed all the jobs that were associated with a2ye in MN4,

I believe that you only had to re-launch autosubmit to keep going, 


> then modified the different status of the failed, ready and queuing jobs to waiting. And I tried to run: autosubmit run a2ye. But I got this error:

Never saw these issues however I think that it is likely due there were jobs inside the wrapper that weren't running and autosubmit tried to run them.. to solve all errors better do 

* autosubmit create a2ye -np
* autosubmit recovery a2ye --all -s

Recovery, will look for completed job and put them into completed and the rest of workflow to waiting. 


> queuing jobs to waiting

Perhaps, this is what caused the inconsistency to the wrapped jobs 

> the number of chunks in the proj file

When changing the number of chunks, is better to stop the experiment and do at least on 3.12.0

* autosubmit create a2ye -np
* autosubmit recovery a2ye --all -s
* autosubmit run a2ye 

On a side note, on the 3.12.0 version, All inner jobs that are not running ( inner jobs I mean, jobs inside a wrapper) they will show up as *submitted* although they are in *queuing*, until they start to run. In 3.13.0 this is solved.

**Comment by kinow** [comment]
In GitLab by @acarreri on Nov 6, 2020, 10:37

Thanks @dbeltrankyl for the explanations and solutions/recommendations. It's pretty clear.

**Comment by kinow** [comment]
In GitLab by @acarreri on Nov 6, 2020, 10:37

closed
