### ISSUE TITLE
autosubmit refusing to obey direct orders

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#620]
In GitLab by @ rbernard on Nov 18, 2020, 10:15

Hi @dbeltrankyl 

when trying to change status of failed jobs I get an error from AS:

> autosubmit setstatus a32z -fs FAILED -t WAITING -s
Preparing .lock file to avoid multiple instances with same expid.

> Checking configuration files...
platforms_a32z.conf OK
jobs_a32z.conf OK
autosubmit_a32z.conf OK
expdef_a32z.conf  OK
Configuration files OK

>Creating jobs...
Loading JobList
[CRITICAL] Unhandled exception on Autosubmit: 
Traceback (most recent call last):                                                                                                                                 
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 458, in parse_args                                                                                                                                                   
    args.group_by, args.expand, args.expand_status, args.notransitive,args.check_wrapper)                                                                          
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 2683, in set_status                                                                                                                                                  
    job_list = Autosubmit.load_job_list(expid, as_conf, notransitive=notransitive)                                                                                 
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 3154, in load_job_list                                                                                                                                               
    new=False, notransitive=notransitive)                                                                                                                          
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_list.py", line 140, in generate
    jobs_data = {str(row[0]): row for row in self.load()}
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_list.py", line 780, in load
    return self._persistence.load(self._persistence_path, self._persistence_file)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_list_persistence.py", line 73, in load
    return pickle.load(fd)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError

I have taken a look at recent issues but couldn't find anything similar, or better said, anything identical (all AS errors look the same to me).

I haven't paid attention with the recent changes in version so I'm still using default.

thanks
R

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 18, 2020, 10:35

Hi @ rbernard ,

We had an updated for 3.12.0 (called 3.12.0-fixed) but I'm certain that it is unrelated to this issue.

I never see before this error on Autosubmit but I believe that is due to the lately esarchive issues since this error is shown when the pkl file is corrupt or can't be generated ( perhaps due space? ).

I checked your files and apparently the job_list.pkl is corrupted since :

`-rw-rw-r--+ 1 rbernard Earth    0 Nov 17 08:16 job_list_a32z.pkl`

it has 0 bytes of info.

I recommend you to do the usual Autosubmit recovery procedure:

which is to perform an autosubmit create, and autosubmit recovery

Additionally delete this job_list_a32z.pkl file since it is invalid right now, this file is in charge of store the job_list status.

FYI: @mcastril , @wuruchi

**Comment by kinow** [comment]
In GitLab by @ rbernard on Nov 18, 2020, 17:24

Hi @dbeltrankyl 

I'm having troubles understanding how the recovery should be done.
I did autosubmit create and then :
autosubmit recovery a32z -s
but all jobs are still in WAITING

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 18, 2020, 17:37

By default, it only looks for  (SUBMITTED, QUEUING, RUNNING), UNKNOWN or READY

Since you want to update waiting for jobs you must use: 

`autosubmit recovery a32z --all -s`

**Comment by kinow** [comment]
In GitLab by @ rbernard on Nov 18, 2020, 17:39

will it set those jobs to COMPLETED if they are completed?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 18, 2020, 17:41

Yes, it will look for completed files.

Anyway, if you don't use -s ( which means save) you can see what will be the output of the command

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Nov 19, 2020, 15:24

Hi @dbeltrankyl ;

I got the same error today for starting a330, autosubmit (default version) was running this morning but it crashed and now I have the same issue of empty pkl file as you mentioned above:

-rw-rw-r--+ 1 rmahmood Earth    0 nov 19 12:42 job_list_a330.pkl

So the only option is to perform recovery, correct? The experiment is ~70% finished.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 19, 2020, 15:32

Hi @ rmahmood 

I'm afraid that yes, that is the only way.

```
autosubmit create a330 -np 
autosubmit recovery a330 --all -s
```

It's strange that happens twice in two days, I'm discarding that it is an issue with the code because it is the default version that has the same code for the last 7 months.

Some questions to try to see what is the source:

Which machine were you using?

How long it was running? 

It was running under nohup or interactive? 


@mcastril, @wuruchi  do you have any idea about this?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 19, 2020, 15:38

Additionally, If you have issues with "ssh no active session", please use 3.12.0-fixed

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Nov 19, 2020, 15:39

Machine was: bscesautosubmit02

Not quite how long it was running because I had to turn it off sometimes due space limitations (and also to resubmit failed jobs) in past few days. Probably, it was running maybe for two days (a guess!sorry).

It was running under nohup.

Another guess, it crashed today afternoon when esarchive was having some issue (just for a while).

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 19, 2020, 15:43

I revised the logs and in fact, it seems that is due esarchive:

```
[CRITICAL] 2020-11-19 12:49:08,954 Unhandled exception on Autosubmit: [Errno 5] Input/output error: '/esarchive/autosubmit/a330/pkl/job_list_a330.pkl'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1063, in run_experiment
    job_list.save()
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_list.py", line 786, in save
    self._persistence.save(self._persistence_path, self._persistence_file, self._job_list)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_list_persistence.py", line 87, in save
    fd = open(path, 'w')
IOError: [Errno 5] Input/output error: '/esarchive/autosubmit/a330/pkl/job_list_a330.pkl'
```

It failed to write the file, due space limitations or just not being able to reach /esarchive I can't be sure since this output can be both causes

In autosubmit 3.13.0b there is a backup mechanism but for 3.12.0 there is nothing

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Nov 19, 2020, 15:52

Yes,,, itś the same time when we had a discussion about esarchive not responding, on slack's auto-ecearth channel.

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Nov 19, 2020, 16:33

Do I need to delete `job_list_a330.pkl`, before starting the recovery?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 20, 2020, 09:11

Sorry I missed this comment, 

No, but you can delete it if you want it doesn't have any data

**Comment by kinow** [comment]
In GitLab by @ rbernard on Nov 21, 2020, 21:43

mentioned in issue Experiments#200

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 24, 2020, 11:59

closed
