### ISSUE TITLE
[ERROR] 2020-12-09 18:35:49,165 marenostrum4 submission failed

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#635]
In GitLab by @ mfalls on Dec 10, 2020, 13:09

Hi @wuruchi, @mcastril 

I launched several experiments yesterday and they failed after INI. I was using version 3.12.0.
a274, a27e, a27f, a27g and a274 did not produce any log file in tmp/ASLOGS, and according to the log in the GUI, they finished with the error message:
```
[WARNING] 2020-12-09 18:35:49,164 Command sbatch -D /gpfs/scratch/bsc32/bsc32786/a27e/LOG_a27e /gpfs/scratch/bsc32/bsc32786/a27e/LOG_a27e/a27e_19600101_fc0000_91_SIM.cmd in mn-bsc32 warning: sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)
2020-12-09 18:35:49,165 Command sbatch -D /gpfs/scratch/bsc32/bsc32786/a27e/LOG_a27e /gpfs/scratch/bsc32/bsc32786/a27e/LOG_a27e/a27e_19600101_fc0000_91_SIM.cmd in mn-bsc32 successful with out message: 
2020-12-09 18:35:49,165 Output 
[ERROR] 2020-12-09 18:35:49,165 marenostrum4 submission failed
[CRITICAL] 2020-12-09 18:35:49,169 Unhandled exception on Autosubmit: list index out of range
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1076, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1132, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters,inspect)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 97, in submit
    self._do_submission()
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 137, in _do_submission
    job.id = self.platform.submit_job(job, job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 245, in submit_job
    job_id = self.get_submitted_job_id(self.get_ssh_output())
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/slurmplatform.py", line 77, in get_submitted_job_id
    return output.split(' ')[3]
IndexError: list index out of range
```
Looking at the times, the error in all 5 experiments happened within 5 seconds of each other. 

I also launched a327, a328, a329 and a33u at the same time with the same config and they have also stopped at the same point. However I'm unable to identify the error here as no log file was produced nor anything in the gui.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Dec 10, 2020, 14:05

Hello @ mfalls 

I think the main source of the error is:

>`Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)`

It seems that your batch job is bigger than allowed for users of your group. It can be related to wallclock settings of your jobs.

@mcastril what do you think?

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 10, 2020, 14:18

Yes, when you see such message is that Slurm doesn't admit the parameters you are specifying.

In those situations you have to check your job parameters (processors asked, time asked, queue used).

In case you are using wrappers it may help to look the generated .cmd file in tmp/ and examine the header.

**Comment by kinow** [comment]
In GitLab by @ mfalls on Dec 10, 2020, 14:46

In this case, the experiments have: 
- Normal queue (no debug)
- MAX_WALLCLOCK = 48.00
- Max processors = 768
- No wrappers
- Version 3.12

I ran this same config over the weekend with no issue.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Dec 10, 2020, 15:48

Hello @ mfalls 

Can you try to launch one of the experiments again and check if the same error happens?

Perhaps it happened that too many jobs attempted to queue at the same time. I mean, if you were using the same config and same autosubmit version over the weekend without issue, then it should work just fine now. Nothing has changed on the 3.12.0.

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 10, 2020, 16:38

@ mfalls could you paste the .cmd of one of the jobs of interest so we know what's the final header submitted to the cluster?

**Comment by kinow** [comment]
In GitLab by @ mfalls on Dec 10, 2020, 17:58

They can be found here:

/esarchive/autosubmit/a27e/tmp/a27e_INI.cmd

In the case of SIM, it's a bit weird. Most SIMs have a TOTAL_STATS file, except for the last 10 chunks. There are no COMPLETED or STAT files.

/esarchive/autosubmit/a27e/tmp/a27e_19600101_fc0000_98_SIM.cmd

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 10, 2020, 18:25

Thanks Marcus. It's weird indeed. You are only asking 1 CPU process and 100 jobs, at least in a27e.

I think you should try what @wuruchi is proposing: try to submit 10 jobs, then 50, then 100. As he said, there were no changes in this regard, so I don't see why it could be failing now.

**Comment by kinow** [comment]
In GitLab by @ mfalls on Dec 10, 2020, 19:03

I just tried it with 100 (100 chunks, 1 generation) and it worked fine

**Comment by kinow** [comment]
In GitLab by @ mfalls on Dec 11, 2020, 19:12

It seems to failing about 50% of the time - I launched 5 full experiments yesterday evening, and this morning two had failed and 3 were still running.

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 14, 2020, 10:21

@ mfalls could you report this issue to Operations? They do not know much about AS but you can simply tell them that we use Autosubmit to launch independent jobs, and that sometimes is complaining about the allocation requisites, but sometimes not (copying the error message).

**Comment by kinow** [comment]
In GitLab by @ mfalls on Dec 14, 2020, 13:59

Response from David in operations:

> Dear Marcus,
> 
> 
> in MN4 we have a limit of 365 jobs per user. I think you are exceeding this
> number and this is why the job submission fails. Could you check if you have
> more than 365 jobs in the queues ? if it is the case, then you need to wait
> until some of them finish to submit more jobs.
> 
> 
> Best regards,
> 
> David.

These experiments have the wrappers turned off. I turned them off instead of switching to single generation wrappers because it was simpler. Submitting multiple jobs in a wrapper counts as only one, correct? Given that this is the first time I've received errors like this, and that I successfully ran 5x100 chunk experiments without wrappers just two weeks ago, I guess this is a new policy?

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 14, 2020, 15:21

Hi @ mfalls . In fact this policy is quite old. The restriction was even harder and they raised the maximum number of jobs because Miriam needed to submit 1 year of daily forecasts.

This came to my mind when you reported the issue at first, but I discarded it because you have 100 simulations per generation. I was obviating the fact that you run multiple experiments in parallel, and that's the thing.

As you rightly say, wrappers are one individual job, so count as one. When you ran 5x100 maybe you never had more than 3 generations submitted at the same time, although I find it difficult that they were so synchronized than never interfered.

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 14, 2020, 15:24

You can use wrappers and set all the MAX values to 100 to just submit one generation at once while we completely test #598

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 12, 2021, 14:06

Hi @ mfalls I was on holidays, 

Just to mention:

> did not produce any log file in tmp/ASLOGS

3.12.0 doesn't store the logs in tmp/ASLOGS, they are stored on tmp/

About the issue itself, can we close it? or there is still pending work? @mcastril

**Comment by kinow** [comment]
In GitLab by @mcastril on Jan 19, 2021, 11:18

closed
