### ISSUE TITLE
Error setting up the vertical WRAPPER for an on-going experiment

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#639]
In GitLab by @jllort on Dec 14, 2020, 11:46

Hi all,

I'm having performance issues with the experiment `a369` and @etiennesky suggested to try running it with a vertical wrapper. However, when I set up the wrapper I've got the following error:
````
[WARNING] 2020-12-14 11:28:29,444 We could not find that job a369_19500101_fc0_1_SIM in the list!!!!
````

The odd thing here is that the starting date is on 18500101 so I don't understand why the wrapper is looking for 19500101* job.

Thank you!

**Comment by kinow** [comment]
In GitLab by @wuruchi on Dec 14, 2020, 13:19

Hello @jllort 

I have made a backup of your packages database `/pkl/job_packages_a369.db` to `/pkl/job_packages_old.db`. Perhaps you run an experiment using that date `1950*` around October? 

Anyway, try running it again.

**Comment by kinow** [comment]
In GitLab by @jllort on Dec 14, 2020, 14:28

Thanks @wuruchi !

Yes indeed, I did run a test in October with this starting date. Sorry I forgot. 

I'll now test it.

**Comment by kinow** [comment]
In GitLab by @jllort on Dec 14, 2020, 14:43

I'm now getting the following error:
````
[CRITICAL] 2020-12-14 14:30:57,623 Unhandled exception on Autosubmit: attempt to write a readonly database
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 959, in run_experiment
    "job_packages_" + expid)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_package_persistence.py", line 35, in __init__
    self.db_manager.create_table(self.JOB_PACKAGES_TABLE, self.TABLE_FIELDS)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/database/db_manager.py", line 54, in create_table
    cursor.execute(create_command)
OperationalError: attempt to write a readonly database
````

**Comment by kinow** [comment]
In GitLab by @wuruchi on Dec 14, 2020, 14:47

Looks like we got the old `eadmin` error. Please try again once more.

@mcastril The `job_packages` got assigned to the `eadmin` user.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Dec 14, 2020, 15:02

Seems that packages are being produced.

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 14, 2020, 15:28

@jllort this is a recurrent issue, sometimes the db files are attributed to this user.

You mean it is fixed @wuruchi ?

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 14, 2020, 15:29

```
-rw-r--r--+ 1 bsc32101 Earth   4096 dic 14 14:57 job_packages_a369.db
-rw-rw-r--+ 1 bsc32101 Earth 406656 dic 14 15:29 job_list_a369.pkl
```

It seems it's ok right now

**Comment by kinow** [comment]
In GitLab by @wuruchi on Dec 14, 2020, 15:32

Hi @mcastril 

Yes, I deleted the `eadmin` file. Seems to be fixed now.

**Comment by kinow** [comment]
In GitLab by @jllort on Dec 14, 2020, 16:04

Yes, now the job was successfully submitted.

If that's ok with you, let's keep the issue open in case some other problems appear when the wrapper starts running.

Thank you!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 12, 2021, 14:09

Hi @jllort.

We are doing a Git clean-up and since you had no more problems for 1 month, I'll close this issue. But feel free to open it again if you encounter more problems.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 12, 2021, 14:09

closed
