### ISSUE TITLE
Horizontal-vertical wrapper fine tuning

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#640]
In GitLab by @mcastril on Dec 22, 2020, 17:56

I created a copy of `a34f` (`a3di`) to see how the horizontal-vertical wrappers work and if it is responsive to changes in wallclock times. Everything worked more or less as expected, with some exceptions that I will explain.

This is a 10x10 case with a full wrapper:

![Screenshot_from_2020-12-22_15-40-46](https://earth.bsc.es/gitlab/es/autosubmit/uploads/6635b505559b0dce565ab636cecdd6cf/Screenshot_from_2020-12-22_15-40-46.png)

This is a 100x100 case with 48-hour max wallclock so all job should fit in the wrapper. In fact, almost all the generations fit in, with the exception of the last four (this is difficult to see unless you enlarge the image). The only problem is that accounting for the times of the SIMs + POSTs (15min + 5min) there should be enough time in 48 hours to run the full thing inside one single job.

![Screenshot_from_2020-12-22_16-12-04](https://earth.bsc.es/gitlab/es/autosubmit/uploads/80bdbf1148885c94e36800a569c41526/Screenshot_from_2020-12-22_16-12-04.png) 

This is the same case after decreasing the max wallclock to 2-hour. Now you can see that there are more and smaller boxes. 

![Screenshot_from_2020-12-22_17-27-37](https://earth.bsc.es/gitlab/es/autosubmit/uploads/d6f4512bd5b8e563d519f6851f3ad479/Screenshot_from_2020-12-22_17-27-37.png)

Also in the GUI, the result is visible:

![Screenshot_from_2020-12-22_17-39-16](https://earth.bsc.es/gitlab/es/autosubmit/uploads/aec8fdefa6e329a1171c876dc57850a5/Screenshot_from_2020-12-22_17-39-16.png)

So Autosubmit takes into account changes in wallclock, but again my own calculation doesn't match. In 2 hour there should be enough time for 6 generations, and Autosubmit is only including 4 of them. I am running the experiment and this is what is happening, showing some output here:

```
8888 of 10101 jobs remaining (17:39)
Wrapper job a3dj_ASThread_160865513516_100_404 changed from SUBMITTED to status COMPLETED
Job a3dj_19600101_fc0012_1_SIM is COMPLETED
Job a3dj_19600101_fc0012_2_SIM is COMPLETED
Job a3dj_19600101_fc0012_3_SIM is COMPLETED
Job a3dj_19600101_fc0012_4_SIM is COMPLETED
Job a3dj_19600101_fc0012_5_SIM is COMPLETED
Job a3dj_19600101_fc0012_6_SIM is COMPLETED
......
......
......
Job a3dj_19600101_fc0015_20_SIM is COMPLETED
Job a3dj_19600101_fc0015_62_SIM is COMPLETED
Job a3dj_19600101_fc0015_POST is COMPLETED


8484 of 10101 jobs remaining (17:42)
Wrapper job a3dj_ASThread_1608655316347_100_404 changed from SUBMITTED to status COMPLETED
Job a3dj_19600101_fc0016_1_SIM is COMPLETED
Job a3dj_19600101_fc0016_2_SIM is COMPLETED
Job a3dj_19600101_fc0016_3_SIM is COMPLETED

```

Do you know @dbeltrankyl @wuruchi if there is a margin/overhead taken into account? Could it be due to the member/chunk inverse order?

@ mfalls

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 22, 2020, 18:00

I wanted to highlight this in a separate comment. I tried to run both cases (~9600 jobs in a wrapper) and smaller wrappers of ~400 jobs, and I would recommend the second by now.

In the first case, Autosubmit spends much time creating/submitting the wrapper or waiting for the completed files, failing with this error:

```
10100 of 10101 jobs remaining (16:48)
Wrapper job a3di_ASThread_16086512147980_100_9696 changed from SUBMITTED to status COMPLETED
ERROR:paramiko.transport:Socket exception: Connection reset by peer (104)
[ERROR] Trace: 
[ERROR] Command find /gpfs/scratch/bsc32/bsc32252/a3di/LOG_a3di  -name *a3di_19600101_fc0000_1_SIM_COMPLETED -o  -name *a3di_19600101_fc0000_2_SIM_COMPLETED -o  -name *a3di_19600101_fc0000_3_SIM_COMPLETED -o  -name *a3di_19600101_fc0000_4_SIM_COMPLETED -o  -name *a3di_19600101_fc0000_5_SIM_COMPLETED -o  -name *a3di_19600101_fc0000_6_SIM_COMPLETED -o  -name *a3di_19600101_fc0000_7_SIM_COMPLETED 
```

With the "smaller" wrappers the process was much smoother. It still was taking a lot of time to recover and report the completed files, and there were some errors like this one:

```
Job a3dj_19600101_fc0035_98_SIM is COMPLETED
ERROR:paramiko.transport:Secsh channel 3491 open FAILED: open failed: Administratively prohibited
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/database/db_jobdata.py", line 1114, in write_finish_time
    job_id, is_packed)
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 370, in check_job_energy
    self.send_command(check_energy_cmd)
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 653, in send_command
    command, self.host, '\n'.join(stderr_readlines)), 6005, e.message)
AutosubmitError:  

Job a3dj_19600101_fc0035_86_SIM is COMPLETED
Job a3dj_19600101_fc0035_87_SIM is COMPLETED
Job a3dj_19600101_fc0035_88_SIM is COMPLETED
```

But the process was not being interrupted.

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 22, 2020, 18:02

You have `a3dj` experiment for testing (better this one than `a3di`, because a3di points to @ mfalls experiment project directory that contains a nohup file without shared permissions so the `create` fails). `a3dj` points to the `a3di` proj.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 13, 2021, 13:31

I will look into this issue, I think this should be solved for 3.13.0

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 9, 2021, 09:47

While I think there can be further optimizations, there are new implementations on 3.13.0b that should speed up a bit the wrappers, there is still work left to do for really large wrappers on the creation part, the sending and submission should be noticeably faster than before.

About the wrapper itself, the wallclock issue has been fixed

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 9, 2021, 18:21

Thanks @dbeltrankyl , I assume that you `tested` it with a copy of `a3dj` right?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 17, 2021, 13:33

Not sure if there were further issues in this one
