### ISSUE TITLE
CRITICAL error when trying to create/run

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#641]
In GitLab by @ flope1 on Dec 23, 2020, 15:09

Hello @mcastril @dbeltrankyl @wuruchi,

Today I tried to run an experiment (a3dl) and when doing create with autosubmit it showed the following error:

`[CRITICAL] Unhandled exception on Autosubmit: attempt to write a readonly database
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 959, in run_experiment
    "job_packages_" + expid)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_package_persistence.py", line 35, in __init__
    self.db_manager.create_table(self.JOB_PACKAGES_TABLE, self.TABLE_FIELDS)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/database/db_manager.py", line 54, in create_table
    cursor.execute(create_command)
OperationalError: attempt to write a readonly database`

I refresh the experiment and it seemed to be fine, so ran it, but then showed again the same error. I don't know how to interpret it and I cannot identify what's wrong. 

If I can provide more information or help please let me know.

Ferran López Martí

**Comment by kinow** [comment]
In GitLab by @wuruchi on Dec 23, 2020, 15:29

Hello @ flope1 

Try to run it again, it should work now.

@mcastril Another instance of the `eadmin` bug.

**Comment by kinow** [comment]
In GitLab by @ flope1 on Dec 23, 2020, 15:43

Hello @wuruchi,

I've tried again and it's showing the same error.

**Comment by kinow** [comment]
In GitLab by @ flope1 on Dec 23, 2020, 16:10

Solved, if it happens again:
Change the file(/esarchive/autosubmit/a3dl/pkl/job_packages_a3dl.db) job_packages to job_packages_a3dl_bk.db or change permissions of the file with chmod 777 and create again.

**Comment by kinow** [comment]
In GitLab by @ flope1 on Dec 23, 2020, 16:10

closed
