### ISSUE TITLE
[CRITICAL] Unhandled exception on Autosubmit: database is locked

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#654]
In GitLab by @mgali on Feb 1, 2021, 11:43

When trying to copy an AS experiment from @ mfalls with the following command:

`autosubmit expid -y a27e -H marenostrum4 -d Description`

I get this CRITICAL error:
```
[CRITICAL] Unhandled exception on Autosubmit: database is locked
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 419, in parse_args
    args.operational) != ''
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 585, in expid
    exp_id = copy_experiment(copy_id, description, Autosubmit.autosubmit_version, test, operational)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/experiment/experiment_common.py", line 93, in copy_experiment
    new_name = new_experiment(description, version, test, operational)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/experiment/experiment_common.py", line 68, in new_experiment
    if not db_common.save_experiment(new_name, description, version):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/database/db_common.py", line 157, in save_experiment
    conn.commit()
OperationalError: database is locked
```

I could not find any similar error in the Issues list.

Any hint? Thanks for your help!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 1, 2021, 11:48


Seems that the main db has some issues I guess due to the Friday shutdown,

FYI @wuruchi , what do you think?

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 1, 2021, 11:55

Hello @mgali 

Please try again and report if the error repeats.

@dbeltrankyl, `db_common.py` points to the `ecearth.db` database. It is highly improbable to get a database is locked error on this database, I suspect that some sudden traffic caused this error and that by trying again, it should be fixed.

**Comment by kinow** [comment]
In GitLab by @ mfalls on Feb 1, 2021, 11:57

Hi all, 

I've just tried `autosubmit expid -y a27e -H marenostrum4 -d "coyp of a27e"`, which I've done multiple times successfully in the past and getting the same error as Marti. I'd thought previously that it could have been an issue with permissions of Marti copying my experiment but I guess not..

**Comment by kinow** [comment]
In GitLab by @mgali on Feb 1, 2021, 11:57

I keep getting the same error, too. I also tried with other experiments (taken from recent Issues). Same error, too.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 1, 2021, 12:02

Looks like something crashed the database, probably related to the outage.

I will rebuild the file and post here when it's ready.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 1, 2021, 12:09

Hello @mgali @ mfalls 

It should be working now, please try again.

**Comment by kinow** [comment]
In GitLab by @mgali on Feb 1, 2021, 12:12

Now it works for me, thanks a lot @wuruchi !

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 1, 2021, 12:13

closed

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 1, 2021, 12:14

I am glad it works. 

I am closing it now. I guess we should implement some kind of protocol to execute after outages of this kind so we make sure that some basic stuff is working correctly. FYI: @mcastril

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 1, 2021, 12:18

Thanks @wuruchi

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 1, 2021, 17:04

Thank you for documenting the problem. @wuruchi I agree that this is something to take into account for the checks that I mentioned and that we should implement in the short term. Knowing if the database is correct after an outage or at any time, and if not then have a way to recover it.

@kserradell to take into account along with the consequences of the outage.

**Comment by kinow** [comment]
In GitLab by @kserradell on Feb 1, 2021, 17:05

How can we mitigate this issue?

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 1, 2021, 17:18

I roughly mentioned in the AS meetings and with PA that my idea is to implement some cheap periodic tests to verify the status of the infrastructure. Then have some alerts and a place to check the status.

I would like to have it in the short term and the idea is to have all checks in the same place, together with the /esarchive one and the /gpfs/scratch and /gpfs/projects occupation.
