### ISSUE TITLE
[CRITICAL] Unhandled exception on Autosubmit: database is locked

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#654]
In GitLab by @mgali on Feb 1, 2021, 11:43

When trying to copy an AS experiment from @ mfalls with the following command:

`autosubmit expid -y a27e -H marenostrum4 -d Description`

I get this CRITICAL error:
```
[CRITICAL] Unhandled exception on Autosubmit: database is locked
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 419, in parse_args
    args.operational) != ''
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 585, in expid
    exp_id = copy_experiment(copy_id, description, Autosubmit.autosubmit_version, test, operational)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/experiment/experiment_common.py", line 93, in copy_experiment
    new_name = new_experiment(description, version, test, operational)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/experiment/experiment_common.py", line 68, in new_experiment
    if not db_common.save_experiment(new_name, description, version):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/database/db_common.py", line 157, in save_experiment
    conn.commit()
OperationalError: database is locked
```

I could not find any similar error in the Issues list.

Any hint? Thanks for your help!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 1, 2021, 11:48


Seems that the main db has some issues I guess due to the Friday shutdown,

FYI @wuruchi , what do you think?

**Comment by kinow** [comment]
In GitLab by @wuruchi on Feb 1, 2021, 12:13

closed

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 1, 2021, 17:04

Thank you for documenting the problem. @wuruchi I agree that this is something to take into account for the checks that I mentioned and that we should implement in the short term. Knowing if the database is correct after an outage or at any time, and if not then have a way to recover it.

@kserradell to take into account along with the consequences of the outage.

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 1, 2021, 17:18

I roughly mentioned in the AS meetings and with PA that my idea is to implement some cheap periodic tests to verify the status of the infrastructure. Then have some alerts and a place to check the status.

I would like to have it in the short term and the idea is to have all checks in the same place, together with the /esarchive one and the /gpfs/scratch and /gpfs/projects occupation.
