### ISSUE TITLE
Add support for Nimbus platform

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#657]
In GitLab by @gmontanepinto on Feb 2, 2021, 13:30

Hi @dbeltrankyl @wuruchi 

I'm having a weird error in experiment a3g0 using 3.13 (in 3.12 it works fine):

```
[ERROR] Trace: local variable 'status' referenced before assignment
 [CRITICAL] Unhandled error: If you see this message, please report it in Autosubmit's GitLab project
```

The experiment's HPCARCH is set to Nimbus (AEMET's cluster), but the first jobs are run in the LOCAL platform. Looking at the logs, seems that the error happens after some of the LOCAL jobs change the status from RUNNING to FAILED/COMPLETED. But in fact some of the remote jobs (REMOTE_COMPILE and COMPILE_DA) are successfully run in the remote platform without Autosubmit having apparently noticed it (there is no log regarding these jobs). So I'm not sure if the error happens when the local jobs are finished or when the remote jobs start.

If I try to continue the experiment after it failed (with or without changing the status of failed jobs), autosubmit seems to recover the status of the jobs but the same error happens again. Doing a create and restarting the experiment does not either solve the problem, it crashes at the same point. I've also created some copies of a3g0 (a3g8 and a3ga) but the error still happens. 

Turns out that the experiment is the same with which I found the issue reported in #653, so I don't know if it could be related (maybe a corruption due to having copied the experiment with 3.12 and then migrated it to 3.13?). 

I'm able to run other experiments using other platforms, so it must be something with this particular experiment or the platform.

Let me know if you need more info from my side to investigate it.

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 3, 2021, 10:23

We had some other issues with the LOCAL platform last week, only in 3.13.0 too. But maybe it's unrelated at all (#648)

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Feb 4, 2021, 10:16

I confirm that the error has to do with remote jobs and not with the LOCAL ones. The jobs are actually submitted, but autosubmit crashes immediately after.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 9, 2021, 09:43

Hi @gmontanepinto ,

I updated the 3.13.0b just now, right now I don't find any issue with a copy of your experiment, perhaps the issue is attached to Nimbus platform. 

Could you try to run experiment again and see if the issue remains with these last changes?

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Feb 9, 2021, 18:35

Hi @dbeltrankyl,

Just tested and the issue is still there. It happens after the first remote job is submitted and before autosubmit prints the trace in the log, but the job is actually submitted and runs fine.

If you want I can bring you access to the Nimbus cluster so you can check if there's something there that makes Autosubmit crash.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 10, 2021, 09:23

Hi @gmontanepinto ,

Ok give me access please, so I can test with a vdevel version without bothering you

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 11, 2021, 11:48

Hi @gmontanepinto,

Seems that in fact there is an issue while retrieving job status from **nimbus5** platform, still not sure why since the commands seem to work if prompted manually.

There is a "fix", now you can run that experiment although these jobs will start in an unknown status. At least it worked using dummy templates

edit: It is hard to debug since I can't use the debugger but I will keep working to see if I can implement the optimal solution

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Feb 11, 2021, 14:51

Hi @dbeltrankyl,

Just tested and it works like you say: it sets the jobs to UNKNOWN and at the end it sets them to COMPLETED when they actually finish.

But it shows another error while the job is in the UNKNOWN status:

```
[ERROR] check_job() The job id (20090506) status is -2.
Job a3g0_REMOTE_COMPILE is UNKNOWN. Checking completed files to confirm the failure...
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1579, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1706, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
Exception in thread JOB_a3g0_REMOTE_COMPILE:
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0b0-py2.7.egg/autosubmit/job/job.py", line 564, in retrieve_logfiles
    e.message, self.name), 6001)
UnboundLocalError: local variable 'e' referenced before assignment
```

Did you also get this?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 11, 2021, 14:59

Hi @gmontanepinto , 

No, I didn't. the dummy templates finishes in 5seconds so I guess it didn't trigger that, in anycase I need to work further into that platform so perhaps is better to use 3.12.0 until I figure why autosubmit can't gather the job status with sacct inside autosubmit

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Feb 11, 2021, 15:11

Perfect, thanks! Let me know if you need something from my side.

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Feb 11, 2021, 16:39

I've just realized that the Nimbus sysadmin team posted a notification on October 2020 regarding some changes they did in the `sacct` command:

> Wrapper sacct    	09 10 2020 - Friday
> 
> Determinadas consultas mal formadas con el comando sacct producen un colapso del servidor de login donde se ejecuta el comando. 
> 
> Para corregir este bug hemos implementado un wrapper con el mismo nombre, sacct, que está funcionando desde ayer día 8. 
> 
> Desde el punto de vista de los usuarios las consultas se seguirán realizando del mismo modo. 
> 
> Su función es la de impedir que se realicen consultas mal formadas informando de ello. Si la consulta está bien formada se ejecuta la consulta y la salida es idéntica a la que teníamos anteriormente. 
> 
> Estos son los tres posibles casos de ejecución del wrapper: 
> 
> 1. Consulta bien formada: el wrapper no añade nada a la salida de la consulta. Es decir que el output del wrapper será identico al proporcionado hasta ahora por el comando sacct si los chequeos sintácticos que hace el wrapper son válidos. 
> 
> 2. Consulta mal formada: en caso que haya algún error sintáctico no se llega a lanzar el comando sacct y la salida del wrapper informará de ello. Por ejemplo una consulta en la que el jobid no es un valor numérico positivo: 
> 
> ```
> 10:13:00 [nimbus4:]$ sacct -j 1235698k 
> --------------------------------------------------------------------- 
> Query Slurm DB using "sacct" Wrapper 
> --------------------------------------------------------------------- 
> Usage: sacct [ARGS] 
> Help: sacct -h OR sacct --help 
> Example: sacct -j 12547 --format=JobID,JobName,MaxRSS,Elapsed 
> Interactive mode: sacct -j 12547 -interactive 
> More Options: sacct -e 
> --------------------------------------------------------------------- 
> 
> --------------------------------------------------------------------- 
> ERROR: '1235698k' non-positive number detected for "-j" option! 
> --------------------------------------------------------------------- 
> ```
> 
> 3. Parámetro "-interactive": Si añadimos este parámetro, el wrapper añadirá información (en color verde) a la salida del comando sacct. Ejemplo: 
> 
> ```
> 10:13:07 [nimbus4:]$ sacct -j 145786 -interactive 
> --------------------------------------------------------------------- 
>  Current Query: sacct -j 145786 -interactive
>  --------------------------------------------------------------------- 
>    JobID    JobName         Start                 End          Elapsed    State     ExitCode      User           NodeList 
> ------------ ---------- ------------------- ----------------- ---------- ---------- -------     ---------      ----------------  
> 145786        gl_bd 2016-03-14T07:31:53 2016-03-14T07:33:22   00:01:29  COMPLETED      0:0      harmonie         nimbus4306 
> 145786.batch  batch 2016-03-14T07:31:53 2016-03-14T07:33:22   00:01:29  COMPLETED      0:0                       nimbus4306 
> 145786.0      sleep 2016-03-14T07:31:53 2016-03-14T07:31:53   00:00:00  COMPLETED      0:0                       nimbus4306 
> 145786.1  pmi_proxy 2016-03-14T07:31:54 2016-03-14T07:33:17   00:01:23  COMPLETED      0:0                       nimbus4306 
>  --------------------------------------------------------------------- 
>  Query Time: H:M:S:ms | 00:00:01:090ms
>   Date/Time: Fri Oct  9 08:25:21 UTC 2020
>  --------------------------------------------------------------------- 
> ```

Could this be the reason why autosubmit is not able to get the jobs status?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 11, 2021, 16:44

Hi @gmontanepinto ,

If manually prompted, I'm getting the right results (apparently) but since this is a modded version of sacct it is likely that @mcastril was right and there is some space or extra tab that is breaking the function that autosubmit uses for split the output list.

So I will check that and say something tomorrow. 

Thanks for the info

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 12, 2021, 16:50

Hi @gmontanepinto ,

I found the issue, I didn't notice it early because I was using one id

```
[bsc1@nimbus5 ~ ]$ sacct -j 20098935,20098936
 ---------------------------------------------------------------------
                 Query Slurm DB using "sacct" Wrapper                
 ---------------------------------------------------------------------
            Usage: sacct [ARGS]
             Help: sacct -h OR sacct --help
          Example: sacct -j 12547 --format=JobID,JobName,MaxRSS,Elapsed
 Interactive mode: sacct -j 12547 -interactive
     More Options: sacct -e
 ---------------------------------------------------------------------

 ---------------------------------------------------------------------
 ERROR: '20098935,20098936' non-positive number detected for "-j" option!
 ---------------------------------------------------------------------
```


```
[bsc1@nimbus5 ~ ]$ sacct --jobs 20098935,20098936
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
20098935     a3hp_2021+       desa developme+          2  COMPLETED      0:0 
20098935.ba+      batch            developme+          2  COMPLETED      0:0 
20098936     a3hp_2021+       desa developme+          2  COMPLETED      0:0 
20098936.ba+      batch            developme+          2  COMPLETED      0:0
```
Also, this doesn't work although in marenostrum4 it works (I will just erase the final comma)

```
[bsc1@nimbus5 ~ ]$ sacct --jobs 20098935,20098936,
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
```


In marenostrum4 -j works properly:

```
bsc32070@login2:~> sacct -j 14207122,14207120
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
14207120     a02j_1960+       main      bsc32          1  COMPLETED      0:0 
14207120.ba+      batch                 bsc32          1  COMPLETED      0:0 
14207120.ex+     extern                 bsc32          1  COMPLETED      0:0 
14207122     a02j_1960+       main      bsc32          1  COMPLETED      0:0 
14207122.ba+      batch                 bsc32          1  COMPLETED      0:0 
14207122.ex+     extern                 bsc32          1  COMPLETED      0:0 
```
```
bsc32070@login2:~> sacct --jobs 14207122,14207120,
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
14207120     a02j_1960+       main      bsc32          1  COMPLETED      0:0 
14207120.ba+      batch                 bsc32          1  COMPLETED      0:0 
14207120.ex+     extern                 bsc32          1  COMPLETED      0:0 
14207122     a02j_1960+       main      bsc32          1  COMPLETED      0:0 
14207122.ba+      batch                 bsc32          1  COMPLETED      0:0 
14207122.ex+     extern                 bsc32          1  COMPLETED      0:0 
```



There are two actions that we must take:

* Change -j option for all slurm platforms for --jobs (this will be implemented on Monday)
* Report -j bug to Nimbus developers

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 12, 2021, 17:35

Good one Dani!

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Feb 12, 2021, 18:13

Great! I will try to report the issue to AEMET people.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 15, 2021, 08:58

I'm getting this issue now 

```
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1579, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1706, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
```
This is the issue you reported @gmontanepinto but it is being shown to me today. 

It is using the module vdevel version and happens only on nimbus platform.. seems that the thread refuses to connect to that platform for retrieving log files,

Working on it

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 15, 2021, 14:39

Hi @gmontanepinto ,

There should be any kind of limitation regarding multiple connections (with the threads) I spent the morning figuring what is the issue but I can't determine what is happening, perhaps we should contact them or some

Meanwhile, I added a flag called DISABLE_RECOVERY_THREADS = true you can add this parameter in platforms.conf under the platform section that you want to disable.

You can test if it works using the autosubmit/devel version available on the modules, I will update 3.13.0b later today with this and other changes

Edit: What the parameter does is to active a single-threaded function instead of rely on threads, this will speed-down the run but not make it unusable

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 16, 2021, 09:46

Hi @gmontanepinto ,

The 3.13.0b version has been updated, 

As a summary:
- Nimbus issue with check job is fixed, 
- Nimbus issue with paramiko multiple connections by using threads is not working, but there is a workaround using the new parameter called `DISABLE_RECOVERY_THREADS`

To active it

```
platform.conf
[nimbus5]
HOST = nimbus
...
DISABLE_RECOVERY_THREADS = TRUE
```

This will disable recovery threads ( but not the newer data_Transfer threads using while creating scripts) and will act a single-threaded mechanism that may delay the speed of the workflow but not near as much as 3.12.0

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 16, 2021, 09:50

Good job @dbeltrankyl. I think it's worth to ask if they have any firewall or restriction. 

Nevertheless, the single thread option will be useful because it may be the same in other platforms.

@kserradell

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Feb 16, 2021, 11:29

Tested and working fine. Without the `DISABLE_RECOVERY_THREADS` option I've only seen the SSHException once so it seems to be a bit random (maybe it depends on the number of jobs running at the same time?). 

The only thing is that now the log trace saying that a job has been submitted is not shown:

```
61 of 107 jobs remaining (11:17)


61 of 107 jobs remaining (11:17)
Job a3g0_20210128_000_1_SIM is RUNNING
```

I will contact AEMET to report the issues we found. If I'm not wrong there are two different problems:

- The `sacct -j` command not accepting more than one job ID (while using `--jobs` works fine)
- This multiple connection limitation to retrieve the logs using threads.

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Feb 18, 2021, 16:42

Answer from Nimbus support:

> Hola Gilbert,
> 
> Si, estás en lo cierto,  el wrapper sólo acepta un ID. Cuando hizimos el wrapper no contemplamos la posibilidad de consultar varios ID's.
> 
> Podríamos corregirlo pero estamos muy ocupados con la instalación del nuevo clúster y dado que tenéis la posibilidad de utilizar la opción --jobs os  agradezco que lo hayáis cambiado en vuestros scripts.
> 
> En cuanto al   número de conexiones abiertas simultáneamente no hemos establecido un valor. Estará operativo el valor por defecto. No creo que esto sea un problema. Es posible que el rechazo se deba a una saturación por carga en el clúster. 
> 
> Si te parece, cuando os ocurra esta situación, envíanos los ID de los jobs involucrados y toda la información añadida que obtengáis en vuestras salidas. Los ID's nos pemitirán indagar la carga de trabajo del cluster en el momento en que se produzca  el fallo y/o si ha habido algún problema coincidente con el vuestro.
> 
> Un saludo,
> 
> Angel.

I can try to continue the test runs using the 3.13 without the `DISABLE_RECOVERY_THREADS` parameter and contact them again with the job IDs if I get the error again.

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 22, 2021, 15:23

I guess this won't be a big deal in the current operational, but in the DA one can become a bigger issue. Do you think so @gmontanepinto? Were you trying this one?

In case of saturation, you maybe can play with the `SAFETYSLEEPTIME` value.

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Feb 22, 2021, 18:49

Yes, I was doing the tests for the operational DA, but it is unlikely that it will run operationally in the current Nimbus cluster. We don't have a deadline for the DA to become operational (for now we are only testing that it would work), but there's also the fact that Nimbus will be replaced by a new cluster in a near future. We still don't know when will this happen, but AEMET just told us that they are currently focused on it and support for Nimbus is limited. So I would say it is not a critical issue, at least for now.

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 24, 2021, 18:07

Thanks @gmontanepinto. Yesterday it was finally made official that it will be an AMD one, like the next ECMWF cluster.

https://atos.net/es/2021/comunicados-de-prensa-es_2021_02_23/atos-aumenta-en-10-la-potencia-de-supercomputacion-de-la-agencia-estatal-de-meteorologia-aemet

So it's likely that we end the year being users of 2 AMD clusters at least.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 17, 2021, 13:33

Closing the issue, also this feature explanation has been added to the tutorial.
