### ISSUE TITLE
[CRITICAL] Unhandled exception on Autosubmit: 'bool' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#658]
In GitLab by @mgali on Feb 4, 2021, 10:30

Hi,

I am trying to run an experiment (a3g3) based on Marcus Falls' a27e, using the genetic algorithm AS workflow (https://earth.bsc.es/gitlab/cp/genetic_algorithm_pisces1d/-/wikis/Pisces1d-Genetic-Algorithm-Usage).

I am using AS 3.12.0

I get this error:

```
[ERROR] marenostrum4 submission failed
[CRITICAL] Unhandled exception on Autosubmit: 'bool' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1076, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1132, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters,inspect)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 96, in submit
    self._send_files()
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 129, in _send_files
    self.platform.send_file(self._job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 126, in send_file
    self.delete_file(filename)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 200, in delete_file
    Log.debug('Could not remove file {0}'.format(os.path.join(self.get_files_path(), filename)))
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'bool' object has no attribute 'startswith'

```

A similar message was reported in closed issue #435 by @etiennesky 

Any hint @mcastril ? Thanks!

**Comment by kinow** [comment]
In GitLab by @etiennesky on Feb 4, 2021, 10:35

The root of the error is mentioned in the above issue

`I think the issue is on your jobs.conf \[POST\] the path that you specified doesn't exist`

This means you probably need to adjust the path of your template script.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 4, 2021, 10:35

Hi @mgali ,

This happens on 3.12.0 when, in the jobs.conf, a [job] the `FILE = path` parameter points to an invalid path or a script file that doesn't exist, revise the names and check that the proj dir contains the correct file

**Comment by kinow** [comment]
In GitLab by @ lpalma on Feb 5, 2021, 10:46

Hi,

We have experienced the same problem in the decathlon workflow, which runs every week with a fixed configuration:

```
[ERROR] nord3 submission failed
[CRITICAL] Unhandled exception on Autosubmit: 'bool' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1076, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1132, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters,inspect)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 96, in submit
    self._send_files()
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 129, in _send_files
    self.platform.send_file(self._job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 126, in send_file
    self.delete_file(filename)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 200, in delete_file
    Log.debug('Could not remove file {0}'.format(os.path.join(self.get_files_path(), filename)))
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'bool' object has no attribute 'startswith'
```
FYI @amartine

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 5, 2021, 10:50

hi @ lpalma ,

If your experiment is a37p, the proj dir seems to be empty 

dbeltran@ bscearth375:/esarchive/autosubmit/a37p/proj> ll
total 0

If not, could you write which experiment it is?

**Comment by kinow** [comment]
In GitLab by @ lpalma on Feb 5, 2021, 12:07

Oh, I see! probably something went wrong during the last refresh. I have already fixed this.

thanks @dbeltrankyl

**Comment by kinow** [comment]
In GitLab by @etiennesky on Feb 5, 2021, 12:12

sorry if I am overlooking something...

Given that the message error is not intuitive, and since 0.12 will probably not receive more updates, it would be nice to have in the documentation an explanation of the error and its causes (i.e. the template file does not exist).

**Comment by kinow** [comment]
In GitLab by @mgali on Feb 5, 2021, 16:58

Hi, thanks to all for your inputs!

The issue is sorted out. Indeed, AS was looking for the templates in the wrong place. Some confusion was added by the fact that the parent exp from @ mfalls was running on local and mine on git, so that when I refreshed I lost some necessary edits I had made before...

Anyway: I am with Etienne, an explicit error message, or its explicit translation in the documentation, would be very helpful.

I am closing the issue now.

**Comment by kinow** [comment]
In GitLab by @mgali on Feb 5, 2021, 16:58

closed

**Comment by kinow** [comment]
In GitLab by @etiennesky on Feb 5, 2021, 17:24

reopening so the documentation issue is not forgotten...

**Comment by kinow** [comment]
In GitLab by @mgali on Feb 5, 2021, 17:27

OK, good point. If this error message can only arise from the missing templates, then I vote for an explicit error message. Cheers

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 10, 2021, 15:22

Given that this happens in 3.12 it's better to just add it to the FAQ section.

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 10, 2021, 15:22

unassigned @mgali

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 3, 2021, 13:20

This message was added to the docs of 3.12.0

**Comment by kinow** [comment]
In GitLab by @mgali on Mar 25, 2021, 17:03

mentioned in issue auto-ecearth3#1487
