### ISSUE TITLE
[CRITICAL] Unhandled exception on Autosubmit: 'bool' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#658]
In GitLab by @mgali on Feb 4, 2021, 10:30

Hi,

I am trying to run an experiment (a3g3) based on Marcus Falls' a27e, using the genetic algorithm AS workflow (https://earth.bsc.es/gitlab/cp/genetic_algorithm_pisces1d/-/wikis/Pisces1d-Genetic-Algorithm-Usage).

I am using AS 3.12.0

I get this error:

```
[ERROR] marenostrum4 submission failed
[CRITICAL] Unhandled exception on Autosubmit: 'bool' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 416, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1076, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence):
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/autosubmit.py", line 1132, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters,inspect)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 96, in submit
    self._send_files()
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/job/job_packages.py", line 129, in _send_files
    self.platform.send_file(self._job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 126, in send_file
    self.delete_file(filename)
  File "/shared/earth/software/autosubmit/3.12.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 200, in delete_file
    Log.debug('Could not remove file {0}'.format(os.path.join(self.get_files_path(), filename)))
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'bool' object has no attribute 'startswith'

```

A similar message was reported in closed issue #435 by @etiennesky 

Any hint @mcastril ? Thanks!

**Comment by kinow** [comment]
In GitLab by @etiennesky on Feb 5, 2021, 17:23

reopened

**Comment by kinow** [comment]
In GitLab by @mgali on Feb 5, 2021, 17:27

OK, good point. If this error message can only arise from the missing templates, then I vote for an explicit error message. Cheers

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 10, 2021, 15:22

Given that this happens in 3.12 it's better to just add it to the FAQ section.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 3, 2021, 13:20

This message was added to the docs of 3.12.0
