### ISSUE TITLE
users should be notified of AS crashes

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#676]
In GitLab by @etiennesky on Mar 26, 2021, 11:03

due to esarchive failures, AS frequently (maybe once a week) crashes and users are not made aware of this, loosing precious time while the experiment could be running.

unless users enable email alerts for COMPLETED jobs, there is no way a user can know that the experiment is not doing anything after an AS crash (without actively monitoring the experiment, which is not ideal).

Would it be possible to send email alerts when AS crashes due to such failures?

e.g. expid a3ba runnning AS 0.13

```
1105 of 1509 jobs remaining (23:05)
Job a3ba_ASThread_16165175265672_528_12 is QUEUING (Priority)
Job a3ba_18500101_fc1_43_POST is QUEUING
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/logging/__init__.py", line 883, in emit
    self.flush()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/logging/__init__.py", line 843, in flush
    self.stream.flush()
IOError: [Errno 5] Input/output error
Logged from file log.py, line 225


1105 of 1509 jobs remaining (23:24)
[ERROR] Trace: No section: 'config'
 [CRITICAL] Unhandled error: If you see this message, please report it in Autosubmit's GitLab project
You have new mail in /var/mail/etourign
```

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 26, 2021, 17:23

Hi @etiennesky. I think that's a good idea.

I see only one problem: We should ensure that emails can be sent in most situations to avoid users waiting for an email that will never arrive. I think that it should be possible with that kind of "controlled" errors, at least.

@dbeltrankyl, what do you think?

Related to that, @dbeltrankyl, do you think that it's possible to implement a retrial mechanism for I/O exceptions like this one? I guess it's not easy because Autosubmit it's seen this as a configuration file problem, and not the underlying I/O error, that should be captured somehow.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Mar 26, 2021, 18:00

Hi @mcastril if the I/O related crashes are fixed then there is no need for emails being sent. 

In any case, perhaps a global try/catch  clause  on IOError in the main AS loop could be used to send an email when it crashes abnormally, or to les AS pause for a few seconds until trying again.

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 26, 2021, 18:05

Yep, that's the intention: first, try to go to the root problem and minimize the sensibility to the filesystem, that it's causing a lot of trouble. Then, improve the communication in case of problems.

Being the IOError exposed in the log it's a good sign, so I hope we can do something, as we do with recovering remote files but simpler, no need for threads here I think.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Mar 26, 2021, 18:08

however, I think the best thing to do is a sleep(x) and then maybe 1 or 2 retrials, to avoid an infinite loop, but in any case it would be better than crashing.

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 26, 2021, 18:09

Yes, that's what we do in other situations, also progressively increasing the time between intervals to cover the maximum time possible without loading the machines more than necessary.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 29, 2021, 14:54

> do you think that it's possible to implement a retrial mechanism for I/O exceptions like this one?

I would have to evaluate since even the log itself can crash due I/O error(like in this case), and it can crash in multiple locations of the code. 

For the autosubmit code itself, it can be tricky to solve but I think we can implement a similar system that the one we currently have for platforms. the major issue I think it would be the log library


We already have a fork of the original log so we can implement any kind of mitigation code .. but it is a class extension of logging.py and the way it works is kinda different from the rest of the code, but there should be some way to redirect the log to dev/null or some like that in case the filesystem is not reachable to avoid the crash

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 29, 2021, 16:03

Thanks for the insight @dbeltrankyl  

I understand the two-step approach: 1) Autosubmit 2) Logging.

In any case, are we sure that the logging error would produce a crash? In the example by @etiennesky it seems that Autosubmit continued the execution after the logging exception:

```
Logged from file log.py, line 225


1105 of 1509 jobs remaining (23:24)
[ERROR] Trace: No section: 'config'
```

And finally it crashed due to the config exception.

**Comment by kinow** [comment]
In GitLab by @etiennesky on Mar 29, 2021, 16:07

probably the [ERROR] Trace: No section: 'config' is because the config parser did not find any config, since the file was not found, so detecting the I/O error would be done differently than try/catch IOError

**Comment by kinow** [comment]
In GitLab by @mcastril on Apr 16, 2021, 13:27

I was looking for the log for this problem, but it seems that there is no log in `/esarchive/autosubmit/a3ba/tmp/ASLOGS`. It could be that when this problem happens, AS also fails to write the logfile, which is really bad.

```
-rwxrwxr-x 1 bsc32051 Earth         0 mar 26 18:38 20210326_183830_run_err.log
-rwxrwxr-x 1 bsc32051 Earth   1228965 mar 26 19:49 20210326_183830_run.log
-rwxrwxr-x 1 bsc32051 Earth         0 mar 26 19:50 20210326_195015_setstatus_err.log
-rwxrwxr-x 1 bsc32051 Earth     16101 mar 26 19:50 20210326_195015_setstatus.log
-rwxrwxr-x 1 bsc32051 Earth         0 mar 29 11:08 20210329_110807_run_err.log
-rwxrwxr-x 1 bsc32051 Earth  61177620 mar 31 17:37 20210329_110807_run.log
```

It's reasonable because there is an IO error, but some retrial mechanism for the log writing could be implemented.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Apr 23, 2021, 15:56

mentioned in commit 339c22fbf67c5e8e06e8d355e70d423ab984ef46

**Comment by kinow** [comment]
In GitLab by @wuruchi on Apr 23, 2021, 18:58

mentioned in commit 9fd9d87fb9a618977699f69e7f19fb41d7e8ba7f

**Comment by kinow** [comment]
In GitLab by @wuruchi on Apr 23, 2021, 18:58

mentioned in commit 4274365717d897ef4adf88a73789abc6efe2a98c

**Comment by kinow** [comment]
In GitLab by @wuruchi on Apr 26, 2021, 13:10

mentioned in commit 5f3327b029f7239a16263ea45845af7fd589cb79

**Comment by kinow** [comment]
In GitLab by @wuruchi on Apr 26, 2021, 13:14

mentioned in commit 4b0a5f0d35b6aa6aaeaee78dc246239f7ac0cb02

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 23, 2021, 15:01

I forgot about this issue, will look at it next week ( the retrial mechanism for I/O)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 7, 2021, 14:44

This will be on the next 3.14.0 update.

Logs:

* Added a retrial mechanism to Log.file write ( .err, .out) 
* Added a check inside the main code in case that this file is not yet created.
* Added a retrial mechanism on platform recovery, perhaps we should change the datetime log when this happens and write it to a new log? @mcastril.

Notifications[working on]
* [Pending] send an email each time the remote platform is failing, set or not the mail notification to TRUE or False

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 7, 2021, 18:57

> Added a retrial mechanism on platform recovery, perhaps we should change the datetime log when this happens and write it to a new log? @mcastril.

Ideally we should have one log per run, but if this is going to make things easier go on with that, it's not terrible

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 14, 2021, 13:05

Added the notifier mechanism for remote platform issues. It will be activated by default and it will only check if there is set an email( or more).

* Added a new variable on autosubmit.conf 
* [mail] NOTIFY_ON_REMOTE_FAIL = True # default TRUE
* Added variable on newer experiments created with 3.14.0, existing experiments must add this variable manually to disable the notifications on remote crash. 

The email contains information about which platform has issues and the host used, alongside with a recommendation of changing the host or add multiple hosts if the issue persist.
