### ISSUE TITLE
Issue when trying to connect to moore: AuthenticationException: Authentication failed

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#68]
In GitLab by @dmanubens on Nov 13, 2015, 11:56

The issue is due to not having an identityfile in paramiko connection.
If it is None it raises AuthenticationException: Authentication failed

**Comment by kinow** [comment]
In GitLab by @dmanubens on Dec 1, 2015, 15:20

mentioned in commit 733675f42182608c1c9c065471a0937dddb5810a

**Comment by kinow** [comment]
In GitLab by @fmassonn on Nov 15, 2017, 15:17

I've had the same issue right now. Not sure to understand how to fix it?

**Comment by kinow** [comment]
In GitLab by @fmassonn on Nov 15, 2017, 15:17

```
Jobs ready for moore: 1
2017-11-15 15:12:56,688 Number of jobs ready: 1
2017-11-15 15:12:56,688 Number of jobs available: 3
2017-11-15 15:12:56,689 Jobs ready for moore: 1
[ERROR] 2017-11-15 15:12:57,140 moore submission failed
[CRITICAL] 2017-11-15 15:12:57,238 Unhandled exception on Autosubmit: Authentication failed.
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 334, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 692, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test):
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/autosubmit.py", line 730, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters)
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/job/job_packages.py", line 87, in submit
    self._send_files()
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/job/job_packages.py", line 115, in _send_files
    self.platform.send_file(self._job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 95, in send_file
    if not self.connect():
  File "/shared/earth/software/autosubmit/3.9.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.9.0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 81, in connect
    key_filename=self._host_config_id)
  File "build/bdist.linux-x86_64/egg/paramiko/client.py", line 307, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "build/bdist.linux-x86_64/egg/paramiko/client.py", line 519, in _auth
    raise saved_exception
AuthenticationException: Authentication failed.
```

**Comment by kinow** [comment]
In GitLab by @fmassonn on Nov 15, 2017, 15:17

I can do `ssh moore` passwordless

**Comment by kinow** [comment]
In GitLab by @fmassonn on Nov 15, 2017, 15:41

Got it, I stupidly forgot to change the user name in the file platforms_a0sa.conf
