### ISSUE TITLE
Retrials Time

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#695]
In GitLab by @molidg on May 10, 2021, 13:42

@dbeltrankyl @wuruchi As we discussed in a meeting some time ago, could be interesting a kind of delay beteween autosubmit retrials for the operational runs. Some jobs fail because of GPFS problems and waiting some minutes before re-submit again the jobs could be a good solution. 

FYI:@mcastril

**Comment by kinow** [comment]
In GitLab by @mcastril on May 10, 2021, 15:00

Thanks @molidg. I think that an option to add a delay between retrials, with the delay increasing with the number of retry is possible.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 13, 2021, 13:49

This will be the next thing I'll do in 3.14.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 23, 2021, 15:09

> This will be the next thing I'll do in 3.14.

Now for real, this will be looked on the following weeks

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 27, 2021, 13:29

I've implemented this on retrial_delayed branch ( that will be merged into 3.14.0 & master branch)

* Added a new status called DELAYED ( @wuruchi , please take it into account for the gui)
* Added a new parameter on jobs.conf called DELAY_RETRIALS = (seconds)
* When a job fails and it has this parameter set higher than 0, the job will enter in the new status DELAYED until the datetime.now() >= datetime.now()(of when the job was detected as failed) + delay_retrials ( in seconds). Then it will be put into ready status

**Comment by kinow** [comment]
In GitLab by @wuruchi on Sep 27, 2021, 13:30

Hello @dbeltrankyl 

Noted, I will implement it as soon as possible.

**Comment by kinow** [comment]
In GitLab by @mcastril on Sep 27, 2021, 15:20

* To take into account into: setstatus, priority jobs, lists, etc

* To be able to specify incremental delays using the same variable

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 28, 2021, 10:41

I've changed the retrials to made it incremental if + is added at the end of the number.

Right now it adds 60seconds each time it fails, if it fails 5 times the end result would be 60*5 + the number specified. 

Should I increment this 60seconds to something higher?

**Comment by kinow** [comment]
In GitLab by @mcastril on Sep 28, 2021, 10:51

Hi @dbeltrankyl. Why not using `DELAY_RETRIALS` (maybe better `DELAY_RETRY_TIME`, which is longer but more specific) as the delay time, with an additive value if prepended by `+`.

For example:

```
RETRIALS=5
DELAY_RETRY_TIME=30
```

Would retry after 30, 60, 90, 120, 150 seconds

```
RETRIALS=5
DELAY_RETRY_TIME=+30
```

Would retry after 30, 90, 180, 300, 450 seconds

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 28, 2021, 11:22

Yes, that was my first though but if the user set some higher like wait 600seconds it would be too big but I can do like it if you think it is better

**Comment by kinow** [comment]
In GitLab by @mcastril on Sep 28, 2021, 12:02

Yes, I also was thinking about that. But I think that we should allow users controling also the time for the first retrial. 

Another idea is to also allow:

```
RETRIALS=3
DELAY_RETRY_TIME=*10
```

Would retry after 10 seconds, 100 seconds, 1000 seconds...

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 30, 2021, 14:13

Implemented the three options:

```
RETRIALS=3
DELAY_RETRY_TIME=11
```
Will wait 11 seconds between runs

```
RETRIALS=3
DELAY_RETRY_TIME=*11
```
Will increment *10 the time put on there ( 11, would be 11,110,1100)

```
RETRIALS=3
DELAY_RETRY_TIME=+11
```
Will increment +11 the time put on there ( 11, would be 11,22,33)

**Comment by kinow** [comment]
In GitLab by @mcastril on Sep 30, 2021, 14:51

Thanks @dbeltrankyl. About the mulitiplier operator, I was thinking to multiply by the number specified (multiply by 11 in your case). I admit that using 10 can be more helpful for prevent explosion by using high-values. On the other hand, it can be too much for low values (2, 4, 8, 16...) and also we should explain why (+11 is 11+11 and \*11 becomes 11\*10).

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 7, 2021, 13:26

I changed the doc to reflect that the * will be in the potency of 10. 

I also specified that the * approach is intended when is expected that the filesystem will fail multiple times ( longer runs) otherwise is better to use the plain or the + approach

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 8, 2021, 17:07

Can I see the docs? I don't see the option in latest nor 3.14.

I was going to say that it's not the power of 10 but multiplied by 10 :)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 11, 2021, 09:25

It is not yet on 3.14, only in master branch. It was in tutorial section but I added it as well into new job section

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 13, 2021, 16:36

Are you sure? I only see those results:

https://autosubmit.readthedocs.io/en/master/search.html?q=DELAY_RETRY_TIME&check_keywords=yes&area=default

And in tutorials, nothing about DELAY

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 13, 2021, 16:55

I see the issue, seems that there is an issue when building the version from readthedocs side

```
Installed /home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/PyNaCl-1.4.0-py2.7-linux-x86_64.egg
Searching for cryptography>=2.5
Reading https://pypi.org/simple/cryptography/
Downloading https://files.pythonhosted.org/packages/10/91/90b8d4cd611ac2aa526290ae4b4285aa5ea57ee191c63c2f3d04170d7683/cryptography-35.0.0.tar.gz#sha256=9933f28f70d0517686bd7de36166dda42094eac49415459d9bdf5e7df3e0086d
Best match: cryptography 35.0.0
Processing cryptography-35.0.0.tar.gz
Writing /tmp/easy_install-MxNbDN/cryptography-35.0.0/setup.cfg
Running cryptography-35.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-MxNbDN/cryptography-35.0.0/egg-dist-tmp-jJaJmU
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/checkouts/latest/setup.py", line 61, in <module>
    scripts=['bin/autosubmit']
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/home/docs/.pyenv/versions/2.7.18/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/docs/.pyenv/versions/2.7.18/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/docs/.pyenv/versions/2.7.18/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 713, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/home/docs/.pyenv/versions/2.7.18/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/docs/.pyenv/versions/2.7.18/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/docs/checkouts/readthedocs.org/user_builds/autosubmit/envs/latest/lib/python2.7/site-packages/setuptools/sandbox.py", line 44, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-MxNbDN/cryptography-35.0.0/setup.py", line 84
    print(f"    Python: {'.'.join(str(v) for v in sys.version_info[:3])}")
                                                                        ^
SyntaxError: invalid syntax
```

My guess is that the newer version of cryptography doesn't support python 2.7 anymore I'll change the pip to install the 2.5 version instead of >=2.5

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 24, 2021, 15:11

Docs updated, including this last comment
