### ISSUE TITLE
Issues with a3w5

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#726]
In GitLab by @mcastril on Aug 17, 2021, 19:09

Hi @dbeltrankyl. @ rfernand reported an issue with stopping (to change the status of some tasks) and resuming this big experiment. According to the description, it seemed like Autosubmit was forgetting the status of RUNNING wrappers. 

This is the status before the pause:

**20210816_112254_run.log**
```
2021-08-16 18:02:26,417 a3w5_20001101_fc00_6_SIM           17018865       RUNNING        marenostrum4        bsc_es
2021-08-16 18:02:26,417 a3w5_20001101_fc00_7_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:02:26,417 a3w5_20001101_fc00_8_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:02:26,417 a3w5_20001101_fc00_9_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:02:26,417 a3w5_20001101_fc00_10_SIM          17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:02:26,418 a3w5_20001101_fc00_11_SIM          17018865       QUEUING        marenostrum4        bsc_es
```

This is the status after the pause:

**20210816_175704_run.log**
```
2021-08-16 18:02:26,417 a3w5_20001101_fc00_6_SIM           17018865       RUNNING        marenostrum4        bsc_es
2021-08-16 18:02:26,417 a3w5_20001101_fc00_7_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:02:26,417 a3w5_20001101_fc00_8_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:02:26,417 a3w5_20001101_fc00_9_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:02:26,417 a3w5_20001101_fc00_10_SIM          17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:02:26,418 a3w5_20001101_fc00_11_SIM          17018865       QUEUING        marenostrum4        bsc_es
```

but shorty afterwards, in the same log:

```
2021-08-16 18:02:34,379 Successful check job command: sacct -n -X --jobs 17018865 -o "State"
2021-08-16 18:02:34,379 Wrapper job a3w5_ASThread_16281658676437_768_6 changed from SUBMITTED to status RUNNING
2021-08-16 18:02:34,379 Checking inner jobs status
2021-08-16 18:02:35,418 Job a3w5_20001101_fc00_1_SIM started at 2021-08-16 11:18:51
2021-08-16 18:02:35,418 Job a3w5_20001101_fc00_1_SIM is RUNNING
2021-08-16 18:02:35,433 a3w5_20001101_fc00_1_SIM_STAT file have been transfered
2021-08-16 18:02:36,555 a3w5_20001101_fc00_1_SIM job seems to have completed: checking...
2021-08-16 18:02:36,568 Job a3w5_20001101_fc00_1_SIM is COMPLETED
2021-08-16 18:02:36,585 a3w5_20001101_fc00_1_SIM_STAT file have been transfered
2021-08-16 18:02:36,701 Job a3w5_20001101_fc00_1_SIM finished at 2021-08-16 12:31:23
```

Autosubmit "forgets" about the running wrapper and resets its status to zero. Then it realizes that the inner jobs are already COMPLETED and starts setting their correct status.

This happened with all the SIMs until the fifth, and again:

```
2021-08-16 18:04:17,942 a3w5_20001101_fc00_6_SIM           17018865       RUNNING        marenostrum4        bsc_es
2021-08-16 18:04:17,942 a3w5_20001101_fc00_7_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:04:17,942 a3w5_20001101_fc00_8_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:04:17,942 a3w5_20001101_fc00_9_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:04:17,942 a3w5_20001101_fc00_10_SIM          17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:04:17,943 a3w5_20001101_fc00_11_SIM          17018865       QUEUING        marenostrum4        bsc_es
```

However, after SIM_6 is COMPLETED, Autosubmit does not proceed checking the running status of the 7th:

```
2021-08-16 18:32:31,189 Saving JobList: /esarchive/autosubmit/a3w5/pkl/job_list_a3w5_backup.pkl
2021-08-16 18:32:31,894 Job list saved
2021-08-16 18:32:32,205 Checking jobs for platform=marenostrum4
2021-08-16 18:32:32,206 Checking Wrapper 17018865
2021-08-16 18:32:35,278 Successful check job command: sacct -n -X --jobs 17018865 -o "State"
2021-08-16 18:32:35,278 Checking inner jobs status
2021-08-16 18:32:37,320 a3w5_20001101_fc00_6_SIM job seems to have completed: checking...
2021-08-16 18:32:37,334 Job a3w5_20001101_fc00_6_SIM is COMPLETED
2021-08-16 18:32:37,393 a3w5_20001101_fc00_6_SIM_STAT file have been transfered
2021-08-16 18:32:37,505 Job a3w5_20001101_fc00_6_SIM finished at 2021-08-16 18:32:21
```

```
2021-08-16 18:32:38,316 a3w5_20001101_fc00_7_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:32:38,317 a3w5_20001101_fc00_8_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:32:38,317 a3w5_20001101_fc00_9_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:32:38,317 a3w5_20001101_fc00_10_SIM          17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 18:32:38,317 a3w5_20001101_fc00_11_SIM          17018865       QUEUING        marenostrum4        bsc_es
```

The status is checked, but SIM_7 is never RUNNING
```
2021-08-16 18:32:54,576 Checking Wrapper 17018865
2021-08-16 18:32:57,798 Successful check job command: sacct -n -X --jobs 17018865 -o "State"
```

During the stop there was a setstatus and an interruption in the process:

**20210816_175624_setstatus.log**
```
Job Name                           Job Id         Job Status     Job Platform        Job Queue
2021-08-16 17:56:47,849 a3w5_19951101_fc00_11_NCTIME       558440         COMPLETED      nord3               bsc_es
2021-08-16 17:56:47,849 a3w5_20051101_fc00_11_NCTIME       556771         COMPLETED      nord3               bsc_es
2021-08-16 17:56:47,850 a3w5_20101101_fc00_11_NCTIME       556777         COMPLETED      nord3               bsc_es
2021-08-16 17:56:47,850 a3w5_20151101_fc00_11_NCTIME       558445         COMPLETED      nord3               bsc_es
2021-08-16 17:56:47,850 a3w5_20201101_fc00_11_NCTIME       558851         COMPLETED      nord3               bsc_es
2021-08-16 17:56:47,850 a3w5_20001101_fc00_6_SIM           17018865       RUNNING        marenostrum4        bsc_es
2021-08-16 17:56:47,850 a3w5_20001101_fc00_7_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 17:56:47,850 a3w5_20001101_fc00_8_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 17:56:47,850 a3w5_20001101_fc00_9_SIM           17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 17:56:47,850 a3w5_20001101_fc00_10_SIM          17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 17:56:47,851 a3w5_20001101_fc00_11_SIM          17018865       QUEUING        marenostrum4        bsc_es
2021-08-16 17:56:47,854 Saving JobList: /esarchive/autosubmit/a3w5/pkl/job_list_a3w5.pkl
2021-08-16 17:56:48,563 Job list saved
2021-08-16 17:56:48,829 Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.13.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0-py2.7.egg/autosubmit/database/db_jobdata.py", line 915, in process_status_changes
    self.update_jobs_from_change_status(tracking_dictionary)
  File "/shared/earth/software/autosubmit/3.13.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.13.0-py2.7.egg/autosubmit/database/db_jobdata.py", line 1573, in update_jobs_from_change_status
    status_code, final_status_code = tracking_dictionary[job_name]
ValueError: too many values to unpack

[WARNING] 2021-08-16 17:56:48,830 Autosubmit couldn't process status changes validate_current_run too many values to unpack
```

I don't know if it can be related, since it doesn't seem to have impacted the status of the jobs neither the wrapper that they belong to.

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 17, 2021, 19:10

I recommended @ rfernand to not stop Autosubmit to change the status and use the update_list method instead by the moment.

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 17, 2021, 19:11

@wuruchi there is a minor issue related to this one in the GUI. Looking at the historical information, it seems that one of the jobs is duplicated (the one lasting 1:32:32):

![Screenshot_from_2021-08-17_19-10-24](https://earth.bsc.es/gitlab/es/autosubmit/uploads/8dd42ae7d07286610df0b49676e15bf6/Screenshot_from_2021-08-17_19-10-24.png)

It belongs to the RunId `2108051331` of this experiment (`a3wl`)

**Comment by kinow** [comment]
In GitLab by @wuruchi on Aug 18, 2021, 07:45

Hello @mcastril 

Looking into it.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Aug 19, 2021, 22:05

mentioned in commit d0c887f415f22a9073bbde7b0c99fe8fa45b5aa3

**Comment by kinow** [comment]
In GitLab by @wuruchi on Aug 19, 2021, 22:19

Hello @mcastril 

Thanks for reporting this issue. I detected that a change implemented a couple of weeks ago added an extra variable to the dictionary that keeps track of the changes implemented by `set status`. I have corrected this problem in the `3.13.0-Release-branch`. The bug wasn't present in the `master` branch.

See line `4600` of `autosubmit.py` at https://earth.bsc.es/gitlab/es/autosubmit/-/commit/d0c887f415f22a9073bbde7b0c99fe8fa45b5aa3#6bde465286156a9da245a31e64df703a55c76323_4600_4605

This error on the change status process of the historical database was generating conflicts between the actual status of the job and the status stored in the historical database. That is the source of the duplicate rerun you found.

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 20, 2021, 10:44

Good that you found it @wuruchi ! Thanks for the detailed explanation :)

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 20, 2021, 10:45

@ rfernand how it is your experiment going without stopping it to run `setstatus`?

I hope that early next week @dbeltrankyl will be able to have a look on the weird behavior with the running wrappers.

**Comment by kinow** [comment]
In GitLab by @ rfernand on Aug 20, 2021, 10:50

Hi @mcastril, the simulation is running well! It is making progress faster than I expected! Thanks for the help!

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 20, 2021, 11:03

I am happy that it is helpful to circumvent the bug and also about the progress, thank you for the quick feedback!

In a not-so-far future, you will be able to do this kind of change from the GUI (also without stopping Autosubmit). This will make the `update list feature more accessible to everyone.

Note that you have a shortcut in the GUI to automatically generate the file content (in the "activate selection mode option") (that you would only need to copy and paste)

![Screenshot_from_2021-08-20_11-02-42](https://earth.bsc.es/gitlab/es/autosubmit/uploads/8c0ed6d21d0f01064040432fa3d6a803/Screenshot_from_2021-08-20_11-02-42.png)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 23, 2021, 08:55

Good Morning, @mcastril , @ rbernard 

This has always happened on all autosubmit versions 

```
2021-08-16 18:02:34,379 Successful check job command: sacct -n -X --jobs 17018865 -o "State"
2021-08-16 18:02:34,379 Wrapper job a3w5_ASThread_16281658676437_768_6 changed from SUBMITTED to status RUNNING
```

I saw this two weeks ago and did a fix for 3.14 but not for 3.13, basically, when a wrapper is loaded, it defaults the status to submitted but didn't it as a major issue since it appears that only affect in a visual way during my tests thus I didn't have the issue of autosubmit being stuck but I didn't use setstatus

I did the fix only on the 3.14 since I didn't want to update the 3.13 just before I went on holiday for 1 week but I will transfer the changes into 3.13 after I test it with setstatus.

The change that I was mentioning is this:
https://earth.bsc.es/gitlab/es/autosubmit/-/commit/e1afb3edacf12b7ad2179983b79ef84b4e9013bd

(only the autosubmit.py file, the rest are changes of 3.13 transferred into 3.14)

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 23, 2021, 12:51

Hi @dbeltrankyl 

I believe that the `setstatus` may be anecdotic. The main issue is that, after stopping and resuming Autosubmit, the wrapper status is `SUBMITTED`, as you say. Then, when Autosubmit realizes that the wrapper is running it starts to check all the jobs from the first one, even if they were already `COMPLETED`. This is a minor issue, I guess, since it only appears in the logs and cannot cause any problem since all these jobs had already the `COMPLETED` status.

The major issue is that, after `a3w5_20001101_fc00_6_SIM` is finished and Autosubmit detects it is `COMPLETED`, it does not detect that `a3w5_20001101_fc00_7_SIM` is `RUNNING`. All the rest of inner jobs in the wrapper remain in `QUEUING` status, even if the log displays:

```
2021-08-16 19:50:25,869 Successful check job command: sacct -n -X --jobs 17018865 -o "State"
2021-08-16 19:50:25,870 Checking inner jobs status
```

But the job must be RUNNING since it is the same wrapper in which `a3w5_20001101_fc00_6_SIM` was `COMPLETED` and Autosubmit keeps checking its status forever, so I think that those jobs will never be set to `COMPLETED` unless the user does it on their own.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 24, 2021, 12:07

Updated 3.13.0, now autosubmit will recognize the previous status of the wrapper.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 23, 2021, 14:55

I think this was solved with the last fix , I'll close it for now
