### ISSUE TITLE
Unhandled exception pointing to wrong reason when the date has wrong format.

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#73]
In GitLab by @orioltinto on Nov 16, 2015, 10:49

I just put a date with wrong format in the expdef configuration file but the error message does not point in that way. I let this issue here just in case someone else make the same mistake.

[CRITICAL] Unhandled exception on Autosubmit: 'NoneType' object has no attribute 'hour' Traceback (most recent call last): File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 274, in parse_args return Autosubmit.create(args.expid, args.noplot) File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 1252, in create if date.hour > 1: AttributeError: 'NoneType' object has no attribute 'hour'

**Comment by kinow** [comment]
In GitLab by @jvegreg on Jan 14, 2016, 10:35

Status changed to closed by commit 3e58ea46bb47e4cc23f474b4ddfde1b98e7f4ed9
