### ISSUE TITLE
New platform for the new Nord3 Slurm nodes

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#747]
In GitLab by @mcastril on Oct 25, 2021, 13:42

I open this issue because we need to test the new Nord3 Slurm nodes. In a few weeks, we will start deploying our workflows in the new platform so the first action is to check that Autosubmit can interface with it.

@wuruchi it would be also important to check if the new platform provides energy metrics, because we might use them in the DDBB.

At least I guess it will be easier to focus more on Slurm and not actively maintain LSF.

**Comment by kinow** [comment]
In GitLab by @wuruchi on Oct 26, 2021, 09:44

Hello @mcastril 

I am glad they are going to use Slurm at Nord3, it makes things easier. The current process should also cover this scenario.

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 27, 2021, 12:18

Hi, could you try this once that you finish any task that you are working on? It seems that they want to do a transition in about 2 weeks.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 27, 2021, 12:50

working on

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 28, 2021, 11:06

Hello @mcastril 

Seems that normal bash jobs are working fine. 

However, for wrappers(python always):

```
cat a02g_ASThread_16354116471989_10_6.err
/usr/bin/env: 'python': No such file or directory
```

and normal python jobs:

```
[ERROR] check_job() The job id (10973) status is -2.
Job a02g_20210920_00_1_SIM is QUEUING
Job a02g_20210921_00_1_SIM is UNKNOWN. Checking completed files to confirm the failure...
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 28, 2021, 11:09

The same goes for R

```
[bsc32070@login4 LOG_a02g]$ cat a02g_20210921_00_1_SIM.cmd.err
/usr/bin/env: 'Rscript': No such file or directory
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 28, 2021, 11:15

On terminal:

This works

`[bsc32070@login4 LOG_a02g]$ /usr/bin/env python2`

But this no

`[bsc32070@login4 LOG_a02g]$ /usr/bin/env python`

R only works after:

On terminal:

```
[bsc32070@login4 LOG_a02g]$ Module load R
[bsc32070@login4 LOG_a02g]$ /usr/bin/env R
```

Works

```
[bsc32070@login4 LOG_a02g]$ Module load R
[bsc32070@login4 LOG_a02g]$ /usr/bin/env Rscript` 
```

EDIT:
This work, but only if used within a template.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 28, 2021, 11:20

@mcastril , The solution seems easy for python ( not sure R) but there is an issue from Autosubmit side.

Until now, we were looking at the schedule variable but now I will need to look up the IP ( that can be an alias) or platform name ( that can be any) in order to put a special rule for this platform thus this include new constraints for ensure it correct behaviour.

Edit: We can put  a restriction that IP or PLATFORM NAME must contain "NORD" word... or

Edit2: In the process of checking if we're correctly connected to the remote platform, perform the command as follows: 

```
[bsc32070@login4 ~]$ grep `hostname` /etc/hosts | head -n1
10.2.9.201 login4 login4.nord3 s1m1u37
```
Then in Autosubmit filter this line and we would have always the name of the platform regardless it name or IP configured, this also will be useful for the next ECMWF platform

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 28, 2021, 11:24


Also, in a failed .cmd that contained the Python issue: 

```
[bsc32070@login4 LOG_a02g]$ squeue
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
             10718      main a03c_202 bsc32070 CG       0:03      2 s05r1b[12-13]

JOBID     NAME                     CPUS   NODES TIME_LIMIT TIME    FEATURES  QOS     PRIORITY  STATE     REASON    
10718     a03c_2021102412_MONARCH_148     2     5:00       0:03    (null)    debug   119659    COMPLETINGNonZeroExi
```

Seems that this job is stuck forever, the time doesn't advance and is forever in a "COMPLETING" state.

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 28, 2021, 16:52

> Edit2: In the process of checking if we're correctly connected to the remote platform, perform the command as follows:

You also have the `BSC_MACHINE` env var, which is available at least in `MN4` and `nord3`.

> But this no
> 
> `[bsc32070@login4 LOG_a02g]$ /usr/bin/env python`

I think this works for me. But maybe not in interactive mode?

Do you know why you were logged to login4?

> bsc32252@login1:~> salloc -q interactive
> salloc: error: s_p_parse_file: unable to status file /etc/slurm/slurm.conf: No such file or directory, retrying in 1sec up to 60sec
> ^C
> bsc32252@login1:~> salloc -p interactive
> salloc: error: s_p_parse_file: unable to status file /etc/slurm/slurm.conf: No such file or directory, retrying in 1sec up to 60sec

Well, it seems that interactive doesn't work like in mn4

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 29, 2021, 09:15

> Do you know why you were logged to login4?

I thought the nord4.bsc.es is the only node with the slurm, no?

According to Kim e-mail: 


> Support has been working in reinstalling Nord3 and it's ready for testing.

> To access: ssh bsc32XXX@nord4.bsc.es

**Comment by kinow** [comment]
In GitLab by @mcastril on Oct 29, 2021, 10:22

Ah yes, of course, I forgot it

Cannot you use `/usr/bin/env python2` in all platforms? Maybe they just didn't want to set a default Python

About R... is there any difference? I don't manage to get `/usr/bin/env Rscript` to work in `nord3` nor `mn4` either

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 2, 2021, 16:14

@kserradell @pabretonniere FYI. There are ongoing issues with R scripts due to the jobs not inheriting the environment loaded before doing `sbatch` (for jobs submitted with Paramiko, not for the ones submitted interactively). We have some workarounds but there's an open ticket to `operations`.

**Comment by kinow** [comment]
In GitLab by @kserradell on Nov 2, 2021, 16:18

Thanks for the update and for opening a ticket.

This inheritance of the environment is a critical issue that needs to be solved before opening the machine to the rest of the department.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 2, 2021, 16:46

Yes, the issue seems to be this one:

ERROR: Unable to locate a modulefile for 'R' 

It showed up when I did the paramiko_demo. This module can be found in an iterative terminal, but through paramiko can't be found, maybe this happens for all modules in nord4.bsc.es. Anyway, I sent to them the demo.py and the new log

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 2, 2021, 17:26

Although is just a warning, I see that also this is shown:

```
Command cd /gpfs/scratch/bsc32/bsc32070/a03d/LOG_a03d; tar -xvf wrapper_scripts.tar in nord4.bsc.es warning: tar: a03d_19600101_00_1_SIM.cmd: time stamp 2021-11-02 17:24:30 is 10.096099171 s in the future

tar: a03d_19600101_00_3_SIM.cmd: time stamp 2021-11-02 17:24:30 is 10.095080204 s in the future
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 2, 2021, 17:30

Hello @kserradell , @mcastril 

Using #!/usr/bin/env python2
I can run python scripts on nord4.bsc.es, however, the wrappers are failed due to a missing library:

```
Traceback (most recent call last):
  File "/var/spool/slurmd/job11503/slurm_script", line 21, in <module>
    from bscearth.utils.date import date2str 
ImportError: No module named bscearth.utils.date
```


This module is not in nord4.bsc.es. I use this for the vertical wrappers

`from bscearth.utils.date import date2str `

Edit: Is only one function so I can export it into the wrapper script if is not possible have this library

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 2, 2021, 17:37

> Cannot you use `/usr/bin/env python2` in all platforms? Maybe they just didn't want to set a default Python

Seems that python2 is fine( a side of the comment of the wrappers on nord3), I will add python3 into 3.14.0 tho. So we will have 

```
TYPE = Bash
TYPE = R
TYPE = python (python 2, default)
TYPE = python3 (python 3) 
```

**Comment by kinow** [comment]
In GitLab by @kserradell on Nov 2, 2021, 17:38

@dbeltrankyl which python binary are you using?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 2, 2021, 17:42

I put 
`#!/usr/bin/env python2 `at the beginning of the file,

So I guess it is using this one:

```
[bsc32070@login4 ~]$ type -a python2
python2 is /usr/bin/python2
```

```
[bsc32070@login4 ~]$ /usr/bin/python2 
Python 2.7.18 (default, Jan 22 2021, 11:25:37) 
[GCC 8.4.1 20200928 (Red Hat 8.4.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from bscearth.utils.date import date2str 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named bscearth.utils.date
```

**Comment by kinow** [comment]
In GitLab by @kserradell on Nov 2, 2021, 17:46

I don't really understand the issue here. I can't reproduce the issue in Nord3.

```
[bsc32353@MN3:login1 ~]$ /usr/bin/python2
Python 2.6.9 (unknown, Mar 31 2014, 22:15:20)
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from bscearth.utils.date import date2str
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named bscearth.utils.date
>>>
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 2, 2021, 17:59

I don't really need this module anymore, I double-checked the code and the part that was using this module was replaced by another code. However, if somebody wants to use the module bscearth, seems that is not available since whenever you try to import it it will display

`ImportError: No module named bscearth.utils.date`

because it seems that bscearth module is not available.

Edit: It is a module that can be installed with pip, I'm using it in the main code of autosubmit for functions like: 

`jobs_date = filter(lambda j: date2str(j.date) == date, job_list.get_job_list())`

but the wrapper of inner jobs also had an import that reference this module and seems that is not available on nord4.bsc.es, however like I said, I don't use it anymore on the wrapper so I can erase the import line

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 2, 2021, 18:09

@dbeltrankyl but looking at Kim's test, it seems that it isn't available in Nord3 (the other nodes) either?

If that's the case, how we are able to run jobs in Nord3 right now.

**Comment by kinow** [comment]
In GitLab by @kserradell on Nov 2, 2021, 18:17

@dbeltrankyl Could we have a short meeting tomorrow to solve this issue? I'm quite confused.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 2, 2021, 18:18

Sorry, I think it's my fault. 

I think I had in the bashrc the module load python/2.7.14 loaded due to some test I did while I was working on that code. In that version, it works. While in the default one it doesn't work

**Comment by kinow** [comment]
In GitLab by @kserradell on Nov 2, 2021, 18:19

Great!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 4, 2021, 09:19

Hello @kserradell , @mcastril 

Seems that they found the issue with the modules. 

> Hola, Daniel:
> 
> Os contacto para informar que hemos dado con el problema y ya hemos avisado a
> los compañeros de sysadmin para que lo solucionen.
> 
> Tan pronto como lo arreglen, os avisamos.
> 
> Un saludo,
> 
> Cristian

**Comment by kinow** [comment]
In GitLab by @kserradell on Nov 11, 2021, 15:22

@dbeltrankyl, is this issue. https://earth.bsc.es/gitlab/es/requests/-/issues/1626

As soon as you validate the workaround, please confirm. After the mail announcement, I would like to start the migration as soon as possible.
