### ISSUE TITLE
Autosubmit is hanging after the wrapped jobs have completed (deadlock?)

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#749]
In GitLab by @vlap on Nov 1, 2021, 24:01

Hi @dbeltrankyl and @mcastril,

I am running several coupled (atm+oce) ecearth experiments, using vertical wrappers of the SIM jobs. In two of them (`a404` and `a405`) something went wrong with autosubmit and it stopped correctly registering the change in job status. Here is from `a403`: the relevant bit 
```
305 of 332 jobs remaining (13:43)
Job a403_19800101_fc00_5_SIM is RUNNING

305 of 332 jobs remaining (13:44)
[38;5;214m[ERROR] Trace: [0m[39m
[38;5;214m[ERROR] Command sacct -n -X --jobs 18111867 -o "State" in mn-bsc32 warning:  [eCode=6005][0m[39m
Waiting 30 seconds before continue
Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Using existing valid structure.
Checking the connection to all platforms in use
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1579, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1706, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
[32m[marenostrum4] Connection successful to host mn-bsc32[0m[39m
[32m[local] Connection successful to host localhost[0m[39m
[32m[local] Correct user privileges for host localhost[0m[39m
[32m[nord3] Connection successful to host nord1.bsc.es[0m[39m
[32m[nord3] Correct user privileges for host nord1.bsc.es[0m[39m
[32m[transfer_node] Connection successful to host dt02.bsc.es[0m[39m
[32m[transfer_node] Correct user privileges for host dt02.bsc.es[0m[39m
Couldn't recover the platforms, retrying in 30seconds...
Checking the connection to all platforms in use
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1579, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1706, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
[32m[marenostrum4] Connection successful to host mn-bsc32[0m[39m
[32m[local] Connection successful to host localhost[0m[39m
[32m[local] Correct user privileges for host localhost[0m[39m
[32m[nord3] Connection successful to host nord1.bsc.es[0m[39m
[32m[nord3] Correct user privileges for host nord1.bsc.es[0m[39m
[32m[transfer_node] Connection successful to host dt02.bsc.es[0m[39m
[32m[transfer_node] Correct user privileges for host dt02.bsc.es[0m[39m
Couldn't recover the platforms, retrying in 30seconds...
Checking the connection to all platforms in use
[32m[local] Connection successful to host localhost[0m[39m
[32m[local] Correct user privileges for host localhost[0m[39m
[32m[nord3] Connection successful to host nord1.bsc.es[0m[39m
[32m[nord3] Correct user privileges for host nord1.bsc.es[0m[39m
[32m[transfer_node] Connection successful to host dt02.bsc.es[0m[39m
[32m[transfer_node] Correct user privileges for host dt02.bsc.es[0m[39m
Couldn't recover the platforms, retrying in 30seconds...
Checking the connection to all platforms in use
[32m[marenostrum4] Connection successful to host mn-bsc32[0m[39m
[32m[local] Connection successful to host localhost[0m[39m
[32m[local] Correct user privileges for host localhost[0m[39m
[32m[nord3] Connection successful to host nord1.bsc.es[0m[39m
[32m[nord3] Correct user privileges for host nord1.bsc.es[0m[39m
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1579, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1706, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
[32m[transfer_node] Connection successful to host dt02.bsc.es[0m[39m
Couldn't recover the platforms, retrying in 30seconds...
Checking the connection to all platforms in use
[32m[marenostrum4] Connection successful to host mn-bsc32[0m[39m
[32m[local] Connection successful to host localhost[0m[39m
[32m[local] Correct user privileges for host localhost[0m[39m
[32m[nord3] Connection successful to host nord1.bsc.es[0m[39m
[32m[nord3] Correct user privileges for host nord1.bsc.es[0m[39m
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1579, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/shared/earth/software/autosubmit/3.13.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/paramiko-1.15.0-py2.7.egg/paramiko/transport.py", line 1706, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
[32m[transfer_node] Connection successful to host dt02.bsc.es[0m[39m
Couldn't recover the platforms, retrying in 30seconds...
Checking the connection to all platforms in use
[32m[marenostrum4] Connection successful to host mn-bsc32[0m[39m
[32m[local] Connection successful to host localhost[0m[39m
[32m[local] Correct user privileges for host localhost[0m[39m
[32m[nord3] Connection successful to host nord1.bsc.es[0m[39m
[32m[nord3] Correct user privileges for host nord1.bsc.es[0m[39m
[32m[transfer_node] Connection successful to host dt02.bsc.es[0m[39m
[32m[transfer_node] Correct user privileges for host dt02.bsc.es[0m[39m
Couldn't recover the platforms, retrying in 30seconds...
Checking the connection to all platforms in use
[32m[marenostrum4] Connection successful to host mn-bsc32[0m[39m
[32m[marenostrum4] Correct user privileges for host mn-bsc32[0m[39m
[32m[local] Connection successful to host localhost[0m[39m
[32m[local] Correct user privileges for host localhost[0m[39m
[32m[nord3] Connection successful to host nord1.bsc.es[0m[39m
[32m[nord3] Correct user privileges for host nord1.bsc.es[0m[39m
[32m[transfer_node] Connection successful to host dt02.bsc.es[0m[39m
[32m[transfer_node] Correct user privileges for host dt02.bsc.es[0m[39m


305 of 332 jobs remaining (13:53)
Wrapper job a403_ASThread_16353422957518_768_3 changed from SUBMITTED to status RUNNING
Job a403_19800101_fc00_1_SIM started at 2021-10-29 07:17:15
Job a403_19800101_fc00_1_SIM is RUNNING
[32mJob a403_19800101_fc00_1_SIM is COMPLETED[0m[39m
Job a403_19800101_fc00_1_SIM finished at 2021-10-29 08:45:32


307 of 332 jobs remaining (13:54)
Job a403_19800101_fc00_2_SIM started at 2021-10-29 08:45:32
Job a403_19800101_fc00_2_SIM is RUNNING
[32mJob a403_19800101_fc00_2_SIM is COMPLETED[0m[39m
Job a403_19800101_fc00_2_SIM finished at 2021-10-29 10:13:10


306 of 332 jobs remaining (13:54)
Job a403_19800101_fc00_3_SIM started at 2021-10-29 10:13:10
Job a403_19800101_fc00_3_SIM is RUNNING
[32mJob a403_19800101_fc00_3_SIM is COMPLETED[0m[39m
Job a403_19800101_fc00_3_SIM finished at 2021-10-29 11:40:51


305 of 332 jobs remaining (13:54)


305 of 332 jobs remaining (13:54)


305 of 332 jobs remaining (13:55)


305 of 332 jobs remaining (13:55)
Failed to retrieve log files a403_19800101_fc00_1_SIM.cmd.out and a403_19800101_fc00_1_SIM.cmd.err e=6001


305 of 332 jobs remaining (13:55)
Failed to retrieve log files a403_19800101_fc00_2_SIM.cmd.out and a403_19800101_fc00_2_SIM.cmd.err e=6001


305 of 332 jobs remaining (13:55)
Failed to retrieve log files a403_19800101_fc00_3_SIM.cmd.out and a403_19800101_fc00_3_SIM.cmd.err e=6001


305 of 332 jobs remaining (13:55)
```
`a403` has been hanging in a deadlock, not updating job statuses of completed jobs and doing nothing.

`a404` is also hanging in a deadlock but it does not even write anything into the log. Autosubmit run  task is still active but log has last been updated on Oct 29.

In realily, the wrappers have finished successfully but autosubmit cannot update itself accordingly.

I have killed these autosubmit instances, run status recovery and restarted the experiments.

PS I do not have much experience with wrappers and not sure whether this problem is caused by the wrappers or not. Sorry, if this situation has already been addressed somewhere.

**Comment by kinow** [comment]
In GitLab by @acarreri on Nov 2, 2021, 09:33

Hi,

I think I have the same issue with one of my experiment (`a3zy`), with vertical wrappers also.
In AS, the experiment seems stuck: ![Capture_d_écran_2021-11-02_091603](https://earth.bsc.es/gitlab/es/autosubmit/uploads/5cbd4ca33df9899b5d9147d60061f9f3/Capture_d_écran_2021-11-02_091603.jpg)

In the GUI, it appears `RUNNING` but since more than 3 days which is not possible. ![Capture_d_écran_2021-11-02_091542](https://earth.bsc.es/gitlab/es/autosubmit/uploads/6b2a0547f14de20261da29339b6c5af7/Capture_d_écran_2021-11-02_091542.jpg)

The job is not running anymore on MN4, there is no log file associated with this SIM job in `/esarchive/autosubmit/a3zy/tmp/LOG_a3zy/` but in `/gpfs/scratch/bsc32/bsc32283/a3zy/LOG_a3zy/a3zy_ASThread_16354181742936_1248_2.out`, it's indicated:
~~~
a3zy_19800101_fc00_6_SIM.cmd.out

2021-10-29 12:15:59.758422 The job  a3zy_19800101_fc00_6_SIM.cmd  has been COMPLETED
a3zy_19800101_fc00_7_SIM.cmd.out

2021-10-29 18:57:45.587706 The job  a3zy_19800101_fc00_7_SIM.cmd  has been COMPLETED
~~~

Note also that I had to kill autosubmit (with the kill command I mean).

Hope it adds some inputs to understand the issue.

Thanks

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 2, 2021, 09:47

It seems that both issues are related to remote platform issues during the weekend,

Usually, autosubmit is able to recover(from 3.13.0) and continue to run, and about the LOG recovery I think they were killed(timeout) before they could recover the log err and out from the remote. 

The jobs could finish correctly, but autosubmit weren't able to correctly re-establish the connection to the slurm scheduler, 

What I'm not sure is why this time Autosubmit was not able to continue the experiment, because this same scenario happened before and was fixed. I'll check

**Comment by kinow** [comment]
In GitLab by @vlap on Nov 2, 2021, 10:16

thanks @dbeltrankyl. Yes, it seems to be caused by platform issues but, as you say, autosubmit could not re-establish itself correctly. If you think that this behavior is in a way normal, feel free to close the issue.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 2, 2021, 13:48

Hi @vlap ,

I just noticed that you're using 3.13.0b, you should be using 3.13.0. 

3.13.0b was the beta version ( as b) indicate, but 3.13.0 has fixes ( like this one) and is also the default autosubmit version and the recommended one

**Comment by kinow** [comment]
In GitLab by @vlap on Nov 2, 2021, 13:49

ok, thanks, noted. I copied it from the issue with pre-submission and thought it was necessary to run with pre-submission. is pre-submission available with 3\.13.0?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 2, 2021, 14:24

Yes, I sent an email indicating that I will erase 3.13.0b version next week and users must use the 3.13.0 one. 

I will close this issue, if this happens with the default version , please reopen it again.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 2, 2021, 14:27

Yes, 3.13.0 has the same features as 3.13.0b but with bug-fixes that were included in a post-release. 

and 3.14.0b has extended features but is still in beta and not recommended right now

**Comment by kinow** [comment]
In GitLab by @acarreri on Nov 2, 2021, 14:29

Hi @dbeltrankyl ,

I don't know if the behaviour I had with `a3zy` is a normal one or not, but I really think I'm using 3.13.0. 

Could you tell me if something's wrong or if it's what you expect? cf this [comment](https://earth.bsc.es/gitlab/es/autosubmit/-/issues/749#note_151309). Note that I had to do a recovery before relaunching the experiment. 

Thanks

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 2, 2021, 14:41

@acarreri , I think is this case is a different issue. 

Seems that autosubmit waited forever in a petition sent to marenostrum4, this could be due to an issue in the remote_platform. 

However, there is a timeout in all remote communications that never was triggered( timeout is 120 seconds) so I believe that there was an uncommon bug in paramiko library( external to autosubmit code) 

For 3.13.0, this won't be fixed but perhaps in 3.14.0 we can update the paramiko version ( @mcastril ) to see if the bug is solved.

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 2, 2021, 15:44

@eferre1 suffered the same problem in #455. +1 for updating Paramiko and see if it is more robust against connection issues

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 2, 2021, 15:48

> ok, thanks, noted. I copied it from the issue with pre-submission and thought it was necessary to run with pre-submission. is pre-submission available with 3.13.0?

Are you testing it @vlap ?

**Comment by kinow** [comment]
In GitLab by @eferre1 on Nov 2, 2021, 15:52

As @mcastril said, I had the same problem in `a3pg`, that stopped working at the same time as the other experiments reported here. I checked and it is using the standard 3.13.0 version and the problem seems that the logs were never retrieved from marenostrum, but autosubmit didn't detect that they were there and recovered automatically, and in my case it stopped its execution but on the GUI it showed it as running (I think this was more an issue of the GUI not being able to detect the correct status since it is not finished nor failed). I ran `autosubmit recovery` and then `autosubmit run` and everything was solved.

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 2, 2021, 15:57

Yes, @acarreri @eferre1 the GUI takes the step statuses from Autosubmit internal database. Therefore, in case that Autosubmit is stopped, the GUI will never update its status.

There was a warning in the GUI for experiments that the GUI detects they are not updating their logs anymore. @wuruchi can you refresh my mind? I think it was only present on the search page, wasn't it? If that's true, could a similar warning be shown on the experiment page?

**Comment by kinow** [comment]
In GitLab by @vlap on Nov 2, 2021, 16:10

yes, it runs fine, it probably helps with the queuing times but because of the autosubmit crash/restart I reported here I do not have a clean comparison that I wanted (two virtually identical experiments with wrappers submitted simultaneously, one with pre-submission and one without)

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 2, 2021, 16:31

Thanks, @vlap, I wanted to check the logs to see if Autosubmit was choosing well the jobs to put on `HELD` status. I did it and it seems to be ok. 

When the 3 experiments end, we can compare the total queuing time shown in the `Stats` section. So far `a405` has been queuing much more time, but it's also beyond the others in progress.

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 2, 2021, 16:35

> When the 3 experiments end, we can compare the total queuing time shown in the `Stats` section. So far `a405` has been queuing much more time, but it's also beyond the others in progress.

Moreover, I think that we need to correct how the statistics are computed for `HELD` jobs. I suspect that it is counting `HELD` time as queuing time. Opening an issue (#750).

**Comment by kinow** [comment]
In GitLab by @wuruchi on Nov 2, 2021, 16:59

Hello @mcastril @eferre1 

There is a warning sign that is displayed on the control bars of the Tree and Graph Views when the experiment activity is **suspicious**. Specifically: When the experiment log has been inactive for more than 10 minutes but there are jobs in status `QUEUING`, `SUBMITTED`, or `RUNNING in the `pkl`.

**Comment by kinow** [comment]
In GitLab by @eferre1 on Nov 2, 2021, 17:02

Thanks @wuruchi, I think I've seen that warning sometimes but I might have missed it this time.

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 2, 2021, 17:02

Thanks @wuruchi for refreshing my mind. @eferre1 @acarreri do you remember seeing something like @wuruchi is describing? If not, maybe we could make the sign even more annoying (adding some blinking or something? and maybe a way to dismiss the sign to not torture users with false-positive signs)

**Comment by kinow** [comment]
In GitLab by @eferre1 on Nov 2, 2021, 17:04

Yes, I can confirm that the HELD jobs are counting the time as if they were QUEUEING, I saw that behaviour in `a3pg`.

**Comment by kinow** [comment]
In GitLab by @acarreri on Nov 2, 2021, 17:14

As you can see in this [comment](https://earth.bsc.es/gitlab/es/autosubmit/-/issues/749#note_151309), the GUI didn't show any suspicious warning.

Also I had to kill AS (with a kill -9 command line), it was stuck, it was not stopped.

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 2, 2021, 17:28

I think that the warning should be out of that crop region, together with the control bars

> Also I had to kill AS (with a kill -9 command line), it was stuck, it was not stopped.

The GUI controls the log update, so it should be the same

**Comment by kinow** [comment]
In GitLab by @wuruchi on Nov 2, 2021, 18:07

Hello @mcastril @acarreri 

I think this is proof that the warning is not disruptive enough. I will make it show as a pop up when you open the experiment. Suggestions are welcomed.

**Comment by kinow** [comment]
In GitLab by @vlap on Nov 2, 2021, 23:27

thanks for taking a look, @mcastril. it's as you say

**Comment by kinow** [comment]
In GitLab by @vlap on Nov 2, 2021, 23:30

yeah, I also have no idea where the warning is supposed to be. Not sure I have ever seen it. And this is not the first time that I have had to kill/refresh/restart autosubmit. Usually after some infrastructure issues.
