### ISSUE TITLE
IOError: [Errno 116]

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#759]
In GitLab by @ rambika on Dec 7, 2021, 11:45

While doing autosubmit trails and auto-monarch test, I am facing the following error: 

`Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/logging/__init__.py", line 883, in emit
    self.flush()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/logging/__init__.py", line 843, in flush
    self.stream.flush()
IOError: [Errno 116] Stale file handle
Logged from file log.py, line 286
` 

This is occurring in every step. However the jobs seems to be running. Did anyone came across this issue before? 

P.S: I am running auto submit on bscesautosubmit01.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 7, 2021, 12:48

Yes, this happens when there are issues in our esarchive. The experiment will continue running but some logs may not be saved.

The next version will have some mechanism to reduce these kinds of errors or recover them if the error is fatal.

However the underlying issue is the filesystem itself.

**Comment by kinow** [comment]
In GitLab by @ rambika on Dec 7, 2021, 12:53

@dbeltrankyl Thank you for the information. Just wanted to make sure this doesn't affect the runs.
