### ISSUE TITLE
autosubmit resubmitting finished jobs

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#767]
In GitLab by @ rmahmood on Jan 6, 2022, 14:46

Hi, @dbeltrankyl ,@wuruchi ,

Experiment id: a3xx

I stopped autosubmit to make changes to maximum number of jobs running/queuing in the autosubmit configuration file. The local setup was rerun. Somehow autosubmit is trying resubmit the completed jobs again. Below are some error messages:

 `[CRITICAL] The current host is not allowed to run Autosubmit [eCode=7004]` , Is this related to nord3?

```
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/logging/__init__.py", line 883, in emit
    self.flush()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/logging/__init__.py", line 843, in flush
    self.stream.flush()
IOError: [Errno 116] Stale file handle
Logged from file log.py, line 286
```

FYI: @ yruprich

**Comment by kinow** [comment]
In GitLab by @wuruchi on Jan 6, 2022, 16:18

Hello @ rmahmood 

> \[CRITICAL\] The current host is not allowed to run Autosubmit \[eCode=7004\]

This error happens because you are trying to run Autosubmit **from** a machine that is not allowed to do it. For example, your workstation. You can run Autosubmit on `bscesautosubmit01` or `bscesautosubmit02`. Make sure you are using any of these hosts.

Then, the other error seems related to the infrastructure, but the most important error is the one I mentioned above.

**Comment by kinow** [comment]
In GitLab by @ rmahmood on Jan 6, 2022, 19:00

Ah! sorry my mistake. Was trying to run from workstation. Thanks @wuruchi
