### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#782]
In GitLab by @pablohe on Feb 20, 2022, 20:42

Hi @mcastril @wuruchi @dbeltrankyl ! 

I'm trying to install autosubmit via pip in centos 8 and I'm getting the following error:

```bash
[pablo@hypatia ~]$ lsb_release -d
Description:	CentOS Linux release 8.2.2004 (Core) 
[pablo@hypatia ~]$ python3 -m venv autosubmit
[pablo@hypatia ~]$ source autosubmit/bin/activate
(autosubmit) [pablo@hypatia ~]$pip install autosubmit
....

(autosubmit) [pablo@hypatia ~]$ autosubmit configure
Traceback (most recent call last):
  File "/home/pablo/autosubmit/bin/autosubmit", line 32, in <module>
    from autosubmit.autosubmit import Autosubmit
  File "/home/pablo/autosubmit/lib64/python3.6/site-packages/autosubmit/autosubmit.py", line 1083
    "pkl", "job_packages_" + expid + ".db"), 0644)
                                                ^
SyntaxError: invalid token
```

any autosubmit command returns the same error

Tchus!

**Comment by kinow** [comment]
In GitLab by @pablohe on Feb 20, 2022, 20:43

I'm following http://www.bsc.es/projects/earthscience/autosubmit/installation.html

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 21, 2022, 09:09

Hello @pablohe ,

I was unaware of the existence of the link that you mentioned, the correct installation info is insides in readthedocs ( https://autosubmit.readthedocs.io/en/master/installation.html?highlight=installation )

It seems that the error is related to using python 3.6 instead of python 2. 

Please use python 2 instead of python 3. Python3 is planned for Autosubmit 4.0 (April)

We are discussing the installation in #753. As oriol mentioned, these are the steps that you may need to execute:

```shell
 Update repositories
apt update

# Avoid interactive stuff
export DEBIAN_FRONTEND=noninteractive

# Dependencies
apt install wget curl python2 python-tk python2-dev graphviz -y -q

# Additional dependencies related with pycrypto
apt install build-essential libssl-dev libffi-dev -y -q

# Download get pip script and launch it
wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
python2 get-pip.py

# Install autosubmit using pip
pip2 install autosubmit

# Check that we can execute autosubmit commands
autosubmit -h

# Configure
autosubmit configure

# Install
autosubmit install

# Get expid
autosubmit expid -H TEST -d "Test exp."

# Create with -np
# Since it was a new install the expid will be a000
autosubmit create a000 -np
```

The readthedocs should have this example soon, however, there is an issue with the build compilation and the auto-build procedure didn't trigger last week

**Comment by kinow** [comment]
In GitLab by @pablohe on Feb 21, 2022, 12:27

Hi! many thanks @dbeltrankyl 

I'll test it.

**Comment by kinow** [comment]
In GitLab by @pablohe on Feb 21, 2022, 16:06

It worked. Many thanks.

**Comment by kinow** [comment]
In GitLab by @mcastril on Feb 21, 2022, 17:15

Thank you @pablohe for reporting that, and welcome back in GitLab
