### ISSUE TITLE
GUI: Wrappers order in the Tree View

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#803]
In GitLab by @mcastril on Apr 4, 2022, 11:28

@wuruchi do you think that wrappers could be ordered in alphabetical order? I think this will lead to a temporal order which would make easier to follow.

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 5, 2022, 12:13

Hi @mcastril , Can you please provide an existing example of wrong ordering in experiments with wrappers ? this issue applies both vertical and horizontal wrappers ? I checked one and I think it looks good or I am missing something:

https://earth.bsc.es/autosubmitapp/experiment/a11x

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 5, 2022, 14:59

thanks for the example @mcastril

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 5, 2022, 17:23

I created a new branch (AS_API_Issue_803_ordering_wrappers) to test the changes done, I will debug in the development machine

**Comment by kinow** [comment]
In GitLab by @mcastril on Jul 6, 2022, 16:35

I thought that we had disabled the CAS authentication in the dev. webserver. It's not open to outside so it wouldn't be any security risk.

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 6, 2022, 16:38

yes, that is true, but I think some features requires the user to be authenticated based on some Wilmer comments

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 6, 2022, 16:42

ok sounds good

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 7, 2022, 10:45

yesteday after updating the API in the VM, I ran on this error:

```
[2022-07-07 09:52:47 +0000] [436880] [INFO] RUN|RECEIVED|
[2022-07-07 09:52:47 +0000] [436880] [ERROR] Exception on /running/ [GET]
Traceback (most recent call last):
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/autosubmit_api/app.py", line 215, in search_running
    result = get_current_running_exp()
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/autosubmit_api/database/db_common.py", line 421, in get_current_running_exp
    cursor.execute(query)
OperationalError: no such table: listexp
```


is it weird since I did not modify anything related to it since. I will try to figure out what can be

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 7, 2022, 17:26

I guess is enough to copy the experiment you mentioned @mcastril that has wrappers to the VM so I can test the changes and see how it works with a real example. do I need to do also some other stuff of with just copying the folder is enought ?

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 7, 2022, 17:36

I found one so there is no need to copy anything:

`http://84.88.189.213/autosubmitapp/experiment/a4h9`

**Comment by kinow** [comment]
In GitLab by @mcastril on Jul 8, 2022, 09:28

I was going to ask if there wasn't any other experiment having wrappers, I thought I remembered that we had at least one.

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 8, 2022, 09:36

Hi @mcastril I can search, anyways the changes I did not work as expected, I need to dig more in the code

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 14, 2022, 12:58

I just finished the changes and it seems that it works fine, who can validate this ?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 14, 2022, 14:00

I'm not using the GUI regularly, so maybe @eferre1 can validate it better than me ( if he has time)

**Comment by kinow** [comment]
In GitLab by @eferre1 on Jul 14, 2022, 14:30

I have to run some "long" experiments (5 members - 20 chunks) for auto-ecearth3#1758, so I will be able to check it soon if it is not too urgent.

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 14, 2022, 14:32

It needs to be tested in the development environment, where the changes are deployed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 14, 2022, 14:34

In that case

@ jberlin maybe you can copy the tests that @eferre1 will use and run them with project_type = None and afterwards, compare them

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 14, 2022, 14:36

yeah sounds good, after @eferre1 finished running the exp we can compare both in dev and production

**Comment by kinow** [comment]
In GitLab by @eferre1 on Jul 14, 2022, 14:39

If you can open ongoing experiments in the development environment (or copy the .db files to "fake clone" them), then you could use the `a28v` experiment that is already running with wrappers and in the current GUI tree view is not being sorted out (the current running wrapper is in the middle of the wrappers list). 

If not, don't try to run a copy of it though, it is the VHR run from Edu and it cannot run in the normal queues of bsc32 accounts, we will do it once I have the other experiments finished.

PS: although in that experiment the GUI shows this in red at the top: `database disk image is malformed` (not sure if it affects something)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 14, 2022, 14:42

In Autosubmit debug mode, ( project_type = None ) , it can run anything as it doesn't run the real templates, only the workflow structure. Would just be a matter of changing the platform.conf to the bsc user (and the QUEUE to debug to speedup the queuing time)

**Comment by kinow** [comment]
In GitLab by @eferre1 on Jul 14, 2022, 14:49

Ok, I didn't know that, then yes, you could already check with that a28v experiment (it is a big one), or wait for my runs to do it.

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 14, 2022, 15:43

so cpying these files /esarchive/autosubmit/a28v to the virtual machine Autosubmit folder will be enough o check this properly ?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 14, 2022, 15:52

No, because it won't be registered in the DB and the GUI won't see the experiment ( I believe) 

What I do to test an office experiment in my local home is to: 

1. Create a new experiment with `autosubmit expdef -dm`
1. `scp office:/esarchive/autosubmit/<expid>/conf/* autosubmit/<expid>/conf`
1. Change configuration names per the name of the new expid
1. in autosubmit.conf, change `[config] EXPID = <original> EXPID = <new_id>`
1. in expdef.conf, change `[default] EXPID = <original> EXPID = <new_id>`
1. in dummy case, change project -> project_type = git for project_type = none 
1. in platform.conf, change platforms for your user.
1. in dummy case, change bsc_es or class_a per debug. 


This is because there is no way of doing an autosubmit remote copy from one machine to another ( may be worth doing this feature in the future? ) 

edit: Or a command like fixconf that does these steps

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 14, 2022, 16:32

I simply copied it and the API picket it up:

http://84.88.189.213/autosubmitapp/experiment/a28v

@eferre1 can you please check when you have some spare time ? thanks!

**Comment by kinow** [comment]
In GitLab by @eferre1 on Jul 14, 2022, 16:33

How can I check it? I cannot access that url that you mention @ jberlin

**Comment by kinow** [comment]
In GitLab by @eferre1 on Jul 14, 2022, 16:39

Ok, it seems to be working, as you can see here in the images below.

Actual GUI tree view, the running wrapper is in the middle (not sorted):

![Screenshot_from_2022-07-14_16-35-01](https://earth.bsc.es/gitlab/es/autosubmit/uploads/695351c57505cb9954b49b97f4736361/Screenshot_from_2022-07-14_16-35-01.png)

Development GUI view, the running wrapper is at the end (sorted out):

![Screenshot_from_2022-07-14_16-35-04](https://earth.bsc.es/gitlab/es/autosubmit/uploads/ce547bcbce38ff01fdc81f5d7eb758ce/Screenshot_from_2022-07-14_16-35-04.png)

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 14, 2022, 16:45

great ! thanks @eferre1

**Comment by kinow** [comment]
In GitLab by @ jberlin on Jul 28, 2022, 09:37

We should plan the deployment of the new release, I guess is better to accumulate several fixes in one deploy so we dont disrupt too much the users.

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 16, 2022, 18:27

mentioned in issue autosubmitreact#9

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 18, 2022, 10:12

moved to autosubmit_api#8
