### ISSUE TITLE
"autosubmit create" : when credentials are inserted incorrectly, repetition fails

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#81]
In GitLab by @obellprat on Jan 7, 2016, 11:00

Hi @dmanubens and @jvegreg ,

I inserted my password wrongly when running autosubmit create. When I repeat it I get this error. How can I fix this? 

Thanks,
Omar

autosubmit create a03l

Checking configuration files...
autosubmit_a03l.conf OK
platforms_a03l.conf OK
jobs_a03l.conf OK
expdef_a03l.conf  OK
Configuration files OK

Using project folder: /esnas/autosubmit/a03l/proj
[CRITICAL] Unhandled exception on Autosubmit: [Errno 2] No such file or directory: '/esnas/autosubmit/a03l/proj/model/templates/ecearth3/ecearth3.conf'
Traceback (most recent call last):
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 274, in parse_args
    return Autosubmit.create(args.expid, args.noplot)
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 1224, in create
    Autosubmit._create_project_associated_conf(as_conf, False, update_job)
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 1184, in _create_project_associated_conf
    project_destiny)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/esnas/autosubmit/a03l/proj/model/templates/ecearth3/ecearth3.conf'

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jan 7, 2016, 11:12

Hi @obellprat ,

You can just do ```autosumbit refresh a03l```
Otherwise you can just delete the a03l/proj folder and try create again.

Best

**Comment by kinow** [comment]
In GitLab by @obellprat on Jan 7, 2016, 12:22

Great, thanks a lot.
