### ISSUE TITLE
Compatibility issue 3.2.0b2

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#83]
In GitLab by @kserradell on Jan 8, 2016, 14:49

When running a03i with AS 3.2.0b2,

```python
Starting job submission...
[CRITICAL] Unhandled exception on Autosubmit: 'MN3'
Traceback (most recent call last):
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/autosubmit/autosubmit.py", line 278, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/autosubmit/autosubmit.py", line 553, in run_experiment
    Autosubmit._load_parameters(as_conf, joblist, submitter.platforms)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/autosubmit/autosubmit.py", line 492, in _load_parameters
    platform = platforms[as_conf.get_platform()]
KeyError: 'MN3'
```

**Comment by kinow** [comment]
In GitLab by @jvegreg on Jan 14, 2016, 10:35

Status changed to closed by commit c97f66d8073af28ae96bc30d2c7fd617d291be7d
