### ISSUE TITLE
Autosubmit clean not working as expected

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#838]
In GitLab by @eferre1 on Jun 21, 2022, 12:21

Hi @dbeltrankyl, I was going to clean the release experiments from auto-ecearth3 3.3.3.2 release with the `autosubmit clean expid -pr -p -s` command to reduce a bit the space used in esarchive, but it is not working as expected (even though I just ran a refresh so there are no local changes). Here is the message printed by autosubmit:

```
eferre1@ bscesautosubmit01:~> autosubmit clean t06a -pr -p -s

Checking configuration files...
expdef_t06a.conf OK
platforms_t06a.conf OK
jobs_t06a.conf OK
wrappers OK
autosubmit_t06a.conf OK
Configuration files OK

Registering commit SHA...
Cleaning GIT directory...
Changes not pushed detected... SKIPPING!
 [CRITICAL] Synchronization needed! [eCode=7064]
More info at https://autosubmit.readthedocs.io/en/latest/faq.html
```

The problem as I see it, is that after the refresh the experiment `/proj/auto-ecearth3/` is in detached mode, so it detects it as having local changes and the `clean` fails. Below I add the refresh and status logs:

<details><summary>autosubmit refresh</summary>

```
autosubmit version:
3.13.0

refreshing: t06a:  t06a tag 3.3.3.2 test case: ORCA1L75 +  surface restoring - CHUNKSIZE=12 marenostrum4 
sed -i 's/PROJECT_ORIGIN = https\:\/\/earth.bsc.es\/gitlab\/es\/auto-ecearth3.git/PROJECT_ORIGIN = https:\/\/eferre1.bsc.es\/gitlab\/es\/auto-ecearth3.git/g' /esarchive/autosubmit/t06a/conf/expdef_t06a.conf

Checking configuration files...
expdef_t06a.conf OK
platforms_t06a.conf OK
jobs_t06a.conf OK
wrappers OK
autosubmit_t06a.conf OK
Configuration files OK

Making a backup of your current proj folder at /esarchive/autosubmit/t06a/proj_1655803291
Cloning 3.3.3.2 https://eferre1@ earth.bsc.es/gitlab/es/auto-ecearth3.git into /esarchive/autosubmit/t06a/proj
Cloning into 'auto-ecearth3'...
remote: Enumerating objects: 19912, done.
remote: Counting objects: 100% (6241/6241), done.
remote: Compressing objects: 100% (1223/1223), done.
remote: Total 19912 (delta 5924), reused 5045 (delta 5018), pack-reused 13671
Receiving objects: 100% (19912/19912), 45.66 MiB | 7.52 MiB/s, done.
Resolving deltas: 100% (13386/13386), done.
Note: checking out '947f9227af11c879cb96971ea413646d6f84e304'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Checking out files: 100% (379/379), done.
Submodule 'ece2cmor' (https://earth.bsc.es/gitlab/es/ece2cmor.git) registered for path 'ece2cmor'
Submodule 'ece3-postproc' (https://eferre1:BQaqVfmhpxW-pAi2uqHN@ earth.bsc.es/gitlab/es/ece3-postproc.git) registered for path 'ece3-postproc'
Submodule 'es-esmvaltool' (https://earth.bsc.es/gitlab/es/es-esmvaltool.git) registered for path 'es-esmvaltool'
Submodule 'sources' (https://eferre1:BQaqVfmhpxW-pAi2uqHN@ earth.bsc.es/gitlab/svn/ecearth-mirror.git) registered for path 'sources'
Submodule 'test_cases' (https://earth.bsc.es/gitlab/es/auto-ecearth-conf-files.git) registered for path 'test_cases'
Submodule 'utils' (https://earth.bsc.es/gitlab/es/auto-ecearth-utils.git) registered for path 'utils'
Cloning into '/esarchive/autosubmit/t06a/proj/auto-ecearth3/ece2cmor'...
remote: Enumerating objects: 14192, done.        
remote: Counting objects: 100% (74/74), done.        
remote: Compressing objects: 100% (51/51), done.        
remote: Total 14192 (delta 40), reused 46 (delta 23), pack-reused 14118
Receiving objects: 100% (14192/14192), 177.77 MiB | 17.84 MiB/s, done.
Resolving deltas: 100% (10087/10087), done.
Cloning into '/esarchive/autosubmit/t06a/proj/auto-ecearth3/ece3-postproc'...
remote: Enumerating objects: 1725, done.        
remote: Total 1725 (delta 0), reused 0 (delta 0), pack-reused 1725        
Receiving objects: 100% (1725/1725), 2.38 MiB | 4.89 MiB/s, done.
Resolving deltas: 100% (1054/1054), done.
Cloning into '/esarchive/autosubmit/t06a/proj/auto-ecearth3/es-esmvaltool'...
remote: Enumerating objects: 3214, done.        
remote: Counting objects: 100% (464/464), done.        
remote: Compressing objects: 100% (260/260), done.        
remote: Total 3214 (delta 275), reused 374 (delta 202), pack-reused 2750
Receiving objects: 100% (3214/3214), 14.89 MiB | 11.84 MiB/s, done.
Resolving deltas: 100% (1967/1967), done.
Cloning into '/esarchive/autosubmit/t06a/proj/auto-ecearth3/sources'...
remote: Enumerating objects: 126955, done.        
remote: Counting objects: 100% (117/117), done.        
remote: Compressing objects: 100% (54/54), done.        
remote: Total 126955 (delta 70), reused 102 (delta 63), pack-reused 126838
Receiving objects: 100% (126955/126955), 789.11 MiB | 9.13 MiB/s, done.
Resolving deltas: 100% (82862/82862), done.
Cloning into '/esarchive/autosubmit/t06a/proj/auto-ecearth3/test_cases'...
remote: Enumerating objects: 8636, done.        
remote: Counting objects: 100% (2038/2038), done.        
remote: Compressing objects: 100% (649/649), done.        
remote: Total 8636 (delta 1233), reused 1582 (delta 848), pack-reused 6598        
Receiving objects: 100% (8636/8636), 968.17 KiB | 503.00 KiB/s, done.
Resolving deltas: 100% (5332/5332), done.
Cloning into '/esarchive/autosubmit/t06a/proj/auto-ecearth3/utils'...
remote: Enumerating objects: 376, done.        
remote: Total 376 (delta 0), reused 0 (delta 0), pack-reused 376        
Receiving objects: 100% (376/376), 56.80 KiB | 684.00 KiB/s, done.
Resolving deltas: 100% (196/196), done.
Submodule 'ece2cmor3/resources/cmip6-cmor-tables' (https://github.com/PCMDI/cmip6-cmor-tables.git) registered for path 'ece2cmor/ece2cmor3/resources/cmip6-cmor-tables'
Cloning into '/esarchive/autosubmit/t06a/proj/auto-ecearth3/ece2cmor/ece2cmor3/resources/cmip6-cmor-tables'...
remote: Enumerating objects: 5539, done.        
remote: Counting objects: 100% (426/426), done.        
remote: Compressing objects: 100% (213/213), done.        
remote: Total 5539 (delta 241), reused 314 (delta 193), pack-reused 5113        
Receiving objects: 100% (5539/5539), 4.90 MiB | 1004.00 KiB/s, done.
Resolving deltas: 100% (4462/4462), done.
Removing backup...
Project folder updated
```

</details>

<details><summary>Git status</summary>

```
eferre1@ bscearth358:/esarchive/autosubmit/t06a/proj/auto-ecearth3> git status
Not currently on any branch.
nothing to commit, working tree clean
```

</details>

Also, at the same time, I noticed that running the command modified the `expdef.conf` file and changed the branch and commit lines like this:

```diff
[git]
# Repository URL  STRING = 'https://github.com/torvalds/linux.git'
PROJECT_ORIGIN = https://earth.bsc.es/gitlab/es/auto-ecearth3.git
# Select branch or tag, STRING, default = 'master', help = {'master' (default), 'develop', 'v3.1b', ...}
- PROJECT_BRANCH = 3.3.3.2
+ PROJECT_BRANCH = HEAD

# type = STRING, default = leave empty, help = if model branch is a TAG leave empty
- PROJECT_COMMIT =
+ PROJECT_COMMIT = 947f9227af11c879cb96971ea413646d6f84e304
```

I don't know if this is the expected behaviour, since for example in this case it wouldn't change anything since the branch is a TAG and it is the same as the commit, but for some other case it could make copying the experiment to not have the correct `proj` due to downloading the commit instead of the updated branch. I think that the `autosubmit clean` is meant to be used to leave the `conf` files to be able to be use the `expid` as an origin for a copy and clean the `proj` and `plots` folders to save space.

@mcastril

**Comment by kinow** [comment]
In GitLab by @eferre1 on Jun 21, 2022, 16:41

It returns it empty:

```
eferre1@ bscearth358:/esarchive/autosubmit/t06a/proj/auto-ecearth3> git diff-index HEAD --
eferre1@ bscearth358:/esarchive/autosubmit/t06a/proj/auto-ecearth3> echo $?
0
```

But at the same time, since it is in detached mode after the refresh, it says that is not in any branch when running a `git status`, so that might be causing conflict somewhere?

> Actually, the idea is that the experiment can be reproduced later, and for that reason, I think it's better to have a commit id, which cannot change as the tag can.

Then I think it might be better to leave it this way with the change to the commit, since this is an exceptional case and I can easily solve it within the script that I have to run the clean too (its just a for with the expids and runs the `autosubmit clean` command, I can add a `sed` after it to reset the branch and remove the commit for the release experiments)

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 23, 2022, 11:23

We need to know why it is in a detached state when cloning a tag. @eferre1 do you know if it's always like that when you clone a tag?

**Comment by kinow** [comment]
In GitLab by @eferre1 on Jun 23, 2022, 11:40

I've done a few tests cloning out other tags, and it seems that it is always the case.

So, I guess that the way of thinking about it is that if you check out a branch, it is supposedly because you are going to develop it, but if you check out a tag, it is because you need it to be an exact copy without modifications and if you modify anything you will have to check where that needs to be pushed.

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 28, 2022, 17:12

> So, I guess that the way of thinking about it is that if you check out a branch, it is supposedly because you are going to develop it, but if you check out a tag, it is because you need it to be an exact copy without modifications and if you modify anything you will have to check where that needs to be pushed.

Yes, it makes sense. But it makes harder to `clean` experiments as most users clone a tag, at least in Auto-EC-Earth.

**Comment by kinow** [comment]
In GitLab by @eferre1 on Jul 26, 2022, 09:37

Looking again into this, and also taking into account that any non-development experiment could (and probably should) be using the `fetch-single branch` functionality to speed up the cloning process:

```
eferre1@ bscearth358:/esarchive/autosubmit/t06a/proj/auto-ecearth3> git diff-index HEAD --
eferre1@ bscearth358:/esarchive/autosubmit/t06a/proj/auto-ecearth3> echo $?
0
eferre1@ bscearth358:/esarchive/autosubmit/t06a/proj/auto-ecearth3> git status
Not currently on any branch.
nothing to commit, working tree clean
eferre1@ bscearth358:/esarchive/autosubmit/t06a/proj/auto-ecearth3> git branch --list
* (no branch)
```

This was after a refresh on an experiment of the release (so it cloned a tag), and as you can see, no differences are found, it is in detached mode but also it doesn't have any branch tracked on the local repository, so right now I'm not sure how this could be checked without a lot of complex conditions to be sure that it will work.

**Comment by kinow** [comment]
In GitLab by @mcastril on Jul 27, 2022, 19:17

Do you think that it is because of the `fetch-single branch` or should it happen always that you clone a tag?

**Comment by kinow** [comment]
In GitLab by @eferre1 on Jul 28, 2022, 09:52

> Do you think that it is because of the `fetch-single branch` or should it happen always that you clone a tag?

If you refer to the not seeing all the branches, then yes, it is because of that option, if you refer to being on detached mode, then it shouldn't affect using the `fetch-single branch`, only the fact that you are cloning a tag. Here is the result of the same commands when no using the `fetch-single branch` but cloning a tag (I was missing a `-ar` parameter on the command to show all branches tracked, but the results are the same).

- On the same experiment as above:
```
eferre1@ bscearth358:/esarchive/autosubmit/t06a/proj/auto-ecearth3> git branch --list -ar
eferre1@ bscearth358:/esarchive/autosubmit/t06a/proj/auto-ecearth3>
```
- On a cloned tag but no `fetch-single branch`:
```
eferre1@ bscearth358:/esarchive/autosubmit/a3vr/proj/auto-ecearth3> git diff-index HEAD --
eferre1@ bscearth358:/esarchive/autosubmit/a3vr/proj/auto-ecearth3> echo $?
0
eferre1@ bscearth358:/esarchive/autosubmit/a3vr/proj/auto-ecearth3> git status
Not currently on any branch.
nothing to commit, working tree clean
eferre1@ bscearth358:/esarchive/autosubmit/a3vr/proj/auto-ecearth3> git branch --list
* (no branch)
eferre1@ bscearth358:/esarchive/autosubmit/a3vr/proj/auto-ecearth3> git branch --list -ar
  origin/1017-development-CLEAN-templates-refactory
  origin/1026-develop_cmor_pow9
  (···)
  origin/v3.1f_SST_restoring
eferre1@ bscearth358:/esarchive/autosubmit/a3vr/proj/auto-ecearth3> 
```

As you can see, with the `git branch --list -ar` it shows all the branches tracked (local and remote) when not using the `fetch-single branch` option, but it is still in detached mode, and even doing a `git checkout` will keep it in detached mode if it is a tag (it detects that you checked out the tag, but keeps detached from it since you cannot push changes into a tag):

```
eferre1@ bscearth358:/esarchive/autosubmit/a3vr/proj/auto-ecearth3> git checkout 3.3.3.2
HEAD is now at 947f9227... [3.3.3.2] Update last changes in test_cases for 3.3.3.2 release
eferre1@ bscearth358:/esarchive/autosubmit/a3vr/proj/auto-ecearth3> git status
HEAD detached at 3.3.3.2
nothing to commit, working tree clean
```

**Comment by kinow** [comment]
In GitLab by @mcastril on Jul 29, 2022, 19:20

Thanks, @eferre1 

We know then that cloning a tag is a problem for checking differences.

About `fetch-single branch`, it seems that the examples above were from release experiments, so they already have the mentioned problem.

What happens if you clone a branch with `fetch-single branch`? Any difference with respect to not using it?

**Comment by kinow** [comment]
In GitLab by @eferre1 on Aug 9, 2022, 10:45

Here you can see the results with the parameter active or not, in 2 experiments using trunk. The difference is only that the `git branch --list -ar` can see all the branches in on case while in the other only sees the used branch (and the remote reference of that branch).

- Experiment with `fetch-single branch` set to true:

```
eferre1@ bscearth358:/esarchive/autosubmit/t0n2/proj/auto-ecearth3> git diff-index HEAD --
eferre1@ bscearth358:/esarchive/autosubmit/t0n2/proj/auto-ecearth3> echo $?
0
eferre1@ bscearth358:/esarchive/autosubmit/t0n2/proj/auto-ecearth3> git status
On branch trunk
Your branch is up-to-date with 'origin/trunk'.
nothing to commit, working tree clean
eferre1@ bscearth358:/esarchive/autosubmit/t0n2/proj/auto-ecearth3> git branch --list
* trunk
eferre1@ bscearth358:/esarchive/autosubmit/t0n2/proj/auto-ecearth3> git branch --list -ar
  origin/HEAD -> origin/trunk
  origin/trunk
```

- Experiment with `fetch-single branch` set to false:

```
eferre1@ bscearth358:/esarchive/autosubmit/t0n3/proj/auto-ecearth3> git diff-index HEAD --
eferre1@ bscearth358:/esarchive/autosubmit/t0n3/proj/auto-ecearth3> echo $?
0
eferre1@ bscearth358:/esarchive/autosubmit/t0n3/proj/auto-ecearth3> git status
On branch trunk
Your branch is up-to-date with 'origin/trunk'.
nothing to commit, working tree clean
eferre1@ bscearth358:/esarchive/autosubmit/t0n3/proj/auto-ecearth3> git branch --list
* trunk
eferre1@ bscearth358:/esarchive/autosubmit/t0n3/proj/auto-ecearth3> git branch --list -ar
  origin/1017-development-CLEAN-templates-refactory
  origin/1026-develop_cmor_pow9
  ···
```

I don't know if a branch can have the same name as a tag and what happens (which one is used) in that case, but anyways, maybe an option would be to create the `_production` branch at the same time that we do a release and have the users set directly the branch and it would help with this cleaning (but then we would have the releases tagged only to have the info of the commits, etc on the release, but not be used).

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 9, 2022, 13:23

Thank you for the tests @eferre1.

As this [thread](https://stackoverflow.com/questions/5582208/checking-out-git-tag-leads-to-detached-head-state) explains, committing a TAG being attached to a BRANCH is not incompatible.

We could then always create the TAG after having branched the production from the master. The issue is then explaining Autosubmit which branch it should stick to. 

On the other hand, if all reference experiments point to the branch instead of the tag, few users will use a tag. Anyway, it would be good to have a fix. 

Maybe in Autosubmit4 tags should be declared in `PROJECT_COMMIT`, leaving the possibility to also fill `PROJECT_BRANCH`...

**Comment by kinow** [comment]
In GitLab by @eferre1 on Aug 9, 2022, 14:23

> On the other hand, if all reference experiments point to the branch instead of the tag, few users will use a tag. The issue is then explaining Autosubmit which branch it should stick to.

Well, I think that in this case, we could just create the `version_production` branch when doing the release (without waiting to update any bugfix in that release like we do now) and then tell the users to directly set the production branch to be used. That would mean that it is cloning a branch always, avoiding any issue with the `autosubmit clean` but also, as you say, nobody would be using the TAG (even though at first and until any bugfix makes it into the production branch, this would be pointing to the same commit that the TAG and be the same as using the TAG in practical terms).

> The issue is then explaining Autosubmit which branch it should stick to.

If we follow this procedure of creating the branch at the same time than the TAG, it would be enough to set the `PROJECT_BRANCH = version_production` in the `expdef.conf` so AS would always clone the production branch.

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 9, 2022, 14:59

Yes, for Auto-EC-Earth, it can work pretty well however some other Auto-Models do not use production branches and we need a more general solution. But we can wait for AS4.

**Comment by kinow** [comment]
In GitLab by @eferre1 on Aug 9, 2022, 15:18

Ok, right, for any other auto-model not using production branches it could only work if when there is a TAG and a branch with the same name (and defining that name in the `expdef.conf` in the `PROJECT_BRANCH`), AS uses the branch when running the `create` and `refresh` commands, but it is true that it would depend of how AS interprets it and could cause problems.

**Comment by kinow** [comment]
In GitLab by @gmontanepinto on Jul 11, 2023, 12:59

As we commented offline with @dbeltrankyl, I was trying to archive some auto-ecearth experiments but I was thrown an error that could be related to this issue:

```
Changes not committed detected... SKIPPING!
[ERROR] Trace: 'AutosubmitCritical' object has no attribute 'messagee'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.14.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.14.0-py2.7.egg/EGG-INFO/scripts/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/shared/earth/software/autosubmit/3.14.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.14.0-py2.7.egg/autosubmit/autosubmit.py", line 660, in parse_args
    return Autosubmit.archive(args.expid, noclean=args.noclean, uncompress=args.uncompress)
  File "/shared/earth/software/autosubmit/3.14.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.14.0-py2.7.egg/autosubmit/autosubmit.py", line 4033, in archive
    if version is not None and version.startswith('3') and not Autosubmit.clean(expid, True, True, True):
  File "/shared/earth/software/autosubmit/3.14.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.14.0-py2.7.egg/autosubmit/autosubmit.py", line 2659, in clean
    raise AutosubmitCritical("Couldn't clean this experiment, check if you have the correct permisions",7012,e.messagee)
AttributeError: 'AutosubmitCritical' object has no attribute 'messagee'
 [CRITICAL] None'AutosubmitCritical' object has no attribute 'messagee'
Unhandled error: If you see this message, please report it in Autosubmit's GitLab project
```

Apart from a typo in the code (`messagee`), it seems that Autosubmit is detecting some non-committed changes but this is not true. The problem I think is that the experiments are pointing to a branch that doesn't exist anymore (`3.3.3.1_developments`). 

This has happened first with t0j7 using 3.14, but for some reason switching to 3.15 solved the problem. Tried also with t0j6 and t0j8 but in this case none of the both versions are working.

**Comment by dbeltrankyl** [comment]
Summary of this issue is that you can't clean an experiment if there is an uncommitted commit
