### ISSUE TITLE
Saga issue object lease

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#84]
In GitLab by @kserradell on Jan 8, 2016, 14:52

When running a03i with AS 3.2.0b2,

```
(virtualenv)[kserrade@ bscearth307 ~ ]$ autosubmit recovery -all -s a03i 
Recovering experiment a03i

Checking configuration files...
autosubmit_a03i.conf OK
platforms_a03i.conf OK
jobs_a03i.conf OK
expdef_a03i.conf  OK
Configuration files OK

Looking for COMPLETED files
CHANGED job 'a03i_FIX' status to COMPLETED
CHANGED job 'a03i_20140326_reg_1_VAR' status to COMPLETED
CHANGED job 'a03i_20140326_reg_2_VAR' status to WAITING
CHANGED job 'a03i_20140326_reg_3_VAR' status to WAITING
CHANGED job 'a03i_20140326_reg_4_VAR' status to WAITING
CHANGED job 'a03i_20140326_reg_5_VAR' status to WAITING
CHANGED job 'a03i_20140326_reg_6_VAR' status to WAITING
CHANGED job 'a03i_20140326_reg_7_VAR' status to WAITING
CHANGED job 'a03i_20140326_reg_8_VAR' status to WAITING
CHANGED job 'a03i_20140326_reg_9_VAR' status to WAITING
CHANGED job 'a03i_20140326_reg_10_VAR' status to WAITING
CHANGED job 'a03i_20140326_reg_11_VAR' status to WAITING
[CRITICAL] Unhandled exception on Autosubmit: LeaseObject is already leased: <radical.utils.lease_manager._LeaseObject object at 0x7fc929215790>
Traceback (most recent call last):
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/autosubmit/autosubmit.py", line 290, in parse_args
    return Autosubmit.recovery(args.expid, args.save, args.all, args.hide)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/autosubmit/autosubmit.py", line 838, in recovery
    if job.get_platform().get_completed_files(job.name):
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/autosubmit/platforms/platform.py", line 182, in get_completed_files
    return self.get_file('{0}_COMPLETED'.format(job_name), False)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/autosubmit/platforms/platform.py", line 151, in get_file
    filename)))
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/saga/filesystem/file.py", line 86, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/saga/namespace/entry.py", line 89, in __init__
    url, flags, session, ttype=_ttype)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 1008, in init_instance
    self.shell = self.lm.lease (lease_tgt, self.shell_creator, self.url)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/radical/utils/lease_manager.py", line 362, in lease
    obj.lease ()
RuntimeError: LeaseObject is already leased: <radical.utils.lease_manager._LeaseObject object at 0x7fc929215790>
```

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jan 14, 2016, 10:35

Status changed to closed by commit dd7604e362e3639c8a21638d1ce210f78e559bfd
