### ISSUE TITLE
local variable 'platform' referenced before assignment

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#859]
In GitLab by @mcastril on Aug 17, 2022, 11:15

Hi @dbeltrankyl 

@molidg reported a problem this morning when using AS 3.14.0b

```
Exception in thread JOB_a52i_20220817_1_1_GET_HERMES_INPUTS:
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/shared/earth/software/autosubmit/3.14.0b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.14.0b0-py2.7.egg/autosubmit/job/job.py", line 658, in retrieve_logfiles
    out_exist = platform.check_file_exists(
UnboundLocalError: local variable 'platform' referenced before assignment
```

I assume that it's an issue with the platform. Nevertheless, I wanted to be sure, and looking into the code, I think that the situation could be better covered with an Exception.

```python
            platform = submitter.platforms[platform_name.lower()]
            try:
                platform.test_connection()
            except:
                pass
            max_logs = int(as_conf.get_retrials()) - fail_count
            last_log = int(as_conf.get_retrials()) - fail_count
```

I hypothesize that this try-except would capture the problem if the exception was propagated upwards. Maybe the `pass` is inhibiting the behavior.

Could you review it @dbeltrankyl ?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 29, 2022, 08:41

(This only affects to the log recovery, )

This try: except is not meant to be there because it was added while debugging that part. However, it shouldn't affect that error because the platform is assigned out of that try/except block. Also, in case

And in the previous block, there is another try except that should be triggered, I think the issue is that Exception instead of BaseException, will change it.

In any case, the log wouldn't be recovered due to some issue while loading the as_conf for that thread, the only difference would be the message sent to the console, maybe there were issues in esarchive

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 29, 2022, 13:51

I've divided this try, except into two different blocks and added a second retrial to gather the platform info. 

This step is very rare that fails ( in fact is the first time I see it happen). I put only one additional retrial of 5 min since this doesn't affect the overall performance of autosubmit. However, I'm not sure that the retrial would be useful since the only element that can affect this step is the esarchive and is unlikely that it would be fixed soon enough.

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 30, 2022, 11:18

> This try: except is not meant to be there because it was added while debugging that part. However, it shouldn't affect that error because the platform is assigned out of that try/except block. Also, in case

The platform is assigned out of block, but if the user is not using wrappers the platform is only used inside the try/catch block. So, I thought that if that `platform` had an unexpected value, it should at least crash there. But it's true that the error that is `undefined`.

> In any case, the log wouldn't be recovered due to some issue while loading the as_conf for that thread, the only difference would be the message sent to the console, maybe there were issues in esarchive

The main difference is that it should give a warning instead of crashing (I think it was crashing), if it's not anything critical.

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 30, 2022, 11:27

> However, I'm not sure that the retrial would be useful since the only element that can affect this step is the esarchive and is unlikely that it would be fixed soon enough.

I think that the error was due to a very short interruption (/esarchive was out for 10 minutes a couple of times last week)

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 30, 2022, 11:36

Sorry because I am losing the context. If this is inside a thread, I would just kill the thread, but I think it's not the situation.

If the problem is in the critical path, why not entering in a loop of retrials like with some other issues (networking, etc)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 30, 2022, 11:37

It was inside a thread `Exception in thread JOB_a52i_20220817_1_1_GET_HERMES_INPUTS:` 

It shouldn't crash the main loop, only the thread that recover the logs

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 31, 2022, 10:26

Thank you @dbeltrankyl. Can you add the commit to the issue for reference whenever something gets fixed by a bugfix? It will be helpful to have a better trace.
