### ISSUE TITLE
File exists! New experiment with 3.2.0b3 fails when trying to create REMOTE_LOG_DIR

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#86]
In GitLab by @dmanubens on Jan 12, 2016, 17:46

```
16 of 16 jobs remaining (17:42)
Job a03m_LOCAL_SETUP is COMPLETED

Jobs ready for marenostrum3: 1
Jobs to submit: 1
[CRITICAL] Unhandled exception on Autosubmit: not enough arguments for format string
Traceback (most recent call last):
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/autosubmit/autosubmit.py", line 278, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/autosubmit/autosubmit.py", line 599, in run_experiment
    Autosubmit.submit_ready_jobs(as_conf, joblist, platforms_to_test)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/autosubmit/autosubmit.py", line 640, in submit_ready_jobs
    platform.send_file(scriptname)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/autosubmit/platforms/platform.py", line 111, in send_file
    workdir = self.get_workdir(self.get_files_path())
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/autosubmit/platforms/platform.py", line 128, in get_workdir
    parent = self.get_workdir(os.path.dirname(path))
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/autosubmit/platforms/platform.py", line 129, in get_workdir
    parent.make_dir(new_directory)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/saga/namespace/directory.py", line 197, in make_dir
    return self._adaptor.make_dir (surl.Url (tgt), flags, ttype=ttype)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/esnas/autosubmit/virtualenv/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 767, in make_dir
    raise saga.NoSuccess ("make_dir (%s) failed: %s" % tgt_in, out)
TypeError: not enough arguments for format string
```

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jan 13, 2016, 10:38

Title changed from **New experiment with 3.2.0b3 fails when trying to create REMOTE_LOG_DIR** to **File exists! New experiment with 3.2.0b3 fails when trying to create REMOTE_LOG_DIR**
