### ISSUE TITLE
[autosubmit 4] autosubmit configure fails on python:3 container

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#866]
Hello :wave: 

I'm having a few issues with the branch 4.0-branch-2022, but I am not sure if these are issues due to ongoing revamp of the project, or if it's something with my operating system/libraries/environment.

Today I decided to use a blank `python:3` Docker container to test, which is convenient as it brings git too. It contains Python 3.10.7 at the moment, and these are commands that I used, and the traceback I'm getting:

```bash
$ docker pull python:3
$ docker run --rm -ti python:3 /bin/bash
root@bd6d4d08961b:/ git clone https://earth.bsc.es/gitlab/es/autosubmit.git
root@bd6d4d08961b:/ cd autosubmit/
root@bd6d4d08961b:/ git checkout 4.0-branch-2022
root@bd6d4d08961b:/ pip install -e .
root@bd6d4d08961b:/ autosubmit configure
root@bd6d4d08961b:/autosubmit# autosubmit configure
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/bin/autosubmit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/autosubmit/bin/autosubmit", line 34, in <module>
    from autosubmit.autosubmit import Autosubmit
  File "/autosubmit/autosubmit/autosubmit.py", line 42, in <module>
    from .monitor.monitor import Monitor
  File "/autosubmit/autosubmit/monitor/monitor.py", line 42, in <module>
    from .diagram import create_bar_diagram
  File "/autosubmit/autosubmit/monitor/diagram.py", line 22, in <module>
    import matplotlib as mtp
  File "/usr/local/lib/python3.10/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "/usr/local/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 26, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/usr/local/lib/python3.10/site-packages/matplotlib/colors.py", line 82, in <module>
    from matplotlib import _api, cbook, scale
  File "/usr/local/lib/python3.10/site-packages/matplotlib/scale.py", line 18, in <module>
    from matplotlib.ticker import (
  File "/usr/local/lib/python3.10/site-packages/matplotlib/ticker.py", line 179, in <module>
    from matplotlib import transforms as mtransforms
  File "/usr/local/lib/python3.10/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import
```

I noticed there's a `requirements.txt` file too, so I tried using that instead. Then, instead of `numpy`, it's failing due to the `packaging` module :thinking: 

```
root@bd6d4d08961b:/autosubmit# pip install -r requirements.txt
root@bd6d4d08961b:/autosubmit# autosubmit configure
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (packaging 19.0 (/usr/local/lib/python3.10/site-packages), Requirement.parse('packaging>19'), {'autosubmit'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/autosubmit", line 4, in <module>
    __import__('pkg_resources').require('autosubmit==4.0.0b0')
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'packaging>19' distribution was not found and is required by autosubmit
```

I think some days ago I simply forced a dependency to be updated (packaging I think?) in order to get it to build on my environment, but still had other issues. I will try to replicate these other issues over the next days as I continue to set up a AS 4 environment to play.

Thanks!
-Bruno

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 19, 2022, 11:11

First welcome to our team!

The current python version is v3.7.3 and is the only one available on the bsc office so we're forced to use it.  Perhaps you could try that one.

Currently, there are some issues with AS4 regarding the dependencies ( that were fully reworked and I'm polishing the final details), however, the installation should work fine.

**Comment by kinow** [comment]
>First welcome to our team!

Thank you @dbeltrankyl ! :tada: 

>The current python version is v3.7.3 and is the only one available on the bsc office so we're forced to use it. Perhaps you could try that one.

I replaced `python:3` by `python:3.7.3`, then ran `pip install -U pip` (as bcrypt failed to install) and `pip install -e .`.

Now `autosubmit configure` worked with no issues. Closing this issue as 3.7.3 works fine. Thanks @dbeltrankyl !

**Comment by kinow** [comment]
Happy to help with the documentation in the future if needed. Being a beginner at Autosubmit I should be able to test basic features and commands, and give an unbiased feedback on the docs 😃👍
