### ISSUE TITLE
Set status failing several times, but then worked again:

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#88]
In GitLab by @obellprat on Jan 18, 2016, 12:40

I got the following error e few times when using "setstatus". After closing different terminals and other programs the command worked again. Error stored here for documentation in case of future encounters:

autosubmit setstatus a032 -t READY -fs FAILED -s
Traceback (most recent call last):
  File "/shared/earth/software/bin/autosubmit", line 29, in <module>
    from autosubmit.autosubmit import Autosubmit
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 56, in <module>
    from config.config_common import AutosubmitConfig
  File "/shared/earth/python2.7/autosubmit/config/config_common.py", line 34, in <module>
    from autosubmit.platforms.psplatform import PsPlatform
  File "/shared/earth/python2.7/autosubmit/platforms/psplatform.py", line 23, in <module>
    from autosubmit.platforms.hpcplatform import HPCPlatform
  File "/shared/earth/python2.7/autosubmit/platforms/hpcplatform.py", line 22, in <module>
    import paramiko
  File "build/bdist.linux-x86_64/egg/paramiko/__init__.py", line 30, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 66, in <module>
  File "/shared/earth/python2.7/Crypto/Cipher/ARC4.py", line 66, in <module>
    from Crypto.Cipher import _ARC4
ImportError: /shared/earth/python2.7/Crypto/Cipher/_ARC4.so: undefined symbol: PyUnicodeUCS4_FromStrin

**Comment by kinow** [comment]
In GitLab by @jvegreg on Feb 15, 2016, 11:11

It is the same error that has been discussed on #90.
