### ISSUE TITLE
Python modules: incompatibility of autosubmit with other software

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#90]
In GitLab by @fmassonn on Jan 21, 2016, 14:17

Hello,

I'm having a problem that I'm fixing manually for now, but Valentina @vsicardi has the same so we thought to open a ticket.

Autosubmit cannot run with the "Python" module loaded:

fmassonn@ bscearth321:~$ module purge; module load Python; autosubmit
Traceback (most recent call last):
  File "/shared/earth/software/bin/autosubmit", line 29, in <module>
    from autosubmit.autosubmit import Autosubmit
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 56, in <module>
    from config.config_common import AutosubmitConfig
  File "/shared/earth/python2.7/autosubmit/config/config_common.py", line 34, in <module>
    from autosubmit.platforms.psplatform import PsPlatform
  File "/shared/earth/python2.7/autosubmit/platforms/psplatform.py", line 23, in <module>
    from autosubmit.platforms.hpcplatform import HPCPlatform
  File "/shared/earth/python2.7/autosubmit/platforms/hpcplatform.py", line 22, in <module>
    import paramiko
  File "build/bdist.linux-x86_64/egg/paramiko/__init__.py", line 30, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 66, in <module>
  File "/shared/earth/python2.7/Crypto/Cipher/ARC4.py", line 66, in <module>
    from Crypto.Cipher import _ARC4
ImportError: /shared/earth/python2.7/Crypto/Cipher/_ARC4.so: undefined symbol: PyUnicodeUCS4_FromString

--------------------------------

fmassonn@ bscearth321:~$ module purge; autosubmit
usage: autosubmit [-h] [-v]
                  [-lf {EVERYTHING,DEBUG,INFO,RESULT,USER_WARNING,WARNING,ERROR,CRITICAL,NO_LOG}]
                  [-lc {EVERYTHING,DEBUG,INFO,RESULT,USER_WARNING,WARNING,ERROR,CRITICAL,NO_LOG}]
                  
                  {unarchive,expid,stats,monitor,changelog,archive,recovery,create,refresh,setstatus,readme,install,clean,test,run,configure,check,delete}
                  ...
autosubmit: error: too few arguments

------------------------------

On the other hand, some softwares like iPython do need the Python module to e.g. load NetCDFs.

My current option is to manually load Python when I'm running iPython but that's not a good fix. I could also think to create a fake autosubmit binary file that unloads Python module before calling autosubmit, but that's again not a long-term solution, especially if iPython and autosubmit have to be used consecutively. In any case, we don't want this error to pop up again when new staff comes here: they won't know how to solve it unless they talk to the ones that know the problem.

Any idea how to fix this @dmanubens  ? Thanks in advance.

François

People interested: @ cprodhomme @vsicardi

**Comment by kinow** [comment]
In GitLab by @dmanubens on Jan 21, 2016, 14:54

If there is an incompatibility with the Python module in the ES workstations I would go for creating an Autosubmit module. @omula @kserradell how do you see it ?

**Comment by kinow** [comment]
In GitLab by @jvegreg on Jan 22, 2016, 09:52

This is related to PyCrypto, which its used by Paramiko.This library will not longer be used from 3.2 onwards. Maybe we can release 3.2 and see what happens

**Comment by kinow** [comment]
In GitLab by @jvegreg on Jan 22, 2016, 09:57

It is a problem related to different Unicode settings on the python runtime and pycrypto library.

http://stackoverflow.com/questions/31644056/is-python-2-7-wide-build-usc4-not-compatible-with-certain-libraries

http://effbot.org/pyfaq/when-importing-module-x-why-do-i-get-undefined-symbol-pyunicodeucs2.htm

**Comment by kinow** [comment]
In GitLab by @jvegreg on Jan 25, 2016, 09:22

@omula recompiled the python interpreter used by the Python module with USC4 and apparently solves the problem. We are testing it just to be sure that this change doesn't break anything

**Comment by kinow** [comment]
In GitLab by @vsicardi on Jan 29, 2016, 15:11

Hi,
would you, please, suggest me what should I do in order to avoid this problem? I have to do "
module unload Python" every time I launch an autosubmit command in a new terminal tab. It's not a big deal, but still if it was possible to avoid it, I would really appreciate.
Thank you

**Comment by kinow** [comment]
In GitLab by @jvegreg on Feb 15, 2016, 10:47

Please, use module load autosubmit in the meantime.
