### ISSUE TITLE
Error with pickle

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#91]
In GitLab by @fmassonn on Jan 29, 2016, 15:30

I'm trying to make an autosubmit (3.1.9) setstatus, and get the following error

fmassonn@ bscearth321:~/NEMO_EOF/data$ autosubmit setstatus -s -t READY -fl "a02x_19790101_fc0_152_SIM" a02x
[CRITICAL] Unhandled exception on Autosubmit: 
Traceback (most recent call last):
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 282, in parse_args
    args.filter_chunks, args.filter_status, args.filter_type)
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 1385, in set_status
    ".pkl"), 'r'))
  File "/usr/lib64/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib64/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib64/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError

Note that an autosubmit -h works

**Comment by kinow** [comment]
In GitLab by @fmassonn on Jan 29, 2016, 15:49

The error seems to happen when the PKL file has been previously corrupted, for instance if two autosubmit instances were running at the same time

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 4, 2018, 11:43

In the code, there is a .lock mechanism that denies two or more instances of autosubmit running in the same experiment at the same time. So the PKL file should not corrupt anymore. 

I will close this issue, if there is any problem related to this I can reopen this again.
