### ISSUE TITLE
Folder in scratch does not follow the pattern %SCRATCH_DIR%/%CURRENT_PROJ% in Juwels

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#912]
In GitLab by @mandresm on Dec 9, 2022, 16:42

**Reported in**: mattermost/MPI-M/Autosubmit-support

**Tag**: `v4.0.0b`

Hi all,

In Juwels, the folders associated to the projects (accounts) do not match the project name. For example, the account I use in Juwels is `hhb19` for `#SBATCH -A`, however, the project's scratch is `/p/scratch/chhb` (an extra **c** to the project's name).

This creates the following problem when one sets `PROJECT: chhb19` in the platform file:
```
ERROR] Trace: sbatch: error: batch job submission failed: invalid account or account/partition combination specified
```

And the following problem if one sets it to `hhb19` (because it's unable to create this file `/p/scratch/hhb19/andres-martinez1/permission_checker_azxbyc` when checking the connection due to the missing **c**):
```
Scripts OK
Autosubmit is running with v4.0.0
Checking the connection to all platforms in use
[local] Correct user privileges for host localhost
[local] Connection successful to host localhost
Traceback (most recent call last):
  File "/home/ollie/mandresm/utilities/autosubmit/autosubmit/autosubmit.py", line 1858, in run_experiment
    Autosubmit.restore_platforms(platforms_to_test)
  File "/home/ollie/mandresm/utilities/autosubmit/autosubmit/autosubmit.py", line 2253, in restore_platforms
    "Issues while checking the connectivity of platforms.", 7010, issues + "\n" + ssh_config_issues)
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ollie/mandresm/utilities/autosubmit/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/ollie/mandresm/utilities/autosubmit/autosubmit/autosubmit.py", line 630, in parse_args
    args.start_after, args.run_members)
  File "/home/ollie/mandresm/utilities/autosubmit/autosubmit/autosubmit.py", line 2202, in run_experiment
    raise AutosubmitCritical(e.message, e.code, e.trace)
log.log.AutosubmitCritical:  
[ERROR] None
[ERROR] Trace: 
[JUWELS] has configuration issues.
 Check that the connection is passwd-less.(ssh andres-martinez1@juwels-cluster)
 Check the parameters that build the root_path are correct:{scratch_dir/project/user} = {/p/scratch//hhb19/andres-martinez1}

 [CRITICAL] Issues while checking the connectivity of platforms. [eCode=7010]
```

Is all this a real problem, or is there an option that allows to overcome it already?

I have overcome the problem and managed to get the full vanilla workflow working by adding a new variable in the platform file named `SCRATCH_PROJECT_DIR: chhb19` while `PROJECT: hhb19`. I also created a new property in the platform object: `platform.project_dir` which takes values of `SCRATCH_PROJECT_DIR` if it exists and of `PROJECT` if it doesn't. Then I use this variable everywhere where `platform.project` was used for the project directory in scratch.

I have tried to push my branch to do a PR in case it's useful for the more generalized solution you  might want to produced, but I don't think I have the permissions.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 12, 2022, 09:37

Hello,

Sorry for the delay, I was on holiday last week, will check this later today but I think that there is no way of changing the structure, so far, all HPC followed this structure.

> I have overcome the problem and managed to get the full vanilla workflow working by adding a new variable in the platform file named `SCRATCH_PROJECT_DIR: chhb19` while `PROJECT: hhb19`. I also created a new property in the platform object: `platform.project_dir` which takes values of `SCRATCH_PROJECT_DIR` if it exists and of `PROJECT` if it doesn't. Then I use this variable everywhere where `platform.project` was used for the project directory in scratch.

I think this should be the solution. I'll add it. 

About the permissions, I can't give them maybe @mcastril can, but he was also on holiday and today is on work travel so I don't know when he will answer

**Comment by kinow** [comment]
In GitLab by @mandresm on Dec 12, 2022, 13:56

Thanks @dbeltrankyl I'll pull-request later today once I can push the branch. I could also fork and pull-request from the fork if that's the preferred way.

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 12, 2022, 19:35

Thanks for reporting the issue and proposing the solution @mandresm! With @Lerriola, we had the same problem with Levante, but we decided to do the tests in the `work` partition (that follows the structure expected by Autosubmit) while we had a better solution for this. 

Your fix looks also good for me. I promoted you to Reporter, please tell me if that doesn't work for you.

**Comment by kinow** [comment]
In GitLab by @mandresm on Dec 12, 2022, 22:42

I'm afraid I still cannot push a new branch into the project:
```
git push --set-upstream origin fix/proj_dir_in_scratch
remote: You are not allowed to push code to this project.
fatal: unable to access 'https://earth.bsc.es/gitlab/es/autosubmit.git/': The requested URL returned error: 403
```

**Comment by kinow** [comment]
In GitLab by @mandresm on Dec 15, 2022, 14:06

it worked, thanks :)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 21, 2022, 14:15

mentioned in commit 1f75aff9f8839a41bb44ccc4a1c6b5016a62f5c6
