### ISSUE TITLE
Documentation: Add error codes in the Installation procedure and block other commands

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#913]
In GitLab by @dbeltrankyl on Dec 14, 2022, 11:20

Ensure that Autosubmit configuration and installation are present before running any of the other Autosubmit commands.

What do these commands:

* Installation creates the main autosubmit db
* Configure creates the autosubmitrc

Todo: 

* [x] Add in init_log function to check if autosubmitrc and the main db exist.
* [x] Add in the installation command a function to check that autosubmitrc exists. 
* [x] Add error code in https://autosubmit.readthedocs.io/en/4.0-branch-2022/troubleshooting/error-codes.html and in the methods commented

Related to https://earth.bsc.es/gitlab/digital-twins/de_340/project_management/-/issues/216

**Comment by kinow** [comment]
mentioned in issue digital-twins/de_340/project_management#216

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 15, 2022, 09:58

marked the checklist item **Add in init_log function to check if autosubmitrc and the main db exist.** as completed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 15, 2022, 09:58

marked the checklist item **Add in the installation command a function to check that autosubmitrc exists.** as completed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 15, 2022, 09:58

marked the checklist item **Add in the installation command a function to check that autosubmitrc exists.** as incomplete

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 15, 2022, 09:58

marked the checklist item **Add error code in https://autosubmit.readthedocs.io/en/4.0-branch-2022/troubleshooting/error-codes.html and in the methods commented** as completed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 15, 2022, 10:12

mentioned in commit fb0bd1c91220ed2f342714c848b38df6329350fa

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 15, 2022, 10:12

marked the checklist item **Add in the installation command a function to check that autosubmitrc exists.** as completed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 15, 2022, 10:13

I've already uploaded the changes to 4.0 branch. I think all is addressed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 15, 2022, 10:19

nvm, I missed this one 

* [x] Check experiment database (R/W) and autosubmitrc (R) permissions before run autosubmit

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 15, 2022, 10:32

mentioned in commit e7f4e8c3e199b8c5b85c93fa6e2797df15b41ab2

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 15, 2022, 10:32

mentioned in commit b83b4a7050936920267d091b64a5b94a1f45d6a7

**Comment by kinow** [comment]
Error codes looking good! 

>nvm, I missed this one

Is this one ready now?

I synced my branch, checked out `master`, renamed my `.autosubmitrc` and tested asking autosubmit to monitor an experiment, and I believe it recognized the missing file and raised an error correctly.

```bash
(venv) kinow@ranma:~/Development/python/workspace/autosubmit$ autosubmit monitor a000
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/autosubmit/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 626, in parse_args
    Autosubmit._init_logs(args, args.logconsole, args.logfile, expid)
  File "/home/kinow/Development/python/workspace/autosubmit/autosubmit/autosubmit.py", line 720, in _init_logs
    raise AutosubmitCritical('No configuration file(autosubmitrc) found in this filesystem. Please run "autosubmit configure" first.',7006)
log.log.AutosubmitCritical:  
[ERROR] None
 [CRITICAL] No configuration file(autosubmitrc) found in this filesystem. Please run "autosubmit configure" first. [eCode=7006]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html

```

I think everything is OK here, or is anything still pending?

Thanks!!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 21, 2022, 09:59

All are updated on the master branch

**Comment by kinow** [comment]
Thank you @dbeltrankyl !

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 16, 2023, 10:11

mentioned in issue digital-twins/de_340/project_management#118

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 19, 2023, 09:34

I added a line in the err and doc to indicate to init ssh-agent in case it isn't. 

I think we can close the issue
