### ISSUE TITLE
allow placeholders in standard configuration files

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#928]
In GitLab by @mandresm on Jan 10, 2023, 14:07

I am putting together a general workflow  with a `jobs.yaml`. This workflow needs to be able to run in LUMI and JUWELS. In my view, the user should need to change only variables relevant to the experiment in `expdef.yaml` but the rest of the files, I would like to provide them with a git project, and should need no change.

In this workflow I'm working on, some tasks require `LUMI-login/JUWELS-login` platforms and other tasks require `LUMI/JUWELS` (the 4 of them defined in `platforms.yaml`). I would like to be able to use place holders within the `jobs.yaml` (and other standard configuration files) so that I can make the platforms of each task in `jobs.yaml` depend on the platform I assign via `autosubmit create -H JUWELS/LUMI`. The syntax I'm thinking of would look like this:
```yaml
JOBS:
  REMOTE_SETUP:
    [ ... ]
    PLATFORM: "%DEFAULT.HPCARCH%-login"
  SIM:
    [ ... ]
    PLATFORM: "%DEFAULT.HPCARCH"
```

Would that be possible? are there other alternative solutions that allow for this level of modularity and automatization?

This is only one example of the need for being able to call variables from different configuration files, but we will likely see more examples as we try to generalize and automatize the workflow for DestinE, considering that it will run different models and in different platforms. Also, the more files the user has to change (specially when duplication of information takes place: here `autosubmit expid -H <HPC>` and the `PLATFORM: <HPC>/<HPC>-login` in the `jobs.yaml') the easier is to make mistakes.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 16, 2023, 10:11

mentioned in issue digital-twins/de_340/project_management#118

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 19, 2023, 10:00

I've started to work on this. 

I need to change the location of the function that parses these placeholders in the conf because right now it is only readable after the jobs had their parameters set. So it is not translated in the appropriated time for the jobs.conf.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 31, 2023, 16:42

Hello, 

I created a merge https://earth.bsc.es/gitlab/es/autosubmit/-/merge_requests/304 


I'll create a tag soon and upload it to the pip ( once I perform some tests since I merged two branches )

**Comment by kinow** [comment]
In GitLab by @mandresm on Feb 9, 2023, 15:36

Thanks @dbeltrankyl, how do I use the new feature? How can I write the following correctly to use this feature in the `platform.yml`?
```
JOBS:
  REMOTE_SETUP:
    [ ... ]
    PLATFORM: "<HPCARCH name>-login"
  SIM:
    [ ... ]
    PLATFORM: "<HPCARCH name>"
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 9, 2023, 16:30

Hello, you should use tag 4.0.0b4 , I fixed a potential bug on the autosubmitconfigparser (updated to 0.0.78)

```
JOBS:
  REMOTE_SETUP:
    [ ... ]
    PLATFORM: "%DEFAULT.HPCARCH%-login"
  SIM:
    [ ... ]
    PLATFORM: "%DEFAULT.HPCARCH%" # but not need as the default is already the hpcarch

```

**Comment by kinow** [comment]
In GitLab by @mandresm on Feb 10, 2023, 10:58

Hi @dbeltrankyl,

When I look at the `setup.py` in `v4.0.0b4` the version of the autosubmitconfigparser is `0.0.77`.

Any how, even if I fix that I get the following error:
```
Traceback (most recent call last):
  File "/home/ollie/mandresm/.conda/envs/autosubmit/lib/python3.7/site-packages/autosubmitconfigparser/config/configcommon.py", line 2369, in get_parser
    parser.data = parser.load(f)
  File "/home/ollie/mandresm/.local/lib/python3.7/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
  File "/home/ollie/mandresm/.local/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 731, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.scanner.ScannerError: while scanning for the next token
found character that cannot start any token
  in "/home/ollie/mandresm/as_experiments/a01v/proj/proj_ifs-fesom/conf/ifs-fesom/jobs.yml", line 15, column 15

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ollie/mandresm/.conda/envs/autosubmit/lib/python3.7/site-packages/autosubmitconfigparser/config/configcommon.py", line 1365, in reload
    self.parser_factory, custom_file))
  File "/home/ollie/mandresm/.conda/envs/autosubmit/lib/python3.7/site-packages/autosubmitconfigparser/config/configcommon.py", line 2377, in get_parser
    "{}\n This file and the correctness of its content are necessary.".format(str(exp)))
Exception: while scanning for the next token
found character that cannot start any token
  in "/home/ollie/mandresm/as_experiments/a01v/proj/proj_ifs-fesom/conf/ifs-fesom/jobs.yml", line 15, column 15
 This file and the correctness of its content are necessary.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ollie/mandresm/utilities/autosubmit/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/home/ollie/mandresm/utilities/autosubmit/autosubmit/autosubmit.py", line 627, in parse_args
    Autosubmit._init_logs(args, args.logconsole, args.logfile, expid)
  File "/home/ollie/mandresm/utilities/autosubmit/autosubmit/autosubmit.py", line 769, in _init_logs
    as_conf.reload(first_load=True)
  File "/home/ollie/mandresm/.conda/envs/autosubmit/lib/python3.7/site-packages/autosubmitconfigparser/config/configcommon.py", line 1370, in reload
    "{0}\nCheck configuration indentation or look for repeated parameter\nCheck if you have any uncommented value that should be commented".format(str(e)), 7014)
log.log.AutosubmitCritical:  
 [CRITICAL] while scanning for the next token
found character that cannot start any token
  in "/home/ollie/mandresm/as_experiments/a01v/proj/proj_ifs-fesom/conf/ifs-fesom/jobs.yml", line 15, column 15
 This file and the correctness of its content are necessary.
Check configuration indentation or look for repeated parameter
Check if you have any uncommented value that should be commented [eCode=7014]
```

I'm probably doing something stupid...?
```
  REMOTE_SETUP:
    FILE: templates/remote_setup.sh
    DEPENDENCIES: SYNCHRONIZE
    RUNNING: once
    PLATFORM: "%DEFAULT.HPCARCH%"
  INI:
    FILE: templates/ini.sh
    DEPENDENCIES: REMOTE_SETUP
    RUNNING: member
    PLATFORM: "%DEFAULT.HPCARCH%-login"
    #WALLCLOCK: '00:10'

```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 10, 2023, 11:00

Is the first time I see that error, could I have the full jobs.yml? not sure what is happening

**Comment by kinow** [comment]
In GitLab by @mandresm on Feb 10, 2023, 11:51

I found what it's happening... my bad. The first time I wun `create` I wrote `PLATFORM: %DEFAULT.HPCARCH%`, without `"`. I fixed adding the quotes, and try to create it again but the `job.yml` in the experiment was not updated and I was still getting the error of raumel parser complaining about the non-stringed `%`. Now it is solved. Then only thing remaining is that `v4.0.0b4` has the "wrong" version of autosubmitconfigparser.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 10, 2023, 11:57

> I fixed adding the quotes

Ah yes, that is what I thought but since the output, you have shown it had the " I was confused.

> Then only thing remaining is that `v4.0.0b4` has the "wrong" version of autosubmitconfigparser.

Yes, thanks for pointing it fixed in master I'll add a new tag later

**Comment by kinow** [comment]
In GitLab by @mandresm on Feb 10, 2023, 17:34

All is working correctly and as expected. Thanks a lot! Our jobs.yml in the ClimateDT workflow project can be now platform-agnostic :) Feel free to close the issue.
