### ISSUE TITLE
autosubmit stats error

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#93]
In GitLab by @fmassonn on Feb 5, 2016, 09:36

Hello,
I have this. I think it's related to the fact that I have quite a lot of short chunks (408).

autosubmit stats a03x

[CRITICAL] Unhandled exception on Autosubmit: width and height must each be below 32768
Traceback (most recent call last):
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 266, in parse_args
    return Autosubmit.statistics(args.expid, args.output)
  File "/shared/earth/python2.7/autosubmit/autosubmit.py", line 757, in statistics
    monitor_exp.generate_output_stats(expid, jobs.get_job_list(), file_format)
  File "/shared/earth/python2.7/autosubmit/monitor/monitor.py", line 198, in generate_output_stats
    self.create_bar_diagram(expid, joblist, output_file)
  File "/shared/earth/python2.7/autosubmit/monitor/monitor.py", line 302, in create_bar_diagram
    plt.savefig(output_file, bbox_extra_artists=lgd)
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 577, in savefig
    draw()   # need this if 'transparent=True' to reset colors
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 570, in draw
    get_current_fig_manager().canvas.draw()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 456, in draw
    self.renderer = self.get_renderer(cleared=True)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 473, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 94, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi, debug=False)
ValueError: width and height must each be below 32768

**Comment by kinow** [comment]
In GitLab by @jvegreg on Feb 15, 2016, 10:38

Can you give write permissions to the group, please?

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Jul 8, 2016, 17:13

Duplicated: #158 so I proceed to close it.
