### ISSUE TITLE
Coverage missing

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#933]
In GitLab by @dbeltrankyl on Jan 19, 2023, 09:54

Codacy-coverage has been missing since the departure of Javi(ex-bsc member).

We should add it again although it is not a priority related to #481

**Comment by kinow** [comment]
Had some 15 minutes before having to go to an appointment, so I synced my repo and started working on quick issues. I tried this one too, here's what I did:

```bash
conda create  -n autosubmit4 python=3.7
conda activate autosubmit4
pip install -e .
python3 -m 'nose' --exclude=regression  --verbosity=3 test/unit
```

All good so far. Then the commented parameters:

```bash
python3 -m 'nose' --exclude=regression  --verbosity=3 test/unit --with-coverage --cover-package=autosubmit --cover-inclusive --cover-xml --cover-xml-file=test/coverage.xml
```

That gave me an error similar to [this one](https://github.com/pytest-dev/pytest-mock/issues/133):

```bash
test_returned_packages_section_not_self_dependent (test.unit.test_wrappers.TestWrappers) ... ok

Traceback (most recent call last):
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/nose/__main__.py", line 8, in <module>
    run_exit()
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/nose/core.py", line 66, in run
    result.printErrors()
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/nose/result.py", line 110, in printErrors
    self.config.plugins.report(self.stream)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/nose/plugins/cover.py", line 183, in report
    self.coverInstance.stop()
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/coverage/control.py", line 788, in combine
    self.get_data()
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/coverage/control.py", line 817, in get_data
    if hasattr(self, "_collector") and self._collector.flush_data():
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/coverage/collector.py", line 499, in flush_data
    self.covdata.add_lines(self.mapped_file_dict(line_data))
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/coverage/sqldata.py", line 126, in _wrapped
    return method(self, *args, **kwargs)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/coverage/sqldata.py", line 490, in add_lines
    self._choose_lines_or_arcs(lines=True)
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/coverage/sqldata.py", line 556, in _choose_lines_or_arcs
    with self._connect() as con:
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/coverage/sqldata.py", line 342, in _connect
    self._open_db()
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/coverage/sqldata.py", line 285, in _open_db
    self._read_db()
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/coverage/sqldata.py", line 289, in _read_db
    with self._dbs[threading.get_ident()] as db:
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/coverage/sqldata.py", line 1118, in __enter__
    self.con.__enter__()
  File "/home/bdepaula/mambaforge/envs/autosubmit4/lib/python3.7/site-packages/mock/mock.py", line 657, in __getattr__
    raise AttributeError(name)
AttributeError: __enter__

```

So I think we need to fix this one before trying to upload it to Codacy.

**Comment by kinow** [comment]
Hmm, the linked merge request fixes the build.

In Codacy you have three options for log-in: GitHub, GitLab, and Google. GitHub asks you for permission to impersonate you (i.e. create pull requests, comments, commits, etc., as if it were you), which I try to avoid granting to other apps…

Then I logged in with the Google log-in. But now you must use one of these options to create an Organization in Codacy:

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/c2638063e767ae79d2bed1c1b860037d/image.png)

I picked GitLab, but that does not give you an option to use an internal GitLab. Instead it redirects you to https://gitlab.com/users/sign_in, which doesn't look correct since we don't have Autosubmit hosted in the public gitlab.com :confused:

**Comment by kinow** [comment]
Codecov is a known alternative to Codacy. But for hosted GitLab, they recommend a hosted instance of Codecov: https://about.codecov.io/pricing/

It's free, but I guess it'd require someone to install and maintain it too :disappointed: And like Codacy, it also requires you to give write permission to GitHub, if you choose that option for logging in.

**Comment by kinow** [comment]
Looks like GitLab CICD supports reporting coverage without the need of external services. I've pushed a commit to test it :drum: :fingers_crossed: 

https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 2, 2023, 16:01

Thanks for looking at it, 

Seems that the last comment would be the ideal solution let's hope it works

**Comment by kinow** [comment]
Thanks @dbeltrankyl !

It looks like it ran successfully... now... where are the coverage numbers? :laughing: 

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/c87180837e0c921266805a29827bd2f8/image.png)

**Comment by kinow** [comment]
I changed the label from todo (sorry, forgot to move to in progress) to testing. I think we just need to verify if a merge request that modifies Python source code in Autosubmit gets the coverage in the diff panel. :fingers_crossed: that it will do!

**Comment by kinow** [comment]
mentioned in commit 8888cd364bbbfffc981e3c3dd22a0633bf38bf3e

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 27, 2023, 21:05

So, if got it right, GitLab performs the coverage almost automatically right? You only need to point out the report in the `artifact` section.

**Comment by kinow** [comment]
Yes, it gives us the coverage report free of charge :slight_smile: 

There are two places that we did in the Autosubmit case to have coverage. First we added a regular expression that gives a coverage number in one of our jobs of our CICD pipeline: https://earth.bsc.es/gitlab/es/autosubmit/-/blob/master/.gitlab-ci.yml#L32

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/827b1e7870d078c17c9d7c3e6cd1ffad/image.png)

Then, given we had a command already producing coverage report compatible with Cobertura format (here: https://earth.bsc.es/gitlab/es/autosubmit/-/blob/master/.gitlab-ci.yml#L31), we just had to use the `artifact` as you pointed: https://earth.bsc.es/gitlab/es/autosubmit/-/blob/master/.gitlab-ci.yml#L36-40

This `artifact` with a coverage report value gets used by GitLab to produce the diff in the merge requests. It normally takes a few seconds (1 minute?) for the coverage to appear on the merge request. And it only works if GitLab has a feature enabled (in the past they had it disabled by default due to performance).

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/a93780fd0b14d9bd94fe9f3e3364c466/image.png)

p.s.: we can archive other things in our pipelines, like XML files, Autosubmit configuration files, screenshots, etc., https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 29, 2023, 18:45

Thanks for the detailed information @kinow 

While reading it, I think it's so important that it should be on a wiki page in the project.

**Comment by kinow** [comment]
>While reading it, I think it's so important that it should be on a wiki page in the project.

Good idea! Will try to create a Wiki page this week, so I don't forget it. Thanks!

**Comment by kinow** [comment]
Started with a copy of the previous comment as the initial content for the new wiki page: https://earth.bsc.es/gitlab/es/autosubmit/-/wikis/Code-coverage

Will update it as needed (all: feel free to edit it too :slight_smile: )
