### ISSUE TITLE
migrate error:  [CRITICAL] None 'ascii' codec can't decode byte 0xc2 in position 173: ordinal not in range(128)

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#969]
In GitLab by @vsicardi on Mar 8, 2023, 13:20

Hello @dbeltrankyl and @kinow,

I am sorry, but I have a new error when migrating another experiment of mine from **cns60 to bsc32.**

The exp is **a5hn**  and my res user is **cns60057**.

**Autosubmit version 3.14.0**

Here the error I get: 

```
autosubmit migrate a5hn -o 
Autosubmit is running with 3.14.0

Checking configuration files...
expdef_a5hn.conf OK
platforms_a5hn.conf OK
jobs_a5hn.conf OK
wrappers OK
autosubmit_a5hn.conf OK
Configuration files OK

Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Checking the connection to all platforms in use
[local] Correct user privileges for host localhost
[local] Connection successful to host localhost
[nord3v2] Correct user privileges for host nord4.bsc.es
[nord3v2] Connection successful to host nord4.bsc.es
[transfer_node] Correct user privileges for host mn-dt-cns60
[transfer_node] Connection successful to host mn-dt-cns60
[marenostrum4] Correct user privileges for host mn1.bsc.es
[marenostrum4] Connection successful to host mn1.bsc.es
Migrating experiment a5hn
Checking remote platforms
Checking [nord3v2] from platforms configuration...
Checking [marenostrum4] from platforms configuration...
Checking [transfer_node] from platforms configuration...
[OPTIONAL] PROJECT_TO directive not found. The directive PROJECT will remain unchanged
[OPTIONAL] HOST_TO directive not found. The directive HOST will remain unchanged
Files/dirs on nord3v2 have been successfully offered
Project in platform configuration file successfully updated to cns60
[ERROR] Trace: 'ascii' codec can't decode byte 0xc2 in position 173: ordinal not in range(128)
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.14.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.14.0-py2.7.egg/EGG-INFO/scripts/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/shared/earth/software/autosubmit/3.14.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.14.0-py2.7.egg/autosubmit/autosubmit.py", line 633, in parse_args
    return Autosubmit.migrate(args.expid, args.offer, args.pickup, args.onlyremote)
  File "/shared/earth/software/autosubmit/3.14.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.14.0-py2.7.egg/autosubmit/autosubmit.py", line 2892, in migrate
    platform, as_conf.get_migrate_user_to(platform))
  File "/shared/earth/software/autosubmit/3.14.0-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.14.0-py2.7.egg/autosubmit/config/config_common.py", line 415, in set_new_user
    r'[^#]\bUSER\b =.*', contentToMod).group(0)[1:], "USER = " + new_user)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 173: ordinal not in range(128)
 [CRITICAL] None'ascii' codec can't decode byte 0xc2 in position 173: ordinal not in range(128)
Unhandled error: If you see this message, please report it in Autosubmit's GitLab project


```

Any help would be highly appreciated.

Thanks

FIY @eferre1

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 8, 2023, 13:25

Hello, 

This seems to be an issue with the locale setting of the machine, this can happen depending on your local terminal settings ( usually, this happens when you connect  to the office from a MAC)  

```
dbeltran@ bscearth357:~> locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```

If your `locale` is not similar to mine, please perform:

```
 export LANG="en_GB.UTF-8"
 export LC_ALL="en_GB.UTF-8"

```

And then use autosubmit

**Comment by kinow** [comment]
In GitLab by @vsicardi on Mar 8, 2023, 14:05

Thank you @dbeltrankyl,

I have to admit I have no idea of what are you speaking about. But I trust, a lot.

my locale is:

```
locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```

I performed 
```
 export LANG="en_GB.UTF-8"
 export LC_ALL="en_GB.UTF-8"
```

unfortunately, I get the same error.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 9, 2023, 09:13

Hello, 

These kind of errors: 

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 173: ordinal not in range(128)
 [CRITICAL] None'ascii' codec can't decode byte 0xc2 in position 173: ordinal not in range(128)
Unhandled error: If you see this message, please report it in Autosubmit's GitLab project
```

Are always related to the encoding. In 3.14.0, we implemented some code always to enforce utf8, but it doesn't work properly in some machines like autosubmit01. In autosubmit 4 this code is improved to make it work on all machines, but the migrate command won't work with that version. 


The last locale error was discussed on https://earth.bsc.es/gitlab/es/auto-monarch/-/issues/519#note_201832.

I quote the solution found on there for its case, if it helps:


> thanks! as mentioned in https://stackoverflow.com/questions/7165108/in-os-x-lion-lang-is-not-set-to-utf-8-how-to-fix-it, adding to `~/.profile` :

```
export LC_ALL=en_GB.UTF-8  
export LANG=en_GB.UTF-8
```

> solves the issue (after running source ~/.profile)!


It seems it didn't work for you, so maybe there is a non-utf char in the configuration files. Could you look at all USER or/and USER_TO variables and rewrite them? Without copying & paste

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 9, 2023, 10:13

@vsicardi as @dbeltrankyl says, we think that there could be something strange in the USER and USER_TO lines. Could you rewrite them by hand and see if that solves the issue?

**Comment by kinow** [comment]
In GitLab by @vsicardi on Mar 9, 2023, 13:23

Hi @mcastril and @dbeltrankyl,

Thank you so much for the clarification. I was still trying to figure out what to do.

I correctly modified the platform.conf and now it is working.

I am sorry for having created some noise.

Thank you

**Comment by kinow** [comment]
In GitLab by @mcastril on Mar 9, 2023, 19:48

No problem, that's why we have issues. Now it's tracked for the next time it happens :slight_smile:

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 21, 2023, 11:29

mentioned in commit c87d5422d074213894ea142166dba46a708c7bed
