### ISSUE TITLE
[documentation] Missing error codes, e.g. 3000

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#974]
( This is a template for bug reports. Please fill in the relevant information and delete the rest. )

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

`master`

### Expid affected(If applicable)

NA

### Which task has issues? Where is the log(If applicable)

NA

### Summary

I was testing the LUMI VM for ClimateDT, and got an error `3000`. I then went to our [Error Codes](https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html) page in our docs, but it didn't have anything about error codes like `3000`? Is that intentional, or maybe it's explained somewhere else?

### Steps to reproduce

Try to connect to an invalid/broken remote platform.

### What is the current bug behavior?

An error code missing from our error codes page.

### What is the expected correct behavior?

An error code that exists in our error codes page.

### Relevant logs and/or screenshots(if applicable)

```bash
...
...
Checking the connection to all platforms in use
[WARNING] [LUMI-STANDARD] Connection failed to host *******[eCode=3000]
Traceback (most recent call last):
  File "/appl/AS/4.0.7/lib64/python3.9/site-packages/autosubmit/autosubmit.py", line 1873, in run_experiment
    Autosubmit.restore_platforms(platforms_to_test)
  File "/appl/AS/4.0.7/lib64/python3.9/site-packages/autosubmit/autosubmit.py", line 2274, in restore_platforms
    raise AutosubmitCritical(
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/AS/4.0.7/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/appl/AS/4.0.7/lib64/python3.9/site-packages/autosubmit/autosubmit.py", line 629, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive, args.update_version, args.start_time,
  File "/appl/AS/4.0.7/lib64/python3.9/site-packages/autosubmit/autosubmit.py", line 2217, in run_experiment
    raise AutosubmitCritical(e.message, e.code, e.trace)
log.log.AutosubmitCritical:  
[ERROR] None
[ERROR] Trace: 
[LUMI-STANDARD] has configuration issues.
...
...
```

### Any other relevant information(if applicable)

()

**Comment by kinow** [comment]
created branch [`974-missing-error-codes-e-g-3000`](/gitlab/es/autosubmit/-/compare/master...974-missing-error-codes-e-g-3000) to address this issue

**Comment by kinow** [comment]
mentioned in commit ceaffe8cbfa0dd8fb716dcd15958ce6405e870a9
