### ISSUE TITLE
No such file or directory: '.../proj.yaml'

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#984]
In GitLab by @orioltinto on Mar 21, 2023, 18:03

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

I tried to use the latest version (4.0.73) with an existing experiment created with (4.0.71) and it fails at fetching the project file specified in expdef. Also, I tried to create a new experiment from scratch to see if some variable name changed and I didn't get any configuration file. Is that an expected change?

### Steps to reproduce

autosubmit refresh axxx -mc -jc

### What is the current bug behavior?

```
[ERROR] Trace: [Errno 2] No such file or directory: 'conf/real-from-dwd-ana/proj.yaml'
 [CRITICAL]   Download failed [eCode=7064]
```
### What is the expected correct behavior?

Updating the file properly. It works correctly with previous version.

### Relevant logs and/or screenshots(if applicable)

Full log:
```
autosubmit refresh a00d -v -mc -jc
Autosubmit is running with 4.0.73

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Making a backup of your current proj folder at /home/o/Oriol.Tinto/autosubmit/a00d/proj_1679418006
Cloning real-from-ideal git@gitlab.physik.uni-muenchen.de:w2w/autosubmit-icon-today.git into /home/o/Oriol.Tinto/autosubmit/a00d/proj
Cloning into 'autosubmit-icon-today'...
X11 forwarding request failed on channel 0
remote: Enumerating objects: 852, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 852 (delta 27), reused 56 (delta 20), pack-reused 779
Receiving objects: 100% (852/852), 112.80 KiB | 577.00 KiB/s, done.
Resolving deltas: 100% (421/421), done.
Removing backup...
Project folder updated
Traceback (most recent call last):
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmit/autosubmit.py", line 3850, in refresh
    Autosubmit._create_project_associated_conf(
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmit/autosubmit.py", line 4338, in _create_project_associated_conf
    shutil.copyfile(os.path.join(as_conf.get_project_dir(), as_conf.get_file_project_conf()),
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'conf/real-from-dwd-ana/proj.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmit/autosubmit.py", line 695, in parse_args
    return Autosubmit.refresh(args.expid, args.model_conf, args.jobs_conf)
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmit/autosubmit.py", line 3855, in refresh
    raise AutosubmitCritical("  Download failed", 7064, str(e))
log.log.AutosubmitCritical:  
[ERROR] Trace: [Errno 2] No such file or directory: 'conf/real-from-dwd-ana/proj.yaml'
 [CRITICAL]   Download failed [eCode=7064]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

()

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 22, 2023, 08:49

Hello @orioltinto, 

Could I have a look into the conf files? 

> Also, I tried to create a new experiment from scratch to see if some variable name changed and I didn't get any configuration file. Is that an expected change?

No, with -min you should have a minimal.yml, and with -dm or without nothing you should have the default files.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 22, 2023, 08:55

Ah, I see that youre using the flags -mc and -jc. These flags are soon to be deprecated because now Autosubmit is able to load directly the configuration without copy it to $expid/conf through Custom_config.

Could you use:

```
default:
  Custom_config:
    Pre:
     - "%PROJDIR%/conf/real-from-dwd-ana/proj.yaml
     - "%PROJDIR%/conf/real-from-dwd-ana/jobs.yaml"
```

instead of the Jobs/proj_files directive? Also the refresh flags are no need anymore

(Not sure if the jobs path is correct, put the correct path or you can just load the folder)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 22, 2023, 08:59

info at https://earth.bsc.es/gitlab/es/autosubmit/-/issues/958#note_203164

**Comment by kinow** [comment]
In GitLab by @orioltinto on Mar 22, 2023, 10:42

Hi @dbeltrankyl,


I tried this:
```
 autosubmit expid  -H LRZ -d "Trying new experiment with 4.0.73"
```
and I got an experiment without any configuration file in it.


About the default.custom_config thing, where exactly should I put it?

Right now in my **expdef** I have:

```yaml
project_files:
  FILE_PROJECT_CONF: 'conf/real-from-dwd-ana/proj.yaml'
  FILE_JOBS_CONF: 'conf/real-from-dwd-ana/jobs.yaml'
  JOB_SCRIPTS_TYPE: 'yaml'
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 22, 2023, 11:08

> `autosubmit expid -H LRZ -d "Trying new experiment with 4.0.73"`

I'm not sure what happened. I got the appropriate files using the last tag, maybe the current pip version. I'll update that version soon after some merge requests are merged. Could you try for now with 

`autosubmit expid -H LRZ -dm -d "Trying new experiment with 4.0.73"` ? 

In any case, the $expid/conf files can be the same as your previous experiment. you can copy them from there until is solved. 

> About the default.custom_config thing, where exactly should I put it?

You can put it anywhere inside $expid/conf. The only requisite is that it must be a yml file. 

If I keep the older configuration structure in mind, the appropriate place would be `$expid/conf/expdef.yml`. 

So you expdef will look similar to: 

```yaml
DeFault:
  EXPID: "TO_FILL"
  HPCARCH: "LRZ"
  CUSTOM_CONFIG: 
      PRE: 
       - "%PROJDIR%/conf/real-from-dwd-ana"
       - # you can add more files or folders.
      POST:
       - "~/user_platform_stuff.yml" 
experiment:
  DATELIST: 20220401
  MEMBERS: "fc0"
  CHUNKSIZEUNIT: month
  CHUNKSIZE: 4
  NUMCHUNKS: 2
  CHUNKINI: ''
  CALENDAR: standard
project:
  PROJECT_TYPE: git
  PROJECT_DESTINATION: 'TO_FILL'
git:
  PROJECT_ORIGIN: ''
  PROJECT_BRANCH: ''
  PROJECT_COMMIT: ''
  PROJECT_SUBMODULES: ''
  FETCH_SINGLE_BRANCH: True
svn:
  PROJECT_URL: ''
  PROJECT_REVISION: ''
local:
  PROJECT_PATH: ''

```

So when you perform an "autosubmit refresh", autosubmit will look to the files in this order: 

* %PROJDIR%/conf/real-from-dwd-ana/jobs.yml , %PROJDIR%/conf/real-from-dwd-ana/proj.yml 
* $expid/conf/expdef.yml , others files that you may have 
* $HOME/user_platform_stuff.yml # This file should have things like PLATFORMS.MARENOSTRUM.USER

Then what would be left is to have the parameters autosubmit.yml and platform.yml somewhere in your $expid/conf or in your %PROJDIR%/conf/real-from-dwd-ana folder. 

Finally, the experiment structure would look similar to the following:

```sh
ls $expid/conf

expid.yml autosubmit.yml

ls $expid/proj/proj_name/conf/real-from-dwd-ana

jobs.yml proj.yml 
```

Note: proj.yml data can now be divided into multiple files, so you don't have to use "proj" as a name. You could have multiple folders or files and load only what you wish from the $expid/conf using the custom_config directive.

Note 2: $expid/conf has priority over PRE , whatever is defined there will overwrite

Example. Let's say you have in the %PROJDIR%/conf/real-from-dwd-ana/jobs.yml

%PROJDIR%/conf/real-from-dwd-ana/jobs.yml
```yaml
JOBS:
 SETUP:
  FILE: file1.sh
  RUNNING: chunk
```

You could have another file in your $expid/conf, let's $expid/conf/experiment_specific_jobs.yml, that overwrites the %PROJDIR%/conf/real-from-dwd-ana/jobs.yml parameter or adds new jobs. 

$expid/conf/experiment_specific_jobs.yml
```yaml
JOBS:
 SETUP:
  RUNNING: member
  PLATFORM: LOCAL
 SIM:
  FILE: file2.sh 
```

Final memory values would be for autosubmit: 

```yaml
JOBS:
 SETUP:
  FILE: file1.sh
  RUNNING: member
  PLATFORM: LOCAL
 SIM:
  FILE: file2.sh 
```

Note 3: if you have a $expid/conf/minimal.yml , the previous doesn't apply to this file as is an special file to setup this distributed conf

**Comment by kinow** [comment]
In GitLab by @orioltinto on Mar 22, 2023, 11:57

If I try to get rid of :

```yaml
project_files:
  FILE_PROJECT_CONF: 'conf/real-from-dwd-ana/proj.yaml'
  FILE_JOBS_CONF: 'conf/real-from-dwd-ana/jobs.yaml'
  JOB_SCRIPTS_TYPE: 'yaml'

```

and add:
```yaml
DeFault:
  EXPID: "TO_FILL"
  HPCARCH: "LRZ"
  CUSTOM_CONFIG: 
      PRE: 
       - "%PROJDIR%/conf/real-from-dwd-ana"
       - # you can add more files or folders.
      POST:
       - "~/user_platform_stuff.yml" 
```

then I get:


```
Traceback (most recent call last):
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmit/autosubmit.py", line 636, in parse_args
    Autosubmit._init_logs(args, args.logconsole, args.logfile, expid)
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmit/autosubmit.py", line 777, in _init_logs
    as_conf.reload(force_load=True)
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmitconfigparser/config/configcommon.py", line 1328, in reload
    starter_conf = self.unify_conf(starter_conf, self.load_config_file(starter_conf, Path(filename)))
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmitconfigparser/config/configcommon.py", line 571, in load_config_file
    return self.unify_conf(current_folder_data,self.deep_normalize(new_file.data))
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmitconfigparser/config/configcommon.py", line 639, in unify_conf
    self.dynamic_variables = list(set(self.dynamic_variables))
TypeError: unhashable type: 'list'
 [CRITICAL] Noneunhashable type: 'list'
Unhandled error: If you see this message, please report it in Autosubmit's GitLab project

```

I also tried to start from scratch using a minimal configuration file like:


```yaml

CONFIG:
  AUTOSUBMIT_VERSION: "4.0.73"
  TOTALJOBS: 20
  MAXWAITINGJOBS: 20
DEFAULT:
  EXPID: "a00g"
  HPCARCH: "LMU"
  #hint: use %PROJDIR% to point to the project folder (where the project is cloned)
  CUSTOM_CONFIG:
     PRE:
      - "%PROJDIR%/conf/real-from-dwd-ana"
#      - # you can add more files or folders.
     POST:
      - "~/autosubmit/platforms.yml"

PROJECT:
  PROJECT_TYPE: "git"
  PROJECT_DESTINATION: "git_project"
GIT:
  PROJECT_ORIGIN: "https://gitlab.physik.uni-muenchen.de/w2w/autosubmit-icon-today.git"
  PROJECT_BRANCH: "minimal-configuration"
  PROJECT_COMMIT: ""
  PROJECT_SUBMODULES: ""
  FETCH_SINGLE_BRANCH: True                          
```
But it complains about the Main platform being undefined, which I assume means that it is not actually getting the platforms file.
```log
 [CRITICAL] On Configuration files:
Critical Issues on [Expdef] config file:
[Default] Main platform is not defined! check if [HPCARCH = LMU] has any typo
 [eCode=7014]

```


Do you have a working project that uses the minimal configuration so I can take a look?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 22, 2023, 12:20

```
Traceback (most recent call last):
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmit/autosubmit.py", line 636, in parse_args
    Autosubmit._init_logs(args, args.logconsole, args.logfile, expid)
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmit/autosubmit.py", line 777, in _init_logs
    as_conf.reload(force_load=True)
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmitconfigparser/config/configcommon.py", line 1328, in reload
    starter_conf = self.unify_conf(starter_conf, self.load_config_file(starter_conf, Path(filename)))
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmitconfigparser/config/configcommon.py", line 571, in load_config_file
    return self.unify_conf(current_folder_data,self.deep_normalize(new_file.data))
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmitconfigparser/config/configcommon.py", line 639, in unify_conf
    self.dynamic_variables = list(set(self.dynamic_variables))
TypeError: unhashable type: 'list'
 [CRITICAL] Noneunhashable type: 'list'
Unhandled error: If you see this message, please report it in Autosubmit's GitLab project

```

I have no issues with the last tag. Soon it will be updated again, but I updated the pip with the current master branch(4.0.74) to see if something where missing. 

I check if the example on rst still works, and it works: 

https://autosubmit.readthedocs.io/en/master/userguide/set_and_share_the_configuration/index.html#advanced-configuration-full-dummy-example-reproducible


This is pretty simple tho, just with the minimal.yml setup, 

perform autosubmit create and it should work,   

All the data is in the "%PROJDIR%/as_conf" except for the minimal.yml, 

It is basically a dummy but with the configuration in %PROJDIR%/as_conf instead of in $expid/conf

**Comment by kinow** [comment]
In GitLab by @orioltinto on Mar 22, 2023, 12:38

I'm just trying to reproduce the minimal example with 4.0.73 and this happens:

```
autosubmit expid -min -repo https://earth.bsc.es/gitlab/ces/auto-advanced_config_example -b main -conf as_conf -d "Test minimal conf"
Autosubmit is running with 4.0.73
The new experiment "a00i" has been registered.
Generating folder structure...
Generating config files...
Experiment a00i created
```

```
autosubmit refresh a00i
[ERROR] Trace: 'str' object has no attribute 'items'
Traceback (most recent call last):
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/bin/autosubmit", line 36, in main
    Autosubmit.parse_args()
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmit/autosubmit.py", line 636, in parse_args
    Autosubmit._init_logs(args, args.logconsole, args.logfile, expid)
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmit/autosubmit.py", line 777, in _init_logs
    as_conf.reload(force_load=True)
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmitconfigparser/config/configcommon.py", line 1328, in reload
    starter_conf = self.unify_conf(starter_conf, self.load_config_file(starter_conf, Path(filename)))
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmitconfigparser/config/configcommon.py", line 570, in load_config_file
    new_file.data["DEFAULT"]["CUSTOM_CONFIG"] = self.convert_list_to_string(new_file.data["DEFAULT"]["CUSTOM_CONFIG"])
  File "/project/meteo/work/Oriol.Tinto/autosubmit/4.0.73/venv/lib/python3.8/site-packages/autosubmitconfigparser/config/configcommon.py", line 551, in convert_list_to_string
    for key, val in data.items():
AttributeError: 'str' object has no attribute 'items'
 [CRITICAL] None'str' object has no attribute 'items'
Unhandled error: If you see this message, please report it in Autosubmit's GitLab project
```

I tried with a newer version of python(3.10) and 4.0.74 and it seems to work.
I haven't checked whether the issue is with 73 or with python 3.8

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 22, 2023, 13:11

Should be an issue with 4.0.73. Apologies for that 

Python versions that work for sure: 

* 3.7.3 ( bsc workstations )
* 3.9 ( new hub workstations ) 

I'm using 3.9 for all development, so is the safest to use

**Comment by kinow** [comment]
In GitLab by @orioltinto on Mar 22, 2023, 15:37

Hi again,
I've been trying to set up the configuration using the minimal.yml thing and I'm having some troubles.

If I follow the [example](https://autosubmit.readthedocs.io/en/master/userguide/set_and_share_the_configuration/index.html#advanced-configuration-full-dummy-example-reproducible) and do soemthing like:

```
CONFIG:
  AUTOSUBMIT_VERSION: "4.0.74"
  TOTALJOBS: 20
  MAXWAITINGJOBS: 20
DEFAULT:
  EXPID: "a00g"
  HPCARCH: "local"
  #hint: use %PROJDIR% to point to the project folder (where the project is cloned)
  CUSTOM_CONFIG: "%PROJDIR%/conf/common/"
```

All the files inside conf/common/ are loaded.

Then I tried to use the PRE, POST thing because I would like to split the configuration files in different folders, and it seems that I can't point to folders anymore but I need to put the complete list of files to make it work. For example:
```yaml
  CUSTOM_CONFIG:
    PRE:
      - "%PROJDIR%/conf/common/expdef.yml"
      - "%PROJDIR%/conf/real-from-ideal/jobs.yml"
      - "%PROJDIR%/conf/real-from-ideal/proj.yml"
    POST:
      - "/home/o/Oriol.Tinto/autosubmit/platforms.yml"
```


Is it intentional or is there a way of pointing to a single folder using the PRE POST thing?

By the way, in my case it didn't expand the HOME (~) symbol.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 22, 2023, 16:16

mentioned in commit ces/autosubmit4-config-parser@c64133da9706ba52f3a123ed0c7aeb25b9cab2b5

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 22, 2023, 16:18

Hmm, not intended. Thanks for telling me 

It was not accumulated in the unified config when more than one was prompted. Fixed in the commit mentioned. 

> By the way, in my case it didn't expand the HOME (\~) symbol.

I think this never worked, added, and tested.

I'll update a new tag that points to the new autosubmitconfig version.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 22, 2023, 16:25

Added 4.0.75 //  v4.0.0b12

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 27, 2023, 09:21

Fixed in the commented tag, closing this issue
